# Physical states, Qualities, Spatial relations, Weather, Difficulty, Manners
# (romaji, hiragana, katakana, kanji, meaning, type, topic)
DATA = [
    # J
    ("jama na", "じゃまな", "ジャマナ", "邪魔な", "hindering / in the way / obtrusive", "na-adjective", "Conditions & States"),
    ("jimi na", "じみな", "ジミナ", "地味な", "plain / sober / understated in design", "na-adjective", "Appearance & Style"),
    ("jinjou na", "じんじょうな", "ジンジョウナ", "尋常な", "ordinary / normal / customary", "na-adjective", "Conditions & States"),
    ("jinzou no", "じんぞうの", "ジンゾウノ", "人造の", "artificial / synthetic", "na-adjective", "Conditions & States"),
    ("jishin-tappuri na", "じしんたっぷりの", "ジシンタップリノ", "自信たっぷりの", "full of self-confidence", "na-adjective", "Character & Personality"),
    ("jisshitsu-teki na", "じっしつてきな", "ジッシツテキナ", "実質的な", "substantial / effective / real", "na-adjective", "Work & Study"),
    ("jitsuyo-teki na", "じつようてきな", "ジツヨウテキナ", "実用的な", "practical / pragmatic / functional", "na-adjective", "Praise & Quality"),
    ("jitsuryoku no aru", "じつりょくのある", "ジツリョクノアル", "実力のある", "competent / truly capable", "na-adjective", "Character & Personality"),
    ("jiyuu na", "じゆうな", "ジユウナ", "自由な", "free / unrestricted / unbound", "na-adjective", "Conditions & States"),
    ("joubu na", "じょうぶな", "ジョウブナ", "丈夫な", "durable / robust / sturdy fabric", "na-adjective", "Appearance & Quality"),
    ("joudan no you na", "じょうだんのような", "ジョウダンノヨウナ", "冗談のような", "almost like a joke / unbelievable", "na-adjective", "Conditions & States"),
    ("jouhin na", "じょうひんな", "ジョウヒンナ", "上品な", "refined / elegant / graceful manners", "na-adjective", "Appearance & Style"),
    ("jounetsu-teki na", "じょうねつてきな", "ジョウネツテキナ", "情熱的な", "passionate / ardent / zealous", "na-adjective", "Character & Personality"),
    ("joushikiteki na", "じょうしきてきな", "ジョウシキテキナ", "常識的な", "sensible / reasonable", "na-adjective", "Character & Personality"),
    ("joutou na", "じょうとうな", "ジョウトウナ", "上等な", "top-quality / superior / choice", "na-adjective", "Praise & Quality"),
    ("juubun na", "じゅうぶんな", "ジュウブンナ", "十分な", "ample / plenty / sufficient", "na-adjective", "Degree & Intensity"),
    ("juudai na", "じゅうだいな", "ジュウダイナ", "重大な", "weighty / momentous / grave", "na-adjective", "Degree & Intensity"),
    ("juunai na", "じゅうような", "ジュウヨウナ", "重要な", "crucial / paramount / important", "na-adjective", "Praise & Quality"),
    ("juunan na", "じゅうなんな", "ジュウナンナ", "柔軟な", "flexible / adaptable / supple", "na-adjective", "Character & Personality"),
    ("junpui na", "じゅんすいな", "ジュンスイナ", "純粋な", "pure / genuine / uncontaminated", "na-adjective", "Character & Personality"),
    # K
    ("kaiteki na", "かいてきな", "カイテキナ", "快適な", "comfortable / pleasant living", "na-adjective", "Conditions & States"),
    ("kakaku no tegoro na", "てごろな", "テゴロナ", "手頃な", "affordable / reasonable price", "na-adjective", "Shopping & Money"),
    ("kakkoii", "かっこいい", "カッコイイ", "格好いい", "cool / handsome / stylish", "i-adjective", "Appearance & Style"),
    ("kakkoku no", "かっこの", "カッコノ", "格好の", "ideal / well-suited target", "na-adjective", "Conditions & States"),
    ("kakko-warui", "かっこわるい", "カッコワルイ", "格好悪い", "clunky / uncool / awkward-looking", "i-adjective", "Appearance & Style"),
    ("kakunou shita", "かくにんした", "カクニンシタ", "確認した", "verified / confirmed", "na-adjective", "Work & Study"),
    ("kakushin no aru", "かくしんのある", "カクシンノアル", "確信のある", "confident / convinced of outcome", "na-adjective", "Feelings & Mood"),
    ("kanari no", "かなりの", "カナリノ", "可成りの", "considerable / substantial in scale", "na-adjective", "Degree & Intensity"),
    ("kanashii", "かなしい", "カナシイ", "悲しい", "sad / sorrowful / heart-breaking", "i-adjective", "Feelings & Mood"),
    ("kanben na", "かんべんな", "カンベンナ", "簡便な", "handy / simple to operate", "na-adjective", "Difficulty & Ease"),
    ("kandou-teki na", "かんどうてきな", "カンドウテキナ", "感動的な", "moving / deeply touching / inspiring", "na-adjective", "Feelings & Mood"),
    ("kan'i na", "かんいな", "カンイナ", "簡易な", "simple / streamlined / quick", "na-adjective", "Difficulty & Ease"),
    ("kanketsu na", "かんけつな", "カンケツナ", "簡潔な", "concise / succinct / compact", "na-adjective", "Character & Clarity"),
    ("kanpeki na", "かんぺきな", "カンペキナ", "完璧な", "flawless / immaculate / perfect", "na-adjective", "Praise & Quality"),
    ("kanran na", "かんらんな", "カンランナ", "寛容な", "tolerant / generous-hearted", "na-adjective", "Character & Personality"),
    ("kanryo shita", "かんりょうした", "カンリョウシタ", "完了した", "completed / finalized", "na-adjective", "Work & Study"),
    ("kantou shita", "かんたんした", "カンタンシタ", "感服した", "impressed with admiration", "na-adjective", "Feelings & Mood"),
    ("kantan na", "かんたんな", "カンタンナ", "簡単な", "easy / straightforward / simple", "na-adjective", "Difficulty & Ease"),
    ("kanyou na", "かんような", "カンヨウナ", "肝要な", "vital / of primary importance", "na-adjective", "Praise & Quality"),
    ("karai", "からい", "カライ", "辛い", "spicy hot / salty / harsh grading", "i-adjective", "Food & Taste"),
    ("karakuchi no", "からくちの", "カラクチノ", "辛口の", "dry sake / scathing critique", "na-adjective", "Food & Taste"),
    ("karamatta", "からまった", "カラマッタ", "絡まった", "entangled / twisted together", "na-adjective", "Conditions & States"),
    ("karappo no", "からっぽの", "カラッポノ", "空っぽの", "completely empty container", "na-adjective", "Conditions & States"),
    ("karui", "かるい", "カルイ", "軽い", "light in weight / nimble / frivolous", "i-adjective", "Size & Shape"),
    ("kashikoi", "かしこい", "カシコイ", "賢い", "wise / intelligent / shrewd", "i-adjective", "Character & Personality"),
    ("kasuka na", "かすかな", "カスカナ", "微かな", "faint aroma / slight murmur", "na-adjective", "Character & Clarity"),
    ("katachi no ii", "かたちのいい", "カタチノイイ", "形のいい", "well-shaped / shapely", "i-adjective", "Appearance & Style"),
    ("katai", "かたい", "カタイ", "硬い", "hard stone / stiff posture", "i-adjective", "Appearance & Quality"),
    ("katai-firm", "かたい", "カタイ", "固い", "firm handshake / solid resolve", "i-adjective", "Character & Personality"),
    ("katai-strict", "かたい", "カタイ", "堅い", "steadfast / upright character", "i-adjective", "Character & Personality"),
    ("kawaii", "かわいい", "カワイイ", "可愛い", "cute / adorable / sweet", "i-adjective", "Appearance & Style"),
    ("kawaisou na", "かわいそうな", "カワイソウナ", "可哀想な", "pitiable / poor thing / pathetic", "na-adjective", "Feelings & Mood"),
    ("kawaratta", "かわった", "カワッタ", "変わった", "peculiar / unique / eccentric", "na-adjective", "Character & Personality"),
    ("kawaita", "かわいた", "カワイタ", "乾いた", "dry dry sand / parched throat", "na-adjective", "Weather & Climate"),
    ("kayowai", "かよわい", "カヨワイ", "弱弱しい", "delicate / frail / frail-looking", "i-adjective", "Body & Health"),
    ("kazan no chikai", "かざんのちかい", "カザンノチカイ", "火山の近い", "close to active volcano", "i-adjective", "Places & Spatial"),
    ("keikai na", "けいかいな", "ケイカイナ", "軽快な", "light-hearted / brisk rhythm", "na-adjective", "Appearance & Mood"),
    ("keiken-yutaka na", "けいけんゆたかな", "ケイケンユタカナ", "経験豊かな", "rich in experience / veteran", "na-adjective", "Character & Personality"),
    ("keikou no aru", "けいこうのある", "ケイコウノアル", "蛍光のある", "fluorescent / glowing", "na-adjective", "Appearance & Style"),
    ("keitai ni tekishita", "けいたいに適した", "ケイタイニテキシタ", "携帯に適した", "portable / compact to carry", "na-adjective", "Conditions & States"),
    ("kekkou na", "けっこうな", "ケッコウナ", "結構な", "splendid / sufficient / no thank you", "na-adjective", "Praise & Quality"),
    ("kemutai", "けむたい", "ケムタイ", "煙たい", "smoky / suffocating presence", "i-adjective", "Weather & Senses"),
    ("kenbannin no", "けんぜんな", "ケンゼンナ", "健全な", "sound in mind and body / wholesome", "na-adjective", "Safety & Health"),
    ("kenkyo na", "けんきょな", "ケンキョナ", "謙虚な", "humble / modest in demeanor", "na-adjective", "Character & Personality"),
    ("kenkou na", "けんこうな", "ケンコウナ", "健康な", "healthy / in fine physical trim", "na-adjective", "Safety & Health"),
    ("kennon na", "けんのんな", "ケンノンナ", "剣呑な", "dangerous / risky / hazardous", "na-adjective", "Safety & Health"),
    ("kewashii", "けわしい", "ケワシイ", "険しい", "steep precipice / stern look", "i-adjective", "Places & Spatial"),
    ("kibou ni michita", "きぼうにみちた", "キボウニミチタ", "希望に満ちた", "full of radiant hope", "na-adjective", "Feelings & Mood"),
    ("kibishii", "きびしい", "キビシイ", "厳しい", "strict teacher / harsh winter weather", "i-adjective", "Character & Personality"),
    ("kiken na", "きけんな", "キケンナ", "危険な", "hazardous / perilous / dangerous", "na-adjective", "Safety & Health"),
    ("kikinzoku no", "ききんぞくの", "キキンゾクノ", "貴金属の", "precious metallic", "na-adjective", "Conditions & States"),
    ("kimagure na", "きまぐれな", "キマグレナ", "気まぐれな", "capricious / whimsical / fickle", "na-adjective", "Character & Personality"),
    ("kimazu", "きまずい", "キマズイ", "気まずい", "awkward / tense atmosphere", "i-adjective", "Feelings & Mood"),
    ("kime-komaka na", "きめこまかな", "キメコマカナ", "きめ細やかな", "fine-grained / attentive service", "na-adjective", "Praise & Quality"),
    ("kimi-warui", "きみわるい", "キミワルイ", "気味悪い", "creepy / gross / sinister", "i-adjective", "Feelings & Mood"),
    ("kin'iro no", "きんいろの", "キンイロノ", "金色の", "golden / gilded hue", "na-adjective", "Colors & Styles"),
    ("kinou-teki na", "きのうてきな", "キノウテキナ", "機能的な", "functional / well-designed", "na-adjective", "Praise & Quality"),
    ("kinpatsu no", "きんぱつの", "キンパツノ", "金髪の", "blond-haired", "na-adjective", "Appearance & Style"),
    ("kintou na", "きんとうな", "キントウナ", "均等な", "even / uniform / balanced", "na-adjective", "Conditions & States"),
    ("kiou no aru", "きおくのあたらしい", "キオクノアタラシイ", "記憶の新しい", "fresh in memory", "i-adjective", "Emotions & Mind"),
    ("kirei na", "きれいな", "キレイナ", "綺麗な", "beautiful / spotless clean / neat", "na-adjective", "Appearance & Style"),
    ("kiritto shita", "きりっとした", "キリットシタ", "きりっとした", "dapper / smart / well-poised", "na-adjective", "Appearance & Style"),
    ("kiroku-teki na", "きろくてきな", "キロクテキナ", "記録的な", "record-breaking heat/rain", "na-adjective", "Degree & Intensity"),
    ("kiryuu no tsuyoi", "きりゅうのつよい", "キリュウノツヨイ", "気流の強い", "with turbulent air currents", "i-adjective", "Weather & Climate"),
    ("kisen no aru", "きぜんとした", "キゼントシタ", "毅然とした", "resolute / staunch / dauntless", "na-adjective", "Character & Personality"),
    ("kitanai", "きたない", "キタナイ", "汚い", "dirty / filthy / foul / unfair", "i-adjective", "Appearance & Quality"),
    ("kitte-teki na", "きっての", "キッテノ", "切っての", "the foremost / unexcelled", "na-adjective", "Praise & Quality"),
    ("kitsui", "きつい", "キツイ", "きつい", "tight shoes / grueling work / stern", "i-adjective", "Difficulty & Ease"),
    ("kiwamete ooi", "きわめておおい", "キワメテオオイ", "極めて多い", "extremely plentiful", "i-adjective", "Degree & Intensity"),
    ("kiyome-rareta", "きよめられた", "キヨメラレタ", "清められた", "purified / sanctified", "na-adjective", "Culture & Society"),
    ("kiyoi", "きよい", "キヨイ", "清い", "pure / clean spring water / upright", "i-adjective", "Character & Personality"),
    ("kizukatta", "きづかいのゆきとどいた", "キヅカイノユキトドイタ", "気配りの利いた", "attentive / considerate", "na-adjective", "Social & Communication"),
    ("kobuto na", "こがらな", "コガラナ", "小柄な", "petite / small of build", "na-adjective", "Size & Shape"),
    ("kodai na", "こだいな", "コダイナ", "広大な", "vast / colossal / boundless plain", "na-adjective", "Size & Shape"),
    ("kodawari no", "こだわりの", "コダワリノ", "こだわりの", "artisanal / specially curated", "na-adjective", "Praise & Quality"),
    ("koe no ookii", "こえのおおきい", "コエノオオキイ", "声の大きい", "loud-voiced / vocal", "i-adjective", "Social & Communication"),
    ("koi", "こい", "コイ", "濃い", "deep rich color / strong thick tea", "i-adjective", "Food & Taste"),
    ("koibito no you na", "こいびとのような", "コイビトノヨウナ", "恋人のような", "affectionate like sweethearts", "na-adjective", "Feelings & Mood"),
    ("kokorobosoi", "こころぼそい", "ココロボソイ", "心細い", "forlorn / helpless / uneasy", "i-adjective", "Feelings & Mood"),
    ("kokoroyoi", "こころよい", "ココロヨイ", "快い", "pleasant / comfortable / agreeable", "i-adjective", "Feelings & Mood"),
    ("kokorozuyoi", "こころづよい", "ココロヅヨイ", "心強い", "heartening / reassuring / emboldened", "i-adjective", "Feelings & Mood"),
    ("kome no umai", "こめのうまい", "コメノウマイ", "米の美味い", "with delicious rice harvest", "i-adjective", "Food & Taste"),
    ("komoyaka na", "こまやかな", "コマヤカナ", "細やかな", "warm and tender / meticulous", "na-adjective", "Character & Personality"),
    ("konkou shita", "こんざつした", "コンザツシタ", "混雑した", "crowded / packed with passengers", "na-adjective", "Conditions & States"),
    ("konnan na", "こんなんな", "コンナンナ", "困難な", "challenging / arduous / difficult", "na-adjective", "Difficulty & Ease"),
    ("kouban no chikai", "こうばんのちかい", "コウバンノチカイ", "交番の近い", "near police box / safe", "i-adjective", "Safety & Health"),
    ("koufuku na", "こうふくな", "コウフクナ", "幸福な", "happy / blessed / blissful", "na-adjective", "Feelings & Mood"),
    ("kouka na", "こうかな", "コウカナ", "高価な", "expensive / costly / high-priced", "na-adjective", "Shopping & Money"),
    ("kouki na", "こうきな", "コウキナ", "高貴な", "noble / aristocratic / exalted", "na-adjective", "Praise & Quality"),
    ("koukyuu na", "こうきゅうな", "コウキュウナ", "高級な", "high-grade / upscale / posh", "na-adjective", "Praise & Quality"),
    ("koushin no tsuyoi", "こうしんのつよい", "コウシンノツヨイ", "向上心の強い", "highly ambitious / driven to excel", "i-adjective", "Character & Personality"),
    ("kousho na", "こうしょな", "コウショナ", "高尚な", "sublime / refined / lofty taste", "na-adjective", "Praise & Quality"),
    ("kousui no kaori no", "こうすいのかおる", "コウスイノカオル", "香水香る", "perfumed / fragrant aroma", "na-adjective", "Appearance & Style"),
    ("kouun na", "こううんな", "コウウンナ", "幸運な", "fortunate / auspicious / lucky", "na-adjective", "Feelings & Mood"),
    ("kowai", "こわい", "コワイ", "怖い", "scary / frightening / terrified", "i-adjective", "Feelings & Mood"),
    ("kudaranai", "くだらない", "クダラナイ", "下らない", "worthless / trivial / nonsense", "i-adjective", "Appearance & Quality"),
    ("kura-kura suru", "くらくらする", "クラクラスル", "眩暈する", "dizzy / giddy / lightheaded", "na-adjective", "Body & Health"),
    ("kurai", "くらい", "クライ", "暗い", "dark night / gloomy temperament", "i-adjective", "Appearance & Mood"),
    ("kurashiyasui", "くらしやすい", "クラシヤスイ", "暮らしやすい", "pleasant to live in / comfortable", "i-adjective", "Conditions & States"),
    ("kuroi", "くろい", "クロイ", "黒い", "pitch black / sun-darkened", "i-adjective", "Colors & Styles"),
    ("kushikatsu no umai", "くしかつのうまい", "クシカツノウマイ", "串カツの美味い", "famous for delicious fried skewers", "i-adjective", "Food & Taste"),
    ("kusai", "くさい", "クサイ", "臭い", "ill-smelling / stinky / suspicious", "i-adjective", "Weather & Senses"),
    ("kushiku mo", "くしくも", "クシクモ", "奇しくも", "strangely / mysteriously enough", "na-adjective", "Conditions & States"),
    ("kutsu no atarashii", "くつのあたらしい", "クツノアタラシイ", "靴の新しい", "wearing brand-new shoes", "i-adjective", "Clothes & Fashion"),
    ("kyoudai na", "きょうだいな", "キョウダイナ", "巨大な", "gigantic / colossal / titanic", "na-adjective", "Size & Shape"),
    ("kyoumi-bukai", "きょうみぶかい", "キョウミブカイ", "興味深い", "deeply intriguing / absorbing", "i-adjective", "Feelings & Mood"),
    ("kyuukutsu na", "きゅうくつな", "キュウクツナ", "窮屈な", "cramped / tight shoes / formal", "na-adjective", "Conditions & States"),
    ("kyuu na", "きゅうな", "キュウナ", "急な", "sudden / steep slope / urgent", "na-adjective", "Speed & Time")
]
