# Senses, Appearance, Shapes, Colors, Textures, Flavors, Sound, Temperature
# (romaji, hiragana, katakana, kanji, meaning, type, topic)
DATA = [
    # E
    ("eisei-teki na", "えいせいてきな", "エイセイテキナ", "衛生的な", "hygienic / sanitary / clean", "na-adjective", "Safety & Health"),
    ("eleganto na", "えれがんとな", "エレガントナ", "エレガントな", "elegant / refined / graceful", "na-adjective", "Appearance & Style"),
    ("emikoi", "えがおの", "エガオノ", "笑顔の", "smiling / cheerful-faced", "na-adjective", "Appearance & Mood"),
    ("enman na", "えんまんな", "エンマンナ", "円満な", "harmonious / amicable / peaceful", "na-adjective", "Social & Communication"),
    ("enryo-bukai", "えんりょぶかい", "エンリョブカイ", "遠慮深い", "reserved / shy / diffident", "i-adjective", "Character & Personality"),
    ("erai", "えらい", "エライ", "偉い", "great / eminent / admirable", "i-adjective", "Praise & Quality"),
    ("etoku shita", "えとくした", "エトクシタ", "会得した", "well-versed / mastered", "na-adjective", "Work & Study"),
    # F
    ("fuan na", "ふあんな", "フアンナ", "不安な", "anxious / uneasy / apprehensive", "na-adjective", "Feelings & Mood"),
    ("fuben na", "ふべんな", "フベンナ", "不便な", "inconvenient / awkward location", "na-adjective", "Conditions & States"),
    ("fubyoudou na", "ふびょうどうな", "フビョウドウナ", "不平等な", "unequal / unfair", "na-adjective", "Culture & Society"),
    ("fukai", "ふかい", "フカイ", "深い", "deep / profound ocean or thought", "i-adjective", "Places & Spatial"),
    ("fukai na", "ふかいな", "フカイナ", "不快な", "unpleasant / disagreeable", "na-adjective", "Feelings & Mood"),
    ("fukanzen na", "ふかんぜんな", "フカンゼンナ", "不完全な", "incomplete / defective", "na-adjective", "Conditions & States"),
    ("fukashigi na", "ふかしぎな", "フカシギナ", "不可思議な", "mysterious / miraculous", "na-adjective", "Conditions & States"),
    ("fuketsu na", "ふけつな", "フケツナ", "不潔な", "unclean / unsanitary / dirty", "na-adjective", "Safety & Health"),
    ("fukou na", "ふこうな", "フコウナ", "不幸な", "unhappy / unfortunate / sorrowful", "na-adjective", "Feelings & Mood"),
    ("fukumi no aru", "ふくみのある", "フクミノアル", "含みのある", "pregnant with meaning", "na-adjective", "Character & Clarity"),
    ("fukuzatsu na", "ふくざつな", "フクザツナ", "複雑な", "complex / intricate / complicated", "na-adjective", "Difficulty & Ease"),
    ("funiki no ii", "ふんいきのいい", "フンイキノイイ", "雰囲気のいい", "atmospheric / cozy aura", "i-adjective", "Appearance & Style"),
    ("fushigi na", "ふしぎな", "フシギナ", "不思議な", "wondrous / strange / mysterious", "na-adjective", "Conditions & States"),
    ("fushizen na", "ふしぜんな", "フシゼンナ", "不自然な", "unnatural / artificial / strained", "na-adjective", "Conditions & States"),
    ("fushoujiki na", "ふしょうじきな", "フショウジキナ", "不正直な", "dishonest / insincere", "na-adjective", "Character & Personality"),
    ("futou na", "ふとうな", "フトウナ", "不当な", "unjust / unfair / exorbitant", "na-adjective", "Culture & Society"),
    ("futsugou na", "ふつごうな", "フツゴウナ", "不都合な", "inconvenient / prejudicial", "na-adjective", "Conditions & States"),
    ("futsuu no", "ふつうの", "フツウノ", "普通の", "ordinary / normal / commonplace", "na-adjective", "Conditions & States"),
    ("futoi", "ふとい", "フトイ", "太い", "thick / fat / bold", "i-adjective", "Size & Shape"),
    ("fuyuu na", "ふゆうな", "フユウナ", "富裕な", "wealthy / affluent / well-off", "na-adjective", "Conditions & States"),
    # G
    ("gaikou-teki na", "がいこうてきな", "ガイコウテキナ", "外交的な", "diplomatic / sociable / extrovert", "na-adjective", "Character & Personality"),
    ("gaman-zuyoi", "がまんづよい", "ガマンヅヨイ", "我慢強い", "patient / persevering / stoic", "i-adjective", "Character & Personality"),
    ("gankou na", "がんこな", "ガンコナ", "頑固な", "stubborn / obstinate / persistent", "na-adjective", "Character & Personality"),
    ("gantou na", "がんじょうな", "ガンジョウナ", "頑丈な", "sturdy / robust / solidly built", "na-adjective", "Conditions & States"),
    ("garei na", "がれいな", "ガレイナ", "雅麗な", "gracefully elegant", "na-adjective", "Appearance & Style"),
    ("gasshiri shita", "がっしりした", "ガッシリシタ", "がっしりした", "muscular / stout / solidly built", "na-adjective", "Appearance & Style"),
    ("geijutsu-teki na", "げいじゅつてきな", "ゲイジュツテキナ", "芸術的な", "artistic / aesthetic", "na-adjective", "Culture & Society"),
    ("gekikara na", "げきからな", "ゲキカラナ", "激辛な", "ultra-spicy / scorching hot", "na-adjective", "Food & Taste"),
    ("geki-retsu na", "げきれつな", "ゲキレツナ", "激烈な", "fierce / vehement / violent", "na-adjective", "Degree & Intensity"),
    ("genjitsu-teki na", "げんじつてきな", "ゲンジツテキナ", "現実的な", "realistic / practical / pragmatic", "na-adjective", "Character & Personality"),
    ("genjuu na", "げんじゅうな", "ゲンジュウナ", "厳重な", "strict / rigorous / tight security", "na-adjective", "Conditions & States"),
    ("genki na", "げんきな", "ゲンキナ", "元気な", "lively / vigorous / in good health", "na-adjective", "Safety & Health"),
    ("genmitsu na", "げんみつな", "ゲンミツナ", "厳密な", "precise / exact / meticulous", "na-adjective", "Work & Study"),
    ("giri-gatai", "ぎりがたい", "ギリガタイ", "義理堅い", "dutiful / conscientious", "i-adjective", "Character & Personality"),
    ("gokuraku no you na", "ごくらくのような", "ゴクラクノヨウナ", "極楽のような", "heavenly / blissful bliss", "na-adjective", "Feelings & Mood"),
    ("gousho na", "ごうかな", "ゴウカナ", "豪華な", "luxurious / gorgeous / deluxe", "na-adjective", "Appearance & Style"),
    ("gouriteki na", "ごうりてきな", "ゴウリテキナ", "合理的な", "rational / logical / reasonable", "na-adjective", "Work & Study"),
    ("guutara na", "ぐうたらな", "グウタラナ", "ぐうたらな", "idle / lazy / shiftless", "na-adjective", "Character & Personality"),
    ("gyougi no ii", "ぎょうぎのいい", "ギョウギノイイ", "行儀のいい", "well-mannered / polite child", "i-adjective", "Character & Personality"),
    # H
    ("hade na", "はでな", "ハデナ", "派手な", "showy / flashy / flamboyant", "na-adjective", "Appearance & Style"),
    ("hadazawari no ii", "はだざわりのいい", "ハダザワリノイイ", "肌触りのいい", "pleasant to the touch / silky", "i-adjective", "Appearance & Quality"),
    ("hageshii", "はげしい", "ハゲシイ", "激しい", "violent / intense / fierce wind", "i-adjective", "Degree & Intensity"),
    ("haikara na", "はいからな", "ハイカラナ", "ハイカラな", "fashionable / Westernized / smart", "na-adjective", "Appearance & Style"),
    ("hairyo no aru", "はいりょのある", "ハイリョノアル", "配慮のある", "thoughtful / considerate", "na-adjective", "Social & Communication"),
    ("haitoku-teki na", "はいとくてきな", "ハイトクテキナ", "背徳的な", "corrupt / immoral", "na-adjective", "Character & Personality"),
    ("hakujaku na", "はくじゃくな", "ハクジャクナ", "薄弱な", "feeble / weak-willed", "na-adjective", "Character & Personality"),
    ("haku-netsu shita", "はくねつした", "ハクネツシタ", "白熱した", "heated match / white-hot", "na-adjective", "Degree & Intensity"),
    ("hamigakitate no", "はみがきたての", "ハミガキタテノ", "磨き立ての", "freshly brushed / sparkling", "na-adjective", "Safety & Health"),
    ("hanayaka na", "はなやかな", "ハナヤカナ", "華やかな", "gorgeous / brilliant / radiant", "na-adjective", "Appearance & Style"),
    ("happii na", "はっぴーな", "ハッピーナ", "ハッピーな", "happy / delightful", "na-adjective", "Feelings & Mood"),
    ("haritsumeta", "はりつめた", "ハリツメタ", "張り詰めた", "taut / high-strung / tense atmosphere", "na-adjective", "Feelings & Mood"),
    ("hasukashii", "はずかしい", "ハズカシイ", "恥ずかしい", "embarrassed / bashful / shameful", "i-adjective", "Feelings & Mood"),
    ("hayai-fast", "はやい", "ハヤイ", "速い", "fast / speedy / rapid", "i-adjective", "Speed & Time"),
    ("hayai-early", "はやい", "ハヤイ", "早い", "early in morning or year", "i-adjective", "Speed & Time"),
    ("hebon na", "へぼんな", "ヘボンナ", "平凡な", "mediocre / unremarkable / ordinary", "na-adjective", "Appearance & Quality"),
    ("heiki na", "へいきな", "ヘイキナ", "平気な", "calm / unconcerned / cool", "na-adjective", "Feelings & Mood"),
    ("heikou na", "へいこうな", "ヘイコウナ", "平行な", "parallel / side by side", "na-adjective", "Size & Shape"),
    ("heiten shita", "へいてんした", "ヘイテンシタ", "閉店した", "closed down (store)", "na-adjective", "Conditions & States"),
    ("heiwa na", "へいわな", "ヘイワナ", "平和な", "peaceful / tranquil / harmonious", "na-adjective", "Culture & Society"),
    ("heta na", "へたな", "ヘタナ", "下手な", "unskillful / poor at craft", "na-adjective", "Difficulty & Ease"),
    ("hiebie to shita", "ひえびえとした", "ヒエビエトシタ", "冷え冷えとした", "chilly / frost-bitten", "na-adjective", "Weather & Climate"),
    ("higoro no", "ひごろの", "ヒゴロノ", "日頃の", "daily / everyday habitual", "na-adjective", "Daily Life"),
    ("hikutsu na", "ひくつな", "ヒクツナ", "卑屈な", "servile / groveling / obsequious", "na-adjective", "Character & Personality"),
    ("hikui", "ひくい", "ヒクイ", "低い", "low in height / low pitch", "i-adjective", "Size & Shape"),
    ("hima na", "ひまな", "ヒマナ", "暇な", "free / unoccupied / idle", "na-adjective", "Speed & Time"),
    ("hinjaku na", "ひんじゃくな", "ヒンジャクナ", "貧弱な", "poor / meager / scrawny", "na-adjective", "Size & Shape"),
    ("hinpu no sa no aru", "ひんぷのさのある", "ヒンプノサノアル", "貧富の差のある", "unequal in wealth", "na-adjective", "Culture & Society"),
    ("hiroi", "ひろい", "ヒロイ", "広い", "wide / spacious / broad room", "i-adjective", "Size & Shape"),
    ("hisshi na", "ひっしな", "ヒッシナ", "必死な", "desperate / frantic / all-out", "na-adjective", "Character & Personality"),
    ("hitamuki na", "ひたむきな", "ヒタムキナ", "直向きな", "earnest / single-minded", "na-adjective", "Character & Personality"),
    ("hito-natsukoi", "ひとなつっこい", "ヒトナツッコイ", "人懐っこい", "friendly / sociable / outgoing", "i-adjective", "Character & Personality"),
    ("hitori-bocchi no", "ひとりぼっちの", "ヒトリボッチノ", "一人ぼっちの", "lonely / solitary", "na-adjective", "Feelings & Mood"),
    ("hitoshii", "ひとしい", "ヒトシイ", "等しい", "equal / identical in value", "i-adjective", "Degree & Intensity"),
    ("hitsu-you na", "ひつような", "ヒツヨウナ", "必要な", "essential / necessary / required", "na-adjective", "Conditions & States"),
    ("hiyoko no you na", "ひよこのような", "ヒヨコノヨウナ", "雛のような", "chick-like / tiny & fluffy", "na-adjective", "Appearance & Style"),
    ("hokorashii", "ほこらしい", "ホコラシイ", "誇らしい", "proud / filled with pride", "i-adjective", "Feelings & Mood"),
    ("hoka no", "ほかの", "ホカノ", "他の", "other / different / another", "na-adjective", "Conditions & States"),
    ("honki na", "ほんきな", "ホンキナ", "本気な", "dead serious / earnest", "na-adjective", "Character & Personality"),
    ("honto no", "ほんとうの", "ホントウノ", "本当の", "genuine / real / authentic", "na-adjective", "Praise & Quality"),
    ("horonigai", "ほろにがい", "ホロニガイ", "ほろ苦い", "bittersweet in taste or memory", "i-adjective", "Food & Taste"),
    ("hoshii", "ほしい", "ホシイ", "欲しい", "desired / wanted / coveted", "i-adjective", "Feelings & Mood"),
    ("hosoi", "ほそい", "ホソイ", "細い", "thin / slender / narrow thread", "i-adjective", "Size & Shape"),
    ("hotto shita", "ほっとした", "ホットシタ", "ほっとした", "relieved / reassured", "na-adjective", "Feelings & Mood"),
    ("hyouban no ii", "ひょうばんのいい", "ヒョウバンノイイ", "評判のいい", "well-reputed / acclaimed", "i-adjective", "Praise & Quality"),
    # I
    ("ibara no", "いばらの", "イバラノ", "茨の", "thorny / perilous path", "na-adjective", "Conditions & States"),
    ("ichidaiji na", "いちだいじな", "イチダイジナ", "一大事な", "monumental / of great consequence", "na-adjective", "Degree & Intensity"),
    ("ichiryuu no", "いちりゅうの", "イチリュウノ", "一流の", "first-class / top-tier", "na-adjective", "Praise & Quality"),
    ("idai na", "いだいな", "イダイナ", "偉大な", "mighty / magnificent / great", "na-adjective", "Praise & Quality"),
    ("ii", "いい", "イイ", "良い", "good / fine / pleasant", "i-adjective", "Praise & Quality"),
    ("ii-kagen na", "いいかげんな", "イイカゲンナ", "いい加減な", "half-baked / irresponsible / moderate", "na-adjective", "Character & Personality"),
    ("iji-waru na", "いじわるな", "イジワルナ", "意地悪な", "spiteful / ill-natured / mean", "na-adjective", "Character & Personality"),
    ("ikigurushii", "いきぐるしい", "イキグルシイ", "息苦しい", "stifling / suffocating / oppressive", "i-adjective", "Body & Health"),
    ("ikiki to shita", "いきいきとした", "イキイキトシタ", "生き生きとした", "vibrant / full of life", "na-adjective", "Appearance & Mood"),
    ("ikkyou na", "いっきょうな", "イッキョウナ", "一興な", "amusing / diverting", "na-adjective", "Feelings & Mood"),
    ("ikari ni michita", "いかりにみちた", "イカリニミチタ", "怒りに満ちた", "furious / wrathful", "na-adjective", "Feelings & Mood"),
    ("ima-fuu no", "いまふうの", "イマフウノ", "今風の", "modern / contemporary in style", "na-adjective", "Appearance & Style"),
    ("insho-teki na", "いんしょうてきな", "インショウテキナ", "印象的な", "striking / memorable / impressive", "na-adjective", "Appearance & Style"),
    ("intai shita", "いんたいした", "インタイシタ", "引退した", "retired from work", "na-adjective", "Conditions & States"),
    ("ippan-teki na", "いっぱんてきな", "イッパンテキナ", "一般的な", "general / widespread / common", "na-adjective", "Conditions & States"),
    ("iraira shita", "いらいらした", "イライラシタ", "苛々した", "edgy / fretful / annoyed", "na-adjective", "Feelings & Mood"),
    ("iro-torigidori na", "いろとりどりな", "イロトリドリナ", "色とりどりな", "multicolored / colorful array", "na-adjective", "Appearance & Style"),
    ("isagiyoi", "いさぎよい", "イサギヨイ", "潔い", "manly / pure-hearted / sportsmanship", "i-adjective", "Character & Personality"),
    ("isogashii", "いそがしい", "イソガシイ", "忙しい", "busy / engaged / occupied", "i-adjective", "Speed & Time"),
    ("itadakitate no", "いきたての", "イキタテノ", "淹れたての", "freshly brewed (coffee, tea)", "na-adjective", "Food & Taste"),
    ("itai", "いたい", "イタイ", "痛い", "painful / sore / aching", "i-adjective", "Body & Health"),
    ("itaitashii", "いたいたしい", "イタイタシイ", "痛々しい", "heart-wrenching / tragic to look at", "i-adjective", "Feelings & Mood"),
    ("itarinitsukuseni", "いたれりつくせりの", "イタレリツクセリノ", "至れり尽くせりの", "hospitable down to every detail", "na-adjective", "Praise & Quality"),
    ("itoshiki", "いとしい", "イトシイ", "愛しい", "beloved / darling / dear", "i-adjective", "Feelings & Mood"),
    ("iyami na", "いやみな", "イヤミナ", "嫌味な", "sarcastic / snide / offensive", "na-adjective", "Character & Personality"),
    ("iya na", "いやな", "イヤナ", "嫌な", "disagreeable / unpleasant / hateful", "na-adjective", "Feelings & Mood")
]
