# Emotions, Feelings, Mood, Human Character, Personality Traits
# (romaji, hiragana, katakana, kanji, meaning, type, topic)
DATA = [
    # A
    ("adokenai", "あどけない", "アドケナイ", "無邪気な", "innocent / naive / childlike", "i-adjective", "Character & Personality"),
    ("aikurushii", "あいくるしい", "アイクルシイ", "愛くるしい", "charming / adorable / lovable", "i-adjective", "Appearance & Style"),
    ("aimai na", "あいまいな", "アイマイナ", "曖昧な", "ambiguous / vague / indistinct", "na-adjective", "Character & Clarity"),
    ("aiso no ii", "あいそのいい", "アイソノイイ", "愛想のいい", "affable / amiable / courteous", "i-adjective", "Character & Personality"),
    ("akarasama na", "あからさまな", "アカラサマナ", "露骨な", "overt / frank / outspoken", "na-adjective", "Character & Clarity"),
    ("akarui", "あかるい", "アカルイ", "明るい", "bright / cheerful / sunny personality", "i-adjective", "Appearance & Mood"),
    ("akkiraka na", "あっけらかんな", "アッケラカンナ", "呆気らかんな", "indifferent / nonplussed / airy", "na-adjective", "Feelings & Mood"),
    ("akkenai", "あっけない", "アッケナイ", "呆気ない", "too brief / anticlimactic", "i-adjective", "Feelings & Mood"),
    ("amaku miru", "あまい", "アマイ", "甘い", "lenient / overly optimistic", "i-adjective", "Character & Personality"),
    ("amatour na", "あまとうな", "アマトウナ", "甘党な", "having sweet tooth", "na-adjective", "Food & Taste"),
    ("anshin na", "あんしんな", "アンシンナ", "安心な", "relieved / secure / peaceful", "na-adjective", "Feelings & Mood"),
    ("antei shita", "あんていした", "アンテイシタ", "安定した", "stable / steadfast in character", "na-adjective", "Conditions & States"),
    ("anzen na", "あんぜんな", "アンゼンナ", "安全な", "safe / out of harm's way", "na-adjective", "Safety & Health"),
    ("aoge na", "あおげな", "アオゲナ", "仰げな", "high-minded / noble", "na-adjective", "Character & Personality"),
    ("appare na", "あっぱれな", "アッパレナ", "天晴れな", "splendid / admirable / glorious", "na-adjective", "Praise & Quality"),
    ("aragoi", "あらい", "アライ", "荒い", "rough / wild / fierce temper", "i-adjective", "Character & Personality"),
    ("aratamatta", "あらたまった", "アラタマッタ", "改まった", "formal / solemn in manner", "na-adjective", "Character & Personality"),
    ("arata na", "あらたな", "アラタナ", "新たな", "brand-new / fresh", "na-adjective", "Conditions & States"),
    ("arigatagaru", "ありがたい", "アリガタイ", "有り難い", "grateful / welcome / blessed", "i-adjective", "Feelings & Mood"),
    ("asaguroi", "あさぐろい", "アサグロイ", "浅黒い", "sun-tanned / dark-complexioned", "i-adjective", "Appearance & Style"),
    ("asappira na", "あさはかな", "アサハカナ", "浅はかな", "shallow / frivolous / thoughtless", "na-adjective", "Character & Personality"),
    ("asekusai", "あせくさい", "アセクサイ", "汗臭い", "smelling of sweat", "i-adjective", "Body & Health"),
    ("ashibaya na", "あしばやな", "アシバヤナ", "足早な", "brisk-footed / quick-paced", "na-adjective", "Speed & Time"),
    ("atatakai-heart", "あたたかい", "アタタカイ", "温かい", "warm-hearted / kindly", "i-adjective", "Character & Personality"),
    ("atarashii", "あたらしい", "アタラシイ", "新しい", "new / fresh / novel", "i-adjective", "Appearance & Quality"),
    ("atsui-heart", "あつい", "アツイ", "熱い", "passionate / zealous of heart", "i-adjective", "Feelings & Mood"),
    ("atsukamashii", "あつかましい", "アツカマシイ", "厚かましい", "impudent / brazen / shameless", "i-adjective", "Character & Personality"),
    ("aware na", "あわれな", "アワレナ", "哀れな", "pitiful / pathetic / touching", "na-adjective", "Feelings & Mood"),
    ("awatedoi", "あわただしい", "アワタダシイ", "慌ただしい", "hectic / bustling / hurried", "i-adjective", "Speed & Time"),
    ("ayafuya na", "あやふやな", "アヤフヤナ", "あやふやな", "vague / uncertain / dubious", "na-adjective", "Character & Clarity"),
    ("ayashii", "あやしい", "アヤシイ", "怪しい", "suspicious / dubious / shady", "i-adjective", "Conditions & States"),
    ("azayaka na", "あざやかな", "アザヤカナ", "鮮やかな", "vivid / brilliant / masterful", "na-adjective", "Appearance & Style"),
    # B
    ("baika na", "ばいかな", "バイカナ", "倍加な", "doubled / intensified", "na-adjective", "Degree & Intensity"),
    ("baka na", "ばかな", "バカナ", "馬鹿な", "foolish / stupid / silly", "na-adjective", "Character & Personality"),
    ("baka-shoujiki na", "ばかしょうじきな", "バカショウジキナ", "馬鹿正直な", "honest to a fault", "na-adjective", "Character & Personality"),
    ("bakusentaru", "ばくぜんとした", "バクゼントシタ", "漠然とした", "vague / obscure / nebulous", "na-adjective", "Character & Clarity"),
    ("banshou na", "ばんしょうな", "バンショウナ", "万象な", "all-encompassing", "na-adjective", "Degree & Intensity"),
    ("barabara na", "ばらばらな", "バラバラナ", "散り散りな", "scattered / disjointed", "na-adjective", "Conditions & States"),
    ("bimyoo na", "びみょうな", "ビミョウナ", "微妙な", "subtle / delicate / tricky", "na-adjective", "Character & Clarity"),
    ("binbounin", "びんぼうな", "ビンボウナ", "貧乏な", "poor / needy / destitute", "na-adjective", "Conditions & States"),
    ("binkan na", "びんかんな", "ビンカンナ", "敏感な", "sensitive / perceptive / alert", "na-adjective", "Feelings & Mood"),
    ("binsoku na", "びんそくな", "ビンソクナ", "敏速な", "prompt / nimble / agile", "na-adjective", "Speed & Time"),
    ("bishoutaru", "びしょうな", "ビショウナ", "微小な", "microscopic / tiny", "na-adjective", "Size & Shape"),
    ("bita na", "びたな", "ビタナ", "微細な", "minute / fine in detail", "na-adjective", "Size & Shape"),
    ("biyou na", "びような", "ビヨウナ", "美麗な", "splendidly beautiful", "na-adjective", "Appearance & Style"),
    ("bonyari shita", "ぼんやりした", "ボンヤリシタ", "ぼんやりした", "absent-minded / hazy / dim", "na-adjective", "Feelings & Mood"),
    ("bousou na", "ぼうそうな", "ボウソウナ", "奔放な", "wild / unrestrained / free-spirited", "na-adjective", "Character & Personality"),
    ("buji na", "ぶじな", "ブジナ", "無事な", "safe and sound / untroubled", "na-adjective", "Safety & Health"),
    ("bukiyou na", "ぶきような", "ブキヨウナ", "不器用な", "clumsy / awkward / unhandy", "na-adjective", "Character & Personality"),
    ("bukimi na", "ぶきみな", "ブキミナ", "不気味な", "eerie / uncanny / ominous", "na-adjective", "Feelings & Mood"),
    ("bunka-teki na", "ぶんかてきな", "ブンカテキナ", "文化的な", "cultural / civilized", "na-adjective", "Culture & Society"),
    ("burei na", "ぶれいな", "ブレイナ", "無礼な", "rude / discourteous / insolent", "na-adjective", "Character & Personality"),
    ("busu na", "ぶすな", "ブスナ", "不細工な", "unattractive / homely", "na-adjective", "Appearance & Style"),
    ("butsuri-teki na", "ぶつりてきな", "ブツリテキナ", "物理的な", "physical / tangible", "na-adjective", "Conditions & States"),
    # C
    ("chanto shita", "ちゃんとした", "チャントシタ", "ちゃんとした", "proper / respectable / decent", "na-adjective", "Character & Personality"),
    ("charming na", "ちゃーみんぐな", "チャーミングナ", "チャーミングな", "charming / captivating", "na-adjective", "Appearance & Style"),
    ("chibi na", "ちびな", "チビナ", "ちびな", "tiny / pint-sized", "na-adjective", "Size & Shape"),
    ("chika na", "ちかな", "チカナ", "身近な", "familiar / close at hand", "na-adjective", "Places & Spatial"),
    ("chikara-zuyoi", "ちからづよい", "チカラヅヨイ", "力強い", "forceful / robust / reassuring", "i-adjective", "Character & Personality"),
    ("chiisai", "ちいさい", "チイサイ", "小さい", "small / little / petite", "i-adjective", "Size & Shape"),
    ("chiisana", "ちいさな", "チイサナ", "小さな", "small / tiny", "na-adjective", "Size & Shape"),
    ("chinpunkan na", "ちんぷんかんぷんな", "チンプンカンプンナ", "珍紛漢紛な", "incomprehensible / Greek to me", "na-adjective", "Difficulty & Ease"),
    ("chiteki na", "ちてきな", "チテキナ", "知的な", "intellectual / smart / erudite", "na-adjective", "Character & Personality"),
    ("chotto shita", "ちょっとした", "チョットシタ", "一寸した", "minor / considerable / quite good", "na-adjective", "Degree & Intensity"),
    ("choudo ii", "ちょうどいい", "チョウドイイ", "丁度いい", "just right / perfect fit", "i-adjective", "Conditions & States"),
    ("chouki-teki na", "ちょうきてきな", "チョウキテキナ", "長期的な", "long-term in perspective", "na-adjective", "Speed & Time"),
    ("chuushou-teki na", "ちゅうしょうてきな", "チュウショウテキナ", "抽象的な", "abstract / conceptual", "na-adjective", "Character & Clarity"),
    ("chuujitsu na", "ちゅうじつな", "チュウジツナ", "忠実な", "faithful / loyal / true", "na-adjective", "Character & Personality"),
    ("chuushin-teki na", "ちゅうしんてきな", "チュウシンテキナ", "中心的な", "central / pivotal / core", "na-adjective", "Places & Spatial"),
    # D
    ("daenshou na", "だえんけいの", "ダエンケイノ", "楕円形の", "oval / elliptic", "na-adjective", "Size & Shape"),
    ("daiji na", "だいじな", "ダイジナ", "大事な", "crucial / precious / important", "na-adjective", "Praise & Quality"),
    ("daikibo na", "だいきぼな", "ダイキボナ", "大規模な", "large-scale / massive", "na-adjective", "Size & Shape"),
    ("daikirai na", "だいきらいな", "ダイキライナ", "大嫌いな", "detested / loathed", "na-adjective", "Feelings & Mood"),
    ("dainamikku na", "だいなみっくな", "ダイナミックナ", "ダイナミックな", "dynamic / high-powered", "na-adjective", "Character & Personality"),
    ("daisuki na", "だいすきな", "ダイスキナ", "大好きな", "beloved / deeply cherished", "na-adjective", "Feelings & Mood"),
    ("daitan na", "だいたんな", "ダイタンナ", "大胆な", "bold / daring / audacious", "na-adjective", "Character & Personality"),
    ("daiya no you na", "だいやのような", "ダイヤノヨウナ", "ダイヤのような", "sparkling like diamond", "na-adjective", "Appearance & Style"),
    ("dame na", "だめな", "ダメナ", "駄目な", "useless / no-good / hopeless", "na-adjective", "Conditions & States"),
    ("dansei-teki na", "だんせいてきな", "ダンセイテキナ", "男性的な", "masculine / manly", "na-adjective", "Character & Personality"),
    ("dantotsu na", "だんとつな", "ダントツナ", "断トツな", "far and away the best", "na-adjective", "Praise & Quality"),
    ("darashinai", "だらしない", "ダラシナイ", "だらしない", "slovenly / loose / untidy", "i-adjective", "Character & Personality"),
    ("darui", "だるい", "ダルイ", "怠い", "sluggish / languid / fatigued", "i-adjective", "Body & Health"),
    ("deguchi no chikai", "でぐちのちかい", "デグチノチカイ", "出口の近い", "near the exit", "i-adjective", "Places & Spatial"),
    ("dekiai no", "できあいの", "デキアイノ", "出来合いの", "ready-made / off-the-rack", "na-adjective", "Conditions & States"),
    ("dekiru-person", "できる", "デキル", "出来る", "capable / talented / proficient", "na-adjective", "Character & Personality"),
    ("dento-teki na", "でんとうてきな", "デントウテキナ", "伝統的な", "traditional / heritage-steeped", "na-adjective", "Culture & Society"),
    ("detarame na", "でたらめな", "デタラメナ", "出鱈目な", "irresponsible / random gibberish", "na-adjective", "Character & Personality"),
    ("dokudokushii", "どくどくしい", "ドクドクシイ", "毒々しい", "poisonous-looking / venomous", "i-adjective", "Appearance & Style"),
    ("dokuji na", "どくじな", "ドクジナ", "独自な", "original / unique / idiosyncratic", "na-adjective", "Praise & Quality"),
    ("dokuritsu shita", "どくりつした", "ドクリツシタ", "独立した", "independent / self-reliant", "na-adjective", "Character & Personality"),
    ("dokusou-teki na", "どくそうてきな", "ドクソウテキナ", "独創的な", "creative / original / inventive", "na-adjective", "Praise & Quality"),
    ("donkan na", "どんかんな", "ドンカンナ", "鈍感な", "thick-skinned / insensitive", "na-adjective", "Character & Personality"),
    ("donkusa", "どんくさい", "ドンクサイ", "鈍くさい", "clumsy / slow-witted", "i-adjective", "Character & Personality"),
    ("dousei no", "どうせいの", "ドウセイノ", "同性の", "of the same sex", "na-adjective", "People & Family"),
    ("doushi no", "どうしの", "ドウシノ", "同士の", "fellow / companion", "na-adjective", "Social & Communication"),
    ("doutoku-teki na", "どうとくてきな", "ドウトクテキナ", "道徳的な", "moral / ethical / virtuous", "na-adjective", "Character & Personality"),
    ("dorodoro na", "どろどろな", "ドロドロナ", "泥々な", "muddy / gooey / syrupy", "na-adjective", "Conditions & States")
]
