# Sino-Japanese JLPT N5-N2 na-adjectives & Authentic Expressions
# (romaji, hiragana, katakana, kanji, meaning, type, topic)
DATA = [
    # A
    ("akutibu na", "あくてぃぶな", "アクティブナ", "アクティブな", "active / energetic / proactive", "na-adjective", "Character & Personality"),
    ("anraku na", "あんらくな", "アンラクナ", "安楽な", "comfortable / easy living", "na-adjective", "Conditions & States"),
    ("antei-teki na", "あんていてきな", "アンテイテキナ", "安定的な", "consistently stable", "na-adjective", "Conditions & States"),
    ("appu-to-deeto na", "あっぷとぅでーとな", "アップトゥデートナ", "最新の", "up-to-date / state-of-the-art", "na-adjective", "Appearance & Style"),
    ("arukari-sei no", "あるかりせいの", "アルカリセイノ", "アルカリ性の", "alkaline nature", "na-adjective", "Conditions & States"),
    ("asagao-iro no", "あさがおいろの", "アサガオイロノ", "朝顔色の", "morning glory violet hue", "na-adjective", "Colors & Styles"),
    ("asase no", "あさせの", "アサセノ", "浅瀬の", "shoal / shallow water", "na-adjective", "Places & Spatial"),
    ("atataka na", "あたたかな", "アタタカナ", "暖かな", "balmy / warm and cozy sun", "na-adjective", "Weather & Climate"),
    ("atsukurushii", "あつくるしい", "アツクルシイ", "暑苦しい", "sweltering / stiflingly hot", "i-adjective", "Weather & Climate"),
    # B
    ("baio-teki na", "ばいおてきな", "バイオテキナ", "生物的な", "biological / bio-based", "na-adjective", "Science & Nature"),
    ("bannou na", "ばんのうな", "バンノウナ", "万能な", "all-purpose / versatile tool", "na-adjective", "Praise & Quality"),
    ("bariki no aru", "ばりきのある", "バリキノアル", "馬力のある", "high-horsepower / vigorous", "na-adjective", "Character & Personality"),
    ("beikoku-fuu no", "べいこくふうの", "ベイコクフウノ", "アメリカ風の", "American-style in design", "na-adjective", "Appearance & Style"),
    ("betsu no", "べつの", "ベツノ", "別の", "different / another / separate", "na-adjective", "Conditions & States"),
    ("bi-teki na", "びてきな", "ビテキナ", "美的な", "aesthetic / artistic in sensibility", "na-adjective", "Appearance & Style"),
    ("bousai-teki na", "ぼうさいてきな", "ボウサイテキナ", "防災的な", "disaster-preventive", "na-adjective", "Safety & Health"),
    ("bousui no", "ぼうすいの", "ボウスイノ", "防水の", "waterproof / water-resistant", "na-adjective", "Appearance & Quality"),
    ("bunkateki na", "ぶんかてきな", "ブンカテキナ", "文化的な", "cultured / enlightened", "na-adjective", "Culture & Society"),
    # C
    ("chakujitsu na", "ちゃくじつな", "チャクジツナ", "着実な", "steady / trustworthy / sound progress", "na-adjective", "Character & Personality"),
    ("chikyuu-kibo no", "ちきゅうきぼの", "チキュウキボノ", "地球規模の", "global in scale", "na-adjective", "Size & Shape"),
    ("chimei-teki na", "ちめいてきな", "チメイテキナ", "致命的な", "fatal / critical flaw", "na-adjective", "Degree & Intensity"),
    ("chitsujo-tadashii", "ちつじょただしい", "チツジョタダシイ", "秩序正しい", "methodical / orderly / disciplined", "i-adjective", "Character & Personality"),
    ("chokkan-teki na", "ちょっかんてきな", "チョッカンテキナ", "直感的な", "intuitive / instinctively obvious", "na-adjective", "Character & Clarity"),
    ("chokusetsu-teki na", "ちょくせつてきな", "チョクセツテキナ", "直接的な", "direct / firsthand interaction", "na-adjective", "Social & Communication"),
    ("choutatsu no", "ちょうたつした", "チョウタツシタ", "熟達した", "proficient / seasoned veteran", "na-adjective", "Work & Study"),
    ("chouwa shita", "ちょうわした", "チョウワシタ", "調和した", "harmonized / well-coordinated", "na-adjective", "Appearance & Style"),
    ("chuuko no", "ちゅうこの", "チュウコノ", "中古の", "secondhand / pre-owned vehicle", "na-adjective", "Shopping & Money"),
    ("chuushou no", "ちゅうしょうの", "チュウショウノ", "中小の", "small-to-medium enterprise", "na-adjective", "Size & Shape"),
    # D
    ("dai-kibo na", "だいきぼな", "ダイキボナ", "大がかりな", "grand in design / wide-ranging", "na-adjective", "Size & Shape"),
    ("dai-shizen no", "だいしぜんの", "ダイシゼンノ", "大自然の", "primeval / of great nature", "na-adjective", "Weather & Climate"),
    ("dan-teki na", "だんてきな", "ダンテキナ", "断片的な", "fragmentary / piecemeal knowledge", "na-adjective", "Character & Clarity"),
    ("danwa-teki na", "だんわてきな", "ダンワテキナ", "談話的な", "conversational / colloquial tone", "na-adjective", "Social & Communication"),
    ("dento-teki na-culture", "こでんの", "コデンノ", "古式ゆかしい", "steeped in ancient tradition", "i-adjective", "Culture & Society"),
    ("denshi-teki na", "でんしてきな", "デンシテキナ", "電子的な", "electronic / digital interface", "na-adjective", "Appearance & Quality"),
    ("dokuji no", "どくじの", "ドクジノ", "独特の", "singular / peculiar idiosyncrasy", "na-adjective", "Praise & Quality"),
    ("dokusou-teki", "どくそうてきな", "ドクソウテキナ", "独自性のある", "highly original in thought", "na-adjective", "Praise & Quality"),
    ("douteki na", "どうてきな", "ドウテキナ", "動的な", "dynamic / animated / kinetic", "na-adjective", "Conditions & States"),
    # E
    ("eikyuu no", "えいきゅうの", "エイキュウノ", "永久の", "eternal / everlasting peace", "na-adjective", "Speed & Time"),
    ("eisei no", "えいせいの", "エイセイノ", "衛星の", "satellite-borne / celestial", "na-adjective", "Places & Spatial"),
    ("ekitai no", "えきたいの", "エキタイノ", "液体の", "liquid fluid state", "na-adjective", "Conditions & States"),
    ("ekonomii na", "えこのみーな", "エコノミーナ", "経済的な", "economical / thrift-friendly", "na-adjective", "Shopping & Money"),
    ("enerugisshu na", "えねるぎっしゅな", "エネルギッシュナ", "エネルギッシュな", "energetic / full of stamina", "na-adjective", "Character & Personality"),
    ("enshin-teki na", "えんしんてきな", "エンシンテキナ", "遠心的な", "centrifugal in motion", "na-adjective", "Conditions & States"),
    # F
    ("fuan-teki na", "ふあんてきな", "フアンテキナ", "不安定な", "unstable / precarious balance", "na-adjective", "Conditions & States"),
    ("fuhen-teki na", "ふへんてきな", "フヘンテキナ", "普遍的な", "universal / all-embracing truth", "na-adjective", "Praise & Quality"),
    ("fujiyuu na", "ふじゆうな", "フジユウナ", "不自由な", "inconvenienced / disabled / restricted", "na-adjective", "Conditions & States"),
    ("fukashin na", "ふかしんな", "フカシンナ", "不審な", "suspicious vehicle / shady stranger", "na-adjective", "Safety & Health"),
    ("fuketsu-goku na", "ふけつな", "フケツナ", "不潔極まりない", "utterly squalid / unsanitary", "na-adjective", "Safety & Health"),
    ("fukyuu no", "ふきゅうの", "フキュウノ", "不朽の", "immortal masterpiece of art", "na-adjective", "Praise & Quality"),
    ("fumeiryou na", "ふめいりょうな", "フメイリョウナ", "不明瞭な", "unclear voice / blurred photo", "na-adjective", "Character & Clarity"),
    ("funinshou na", "ふにんきな", "フニンキナ", "不人気な", "unpopular policy", "na-adjective", "Social & Communication"),
    ("fusei na", "ふせいな", "フセイナ", "不正な", "illicit / corrupt / fraudulent", "na-adjective", "Character & Personality"),
    ("fushin na", "ふしんな", "フシンナ", "不振な", "sluggish economy / slump", "na-adjective", "Conditions & States"),
    ("fushou no", "ふしょうの", "フショウノ", "負傷の", "injured / wounded", "na-adjective", "Body & Health"),
    ("futou-mei na", "ふとうめいな", "フトウメイナ", "不透明な", "opaque frosted glass / murky future", "na-adjective", "Appearance & Style"),
    ("fuyou na", "ふような", "フヨウナ", "不要な", "unneeded / superfluous / disposable", "na-adjective", "Conditions & States"),
    # G
    ("gainen-teki na", "がいねんてきな", "ガイネンテキナ", "概念的な", "conceptual / theoretical", "na-adjective", "Work & Study"),
    ("gakujutsu-teki na", "がくじゅつてきな", "ガクジュツテキナ", "学術的な", "academic / scientific thesis", "na-adjective", "Work & Study"),
    ("genba no", "げんばの", "ゲンバノ", "現場の", "on-the-scene / field-based", "na-adjective", "Work & Study"),
    ("genshuku na", "げんしゅくな", "ゲンシュクナ", "厳粛な", "solemn / grave / austere ceremony", "na-adjective", "Culture & Society"),
    ("gimon-darake no", "ぎもんだらけの", "ギモンダラケノ", "疑問だらけの", "riddled with questions", "na-adjective", "Difficulty & Ease"),
    ("giri-chou no", "ぎりの", "ギリノ", "義理の", "in-law relationship", "na-adjective", "People & Family"),
    ("gouin na", "ごういんな", "ゴウインナ", "強引な", "pushy / coercive / heavy-handed", "na-adjective", "Character & Personality"),
    ("goukaku no-exam", "ごうかくすいじゅんの", "ゴウカクスイジュンノ", "合格基準の", "meeting passing marks", "na-adjective", "Work & Study"),
    ("guranpuri no", "ぐらんぷりの", "グランプリノ", "最優秀の", "grand-prix champion quality", "na-adjective", "Praise & Quality"),
    # H
    ("haikara-san no", "はいからな", "ハイカラナ", "ハイカラな風情の", "charmingly retro-modern", "na-adjective", "Appearance & Style"),
    ("hakusetsu no", "はくせつの", "ハクセツノ", "白雪の", "snow-covered / snowy white", "na-adjective", "Colors & Styles"),
    ("han-teki na", "はんてきな", "ハンテキナ", "模範的な", "exemplary / model student", "na-adjective", "Praise & Quality"),
    ("han'ei shita", "はんえいした", "ハンエイシタ", "繁栄した", "prosperous / flourishing town", "na-adjective", "Conditions & States"),
    ("haru-urara na", "はるうららな", "ハルウララナ", "春うららかな", "gloriously mild and sunny spring", "na-adjective", "Weather & Climate"),
    ("hatsubai-chuu no", "はつばいちゅうの", "ハツバイチュウノ", "発売中の", "currently on sale on market", "na-adjective", "Shopping & Money"),
    ("heibon na", "へいぼんな", "ヘイボンナ", "凡庸な", "commonplace / run-of-the-mill", "na-adjective", "Appearance & Quality"),
    ("heisa-teki na", "へいさてきな", "ヘイサテキナ", "閉鎖的な", "clannish / insular / exclusive", "na-adjective", "Character & Personality"),
    ("heisoku na", "へいそくな", "ヘイソクナ", "閉塞した", "stifled / bogged down", "na-adjective", "Conditions & States"),
    ("henpin no dekinai", "へんぴんのできない", "ヘンピンノデキナイ", "返品不可の", "non-returnable merchandise", "na-adjective", "Shopping & Money"),
    ("hi-kagaku-teki na", "ひかがくてきな", "ヒカガクテキナ", "非科学的な", "unscientific superstition", "na-adjective", "Work & Study"),
    ("hi-koushiki na", "ひこうしきな", "ヒコウシキナ", "非公式な", "informal / off-the-record chat", "na-adjective", "Social & Communication"),
    ("hiai ni michita", "ひあいにみちた", "ヒアイニミチタ", "悲哀に満ちた", "steeped in melancholy pathos", "na-adjective", "Feelings & Mood"),
    ("hikou-teki na", "ひこうてきな", "ヒコウテキナ", "非行の", "delinquent / wayward youth", "na-adjective", "Character & Personality"),
    ("himei no you na", "ひめいのような", "ヒメイノヨウナ", "悲鳴のような", "shriek-like high-pitched scream", "na-adjective", "Appearance & Style"),
    ("hinkaku no aru", "ひんかくのある", "ヒンカクノアル", "品格のある", "dignified / possessing true class", "na-adjective", "Praise & Quality"),
    ("hisou na", "ひそうな", "ヒソウナ", "悲壮な", "tragic yet heroic determination", "na-adjective", "Feelings & Mood"),
    ("hitou no", "ひとうの", "ヒトウノ", "秘湯の", "hidden secluded hot spring bath", "na-adjective", "Places & Spatial"),
    ("hitsuzen-teki na", "ひつぜんてきな", "ヒツゼンテキナ", "必然的な", "inevitable / preordained by destiny", "na-adjective", "Conditions & States"),
    ("hogo-teki na", "ほごてきな", "ホゴテキナ", "保護的な", "overprotective / sheltering", "na-adjective", "Character & Personality"),
    ("hokenshou no", "ほけんしょうの", "ホケンショウノ", "保険証の", "health insurance-covered", "na-adjective", "Safety & Health"),
    ("honmono no", "ほんものの", "ホンモノノ", "真正の", "bona fide / genuine article", "na-adjective", "Praise & Quality"),
    ("houki-teki na", "ほうきてきな", "ホウキテキナ", "放棄された", "abandoned / neglected lot", "na-adjective", "Conditions & States"),
    ("houman na", "ほうまんな", "ホウマンナ", "豊満な", "plump / well-rounded figure", "na-adjective", "Appearance & Style"),
    ("hyoumen-teki na", "ひょうめんてきな", "ヒョウメンテキナ", "表面的な", "superficial / skin-deep inspection", "na-adjective", "Character & Clarity"),
    # I
    ("i-bunka no", "いぶんかの", "イブンカノ", "異文化の", "cross-cultural / foreign culture", "na-adjective", "Culture & Society"),
    ("ichidai no", "いちだいの", "イチダイノ", "一代限りの", "once-in-a-lifetime genius", "na-adjective", "Praise & Quality"),
    ("idou-shiki no", "いどうしきの", "イドウシキノ", "移動式の", "mobile / transportable cart", "na-adjective", "Conditions & States"),
    ("ijou na", "いじょうな", "イジョウナ", "異常な", "unusual / abnormal heat wave", "na-adjective", "Degree & Intensity"),
    ("ikada no you na", "いかだのような", "イカダノヨウナ", "筏のような", "raft-like floating deck", "na-adjective", "Appearance & Style"),
    ("ikoi no", "いこいの", "イコイノ", "憩いの", "relaxing restful sanctuary", "na-adjective", "Feelings & Mood"),
    ("ikura de mo aru", "いくらでもある", "イクラデモアル", "幾らでもある", "countless / abundant in supply", "i-adjective", "Degree & Intensity"),
    ("inshou-bukai", "いんしょうぶかい", "インショウブカイ", "印象深い", "unforgettable / deeply memorable", "i-adjective", "Feelings & Mood"),
    ("intiki na", "いんちな", "インチキナ", "インチキな", "phony / sham / fraudulent bogus", "na-adjective", "Character & Personality"),
    ("ippon no", "いっぽんの", "イッポンノ", "単一の", "single linear / straight line", "na-adjective", "Size & Shape"),
    ("irokui na", "いろけのない", "イロケノナイ", "色気のない", "austere / unglamorous / unromantic", "i-adjective", "Appearance & Style"),
    ("iron na", "いろいろな", "イロイロナ", "種々様々な", "diverse and manifold kinds", "na-adjective", "Conditions & States"),
    ("ishou no gousho na", "いしょうのごうかな", "イショウノゴウカナ", "衣装の豪華な", "dressed in lavish costume", "na-adjective", "Appearance & Style"),
    ("isshou-kenmei na", "いっしょうけんめいな", "イッショウケンメイナ", "一生懸命な", "wholehearted / giving one's all", "na-adjective", "Character & Personality"),
    ("itan no", "いたんの", "イタンノ", "異端の", "heretical / unorthodox thinker", "na-adjective", "Character & Personality"),
    ("itoko-doushi no", "いとこどうしの", "イトコドウシノ", "従兄弟同士の", "among cousins", "na-adjective", "People & Family"),
    # J
    ("jiba no", "じばの", "ジバノ", "地場の", "locally grown / homegrown produce", "na-adjective", "Food & Taste"),
    ("jidou no", "じどうの", "ジドウノ", "自動の", "automatic / sensor-activated", "na-adjective", "Appearance & Quality"),
    ("jika-seizo no", "じかせいの", "ジカセイノ", "自家製の", "homemade / handcrafted in-house", "na-adjective", "Food & Taste"),
    ("jiko-chuushin na", "じこちゅうしんな", "ジコチュウシンナ", "自己中心的な", "self-centered / egotistical", "na-adjective", "Character & Personality"),
    ("jikkan no komotta", "じっかんのこもった", "ジッカンノコモッタ", "実感のこもった", "heartfelt / spoken from experience", "na-adjective", "Social & Communication"),
    ("jinshu no", "じんしゅの", "ジンシュノ", "人種の", "racial / ethnic background", "na-adjective", "People & Family"),
    ("jishin no nai", "じしんのない", "ジシンノナイ", "自信のない", "diffident / lacking self-belief", "i-adjective", "Feelings & Mood"),
    ("joubu de nagamochi", "じょうぶでながもちする", "ジョウブデナガモチスル", "長持ちする", "sturdy and long-lasting durability", "na-adjective", "Appearance & Quality"),
    ("jouju shita", "じょうじゅした", "ジョウジュシタ", "成就した", "wish come true / fulfilled", "na-adjective", "Praise & Quality"),
    ("jouren no", "じょうれんの", "ジョウレンノ", "常連の", "regular patron / frequent visitor", "na-adjective", "People & Family"),
    ("juunbun-sugiru", "じゅうぶんすぎる", "ジュウブンスギル", "十分すぎる", "more than enough / overabundant", "i-adjective", "Degree & Intensity"),
    ("jyakuten no nai", "じゃくてんのない", "ジャクテンノナイ", "弱点のない", "impregnable / without weak spot", "i-adjective", "Praise & Quality"),
    # K
    ("kaerimichi no", "かえりみちの", "カエリミチノ", "帰り道の", "on the way home", "na-adjective", "Movement & Travel"),
    ("kagaku-teki na", "かがくてきな", "カガクテキナ", "科学的な", "scientific / grounded in empiricism", "na-adjective", "Work & Study"),
    ("kaigai-muke no", "かいがいむけの", "カイガイムケノ", "海外向けの", "designed for overseas markets", "na-adjective", "Culture & Society"),
    ("kaikatsu na", "かいかつな", "カイカツナ", "快活な", "chirpy / sunny and spirited", "na-adjective", "Appearance & Mood"),
    ("kaisen no umai", "かいせんのうまい", "カイセンノウマイ", "海鮮の美味い", "renowned for luscious seafood", "i-adjective", "Food & Taste"),
    ("kaito-teki na", "かいとうてきな", "カイトウテキナ", "快刀乱麻の", "decisive / cleanly resolving knot", "na-adjective", "Praise & Quality"),
    ("kaiwa-teki na", "かいわてきな", "カイワテキナ", "対話的な", "conversational / dialogic in tone", "na-adjective", "Social & Communication"),
    ("kakudai shita", "かくだいした", "カクダイシタ", "拡大した", "enlarged / expanded in scope", "na-adjective", "Size & Shape"),
    ("kakuritsu no takai", "かくりつのたかい", "カクリツノタカイ", "確率の高い", "highly probable / odds-on", "i-adjective", "Character & Clarity"),
    ("kamaboko-shaped", "かまぼこがたの", "カマボコガタノ", "蒲鉾型の", "semi-cylindrical arch vaulted", "na-adjective", "Size & Shape"),
    ("kanzen na", "かんぜんな", "カンゼンナ", "完全な", "complete / thoroughgoing / intact", "na-adjective", "Praise & Quality"),
    ("kao-iro no ii", "かおいろのいい", "カオイロノイイ", "顔色のいい", "healthy complexioned / looking well", "i-adjective", "Safety & Health"),
    ("karada ni ii", "からだにいい", "カラダニイイ", "体にいい", "wholesome / beneficial to health", "i-adjective", "Safety & Health"),
    ("kasou-teki na", "かそうてきな", "カソウテキナ", "仮想的な", "virtual / simulated in software", "na-adjective", "Conditions & States"),
    ("katei-teki na", "かていてきな", "カテイテキナ", "家庭的な", "homely / family-oriented atmosphere", "na-adjective", "Home & Living"),
    ("kayou ni tekishita", "かようにてきした", "カヨウニテキシタ", "通勤に適した", "well-suited for daily commute", "na-adjective", "Conditions & States"),
    ("kaze-tooshi no ii", "かぜとおしのいい", "カゼトオシノイイ", "風通しのいい", "well-ventilated / transparent culture", "i-adjective", "Home & Living"),
    ("keiken-asai", "けいけんのあさい", "ケイケンノアサイ", "経験の浅い", "inexperienced / greenhorn newcomer", "i-adjective", "Work & Study"),
    ("keishiki-teki na", "けいしきてきな", "ケイシキテキナ", "形式的な", "pro-forma / perfunctory formalities", "na-adjective", "Social & Communication"),
    ("keizai-teki na", "けいざいてきな", "ケイザイテキナ", "経済的な", "thrifty / financially sound", "na-adjective", "Shopping & Money"),
    ("kekkai no you na", "けっかいのような", "ケッカイノヨウナ", "結界のような", "barrier-like protective silence", "na-adjective", "Conditions & States"),
    ("kenchiku-teki na", "けんちくてきな", "ケンチクテキナ", "建築的な", "architectural / structural beauty", "na-adjective", "Appearance & Style"),
    ("ketsueki-gata no", "けつえきがたの", "ケツエキガタノ", "血液型の", "blood-type personality profile", "na-adjective", "People & Family"),
    ("kibou no moteru", "きぼうのもてる", "キボウノモテル", "希望の持てる", "promising / full of optimistic cheer", "i-adjective", "Feelings & Mood"),
    ("kigaru na", "きがるな", "キガルナ", "気軽な", "casual / lighthearted / carefree", "na-adjective", "Feelings & Mood"),
    ("kigen no ii", "きげんのいい", "キゲンノイイ", "機嫌のいい", "in high good humor / pleased", "i-adjective", "Appearance & Mood"),
    ("kigen no warui", "きげんのわるい", "キゲンノワルイ", "機嫌の悪い", "in foul moody humor / grouchy", "i-adjective", "Appearance & Mood"),
    ("kikaku-gai no", "きかくがいの", "キカクガイノ", "規格外の", "off-standard / out of the box", "na-adjective", "Appearance & Quality"),
    ("kikaku-teki na", "きかくてきな", "キカクテキナ", "計画的な", "well-planned / premeditated", "na-adjective", "Work & Study"),
    ("kiki-hakai na", "ききはくはくな", "キキハクハクナ", "危機迫る", "crisis-laden / critical threshold", "na-adjective", "Safety & Health"),
    ("kimochi no ii", "きもちのいい", "キモチノイイ", "気持ちのいい", "pleasant / comfortable breeze / fine feeling", "i-adjective", "Feelings & Mood"),
    ("kimochi no warui", "きもちのわるい", "キモチノワルイ", "気持ちの悪い", "queasy / nauseating / creepily off", "i-adjective", "Feelings & Mood"),
    ("kinchou shita", "きんちょうした", "キンチョウシタ", "緊張した", "nervous / strained / on edge", "na-adjective", "Feelings & Mood"),
    ("kinki no", "きんきの", "キンキノ", "近畿の", "Kansai Kinki regional identity", "na-adjective", "Places & Spatial"),
    ("kinniku-shitsu na", "きんにくしつな", "キンニクシツナ", "筋肉質な", "muscular / athletic build", "na-adjective", "Appearance & Style"),
    ("kinou no you na", "きのうのような", "キノウノヨウナ", "昨日のような", "as if it were only yesterday", "na-adjective", "Speed & Time"),
    ("kirei-zuki na", "きれいずきな", "キレイズキナ", "綺麗好きな", "fond of tidiness / cleanliness fanatic", "na-adjective", "Character & Personality"),
    ("kiroku-yaburi no", "きろくやぶりの", "キロクヤブリノ", "記録破りの", "groundbreaking / record-shattering", "na-adjective", "Praise & Quality"),
    ("kisoku-tadashii", "きそくただしい", "キソクタダシイ", "規則正しい", "orderly / methodical / regular rhythm", "i-adjective", "Character & Personality"),
    ("kizuna no fukai", "きずなのふかい", "キズナノフカイ", "絆の深い", "bound by deep heartfelt ties", "i-adjective", "Social & Communication"),
    ("kodawari-nuki no", "こだわりぬいた", "コダワリヌイタ", "こだわり抜いた", "crafted with unyielding dedication", "na-adjective", "Praise & Quality"),
    ("kokorozashi no takai", "こころざしのたかい", "ココロザシノタカイ", "志の高い", "high-minded / having noble ideals", "i-adjective", "Character & Personality"),
    ("kokusai-shoku yutaka na", "こくさいしょくゆたかな", "コクサイショクユタカナ", "国際色豊かな", "cosmopolitan / multi-ethnic charm", "na-adjective", "Culture & Society"),
    ("kousei na", "こうせいな", "コウセイナ", "公正な", "fair-minded / impartial / just", "na-adjective", "Character & Personality"),
    ("kouyuu no", "こうゆうの", "コウユウノ", "固有の", "inherent / unique to the region", "na-adjective", "Conditions & States"),
    ("kudamono-zuki na", "くだものずきな", "クダモノズキナ", "果物好きな", "fond of sweet seasonal fruit", "na-adjective", "Food & Taste"),
    ("kufuu o korashita", "くふうをこらした", "クフウヲコラシタ", "工夫を凝らした", "ingeniously devised / clever setup", "na-adjective", "Praise & Quality"),
    ("kurogoma no koubashii", "くろごまのこうばしい", "クロゴマノコウバシイ", "香ばしい", "aromatic black sesame aroma", "i-adjective", "Food & Taste"),
    ("kusuri-kikime no", "くすりのきく", "クスリノキク", "薬効のある", "medically efficacious", "i-adjective", "Safety & Health"),
    ("kyoudou no", "きょうどうの", "キョウドウノ", "共同の", "joint / cooperative / shared ownership", "na-adjective", "Social & Communication"),
    ("kyouko na", "きょうこな", "キョウコナ", "強固な", "impregnable / rock-solid fortress", "na-adjective", "Appearance & Quality"),
    ("kyuujitsu-kibun no", "きゅうじつきぶんの", "キュウジツキブンノ", "休日気分の", "in relaxed holiday weekend mood", "na-adjective", "Feelings & Mood")
]
