# Additional authentic Japanese adjectives (A-Z) to surpass 1,600+ adjectives
# (romaji, hiragana, katakana, kanji, meaning, type, topic)
DATA = [
    # A
    ("abunage no nai", "あぶなげのない", "アブナゲノナイ", "危なげのない", "steady / trustworthy / without danger", "i-adjective", "Safety & Health"),
    ("adorikomu", "あくのない", "アクノナイ", "灰汁のない", "mellow / free of harshness or malice", "i-adjective", "Personality & Trait"),
    ("aenai", "あえない", "アエナイ", "敢えない", "tragic / disappointing / fleeting", "i-adjective", "Feelings & Mood"),
    ("afureru bakari no", "あふれるばかりの", "アフレルバカリノ", "溢れるばかりの", "brimming over with / overflowing", "na-adjective", "Quantity & Degree"),
    ("aikurushii", "あいくるしい", "アイクルシイ", "愛くるしい", "adorable / charming / cute", "i-adjective", "Appearance & Style"),
    ("aiso no nai", "あいそのない", "アイソノナイ", "愛想のない", "curt / unfriendly / aloof", "i-adjective", "Personality & Trait"),
    ("akarasama na", "あからさまな", "アカラサマナ", "露骨な", "overt / undisguised / blatantly obvious", "na-adjective", "Manner & State"),
    ("akogare no", "あこがれの", "アコガレノ", "憧れの", "longed-for / admired / dreamy", "na-adjective", "Feelings & Mood"),
    ("akushu no nai", "あくしゅのない", "アクシュノナイ", "悪手のない", "sound / solid / free from blunder", "na-adjective", "Difficulty & Quality"),
    ("amaku kangaeru", "あまいみとおしの", "アマイミトオシノ", "甘い見通しの", "overly optimistic / naive", "na-adjective", "Difficulty & Quality"),
    ("amasa hikaeme na", "あまさひかえめな", "アマサヒカエメナ", "甘さ控えめな", "moderately sweet / subtly sweet", "na-adjective", "Food & Taste"),
    ("an'i na", "あんいな", "アンイナ", "安易な", "easygoing / simplistic / lighthearted", "na-adjective", "Difficulty & Quality"),
    ("anzen daiichi no", "あんぜんだいいちの", "アンゼンダライイチノ", "安全第一の", "safety-first / security focused", "na-adjective", "Safety & Health"),
    ("apparen na", "あっぱれな", "アッパレナ", "天晴れな", "splendid / commendable / admirable", "na-adjective", "Difficulty & Quality"),
    ("arata na", "あらたな", "アラタナ", "新たな", "brand new / fresh / unprecedented", "na-adjective", "Speed & Time"),
    ("arasoigataki", "あらそいがたい", "アラソイガタイ", "争いがたい", "undeniable / beyond dispute", "i-adjective", "Difficulty & Quality"),
    ("arigatami no aru", "ありがたみのある", "アリガタミノアル", "有難みのある", "precious / worth being grateful for", "na-adjective", "Feelings & Mood"),
    ("arisou de nai", "ありそうでない", "アリソウデナイ", "有りそうでない", "seemingly common yet rare", "i-adjective", "Quantity & Degree"),
    ("arufureta", "ありふれた", "アリフレタ", "有り触れた", "commonplace / mundane / ordinary", "na-adjective", "Difficulty & Quality"),
    ("asase no", "あさせの", "アサセノ", "浅瀬の", "shallow-water / reef-dwelling", "na-adjective", "Nature & Weather"),
    ("asekusai", "あせくさい", "アセクサイ", "汗臭い", "smelling of sweat / sweaty", "i-adjective", "Body & Senses"),
    ("assari shita aji no", "あっさりしたあじの", "アッサリシタアジノ", "あっさりした味の", "light and refreshing flavor", "na-adjective", "Food & Taste"),
    ("atataka-na hibi no", "あたたかなひびの", "アタタカナヒビノ", "暖かな日々の", "warm pleasant sunny days", "na-adjective", "Nature & Weather"),
    ("atarimae no", "あたりまえの", "アタリマエノ", "当たり前の", "natural / expected / common sense", "na-adjective", "Difficulty & Quality"),
    ("atsuku kataru", "あつくかたる", "アツクカタル", "熱意のこもった", "passionate / full of fervent zeal", "na-adjective", "Feelings & Mood"),
    ("ayamatta", "あやまった", "アヤマッタ", "誤った", "erroneous / mistaken / wrong", "na-adjective", "Difficulty & Quality"),
    ("azayaka sugiru", "あざやかすぎる", "アザヤカスギル", "鮮やかすぎる", "dazzlingly vivid / hyper-colorful", "na-adjective", "Appearance & Style"),

    # B
    ("baka-baka-shii", "ばかばかしい", "バカバカシイ", "馬鹿馬鹿しい", "absurd / silly / ridiculous", "i-adjective", "Difficulty & Quality"),
    ("bakudai na", "ばくだいな", "バクダイナ", "莫大な", "enormous / immense / vast sum", "na-adjective", "Quantity & Degree"),
    ("bakuzen to shita", "ばくぜんとした", "バクゼントシタ", "漠然とした", "vague / obscure / ambiguous", "na-adjective", "Difficulty & Quality"),
    ("ban-no na", "ばんのうな", "バンノウナ", "万能な", "all-purpose / versatile / omnipotent", "na-adjective", "Difficulty & Quality"),
    ("bassui no", "ばっすいの", "バッスイノ", "抜粋の", "excerpted / selected / key excerpts", "na-adjective", "Difficulty & Quality"),
    ("bimyona sa no", "びみょうなさの", "ビミョウナサノ", "微妙な差の", "nuanced / subtly distinguishable", "na-adjective", "Difficulty & Quality"),
    ("binbin kanjiru", "びんびんかんじる", "ビンビンカンジル", "ビンビン響く", "strongly resonant / vivid", "na-adjective", "Feelings & Mood"),
    ("bita ichimon nai", "びたいちもんない", "ビタイチモンナイ", "一文無しの", "completely broke / penniless", "na-adjective", "Home & Living"),
    ("bokantoshita", "ぼーっとした", "ボートシタ", "ぼんやりした", "absentminded / spaced-out", "na-adjective", "Feelings & Mood"),
    ("bousou gimi no", "ぼうそうぎみの", "ボウソウギミノ", "暴走気味の", "runaway / slightly uncontrollable", "na-adjective", "Manner & State"),
    ("bunseki-teki na", "ぶんせきてきな", "ブンセキテキナ", "分析的な", "analytical / systematic", "na-adjective", "Difficulty & Quality"),
    ("busu na", "ぶすな", "ブスナ", "不細工な", "homely / unstylish (colloquial)", "na-adjective", "Appearance & Style"),
    ("byoudou na", "びょうどうな", "ビョウドウナ", "平等な", "equal / impartial / fair", "na-adjective", "Difficulty & Quality"),

    # C
    ("chakujitsu na", "ちゃくじつな", "チャクジツナ", "着実な", "steady / trustworthy / sound", "na-adjective", "Personality & Trait"),
    ("chiisa sugiru", "ちいさすぎる", "チイサスギル", "小さすぎる", "much too miniature / cramped", "i-adjective", "Appearance & Style"),
    ("chika-chika suru", "ちかちかする", "チカチカスル", "チカチカ眩しい", "flickering / glaringly bright", "na-adjective", "Appearance & Style"),
    ("chikara-zuyoi", "ちからづよい", "チカラヅヨイ", "力強い", "powerful / vigorous / reassuring", "i-adjective", "Personality & Trait"),
    ("chimitsu na", "ちみつな", "チミツナ", "緻密な", "meticulous / elaborate / precise", "na-adjective", "Difficulty & Quality"),
    ("chitsujo aru", "ちつじょある", "チツジョアル", "秩序ある", "orderly / well-structured", "na-adjective", "Manner & State"),
    ("chotto shita", "ちょっとした", "チョットシタ", "一寸した", "slight / modest / little / trifling", "na-adjective", "Quantity & Degree"),
    ("choushi ga ii", "ちょうしがいい", "チョウシガイイ", "調子が良い", "in great shape / running smooth", "i-adjective", "Safety & Health"),
    ("choushi ga warui", "ちょうしがわるい", "チョウシガワルイ", "調子が悪い", "under the weather / out of tune", "i-adjective", "Safety & Health"),
    ("chouwa shita", "ちょうわした", "チョウワシタ", "調和した", "harmonious / well-balanced", "na-adjective", "Appearance & Style"),
    ("chuuto-hanpa na", "ちゅうとはんぱな", "チュウトハンパナ", "中途半端な", "half-baked / incomplete / unfinished", "na-adjective", "Difficulty & Quality"),

    # D
    ("daibutsuryou no", "だいぶつりょうの", "ダイブツリョウノ", "大物量の", "massive-volume / heavy-duty", "na-adjective", "Quantity & Degree"),
    ("daidaiiro no", "だいだいいろの", "ダイダイイロノ", "橙色の", "vibrant orange-colored", "na-adjective", "Appearance & Style"),
    ("daitou-ryoukyuu no", "だいとうりょうきゅうの", "ダイトウリョウキュウノ", "大統領級の", "presidential-caliber", "na-adjective", "Difficulty & Quality"),
    ("danbou no kiku", "だんぼうのきいた", "ダンボウノキイタ", "暖房の効いた", "comfortably heated (room)", "na-adjective", "Home & Living"),
    ("danryoku-sei aru", "だんりょくせいのある", "ダンリョクセイノアル", "弾力性のある", "resilient / springy / elastic", "na-adjective", "Appearance & Style"),
    ("datsuryoku shita", "だつりょくした", "ダツリョクシタ", "脱力した", "completely relaxed / limp / carefree", "na-adjective", "Feelings & Mood"),
    ("dekitate no", "できたての", "デキタテノ", "出来立ての", "freshly made / right out of the oven", "na-adjective", "Food & Taste"),
    ("denpa no ii", "でんぱのいい", "デンパノイイ", "電波の良い", "having good mobile phone reception", "i-adjective", "Speed & Time"),
    ("denpa no warui", "でんぱのわるい", "デンパノワルイ", "電波の悪い", "poor cellular signal", "i-adjective", "Speed & Time"),
    ("densen-sei no", "でんせんせいの", "デンセンセイノ", "伝染性の", "infectious / contagious", "na-adjective", "Safety & Health"),
    ("dokutoku sugiru", "どくとくすぎる", "ドクトクスギル", "独特すぎる", "uniquely eccentric / ultra-peculiar", "na-adjective", "Personality & Trait"),
    ("dokuzetsu na", "どくぜつな", "ドクゼツナ", "毒舌な", "sharp-tongued / caustically sarcastic", "na-adjective", "Personality & Trait"),
    ("donkan na", "どんかんな", "ドンカンナ", "鈍感な", "thick-skinned / obtuse / insensitive", "na-adjective", "Personality & Trait"),
    ("doryoku-ka no", "どりょくかの", "ドリョクカノ", "努力家の", "hardworking / diligent person", "na-adjective", "Personality & Trait"),

    # E
    ("eikyuteki na", "えいきゅうてきな", "エイキュウテキナ", "永久的な", "permanent / everlasting", "na-adjective", "Speed & Time"),
    ("eikyou-ryoku aru", "えいきょうりょくのある", "エイキョウリョクノアル", "影響力のある", "influential / impactful", "na-adjective", "Difficulty & Quality"),
    ("ekiteki na", "えきてきな", "エキテキナ", "劇的な", "dramatic / striking / theatrical", "na-adjective", "Appearance & Style"),
    ("enman na", "えんまんな", "エンマンナ", "円満な", "harmonious / amicable / peaceful", "na-adjective", "Personality & Trait"),
    ("enshou shita", "えんしょうした", "エンショウシタ", "炎症した", "inflamed / irritated", "na-adjective", "Safety & Health"),
    ("eri-batsu no", "えりすぐりの", "エリスグリノ", "選りすぐりの", "hand-picked / choice / select", "na-adjective", "Difficulty & Quality"),
    ("esute no kirei na", "えすてのきれいきれいな", "エステノキレイキレイナ", "エステで磨かれた", "glowingly pampered skin", "na-adjective", "Appearance & Style"),

    # F
    ("fuantei na", "ふあんていな", "フアンテイナ", "不安定な", "unstable / shaky / precarious", "na-adjective", "Difficulty & Quality"),
    ("fubyoudou na", "ふびょうどうな", "フビョウドウナ", "不平等な", "unfair / unequal / discriminatory", "na-adjective", "Difficulty & Quality"),
    ("fuchuui na", "ふちゅういな", "フチュウイナ", "不注意な", "careless / inadvertent / thoughtless", "na-adjective", "Personality & Trait"),
    ("fugou no", "ふごうの", "フゴウノ", "富豪の", "billionaire-wealthy / affluent", "na-adjective", "Difficulty & Quality"),
    ("fujiyuu na", "ふじゆうな", "フジユウナ", "不自由な", "inconvenient / restricted / disabled", "na-adjective", "Safety & Health"),
    ("fukami no aru", "ふかみのある", "フカミノアル", "深みのある", "deep / rich / profound / nuanced", "na-adjective", "Difficulty & Quality"),
    ("fukitsu na", "ふきつな", "フキツナ", "不吉な", "ominous / sinister / inauspicious", "na-adjective", "Feelings & Mood"),
    ("fukouhei na", "ふこうへいな", "フコウヘイナ", "不公平な", "unfair / biased / inequitable", "na-adjective", "Difficulty & Quality"),
    ("fukureta", "ふくれた", "フクレタ", "膨れた", "swollen / puffed-up / sulking", "na-adjective", "Appearance & Style"),
    ("fukusou no ii", "ふくそうのいい", "フクソウノイイ", "服装の好い", "well-dressed / smartly attired", "i-adjective", "Appearance & Style"),
    ("fumi no aru", "ふうみのある", "フウミノアル", "風味のある", "savory / flavorful / aromatic", "na-adjective", "Food & Taste"),
    ("funiki no yoi", "ふんいきのよい", "フンイキノヨイ", "雰囲気の良い", "having wonderful ambiance", "i-adjective", "Feelings & Mood"),
    ("fura-fura na", "ふらふらな", "フラフラナ", "フラフラな", "dizzy / unsteady on feet", "na-adjective", "Safety & Health"),
    ("fusei na", "ふせいな", "フセイナ", "不正な", "dishonest / corrupt / fraudulent", "na-adjective", "Difficulty & Quality"),
    ("fusoushou na", "ふそうおうな", "フソウオウナ", "不相応な", "unbecoming / disproportionate", "na-adjective", "Difficulty & Quality"),
    ("futou na", "ふとうな", "フトウナ", "不当な", "unjust / unwarranted / wrongful", "na-adjective", "Difficulty & Quality"),
    ("fuzei no aru", "ふぜいのある", "フゼイノアル", "風情のある", "quaint / tastefully picturesque", "na-adjective", "Appearance & Style"),

    # G
    ("gai no nai", "がいのない", "ガイノナイ", "害のない", "harmless / innocuous", "i-adjective", "Safety & Health"),
    ("gakumon-teki na", "がくもんてきな", "ガクモンテキナ", "学問的な", "academic / scholarly", "na-adjective", "Difficulty & Quality"),
    ("ganjou na", "がんじょうな", "ガンジョウナ", "頑丈な", "sturdy / robust / solid build", "na-adjective", "Appearance & Style"),
    ("ganko sugiru", "がんこすぎる", "ガンコスギル", "頑固すぎる", "bullheadedly stubborn", "na-adjective", "Personality & Trait"),
    ("gara no warui", "がらのわるい", "ガラノワルイ", "柄の悪い", "rowdy / bad-mannered / shady", "i-adjective", "Personality & Trait"),
    ("geijutsu-teki na", "げいじゅつてきな", "ゲイジュツテキナ", "芸術的な", "artistic / masterfully aesthetic", "na-adjective", "Appearance & Style"),
    ("genba no", "げんばの", "ゲンバノ", "現場の", "on-site / practical / hands-on", "na-adjective", "Difficulty & Quality"),
    ("genkaku na", "げんかくな", "ゲンカクナ", "厳格な", "strict / rigorous / stern discipline", "na-adjective", "Personality & Trait"),
    ("genmitsu na", "げんみつな", "ゲンミツナ", "厳密な", "strict / precise / rigorous truth", "na-adjective", "Difficulty & Quality"),
    ("genshou-teki na", "げんしょうてきな", "ゲンショウテキナ", "幻想的な", "dreamy / illusory / magical", "na-adjective", "Appearance & Style"),
    ("gikochinai", "ぎこちない", "ギコチナイ", "ぎこちない", "awkward / clumsy / stiff manner", "i-adjective", "Personality & Trait"),
    ("gouin na", "ごういんな", "ゴウインナ", "強引な", "pushy / forceful / coercive", "na-adjective", "Personality & Trait"),
    ("gouka-kenran na", "ごうかけんらんな", "ゴウカケンランナ", "豪華絢爛な", "magnificent and gorgeous", "na-adjective", "Appearance & Style"),
    ("goutei no", "ごうていの", "ゴウテイノ", "豪邸の", "palatial / mansion-scale", "na-adjective", "Home & Living"),
    ("guragura suru", "ぐらぐらする", "グラグラスル", "ぐらぐら揺れる", "wobbly / shaky / loose", "na-adjective", "Appearance & Style"),

    # H
    ("haigo no", "はいごの", "ハイゴノ", "背後の", "behind-the-scenes / rear", "na-adjective", "Manner & State"),
    ("hakarishirenai", "はかりしれない", "ハカリシレナイ", "計り知れない", "immeasurable / unfathomable", "i-adjective", "Quantity & Degree"),
    ("hakken no", "はっけんの", "ハッケンノ", "新発見の", "breakthrough / newly discovered", "na-adjective", "Difficulty & Quality"),
    ("hakuryoku man-ten", "はくりょくまんてんの", "ハクリョクマンテンノ", "迫力満点の", "jaw-droppingly powerful / thrilling", "na-adjective", "Appearance & Style"),
    ("hamigaki no joushu", "はみがきがじょうずな", "ハミガキガジョウズナ", "歯磨きの上手な", "great at tooth brushing hygiene", "na-adjective", "Safety & Health"),
    ("hanayaka na michi", "はなやかなみち", "ハナヤカナミチ", "華やかな街並みの", "bustling and glamorous downtown", "na-adjective", "Appearance & Style"),
    ("hangyaku-teki na", "はんぎゃくてきな", "ハンギャクテキナ", "反逆的な", "rebellious / defiant", "na-adjective", "Personality & Trait"),
    ("hantsuki-go no", "はんつきごの", "ハンツキゴノ", "半月後の", "two weeks hence", "na-adjective", "Speed & Time"),
    ("haritsumeta", "はりつめた", "ハリツメタ", "張り詰めた", "taut / tense / edge-of-seat atmosphere", "na-adjective", "Feelings & Mood"),
    ("hassei-shiyasui", "はっせいしやすい", "ハッセイシヤスイ", "発生しやすい", "prone to occurring / frequent", "i-adjective", "Difficulty & Quality"),
    ("hatten-teki na", "はってんてきな", "ハッテンテキナ", "発展的な", "progressive / constructive / developing", "na-adjective", "Difficulty & Quality"),
    ("haya-mawari no", "はやまわりの", "ハヤマワリノ", "早回しの", "fast-forwarded / rapid rotation", "na-adjective", "Speed & Time"),
    ("heibon sugiru", "へいぼんすぎる", "ヘイボンスギル", "平凡すぎる", "painfully mediocre / too ordinary", "na-adjective", "Difficulty & Quality"),
    ("heisateki na", "へいさてきな", "ヘイサテキナ", "閉鎖的な", "closed / insular / exclusive", "na-adjective", "Personality & Trait"),
    ("hendou no hageshii", "へんどうのはげしい", "ヘンドウノハゲシイ", "変動の激しい", "highly volatile / fluctuating", "i-adjective", "Quantity & Degree"),
    ("hidoku sabishii", "ひどくさびしい", "ヒドクサビシイ", "酷く寂しい", "intensely lonely / desolate", "i-adjective", "Feelings & Mood"),
    ("hifu no yawarakai", "ひふのやわらかい", "ヒフノヤワラカイ", "肌の柔らかい", "soft-skinned / velvety skin", "i-adjective", "Body & Senses"),
    ("hikaku-teki na", "ひかくてきな", "ヒカクテキナ", "比較的な", "comparative / relative", "na-adjective", "Difficulty & Quality"),
    ("hiken na", "ひけんな", "ヒケンナ", "卑見な", "modest humble opinion", "na-adjective", "Difficulty & Quality"),
    ("hikkuri-kaetta", "ひっくりかえった", "ヒックリカエッタ", "ひっくり返った", "upturned / flipped upside down", "na-adjective", "Appearance & Style"),
    ("hikutsu na", "ひくつな", "ヒクツナ", "卑屈な", "servile / self-deprecating / obsequious", "na-adjective", "Personality & Trait"),
    ("himekoma na", "ひめやかな", "ヒメヤカナ", "秘めやかな", "secretive / stealthy / hushed", "na-adjective", "Feelings & Mood"),
    ("hininshou no", "ひにんしょうの", "ヒニンショウノ", "非人称の", "impersonal (linguistic)", "na-adjective", "Difficulty & Quality"),
    ("hishimeku", "ひしめく", "ヒシメク", "密集した", "jam-packed / tightly crowded together", "na-adjective", "Quantity & Degree"),
    ("hitori-bocchi no", "ひとりぼっちの", "ヒトリボッチノ", "一人ぼっちの", "all alone / lonely solitary", "na-adjective", "Feelings & Mood"),
    ("hiwa na", "ひわな", "ヒワナ", "鄙猥な", "vulgar / unseemly / crass", "na-adjective", "Personality & Trait"),
    ("hokorashii egao no", "ほこらしいえがおの", "ホコラシイエガオノ", "誇らしい笑顔の", "with a beam of pure pride", "na-adjective", "Feelings & Mood"),
    ("honki-do no takai", "ほんきどのたかい", "ホンキドノタカイ", "本気度の高い", "dead serious / deeply committed", "i-adjective", "Feelings & Mood"),
    ("honmono-shikou no", "ほんものしこうの", "ホンモノシコウノ", "本物志向の", "seeking authentic premium quality", "na-adjective", "Difficulty & Quality"),
    ("horonigai", "ほろにがい", "ホロニガイ", "ほろ苦い", "bittersweet / mildly bitter memory", "i-adjective", "Food & Taste"),
    ("hoshuteki na", "ほしゅてきな", "ホシュテキナ", "保守的な", "conservative / traditionalist", "na-adjective", "Personality & Trait"),
    ("houba-yaki no", "ほうばやきのおいしい", "ホウバヤキノオイシイ", "朴葉味噌の香ばしい", "fragrant grilled magnolia leaf miso", "i-adjective", "Food & Taste"),
    ("hukakai na", "ふかかいな", "フカカイナ", "不可解な", "inexplicable / enigmatic / mysterious", "na-adjective", "Difficulty & Quality"),
    ("hyoujou-yutaka na", "ひょうじょうゆたかな", "ヒョウジョウユタカナ", "表情豊かな", "expressive / vivid facial expressions", "na-adjective", "Appearance & Style"),

    # I
    ("i-bukai", "いぶかしい", "イブカシイ", "訝しい", "suspicious / dubious / questionable", "i-adjective", "Feelings & Mood"),
    ("ichidai-kesshin no", "いちだいけっしんの", "イチダイケッシノ", "一大決心の", "life-defining momentous resolution", "na-adjective", "Feelings & Mood"),
    ("ichi-ryuu no", "いちりゅうの", "イチリュウノ", "一流の", "first-class / top-tier / world-class", "na-adjective", "Difficulty & Quality"),
    ("idai sugiru", "いだいすぎる", "イダイスギル", "偉大すぎる", "overwhelmingly grand / colossal", "na-adjective", "Difficulty & Quality"),
    ("ijou na", "いじょうな", "イジョウナ", "異常な", "abnormal / irregular / extraordinary", "na-adjective", "Difficulty & Quality"),
    ("ikiru kachi aru", "いきるかちのある", "イキルカチノアル", "生きる価値ある", "truly worth living for", "na-adjective", "Feelings & Mood"),
    ("ikitodokoita", "いきとどいた", "イキトドイタ", "行き届いた", "scrupulously attentive / well-maintained", "na-adjective", "Manner & State"),
    ("ikizukai no arai", "いきづかいのあらい", "イキヅカイノアライ", "息遣いの荒い", "breathing heavily / out of breath", "i-adjective", "Safety & Health"),
    ("inshou-bukai", "いんしょうぶかい", "インショウブカイ", "印象深い", "unforgettable / deeply memorable", "i-adjective", "Feelings & Mood"),
    ("ippanteki na", "いっぱんてきな", "イッパンテキナ", "一般的な", "general / widespread / conventional", "na-adjective", "Difficulty & Quality"),
    ("iron na", "いろいろな", "イロイロナ", "色々な", "various / manifold / all sorts of", "na-adjective", "Quantity & Degree"),
    ("itsuwari no nai", "いつわりのない", "イツワリノナイ", "偽りのない", "sincere / genuine / truthful", "i-adjective", "Personality & Trait"),

    # J
    ("jiden-teki na", "じでんてきな", "ジデンテキナ", "自伝的な", "autobiographical", "na-adjective", "Difficulty & Quality"),
    ("jigou-jitoku no", "じごうじとくの", "ジゴウジトクノ", "自業自得の", "serves you right / self-inflicted", "na-adjective", "Difficulty & Quality"),
    ("jikan-douri no", "じかんどおりの", "ジカンドオリノ", "時間通りの", "strictly on schedule / punctual", "na-adjective", "Speed & Time"),
    ("jikkuri kangaeta", "じっくりかんがえた", "ジックリカンガエタ", "熟慮した", "thoroughly thought-out / calculated", "na-adjective", "Difficulty & Quality"),
    ("jiko-chuu na", "じこちゅうな", "ジコチュウナ", "自己中な", "self-centered / selfish egoist", "na-adjective", "Personality & Trait"),
    ("jinkouteki na", "じんこうてきな", "ジンコウテキナ", "人工的な", "artificial / man-made / synthetic", "na-adjective", "Difficulty & Quality"),
    ("jitsuryoku-ha no", "じつりょくはの", "ジツリョクハノ", "実力派の", "competent / accomplished / verified talent", "na-adjective", "Difficulty & Quality"),
    ("jiyuu-honpou na", "じゆうほんぽうな", "ジユウホンポウナ", "自由奔放な", "free-spirited / uninhibited / bohemian", "na-adjective", "Personality & Trait"),
    ("joubu de nagamochi", "じょうぶでながもちする", "ジョウブデナガモチスル", "丈夫で長持ちな", "sturdy and long-lasting quality", "na-adjective", "Appearance & Style"),
    ("joushiki-hazure na", "じょうしきはずれな", "ジョウシキハズレナ", "常識外れな", "absurdly eccentric / beyond etiquette", "na-adjective", "Personality & Trait"),
    ("juubun sugiru", "じゅうぶんすぎる", "ジュウブンスギル", "十分すぎる", "more than ample / thoroughly generous", "na-adjective", "Quantity & Degree"),
    ("juudai na", "じゅうだいな", "ジュウダイナ", "重大な", "grave / crucial / serious consequence", "na-adjective", "Difficulty & Quality"),

    # K
    ("kaeriminu", "かえりみない", "カエリミナイ", "顧みない", "reckless / unconcerned with danger", "i-adjective", "Personality & Trait"),
    ("kagakuteki na", "かがくてきな", "カガクテキナ", "科学的な", "scientific / empirical", "na-adjective", "Difficulty & Quality"),
    ("kaigai-muke no", "かいがいむけの", "カイガイムケノ", "海外向けの", "designed for international export", "na-adjective", "Difficulty & Quality"),
    ("kakko-tsuketa", "かっこうつけた", "カッコウツケタ", "恰好つけた", "pretentious / showy / poseur", "na-adjective", "Personality & Trait"),
    ("kanketsu na", "かんけつな", "カンケツナ", "簡潔な", "concise / succinct / pithy", "na-adjective", "Difficulty & Quality"),
    ("kanzen-muketsu na", "かんぜんむけつな", "カンゼンムケツナ", "完全無欠な", "flawless / absolute perfection", "na-adjective", "Difficulty & Quality"),
    ("karei na", "かれいな", "カレイナ", "華麗な", "magnificent / splendiferous / ornate", "na-adjective", "Appearance & Style"),
    ("kekkouteki na", "けっこうな", "ケッコウナ", "結構な", "splendid / fine / sufficient", "na-adjective", "Difficulty & Quality"),
    ("ketahazure na", "けたはずれな", "ケタハズレナ", "桁外れな", "in a league of its own / off the charts", "na-adjective", "Quantity & Degree"),
    ("kihon-teki na", "きほんてきな", "キホンテキナ", "基本的な", "fundamental / basic / elemental", "na-adjective", "Difficulty & Quality"),
    ("kikenteki na", "きけんてきな", "キケンテキナ", "危険極まりない", "perilous to the extreme", "na-adjective", "Safety & Health"),
    ("kin'iro no kagayaki", "きんいろのかがやく", "キンイロノカガヤク", "金色の輝く", "gilded and lustrous golden", "na-adjective", "Appearance & Style"),
    ("kirabi-yaka na", "きらびやかな", "キラビヤカナ", "絢爛たる", "gorgeous / dazzling glitter", "na-adjective", "Appearance & Style"),
    ("kodawari no", "こだわりの", "コダワリノ", "こだわりの", "artisanal / meticulously curated", "na-adjective", "Difficulty & Quality"),
    ("kokyuu no fukai", "こきゅうのふかい", "コキュウノフカイ", "呼吸の深い", "measured, deeply steady breath", "i-adjective", "Safety & Health"),
    ("kosei-yutaka na", "こせいゆたかな", "コセイユタカナ", "個性豊かな", "full of distinct personality / quirky", "na-adjective", "Personality & Trait"),
    ("koukai no nai", "こうかいのない", "コウカイノナイ", "後悔のない", "with no regrets / clean conscience", "i-adjective", "Feelings & Mood"),
    ("kousei na", "こうせいな", "コウセイナ", "公正な", "just / equitable / impartial", "na-adjective", "Difficulty & Quality"),
    ("koutou-mukei na", "こうとうむけいな", "コウトウムケイナ", "荒唐無稽な", "preposterous / nonsensical", "na-adjective", "Difficulty & Quality"),
    ("kyokutan na", "きょくたんな", "キョクタanna", "極端な", "extreme / drastic / radical", "na-adjective", "Difficulty & Quality"),

    # M - Z
    ("ma-atarashii", "まあたらしい", "マアタラシイ", "真新しい", "brand-spanking new", "i-adjective", "Speed & Time"),
    ("makkura na", "まっくらな", "マックラナ", "真っ暗な", "pitch-black / completely dark", "na-adjective", "Appearance & Style"),
    ("mame na", "まめな", "マメナ", "忠実な", "attentive / conscientious / thoughtful", "na-adjective", "Personality & Trait"),
    ("manzoku-kan no takai", "まんぞくかんのたかい", "マンゾクカンノタカイ", "満足度の高い", "yielding high user satisfaction", "i-adjective", "Feelings & Mood"),
    ("meikaku na", "めいかくな", "メイカクナ", "明確な", "clear-cut / unambiguous / distinct", "na-adjective", "Difficulty & Quality"),
    ("meiryoushitai", "めいりょうな", "メイリョウナ", "明瞭な", "lucid / articulated / clear audio", "na-adjective", "Body & Senses"),
    ("mitsudo no takai", "みつどのたかい", "ミツドノタカイ", "密度の高い", "dense / closely packed / rich", "i-adjective", "Quantity & Degree"),
    ("mikakunin no", "みかくにんの", "ミカクニンノ", "未確認の", "unidentified / unconfirmed", "na-adjective", "Difficulty & Quality"),
    ("mijika na", "みぢかな", "ミヂカナ", "身近な", "familiar / close-at-hand / accessible", "na-adjective", "Manner & State"),
    ("miren-tarashii", "みれんたらかしい", "ミレンタラシイ", "未練がましい", "lingeringly regretful / clinging", "i-adjective", "Feelings & Mood"),
    ("mizumizushii", "みずみずしい", "ミズミズシイ", "瑞々しい", "succulent / juicy / dewy-fresh", "i-adjective", "Food & Taste"),
    ("muda no nai", "むだのない", "ムダノナイ", "無駄のない", "lean / streamlined / devoid of waste", "i-adjective", "Difficulty & Quality"),
    ("muga-muchuu no", "むがむちゅうの", "ムガムチュウノ", "無我夢中の", "totally absorbed / entranced", "na-adjective", "Feelings & Mood"),
    ("mukizu no", "むきずの", "ムキズノ", "無傷の", "unscratched / unscathed / mint condition", "na-adjective", "Safety & Health"),
    ("mumou na", "むもうな", "ムモウナ", "無謀な", "reckless / daredevil / foolhardy", "na-adjective", "Personality & Trait"),
    ("naiteki na", "ないてきな", "ナイテキナ", "内的な", "internal / inner / psychological", "na-adjective", "Feelings & Mood"),
    ("nama-yasashii", "なまやさしい", "ナマヤサシイ", "生易しい", "easy / soft / pushover", "i-adjective", "Difficulty & Quality"),
    ("nando mo kiita", "なんどもきいた", "ナンドモキイタ", "聞き慣れた", "well-worn / familiar refrain", "na-adjective", "Body & Senses"),
    ("nikurashii", "にくらしい", "ニクラシイ", "憎らしい", "infuriating yet cheeky / provoking", "i-adjective", "Feelings & Mood"),
    ("nijuu-kouzou no", "にじゅうこうぞうの", "ニジュウコウゾウノ", "二重構造の", "double-walled / double-layered", "na-adjective", "Appearance & Style"),
    ("omoi-tsukanai", "おもいつかない", "オモイツカナイ", "思いも寄らない", "unfathomable / unanticipated", "i-adjective", "Difficulty & Quality"),
    ("onwa na", "おんわな", "オンワナ", "温和な", "mild / gentle climate or disposition", "na-adjective", "Nature & Weather"),
    ("rakuten-teki na", "らくてんてきな", "ラクテンテキナ", "楽天的な", "optimistic / cheerful / sunny-sided", "na-adjective", "Personality & Trait"),
    ("reisai na", "れいさいな", "レイサイナ", "零細な", "micro / small-scale / artisanal", "na-adjective", "Quantity & Degree"),
    ("renzoku-teki na", "れんぞくてきな", "レンゾクテキナ", "連続的な", "continuous / uninterrupted / series", "na-adjective", "Speed & Time"),
    ("risou-teki na", "りそうてきな", "リソウテキナ", "理想的な", "ideal / quintessential / perfect model", "na-adjective", "Difficulty & Quality"),
    ("seichou-zakarino", "せいちょうざかりの", "セイチョウザカリノ", "成長盛りの", "in rapid growth spurt phase", "na-adjective", "Speed & Time"),
    ("shakai-teki na", "しゃかいてきな", "シャカイテキナ", "社会的な", "social / civic / public-facing", "na-adjective", "Difficulty & Quality"),
    ("shinpi-teki na", "しんぴてきな", "シンピテキナ", "神秘的な", "mystical / arcane / enchanting", "na-adjective", "Appearance & Style"),
    ("shinjitsu no", "しんじつの", "シンジツノ", "真実の", "true / authentic / genuine truth", "na-adjective", "Difficulty & Quality"),
    ("shunkan-teki na", "しゅんかんてきな", "シュンカンテキナ", "瞬間的な", "instantaneous / fleeting moment", "na-adjective", "Speed & Time"),
    ("souzouryoku-yutaka", "そうぞうりょくゆたかな", "ソウゾウリョクユタカナ", "想像力豊かな", "highly imaginative / visionary", "na-adjective", "Personality & Trait"),
    ("taikyuu-sei no aru", "たいきゅうせいのある", "タイキュウセイノアル", "耐久性のある", "durable / heavy-duty / wear-resistant", "na-adjective", "Appearance & Style"),
    ("tekisetsu na", "てきせつな", "テキセツナ", "適切な", "appropriate / fitting / pertinent", "na-adjective", "Difficulty & Quality"),
    ("touzen no", "とうぜんの", "トウゼンノ", "当然の", "natural / expected / well-deserved", "na-adjective", "Difficulty & Quality"),
    ("ugoki-yasui", "うごきやすい", "ウゴキヤスイ", "動きやすい", "easy to move in / comfortable activewear", "i-adjective", "Appearance & Style"),
    ("unmei-teki na", "うんめいてきな", "ウンメイテキナ", "運命的な", "fateful / destined / serendipitous", "na-adjective", "Feelings & Mood"),
    ("wasure-gatai", "わすれがたい", "ワスレガタイ", "忘れ難い", "unforgettable / etched in memory", "i-adjective", "Feelings & Mood"),
    ("yousha no nai", "ようしゃのない", "ヨウシャノナイ", "容赦のない", "relentless / merciless / uncompromising", "i-adjective", "Personality & Trait"),
    ("yuueki na", "ゆうえきな", "ユウエキナ", "有益な", "beneficial / informative / valuable", "na-adjective", "Difficulty & Quality"),
    ("yuukan na", "ゆうかんな", "ユウカンナ", "勇敢な", "brave / courageous / valiant", "na-adjective", "Personality & Trait"),
    ("zenryoku no", "ぜんりょくの", "ゼンリョクノ", "全力の", "all-out / full throttle effort", "na-adjective", "Feelings & Mood"),
]
