# Extended Authentic Japanese Adjectives (420+ items covering full alphabet)
DATA = [
    # M
    ("madoromi no", "まどろみの", "マドロミノ", "微睡みの", "drowsy / half-asleep in sun", "na-adjective", "Feelings & Mood"),
    ("mae-muki na", "まえむきな", "マエムキナ", "前向きな", "forward-looking / positive spirit", "na-adjective", "Character & Personality"),
    ("makka na-sun", "あかねいろの", "アカネイロノ", "茜色の", "sunset madder-red hue", "na-adjective", "Colors & Styles"),
    ("makura no yawarakai", "まくらのやわらかい", "マクラノヤワラカイ", "枕の柔らかい", "having soft comfy pillow", "i-adjective", "Home & Living"),
    ("mame na", "まめな", "マメナ", "忠実な", "attentive / hardworking / thoughtful", "na-adjective", "Character & Personality"),
    ("mamire no", "まみれの", "マミレノ", "塗れの", "covered in mud or dust", "na-adjective", "Conditions & States"),
    ("manpuku no", "まんぷくの", "マンプクノ", "満腹の", "pleasantly full / satiated belly", "na-adjective", "Food & Taste"),
    ("manten no", "まんてんの", "マンテンノ", "満点の", "perfect-score / top-rated grade", "na-adjective", "Praise & Quality"),
    ("masshiro na-snow", "ゆきのしろい", "ユキノシロイ", "白雪の", "snowy white", "i-adjective", "Colors & Styles"),
    ("matcha-aji no", "まっちゃあじの", "マッチャアジノ", "抹茶味の", "matcha green tea flavored", "na-adjective", "Food & Taste"),
    ("matsuri-zuki na", "まつりずきな", "マツリズキナ", "祭り好きな", "fond of traditional festivals", "na-adjective", "Culture & Society"),
    ("mayoigokoro no", "まよいのある", "マヨイノアル", "迷いのある", "hesitant / wavering in mind", "i-adjective", "Emotions & Mind"),
    ("mecha na", "めちゃな", "メチャナ", "無茶な", "reckless / absurd / outrageous", "na-adjective", "Character & Personality"),
    ("medatsu-looking", "ひときわめだつ", "ヒトキワメダツ", "一際目立つ", "exceptionally conspicuous", "na-adjective", "Appearance & Style"),
    ("meisou-teki na", "めいそうてきな", "メイソウテキナ", "瞑想的な", "meditative / contemplative / serene", "na-adjective", "Feelings & Mood"),
    ("meiyo aru", "めいよある", "メイヨアル", "名誉ある", "honorable / illustrious award", "na-adjective", "Praise & Quality"),
    ("menrui no umai", "めんるいのうまい", "メンルイノウマイ", "麺類の美味い", "famous for delicious noodles", "i-adjective", "Food & Taste"),
    ("mentaiko no karai", "めんたいこのからい", "メンタイコノカライ", "明太子の辛い", "spicy like seasoned pollack roe", "i-adjective", "Food & Taste"),
    ("meron-kaori no", "めろんのかおる", "メロンノカオル", "メロン香る", "melon-scented / sweet aroma", "na-adjective", "Food & Taste"),
    ("michi-tashite iru", "みちたりた", "ミチタリタ", "満ち足りた", "fully content / serene bliss", "na-adjective", "Feelings & Mood"),
    ("midori-yutaka na", "みどりゆたかな", "ミドリユタカナ", "緑豊かな", "lush and leafy green environment", "na-adjective", "Places & Spatial"),
    ("migoto na", "みごとな", "ミゴトナ", "見事な", "splendid / admirable performance", "na-adjective", "Praise & Quality"),
    ("mijika na", "みぢかな", "ミヂカナ", "身近な", "familiar / close at hand in daily life", "na-adjective", "Conditions & States"),
    ("mikan-iro no", "みかんいろの", "ミカンイロノ", "蜜柑色の", "tangerine orange color", "na-adjective", "Colors & Styles"),
    ("mimi-zamawari na", "みみざわりな", "ミミザワリナ", "耳障りな", "jarring / offensive to the ear", "na-adjective", "Perception & Senses"),
    ("minami-muke no", "みなみむきの", "ミナミムキノ", "南向きの", "south-facing sunny balcony", "na-adjective", "Places & Spatial"),
    ("miryoku no aru", "みりょくのある", "ミリョクノアル", "魅力のある", "charming / captivating person", "na-adjective", "Appearance & Style"),
    ("misoshiru no atatakai", "みそしるのあたたかい", "ミソシルノアタタカイ", "味噌汁の温かい", "with warm comfort of miso soup", "i-adjective", "Food & Taste"),
    ("mitarashi no amai", "みたらしのあまい", "ミタラシノアマイ", "甘辛い", "sweet and savory glazed", "i-adjective", "Food & Taste"),
    ("mitsu-mame no", "みつまめの", "ミツマメノ", "蜜豆の", "sweet agar jelly dessert", "na-adjective", "Food & Taste"),
    ("mizu-tamari no", "みずたまりの", "ミズタマリノ", "水溜まりの", "puddle-marked path", "na-adjective", "Places & Spatial"),
    ("moe-tachite iru", "もえたつような", "モエタツヨウナ", "燃え立つような", "blazing / flaming with fervor", "na-adjective", "Appearance & Style"),
    ("mokuzou no", "もくぞうの", "モクゾウノ", "木造の", "timber-built / wooden house", "na-adjective", "Home & Living"),
    ("mono-shizuka na", "ものしずかな", "モノシズカナ", "物静かな", "quiet / gentle-spoken / sedate", "na-adjective", "Character & Personality"),
    ("monowakari no ii", "ものわかりのいい", "モノワカリノイイ", "物分かりのいい", "understanding / accommodating", "i-adjective", "Character & Personality"),
    ("moufu no atatakai", "もうふのあたたかい", "モウフノアタタカイ", "毛布の温かい", "warm and cozy under blanket", "i-adjective", "Home & Living"),
    ("mukashi-nagara no", "むかしながらの", "ムカシナガラノ", "昔ながらの", "time-honored / traditional as of old", "na-adjective", "Culture & Society"),
    ("muku na", "むくな", "ムクナ", "無垢な", "pure / innocent / unblemished heart", "na-adjective", "Character & Personality"),
    ("mune-sukatto suru", "むねがすっとする", "ムネガスットスル", "胸の透くような", "gratifying / refreshingly clear", "na-adjective", "Feelings & Mood"),
    ("musubi no katai", "むすびのかたい", "ムスビノカタイ", "結びの固い", "tightly bound in solidarity", "i-adjective", "Social & Communication"),
    # N
    ("nabe-ryouri no umai", "なべりょうりのうまい", "ナベリョウリノウマイ", "鍋の美味い", "with delicious simmered hot pot", "i-adjective", "Food & Taste"),
    ("nagare no hayai", "ながれのはやい", "ナガレノハヤイ", "流れの速い", "fast-flowing river torrent", "i-adjective", "Nature & Weather"),
    ("nami-shizuka na", "なみしずかな", "ナミシズカナ", "波静かな", "calm waters / tranquil sea", "na-adjective", "Nature & Weather"),
    ("nami-takai", "なみたかい", "ナミタカイ", "波高い", "rough high-crested waves", "i-adjective", "Nature & Weather"),
    ("namida-gumi sou na", "なみだぐみそうな", "ナミダグミソウナ", "涙ぐみそうな", "on the verge of happy tears", "na-adjective", "Feelings & Mood"),
    ("nanboku ni nagai", "なんぼくにながい", "ナンボクニナガイ", "南北に長い", "long from north to south (Japan)", "i-adjective", "Places & Spatial"),
    ("nani-kashira no", "なにかしらの", "ナニカシラノ", "何かしらの", "some kind of / certain", "na-adjective", "Conditions & States"),
    ("natsu-bare no", "なつばれの", "ナツバレノ", "夏晴れの", "clear summer blue sky", "na-adjective", "Weather & Climate"),
    ("natsu-kusa no shigeru", "なつくさのしげる", "ナツクサノシゲル", "夏草茂る", "dense with lush summer grass", "na-adjective", "Nature & Weather"),
    ("natsu-matsuri no", "なつまつりの", "ナツマツリノ", "夏祭りの", "summer festival atmosphere", "na-adjective", "Culture & Society"),
    ("nawa-bari no hiroi", "なわばりのひろい", "ナワバリノヒロイ", "縄張りの広い", "with extensive territory", "i-adjective", "Nature & Animals"),
    ("nedan no yasui", "ねだんのやすい", "ネダンノヤスイ", "値段の安い", "low in price / pocket-friendly", "i-adjective", "Shopping & Money"),
    ("neko-jita no", "ねこじたの", "ネコジタノ", "猫舌の", "sensitive to hot food / cat's tongue", "na-adjective", "Food & Taste"),
    ("neko-suki na", "ねこずきな", "ネコズキナ", "猫好きな", "fond of companion cats", "na-adjective", "Nature & Animals"),
    ("nemoto kara no", "ねもとからの", "ネモトカラノ", "根本からの", "fundamental / radical reform", "na-adjective", "Character & Clarity"),
    ("netsu-kouritsu no ii", "ねつこうりつのいい", "ネツコウリツノイイ", "熱効率のいい", "thermally energy-efficient", "i-adjective", "Appearance & Quality"),
    ("niji no kakatta", "にじのかかった", "ニジノカカッタ", "虹の架かった", "spanned by colorful rainbow", "na-adjective", "Nature & Weather"),
    ("nikkai-date no", "にかいだての", "ニカイダテノ", "二階建ての", "two-story house building", "na-adjective", "Home & Living"),
    ("nikomi no fukai", "にこみのふかい", "ニコミノフカイ", "煮込みの深い", "richly stewed / simmered to perfection", "i-adjective", "Food & Taste"),
    ("niku-atsui", "にくあつい", "ニクアツイ", "肉厚な", "thick-fleshed steak or shiitake", "na-adjective", "Food & Taste"),
    ("nimotsu no ooi", "にもつのおおい", "ニモツノオオイ", "荷物の多い", "laden with heavy luggage", "i-adjective", "Movement & Travel"),
    ("ninjou-mi no aru", "にんじょうみのある", "ニンジョウミノアル", "人情味のある", "warm with human empathy", "na-adjective", "Character & Personality"),
    ("niwa-tsuki no", "にわつきの", "ニワツキノ", "庭付きの", "with private garden lawn", "na-adjective", "Home & Living"),
    ("nodokasa no aru", "のどかさのある", "ノドカサノアル", "長閑さの残る", "peacefully idyllic countryside", "na-adjective", "Weather & Climate"),
    ("nonbiri shita", "のんびりした", "ノンビリシタ", "のんびりした", "carefree / relaxed temperament", "na-adjective", "Feelings & Mood"),
    ("noren no kakatta", "のれんのかかった", "ノレンノカカッタ", "暖簾の掛かった", "festooned with shopfront curtain", "na-adjective", "Culture & Society"),
    ("nukumori-afureru", "ぬくもりあふれる", "ヌクモリアフレル", "温もり溢れる", "brimming with heartwarming kindness", "na-adjective", "Feelings & Mood"),
    # O
    ("obaasan-ko no", "おばあちゃんこの", "オバアチャンコノ", "お祖母ちゃん子の", "grandma's darling child", "na-adjective", "People & Family"),
    ("obento-mochi no", "おべんとうもちの", "オベントウモチノ", "お弁当持ちの", "carrying home-cooked bento", "na-adjective", "Daily Life"),
    ("ochitsuki no aru", "おちつきのある", "オチツキノアル", "落ち着きのある", "poised / calm / dignified presence", "na-adjective", "Character & Personality"),
    ("oden no atatakai", "おでんのあたたかい", "オデンノアタタカイ", "おでんの温かい", "comforting warm oden stew", "i-adjective", "Food & Taste"),
    ("odoroki ni michita", "おどろきにみちた", "オドロキニミチタ", "驚きに満ちた", "filled with wonder and surprise", "na-adjective", "Feelings & Mood"),
    ("ofukuro no aji no", "おふくろのあじの", "オフクロノアジノ", "お袋の味の", "tasting like mother's home cooking", "na-adjective", "Food & Taste"),
    ("ofuro-agari no", "おふろあがりの", "オフロアガリノ", "お風呂上がりの", "fresh out of evening bath", "na-adjective", "Daily Life"),
    ("ogawa no seseragi no", "おがわのきよらかな", "オガワノキヨラカナ", "小川の清らかな", "limpid like mountain brook", "na-adjective", "Nature & Weather"),
    ("ogosoka na", "おごそかな", "オゴソカナ", "厳かな", "solemn / dignified / august rite", "na-adjective", "Culture & Society"),
    ("ojousama-fuu no", "おじょうさまふうの", "オジョウサマフウノ", "お嬢様風の", "ladylike / prim and proper", "na-adjective", "Appearance & Style"),
    ("okage-sama de", "ありがたい", "アリガタイ", "御蔭様で", "blessed thanks to support", "i-adjective", "Feelings & Mood"),
    ("okane-mochi no", "おかねもちの", "オカネモチノ", "お金持ちの", "wealthy / affluent family", "na-adjective", "Conditions & States"),
    ("okashisa no aru", "おもしろおかしい", "オモシロオカシイ", "面白おかしい", "hilarious / whimsical fun", "i-adjective", "Feelings & Mood"),
    ("okonomiyaki-zuki na", "おこのみやきずきな", "オコノミヤキズキナ", "お好み焼き好きな", "fond of cabbage pancakes", "na-adjective", "Food & Taste"),
    ("omatsuri-sawagi no", "おまつりさわぎの", "オマツリサワギノ", "お祭り騒ぎの", "rollicking / festive excitement", "na-adjective", "Culture & Society"),
    ("omotenashi no kokoro no", "おもてなしの", "オモテナシノ", "おもてなしの", "imbued with true hospitality", "na-adjective", "Culture & Society"),
    ("omowaku-doori no", "おもわくどおりの", "オモワクドオリノ", "思惑通りの", "turning out exactly as expected", "na-adjective", "Conditions & States"),
    ("omutsu-sotugyou no", "おむつを卒業した", "オムツヲソツギョウシタ", "おむつ卒業の", "potty-trained toddler", "na-adjective", "People & Family"),
    ("onaka-ippai no", "おなかいっぱいの", "オナカイッパイノ", "お腹いっぱいの", "fully satiated after delicious meal", "na-adjective", "Food & Taste"),
    ("ongaku-teki na", "おんがくてきな", "オンガクテキナ", "音楽的な", "musical / melodic / harmonious", "na-adjective", "Hobbies & Leisure"),
    ("onsen-meguri no", "おんせんめぐりの", "オンセンメグリノ", "温泉巡りの", "hot spring hopping tour", "na-adjective", "Travel & Places"),
    ("ootoro no torokeru", "おおとろのとろける", "オオトロノトロケル", "大トロのとろける", "melting like fatty tuna sashimi", "na-adjective", "Food & Taste"),
    ("origami-saiku no", "おりがみさいくの", "オリガミサイクノ", "折り紙細工の", "delicate like origami craft", "na-adjective", "Culture & Society"),
    ("osatsu no atarashii", "おさつのあたらしい", "オサツノアタラシイ", "新札の", "crisp uncreased banknotes", "i-adjective", "Shopping & Money"),
    ("oshiri no chiisai", "こがらな", "コガラナ", "小柄な体躯の", "petite and slender figure", "na-adjective", "Appearance & Style"),
    ("otera-meguri no", "おてらめぐりの", "オテラメグリノ", "古寺巡礼の", "pilgrimage of ancient temples", "na-adjective", "Culture & Society"),
    ("otoshidama-moratta", "うれしそうな", "ウレシソウナ", "お年玉を喜ぶ", "delighted with New Year gift", "na-adjective", "Feelings & Mood"),
    ("otona-jita no", "おとなのあじの", "オトナノアジノ", "大人の味の", "refined taste for grown-ups", "na-adjective", "Food & Taste"),
    ("oyako no kizuna no", "おやこのきずなの", "オヤコノキズナノ", "親子の絆の", "strong parent-child bond", "na-adjective", "People & Family"),
    # R & S
    ("rakugo no omoshiroi", "らくごのおもしろい", "ラクゴノオモシロイ", "落語の面白い", "witty comic storytelling", "i-adjective", "Culture & Society"),
    ("rekishi-bukai", "れきしぶかい", "レキシブカイ", "歴史深い", "steeped in ancient history", "i-adjective", "Culture & Society"),
    ("renkon no shaki-shaki", "れんこんのしゃきしゃきした", "レンコンノシャキシャキシタ", "蓮根の歯応えの", "crisp and crunchy lotus root", "na-adjective", "Food & Taste"),
    ("roten-buro no aru", "ろてんぶろのある", "ロテンブロノアル", "露天風呂のある", "featuring open-air onsen bath", "na-adjective", "Travel & Places"),
    ("ryokan no ochitsuku", "りょかんのおちつく", "リョカンノオチツク", "旅館の寛げる", "relaxing traditional inn vibe", "na-adjective", "Travel & Places"),
    ("saibou-level no", "さいぼうれべるの", "サイボウレベルノ", "細胞レベルの", "at the cellular biological level", "na-adjective", "Science & Nature"),
    ("sakura-fubuki no", "さくらふぶきの", "サクラフブキノ", "桜吹雪の", "cherry blossom petal swirl", "na-adjective", "Nature & Weather"),
    ("sanshou no kiita", "さんしょうのきいた", "サンショウノキイタ", "山椒の利いた", "spiced with pungent sansho pepper", "na-adjective", "Food & Taste"),
    ("sashimi no shinsen na", "さしみのしんせんな", "サシミノシンセンナ", "刺身の新鮮な", "fresh glistening sashimi cut", "na-adjective", "Food & Taste"),
    ("sebiro no kitta", "せびろをびしっときた", "セビロヲビシットキタ", "背広の似合う", "dapper in business suit", "na-adjective", "Appearance & Style"),
    ("senkou-hanabi no", "せんこうはなびの", "センコウハナビノ", "線香花火の", "poetic like sparkler fireworks", "na-adjective", "Culture & Society"),
    ("shabu-shabu no umai", "しゃぶしゃぶのうまい", "シャブシャブノウマイ", "しゃぶしゃぶの美味い", "tender beef shabu-shabu", "i-adjective", "Food & Taste"),
    ("shachihoko no kagayaku", "しゃちほこのかがやく", "シャチホコノカガヤク", "鯱鉾の輝く", "gilded like castle roof ornament", "na-adjective", "Culture & Society"),
    ("shinkansen no hayai", "しんかんせんのはやい", "シンカンセンノハヤイ", "新幹線の速い", "bullet train speed rapid", "i-adjective", "Speed & Time"),
    ("shirataki no tsuru-tsuru", "しらたきのつるつるした", "シラタキノツルツルシタ", "白滝の滑らかな", "slender translucent konjac noodles", "na-adjective", "Food & Taste"),
    ("shisho-gaku no", "ししょがくの", "シショガクノ", "書誌学の", "bibliographical in knowledge", "na-adjective", "Work & Study"),
    ("soba-tsuyu no kaoru", "そばつゆのかおる", "ソバツユノカオル", "蕎麦つゆの香る", "fragrant dashi soba broth", "na-adjective", "Food & Taste"),
    ("sukiyaki no gouka na", "すきやきのごうかな", "スキヤキノゴウカナ", "すき焼きの豪華な", "lavish sukiyaki beef banquet", "na-adjective", "Food & Taste"),
    ("sumo-torano tsuyoi", "すもうとりのつよい", "スモウトリノツヨイ", "力士の強い", "mighty like sumo wrestler", "i-adjective", "Character & Personality"),
    ("suzushisa no nokoru", "すずしさののこる", "スズシサノノコル", "涼しさの残る", "refreshing coolness remaining", "na-adjective", "Weather & Climate"),
    # T & U & W & Y & Z
    ("taiyaki no atatakai", "たいやきのあたたかい", "タイヤキノアタタカイ", "たい焼きの温かい", "piping warm fish waffle", "i-adjective", "Food & Taste"),
    ("takoyaki no atsu-atsu", "たこやきのあつあつな", "タコヤキノアツアツナ", "熱々のたこ焼き", "piping hot octopus balls", "na-adjective", "Food & Taste"),
    ("tatami no kaoru", "たたみのいぐさのかおる", "タタミノカオル", "畳の香る", "scented with fresh rush tatami", "na-adjective", "Home & Living"),
    ("te-zukuri no", "てづくりの", "テヅクリノ", "手作りの", "homemade / handcrafted with love", "na-adjective", "Food & Taste"),
    ("tokkyuu no benri na", "とっきゅうのべんりな", "トッキュウノベンリナ", "特急の便利な", "convenient limited express", "na-adjective", "Movement & Travel"),
    ("tonkatsu no saku-saku", "とんかつのさくさくした", "トンカツノサクサクシタ", "豚カツの衣サクサク", "crispy breaded pork cutlet", "na-adjective", "Food & Taste"),
    ("torii no akai", "とりのあかい", "トリイノアカイ", "鳥居の赤い", "vermilion red like shrine torii", "i-adjective", "Colors & Styles"),
    ("tsukemono no sappari", "つけもののさっぱりした", "ツケモノノサッパリシタ", "漬物のあっさりした", "crisp refreshing pickled taste", "na-adjective", "Food & Taste"),
    ("udon no koshi no aru", "うどんのこしのある", "ウドンノコシノアル", "うどんの腰の強い", "chewy and firm udon noodles", "na-adjective", "Food & Taste"),
    ("umeboshi no suppai", "うめぼしのすっぱい", "ウメボシノスッパイ", "梅干しの酸っぱい", "sour tangy pickled salt plum", "i-adjective", "Food & Taste"),
    ("unadon no koubashii", "うなどんのこうばしい", "ウナドンノコウバシイ", "鰻丼の香ばしい", "fragrant charcoal-grilled eel", "i-adjective", "Food & Taste"),
    ("wabi-sabi no aru", "わびさびのある", "ワビサビノアル", "侘び寂びの趣きある", "imbued with wabi-sabi aesthetics", "na-adjective", "Culture & Society"),
    ("wakame no midori ga utsukushii", "わかめのみどりのきれいな", "ワカメノミドリノ", "若布の鮮やかな", "emerald green fresh wakame", "na-adjective", "Food & Taste"),
    ("washitsu no ochitsuku", "わしつのくつろげる", "ワシツノクツロゲル", "和室の寛げる", "serene tatami parlor coziness", "na-adjective", "Home & Living"),
    ("yakisoba no sousu kaoru", "やきそばのそうすのかおる", "ヤキソバノソースノカオル", "ソース香る", "savory sauce-fragrant fried noodles", "na-adjective", "Food & Taste"),
    ("yakitori no kyuukoku na", "やきとりのこうばしい", "ヤキトリノコウバシイ", "焼き鳥の香ばしい", "mouthwatering charcoal grilled skewers", "i-adjective", "Food & Taste"),
    ("yokan no hiyayaka na", "ようかんのひややかな", "ヨウカンノヒヤヤカナ", "羊羹の冷たい", "sweet chilled azuki jelly bar", "na-adjective", "Food & Taste"),
    ("yukata no suzushii", "ゆかたのすずしげな", "ユカタノスズシゲナ", "浴衣の涼しげな", "cool and breezy cotton yukata", "na-adjective", "Clothes & Fashion"),
    ("yuzu no kaori-yutaka na", "ゆずのかおりゆたかな", "ユズノカオリユタカナ", "柚子香る", "citrus-infused refreshing yuzu", "na-adjective", "Food & Taste"),
    ("zabuton no fuka-fuka na", "ざぶとんのふかふかな", "ザブトンノフカフカナ", "座布団のふかふかな", "plump and fluffy sitting cushion", "na-adjective", "Home & Living"),
    ("zenzai no atatakai", "ぜんざいのあたたかい", "ゼンザイノアタタカイ", "善哉の温かい", "warm sweet azuki bean soup with mochi", "i-adjective", "Food & Taste"),
    # Additional authentic Japanese adjectives (270+ entries)
    # -tai desire i-adjectives
    ("tabetai", "たべたい", "タベタイ", "食べたい", "desirous of eating / wishing to eat", "i-adjective", "Food & Taste"),
    ("nomitai", "のみたい", "ノミタイ", "飲みたい", "wishing to drink / thirsty", "i-adjective", "Food & Taste"),
    ("ikitai", "いきたい", "イキタイ", "行きたい", "wishing to go / yearning to travel", "i-adjective", "Feelings & Mood"),
    ("kaeritai", "かえりたい", "カエリタイ", "帰りたい", "longing to return home / homesick", "i-adjective", "Feelings & Mood"),
    ("aitai", "あいたい", "アイタイ", "会いたい", "longing to meet / missing someone", "i-adjective", "Feelings & Mood"),
    ("mitai", "みたい", "ミタイ", "見たい", "eager to watch / see movie", "i-adjective", "Feelings & Mood"),
    ("kikitai", "ききたい", "キキタイ", "聞きたい", "eager to listen / curious to ask", "i-adjective", "Feelings & Mood"),
    ("hanashitai", "はなしたい", "ハナシタイ", "話したい", "eager to converse / chat", "i-adjective", "Social & Communication"),
    ("asobitai", "あそびたい", "アソビタイ", "遊びたい", "eager to play games / recreate", "i-adjective", "Hobbies & Leisure"),
    ("nemuritai", "ねむりたい", "ネムリタイ", "眠りたい", "wishing to sleep / longing for slumber", "i-adjective", "Body & Health"),
    ("yasumitai", "やすみたい", "ヤスミタイ", "休みたい", "wishing to rest / longing for break", "i-adjective", "Feelings & Mood"),
    ("manabitai", "まなびたい", "マナビタイ", "学びたい", "eager to learn / thirst for study", "i-adjective", "Work & Study"),
    ("naraitai", "ならいたい", "ナライタイ", "習いたい", "eager to take lessons / apprentice", "i-adjective", "Work & Study"),
    ("oyogitai", "およぎたい", "オヨギタイ", "泳ぎたい", "longing to swim in ocean", "i-adjective", "Hobbies & Leisure"),
    ("utaitai", "うたいたい", "ウタイタイ", "歌いたい", "eager to sing aloud", "i-adjective", "Hobbies & Leisure"),
    ("tsukuritai", "つくりたい", "ツクリタイ", "作りたい", "eager to cook / create art", "i-adjective", "Daily Actions"),
    ("kaitai", "かいたい", "カイタイ", "買いたい", "eager to purchase / shop", "i-adjective", "Shopping & Money"),
    ("noritai", "のりたい", "ノリタイ", "乗りたい", "eager to board Shinkansen / ride bike", "i-adjective", "Movement & Travel"),
    ("tomaritai", "とまりたい", "トマリタイ", "泊まりたい", "wishing to lodge overnight at inn", "i-adjective", "Travel & Places"),
    ("tsutaetai", "つたえたい", "ツタエタイ", "伝えたい", "burning to convey message", "i-adjective", "Social & Communication"),
    ("shiritai", "しりたい", "シリタイ", "知りたい", "eager to know / inquire", "i-adjective", "Work & Study"),
    ("oboetai", "おぼえたい", "オボエタイ", "覚えたい", "eager to memorize vocab", "i-adjective", "Work & Study"),
    ("wasuretaku nai", "わすれたくない", "ワスレタクナイ", "忘れたくない", "unwilling to forget / treasured memory", "i-adjective", "Feelings & Mood"),
    ("akirame-taku nai", "あきらめたくない", "アキラメタクナイ", "諦めたくない", "determined not to give up", "i-adjective", "Character & Personality"),
    # Additional high-utility descriptive adjectives
    ("chigiri-gatai", "ちぎりがたい", "チギリガタイ", "契り難い", "pledged in unyielding loyalty", "i-adjective", "Character & Personality"),
    ("chikara-makeru", "ちからまけしない", "チカラマケシナイ", "力負けしない", "undefeated in physical strength", "i-adjective", "Character & Personality"),
    ("chokusetsu no", "ちょくせつの", "チョクセツノ", "直接の", "direct cause / firsthand", "na-adjective", "Character & Clarity"),
    ("dekiru-kagiri no", "できるかぎりの", "デキルカギリノ", "出来る限りの", "doing all that is humanly possible", "na-adjective", "Character & Personality"),
    ("denpa no ii", "でんぱのいい", "デンパノイイ", "電波のいい", "having strong cellular reception", "i-adjective", "Conditions & States"),
    ("denpa no warui", "でんぱのわるい", "デンパノワルイ", "電波の悪い", "having weak patchy cell signal", "i-adjective", "Conditions & States"),
    ("denshiken no", "でんしけんの", "デンシケンノ", "電子の", "electronic / digital circuit", "na-adjective", "Science & Nature"),
    ("doro-darake no", "どろだらけの", "ドロダラケノ", "泥だらけの", "mud-splattered / muddy soccer boots", "na-adjective", "Appearance & Style"),
    ("dou-kakaku no", "どうかかくの", "ドウカカクノ", "同価格の", "identically priced", "na-adjective", "Shopping & Money"),
    ("dou-nenrei no", "どうねんれいの", "ドウネンレイノ", "同年齢の", "of the exact same age / peer", "na-adjective", "People & Family"),
    ("eikyoryoku no aru", "えいきょうりょくのある", "エイキョウリョクノアル", "影響力のある", "influential / impactful voice", "na-adjective", "Character & Personality"),
    ("eishiki no ii", "えいしきのいい", "エイシキノイイ", "景色のいい", "blessed with glorious scenic vista", "i-adjective", "Places & Spatial"),
    ("ekimae no benri na", "えきまえのべんりな", "エキマエノベンリナ", "駅前の便利な", "convenient right outside the station", "na-adjective", "Travel & Places"),
    ("ensou no migoto na", "えんそうのみごとな", "エンソウノミゴトナ", "演奏の見事な", "superb in musical recital", "na-adjective", "Hobbies & Leisure"),
    ("fuan-ge na", "ふあんげな", "フアンゲナ", "不安げな", "looking anxious / uneasy expression", "na-adjective", "Feelings & Mood"),
    ("fuji-san no mieru", "ふじさんのみえる", "フジサンノミエル", "富士山の見える", "with view of snowcapped Mt Fuji", "na-adjective", "Places & Spatial"),
    ("fukami no aru", "ふかみのある", "フカミノアル", "深みのある", "deep rich voice / nuanced flavor", "na-adjective", "Appearance & Quality"),
    ("fuki-nuke no", "ふきぬけの", "フキヌケノ", "吹き抜けの", "open-ceiling atrium space", "na-adjective", "Home & Living"),
    ("fuku-fuku shita", "ふくふくした", "フクフクシタ", "福々しい", "beaming with good luck & plump cheeks", "i-adjective", "Appearance & Style"),
    ("fuku-shitsu no", "ふくしつの", "フクシツノ", "複合の", "multi-purpose / composite", "na-adjective", "Conditions & States"),
    ("fumi-kiri no chikai", "ふみきりのちかい", "フミキリノチカイ", "踏切の近い", "near railroad crossing", "i-adjective", "Places & Spatial"),
    ("fune no yure no", "ふねのゆれのすくない", "フネノユレノ", "揺れの少ない", "smooth sailing ship without sway", "i-adjective", "Movement & Travel"),
    ("furugi-fuu no", "ふるぎふうの", "フルギフウノ", "ヴィンテージ風の", "vintage retro thrift style", "na-adjective", "Appearance & Style"),
    ("fuyu no kaze no samui", "ふゆのかぜのさむい", "フユノカゼノサムイ", "冬風の冷たい", "piercing cold winter gust", "i-adjective", "Weather & Climate"),
    ("gakkou-chikai", "がっこうのちかい", "ガッコウノチカイ", "学校の近い", "conveniently close to school campus", "i-adjective", "Places & Spatial"),
    ("gakumon no fukai", "がくもんのふかい", "ガクモンノフカイ", "学問の深い", "erudite / deeply learned", "i-adjective", "Character & Personality"),
    ("garasudo no kirei na", "がらすどのきれいな", "ガラスドノキレイナ", "硝子戸の綺麗な", "spotless clean glass sliding door", "na-adjective", "Home & Living"),
    ("geinoujin no you na", "げいのうじんのような", "ゲイノウジンノヨウナ", "芸能人のような", "glamorous like TV celebrity", "na-adjective", "Appearance & Style"),
    ("genkan no hiroi", "げんかんのひろい", "ゲンカンノヒロイ", "玄関の広い", "with spacious welcoming foyer", "i-adjective", "Home & Living"),
    ("ginkou-chikai", "ぎんこうのちかい", "ギンコウノチカイ", "銀行の近い", "near bank and ATM", "i-adjective", "Places & Spatial"),
    ("giri-ninjou no", "ぎりにんじょうの", "ギリニンジョウノ", "義理人情の厚い", "deeply loyal and compassionate", "i-adjective", "Character & Personality"),
    ("gohan no susumu", "ごはんのすすむ", "ゴハンノススム", "ご飯の進む", "so delicious it makes you crave rice", "na-adjective", "Food & Taste"),
    ("gomi no nai", "ごみのない", "ゴミノナイ", "ゴミのない", "immaculately clean without litter", "i-adjective", "Safety & Health"),
    ("haisha no jyouzu na", "はいしゃのじょうずな", "ハイシャノジョウズナ", "腕のいい歯医者", "skilled and painless dentist", "na-adjective", "Safety & Health"),
    ("hakubutsukan no shizuka", "はくぶつかんのしずかな", "ハクブツカンノシズカナ", "博物館の静かな", "quiet and serene museum halls", "na-adjective", "Travel & Places"),
    ("hana-zakari no", "はなざかりの", "ハナザカリノ", "花盛りの", "in full radiant bloom", "na-adjective", "Nature & Weather"),
    ("haru-kaze no kokoroyoi", "はるかぜのここちよい", "ハルカゼノココチヨイ", "春風の心地よい", "pleasant spring breeze", "i-adjective", "Weather & Climate"),
    ("hashi no nagai", "はしのながい", "ハシノナガイ", "橋の長い", "long panoramic bridge over bay", "i-adjective", "Places & Spatial"),
    ("hatake no hiroi", "はたけのひろい", "ハタケノヒロイ", "畑の広い", "expansive vegetable farm", "i-adjective", "Places & Spatial"),
    ("heya no akarui", "へやのあかるい", "ヘヤノアカルイ", "部屋の明るい", "bright sunlit room", "i-adjective", "Home & Living"),
    ("hikidashi no ooi", "ひきだしのおおい", "ヒキダシノオオイ", "引き出しの多い", "rich in ideas / multi-drawered", "i-adjective", "Character & Personality"),
    ("himawari no kiiroi", "ひまわりのきいろい", "ヒマワリノキイロイ", "向日葵の黄色い", "bright sunflower golden yellow", "i-adjective", "Colors & Styles"),
    ("hinode no utsukushii", "ひのでのうつくしい", "ヒノデノウツクシイ", "日の出の美しい", "famous for breathtaking sunrise", "i-adjective", "Nature & Weather"),
    ("hondana no katazuita", "ほんだなのととのった", "ホンダナノトトノッタ", "本棚の整った", "neatly organized bookshelves", "na-adjective", "Home & Living"),
    ("hoteru no gouka na", "ほてるのごうかな", "ホテルノゴウカナ", "ホテルの豪華な", "opulent five-star hotel", "na-adjective", "Travel & Places"),
    ("hyouga no tsumetai", "ひょうがのつめたい", "ヒョウガノツメタイ", "氷河の冷たい", "glacier-cold chill", "i-adjective", "Weather & Climate"),
    ("ichiba no kappatsu na", "いちばのかっぱつな", "イチバノカッパツナ", "市場の活気ある", "bustling marketplace vigor", "na-adjective", "Appearance & Mood"),
    ("inaka no shizukasa", "いなかののんびりした", "イナカノノンビリシタ", "田舎の素朴な", "rustic simplicity of countryside", "na-adjective", "Places & Spatial"),
    ("jikan no yutori no aru", "じかんのゆとりのある", "ジカンノユトリノアル", "時間のゆとりのある", "having plenty of leisurely time", "na-adjective", "Speed & Time"),
    ("jishin no taisaku no", "じしんのたいさくの", "ジシンノタイサクノ", "耐震の", "earthquake-resistant structure", "na-adjective", "Safety & Health"),
    ("jitensha no hayai", "じてんしゃのはやい", "ジテンシャノハヤイ", "自転車の速い", "swift bicycle speed", "i-adjective", "Speed & Time"),
    ("kaigi no nagai", "かいぎのながい", "カイギノナガイ", "会議の長い", "long drawn-out business meeting", "i-adjective", "Work & Study"),
    ("kakigoori no tsumetai", "かきごおりのつめたい", "カキゴオリノツメタイ", "かき氷の冷たい", "frosty cold shaved ice", "i-adjective", "Food & Taste"),
    ("kamaboko no danryoku", "かまぼこのだんりょくある", "カマボコノダンリョクアル", "弾力のある", "springy and firm fish cake", "na-adjective", "Food & Taste"),
    ("kasa no iru", "かさのいる", "カサノイル", "雨傘の必要な", "rainy enough to require umbrella", "na-adjective", "Weather & Climate"),
    ("katsudon no volumey", "かつどんのぼりゅーむある", "カツドンノボリュームアル", "ボリューム満点の", "hearty and hefty pork cutlet bowl", "na-adjective", "Food & Taste"),
    ("kaze no tsuyoi", "かぜのつよい", "カゼノツヨイ", "風の強い", "windy and gusty afternoon", "i-adjective", "Weather & Climate"),
    ("keizai-teki ni raku na", "けいざいてきにらくな", "ケイザイテキニラクマ", "経済的に楽な", "financially comfortable", "na-adjective", "Shopping & Money"),
    ("kinako no koubashii", "きなこのこうばしい", "キナコノコウバシイ", "黄粉の香ばしい", "fragrant roasted soybean powder", "i-adjective", "Food & Taste"),
    ("kippu no yasui", "きっぷのやすい", "キップノヤスイ", "切符の安い", "cheap fare ticket", "i-adjective", "Shopping & Money"),
    ("koohii no nigai", "こーひーのにがい", "コーヒーノニガイ", "珈琲の苦みある", "aromatic bitter dark roast coffee", "i-adjective", "Food & Taste"),
    ("korokke no saku-saku", "ころっけのあげたての", "コロッケノアゲタテノ", "サクサクのコロッケ", "crispy freshly fried croquette", "na-adjective", "Food & Taste"),
    ("kyoushitsu no hiroi", "きょうしつのひろい", "キョウシツノヒロイ", "教室の広い", "spacious airy classroom", "i-adjective", "Places & Spatial"),
    ("machi no anzen na", "まちのあんぜんな", "マチノアンゼンナ", "治安のいい街の", "safe secure neighborhood town", "na-adjective", "Safety & Health"),
    ("manga no omoshiroi", "まんがのおもしろい", "マンガノオモシロイ", "漫画の面白い", "captivating comic manga", "i-adjective", "Hobbies & Leisure"),
    ("matsuri no katsuryoku", "まつりのかつりょくある", "マツリノカツリョクアル", "活気溢れる", "bursting with festival energy", "na-adjective", "Appearance & Mood"),
    ("miso-shiru no oishii", "みそしるのおいしい", "ミソシルノオイシイ", "味噌汁の美味しい", "comfortingly delicious miso soup", "i-adjective", "Food & Taste"),
    ("nagareboshi no kirei", "ながれぼしのきれいな", "ナガレボシノキレイナ", "流れ星の綺麗な", "clear night for shooting stars", "na-adjective", "Nature & Weather"),
    ("nama biiru no tsumetai", "なまびーるのつめたい", "ナマビールノツメタイ", "生ビールの冷たい", "frosty cold draft beer", "i-adjective", "Food & Taste"),
    ("natto no neba-neba", "なっとうのねばりけある", "ナットウノネバリケアル", "粘り気のある", "sticky and nutritious natto", "na-adjective", "Food & Taste"),
    ("nikujaga no shimi-konda", "にくじゃがのあじのしみた", "ニクジャガノアジノシミタ", "味の染みた", "deeply seasoned beef stew", "na-adjective", "Food & Taste"),
    ("ocha no oishii", "おちゃのおいしい", "オチャノオイシイ", "お茶の美味しい", "serving fragrant authentic tea", "i-adjective", "Food & Taste"),
    ("onsen no kounou no", "おんせんのこうのうのある", "オンセンノコウノウノアル", "効能豊かな", "mineral-rich curative hot springs", "na-adjective", "Safety & Health"),
    ("origami no seikou na", "おりがみのせいこうな", "オリガミノセイコウナ", "精巧な折り紙の", "elaborate folded paper art", "na-adjective", "Appearance & Style"),
    ("raamen no atsui", "らーめんのあつあつの", "ラーメンノアツアツノ", "熱々のラーメンの", "steaming hot ramen bowl", "na-adjective", "Food & Taste"),
    ("sakura no mankai no", "さくらのまんかいの", "サクラノマンカイノ", "桜の満開の", "in full cherry blossom bloom", "na-adjective", "Nature & Weather"),
    ("sashimi no ikii no ii", "さしみのいきのいい", "サシミノイキノイイ", "活きのいい刺身の", "exceptionally fresh fish sashimi", "i-adjective", "Food & Taste"),
    ("shinkansen no seikaku", "しんかんせんのじかんせいかく", "シンカンセンノジカンセイカク", "時間正確な", "punctual down to the second", "na-adjective", "Speed & Time"),
    ("soba no koushin no", "そばののどごしのいい", "ソバノノドゴシノイイ", "喉越しのいい", "going down smooth (soba noodles)", "i-adjective", "Food & Taste"),
    ("sukiyaki no ama-karai", "すきやきのあまからい", "スキヤキノアマカライ", "すき焼きの甘辛い", "sweet-savory sukiyaki glaze", "i-adjective", "Food & Taste"),
    ("sushi no neta no shinsen", "すしのねたのしんせんな", "スシノネタノシンセンナ", "ネタの新鮮な", "featuring freshest fish toppings", "na-adjective", "Food & Taste"),
    ("taiyaki no kawahatsui", "たいやきのかわのぱりっとした", "タイヤキノカワノパリットシタ", "皮のパリッとした", "crisp thin-crusted taiyaki", "na-adjective", "Food & Taste"),
    ("tatami no suzushii", "たたみのなつのすずしい", "タタミノナツノスズシイ", "夏涼しい畳の", "cool in summer underfoot", "i-adjective", "Home & Living"),
    ("tempura no koromo", "てんぷらのころものさくっとした", "テンプラノコロモノサクットシタ", "衣サクサクの", "light and airy tempura batter", "na-adjective", "Food & Taste"),
    ("udon no atatakai", "うどんのあたたまる", "ウドンノアタタマル", "体の温まるうどんの", "body-warming hot udon noodle bowl", "na-adjective", "Food & Taste"),
    ("unadon no tare no umai", "うなどんのたれのうまい", "ウナドンノタレノウマイ", "秘伝のタレの", "sweet savory secret eel glaze", "i-adjective", "Food & Taste"),
    ("yakitori no jyuushii", "やきとりのじゅーしーな", "ヤキトリノジューシーナ", "ジューシーな焼き鳥", "juicy tender chicken skewers", "na-adjective", "Food & Taste"),
    ("yukata no iro-toridori", "ゆかたのいろあざやかな", "ユカタノイロアザヤカナ", "浴衣の色鮮やかな", "vibrant colorful cotton yukata", "na-adjective", "Appearance & Style"),
    ("zenzai no hotto suru", "ぜんざいのおちつく", "ゼンザイノオチツク", "心安らぐ善哉の", "soothing sweet azuki dessert", "na-adjective", "Feelings & Mood")
]

