# Compound Adjectives: -yasui, -nikui, -tate, -gachi, -ppoi, -kan
# (romaji, hiragana, katakana, kanji, meaning, type, topic)
DATA = [
    # -yasui (Easy to do / Prone to)
    ("wakari-yasui", "わかりやすい", "ワカリヤスイ", "分かりやすい", "easy to understand / lucid", "i-adjective", "Character & Clarity"),
    ("tsukai-yasui", "つかいやすい", "ツカイヤスイ", "使いやすい", "user-friendly / easy to operate", "i-adjective", "Appearance & Quality"),
    ("tabe-yasui", "たべやすい", "タベヤスイ", "食べやすい", "easy to eat / bite-sized", "i-adjective", "Food & Taste"),
    ("nomi-yasui", "のみやすい", "ノミヤスイ", "飲みやすい", "easy to drink / smooth taste", "i-adjective", "Food & Taste"),
    ("kiki-yasui", "ききやすい", "キキヤスイ", "聞きやすい", "easy on the ears / clear audio", "i-adjective", "Appearance & Quality"),
    ("oboe-yasui", "おぼえやすい", "オボエヤスイ", "覚えやすい", "easy to memorize / catchy", "i-adjective", "Work & Study"),
    ("aruki-yasui", "あるきやすい", "アルキヤスイ", "歩きやすい", "easy to walk in (shoes)", "i-adjective", "Safety & Health"),
    ("sumi-yasui", "すみやすい", "スミヤスイ", "住みやすい", "pleasant to live in / comfortable town", "i-adjective", "Conditions & States"),
    ("yomi-yasui", "よみやすい", "ヨミヤスイ", "読みやすい", "legible font / readable prose", "i-adjective", "Work & Study"),
    ("kaki-yasui", "かきやすい", "カキヤスイ", "書きやすい", "smooth to write with (pen)", "i-adjective", "Appearance & Quality"),
    ("hanashi-yasui", "はなしやすい", "ハナシヤスイ", "話しやすい", "easy to talk to / approachable", "i-adjective", "Character & Personality"),
    ("tsukuri-yasui", "つくりやすい", "ツクリヤスイ", "作りやすい", "easy to prepare (recipe)", "i-adjective", "Cooking & Dining"),
    ("koware-yasui", "こわれやすい", "コワレヤスイ", "壊れやすい", "fragile / easily broken glassware", "i-adjective", "Appearance & Quality"),
    ("tsukare-yasui", "つかれやすい", "ツカレヤスイ", "疲れやすい", "prone to fatigue / low stamina", "i-adjective", "Body & Health"),
    ("kaze o hiki-yasui", "かぜをひきやすい", "カゼヲヒキヤスイ", "風邪を引きやすい", "susceptible to catching colds", "i-adjective", "Body & Health"),
    ("ochiki-yasui", "おちつきやすい", "オチツキヤスイ", "落ち着きやすい", "relaxing / calming space", "i-adjective", "Feelings & Mood"),
    # -nikui (Difficult to do / Hard to)
    ("wakari-nikui", "わかりにくい", "ワカリニクイ", "分かりにくい", "hard to comprehend / obscure", "i-adjective", "Character & Clarity"),
    ("tsukai-nikui", "つかいにくい", "ツカイニクイ", "使いにくい", "awkward to use / cumbersome", "i-adjective", "Appearance & Quality"),
    ("tabe-nikui", "たべにくい", "タベニクイ", "食べにくい", "cumbersome to eat (large bone)", "i-adjective", "Food & Taste"),
    ("nomi-nikui", "のみにくい", "ノミニクイ", "飲みにくい", "hard to swallow (bitter medicine)", "i-adjective", "Food & Taste"),
    ("kiki-nikui", "ききにくい", "キキニクイ", "聞きにくい", "muffled / difficult to hear", "i-adjective", "Appearance & Quality"),
    ("oboe-nikui", "おぼえにくい", "オボエニクイ", "覚えにくい", "difficult to remember / convoluted", "i-adjective", "Work & Study"),
    ("aruki-nikui", "あるきにくい", "アルキニクイ", "歩きにくい", "rough road / difficult to walk", "i-adjective", "Places & Spatial"),
    ("yomi-nikui", "よみにくい", "ヨミニクイ", "読みにくい", "illegible handwriting / dense style", "i-adjective", "Work & Study"),
    ("kaki-nikui", "かきにくい", "カキニクイ", "書きにくい", "scratchy pen / hard to write", "i-adjective", "Appearance & Quality"),
    ("hanashi-nikui", "はなしにくい", "ハナシニクイ", "話しにくい", "difficult to bring up / awkward", "i-adjective", "Social & Communication"),
    ("tsukuri-nikui", "つくりにくい", "ツクリニクイ", "作りにくい", "fussy to craft / complex steps", "i-adjective", "Cooking & Dining"),
    ("koware-nikui", "こわれにくい", "コワレニクイ", "壊れにくい", "durable / hard to damage", "i-adjective", "Appearance & Quality"),
    ("yabure-nikui", "やぶれにくい", "ヤブレニクイ", "破れにくい", "tear-resistant tough fabric", "i-adjective", "Appearance & Quality"),
    ("hie-nikui", "ひえにくい", "ヒエニクイ", "冷えにくい", "retaining heat well / well-insulated", "i-adjective", "Weather & Climate"),
    ("yake-nikui", "やけにくい", "ヤケニクイ", "焼けにくい", "flame-resistant / fireproof", "i-adjective", "Appearance & Quality"),
    # -tate (Freshly made / Freshly completed)
    ("deki-tate no", "できたての", "デキタテノ", "出来立ての", "freshly made / right out of pan", "na-adjective", "Food & Taste"),
    ("yaki-tate no", "やきたての", "ヤキタテノ", "焼き立ての", "freshly baked bread / hot from oven", "na-adjective", "Food & Taste"),
    ("tori-tate no", "とりたての", "トリタテノ", "採り立ての", "freshly harvested from garden", "na-adjective", "Food & Taste"),
    ("age-tate no", "あげたての", "アゲタテノ", "揚げ立ての", "freshly deep-fried piping hot", "na-adjective", "Food & Taste"),
    ("ire-tate no", "いれたての", "イレタテノ", "淹れ立ての", "freshly dripped fragrant coffee", "na-adjective", "Food & Taste"),
    ("tsukuri-tate no", "つくりたての", "ツクリタテノ", "作り立ての", "freshly cooked meal", "na-adjective", "Food & Taste"),
    ("tsuki-tate no", "つきたての", "ツキタテノ", "搗き立ての", "freshly pounded soft mochi", "na-adjective", "Food & Taste"),
    ("nuri-tate no", "ぬりたての", "ヌリタテノ", "塗り立ての", "freshly painted wet paint", "na-adjective", "Conditions & States"),
    ("arai-tate no", "あらいたての", "アライタテノ", "洗い立ての", "freshly laundered crisp shirt", "na-adjective", "Appearance & Style"),
    ("umare-tate no", "うまれたての", "ウマレタテノ", "生まれたての", "newborn infant / baby chick", "na-adjective", "People & Family"),
    # -ppoi (Inclined to / -ish / -y)
    ("kodomo-ppoi", "こともっぽい", "コドモッポイ", "子供っぽい", "childish / immature / juvenile", "i-adjective", "Character & Personality"),
    ("otona-ppoi", "おとなっぽい", "オトナッポイ", "大人っぽい", "mature / grown-up appearance", "i-adjective", "Character & Personality"),
    ("onna-ppoi", "おんなっぽい", "オンナッポイ", "女っぽい", "feminine / womanly grace", "i-adjective", "Appearance & Style"),
    ("otoko-ppoi", "おとこっぽい", "オトコッポイ", "男っぽい", "manly / masculine ruggedness", "i-adjective", "Character & Personality"),
    ("yasuppoi", "やすっぽい", "ヤスッポイ", "安っぽい", "cheap-looking / tacky / tawdry", "i-adjective", "Appearance & Style"),
    ("aburappoi", "あぶらっぽい", "アブラッポイ", "油っぽい", "greasy / oily food", "i-adjective", "Food & Taste"),
    ("mizuppoi", "みずっぽい", "ミズッポイ", "水っぽい", "watery soup / diluted taste", "i-adjective", "Food & Taste"),
    ("shioppoi", "しおっぽい", "シオッポイ", "塩っぽい", "salty / brine-laden flavor", "i-adjective", "Food & Taste"),
    ("okorippoi", "おこりっぽい", "オコリッポイ", "怒りっぽい", "short-tempered / touchy / irascible", "i-adjective", "Character & Personality"),
    ("wasureppoi", "わすれっぽい", "ワスレッポイ", "忘れっぽい", "forgetful / absent-minded", "i-adjective", "Character & Personality"),
    ("akippoi", "あきっぽい", "アキッポイ", "飽きっぽい", "fickle / quick to lose interest", "i-adjective", "Character & Personality"),
    ("guchippoi", "ぐちっぽい", "グチッポイ", "愚痴っぽい", "grumbly / always complaining", "i-adjective", "Character & Personality"),
    ("iroppoi", "いろっぽい", "イロッポイ", "色っぽい", "amorous / sexy / voluptuous", "i-adjective", "Appearance & Style"),
    ("namappoi", "なまっぽい", "ナマッポイ", "生っぽい", "half-raw / uncooked center", "i-adjective", "Food & Taste"),
    ("usamajii", "すさまじい", "スサマジイ", "凄まじい", "terrific / tremendous / staggering", "i-adjective", "Degree & Intensity"),
    ("hitoriyorogashi na", "ひとよがしな", "ヒトヨガシナ", "独りよがりな", "self-complacent / dogmatic", "na-adjective", "Character & Personality"),
    ("kokoro-atatakai", "こころあたたかい", "ココロアタタカイ", "心温かい", "heartwarming / kindly affection", "i-adjective", "Feelings & Mood"),
    ("kokoro-yasashii", "こころやさしい", "ココロヤサシイ", "心優しい", "gentle-spirited / tender-souled", "i-adjective", "Character & Personality"),
    ("kokoro-tsuyoi", "こころづよい", "ココロヅヨイ", "心強い", "emboldened / strongly supported", "i-adjective", "Feelings & Mood"),
    ("kuchi-karui", "くちがるい", "クチガルイ", "口軽い", "blabbermouth / indiscreet with secrets", "i-adjective", "Character & Personality"),
    ("kuchi-katai", "くちがたい", "クチガタイ", "口堅い", "tight-lipped / discreet with secrets", "i-adjective", "Character & Personality"),
    ("kuchi-osabishii", "くちさびしい", "クチサビシイ", "口寂しい", "craving a snack to nibble on", "i-adjective", "Feelings & Mood"),
    ("me-atarashii", "めあたらしい", "メアタラシイ", "目新しい", "novel / eye-catching innovation", "i-adjective", "Praise & Quality"),
    ("me-zamashii", "めざましい", "メザマシイ", "目覚ましい", "striking / remarkable progress", "i-adjective", "Praise & Quality"),
    ("mimi-atarashii", "みみあたらしい", "ミミアタラシイ", "耳新しい", "novel to the ears / freshly coined", "i-adjective", "Praise & Quality"),
    ("te-atatakai", "てあたたかい", "テアタタカイ", "手温かい", "warm to the hand", "i-adjective", "Appearance & Quality"),
    ("te-kibishii", "てきびしい", "テキビシイ", "手厳しい", "trenchant / severe critique", "i-adjective", "Character & Personality"),
    ("te-bayai", "てばやい", "テバヤイ", "手早い", "quick-handed / deft in kitchen", "i-adjective", "Speed & Time"),
    ("te-gatai", "てがたい", "テガタイ", "手堅い", "steady / prudent / unassailable investment", "i-adjective", "Work & Study"),
    ("te-mijika na", "てみじかな", "テミジカナ", "手短な", "brief / concise explanation", "na-adjective", "Character & Clarity"),
    ("te-garu na", "てがるな", "テガルナ", "手軽な", "casual / informal / hassle-free", "na-adjective", "Difficulty & Ease"),
    ("te-goro na-price", "てごろなねだんの", "テゴロナネダンノ", "手頃な値段の", "moderately priced / economical", "na-adjective", "Shopping & Money"),
    ("te-suki na", "てすきな", "テスキナ", "手すきな", "having hands free / unoccupied", "na-adjective", "Speed & Time"),
    ("te-okure no", "ておくれの", "テオクレノ", "手遅れの", "too late for remedy / belated", "na-adjective", "Speed & Time"),
    ("te-atarishidai no", "てあたりしだいの", "テアタリシダイノ", "手当たり次第の", "haphazard / random choice", "na-adjective", "Conditions & States")
]
