# Advanced & Comprehensive A-Z Adjectives (M through Z and compound forms)
# (romaji, hiragana, katakana, kanji, meaning, type, topic)
DATA = [
    # M
    ("maboroshi no", "まぼろしの", "マボロシノ", "幻の", "legendary / phantom / rare gem", "na-adjective", "Praise & Quality"),
    ("machi-nozonda", "まちのぞんだ", "マチノゾンダ", "待ち望んだ", "long-awaited / eager anticipated", "na-adjective", "Feelings & Mood"),
    ("mada mada na", "まだまな", "マダマダナ", "未熟な", "still green / requiring practice", "na-adjective", "Work & Study"),
    ("maeda-shiki no", "まえむきな", "マエムキナ", "前向きな", "forward-looking / constructive", "na-adjective", "Character & Personality"),
    ("magire-monai", "まぎれもない", "マギレモナイ", "紛れもない", "unmistakable / undeniable fact", "i-adjective", "Character & Clarity"),
    ("mahou no you na", "まほうのような", "マホウノヨウナ", "魔法のような", "magical / enchanting effect", "na-adjective", "Praise & Quality"),
    ("majime na", "まじめな", "マジメナ", "真面目な", "diligent / earnest / conscientious", "na-adjective", "Character & Personality"),
    ("makoto no", "まことの", "マコトノ", "誠の", "true / sincere / steadfast loyalty", "na-adjective", "Character & Personality"),
    ("makka na", "まっかな", "マッカナ", "真っ赤な", "crimson red / complete stranger", "na-adjective", "Colors & Styles"),
    ("makkuro na", "まっくろな", "マックロナ", "真っ黒な", "pitch black / deeply tanned", "na-adjective", "Colors & Styles"),
    ("massao na", "まっさおな", "マッサオナ", "真っ青な", "deep azure / pale with shock", "na-adjective", "Colors & Styles"),
    ("masshiro na", "まっしろな", "マッシロナ", "真っ白な", "pure snow-white / blank mind", "na-adjective", "Colors & Styles"),
    ("massugu na", "まっすぐな", "マッスグナ", "真っ直ぐな", "straight road / candid honest nature", "na-adjective", "Character & Personality"),
    ("matomo na", "まともな", "マトモナ", "真当な", "decent / respectable / direct blow", "na-adjective", "Praise & Quality"),
    ("matsuri no you na", "まつりのような", "マツリノヨウナ", "祭りのような", "festive / lively like carnival", "na-adjective", "Appearance & Mood"),
    ("mattaku no", "まったくの", "マッタクノ", "全くの", "sheer / downright / utter", "na-adjective", "Degree & Intensity"),
    ("mazui", "まずい", "マズイ", "不味い", "unpalatable / unappetizing / awkward", "i-adjective", "Food & Taste"),
    ("mechakucha na", "めちゃくちゃな", "メチャクチャナ", "目茶苦茶な", "chaotic / preposterous / ruined", "na-adjective", "Conditions & States"),
    ("medetai", "めでたい", "メデタイ", "めでたい", "joyous / celebratory / auspicious", "i-adjective", "Feelings & Mood"),
    ("meikaku na", "めいかくにな", "メイカクナ", "明確な", "distinct / articulate / explicit", "na-adjective", "Character & Clarity"),
    ("meiryou na", "めいりょうな", "メイリョウナ", "明瞭な", "lucid / crystal-clear statement", "na-adjective", "Character & Clarity"),
    ("meisho no", "めいしょの", "メイショノ", "名所の", "scenic spot / famous tourist destination", "na-adjective", "Places & Spatial"),
    ("meiwaku na", "めいわくな", "メイワクナ", "迷惑な", "annoying / troublesome nuisance", "na-adjective", "Social & Communication"),
    ("mezumashii", "めずらしい", "メズラシイ", "珍しい", "rare / uncommon / curious", "i-adjective", "Praise & Quality"),
    ("michi no", "みちの", "ミチノ", "未知の", "unknown / unexplored continent", "na-adjective", "Conditions & States"),
    ("mijikai", "みじかい", "ミジカイ", "短い", "short in length / brief in duration", "i-adjective", "Size & Shape"),
    ("mikaku no ii", "みかくのいい", "ミカクノイイ", "味覚のいい", "having refined palate for food", "i-adjective", "Food & Taste"),
    ("minikui", "みにくい", "ミニクイ", "醜い", "ugly / unseemly dispute", "i-adjective", "Appearance & Style"),
    ("miryoku-teki na", "みりょくてきな", "ミリョクテキナ", "魅力的な", "fascinating / captivating / alluring", "na-adjective", "Appearance & Style"),
    ("misuborashii", "みすぼらしい", "ミスボラシイ", "みすぼらしい", "shabby / dilapidated / seedy clothes", "i-adjective", "Appearance & Style"),
    ("mitsu na", "みつな", "ミツナ", "密な", "dense / closely packed / intimate", "na-adjective", "Places & Spatial"),
    ("mittomonai", "みっともない", "ミットモナイ", "見っともない", "disgraceful / unseemly behavior", "i-adjective", "Social & Communication"),
    ("mizumizushii", "みずみずしい", "ミズミズシイ", "瑞々しい", "fresh and juicy fruit / youthful", "i-adjective", "Food & Taste"),
    ("modan na", "もだんな", "モダンナ", "モダンな", "chic / modern / stylish", "na-adjective", "Appearance & Style"),
    ("monosugoi", "ものすごい", "モノスゴイ", "物凄い", "stupendous / formidable / shocking", "i-adjective", "Degree & Intensity"),
    ("monotarinai", "ものたりない", "モノタリナイ", "物足りない", "leaving something to be desired / incomplete", "i-adjective", "Feelings & Mood"),
    ("moroi", "もろい", "モロイ", "脆い", "fragile glass / brittle bone / easily weeping", "i-adjective", "Appearance & Quality"),
    ("mottainai", "もったいない", "モッタイナイ", "勿体無い", "wasteful / too good for me / precious", "i-adjective", "Praise & Quality"),
    ("mottomo na", "もっともな", "モットモナ", "尤もな", "plausible / natural / justified argument", "na-adjective", "Character & Clarity"),
    ("muchi na", "むちな", "ムチナ", "無知な", "ignorant / unacquainted with fact", "na-adjective", "Character & Personality"),
    ("muda na", "むだな", "ムダナ", "無駄な", "fruitless / futile / wasteful of time", "na-adjective", "Conditions & States"),
    ("mudan no", "むだんの", "ムダンノ", "無断の", "unauthorized / without notice", "na-adjective", "Social & Communication"),
    ("muimi na", "むいみな", "ムイミナ", "無意味な", "meaningless / point-free", "na-adjective", "Conditions & States"),
    ("mujaki na", "むじゃきな", "ムジャキナ", "無邪気な", "guileless / simple innocent charm", "na-adjective", "Character & Personality"),
    ("mukanpatsu na", "むかんぱつな", "ムカンパツナ", "無関心な", "apathetic / unconcerned", "na-adjective", "Feelings & Mood"),
    ("mune ga atsuku naru", "むねがあつい", "ムネガアツイ", "胸が熱い", "heart filled with deep emotion", "i-adjective", "Feelings & Mood"),
    ("muri na", "むりな", "ムリナ", "無理な", "impossible / unreasonable / overexerting", "na-adjective", "Difficulty & Ease"),
    ("muryou no", "むりょうの", "ムリョウノ", "無料の", "free of charge / complimentary", "na-adjective", "Shopping & Money"),
    ("muzukashii", "むずかしい", "ムズカシイ", "難しい", "hard / difficult puzzle / problematic", "i-adjective", "Difficulty & Ease"),
    # N
    ("nagai", "ながい", "ナガイ", "長い", "long in distance or duration", "i-adjective", "Size & Shape"),
    ("nagayaka na", "なごやかな", "ナゴヤカナ", "和やかな", "genial / amiable / peaceful atmosphere", "na-adjective", "Feelings & Mood"),
    ("naisho no", "ないしょの", "ナイショノ", "内緒の", "confidential / secret between us", "na-adjective", "Social & Communication"),
    ("nama no", "なまの", "ナマノ", "生の", "raw sashimi / live concert broadcast", "na-adjective", "Food & Taste"),
    ("namamekashii", "なまめかしい", "ナマメカシイ", "艶めかしい", "alluring / bewitching / sultry", "i-adjective", "Appearance & Style"),
    ("namanamashii", "なまなましい", "ナマナマシイ", "生々しい", "vivid recollection / fresh wound", "i-adjective", "Conditions & States"),
    ("nameraka na", "なめらかな", "ナメラカナ", "滑らかな", "smooth skin / silky silk / fluent speech", "na-adjective", "Appearance & Quality"),
    ("namida-moroi", "なみだもろい", "ナミダモロイ", "涙脆い", "easily moved to tears / sentimental", "i-adjective", "Character & Personality"),
    ("nanboku no", "なんぼくの", "ナンボクノ", "南北の", "north-to-south orientation", "na-adjective", "Places & Spatial"),
    ("nani-ge-nai", "なにげない", "ナニゲナイ", "何気ない", "casual / nonchalant remark", "i-adjective", "Character & Personality"),
    ("narasareta", "ならされた", "ナラサレタ", "均された", "level / flattened out surface", "na-adjective", "Conditions & States"),
    ("natsukashii", "なつかしい", "ナツカシイ", "懐かしい", "nostalgic / dear old memory", "i-adjective", "Feelings & Mood"),
    ("nayashii", "なやましい", "ナヤマシイ", "悩ましい", "tantalizing / agonizingly seductive", "i-adjective", "Feelings & Mood"),
    ("nebari-zuyoi", "ねばりづよい", "ネバリヅヨイ", "粘り強い", "tenacious / dogged / persevering", "i-adjective", "Character & Personality"),
    ("neba-neba shita", "ねばねばした", "ネバネバシタ", "粘液な", "sticky / slimy (natto, okra)", "na-adjective", "Food & Taste"),
    ("nemutai", "ねむたい", "ネムタイ", "眠たい", "sleepy / drowsy after lunch", "i-adjective", "Body & Health"),
    ("nesshin na", "ねっしんな", "ネッシンナ", "熱心な", "enthusiastic / zealous / dedicated", "na-adjective", "Character & Personality"),
    ("netsuppoi", "ねつっぽい", "ネツッポイ", "熱っぽい", "feverish / impassioned", "i-adjective", "Body & Health"),
    ("nibui", "にぶい", "ニブイ", "鈍い", "dull knife / slow-witted / muted pain", "i-adjective", "Perception & Senses"),
    ("nigai", "にがい", "ニガイ", "苦い", "bitter coffee / harsh bitter memory", "i-adjective", "Food & Taste"),
    ("nigate na", "にがてな", "ニガテナ", "苦手な", "weak point / poor at / uncomfortable with", "na-adjective", "Difficulty & Ease"),
    ("nigiyaka na", "にぎやかな", "ニギヤカナ", "賑やかな", "bustling / bustling street / lively", "na-adjective", "Appearance & Mood"),
    ("nikurashii", "にくらしい", "ニクラシイ", "憎らしい", "odious / provoking / hateful", "i-adjective", "Feelings & Mood"),
    ("nikui", "にくい", "ニクイ", "憎い", "detestable / spiteful / admirably sharp", "i-adjective", "Feelings & Mood"),
    ("nimonai", "にてもにつかない", "ニテモニツカナイ", "似ても似つかない", "completely unalike / disparate", "i-adjective", "Character & Clarity"),
    ("ninki no aru", "にんきのある", "ニンキノアル", "人気のある", "popular among crowds", "na-adjective", "Social & Communication"),
    ("ninshiki no fukai", "にんしきのふかい", "ニンシキノフカイ", "認識の深い", "well-cognizant of problem", "i-adjective", "Work & Study"),
    ("nodoka na", "のどかな", "ノドカナ", "長閑な", "idyllic / tranquil pastoral village", "na-adjective", "Weather & Climate"),
    ("nokori no", "のこの", "ノコリノ", "残りの", "remaining / leftover portions", "na-adjective", "Conditions & States"),
    ("noroma na", "のろまな", "ノロマナ", "のろまな", "slow-moving / sluggish / dullard", "na-adjective", "Speed & Time"),
    ("noroi", "のろい", "ノロイ", "遅い", "sluggish / slow pace", "i-adjective", "Speed & Time"),
    ("nozomashii", "のぞましい", "ノゾマシイ", "望ましい", "desirable / preferable option", "i-adjective", "Praise & Quality"),
    ("nukumori no aru", "ぬくもりのある", "ヌクモリノアル", "温もりのある", "imbued with cozy human warmth", "na-adjective", "Feelings & Mood"),
    ("nurui", "ぬるい", "ヌルイ", "温い", "lukewarm soup / lax regulation", "i-adjective", "Weather & Senses"),
    # O
    ("oishii", "おいしい", "オイシイ", "美味しい", "delicious / flavorful / sweet deal", "i-adjective", "Food & Taste"),
    ("oi-sore to", "おいそれと", "オイソレト", "易々と", "readily / lightly done", "na-adjective", "Difficulty & Ease"),
    ("okashii", "おかしい", "オカシイ", "可笑しい", "funny / comical / peculiar / odd", "i-adjective", "Feelings & Mood"),
    ("okugai no", "おくがいの", "オクガイノ", "屋外の", "outdoor open-air", "na-adjective", "Places & Spatial"),
    ("okumenzasenu", "おくめんもない", "オクメンモナイ", "臆面もない", "unblushing / brazen-faced", "i-adjective", "Character & Personality"),
    ("okute na", "おくてな", "オクテナ", "奥手な", "late-blooming / shy in love", "na-adjective", "Character & Personality"),
    ("omoi", "おもい", "オモイ", "重い", "heavy stone / serious baggage / grave", "i-adjective", "Size & Shape"),
    ("omoshiroi", "おもしろい", "オモシロイ", "面白い", "fascinating / amusing / fun / curious", "i-adjective", "Feelings & Mood"),
    ("onaji no", "おなじの", "オナジノ", "同質の", "identical in nature", "na-adjective", "Conditions & States"),
    ("onwa na", "おんわな", "オンワナ", "温和な", "mild climate / gentle disposition", "na-adjective", "Character & Personality"),
    ("ookii", "おおきい", "オオキイ", "大きい", "big / massive / grand scale", "i-adjective", "Size & Shape"),
    ("ookina", "おおきな", "オオキナ", "大きな", "great / large / considerable", "na-adjective", "Size & Shape"),
    ("oomaka na", "おおまかな", "オオマカナ", "大まかな", "broad / rough approximation / general", "na-adjective", "Character & Clarity"),
    ("oo-matsuri no", "おおまつりの", "オオマツリノ", "大祭の", "grand festival day", "na-adjective", "Culture & Society"),
    ("ooshiki", "おおしい", "オオシイ", "雄々しい", "valiant / gallant / heroic", "i-adjective", "Character & Personality"),
    ("oosugiru", "おおすぎる", "オオスギル", "多すぎる", "far too plentiful / excessive", "i-adjective", "Degree & Intensity"),
    ("ootsubu no", "おおつぶの", "オオツブノ", "大粒の", "large-grained grapes / big raindrops", "na-adjective", "Size & Shape"),
    ("oouke no", "おおうけの", "オオウケノ", "大受けの", "wildly popular with audience", "na-adjective", "Social & Communication"),
    ("osoroshii", "おそろしい", "オソロシイ", "恐ろしい", "dreadful / terrifying / eerie power", "i-adjective", "Feelings & Mood"),
    ("osoi", "おそい", "オソイ", "遅い", "slow moving / late hour at night", "i-adjective", "Speed & Time"),
    ("otonashii", "おとなしい", "オトナシイ", "大人しい", "gentle / docile / quiet and meek", "i-adjective", "Character & Personality"),
    ("ouka na", "おうかな", "オウカナ", "横柄な", "arrogant / overbearing manners", "na-adjective", "Character & Personality"),
    ("oujou shita", "おうじょうした", "オウジョウシタ", "往生した", "hard pressed / at wits' end", "na-adjective", "Feelings & Mood"),
    ("ousetsu no", "おうせつの", "オウセツノ", "応接の", "reception parlor", "na-adjective", "Home & Living"),
    ("oyasui", "おやすい", "オヤスイ", "お安い", "inexpensive / easy as pie", "i-adjective", "Shopping & Money"),
    ("oyobigoshi na", "およびごしな", "オヨビゴシナ", "及び腰な", "hesitant / timid posture", "na-adjective", "Character & Personality"),
    # P & R
    ("parafuto na", "ぱーふぇくとな", "パーフェクトナ", "完全無欠な", "perfect in execution", "na-adjective", "Praise & Quality"),
    ("pichi-pichi shita", "ぴちぴちした", "ピチピチシタ", "ぴちぴちした", "bursting with youth / freshly caught", "na-adjective", "Appearance & Style"),
    ("pika-pika na", "ぴかぴかな", "ピカピカナ", "ぴかぴかな", "sparkling shiny clean / brand-new", "na-adjective", "Appearance & Quality"),
    ("purein na", "ぷれいんな", "プレインナ", "プレーンな", "plain yogurt / unadorned flavor", "na-adjective", "Food & Taste"),
    ("raku na", "らくな", "ラクマ", "楽な", "easy / effortless / comfortable living", "na-adjective", "Difficulty & Ease"),
    ("rakuten-teki na", "らくてんてきな", "ラクテンテキナ", "楽天的な", "optimistic / cheerful outlook", "na-adjective", "Character & Personality"),
    ("rashii", "らしい", "ラシイ", "らしい", "typical / seeming / characteristic", "i-adjective", "Conditions & States"),
    ("reigi-tadashii", "れいぎただしい", "レイギタダシイ", "礼儀正しい", "courteous / polite / well-bred", "i-adjective", "Character & Personality"),
    ("reisei na", "れいせいな", "レイセイナ", "冷静な", "calm / composed / cool-headed", "na-adjective", "Character & Personality"),
    ("reiketsu na", "れいけつな", "レイケツナ", "冷血な", "cold-blooded / callous / unfeeling", "na-adjective", "Character & Personality"),
    ("reikokou na", "れいこくな", "レイコクナ", "冷酷な", "ruthless / harsh / heartless", "na-adjective", "Character & Personality"),
    ("reishou na", "れいしょうな", "レイショウナ", "冷淡な", "indifferent / chilly demeanor", "na-adjective", "Character & Personality"),
    ("ren'ai no", "れんあいの", "レンアイノ", "恋愛の", "romantic / love-related", "na-adjective", "People & Family"),
    ("resuponsu no ii", "れすぽんすのいい", "レスポンスノイイ", "応答の早い", "responsive / quick feedback", "i-adjective", "Work & Study"),
    ("ripana", "りっぱな", "リッパナ", "立派な", "splendid / imposing / honorable deed", "na-adjective", "Praise & Quality"),
    ("risou-teki na", "りそうてきな", "リソウテキナ", "理想的な", "ideal / dream perfect setting", "na-adjective", "Praise & Quality"),
    ("ronri-teki na", "ろんりてきな", "ロンリテキナ", "論理的な", "logical / coherent reasoning", "na-adjective", "Work & Study"),
    ("ryoukou na", "りょうこうな", "リョウコウナ", "良好な", "favorable / in fine working condition", "na-adjective", "Conditions & States"),
    # S
    ("sabishii", "さびしい", "サビシイ", "寂しい", "lonely / desolate / solitary feelings", "i-adjective", "Feelings & Mood"),
    ("saigo no", "さいごの", "サイゴノ", "最後の", "ultimate / concluding / final", "na-adjective", "Conditions & States"),
    ("saiko no", "さいこうの", "サイコウノ", "最高の", "supreme / greatest / finest", "na-adjective", "Praise & Quality"),
    ("saiwai na", "さいわいな", "サイワイナ", "幸いな", "fortunate / blessed circumstance", "na-adjective", "Feelings & Mood"),
    ("sakarashii", "さかんな", "サカンナ", "盛んな", "thriving / vigorous / flourishing sport", "na-adjective", "Conditions & States"),
    ("sakura-iro no", "さくらいろの", "サクライロノ", "桜色の", "cherry blossom pink", "na-adjective", "Colors & Styles"),
    ("samui", "さむい", "サムイ", "寒い", "cold winter weather / freezing air", "i-adjective", "Weather & Climate"),
    ("sappari shita", "さっぱりした", "サッパリシタ", "さっぱりした", "refreshing taste / frankly candid", "na-adjective", "Food & Taste"),
    ("sarari to shita", "さらりとした", "サラリトシタ", "さらりとした", "smooth non-sticky texture / light", "na-adjective", "Appearance & Quality"),
    ("sawayaka na", "さわやかな", "サワヤカナ", "爽やかな", "refreshing morning breeze / crisp air", "na-adjective", "Weather & Climate"),
    ("seichou shita", "せいちょうした", "セイチョウシタ", "成長した", "grown-up / mature", "na-adjective", "People & Family"),
    ("seijitsu na", "せいじつな", "セイジツナ", "誠実な", "sincere / truthful / faithful", "na-adjective", "Character & Personality"),
    ("seikaku na", "せいかくな", "セイカクナ", "正確な", "accurate / precise / faultless timing", "na-adjective", "Work & Study"),
    ("seiketsu na", "せいけつな", "セイケツナ", "清潔な", "hygienic / clean and spotless", "na-adjective", "Safety & Health"),
    ("seikou na", "せいこうな", "セイコウナ", "精巧な", "exquisite / elaborate craftsmanship", "na-adjective", "Praise & Quality"),
    ("seinou no takai", "せいのうのたかい", "セイノウノタカイ", "性能の高い", "high-performance apparatus", "i-adjective", "Praise & Quality"),
    ("seishun no", "せいしゅんの", "セイシュンノ", "青春の", "youthful / golden spring of life", "na-adjective", "Culture & Society"),
    ("semai", "せまい", "セマイ", "狭い", "narrow alley / cramped space", "i-adjective", "Size & Shape"),
    ("senmei na", "せんめいな", "センメイナ", "鮮明な", "vivid / distinct picture / sharp", "na-adjective", "Character & Clarity"),
    ("sensai na", "せんさいな", "センサイナ", "繊細な", "delicate / sensitive / exquisitely nuanced", "na-adjective", "Appearance & Style"),
    ("senshin-teki na", "せんしんてきな", "センシンテキナ", "先進的な", "cutting-edge / progressive", "na-adjective", "Praise & Quality"),
    ("sentaku no hiroi", "せんたくのひろい", "センタクノヒロイ", "選択肢の広い", "with broad options", "i-adjective", "Conditions & States"),
    ("shiawase na", "しあわせな", "シアワセナ", "幸せな", "happy / blessed / joyful in family", "na-adjective", "Feelings & Mood"),
    ("shibui", "しぶい", "シブイ", "渋い", "astringent persimmon / subdued chic taste", "i-adjective", "Food & Taste"),
    ("shikakui", "しかくい", "シカクイ", "四角い", "square / rectangular geometry", "i-adjective", "Size & Shape"),
    ("shinpi-teki na", "しんぴてきな", "シンピテキナ", "神秘的な", "mystical / enigmatic / arcane", "na-adjective", "Conditions & States"),
    ("shinsetsu na", "しんせつな", "シンセツナ", "親切な", "kind-hearted / thoughtful neighbor", "na-adjective", "Social & Communication"),
    ("shinsen na", "しんせんな", "シンセンナ", "新鮮な", "fresh seafood / clean breeze", "na-adjective", "Food & Taste"),
    ("shizuka na", "しずかな", "シズカナ", "静かな", "quiet / serene / tranquil night", "na-adjective", "Appearance & Mood"),
    ("shojiki na", "しょうじきな", "ショウジキナ", "正直な", "honest / forthright / candid", "na-adjective", "Character & Personality"),
    ("shounin no", "しょうにんの", "ショウニンノ", "商人の", "mercantile / merchant-minded", "na-adjective", "Culture & Society"),
    ("shousai na", "しょうさいな", "ショウサイナ", "詳細な", "detailed / comprehensive report", "na-adjective", "Work & Study"),
    ("shun no", "しゅんの", "シュンノ", "旬の", "in-season / peak flavor ingredient", "na-adjective", "Food & Taste"),
    ("subarashii", "すばらしい", "スバラシイ", "素晴らしい", "magnificent / marvelous / superb", "i-adjective", "Praise & Quality"),
    ("subayai", "すばやい", "スバヤイ", "素早い", "quick / nimble / rapid reflex", "i-adjective", "Speed & Time"),
    ("sugoi", "すごい", "スゴイ", "凄い", "awesome / incredible / terrifying", "i-adjective", "Praise & Quality"),
    ("sukoshi no", "すこしの", "スコシノ", "少しの", "a little / tiny amount", "na-adjective", "Degree & Intensity"),
    ("sukunai", "すくない", "スクナイ", "少ない", "few / scarce / meager count", "i-adjective", "Degree & Intensity"),
    ("suppai", "すっぱい", "スッパイ", "酸っぱい", "sour lemon / vinegar tang", "i-adjective", "Food & Taste"),
    ("surudoi", "するどい", "スルドイ", "鋭い", "sharp kitchen knife / keen intuition", "i-adjective", "Character & Personality"),
    ("suzushii", "すずしい", "スズシイ", "涼しい", "refreshing cool evening breeze", "i-adjective", "Weather & Climate"),
    # T
    ("tadashii", "ただしい", "タダシイ", "正しい", "correct / just / righteous", "i-adjective", "Character & Clarity"),
    ("taihou no you na", "たいほうのような", "タイホウノヨウナ", "大砲のような", "cannon-like booming voice", "na-adjective", "Appearance & Style"),
    ("taira na", "たいらな", "タイラナ", "平らな", "flat / level meadow / even", "na-adjective", "Size & Shape"),
    ("taisetsu na", "たいせつな", "タイセツナ", "大切な", "precious / dear / important heirloom", "na-adjective", "Praise & Quality"),
    ("taikutsu na", "たいくつな", "タイクツナ", "退屈な", "tedious / boring / dull lecture", "na-adjective", "Feelings & Mood"),
    ("takai", "たかい", "タカイ", "高い", "high mountain / expensive price", "i-adjective", "Size & Shape"),
    ("takusan no", "たくさんの", "タクサンノ", "沢山の", "many / plentiful / numerous", "na-adjective", "Degree & Intensity"),
    ("tanoshii", "たのしい", "タノシイ", "楽しい", "enjoyable / cheerful / fun outing", "i-adjective", "Feelings & Mood"),
    ("tashika na", "たしかな", "タシカナ", "確かな", "certain / reliable / verified evidence", "na-adjective", "Character & Clarity"),
    ("tasuu no", "たすうの", "タスウノ", "多数の", "in the majority / plural", "na-adjective", "Degree & Intensity"),
    ("tayori ni naru", "たよりになる", "タヨリニナル", "頼りになる", "trustworthy / dependable mentor", "i-adjective", "Character & Personality"),
    ("tegoro na", "てごろな", "テゴロナ", "手頃な", "moderate price / manageable size", "na-adjective", "Shopping & Money"),
    ("teinei na", "ていねいな", "テイネイナ", "丁寧な", "polite / meticulous / conscientious", "na-adjective", "Social & Communication"),
    ("teki-setsu na", "てきせつな", "テキセツナ", "適切な", "suitable / apt / appropriate measure", "na-adjective", "Conditions & States"),
    ("tetsujin no you na", "てつじんのような", "テツジンノヨウナ", "鉄人のような", "iron-willed / indestructible", "na-adjective", "Character & Personality"),
    ("tobikiri no", "とびきりの", "トビキリノ", "飛び切りの", "extraordinary / superlative best", "na-adjective", "Praise & Quality"),
    ("tokubetsu na", "とくべつな", "トクベツナ", "特別な", "special / extraordinary / exceptional", "na-adjective", "Praise & Quality"),
    ("tokui na", "とくいな", "トクイナ", "得意な", "one's forte / proud triumph", "na-adjective", "Character & Personality"),
    ("tooi", "とおい", "トオイ", "遠い", "far / distant country / remote past", "i-adjective", "Places & Spatial"),
    ("totetsumonai", "とてつもない", "トテツモナイ", "途轍もない", "astronomical / unfathomable / preposterous", "i-adjective", "Degree & Intensity"),
    ("tsuyoi", "つよい", "ツヨイ", "強い", "strong / powerful / robust character", "i-adjective", "Character & Personality"),
    ("tsumetai", "つめたい", "ツメタイ", "冷たい", "cold ice / chilly distant reception", "i-adjective", "Weather & Senses"),
    ("tsurasa no aru", "つらい", "ツライ", "辛い", "painful ordeal / heartbreaking grief", "i-adjective", "Feelings & Mood"),
    # U & W & Y & Z
    ("utsukushii", "うつくしい", "ウツクシイ", "美しい", "beautiful / gorgeous / poetic landscape", "i-adjective", "Appearance & Style"),
    ("umai", "うまい", "ウマイ", "美味い", "flavorful tasty / skillful gamer", "i-adjective", "Food & Taste"),
    ("ureshii", "うれしい", "ウレシイ", "嬉しい", "happy / joyful / delighted by good news", "i-adjective", "Feelings & Mood"),
    ("usui", "うすい", "ウスイ", "薄い", "thin slice / pale watercolor / light flavor", "i-adjective", "Appearance & Quality"),
    ("utagawashii", "うたがわしい", "ウタガワシイ", "疑わしい", "suspicious / doubtful veracity", "i-adjective", "Conditions & States"),
    ("wakai", "わかい", "ワカイ", "若い", "youthful / tender-aged / inexperienced", "i-adjective", "People & Family"),
    ("warui", "わるい", "ワルイ", "悪い", "bad / evil / inferior quality", "i-adjective", "Conditions & States"),
    ("wazuka na", "わずかな", "ワズカナ", "僅かな", "scant / slight difference / faint trace", "na-adjective", "Degree & Intensity"),
    ("yasashii-kind", "やさしい", "ヤサシイ", "優しい", "tender-hearted / gentle / kind", "i-adjective", "Character & Personality"),
    ("yasashii-easy", "やさしい", "ヤサシイ", "易しい", "easy / simple problem / elementary", "i-adjective", "Difficulty & Ease"),
    ("yasui", "やすい", "ヤスイ", "安い", "inexpensive / economical / cheap", "i-adjective", "Shopping & Money"),
    ("yawarakai", "やわらかい", "ヤワラカイ", "柔らかい", "soft bread / tender beef / supple", "i-adjective", "Appearance & Quality"),
    ("yoi", "よい", "ヨイ", "良い", "good / wholesome / auspicious", "i-adjective", "Praise & Quality"),
    ("yowai", "よわい", "ヨワイ", "弱い", "weak / fragile health / low alcohol", "i-adjective", "Character & Personality"),
    ("yutaka na", "ゆたかな", "ユタカナ", "豊かな", "abundant nature / rich harvest / fertile", "na-adjective", "Praise & Quality"),
    ("yuumei na", "ゆうめいな", "ユウメイナ", "有名な", "famous / acclaimed / renowned", "na-adjective", "Praise & Quality"),
    ("zankoku na", "ざんこくな", "ザンコクナ", "残酷な", "cruel / ruthless / merciless", "na-adjective", "Character & Personality"),
    ("zetsumyou na", "ぜつみょうな", "ゼツミョウナ", "絶妙な", "superb balance / miraculous timing", "na-adjective", "Praise & Quality")
]
