# Japanese Onomatopoeia and Mimetic adverbs (Giongo / Gitaigo)
# (romaji, hiragana, katakana, kanji, meaning, topic)
DATA = [
    # A
    ("asa-yake de kira-kira", "あさやけできらきら", "アサヤケデキラキラ", "朝焼けでキラキラ", "sparkling brightly in morning sun", "Onomatopoeia & Mimetic"),
    ("asobi de wai-wai", "あそびでわいわい", "アソビデワイワイ", "遊びでワイワイ", "boisterously playing together", "Onomatopoeia & Mimetic"),
    ("asoko de koro-koro", "あそこできころころ", "アソコデコロコロ", "コロコロ転がる", "rolling lightly along", "Onomatopoeia & Mimetic"),
    ("atama ga gan-gan", "あたまががんがん", "アタマガガンガン", "頭がガンガン", "throbbing head / splitting headache", "Onomatopoeia & Mimetic"),
    ("atama ga kura-kura", "あたまがくらくら", "アタマガクラクラ", "頭がクラクラ", "feeling dizzy / room spinning", "Onomatopoeia & Mimetic"),
    ("ase de bisho-bisho", "あせでびしょびしょ", "アセデビショビショ", "汗でビショビショ", "drenched in sweat", "Onomatopoeia & Mimetic"),
    ("ase de beta-beta", "あせでべたべた", "アセデベタベタ", "汗でベタベタ", "sticky with perspiration", "Onomatopoeia & Mimetic"),

    # B
    ("bari-bari", "ばりばり", "バリバリ", "バリバリ", "crunchily / tearing energetically", "Onomatopoeia & Mimetic"),
    ("basa-basa", "ばさばさ", "バサバサ", "バサバサ", "dry and rustling / flutter of wings", "Onomatopoeia & Mimetic"),
    ("bata-bata", "ばたばた", "バタバタ", "バタバタ", "hurriedly / flurried / flapping", "Onomatopoeia & Mimetic"),
    ("biku-biku", "びくびく", "ビクビク", "ビクビク", "fearfully / timidly / trembling", "Onomatopoeia & Mimetic"),
    ("bishi-bishi", "びしばし", "ビシビシ", "ビシビシ", "strictly / rigorously without relent", "Onomatopoeia & Mimetic"),
    ("bisho-nure ni", "びしょぬれに", "ビショヌレニ", "びしょ濡れに", "soaking wet / completely drenched", "Onomatopoeia & Mimetic"),
    ("bita-bita", "びたびた", "ビタビタ", "ビタビタ", "dripping wet / soaking continuously", "Onomatopoeia & Mimetic"),
    ("bobo-to", "ぼうぼうと", "ボウボウト", "ぼうぼうと", "blazing fiercely / roaring flames", "Onomatopoeia & Mimetic"),
    ("boke-boke", "ぼけぼけ", "ボケボケ", "ボケボケ", "blurry / out of focus / hazy", "Onomatopoeia & Mimetic"),
    ("boko-boko", "ぼこぼこ", "ボコボコ", "ボコボコ", "bumpy / full of potholes / bubbling", "Onomatopoeia & Mimetic"),
    ("bon-bon", "ぼんぼん", "ボンボン", "ボンボン", "chiming loudly / recklessly tossing", "Onomatopoeia & Mimetic"),
    ("bonyari-to", "ぼんやりと", "ボンヤリト", "ぼんやりと", "faintly / absentmindedly / vacantly", "Onomatopoeia & Mimetic"),
    ("boro-boro", "ぼろぼろ", "ボロボロ", "ボロボロ", "tattered / crumbling / weeping tears", "Onomatopoeia & Mimetic"),
    ("boso-boso", "ぼそぼそ", "ボソボソ", "ボソボソ", "muttering under breath / dry texture", "Onomatopoeia & Mimetic"),
    ("bota-bota", "ぼたぼた", "ボタボタ", "ボタボタ", "dripping in big heavy drops", "Onomatopoeia & Mimetic"),
    ("buchi-buchi", "ぶちぶち", "ブチブチ", "ブチブチ", "snapping one after another / grumbling", "Onomatopoeia & Mimetic"),
    ("buka-buka", "ぶかぶか", "ブカブカ", "ブカブカ", "too baggy / loose fitting (clothes)", "Onomatopoeia & Mimetic"),
    ("bun-bun", "ぶんぶん", "ブンブン", "ブンブン", "buzzing / humming / swinging fast", "Onomatopoeia & Mimetic"),
    ("bura-bura", "ぶらぶら", "ブラブラ", "ぶらぶら", "strolling leisurely / dangling idle", "Onomatopoeia & Mimetic"),
    ("bururu-to", "ぶるると", "ブルルト", "ぶるると", "shivering with sudden cold shudder", "Onomatopoeia & Mimetic"),
    ("butsu-butsu", "ぶつぶつ", "ブツブツ", "ぶつぶつ", "grumbling / muttering discontent", "Onomatopoeia & Mimetic"),

    # C
    ("chaki-chaki", "ちゃきちゃき", "チャキチャキ", "ちゃきちゃき", "brisk / vivacious / genuine downtowner", "Onomatopoeia & Mimetic"),
    ("chanto", "ちゃんと", "チャント", "ちゃんと", "properly / neatly / reliably", "Manner & State"),
    ("chibi-chibi", "ちびちび", "チビチビ", "ちびちび", "sipping little by little", "Onomatopoeia & Mimetic"),
    ("chiku-chiku", "ちくちく", "チクチク", "ちくちく", "prickly / stinging sensation", "Onomatopoeia & Mimetic"),
    ("chin-to", "ちんと", "チント", "ちんと", "sitting meekly and quiet / microwave ding", "Onomatopoeia & Mimetic"),
    ("chira-chira", "ちらちら", "チラチラ", "ちらちら", "glancing subtly / gently falling snow", "Onomatopoeia & Mimetic"),
    ("chira-ri to", "ちらりと", "チラリト", "ちらりと", "catching a momentary glimpse", "Onomatopoeia & Mimetic"),
    ("chiri-chiri", "ちりちり", "チリチリ", "ちりちり", "frizzy hair / sizzling lightly", "Onomatopoeia & Mimetic"),
    ("choko-choko", "ちょこちょこ", "チョコチョコ", "ちょこちょこ", "toddling with small fast steps", "Onomatopoeia & Mimetic"),
    ("choro-choro", "ちょろちょろ", "チョロチョロ", "ちょろちょろ", "trickling stream / darting around", "Onomatopoeia & Mimetic"),
    ("chotto", "ちょっと", "チョット", "一寸", "a little / briefly / somewhat", "Degree & Quantity"),

    # D
    ("daba-daba", "だばだば", "ダバダバ", "ダバダバ", "running comically with flailing arms", "Onomatopoeia & Mimetic"),
    ("dara-dara", "だらだら", "ダラダラ", "だらだら", "dripping lazily / slouching endlessly", "Onomatopoeia & Mimetic"),
    ("dari-dari", "だらりと", "ダラリト", "だらりと", "hanging limply down", "Onomatopoeia & Mimetic"),
    ("deki-deki", "どきどき", "ドキドキ", "ドキドキ", "heart pounding excitedly", "Onomatopoeia & Mimetic"),
    ("deki-tate", "できたてほやほやで", "デキタテホヤホヤデ", "出来立てホヤホヤで", "piping hot from the grill", "Food & Dining"),
    ("doba-doba", "どばどば", "ドバドバ", "どばどば", "pouring out in huge gushes", "Onomatopoeia & Mimetic"),
    ("dobon-to", "どぼんと", "ドボント", "どぼんと", "with a heavy splash into water", "Onomatopoeia & Mimetic"),
    ("do-do-to", "どうどうと", "ドウドウト", "堂々と", "majestically / proudly without hesitation", "Manner & State"),
    ("dokan-to", "どかんと", "ドカント", "どかんと", "with a massive bang / huge volume at once", "Onomatopoeia & Mimetic"),
    ("doka-doka", "どかどか", "ドカドカ", "どかどか", "barging in noisily and abruptly", "Onomatopoeia & Mimetic"),
    ("doko-doko", "どこどこ", "ドコドコ", "ドコドコ", "rapid drumming thumps", "Onomatopoeia & Mimetic"),
    ("dokkiri-to", "どっきりと", "ドッキリト", "どっきりと", "startled out of one's wits", "Onomatopoeia & Mimetic"),
    ("doku-doku", "どくどく", "ドクドク", "どくどく", "pulsing blood gush / pouring vigorously", "Onomatopoeia & Mimetic"),
    ("don-don", "どんどん", "ドンドン", "どんどん", "steadily progressing / drumming bang", "Speed & Time"),
    ("doro-doro", "どろどろ", "ドロドロ", "どろどろ", "muddy / gooey / slushy / messy drama", "Onomatopoeia & Mimetic"),
    ("dosa-dosa", "どさどさ", "ドサドサ", "どさどさ", "dropping in heavy heap / piled books", "Onomatopoeia & Mimetic"),
    ("dosshin-to", "どっしんと", "ドッシント", "どっしんと", "heavily crashing down with thud", "Onomatopoeia & Mimetic"),
    ("dotabata", "どたばた", "ドタバタ", "ドタバタ", "noisy slapstick / scurrying feet", "Onomatopoeia & Mimetic"),
    ("dotto", "どっと", "ドット", "どっと", "all at once / bursting into laughter or tears", "Quantity & Degree"),

    # F
    ("fawa-fawa", "ふわふわ", "フワフワ", "ふわふわ", "fluffy / buoyant / floating soft", "Onomatopoeia & Mimetic"),
    ("fui-to", "ふいと", "フイト", "ふいと", "abruptly / out of nowhere", "Speed & Time"),
    ("fuka-fuka", "ふかふか", "フカフカ", "ふかふか", "soft and plush / freshly baked bread", "Onomatopoeia & Mimetic"),
    ("fuki-fuki", "ふきふき", "フキフキ", "ふきふき", "briskly wiping clean", "Onomatopoeia & Mimetic"),
    ("fuku-fuku", "ふくふく", "フクフク", "ふくふく", "plump and cheerful / blooming health", "Onomatopoeia & Mimetic"),
    ("fumu-fumu", "ふむふむ", "フムフム", "ふむふむ", "nodding thoughtfully in agreement", "Manner & State"),
    ("fura-fura", "ふらふら", "フラフラ", "ふらふら", "unsteady / staggering lightheaded", "Onomatopoeia & Mimetic"),
    ("furi-furi", "ふりふり", "フリフリ", "ふりふり", "waving frantically / tail wagging", "Onomatopoeia & Mimetic"),
    ("furu-furu", "ふるふる", "フルフル", "ふるふる", "trembling delicately / quivering jelly", "Onomatopoeia & Mimetic"),
    ("fusa-fusa", "ふさふさ", "フサフサ", "ふさふさ", "thick and bushy mane / lush hair", "Onomatopoeia & Mimetic"),
    ("futto", "ふっと", "フット", "ふっと", "suddenly / sighing softly / flashing thought", "Speed & Time"),
    ("fuu-fuu", "ふうふう", "フウフウ", "ふうふう", "blowing on hot soup / panting tired", "Food & Dining"),

    # G
    ("gaba-to", "がばと", "ガバト", "がばと", "springing up suddenly in bed", "Onomatopoeia & Mimetic"),
    ("gabu-gabu", "がぶがぶ", "ガブガブ", "がぶがぶ", "gulping down liquid greedily", "Food & Dining"),
    ("gachagacha", "がちゃがちゃ", "ガチャガチャ", "がちゃがちゃ", "clattering noisily / rattling dishes", "Onomatopoeia & Mimetic"),
    ("gakkari", "がっかり", "ガッカリ", "がっかり", "dejectedly / utterly disappointed", "Manner & State"),
    ("gaku-gaku", "がくがく", "ガクガク", "がくがく", "knees shaking in fear / loose joint", "Onomatopoeia & Mimetic"),
    ("gan-gan", "がんがん", "ガンガン", "ガンガン", "hammering hard / aggressively attacking", "Manner & State"),
    ("gara-gara", "がらがら", "ガラガラ", "ガラガラ", "clattering rattle / totally empty train", "Manner & State"),
    ("gasa-gasa", "がさがさ", "ガサガサ", "がさがさ", "rustling paper / rough dry skin", "Onomatopoeia & Mimetic"),
    ("gasshiri", "がっしり", "ガッシリ", "がっしり", "sturdily built / firmly locked", "Appearance & Style"),
    ("gatsu-gatsu", "がつがつ", "ガツガツ", "がつがつ", "eating ravenously / greedy ambition", "Food & Dining"),
    ("geba-geba", "げばげば", "ゲバゲバ", "ゲバゲバ", "gaudy / roughly painted lines", "Onomatopoeia & Mimetic"),
    ("geho-geho", "げほげほ", "ゲホゲホ", "げほげほ", "hacking dry coughs", "Onomatopoeia & Mimetic"),
    ("geko-geko", "げこげこ", "ゲコゲコ", "げこげこ", "frogs croaking in rice paddy", "Nature & Climate"),
    ("gen-to", "げんと", "ゲント", "厳と", "sternly and uncompromisingly", "Manner & State"),
    ("giku-shaku", "ぎくしゃく", "ギクシャク", "ぎくしゃく", "awkwardly / strained relations", "Manner & State"),
    ("gin-gin", "ぎんぎん", "ギンギン", "ギンギン", "wide awake / glaring intensely bright", "Onomatopoeia & Mimetic"),
    ("gira-gira", "ぎらぎら", "ギラギラ", "ぎらぎら", "blazing fiercely / glaring sun", "Onomatopoeia & Mimetic"),
    ("giri-giri", "ぎりぎり", "ギリギリ", "ぎりぎり", "just barely in the nick of time", "Speed & Time"),
    ("gishi-gishi", "ぎしぎし", "ギシギシ", "ぎしぎし", "creaking floorboards / squeezed tight", "Onomatopoeia & Mimetic"),
    ("gita-gita", "ぎたぎた", "ギタギタ", "ぎたぎた", "greasy and smeared with oil", "Food & Dining"),
    ("gobo-gobo", "ごぼごぼ", "ゴボゴボ", "ごぼごぼ", "gurgling spring water / bubbling", "Nature & Climate"),
    ("gogo-to", "ごうごうと", "ゴウゴウト", "轟々と", "roaring tempest / rumbling waterfall", "Nature & Climate"),
    ("goku-goku", "ごくごく", "ゴクゴク", "ごくごく", "drinking refreshing water in gulps", "Food & Dining"),
    ("gomi-gomi", "ごみごみ", "ゴミゴミ", "ごみごみ", "cluttered / cramped and squalid", "Places & Spatial"),
    ("goro-goro", "ごろごろ", "ゴロゴロ", "ごろごろ", "rolling around at home / thunder rumbling", "Manner & State"),
    ("gorori-to", "ごろりと", "ゴロリト", "ごろりと", "lying down heavily to rest", "Manner & State"),
    ("gosa-gosa", "ごさごさ", "ゴサゴサ", "ごさごさ", "rustling coarse brush", "Onomatopoeia & Mimetic"),
    ("goshi-goshi", "ごしごし", "ゴシゴシ", "ごしごし", "scrubbing vigorously with brush", "Manner & State"),
    ("gotabata", "ごたごた", "ゴタゴタ", "ごたごた", "entangled in chaos / squabbling troubles", "Manner & State"),
    ("goto-goto", "ごとごと", "ゴトゴト", "ごとごと", "rattling along tracks / simmering pot", "Onomatopoeia & Mimetic"),
    ("gotsun-to", "ごつんと", "ゴツント", "ごつんと", "hitting head with audible bump", "Onomatopoeia & Mimetic"),
    ("guchagucha", "ぐちゃぐちゃ", "グチャグチャ", "ぐちゃぐちゃ", "squishy and messy / utterly ruined", "Onomatopoeia & Mimetic"),
    ("gugu-to", "ぐぐっと", "ググット", "ぐぐっと", "pushing deeply with immense leverage", "Manner & State"),
    ("gumi-gumi", "ぐみぐみ", "グミグミ", "ぐみぐみ", "chewy and gum-like consistency", "Food & Dining"),
    ("guni-guni", "ぐにぐに", "グニグニ", "ぐにぐに", "pliable and easily deformed by hand", "Onomatopoeia & Mimetic"),
    ("gunkaku-to", "ぐんぐんと", "グングント", "ぐんぐんと", "shooting up rapidly / bounding forward", "Speed & Time"),
    ("gura-gura", "ぐらぐら", "グラグラ", "ぐらぐら", "shaking violently / boiling water", "Manner & State"),
    ("guri-guri", "ぐりぐり", "グリグリ", "ぐりぐり", "rubbing knuckles in firm circles", "Manner & State"),
    ("guru-guru", "ぐるぐる", "グルグル", "ぐるぐる", "spinning round and round in circles", "Onomatopoeia & Mimetic"),
    ("guta-guta", "ぐだぐだ", "グダグダ", "ぐだぐだ", "rambling on tediously / slack mood", "Manner & State"),
    ("guttari", "ぐったり", "グッタリ", "ぐったり", "exhausted and limp from fatigue", "Manner & State"),
    ("gutto", "ぐっと", "グット", "ぐっと", "firmly pulling / emotionally touched", "Degree & Extent"),

    # H
    ("hachikire-n bakari ni", "はちきれんばかりに", "ハチキレンバカリニ", "はち切れんばかりに", "ready to burst at the seams", "Degree & Extent"),
    ("haki-haki", "はきはき", "ハキハキ", "はきはき", "crisply and articulately speaking", "Manner & State"),
    ("hakkiri", "はっきり", "ハッキリ", "はっきり", "clearly / distinctly / unequivocally", "Manner & State"),
    ("hara-hara", "はらはら", "ハラハラ", "はらはら", "on pins and needles / fluttering petals", "Feelings & Mood"),
    ("haritsumete", "はりつめて", "ハリツメテ", "張り詰めて", "under intense nervous tension", "Manner & State"),
    ("hasu ni", "はすに", "ハスニ", "斜に", "diagonally / looking askance", "Places & Spatial"),
    ("hata-to", "はたと", "ハタト", "はたと", "suddenly striking upon an answer", "Manner & State"),
    ("hata-hata", "はたはた", "ハタハタ", "はたはた", "flapping in the autumn breeze", "Onomatopoeia & Mimetic"),
    ("heko-heko", "へこへこ", "ヘコヘコ", "へこへこ", "kowtowing obsequiously / bowing low", "Manner & State"),
    ("heto-heto", "へとへと", "ヘトヘト", "へとへと", "completely dead tired / dog-tired", "Manner & State"),
    ("hie-hie", "ひえひえ", "ヒエヒエ", "冷え冷え", "chillingly cool / freezing draft", "Nature & Climate"),
    ("hifu-hifu", "ひいひい", "ヒイヒイ", "ひいひい", "groaning and panting under heavy load", "Onomatopoeia & Mimetic"),
    ("hiku-hiku", "ひくひく", "ヒクヒク", "ひくひく", "twitching nose or eyelid repeatedly", "Onomatopoeia & Mimetic"),
    ("hira-hira", "ひらひら", "ヒラヒラ", "ひらひら", "fluttering gently like butterfly wings", "Onomatopoeia & Mimetic"),
    ("hiri-hiri", "ひりひり", "ヒリヒリ", "ひりひり", "tingling burning pain / spicy tongue", "Food & Dining"),
    ("hiro-hiro", "ひろびろと", "ヒロビロト", "広々と", "spaciously / in panoramic expanse", "Places & Spatial"),
    ("hiso-hiso", "ひそひそ", "ヒソヒソ", "ひそひそ", "whispering secrets in hushed undertones", "Manner & State"),
    ("hitasura", "ひたすら", "ヒタスラ", "一筋に", "earnestly / wholeheartedly single-minded", "Manner & State"),
    ("hitori-de ni", "ひとりでに", "ヒトリデニ", "独りでに", "spontaneously of its own accord", "Condition & Logic"),
    ("hitosujini", "ひとすじに", "ヒトスジニ", "一筋に", "devoted exclusively to one path", "Manner & State"),
    ("hiyakari-to", "ひんやりと", "ヒンヤリト", "ひんやりと", "refreshingly cool to the touch", "Nature & Climate"),
    ("hodo-hodo ni", "ほどほどに", "ホドホドニ", "程々に", "in healthy moderation", "Degree & Quantity"),
    ("hoka-hoka", "ほかほか", "ホカホカ", "ほかほか", "steaming warm buns / pleasantly heated", "Food & Dining"),
    ("hoko-hoko", "ほこほこ", "ホコホコ", "ほこほこ", "warm and fluffy steamed sweet potatoes", "Food & Dining"),
    ("hono-bono", "ほのぼの", "ホノボノ", "ほのぼの", "heartwarming and warmly affectionate", "Feelings & Mood"),
    ("horo-horo", "ほろほろ", "ホロホロ", "ほろほろ", "meat falling tenderly off bone / shedding tears", "Food & Dining"),
    ("horori-to", "ほろりと", "ホロリト", "ほろりと", "moved to sentimental gentle tears", "Feelings & Mood"),
    ("hoshigari-ni", "ほしそうに", "ホシソウニ", "欲しそうに", "looking on longingly with yearning", "Feelings & Mood"),
    ("hoso-boso to", "ほそぼそと", "ホソボソト", "細々と", "eking out a modest quiet living", "Manner & State"),
    ("hotto", "ほっと", "ホット", "ほっと", "sighing in vast heartfelt relief", "Feelings & Mood"),
    ("hoyo-hoyo", "ほやほや", "ホヤホヤ", "ほやほや", "fresh out of the oven / newlywed", "Food & Dining"),

    # I, J
    ("ichi-moku-san ni", "いちもくさんに", "イチモクサンニ", "一目散に", "at top breakneck speed fleeing", "Speed & Time"),
    ("ira-ira", "いらいら", "イライラ", "イライラ", "fretful / irritated / testy", "Feelings & Mood"),
    ("itchi-danchi de", "いっちだんけつして", "イッチダンケツシテ", "一致団結して", "in united solidary harmony", "Manner & State"),
    ("ji-ji-to", "じーじーと", "ジージート", "じーじーと", "frying oil sizzling / cicadas buzzing", "Nature & Climate"),
    ("jika ni", "じかに", "ジカニ", "直に", "directly in person / without mediator", "Manner & State"),
    ("jiku-jiku", "じくじく", "ジクジク", "じくじく", "oozing wet / damp weeping wound", "Onomatopoeia & Mimetic"),
    ("jimen ni betari", "じめんにべたりと", "ジメンニベタリト", "地面にべたりと", "plastered flat against the ground", "Places & Spatial"),
    ("jin-jin", "じんじん", "ジンジン", "じんじん", "throbbing from deep cold or pain", "Onomatopoeia & Mimetic"),
    ("jinwari-to", "じんわりと", "ジンワリト", "じんわりと", "gradually welling up with warmth", "Feelings & Mood"),
    ("jiro-jiro", "じろじろ", "ジロジロ", "じろじろ", "staring intently / scrutinizing head to toe", "Manner & State"),
    ("jiri-jiri", "じりじり", "ジリジリ", "じりじり", "scorching sun baking down / inching closer", "Nature & Climate"),
    ("jito-jito", "じとじと", "ジトジト", "じとじと", "clammy and sticky with humidity", "Nature & Climate"),
    ("jitsu-ni", "じつに", "ジツニ", "実に", "truly / indeed / remarkably so", "Degree & Extent"),
    ("jiwa-jiwa", "じわじわ", "ジワジワ", "じわじわ", "slowly but surely permeating", "Speed & Time"),
    ("jotto", "じっと", "ジット", "じっと", "holding still / enduring silently", "Manner & State"),
    ("juki-juki", "ずきずき", "ズキズキ", "ずきずき", "throbbing head or tooth pain", "Onomatopoeia & Mimetic"),
    ("jun-to", "じゅんと", "ジュント", "ジュント", "sizzling hot drop hitting skillet", "Food & Dining"),
    ("jyuu-jyuu", "じゅうじゅう", "ジュウジュウ", "じゅうじゅう", "sizzling grilled meat on hot teppan", "Food & Dining"),

    # K
    ("kaba-kaba", "かぱかぱ", "カパカパ", "カパカパ", "clomping horses hooves", "Onomatopoeia & Mimetic"),
    ("kachi-kachi", "かちかち", "カチカチ", "かちかち", "frozen solid / ticking clock", "Manner & State"),
    ("kafu-kafu", "かふかふ", "カフカフ", "カフカフ", "munching warm buns happily", "Food & Dining"),
    ("kankan ni okotte", "かんかんにおこって", "カンカンニオコッテ", "かんかんに怒って", "furious and spitting mad", "Feelings & Mood"),
    ("kapo-kapo", "ぽくぽく", "ポクポク", "ぽくぽく", "clacking temple wooden block", "Onomatopoeia & Mimetic"),
    ("kara-kara", "からから", "カラカラ", "からから", "bone-dry throat / laughing heartily", "Manner & State"),
    ("karari-to", "からりと", "カラリト", "からりと", "crisp sunny sky clearing up", "Nature & Climate"),
    ("kari-kari", "かりかり", "カリカリ", "カリカリ", "crisp fried bacon / touchy irritable", "Food & Dining"),
    ("kasa-kasa", "かさかさ", "カサカサ", "かさかさ", "rustling autumn leaves / dry chapped skin", "Onomatopoeia & Mimetic"),
    ("katsu-katsu", "かつかつ", "カツカツ", "カツカツ", "clicking high heels / living hand to mouth", "Manner & State"),
    ("kawa-kawa", "からからと", "カラカラト", "空々と", "echoing laughter through hall", "Manner & State"),
    ("ke-ke-to", "けたけたと", "ケタケタト", "けたけたと", "cackling in shrill loud laugh", "Manner & State"),
    ("kera-kera", "けらけら", "ケラケラ", "けらけら", "giggling cheerfully without restraint", "Manner & State"),
    ("kero-ri to", "けろりと", "ケロリト", "けろりと", "nonchalant as if nothing occurred", "Manner & State"),
    ("kibi-kibi", "きびきび", "キビキビ", "きびきび", "crisp, snappy and energetic conduct", "Manner & State"),
    ("kichinto", "きちんと", "キチント", "きちんと", "neatly, meticulously arranged", "Manner & State"),
    ("kii-kii", "きいきい", "キイキイ", "きいきい", "shrill squeaking bicycle brakes", "Onomatopoeia & Mimetic"),
    ("kime-komaka ni", "きめこまかに", "キメコマカニ", "きめ細やかに", "attentively in high fine detail", "Manner & State"),
    ("kin-kin", "きんきん", "キンキン", "キンキン", "ringing bell / piercing shrill / icy cold beer", "Body & Senses"),
    ("kira-kira", "きらきら", "キラキラ", "きらきら", "glistening stars / sparkling eyes", "Appearance & Style"),
    ("kirari-to", "きらりと", "キラリト", "きらりと", "gleaming with sharp brilliant flash", "Appearance & Style"),
    ("kiri-kiri", "きりきり", "キリキリ", "きりきり", "sharp stabbing stomach ache", "Body & Senses"),
    ("kiri-to", "きりっと", "キリット", "きりっと", "smartly composed / sharp dapper suit", "Appearance & Style"),
    ("kishi-kishi", "きしきし", "キシキシ", "きしきし", "squeaking taut hinges", "Onomatopoeia & Mimetic"),
    ("kobo-kobo", "こぼこぼ", "コボコボ", "こぼこぼ", "pouring water into earthen jar", "Onomatopoeia & Mimetic"),
    ("koko-to", "ここと", "ココト", "孤高と", "standing aloof and sublime", "Manner & State"),
    ("koku-koku", "こくこく", "コクコク", "こくこく", "nodding in solemn agreement repeatedly", "Manner & State"),
    ("kome-kamini", "こめかみに", "コメカミニ", "こめかみに", "throbbing at the temples", "Body & Senses"),
    ("kora-kora to", "こらこらと", "コラコラト", "こらこらと", "scolding playfully 'now now!'", "Social & Communication"),
    ("koro-koro", "ころころ", "コロコロ", "ころころ", "rolling marbles / frequently changing mind", "Manner & State"),
    ("koso-koso", "こそこそ", "コソコソ", "こそこそ", "sneaking about stealthily", "Manner & State"),
    ("kote-kote", "こてこて", "コテコテ", "こてこて", "rich heavy Osaka broth / heavily coated", "Food & Dining"),
    ("koto-koto", "ことこと", "コトコト", "ことこと", "simmering stew gently over low flame", "Food & Dining"),
    ("kotsun-to", "こつんと", "コツント", "こつんと", "light rap on wooden desk", "Onomatopoeia & Mimetic"),
    ("kotsu-kotsu", "こつこつ", "コツコツ", "こつこつ", "patiently chipping away diligently", "Manner & State"),
    ("kucha-kucha", "くちゃくちゃ", "クチャクチャ", "くちゃくちゃ", "chewing noisily / crumpled mess", "Manner & State"),
    ("kune-kune", "くねくね", "クネクネ", "くねくね", "winding serpentine path / wriggling", "Places & Spatial"),
    ("kura-kura", "くらくら", "クラクラ", "くらくら", "woozy / swimming head / vertigo", "Body & Senses"),
    ("kuri-kuri", "くりくり", "クリクリ", "くりくり", "round big doe-like eyes", "Appearance & Style"),
    ("kuru-kuru", "くるくる", "クルクル", "くるくる", "whirling swiftly / winding ribbon", "Speed & Time"),
    ("kusha-kusha", "くしゃくしゃ", "クシャクシャ", "くしゃくしゃ", "crumpled handkerchief / ruffled hair", "Appearance & Style"),
    ("kusukusu", "くすくす", "クスクス", "くすくす", "snickering / chuckling under breath", "Manner & State"),
    ("kute-kute", "くたくた", "クタクタ", "くたくた", "boiled limp vegetables / bone tired", "Manner & State"),
    ("kyon-to", "きょんと", "キョント", "きょんと", "blankly innocent stare", "Manner & State"),
    ("kyoro-kyoro", "きょろきょろ", "キョロキョロ", "きょろきょろ", "looking all around bewildered", "Manner & State"),
    ("kyutto", "きゅっと", "キュット", "きゅっと", "squeezing tightly / downing sake shot", "Manner & State"),
]
