# Japanese Degree, Extent, Quantity, and Manner Adverbs
# (romaji, hiragana, katakana, kanji, meaning, topic)
DATA = [
    # A
    ("abunaku", "あぶなく", "アブナク", "危うく", "nearly / almost / within a hair's breadth", "Degree & Extent"),
    ("aikawarazu no goukai sa", "あいかわらずのごうかいさで", "アイカワラズノゴウカイサデ", "相変わらずの豪快さで", "with characteristic hearty grandeur", "Manner & State"),
    ("akarasama ni", "あからさまに", "アカラサマニ", "露骨に", "blatantly / openly / without filter", "Manner & State"),
    ("akkirito", "あっさりと", "アッサリト", "あっさりと", "lightly / cleanly / without lingering", "Manner & State"),
    ("aku-made mo", "あくまでも", "アクマデモ", "飽くまでも", "to the bitter end / strictly / purely", "Degree & Extent"),
    ("amaku mite", "あまくみて", "アワクミテ", "甘く見て", "taking lightly / underestimating", "Manner & State"),
    ("amari", "あまり", "アマリ", "余り", "not very (neg) / excessively", "Degree & Extent"),
    ("amari ni mo", "あまりにも", "アマリニモ", "余りにも", "all too / excessively beyond bounds", "Degree & Extent"),
    ("an'i ni", "あんいに", "アンイニ", "安易に", "too lightly / casually / without care", "Manner & State"),
    ("anata-rashiku", "あなたらしく", "アナタラシク", "あなたらしく", "true to your own wonderful self", "Manner & State"),
    ("anna ni", "あんなに", "アンナニ", "あんなに", "to that immense degree / so much like that", "Degree & Extent"),
    ("appara na made ni", "あっぱれなまでに", "アッパレナマデニ", "天晴れなまでに", "to an admirable, stunning degree", "Degree & Extent"),
    ("arata ni", "あらたに", "アラタニ", "新たに", "anew / freshly / from a clean slate", "Manner & State"),
    ("ari no mama ni", "ありのままに", "アリノママニ", "有りの侭に", "just as things truly are / frankly", "Manner & State"),
    ("asa-haka ni", "あさはかに", "アサハカニ", "浅はかに", "shallowly / rashly without foresight", "Manner & State"),
    ("ase-daku de", "あせだくで", "アセダクデ", "汗だくで", "dripping drenched in honest sweat", "Manner & State"),
    ("atatakaku", "あたたかく", "アタタカク", "温かく", "warmly / cordially welcoming", "Manner & State"),
    ("atsu-atsude", "あつあつで", "アツアツデ", "熱々で", "piping sizzling hot", "Food & Dining"),
    ("atsuku", "あつく", "アツク", "熱く", "passionately / ardently", "Manner & State"),
    ("ayafuya ni", "あやふやに", "アヤフヤニ", "あやふやに", "vaguely / noncommittally", "Manner & State"),
    ("azayaka ni", "あざやかに", "アザヤカニ", "鮮やかに", "vividly / brilliantly / masterfully", "Manner & State"),

    # B
    ("baka ni dekizu", "ばかにできず", "バカニデキズ", "馬鹿にできず", "not to be underestimated or sneered at", "Degree & Extent"),
    ("bakuzen to", "ばくぜんと", "バクゼント", "漠然と", "obscurely / without crisp definition", "Manner & State"),
    ("basshirito", "ばっさりと", "バッサリト", "ばっさりと", "decisively severing / boldly cutting", "Manner & State"),
    ("batsu-gun ni", "ばつぐんに", "バツグンニ", "抜群に", "preeminently / outstandingly above rest", "Degree & Extent"),
    ("betsu ni", "べつに", "ベツニ", "別に", "not particularly / nothing special", "Degree & Extent"),
    ("bimyona hodo ni", "びみょうなほどに", "ビミョウナホドニ", "微妙なほどに", "to a delicately nuanced degree", "Degree & Extent"),
    ("bita ichi-en tari tomo", "びたいちえんたりとも", "ビタイチエンタリトモ", "一文たりとも", "not even a solitary single yen", "Degree & Quantity"),
    ("bozen to", "ぼうぜんと", "ボウゼント", "呆然と", "dumbfounded / in stunned disbelief", "Manner & State"),
    ("bunseki-teki ni", "ぶんせきてきに", "ブンセキテキニ", "分析的に", "systematically and analytically", "Manner & State"),
    ("byoudou ni", "びょうどうに", "ビョウドウニ", "平等に", "equally / impartially to all", "Manner & State"),

    # C
    ("chakujitsu ni", "ちゃくじつに", "チャクジツニ", "着実に", "steadily / surely / step by solid step", "Manner & State"),
    ("chikara-ippai", "ちからいっぱい", "チカライッパイ", "力一杯", "with every ounce of physical power", "Degree & Extent"),
    ("chikara-zuyoku", "ちからづよく", "チカラヅヨク", "力強く", "powerfully / reassuringly", "Manner & State"),
    ("chitsujo tadashiku", "ちつじょただしく", "チツジョタダシク", "秩序正しく", "in orderly disciplined formation", "Manner & State"),
    ("chokusetsu ni", "ちょくせつに", "チョクセツニ", "直接に", "directly in personal contact", "Manner & State"),
    ("choudo yoku", "ちょうどよく", "チョウドヨク", "丁度良く", "just right / in perfect sweet spot", "Degree & Extent"),
    ("choushi yoku", "ちょうしよく", "チョウシヨク", "調子良く", "smoothly sailing / glibly", "Manner & State"),
    ("chou-soku de", "ちょうそくで", "チョウソクデ", "超速で", "at ultra-high supersonic speed", "Speed & Time"),
    ("chuushin ni", "ちゅうしんに", "チュウシンニ", "中心に", "focusing primarily around the core", "Places & Spatial"),
    ("chuujitsu ni", "ちゅうじつに", "チュウジツニ", "忠実に", "faithfully / true to the original", "Manner & State"),

    # D
    ("dai-ichi ni", "だいいちに", "ダイイチニ", "第一に", "first and foremost as top priority", "Sequence & Logic"),
    ("daibu", "だいぶ", "ダイブ", "大分", "considerably / very much / mostly", "Degree & Extent"),
    ("daikibo ni", "だいきぼに", "ダイキボニ", "大規模に", "on an enormous, grand scale", "Degree & Extent"),
    ("daitai", "だいたい", "ダイタイ", "大体", "approximately / generally / broadly", "Degree & Quantity"),
    ("daitan ni", "だいたんに", "ダイタンニ", "大胆に", "boldly / audaciously / daringly", "Manner & State"),
    ("danzen", "だんぜん", "ダンゼン", "断然", "by a country mile / far and away best", "Degree & Extent"),
    ("dasshou ni", "だっしょうに", "ダッショウニ", "脱臼するほどに", "almost dislocating from intensity", "Degree & Extent"),
    ("dokuji ni", "どくじに", "ドクジニ", "独自に", "independently / in one's proprietary style", "Manner & State"),
    ("dokutoku ni", "どくとくに", "ドクトクニ", "独特の", "uniquely and distinctively", "Manner & State"),
    ("dondon susunde", "どんどんすすんで", "ドンドンサスンジデ", "どんどん進んで", "bounding ahead in leaps and bounds", "Speed & Time"),
    ("dorehodo", "どれほど", "ドレホド", "どれ程", "how very much / to what extraordinary extent", "Degree & Extent"),
    ("doushitemo", "どうして", "ドウシテモ", "どうしても", "by all means / no matter what", "Condition & Logic"),

    # E
    ("egao de", "えがおで", "エガオデ", "笑顔で", "with a beaming warm smile", "Manner & State"),
    ("eikyou o ukete", "えいきょうをうけて", "エイキョウヲウケテ", "影響を受けて", "under the deep inspiring influence", "Condition & Logic"),
    ("enman ni", "えんまんに", "エンマンニ", "円満に", "harmoniously and amicably settled", "Manner & State"),
    ("enryo naku", "えんりょなく", "エンリョナク", "遠慮なく", "without hesitation / make yourself at home", "Manner & State"),
    ("erai koto ni", "えらいことに", "エライコトニ", "えらい事に", "in a tremendously huge pickle", "Degree & Extent"),

    # F
    ("fukai kanashimi de", "ふかいかなしみで", "フカイカナシミデ", "深い悲しみで", "in deep bottomless sorrow", "Feelings & Mood"),
    ("fukaku", "ふかく", "フカク", "深く", "deeply / profoundly", "Degree & Extent"),
    ("fuki-nukeru you ni", "ふきぬけるように", "フキヌケルヨウニ", "吹き抜けるように", "like a sweeping refreshing breeze", "Nature & Climate"),
    ("fukusuu de", "ふくすうで", "フクスウデ", "複数で", "in numbers / in multiple parties", "Degree & Quantity"),
    ("fushigi to", "ふしぎと", "フシギト", "不思議と", "mysteriously enough / curiously", "Condition & Logic"),
    ("fushou-bushou ni", "ふしょうぶしょうに", "フショウブショウニ", "不承不承に", "grudgingly / against one's real will", "Manner & State"),
    ("futsuu ni", "ふつうに", "フツウニ", "普通に", "normally / ordinarily / quite genuinely", "Manner & State"),
    ("fuuzen no tomoshibi de", "ふうぜんのともしびで", "フウゼンノトモシビデ", "風前の灯火で", "precariously hanging like candle in wind", "Degree & Extent"),

    # G
    ("gai-kanjou", "がいかんじょう", "ガイカンジョウ", "概観上", "viewed in broad panorama", "Places & Spatial"),
    ("gakuzen to shite", "がくぜんとして", "ガクゼントシテ", "愕然として", "struck dumb with sheer shock", "Feelings & Mood"),
    ("gaman-tsuyoku", "がまんづよく", "ガマンヅヨク", "我慢強く", "patiently persevering with grit", "Manner & State"),
    ("ganban no gotoku", "がんばんのごとく", "ガンバンノゴトク", "岩盤の如く", "solid as granite bedrock", "Degree & Extent"),
    ("ganjou ni", "がんじょうに", "ガンジョウニ", "頑丈に", "sturdily built / reinforced securely", "Manner & State"),
    ("ganko ni", "がんこに", "ガンコニ", "頑固に", "stubbornly / tenaciously refusing", "Manner & State"),
    ("geijutsu-teki ni", "げいじゅつてきに", "ゲイジュツテキニ", "芸術的に", "artistically / exquisitely arranged", "Manner & State"),
    ("gekitetsu de", "げきてつで", "ゲキテツデ", "劇鉄で", "dramatically striking like hammer", "Manner & State"),
    ("gekiteki ni", "げきてきに", "ゲキテキニ", "劇的に", "dramatically / astonishingly transformed", "Degree & Extent"),
    ("genkaku ni", "げんかくに", "ゲンカクニ", "厳格に", "strictly according to the letter", "Manner & State"),
    ("genki yoku", "げんきよく", "ゲンキヨク", "元気よく", "spiritedly and cheerfully", "Manner & State"),
    ("genmitsu ni", "げんみつに", "ゲンミツニ", "厳密に", "rigorously / precisely in scientific truth", "Manner & State"),
    ("genten ni kaette", "げんてんにかえって", "ゲンテンニカエッテ", "原点に返って", "returning fundamentally to first principles", "Sequence & Logic"),
    ("giman-teki ni", "ぎまんてきに", "ギマンテキニ", "欺瞞的に", "deceitfully / disingenuously", "Manner & State"),
    ("giri de", "ぎりで", "ギリデ", "義理で", "out of polite social obligation", "Manner & State"),
    ("gokai o osorezu ni", "ごかいをおそれずに", "ゴカイヲオソレズニ", "誤解を恐れずに", "without fear of being misunderstood", "Manner & State"),
    ("goku", "ごく", "ゴク", "極", "extremely / very / quite", "Degree & Extent"),
    ("goku-shousuu de", "ごくしょうすうで", "ゴクショウスウデ", "極少数で", "in only a very minuscule few", "Degree & Quantity"),
    ("gouin ni", "ごういんに", "ゴウインニ", "強引に", "forcefully pushing one's agenda", "Manner & State"),
    ("gouka ni", "ごうかに", "ゴウカニ", "豪華に", "luxuriously / sumptuously styled", "Manner & State"),
    ("gun-to", "ぐんと", "グント", "ぐんと", "by a big leap / surging noticeably", "Degree & Extent"),

    # H
    ("hageshiku", "はげしく", "ハゲシク", "激しく", "violently / fiercely / passionately", "Degree & Extent"),
    ("hakkiri to", "はっきりと", "ハッキリト", "はっきりと", "clearly / unambiguously distinct", "Manner & State"),
    ("hakuryoku man-ten de", "はくりょくまんてんで", "ハクリョクマンテンデ", "迫力満点で", "with jaw-dropping thrilling power", "Degree & Extent"),
    ("hanbun", "はんぶん", "ハンブン", "半分", "by half / fifty percent", "Degree & Quantity"),
    ("han-kyou-teki ni", "はんきょうてきに", "ハンキョウテキニ", "半狂乱で", "in a near-frenzied frenzy", "Feelings & Mood"),
    ("haruka ni", "はるかに", "ハルカニ", "遥かに", "by far / worlds ahead / distantly", "Degree & Extent"),
    ("heibon ni", "へいぼんに", "ヘイボンニ", "平凡に", "ordinarily / without fanfare", "Manner & State"),
    ("heiki de", "へいきで", "ヘイキデ", "平気で", "coolly unbothered / nonchalantly", "Manner & State"),
    ("heikou shite", "へいこうして", "ヘイコウシテ", "並行して", "in tandem / side by side", "Sequence & Logic"),
    ("heizen to", "へいぜんと", "ヘイゼント", "平然と", "calmly as if nothing happened", "Manner & State"),
    ("hidoku", "ひどく", "ヒドク", "酷く", "terribly / dreadfully / intensely", "Degree & Extent"),
    ("hieshou de", "ひえしょうで", "ヒエショウデ", "冷え症で", "suffering cold hands and feet", "Body & Senses"),
    ("hijou ni", "ひじょうに", "ヒジョウニ", "非常に", "exceptionally / extraordinarily", "Degree & Extent"),
    ("hiketsu toshite", "ひけつとして", "ヒケツトシテ", "秘訣として", "as the guarded secret key", "Manner & State"),
    ("hikkurikaette", "ひっくりかえって", "ヒックリカエッテ", "ひっくり返って", "flipping completely upside down", "Manner & State"),
    ("hisshi ni", "ひっしに", "ヒッシニ", "必死に", "desperately / for dear life", "Manner & State"),
    ("hitasura ni", "ひたすらに", "ヒタスラニ", "一筋に", "earnestly with whole heart", "Manner & State"),
    ("hito-koto de", "ひとことで", "ヒトコトデ", "一言で", "in a single concise nutshell phrase", "Social & Communication"),
    ("hito-kumi de", "ひとくみで", "ヒトクミデ", "一組で", "as a coordinated pair/set", "Degree & Quantity"),
    ("hito-namihazurete", "ひとなみはずれて", "ヒトナミハズレテ", "人並み外れて", "towering far above the average", "Degree & Extent"),
    ("hito-omoi ni", "ひとおもいに", "ヒトオモイニ", "一思いに", "without hesitation / in one fell swoop", "Speed & Time"),
    ("hito-toori", "ひととおり", "ヒトトオリ", "一通り", "roughly in general / covering basics", "Degree & Extent"),
    ("hitori-nokorazu", "ひとりのこらず", "ヒトリノコラズ", "一人残らず", "everyone to the last person", "Degree & Quantity"),
    ("hodohodo ni", "ほどほどに", "ホドホドニ", "程々に", "in balanced healthy moderation", "Degree & Quantity"),
    ("hon-ki de", "ほんきで", "ホンキデ", "本気で", "in dead earnest / seriously", "Manner & State"),
    ("hon-ne de", "ほんねで", "ホンネデ", "本音で", "candidly from one's honest heart", "Social & Communication"),
    ("hontou ni", "ほんとうに", "ホントウニ", "本当に", "truly / genuinely / really", "Degree & Extent"),
    ("houba-yaki no gotoku", "ほうばやきのごとく", "ホウバヤキノゴトク", "朴葉焼きの如く", "savory and fragrant like grilled miso", "Food & Dining"),
    ("hyakubun no ichi de", "ひゃくぶんのいちで", "ヒャクブンノイチデ", "百分の一で", "reduced to one-hundredth portion", "Degree & Quantity"),

    # I
    ("ichidan to", "いちだんと", "イチダント", "一段と", "a notch higher / still more remarkably", "Degree & Extent"),
    ("ichigai ni", "いちがいに", "イチガイニ", "一概に", "unconditionally / sweeps all under one rug", "Condition & Logic"),
    ("ichigo-ichie de", "いちごいちえで", "イチゴイチエデ", "一期一会で", "treasuring as a once-in-lifetime encounter", "Manner & State"),
    ("ichiji ga banji", "いちじがばんじ", "イチジガバンジ", "一事が万事", "the whole reflected in a single sample", "Condition & Logic"),
    ("ichiryoushou ni", "いちりょうしょうに", "イチリョウショウニ", "一両日中に", "within a day or two", "Speed & Time"),
    ("ikigurashiku", "いきぐるしく", "イキグルシク", "息苦しく", "suffocatingly tight / stifling", "Manner & State"),
    ("ikioi yoku", "いきおいよく", "イキオイヨク", "勢いよく", "vigorously / with surging momentum", "Manner & State"),
    ("ikura nan demo", "いくらなんでも", "イクラナンデモ", "幾ら何でも", "no matter how you cut it / excessively", "Degree & Extent"),
    ("ippai ni", "っぱいに", "イッパイニ", "一杯に", "to full capacity / brimming over", "Degree & Quantity"),
    ("isshou-kenmei ni", "いっしょうけんめいに", "イッショウケンメイニ", "一生懸命に", "with every drop of sincere energy", "Manner & State"),
    ("ittou-ryoudan ni", "いっとうりょうだんに", "イットウリョウダンニ", "一刀両断に", "severing with one decisive stroke", "Manner & State"),
    ("iwaba", "いわば", "イワバ", "言わば", "so to speak / as it were", "Condition & Logic"),

    # J
    ("jiyuu ni", "じゆうに", "ジユウニ", "自由に", "freely / at one's own leisure", "Manner & State"),
    ("jouju de", "じょうずで", "ジョウズデ", "上手で", "skillfully / adeptly executed", "Manner & State"),
    ("joujun ni", "じょうじゅんに", "ジョウジュンニ", "上旬に", "in the first ten days of the month", "Speed & Time"),
    ("juubun ni", "じゅうぶんに", "ジュウブンニ", "十分に", "sufficiently / amply / generously", "Degree & Quantity"),
    ("juudan de", "じゅうだんで", "ジュウダンデ", "縦断で", "traversing north to south across", "Places & Spatial"),

    # K
    ("kagiri naku", "かぎりなく", "カギリナク", "限りなく", "boundlessly / infinitively close to", "Degree & Extent"),
    ("kaiteki ni", "かいてきに", "カイテキニ", "快適に", "comfortably / cozily without strain", "Manner & State"),
    ("kakudai shite", "かくだいして", "カクダイシテ", "拡大して", "expanding on an enlarged scale", "Degree & Extent"),
    ("kanari", "かなり", "カナリ", "可なり", "considerably / quite a lot / rather", "Degree & Extent"),
    ("kanzen ni", "かんぜんに", "カンゼンニ", "完全に", "completely / perfectly / entirely", "Degree & Extent"),
    ("karugaruto", "かるがると", "カルガルト", "軽々と", "effortlessly / lifting with ease", "Manner & State"),
    ("kasuka ni", "かすかに", "カスカニ", "微かに", "faintly / hazily discernable", "Degree & Extent"),
    ("kesshite", "けっして", "ケッシテ", "決して", "by no means / never ever (with neg)", "Condition & Logic"),
    ("kirei ni", "きれいに", "キレイニ", "綺麗に", "neatly / cleanly / completely cleared", "Manner & State"),
    ("kiwamete", "きわめて", "キワメテ", "極めて", "exceedingly / supremely / critically", "Degree & Extent"),
    ("kouketsu ni", "こうけつに", "コウケツニ", "高潔に", "with noble spotless integrity", "Manner & State"),
    ("koukyuu ni", "こうきゅうに", "コウキュウニ", "高級に", "first-class in luxury style", "Manner & State"),
    ("koushou ni", "こうしょうに", "コウショウニ", "高尚に", "loftily and with sublime taste", "Manner & State"),

    # M
    ("masu-masu", "ますます", "マスマス", "益々", "more and more / increasingly so", "Degree & Extent"),
    ("mattaku", "まったく", "マッタク", "全く", "entirely / truly / completely", "Degree & Extent"),
    ("meikaku ni", "めいかくに", "メイカクニ", "明確に", "clearly / unequivocally stated", "Manner & State"),
    ("messou mo nai hodo", "めっそうもないほど", "メッソウモナイホド", "滅相もない程", "beyond polite belief", "Degree & Extent"),
    ("mezamashiku", "めざましく", "メザマシク", "目覚ましく", "strikingly / remarkably improved", "Degree & Extent"),
    ("midari ni", "みだりに", "ミダリニ", "妄りに", "recklessly / indiscriminately / without cause", "Manner & State"),
    ("minna de", "みんなで", "ミンナデ", "皆で", "together with all friends / in group", "People & Family"),
    ("mitame yori mo", "みためよりも", "ミタメヨリモ", "見た目よりも", "much more than meets the initial eye", "Degree & Extent"),
    ("motto", "もっと", "モット", "もっと", "even more / further still", "Degree & Extent"),
    ("muri ni", "むりに", "ムリニ", "無理に", "forcibly / against nature / overexerting", "Manner & State"),

    # N - Z
    ("naosara", "なおさら", "ナオサラ", "尚更", "all the more / even still more so", "Degree & Extent"),
    ("nasakebukaku", "なさけぶかく", "ナサケブカク", "情け深く", "with compassionate boundless warmth", "Manner & State"),
    ("natto de neba-neba", "なっとうでねばねばと", "ナットウデネバネバト", "納豆でネバネバと", "stickily strings flowing with vigor", "Food & Dining"),
    ("negattari-kanattari de", "ねがったりかなったりで", "ネガッタリカナッタリデ", "願ったり叶ったりで", "in perfect harmony with wishes", "Feelings & Mood"),
    ("nekkyo-teki ni", "ねっきょうてきに", "ネッキョウテキニ", "熱狂的に", "feverishly / with fanatical zeal", "Feelings & Mood"),
    ("nemu-sou ni", "ねむそうに", "ネムソウニ", "眠そうに", "sleepily rubbing eyelids", "Body & Senses"),
    ("nikoniko to", "にこにこと", "ニコニコト", "にこにこと", "smiling radiantly and cheerfully", "Manner & State"),
    ("nokorazu", "のこらず", "ノコラズ", "残らず", "without a solitary bit remaining", "Degree & Quantity"),
    ("nomikonde", "のみこんで", "ノミコンデ", "飲み込んで", "internalizing deeply into heart", "Manner & State"),
    ("ochitsuite", "おちついて", "オチツイテ", "落ち着いて", "calmly, coolly and collected", "Manner & State"),
    ("oikonde", "おいこんで", "オイコンデ", "追い込んで", "driving forward to peak performance", "Manner & State"),
    ("oishiku", "おいしく", "オイシク", "美味しく", "deliciously / savoring with delight", "Food & Dining"),
    ("omoikkiri", "おもいっきり", "オモイッキリ", "思いっ切り", "to one's heart's absolute content", "Degree & Extent"),
    ("omomuki-bukaku", "おもむきぶかく", "オモムキブカク", "趣深く", "with profound tasteful charm", "Appearance & Style"),
    ("onaji you ni", "おなじように", "オナジヨウニ", "同じように", "identically / in the selfsame manner", "Manner & State"),
    ("onkyou-teki ni", "おんきょうてきに", "オンキョウテキニ", "音響的に", "acoustically / in audio fidelity", "Body & Senses"),
    ("orikou ni", "おりこうに", "オリコウニ", "お利口に", "cleverly / behaving like a good child", "People & Family"),
    ("oshiri-atari ni", "おしりあたりに", "オシリアタリニ", "お尻あたりに", "around the hips or tail end", "Places & Spatial"),
    ("osoroshii hodo", "おそろしいほど", "オソロシイホド", "恐ろしい程", "to a terrifying, awesome extent", "Degree & Extent"),
    ("raku ni", "らくに", "ラクニ", "楽に", "easily / comfortably / without strain", "Manner & State"),
    ("reikoku ni", "れいこくに", "レイコクニ", "冷酷に", "cold-heartedly / ruthlessly", "Manner & State"),
    ("reisei ni", "れいせいに", "レイセイニ", "冷静に", "calmly, rationally and composed", "Manner & State"),
    ("saikou ni", "さいこうに", "サイコウニ", "最高に", "at the pinnacle / supremely best", "Degree & Extent"),
    ("saiwai ni mo", "さいわいにも", "サイワイニモ", "幸いにも", "fortunately / blessedly enough", "Condition & Logic"),
    ("shikiri ni", "しきりに", "シキリニ", "頻りに", "incessantly / persistently again", "Frequency & Habit"),
    ("shikkari to", "しっかりと", "シッカリト", "しっかりと", "firmly / solidly / holding tightly", "Manner & State"),
    ("shin-shin to", "しんしんと", "シンシント", "深々と", "falling quietly (snow) / piercing cold", "Nature & Climate"),
    ("shou-shou", "しょうしょう", "ショウショウ", "少々", "just a slight touch / a little bit", "Degree & Quantity"),
    ("subete", "すべて", "スベテ", "全て", "all / entirely / completely", "Degree & Quantity"),
    ("sukkari", "すっかり", "スッカリ", "すっかり", "thoroughly / completely cleaned out", "Degree & Extent"),
    ("taihen", "たいへん", "タイヘン", "大変", "immensely / gravely / terribly", "Degree & Extent"),
    ("totemo", "とても", "トテモ", "とても", "very / exceedingly / immensely", "Degree & Extent"),
    ("tsuyoku", "つよく", "ツヨク", "強く", "strongly / vigorously / firmly", "Degree & Extent"),
    ("wazuka ni", "わずかに", "ワズカニ", "僅かに", "only slightly / by a razor-thin margin", "Degree & Quantity"),
    ("wari-to", "わりと", "ワリト", "割と", "comparatively / relatively / fairly", "Degree & Extent"),
    ("yagate wa", "やがては", "ヤガテワ", "軈ては", "eventually / in due course of events", "Speed & Time"),
    ("yoppodo", "よっぽど", "ヨッポド", "余程", "by far / much more considerably", "Degree & Extent"),
    ("yutaka ni", "ゆたかに", "ユタカニ", "豊かに", "abundantly / lavishly / prosperously", "Degree & Extent"),
    ("zutto", "ずっと", "ズット", "ずっと", "all along / by far and away better", "Degree & Extent"),
]
