# Comprehensive Japanese Adverbs I through Z (350+ unique entries)
# (romaji, hiragana, katakana, kanji, meaning, topic)
DATA = [
    # I
    ("i-bukashige ni mite", "いぶかしげにみて", "イブカシゲニミテ", "訝しげに見て", "looking on with suspicious skepticism", "Feelings & Mood"),
    ("ichidai-kesshin o shite", "いちだいけっしんをして", "イチダイケッシヲシテ", "一大決心をして", "having resolved upon a life-altering choice", "Feelings & Mood"),
    ("ichido kiri no jinsei", "いちどきりのじんせいで", "イチドキリノジンセイデ", "一度きりの人生で", "in this one and only mortal life", "Condition & Logic"),
    ("ichiryuu no ryouriya de", "いちりゅうのりょうりやで", "イチリュウノリョウリヤデ", "一流の料理屋で", "at an elite Michelin-grade restaurant", "Food & Dining"),
    ("idai na ashiato o nokoshi", "いだいなあしあとをのこし", "イダイナアシアトヲノコシ", "偉大な足跡を残し", "leaving a monumental legacy for ages", "Condition & Logic"),
    ("ijou na netsui de", "いじょうなねついで", "イジョウナネツイデ", "異常な熱意で", "with extraordinary, burning intensity", "Feelings & Mood"),
    ("ikiru tame ni", "きるために", "イキルタメニ", "生きるために", "for the sacred purpose of living", "Condition & Logic"),
    ("ikitodokoita sabisu de", "いきとどいたさーびすで", "イキトドイタサービスデ", "行き届いたサービスで", "with flawless, attentive hospitality", "Social & Communication"),
    ("ikizukai o hisomete", "いきづかいをひそめて", "イキヅカイヲヒソメテ", "息遣いを潜めて", "holding breath in pin-drop quiet", "Manner & State"),
    ("inshou-bukaku kataru", "いんしょうぶかくかたる", "インショウブカクカタル", "印象深く語る", "recounting with profound impression", "Social & Communication"),
    ("ippan no hito toshite", "いっぱんのひととして", "イッパンノヒトトシテ", "一般の人として", "as an everyday member of the public", "People & Family"),
    ("iron na katachi de", "いろいろなかたちで", "イロイロナカタチデ", "色々な形で", "in diverse multitude of variations", "Degree & Quantity"),
    ("itsuwari naku", "いつわりなく", "イツワリナク", "偽りなく", "without an ounce of deceit or falsehood", "Social & Communication"),

    # J
    ("jiden o kaki-nagara", "じでんをかきながら", "ジデンヲカキナガラ", "自伝を書きながら", "while penning one's autobiographical memoirs", "Social & Communication"),
    ("jigou-jitoku to mitome", "じごうじとくとみとめ", "ジゴウジトクトミトメ", "自業自得と認め", "admitting it was all of one's own making", "Condition & Logic"),
    ("jikan o wasurete", "じかんをわすれて", "ジカンヲワスレテ", "時間を忘れて", "losing all track of fleeting hours", "Speed & Time"),
    ("jikkuri to ajiwatte", "じっくりとあじわって", "ジックリトアジワッテ", "じっくりと味わって", "savoring deliberately every single note", "Food & Dining"),
    ("jiko-chuushin ni", "じこちゅうしんに", "ジコチュウシンニ", "自己中心に", "selfishly centering only on self", "Personality & Trait"),
    ("jinkouteki ni tsukura-re", "じんこうてきにつくられ", "ジンコウテキニツクラレ", "人工的に作られ", "synthesized by human craftsmanship", "Condition & Logic"),
    ("jitsuryoku de kachi-tori", "じつりょくでかちとり", "ジツリョクデカチトリ", "実力で勝ち取り", "earning victory through undeniable merit", "Condition & Logic"),
    ("jiyuu-honpou ni ikite", "じゆうほんぽうにいきいて", "ジユウホンポウニイキテ", "自由奔放に生きて", "living untamed and fancy-free", "Manner & State"),
    ("joubu ni hodokoshi", "じょうぶにほどこし", "ジョウブニホドコシ", "丈夫に施し", "reinforcing with stout durability", "Appearance & Style"),
    ("joushiki o koete", "じょうしきをこえて", "ジョウシキヲコエテ", "常識を超えて", "surpassing conventional expectations", "Degree & Extent"),
    ("juubun sugiru hodo", "じゅうぶんすぎるほど", "ジュウブンスギルホド", "十分すぎる程", "far more than generously plenty", "Degree & Quantity"),
    ("juudai na ketsudan de", "じゅうだいなけつだんで", "ジュウダイナケツダンデ", "重大な決断で", "with a pivotal momentous decision", "Condition & Logic"),

    # K
    ("kaerimizu ni", "かえりみずに", "カエリミズニ", "顧みずに", "plunging ahead heedless of hazards", "Manner & State"),
    ("kagakuteki na konkyo de", "かがくてきなこんきょで", "カガクテキナコンキョデ", "科学的な根拠で", "grounded in verifiable empirical proof", "Condition & Logic"),
    ("kaigai e tabidachi", "かいがいえたびだち", "カイガイエタビダチ", "海外へ旅立ち", "setting sail across the blue seas", "Travel & Places"),
    ("kakko-tsukezu ni", "かっこうつけずに", "カッコウツケズニ", "恰好つけずに", "without pretension / humble and real", "Social & Communication"),
    ("kanketsu ni matomete", "かんけつにまとめて", "カンケツニマトメテ", "簡潔にまとめて", "summarizing with razor brevity", "Social & Communication"),
    ("kanzen-muketsu o mezashi", "かんぜんむけつをめざし", "カンゼンムケツヲメザシ", "完全無欠を目指し", "aiming for spotless perfection", "Manner & State"),
    ("karei ni mai", "かれいにまい", "カレイニマイ", "華麗に舞い", "dancing with gorgeous balletic grace", "Appearance & Style"),
    ("kekkouteki na seika de", "けっこうなせいかで", "ケッコウナセイカデ", "結構な成果で", "yielding quite a respectable harvest", "Degree & Extent"),
    ("ketahazure na kibo de", "けたはずれなきぼで", "ケタハズレナキボデ", "桁外れな規模で", "on an off-the-charts colossal scale", "Degree & Extent"),
    ("kihon o taisetsu ni", "きほんをたいせつに", "キホンヲタイセツニ", "基本を大切に", "treasuring the fundamentals devoutly", "Manner & State"),
    ("kiken o kaerimizu", "きけんをかえりみず", "キケンヲカエリミズ", "危険を顧みず", "braving mortal peril without flinching", "Safety & Health"),
    ("kin'iro ni kagayaite", "きんいろにかがやいて", "キンイロニカガヤイテ", "金色に輝いて", "gleaming radiant in pure gold", "Appearance & Style"),
    ("kirabi-yaka ni kazari", "きらびやかにかざり", "キラビヤカニカザリ", "絢爛に飾り", "adorned in lavish glittering splendor", "Appearance & Style"),
    ("kodawari o komete", "こだわりをこめて", "コダワリヲコメテ", "こだわりを込めて", "crafted with unyielding artisanal pride", "Manner & State"),
    ("kokyuu o totonoete", "こきゅうをととのえて", "コキュウヲトトノエテ", "呼吸を整えて", "steadying one's breath calmly", "Safety & Health"),
    ("kosei o ikashite", "こせいをいかして", "コセイヲイカシテ", "個性を生かして", "bringing one's individuality to bear", "Personality & Trait"),
    ("koukai naku susumu", "こうかいなくすすむ", "コウカイナクススム", "後悔なく進む", "pressing forward with zero regrets", "Feelings & Mood"),
    ("kousei na me de", "こうせいなめで", "コウセイナメデ", "公正な目で", "with unbiased impartial discernment", "Condition & Logic"),
    ("koutou-mukei ni kikoete", "こうとうむけいにきこえて", "コウトウムケイニキコエテ", "荒唐無稽に聞こえて", "sounding preposterous and absurd", "Social & Communication"),
    ("kyokutan ni iuto", "きょくたんにいうと", "キョクタインニイウト", "極端に言うと", "to state in the most extreme terms", "Social & Communication"),

    # M
    ("ma-atarashii kimochi de", "まあたらしいきもちで", "マアタラシイキモチデ", "真新しい気持ちで", "with a brand-new revitalized spirit", "Feelings & Mood"),
    ("makkura na yoru ni", "まっくらなよるに", "マックラナヨルニ", "真っ暗な夜に", "into the pitch-black midnight shadows", "Places & Spatial"),
    ("mame ni renraku shite", "まめにれんらくして", "マメニレンラクシテ", "忠実に連絡して", "touching base faithfully and often", "Social & Communication"),
    ("manzoku-kan o motte", "まんぞくかんをもって", "マンゾクカンヲモッテ", "満足感を持って", "with deep warm sense of fulfillment", "Feelings & Mood"),
    ("meikaku na mokuhyou de", "めいかくなもくひょうで", "メイカクナモクヒョウデ", "明確な目標で", "aiming at crisp crystal-clear goals", "Condition & Logic"),
    ("meiryou ni hasshou shite", "めいりょうにはっしょうして", "メイリョウニハッショウシテ", "明瞭に発音して", "pronouncing with lucid distinct diction", "Social & Communication"),
    ("mitsudo o takamete", "みつどをたかめて", "ミツドヲタカメテ", "密度を高めて", "raising density to peak concentration", "Degree & Extent"),
    ("mikakunin no mama", "みかくにんのまま", "ミカクニンノママ", "未確認のまま", "leaving unverified as yet", "Condition & Logic"),
    ("mijika ni kanjite", "みじかにかんじて", "ミジカニカンジテ", "身近に感じて", "feeling intimately close at hand", "Feelings & Mood"),
    ("miren o tachikiri", "みれんをたちきり", "ミレンヲタチキリ", "未練を断ち切り", "severing lingering nostalgic ties", "Feelings & Mood"),
    ("mizumizushiku kagayaite", "みずみずしくかがやいて", "ミズミズシクカガヤイテ", "瑞々しく輝いて", "shining dewy fresh and succulent", "Food & Dining"),
    ("muda o habuite", "むだをはぶいて", "ムダヲハブイテ", "無駄を省いて", "trimming every superfluous excess", "Manner & State"),
    ("muga-muchuu de hashiri", "むがむちゅうではしり", "ムガムチュウデハシリ", "無我夢中で走り", "sprinting in totally absorbed trance", "Manner & State"),
    ("mukizu no mama", "むきずのまま", "ムキズノママ", "無傷のまま", "emerging without a solitary scratch", "Safety & Health"),
    ("mumou ni tsuppashiri", "むもうにつっぱしり", "ムモウニツッパシリ", "無謀に突っ走り", "recklessly plunging ahead headlong", "Manner & State"),

    # N
    ("naiteki na koe o kiki", "ないてきなこえをきき", "ナイテキナコエヲキキ", "内的な声を聴き", "listening intently to inner whisper", "Feelings & Mood"),
    ("namagomi o shori shite", "なまごみをしょりして", "ナマゴミヲショリシテ", "生ゴミを処理して", "disposing of kitchen scraps promptly", "Home & Living"),
    ("namayuruku naku", "なまぬるくなく", "ナマヌルクナク", "生温くなく", "neither lukewarm nor complacent", "Degree & Extent"),
    ("nando mo kurikaeshi", "なんどもくりかえし", "ナンドモクリカエシ", "何度も繰り返し", "repeating over and over tirelessly", "Frequency & Habit"),
    ("nikurashii hodo jouzu", "にくらしいほどじょうずで", "ニクラシイホドジョウズデ", "憎らしい程上手で", "infuriatingly brilliant at it", "Degree & Extent"),
    ("nijuu-boushi o tsuke", "にじゅうぼうしをつけ", "ニジュウボウシヲツケ", "二重防止を掛け", "doubling defensive protections", "Safety & Health"),
    ("ninki-mono toshite", "にんきものとして", "ニンキモノトシテ", "人気者として", "standing tall as beloved favorite", "Social & Communication"),
    ("nobinobi to sugoshite", "のびのびとすごして", "ノビノビトスゴシテ", "のびのびと過ごして", "relaxing comfortably free of tension", "Feelings & Mood"),
    ("nonbiri to fune ni nori", "のんびりとふねにのり", "ノンビリトフネニノリ", "のんびりと船に乗り", "floating leisurely aboard the ferry", "Travel & Places"),
    ("nozomi-doori ni", "のぞみどおりに", "ノゾミドオリニ", "望み通りに", "exactly in accordance with desires", "Condition & Logic"),

    # O
    ("odayaka ni nagarete", "おだやかにながれて", "オダヤカニナガレテ", "穏やかに流れて", "flowing gently downstream", "Nature & Climate"),
    ("oishisa o kami-shime", "おいしさをかみしめて", "オイシサヲカミシメテ", "美味しさを噛み締めて", "savoring the delectable flavors", "Food & Dining"),
    ("omoi-kitte tobidashi", "おもいきってとびだし", "オモイキッテトビダシ", "思い切って飛び出し", "plunging forward taking the leap", "Manner & State"),
    ("omoi-tsuki de naku", "おもいつきでなく", "オモイツキデナク", "思い付きでなく", "not merely on transient whim", "Condition & Logic"),
    ("omote-muki wa", "おもてむきは", "オモテムキワ", "表向きは", "on the outward public surface", "Condition & Logic"),
    ("onwa na kikou no moto", "おんわなきこうのもと", "オンワナキコウノモト", "温和な気候の元", "under mild balmy weather", "Nature & Climate"),
    ("orikousan ni mattete", "おりこうさんにまってて", "オリコウサンニマッテテ", "お利口さんに待ってて", "waiting like a good sweet child", "People & Family"),
    ("osoroshii hayasa de", "おそろしいはやさで", "オソロシイハヤサデ", "恐ろしい速さで", "at frightfully dazzling speed", "Speed & Time"),
    ("otome-gokoro de", "おとめごころで", "オトメゴコロデ", "乙女心で", "with romantic maidenhearted innocence", "Feelings & Mood"),
    ("oyako-sorotte", "おやこそろって", "オヤコソロッテ", "親子揃って", "parent and child together in company", "People & Family"),

    # R
    ("raku-raku to koete", "らくらくとこえて", "ラクラクトコエテ", "軽々と越えて", "surpassing hurdles with ease", "Manner & State"),
    ("rakuten-teki ni kangaete", "らくてんてきにかんがえて", "ラクテンテキニカンガエテ", "楽天的に考えて", "looking brightly on sunny side", "Feelings & Mood"),
    ("reikoku na jijitsu toshite", "れいこくなじじつとして", "レイコクナジジツトシテ", "冷酷な事実として", "as cold hard inescapable fact", "Condition & Logic"),
    ("reisei na handan de", "れいせいなはんだんで", "レイセイナハンダンデ", "冷静な判断で", "with clear-eyed dispassionate judgment", "Condition & Logic"),
    ("reisai-kigyou toshite", "れいさいきぎょうとして", "レイサイキギョウトシテ", "零細企業として", "operating as humble micro-business", "Social & Communication"),
    ("rekidai-saikou no", "れきだいさいこうの", "レキダイサイコウノ", "歴代最高の", "achieving all-time highest record", "Degree & Extent"),
    ("renzoku-toukou de", "れんぞくとうこうで", "レンゾクトウコウデ", "連続投稿で", "posting consecutive updates online", "Social & Communication"),
    ("risou o oikakete", "りそうをおいかけて", "リソウヲオイカケテ", "理想を追いかけて", "chasing noble sublime ideals", "Feelings & Mood"),
    ("ritsuzen to shite", "りつぜんとして", "リツゼントシテ", "慄然として", "shivering with sudden spine chill", "Feelings & Mood"),
    ("ryoushin ni haitte", "りょうしんにはじらい", "リョウシンニハジライ", "良心に恥じず", "true to unblemished conscience", "Manner & State"),

    # S
    ("saiai no hito to", "さいあいのひとと", "サイアイノヒトト", "最愛の人と", "together with one's dearest beloved", "People & Family"),
    ("saibou-level de", "さいぼうれべるで", "サイボウレベルデ", "細胞レベルで", "permeating down to cellular level", "Degree & Extent"),
    ("saichuu ni", "さいちゅうに", "サイチュウニ", "最中に", "right smack in the middle of climax", "Speed & Time"),
    ("saikouchou ni tasshite", "さいこうちょうにたっして", "サイコウチョウニタッシテ", "最高潮に達して", "hitting absolute fever pitch", "Degree & Extent"),
    ("saiwai na koto ni", "さいわいなことに", "サイワイナコトニ", "幸いなことに", "most fortunately and happily", "Condition & Logic"),
    ("sakura no shita de", "さくらのしたで", "サクラノシタデ", "桜の下で", "under blossoming pink cherry trees", "Travel & Places"),
    ("sassa to kime", "さっさときめて", "サッサトキメテ", "さっさと決めて", "deciding quickly without shilly-shallying", "Speed & Time"),
    ("sasuga no ude de", "さすがのうでで", "サスガノウデデ", "流石の腕で", "with true craftsman's mastery", "Manner & State"),
    ("satto te o sashidashi", "さっとてをさしだし", "サットテヲサシダシ", "さっと手を差し出し", "swiftly offering helping hand", "Social & Communication"),
    ("sayuu o yoku mite", "さゆうをよくみて", "サユウヲヨクミテ", "左右をよく見て", "checking carefully left and right", "Safety & Health"),
    ("seichou o mitodoke", "せいちょうをみとどけ", "セイチョウヲミトドケ", "成長を見届け", "watching blossom into maturity", "People & Family"),
    ("seigi no tame ni", "せいぎのために", "セイギノタメニ", "正義のために", "fighting valiantly for righteous justice", "Manner & State"),
    ("seiryoku-teki ni katsudou", "せいりょくてきにかつどう", "セイリョクテキニカツドウ", "精力的に活動し", "working with boundlessly tireless zest", "Manner & State"),
    ("shakai no tame ni", "しゃかいのために", "シャカイノタメニ", "社会のために", "contributing for greater civic good", "Social & Communication"),
    ("shinpi no tobira o ake", "しんぴのとびらをあけ", "シンピノトビラヲアケ", "神秘の扉を開け", "unlocking arcane mystical gates", "Travel & Places"),
    ("shinjitsu o motomete", "しんじつをもとめて", "シンジツヲモトメテ", "真実を求めて", "in unwavering quest for truth", "Manner & State"),
    ("shitsukoku tsuikyuu shite", "しつこくついきゅうして", "シツコクツイキュウシテ", "執拗に追及して", "doggedly pursuing the question", "Manner & State"),
    ("shoujiki ni iuto", "しょうじきにいうと", "ショウジキニイウト", "正直に言うと", "to be quite candid and honest", "Social & Communication"),
    ("shunkan-teki ni handan", "しゅんかんてきにはんだん", "シュンカンテキニハンダン", "瞬間的に判断し", "deciding in a split-second reflex", "Speed & Time"),
    ("souzouryoku o hatarakase", "そうぞうりょくをはたらかせ", "ソウゾウリョクヲハタラカセ", "想像力を働かせ", "letting creative imagination soar", "Manner & State"),
    ("subete o sasagete", "すべてをささげて", "スベテヲササゲテ", "全てを捧げて", "dedicating everything unreservedly", "Degree & Extent"),

    # T
    ("taikyuu-sei o takamete", "たいきゅうせいをたかめて", "タイキュウセイヲタカメテ", "耐久性を高めて", "bolstering longevity against wear", "Appearance & Style"),
    ("tekisetsu na jiki ni", "てきせつなじきに", "テキセツナビキニ", "適切な時期に", "at the opportune right moment", "Speed & Time"),
    ("tokubetsu na hi ni", "とくべつなひに", "トクベツナヒニ", "特別な日に", "on an extraordinary celebratory day", "Frequency & Habit"),
    ("tomoni ayumi-nagara", "ともにあゆみながら", "トモニアユミナガラ", "共に歩みながら", "walking side by side together", "Social & Communication"),
    ("touzen no kekka toshite", "とうぜんのけっかとして", "トウゼンノケッカトシテ", "当然の結果として", "as an inevitable, well-earned fruition", "Condition & Logic"),
    ("tsune-ni maemuki ni", "つねにまえむきに", "ツネニマエムキニ", "常に前向きに", "always maintaining sunny optimism", "Feelings & Mood"),

    # U
    ("ude-zuku de", "うでずくで", "ウデズクデ", "腕尽くで", "by muscular sheer force of arms", "Manner & State"),
    ("ugoki-yasuku shite", "うごきやすくして", "ウゴキヤスクシテ", "動きやすくして", "tailoring for nimble agile movement", "Appearance & Style"),
    ("umaku itte", "うまくやって", "ウマクヤッテ", "上手くやって", "handling with finesse and savvy", "Manner & State"),
    ("unmei o uketomete", "うんめいをうけとめて", "ウンメイヲウケトメテ", "運命を受け止めて", "embracing destiny with quiet courage", "Feelings & Mood"),
    ("utagai mo naku", "うたがいもなく", "ウタガイモナク", "疑いもなく", "without a solitary shadow of suspicion", "Condition & Logic"),

    # W
    ("wasure-gatai omoide", "わすれがたいおもいでで", "ワスレガタイオモイデデ", "忘れ難い思い出で", "as an indelibly cherished memory", "Feelings & Mood"),
    ("wazuka na kikkake kara", "わずかなきっかけから", "ワズカナキッカケカラ", "僅かな切っ掛けから", "sparked by a tiny modest chance", "Sequence & Logic"),

    # Y
    ("yousha naku semetate", "ようしゃなくせめたて", "ヨウシャナクセメタテ", "容赦なく攻め立て", "pressing relentlessly without mercy", "Manner & State"),
    ("yuueki na jyouhou toshite", "ゆうえきなじょうほうとして", "ユウエキナジョウホウトシテ", "有益な情報として", "as invaluable, golden intelligence", "Social & Communication"),
    ("yuukan ni tachimukai", "ゆうかんにたちむかい", "ユウカンニタチムカイ", "勇敢に立ち向かい", "courageously facing up to danger", "Manner & State"),

    # Z
    ("zenryoku de kakenuke", "ぜんりょくでかけぬけ", "ゼンリョクデカケヌケ", "全力で駆け抜け", "sprinting through with every ounce of soul", "Speed & Time"),
    ("zutto zutto mae kara", "ずっとずっとまえから", "ズットズットマエカラ", "ずっとずっと前から", "since long, long ago in distant past", "Speed & Time"),
]
