# Discourse, Logic, Modal, and Conversational Japanese Adverbs (JLPT N5-N1)
# (romaji, hiragana, katakana, kanji, meaning, topic)
DATA = [
    # A
    ("aete iunara", "あえていうなら", "アエテイウナラ", "敢えて言うなら", "if I venture to express it so", "Condition & Logic"),
    ("aikawarazu de", "あいかわらずで", "アイカワラズデ", "相変わらずで", "unchanging as ever in substance", "Manner & State"),
    ("aimai ni", "あいまいに", "アイマイニ", "曖昧に", "equivocally / ambiguously", "Manner & State"),
    ("akiraka ni", "あきらかに", "アキラカニ", "明らかに", "clearly / obviously / manifestly", "Condition & Logic"),
    ("aku made mo kantei", "あくまでもかんていで", "アクマデモカンテイデ", "飽くまでも鑑定で", "purely on appraisal grounds", "Condition & Logic"),
    ("amari ni kanashiku", "あまりにかなしく", "アマリニカナシク", "余りに悲しく", "so terribly sorrowfully", "Feelings & Mood"),
    ("anata no tame ni", "あなたのために", "アナタノタメニ", "あなたの為に", "genuinely for your sake", "People & Family"),
    ("ani-hakaranya", "あにはからんや", "アニハカランヤ", "豈図らんや", "who would have dreamed it? / surprisingly", "Condition & Logic"),
    ("ano ne", "あのね", "アノネ", "あのね", "say, listen / you know what? (conversational)", "Social & Communication"),
    ("anou", "あのう", "アノウ", "あのう", "um / well now / excuse me", "Social & Communication"),
    ("anzuru yori mo", "あんずるよりも", "アンズルヨリモ", "案ずるよりも", "far easier than worrying suggests", "Condition & Logic"),
    ("aoge-ba toutoshi", "あおげばとうとし", "アオゲバトウトシ", "仰げば尊し", "revered on high with honor", "Manner & State"),
    ("arakajime koushou", "あらかじめこうしょうして", "アラカジメコウショウシテ", "予め交渉して", "negotiating well in advance", "Social & Communication"),
    ("ari-gatai koto ni", "ありがたいことに", "アリガタイコトニ", "有り難いことに", "most thankfully / gratefully", "Condition & Logic"),
    ("arima-sen keredo", "ありませんけれど", "アリマセンケレド", "ありませんけれど", "though there is none however", "Sequence & Logic"),
    ("aru-imi de", "あるいみで", "アルイミデ", "ある意味で", "in a certain sense / from one angle", "Condition & Logic"),
    ("aruiwa", "あるいは", "アルイワ", "或いは", "or perhaps / alternately", "Sequence & Logic"),
    ("asase de oyogu", "あさせでおよぐ", "アサセデオヨグ", "浅瀬で泳ぎ", "swimming safely in shallow surf", "Places & Spatial"),
    ("atarimae no gotoku", "あたりまえのごとく", "アタリマエノゴトク", "当たり前の如く", "as if it were the most natural truth", "Condition & Logic"),
    ("ayamarazu ni", "あやまらずに", "アヤマラズニ", "誤らずに", "without a single mistaken slip", "Manner & State"),
    ("azayaka ni mo", "あざやかにも", "アザヤカニモ", "鮮やかにも", "with such breathtaking flair", "Degree & Extent"),

    # B
    ("baka-baka-shiku mo", "ばかばかしくも", "バカバカシクモ", "馬鹿馬鹿しくも", "ridiculously yet charmingly", "Manner & State"),
    ("bakudai na hiou de", "ばくだいなひようで", "バクダイナヒヨウデ", "莫大な費用で", "at astronomical colossal expense", "Degree & Quantity"),
    ("ban-ga-ichi ni mo", "ばんがいちにも", "バンガイチニモ", "万が一にも", "by any million-to-one chance", "Condition & Logic"),
    ("batsu-gun no kire de", "ばつぐんのきれで", "バツグンノキレデ", "抜群の切れで", "with razor-sharp pristine cut", "Manner & State"),
    ("betsu-dankai de", "べつだんかいで", "ベツダンカイデ", "別段階で", "at a discrete separate phase", "Sequence & Logic"),
    ("betsu-dan", "べつだん", "ベツダン", "別段", "particularly / especially so", "Degree & Extent"),
    ("bonyari to nagamete", "ぼんやりとながめて", "ボンヤリトナガメテ", "ぼんやりと眺めて", "gazing vacantly at horizon", "Manner & State"),
    ("bunrui-jou", "ぶんるいじょう", "ブンルイジョウ", "分類上", "categorically / taxonomy-wise", "Condition & Logic"),
    ("byoudou-shugi de", "びょうどうしゅぎで", "ビョウドウシュギデ", "平等主義で", "on strict egalitarian principles", "Condition & Logic"),

    # C
    ("chanto rikai shite", "ちゃんとりかいして", "チャントリカイシテ", "きちんと理解して", "with crisp thorough comprehension", "Manner & State"),
    ("chiisa na koe de", "ちいさなこえで", "チイサナコエデ", "小さな声で", "in a gentle hushed whisper", "Social & Communication"),
    ("chika-jika mata", "ちかぢかまた", "チカヂカマタ", "近々また", "very soon once again", "Frequency & Habit"),
    ("chikara o awasete", "ちからをあわせて", "チカラヲアワセテ", "力を合わせて", "pooling our collective strengths", "Manner & State"),
    ("chitsujo aru katachi de", "ちつじょあるかたちで", "チツジョアルカタチデ", "秩序ある形で", "in disciplined proper arrangement", "Manner & State"),
    ("chotto dake", "ちょっとだけ", "チョットダケ", "一寸だけ", "just a tiny smidgen", "Degree & Quantity"),
    ("chotto matte", "ちょっとまって", "チョットマッテ", "ちょっと待って", "hold on just a moment!", "Social & Communication"),
    ("chousei-go ni", "ちょうせいごに", "チョウセイゴニ", "調整後に", "following fine calibration", "Sequence & Logic"),
    ("chuuou ni", "ちゅうおうに", "チュウオウニ", "中央に", "smack-dab in the center", "Places & Spatial"),

    # D
    ("daikibo ni tenkai shite", "だいきぼにてんかいして", "ダイキボニテンカイシテ", "大規模に展開して", "rolling out on massive scale", "Degree & Extent"),
    ("daitai ni oite", "だいたいにおいて", "ダイタイニオイテ", "大体において", "broadly speaking in general", "Condition & Logic"),
    ("daitan futeki ni", "だいたんふてきに", "ダイタンフテキニ", "大胆不敵に", "audaciously and fearlessly", "Manner & State"),
    ("dakara koso", "だからこそ", "ダカラコソ", "だからこそ", "that is precisely why / for this reason", "Sequence & Logic"),
    ("danpen-teki ni", "だんぺんてきに", "ダンペンテキニ", "断片的に", "in scattered fragments", "Manner & State"),
    ("daredemo wakaru you ni", "だれでもわかるように", "ダレデモワカルヨウニ", "誰でも分かるように", "so that anyone can easily grasp", "Social & Communication"),
    ("douse", "どうせ", "ドウセ", "どうせ", "anyway / in any case / after all", "Condition & Logic"),
    ("dou-yara", "どうやら", "ドウヤラ", "どうやら", "it seems that / apparently", "Condition & Logic"),
    ("doushite koushite", "どうしてこうして", "ドウシテコウシテ", "どうしてこうして", "all in all / somehow or other", "Condition & Logic"),

    # E
    ("eikyou-ryoku o motte", "えいきょうりょくをもって", "エイキョウリョクヲモッテ", "影響力を持って", "wielding substantial influence", "Degree & Extent"),
    ("enman-kaiketsu de", "えんまんかいけつで", "エンマンカイケツデ", "円満解決で", "resolving through sweet accord", "Manner & State"),
    ("en-shita de", "えんのしたで", "エンノシタデ", "縁の下で", "silently supporting backstage", "People & Family"),
    ("etto", "えっと", "エット", "えっと", "let's see now... / well...", "Social & Communication"),

    # F
    ("fuan-ge ni", "ふあんげに", "フアンゲニ", "不安げに", "with uneasy anxious eyes", "Feelings & Mood"),
    ("fukami o motte", "ふかみをもって", "フカミヲモッテ", "深みを持って", "imbued with layered depth", "Degree & Extent"),
    ("fukisoku ni", "ふきそくに", "フキソクニ", "不規則に", "irregularly / spasmodically", "Frequency & Habit"),
    ("fukouhei ni mo", "ふこうへいにも", "フコウヘイニモ", "不公平にも", "with gross unfairness", "Manner & State"),
    ("fushizen ni", "ふしぜんに", "フシゼンニ", "不自然に", "artificially / awkwardly unnatural", "Manner & State"),
    ("futo kangaete", "ふとかんがえて", "フトカンガエテ", "ふと考えて", "reflecting momentarily upon it", "Manner & State"),
    ("futo shita hyoushi ni", "ふとしたひょうしに", "フトシタヒョウシニ", "ふとした拍子に", "by a sudden chance impulse", "Speed & Time"),
    ("futsuu dewa naku", "ふつうではなく", "フツウデワナク", "普通ではなく", "far out of the ordinary", "Degree & Extent"),

    # G
    ("gai-to", "がんと", "ガント", "厳然と", "sternly standing unquestioned", "Condition & Logic"),
    ("gakki-chuu ni", "がっきちゅうに", "ガッキチュウニ", "学期中に", "during the academic school semester", "Speed & Time"),
    ("gan-gan susumu", "がんがんすすむ", "ガンガンススム", "ガンガン進む", "charging ahead aggressively", "Speed & Time"),
    ("ganko na made ni", "がんこなまでに", "ガンコナマデニ", "頑固なまでに", "to an uncompromisingly stubborn degree", "Degree & Extent"),
    ("gappon de", "がっぽんで", "ガッポンデ", "合本で", "compiled as an omnibus edition", "Sequence & Logic"),
    ("geijutsu-hin no gotoku", "げいじゅつひんのごとく", "ゲイジュツヒンノゴトク", "芸術品の如く", "like a pristine work of fine art", "Appearance & Style"),
    ("gekirei o komete", "げきれいをこめて", "ゲキレイヲコメテ", "激励を込めて", "packed with heartfelt encouragement", "Social & Communication"),
    ("genjitsu-teki ni", "げんじつてきに", "ゲンジツテキニ", "現実的に", "realistically / in practical terms", "Condition & Logic"),
    ("genkaku na kanri de", "げんかくなかんりで", "ゲンカクナカンリデ", "厳格な管理で", "under strict tight governance", "Manner & State"),
    ("giri-giri no tokoro de", "ぎりぎりのところで", "ギリギリノトコロデ", "ギリギリのところで", "at the razor-thin cliff edge", "Speed & Time"),
    ("gishi-gishi to", "ぎしぎしと", "ギシギシト", "軋々と", "creaking under heavy load", "Onomatopoeia & Mimetic"),
    ("gomen-kudasai to", "ごめんくださいと", "ゴメンクダサイト", "ごめんくださいと", "calling out 'excuse me!'", "Social & Communication"),
    ("gouin na shuuhou de", "ごういんなしゅほうで", "ゴウインナシュホウデ", "強引な手法で", "via high-handed aggressive means", "Manner & State"),
    ("gunshu-chuu de", "ぐんしゅうちゅうで", "グンシュウチュウデ", "群衆の中で", "amid the dense bustling throng", "Places & Spatial"),

    # H
    ("hachikire-sou ni", "はちきれそうに", "ハチキレソウニ", "はち切れそうに", "brimming ready to explode", "Degree & Extent"),
    ("hageshiku mo", "はげしくも", "ハゲシクモ", "激しくも", "fiercely yet poetically", "Manner & State"),
    ("haigo kara", "はいごから", "ハイゴカラ", "背後から", "from behind from the shadows", "Places & Spatial"),
    ("hajime kara owari made", "はじめからおわりまで", "ハジメカラオワリマデ", "初めから終わりまで", "from start to finish comprehensively", "Sequence & Logic"),
    ("hakken-sha no me de", "はっけんしゃのめで", "ハッケンシャノメデ", "発見者の目で", "through eyes of the first discoverer", "Manner & State"),
    ("han-kyou-ran de", "はんきょうらんで", "ハンキョウランデ", "半狂乱で", "in a hysterical frantic state", "Feelings & Mood"),
    ("han-taiteki ni", "はんたいてきに", "ハンタイテキニ", "反対に", "oppositely / in stark reverse", "Sequence & Logic"),
    ("haruka kanata ni", "はるかかなたに", "ハルカカナタニ", "遥か彼方に", "far off in the distant horizon", "Places & Spatial"),
    ("hasu-kai ni", "はすかいに", "ハスカイニ", "筋向いに", "diagonally across the street", "Places & Spatial"),
    ("heiki na kao de", "へいきなかおで", "ヘイキナカオデ", "平気な顔で", "with a deadpan unflinching poker face", "Manner & State"),
    ("heikou shite susumu", "へいこうしてすすむ", "ヘイコウシテススム", "並行して進む", "progressing synchronously", "Sequence & Logic"),
    ("heisateki na ba de", "へいさてきなばで", "ヘイサテキナバデ", "閉鎖的な場で", "in an insular, exclusive space", "Places & Spatial"),
    ("hidoku mo", "ひどくも", "ヒドクモ", "酷くも", "terribly / so cruelly", "Degree & Extent"),
    ("hiken toshite", "ひけんとして", "ヒケントシテ", "卑見として", "as my humble private submission", "Social & Communication"),
    ("hikkuri-kaesu you ni", "ひっくりかえすように", "ヒックリカエスヨウニ", "ひっくり返すように", "radically upending the status quo", "Manner & State"),
    ("hinekurete", "ひねくれて", "ヒネクレテ", "拗ねて", "perversely / in a contrary mood", "Personality & Trait"),
    ("hisho-chi de", "ひしょちで", "ヒショチデ", "避暑地で", "at a cool summer mountain retreat", "Travel & Places"),
    ("hitasura massugu ni", "ひたすらまっすぐに", "ヒタスラマッスグニ", "一筋に真っ直ぐに", "earnestly in a straight line", "Manner & State"),
    ("hito-kado no", "ひとかどの", "ヒトカドノ", "一角の", "respectably / of decent caliber", "Degree & Extent"),
    ("hito-kuchi de", "ひとくちで", "ヒトクチデ", "一口で", "in a single mouthwatering bite", "Food & Dining"),
    ("hito-nami ni", "ひとなみに", "ヒトナミニ", "人並みに", "at an average decent standard", "Degree & Extent"),
    ("hitori-hitori", "ひとりひとり", "ヒトリヒトリ", "一人ひとり", "each person individually / one by one", "People & Family"),
    ("hodo-yoku", "ほどよく", "ホドヨク", "程よく", "agreeably / pleasantly balanced", "Degree & Extent"),
    ("hokorashige ni", "ほこらしげに", "ホコラシゲニ", "誇らしげに", "proudly with head held high", "Feelings & Mood"),
    ("hontou no tokoro", "ほんとうのところ", "ホントウノトコロ", "本当のところ", "truth be told / deep down", "Condition & Logic"),
    ("hon-yaku de", "ほんやくで", "ホンヤクデ", "翻訳で", "through translation / in rendered words", "Social & Communication"),
    ("hyoumen-jyou", "ひょうめんじょう", "ヒョウメンジョウ", "表面上", "on the surface / ostensibly", "Condition & Logic"),

    # I
    ("ichi-ka bachi-ka", "いちかばちか", "イチカバチカ", "一か八か", "sink or swim / taking big gamble", "Condition & Logic"),
    ("ichi-mou dajin ni", "いちもうだじんに", "イチモウダジンニ", "一網打尽に", "rounding up all in a single net", "Manner & State"),
    ("ichiren no nagare de", "いちれんのながれで", "イチレンノナガレデ", "一連の流れで", "in an unbroken stream of steps", "Sequence & Logic"),
    ("ihen naku", "いへんなく", "イヘンナク", "異変なく", "without untoward occurrence", "Condition & Logic"),
    ("ii-kaereba", "いいかえれば", "イイカエレバ", "言い換えれば", "in other words / put another way", "Sequence & Logic"),
    ("ikani mo", "いかにも", "イカニモ", "如何にも", "truly / genuinely / quite so", "Condition & Logic"),
    ("ikutsu mo no", "いくつもの", "イクツモノ", "幾つもの", "countless numerous occasions", "Degree & Quantity"),
    ("ima no uchi ni", "いまのうちに", "イマノウチニ", "今のうちに", "while we still have this chance", "Speed & Time"),
    ("inaba-gari ni", "いなばがり", "イナバガリ", "否が応でも", "whether ready or not", "Condition & Logic"),
    ("ippan-ron toshite", "いっぱんろんとして", "イッパンロントシテ", "一般論として", "as a broad general proposition", "Condition & Logic"),
    ("isogi de", "いそぎで", "イソギデ", "急ぎで", "in a frantic urgent hurry", "Speed & Time"),
    ("isshou no omoide de", "いっしょうのおもいでで", "イッショウノオモイデデ", "一生の思い出で", "as a lifelong cherished memory", "Feelings & Mood"),
    ("itsu no jidai mo", "いつのじだいも", "イツノジダイモ", "いつの時代も", "in every era across all generations", "Frequency & Habit"),
    ("iya-ou naku", "いやおうなく", "イヤオウナク", "否応なく", "inevitably / willy-nilly", "Condition & Logic"),

    # J
    ("jiba-san de", "じばさんで", "ジバサンデ", "地場産で", "sourced from local regional harvest", "Food & Dining"),
    ("jigen o koete", "じげんをこえて", "ジゲンヲコエテ", "次元を超えて", "transcending boundaries", "Degree & Extent"),
    ("jijitsujou", "じじつじょう", "ジジツジョウ", "事実上", "de facto / effectively in practice", "Condition & Logic"),
    ("jikkan toshite", "じっかんとして", "ジッカントシテ", "実感として", "as a deeply felt personal reality", "Feelings & Mood"),
    ("jiko-sekinin de", "じこせきにんで", "ジコセキニンデ", "自己責任で", "at one's own sole risk and accord", "Condition & Logic"),
    ("jissen-teki ni", "じっせんてきに", "ジッセンテキニ", "実践的に", "in practical hands-on application", "Manner & State"),
    ("jitsu wa", "じつは", "ジツワ", "実は", "as a matter of fact / actually", "Condition & Logic"),
    ("jiyuu-kizama ni", "じゆうきままに", "ジユウキママニ", "自由気ままに", "fancy-free / following whim", "Manner & State"),
    ("juunbun ni kangaete", "じゅうぶんにかんがえて", "ジュウブンニカンガエテ", "熟慮を重ねて", "having considered with maturity", "Manner & State"),

    # K
    ("kaette", "かえって", "カエッテ", "却って", "on the contrary / paradoxically worse", "Sequence & Logic"),
    ("kagiri aru naka de", "かぎりあるなかで", "カギリアルナカデ", "限りある中で", "within finite precious constraints", "Degree & Quantity"),
    ("kanarazuya", "かならずや", "カナラズヤ", "必ずや", "most assuredly / without shadow of doubt", "Condition & Logic"),
    ("kanzen-nenchou de", "かんぜんねんしょうで", "カンゼンネンショウデ", "完全燃焼で", "burning with total fulfilled energy", "Degree & Extent"),
    ("kekka toshite", "けっかとして", "ケッカトシテ", "結果として", "as an ultimate consequence", "Sequence & Logic"),
    ("kesshite yuruma-zu", "けっしてゆるまず", "ケッシテユルマズ", "決して弛まず", "never letting one's guard slip", "Manner & State"),
    ("kikaku-gai de", "きかくがいで", "キカクガイデ", "規格外で", "off the spectrum / unconventional", "Degree & Extent"),
    ("kireigoto naku", "きれいごとなしに", "キレイゴトナシニ", "綺麗事なしに", "without sugarcoated platitudes", "Social & Communication"),
    ("kitto", "きっと", "キット", "屹度", "surely / definitely / without doubt", "Condition & Logic"),
    ("koukai-saki ni tatazu", "こうかいさきにたたず", "コウカイサキニタタズ", "後悔先に立たず", "useless crying over spilled milk", "Condition & Logic"),
    ("kore kara", "これから", "コレカラ", "これから", "from now on / into future", "Speed & Time"),
    ("koushou-jyou", "こうしょうじょう", "コウショウジョウ", "交渉上", "under diplomatic negotiation", "Social & Communication"),
    ("kudaketa hanashi de", "くだけたはなしで", "クダケタハナシデ", "下けた話で", "in informal casual colloquial talk", "Social & Communication"),

    # M
    ("man-ga-ichi", "まんがいち", "マンガイチ", "万一", "if by any rare chance / should worst occur", "Condition & Logic"),
    ("masani", "まさに", "マサニ", "正に", "truly / exactly / right at the peak", "Degree & Extent"),
    ("mattaku motte doukan", "まったくもってどうかん", "マッタクモッテドウカン", "全く以て同感で", "in complete and total consensus", "Social & Communication"),
    ("metta ni", "めったに", "メッタニ", "滅多に", "rarely / seldom (with negative)", "Frequency & Habit"),
    ("mizu-kara susunde", "みずからすすんで", "ミズカラススンデ", "自ら進んで", "stepping forward proactively", "Manner & State"),
    ("moshikashitara", "もしかしたら", "モシカシタラ", "若しかしたら", "perhaps / possibly / perchance", "Condition & Logic"),
    ("moshi ya", "もしや", "モシヤ", "若しや", "could it possibly be that...?", "Condition & Logic"),
    ("moushi-bun naku", "もうしぶんなく", "モウシブンナク", "申し分なく", "without room for criticism / splendidly", "Degree & Extent"),
    ("mukiryoku ni", "むきりょくに", "ムキリョクニ", "無気力に", "apathetically / listlessly", "Feelings & Mood"),
    ("muri-shite", "むりして", "ムリシテ", "無理して", "pushing oneself beyond limits", "Manner & State"),

    # N - Z
    ("nani-yori mo", "なによりも", "ナニヨリモ", "何よりも", "above all else / more than anything", "Degree & Extent"),
    ("nando to naku", "なんどとなく", "ナンドトナク", "何度となく", "time and time again countless times", "Frequency & Habit"),
    ("nanto", "なんと", "ナント", "何と", "what a surprise! / how very!", "Degree & Extent"),
    ("nanto naku", "なんとなく", "ナントナク", "何となく", "somehow / without clear reason", "Feelings & Mood"),
    ("naze ka", "なぜか", "ナゼカ", "何故か", "for some inexplicable reason", "Condition & Logic"),
    ("neba-neba to", "ねばねばと", "ネバネバト", "ねばねばと", "gooey stringy consistency", "Food & Dining"),
    ("nomarazu ni", "のまれずに", "ノマレズニ", "呑まれずに", "without being swallowed by nerves", "Manner & State"),
    ("oyoso", "およそ", "オヨソ", "凡そ", "roughly / approximately / about", "Degree & Quantity"),
    ("roku ni", "ろくに", "ロクニ", "碌に", "barely / properly (with negative)", "Degree & Extent"),
    ("sarani", "さらに", "サラニ", "更に", "furthermore / even more / in addition", "Degree & Extent"),
    ("sassa to", "さっさと", "サッサト", "さっさと", "promptly / briskly without dawdling", "Speed & Time"),
    ("sasuga ni", "さすがに", "サスガニ", "流石に", "as expected / naturally even so", "Condition & Logic"),
    ("sayuu-sarezu", "さゆうされず", "サユウサレズ", "左右されず", "unswayed by external breezes", "Manner & State"),
    ("seizei", "せいぜい", "セイゼイ", "精々", "at the very utmost / to the best extent", "Degree & Quantity"),
    ("sekokkaku", "せっかく", "セッカク", "折角", "with much effort / specially taken pains", "Condition & Logic"),
    ("shikashi", "しかし", "シカシ", "然し", "however / but nevertheless", "Sequence & Logic"),
    ("shousai ni", "しょうさいに", "ショウサイニ", "詳細に", "in granular forensic detail", "Manner & State"),
    ("sore demo", "それでも", "ソレデモ", "それでも", "even so / nonetheless / still", "Sequence & Logic"),
    ("sore nara", "それなら", "ソレナラ", "それなら", "if that is the case / then", "Sequence & Logic"),
    ("sou kangaeru to", "そうかんがえると", "ソウカンガエルト", "そう考えると", "looking at it through that lens", "Condition & Logic"),
    ("sou shite", "そうして", "ソウシテ", "そうして", "and then / having done so", "Sequence & Logic"),
    ("subete o komete", "すべてをこめて", "スベテヲコメテ", "全てを込めて", "pouring every fiber of one's being", "Degree & Extent"),
    ("taitei", "たいてい", "タイテイ", "大抵", "mostly / ordinarily / usually", "Frequency & Habit"),
    ("tatoe donna ni", "たとえどんなに", "タトエドンナニ", "例えどんなに", "no matter how very challenging", "Condition & Logic"),
    ("tatoeba", "たとえば", "タトエバ", "例えば", "for example / instance", "Sequence & Logic"),
    ("tetsuzuki-jou", "てつづきじょう", "テツヅキジョウ", "手続き上", "procedurally / on paperwork side", "Condition & Logic"),
    ("tokoro de", "ところで", "トコロデ", "所で", "by the way / incidentally", "Sequence & Logic"),
    ("tonikaku", "とにかく", "トニカク", "兎に角", "at any rate / anyway / in any event", "Condition & Logic"),
    ("tsumari", "つまり", "ツマリ", "詰まり", "in short / namely / that is to say", "Sequence & Logic"),
    ("wazawaza", "わざわざ", "ワザワザ", "態々", "going out of one's way expressly", "Manner & State"),
    ("yahari", "やはり", "ヤハリ", "矢張り", "as anticipated / after all", "Condition & Logic"),
    ("yappari", "やっぱり", "ヤッパリ", "やっぱり", "as I thought! / after all", "Condition & Logic"),
    ("yokoso", "ようこそ", "ヨウコソ", "ようこそ", "warmly welcome!", "Social & Communication"),
    ("yousuru ni", "ようするに", "ヨウスルニ", "要するに", "in essence / to summarize briefly", "Sequence & Logic"),
    ("zehi", "ぜひ", "ゼヒ", "是非", "by all means / heartily", "Condition & Logic"),
    ("zenpan-teki ni", "ぜんぱんてきに", "ゼンパンテキニ", "全般的に", "across the entire board / generally", "Condition & Logic"),
]
