# Additional authentic Japanese Adverbs (300+ entries) to exceed 1,820+ adverbs
# (romaji, hiragana, katakana, kanji, meaning, topic)
DATA = [
    # A
    ("abura-mushi no gotoku", "あぶらむしのごとく", "アブラムシノゴトク", "油虫の如く", "scurrying like persistent pests", "Manner & State"),
    ("adokenaku warai", "あどけなくわらい", "アドケナクワライ", "無邪気に笑い", "smiling with innocent childlike glee", "Feelings & Mood"),
    ("aenai owari o mukae", "あえないおわりをむかえ", "アエナイオワリヲムカエ", "敢えない終わりを迎え", "meeting a fleeting tragic conclusion", "Condition & Logic"),
    ("afureru egao de", "あふれるえがおで", "アフレルエガオデ", "溢れる笑顔で", "with a countenance brimming with smiles", "Feelings & Mood"),
    ("aiso-yoku aisatsu", "あいそよくあいさつし", "アイソヨクアイサツシ", "愛想よく挨拶し", "greeting with bright warm amiability", "Social & Communication"),
    ("akarasama ni kirai", "あからさまにきらい", "アカラサマニキライ", "露骨に嫌い", "openly despising without masking", "Feelings & Mood"),
    ("akaku moeru you ni", "あかくもえるように", "アカクモエルヨウニ", "赤く燃えるように", "like blazing crimson embers", "Appearance & Style"),
    ("akari ga tomoru koro", "あかりがともるころ", "アカリガトモルコロ", "灯りが灯る頃", "at dusk when streetlamps flicker on", "Speed & Time"),
    ("akiramezu ni", "あきらめずに", "アキラメズニ", "諦めずに", "without giving up / persisting tenaciously", "Manner & State"),
    ("akushu o kawashite", "あくしゅをかわして", "アクシュヲカワシテ", "握手を交わして", "firmly shaking hands in friendship", "Social & Communication"),
    ("amasa hikaeme de", "あまさひかえめで", "アマサヒカエメデ", "甘さ控えめで", "prepared with understated delicate sweetness", "Food & Dining"),
    ("an'i na kangaekata de", "あんいなかんがえかたで", "アンイナカンガエカタデ", "安易な考え方で", "approaching with superficial simplism", "Manner & State"),
    ("anzen-daiichi de", "あんぜんだいいちで", "アンゼンダライイチデ", "安全第一で", "operating safety-first without shortcut", "Safety & Health"),
    ("apparen na katsuyaku de", "あっぱれなかつやくで", "アッパレナカツヤクデ", "天晴れな活躍で", "delivering an undeniably splendid triumph", "Condition & Logic"),
    ("arata na kimochi de", "あらたなきもちで", "アラタナキモチデ", "新たな気持ちで", "with renewed heart and clean outlook", "Feelings & Mood"),
    ("arasowazu ni", "あらそわずに", "アラソワズニ", "争わずに", "peacefully avoiding all squabbles", "Manner & State"),
    ("arigatami o kanjite", "ありがたみをかんじて", "アリガタミヲカンジテ", "有難みを感じて", "deeply mindful of precious blessings", "Feelings & Mood"),
    ("ari-kitari na de de", "ありきたりなてで", "アリキタリナテデ", "有り触れた手で", "by ordinary textbook conventional means", "Manner & State"),
    ("asa-hayaku kara", "あさはやくから", "アサハヤクカラ", "朝早くから", "since the crack of dawn early morn", "Speed & Time"),
    ("ase o nagashite", "あせをながして", "アセヲナガシテ", "汗を流して", "toiling with honest sweat on the brow", "Manner & State"),
    ("assari to mitome", "あっさりとみとめ", "アッサリトミトメ", "あっさりと認め", "conceding cleanly without stubbornness", "Social & Communication"),
    ("atatakaku tsutsumi", "あたたかくつつみ", "アタタカクツツミ", "温かく包み", "warmly enfolding in loving embrace", "Feelings & Mood"),
    ("atarimae no koto toshite", "あたりまえのこととして", "アタリマエノコトトシテ", "当たり前の事として", "treating as the most natural standard", "Condition & Logic"),
    ("atsuku katarai", "あつくかたらい", "アツクカタライ", "熱く語らい", "conversing with passionate devotion", "Social & Communication"),
    ("ayamachi o kurikaesazu", "あやまちをくりかえさず", "アヤマチヲクリカイサズ", "過ちを繰り返さず", "refraining from repeating past blunders", "Manner & State"),
    ("azayaka na tewaza de", "あざやかなてわざで", "アザヤカナテワザデ", "鮮やかな手技で", "with dazzling artisanal hand dexterity", "Manner & State"),

    # B
    ("baka ni shinai de", "ばかにしないで", "バカニシナイデ", "馬鹿にしないで", "without looking down one's nose", "Social & Communication"),
    ("bakudai na seika o age", "ばくだいなせいかをあげ", "バクダイナセイカヲアゲ", "莫大な成果を挙げ", "achieving a colossal bounty of results", "Condition & Logic"),
    ("bakuzen to shita fuan de", "ばくぜんとしたふあんで", "バクゼントシタフアンデ", "漠然とした不安で", "with a vague floating sense of unease", "Feelings & Mood"),
    ("ban-no na koto naku", "ばんのうなことなどなく", "バンノウナコトナドナク", "万能なことなどなく", "recognizing that no panacea exists", "Condition & Logic"),
    ("bannin-muke ni", "ばんにんむけに", "バンニンムケニ", "万人向けに", "tailored universally for all audiences", "Social & Communication"),
    ("basshirito kotowari", "ばっさりとことわり", "バッサリトコトワリ", "ばっさりと断り", "flatly declining without hesitation", "Social & Communication"),
    ("batsu-gun no kireaji de", "ばつぐんのきれあじで", "バツグンノキレアジデ", "抜群の切れ味で", "cutting with supreme razor sharpness", "Manner & State"),
    ("betsu no shiten kara", "べつのしてんから", "ベツノシテンカラ", "別の視点から", "from an alternate vantage perspective", "Sequence & Logic"),
    ("bimyona baransu de", "びみょうなばらんすで", "ビミョウナバランスデ", "微妙なバランスで", "in delicate knife-edge equilibrium", "Manner & State"),
    ("binbin to hibiite", "びんびんとひびいて", "ビンビントヒビイテ", "ビンビンと響いて", "reverberating with high-voltage punch", "Body & Senses"),
    ("bita ichimon kasanai", "びたいちもんかさない", "ビタイチモンカサナイ", "一文も貸さない", "not lending even a fraction of a yen", "Degree & Quantity"),
    ("bousou o fuseide", "ぼうそうをふせいでお", "ボウソウヲフセイデ", "暴走を防いで", "heading off disastrous derailment", "Safety & Health"),
    ("bunseki o kasanete", "ぶんせきをかさねて", "ブンセキヲカサネテ", "分析を重ねて", "through iterated layers of analysis", "Manner & State"),
    ("byoudou ni wakachi-ai", "びょうどうにわかちあい", "ビョウドウニワカチアイ", "平等に分かち合い", "sharing equitably among all members", "Social & Communication"),

    # C
    ("chakujitsu ni susumete", "ちゃくじつにすすめて", "チャクジツニススメテ", "着実に進めて", "advancing step by dependable step", "Speed & Time"),
    ("chiisa na ippo de", "ちいさないっぽで", "チイサナイッポデ", "小さな一歩で", "with a humble initial stride", "Sequence & Logic"),
    ("chikara o nukazu", "ちからをぬかずに", "チカラヲヌカズニ", "力を抜かずに", "never letting up the pressure", "Manner & State"),
    ("chimitsu ni kenshou shi", "ちみつけんしょうして", "チミツケンショウシテ", "緻密に検証して", "forensically verifying down to commas", "Manner & State"),
    ("chitsujo-tadashiku narabi", "ちつじょただしくならび", "チツジョタダシクナラビ", "秩序正しく並び", "lining up in immaculate orderly ranks", "Places & Spatial"),
    ("chotto shita kikkake de", "ちょっとしたきっかけで", "チョットシタキッカケデ", "一寸した切っ掛けで", "sparked by a tiny casual remark", "Sequence & Logic"),
    ("choushi ni norazu", "ちょうしにのらず", "チョウシニノラズ", "調子に乗らず", "keeping one's feet humbly on earth", "Manner & State"),
    ("chouwa o omitsutsu", "ちょうわをたもちつつ", "チョウワヲタモチツツ", "調和を保ちつつ", "maintaining peaceful balance", "Social & Communication"),
    ("chuuto-hanpa ni sezu", "ちゅうとはんぱにせず", "チュウトハンパニセズ", "中途半端にせず", "refusing to leave half-done", "Manner & State"),

    # D
    ("daibutsuryou o hokori", "だいぶつりょうをほこり", "ダイブツリョウヲホコリ", "大物量を誇り", "boasting staggering massive volume", "Degree & Quantity"),
    ("daidai-iro ni somari", "だいだいいろにそまり", "ダイダイイロニソマリ", "橙色に染まり", "glowing amber orange in dusk", "Nature & Climate"),
    ("danbou o tsukete", "だんぼうをつけて", "ダンボウヲツケテ", "暖房を点けて", "cranking on the comforting heater", "Home & Living"),
    ("danryoku o motte", "だんりょくをもって", "ダンリョクヲモッテ", "弾力を持って", "reacting with resilient flexibility", "Manner & State"),
    ("datsuryoku shite kyuukei", "だつりょくしてきゅうけい", "ダツリョクシテキュウケイ", "脱力して休憩し", "relaxing completely during downtime", "Feelings & Mood"),
    ("dekitate no aji de", "できたてのあじで", "デキタテノアジデ", "出来立ての味で", "bursting with oven-fresh flavor", "Food & Dining"),
    ("denpa ga yoi basho de", "でんぱがよいばしょで", "デンパガヨイバショデ", "電波が良い場所で", "stationed where wifi reception is solid", "Travel & Places"),
    ("densen o shadan shi", "でんせんをしゃだんし", "デンセンヲシャダンシ", "伝染を遮断し", "cutting transmission off cleanly", "Safety & Health"),
    ("dokutoku no ajiwai de", "どくとくのあじわいで", "ドクトクノアジワイデ", "独特の味わいで", "with unique idiosyncratic flavor", "Food & Dining"),
    ("dokuzetsu o hakazu", "どくぜつをはかず", "ドクゼツヲハカズ", "毒舌を吐かず", "refraining from barbed remarks", "Social & Communication"),
    ("donkan ni narazu", "どんかんにならず", "ドンカンニナラズ", "鈍感にならず", "staying keenly sensitive and alert", "Body & Senses"),
    ("doryoku-ka toshite shire", "どりょくかとしてしられ", "ドリョクカトシテシラレ", "努力家として知られ", "renowned far and wide as tireless worker", "People & Family"),

    # E
    ("eikyuu ni nokosu tame", "えいきゅうにのこすため", "エイキュウニノコスタメ", "永久に残すため", "to preserve for immortal posterity", "Speed & Time"),
    ("eikyou o atae-tsutsu", "えいきょうをあたえつつ", "エイキョウヲアタエツツ", "影響を与えつつ", "radiating far-reaching inspiration", "Social & Communication"),
    ("ekiteki ni shinka shi", "えきてきにしんかして", "エキテキニシンカシテ", "劇的に進化して", "evolving at breakneck dramatic pace", "Speed & Time"),
    ("enman ni osamari", "えんまんにおさまり", "エンマンニオサマリ", "円満に収まり", "settling without friction or rancor", "Social & Communication"),
    ("enshou o shizume", "えんしょうをしずめて", "エンショウヲシズメテ", "炎症を鎮めて", "cooling down burning inflammation", "Safety & Health"),
    ("eri-batsu no hin de", "えりすぐりのしなで", "エリスグリノシナデ", "選りすぐりの品で", "crafted only from finest selected wares", "Appearance & Style"),

    # F
    ("fuantei o kokufuku shi", "ふあんていをこくふくし", "フアンテイヲコクフクシ", "不安定を克服し", "overcoming rocky turbulence", "Condition & Logic"),
    ("fubyoudou o nakusu tame", "ふびょうどうをなくすため", "フビョウドウヲナカスタメ", "不平等を無くすため", "to eradicate inequality root and branch", "Social & Communication"),
    ("fuchuui o imashime", "ふちゅういをいましめ", "フチュウイヲイマシメ", "不注意を戒め", "admonishing against careless lapses", "Safety & Health"),
    ("fugou no gotoku kurashi", "ふごうのごとくくらし", "フゴウノゴトククラシ", "富豪の如く暮らし", "living like a gilded tycoon", "Home & Living"),
    ("fujiyuu o kanjizu", "ふじゆうをかんじず", "フジユウヲカンジズ", "不自由を感じず", "living comfortably free from want", "Feelings & Mood"),
    ("fukami aru iro de", "ふかみあるいろで", "フカミアルイロデ", "深みある色で", "painted in rich resonant pigment", "Appearance & Style"),
    ("fukitsu o harai", "ふきつをはらい", "フキツヲハライ", "不吉を祓い", "banishing ominous shadows away", "Feelings & Mood"),
    ("fukouhei o tadasu tame", "ふこうへいをただすため", "フコウヘイヲタダスタメ", "不公平を正すため", "to level the tilted playing field", "Condition & Logic"),
    ("fukusou o totonoete", "ふくそうをととのえて", "フクソウヲトトノエテ", "服装を整えて", "adjusting one's formal attire sharply", "Appearance & Style"),
    ("fumi o sonawete", "ふうみをそなえて", "フウミヲソナエテ", "風味を備えて", "blessed with fragrant culinary depth", "Food & Dining"),
    ("funiki ga ii mise de", "ふんいきがいいみせで", "フンイキガイイミセデ", "雰囲気が良い店で", "dining at a cozy cafe with great aura", "Food & Dining"),
    ("fusei o minuki", "ふせいをみぬき", "フセイヲミヌキ", "不正を見抜き", "piercing through fraudulent ruses", "Condition & Logic"),
    ("futou na atsukai ni koushi", "ふとうなあつかいにこうし", "フトウナアツカイニコウシ", "不当な扱いに抗し", "standing firm against wrongful treatment", "Social & Communication"),
    ("fuzei aru machi de", "ふぜいあるまちで", "フゼイアルマチデ", "風情ある町で", "strolling through historic cobblestone lanes", "Travel & Places"),

    # G
    ("gai o oyobosazu", "がいをおよぼさず", "ガイヲオヨボサズ", "害を及ぼさず", "leaving nature unharmed and pristine", "Safety & Health"),
    ("gakumon o osame", "がくもんをおさめ", "ガクモンヲオサメ", "学問を修め", "mastering classical academic disciplines", "Manner & State"),
    ("ganjou ni tsukuri", "がんじょうにつくり", "ガンジョウニツクリ", "頑丈に造り", "constructing with heavy timber integrity", "Appearance & Style"),
    ("gara no yoi hito to", "がらのよいひとと", "ガラノヨイヒトト", "柄の良い人と", "in courteous gentlemanly company", "Social & Communication"),
    ("geijutsu o ai shi", "げいじゅつをあいし", "ゲイジュツヲアイシ", "芸術を愛し", "cherishing the sublime arts devoutly", "Feelings & Mood"),
    ("genba de ashi o hakobi", "げんばであしをはこび", "ゲンバデアシヲハコビ", "現場で足を運び", "visiting the job site on one's own two feet", "Travel & Places"),
    ("genkaku ni mamori", "げんかくにまもり", "ゲンカクニマモリ", "厳格に守り", "upholding commandments to letter", "Manner & State"),
    ("genmitsu ni keisan shi", "げんみつにけいさんし", "ゲンミツニケイサンシ", "厳密に計算し", "calculating with laser precision", "Condition & Logic"),
    ("genshou no sekai de", "げんそうのせかいで", "ゲンソウノセカイデ", "幻想の世界で", "wandering in ethereal dreamscapes", "Travel & Places"),
    ("gouin ni susumezu", "ごういんにすすめず", "ゴウインニススメズ", "強引に進めず", "avoiding heavy-handed coercion", "Social & Communication"),
    ("gouka-kenran ni mise", "ごうかけんらんにみせ", "ゴウカケンランニミセ", "豪華絢爛に見せ", "displaying in dazzling regal luxury", "Appearance & Style"),
    ("goutei o nagame", "ごうていをながめ", "ゴウテイヲナガメ", "豪邸を眺め", "admiring grandiose villas across lake", "Travel & Places"),

    # H
    ("haigo o katame", "はいごをかため", "ハイゴヲカタメ", "背後を固め", "shoring up the rear defense", "Safety & Health"),
    ("hakarishirenai onkei de", "はかりしれないおんけいで", "ハカリシレナイオンケイデ", "計り知れない恩恵で", "with immeasurable, bottomless blessings", "Degree & Extent"),
    ("hakken o yorokobi", "はっけんをよろこび", "ハッケンヲヨロコビ", "発見を喜び", "celebrating the wondrous breakthrough", "Feelings & Mood"),
    ("hakuryoku man-ten no oto", "はくりょくまんてんのおとで", "ハクリョクマンテンノオトデ", "迫力満点の音で", "with room-shaking cinematic acoustics", "Body & Senses"),
    ("hamigaki o taisetsu ni", "はみがきをたいせつに", "ハミガキヲタイセツニ", "歯磨きを大切に", "caring diligently for oral health", "Safety & Health"),
    ("hanayaka na舞台 de", "はなやかなぶたいで", "ハナヤカナブタイデ", "華やかな舞台で", "upon the dazzling spotlit center stage", "Places & Spatial"),
    ("hantsuki-kan no aida", "はんつきかんのあいだ", "ハンツキカンノアイダ", "半月間の間", "spanning a fortnight duration", "Speed & Time"),
    ("haritsumeta ito no gotoku", "はりつめたいとのごとく", "ハリツメタイトノゴトク", "張り詰めた糸の如く", "taut as a plucked bowstring", "Manner & State"),
    ("hassei o matome", "はっせいをまとめ", "ハッセイヲマトメ", "発生をまとめ", "tabulating incidents into a report", "Condition & Logic"),
    ("hatten o toge", "はってんをとげ", "ハッテンヲトゲ", "発展を遂げ", "achieving blooming cultural progress", "Speed & Time"),
    ("heibon na mainichi de", "へいぼんなまいにちで", "ヘイボンナマイニチデ", "平凡な毎日で", "through honest unpretentious daily life", "Frequency & Habit"),
    ("heisateki na kuukan de", "へいさてきなくうかんで", "ヘイサテキナクウカンデ", "閉鎖的な空間で", "within an insular sealed chamber", "Places & Spatial"),
    ("hendou o norikoe", "へんどうをのりこえ", "ヘンドウヲノリコエ", "変動を乗り越え", "navigating through volatile market seas", "Condition & Logic"),
    ("hidoku kanashimi", "ひどくかなしみ", "ヒドクカナシミ", "酷く悲しみ", "grieving with bottomless heart sorrow", "Feelings & Mood"),
    ("hifu o mamori", "ひふをまもり", "ヒフヲマモリ", "肌を守り", "protecting delicate skin from wind", "Safety & Health"),
    ("hikaku o tsuuzhite", "ひかくをつうじて", "ヒカクヲツウジテ", "比較を通じて", "discerning through rigorous contrast", "Condition & Logic"),
    ("hikkuri-kaeru hodo", "ひっくりかえるほど", "ヒックリカエルホド", "ひっくり返る程", "stunning enough to knock one off feet", "Degree & Extent"),
    ("hisshi de korae", "ひっしでこらえ", "ヒッシデコラエ", "必死で堪え", "holding out with every fiber of grit", "Manner & State"),
    ("hitori-bocchi de naku", "ひとりぼっちでなく", "ヒトリボッチデナク", "一人ぼっちでなく", "no longer isolated or lonely", "People & Family"),
    ("hitasura shoujin shi", "ひたすらしょうじんし", "ヒタスラショウジンシ", "ひたすら精進し", "devoting oneself to tireless refinement", "Manner & State"),
    ("hokorashiku mune o hari", "ほこらしくむねをはり", "ホコラシクムネヲハリ", "誇らしく胸を張り", "puffing out chest in quiet pride", "Feelings & Mood"),
    ("honki de torikumi", "ほんきでとりくみ", "ホンキデトリクミ", "本気で取り組み", "grappling with deadly serious resolve", "Manner & State"),
    ("honmono o megutte", "ほんものをめぐって", "ホンモノヲメグッテ", "本物を巡って", "seeking out the genuine McCoy", "Travel & Places"),
    ("horonigai omoide toshite", "ほろにがいおもいでとして", "ホロニガイオモイデトシテ", "ほろ苦い思い出として", "stored as bittersweet nostalgia", "Feelings & Mood"),
    ("hoshuteki na gawa de", "ほしゅてきながわで", "ホシュテキナガワデ", "保守的な側で", "standing on traditionalist side", "Social & Communication"),
    ("hyoujou-yutaka ni warao", "ひょうじょうゆたかにわらい", "ヒョウジョウユタカニワライ", "表情豊かに笑い", "beaming with animated joyful expressions", "Social & Communication"),

    # M - Z
    ("ma-atarashii fuku de", "まあたらしいふくで", "マアタラシイフクデ", "真新しい服で", "decked out in crisp new clothes", "Appearance & Style"),
    ("makkura na michi o", "まっくらなみちを", "マックラナミチヲ", "真っ暗な道を", "walking down the unlit moonlit lane", "Travel & Places"),
    ("mame ni te-ire shi", "まめにていれし", "マメニテイレシ", "忠実に手入れし", "tending with green thumb diligence", "Home & Living"),
    ("manzoku-kan ni hitari", "まんぞくかんにひたり", "マンゾクカンニヒタリ", "満足感に浸り", "basking in deep fulfillment", "Feelings & Mood"),
    ("meikaku ni teigi shi", "めいかくていぎして", "メイカクテイギシテ", "明確に定義して", "defining with crystal razor accuracy", "Condition & Logic"),
    ("mitsudo o tamochi", "みつどをたもち", "ミツドヲタモチ", "密度を保ち", "preserving concentrated richness", "Degree & Extent"),
    ("mizumizushii kajitsu de", "みずみずしいかじつで", "ミズミズシイカジツデ", "瑞々しい果実で", "feasting on dew-fresh sweet peaches", "Food & Dining"),
    ("muda naku tsukai", "むだなくつかい", "ムダナクツカイ", "無駄なく使い", "utilizing every scrap without waste", "Home & Living"),
    ("muga-muchuu de yomi", "むがむちゅうでよみ", "ムガムチュウデヨミ", "無我夢中で読み", "reading glued to the page until dawn", "Social & Communication"),
    ("mukizu de kaeri", "むきずでかえり", "ムキズデカエリ", "無傷で帰り", "returning home safely without scratch", "Safety & Health"),
    ("naiteki na shizukesa de", "ないてきなしずけさで", "ナイテキナシズケサデ", "内的な静けさで", "anchored in deep serene inner peace", "Feelings & Mood"),
    ("namagomi o herashi", "なまごみをへらし", "ナマゴミヲヘラシ", "生ゴミを減らし", "reducing organic kitchen footprint", "Home & Living"),
    ("nando mo fukushuu shi", "なんどもふくしゅうし", "ナンドモフクシュウシ", "何度も復習し", "reviewing vocabulary lessons repeatedly", "Frequency & Habit"),
    ("nikurashii hodo kawaii", "にくらしいほどかわいい", "ニクラシイホドカワイイ", "憎らしい程可愛い", "infuriatingly adorable pup", "Appearance & Style"),
    ("nobinobi to sodatte", "のびのびとそだって", "ノビノビトソダッテ", "のびのびと育って", "growing up happily unconstrained", "People & Family"),
    ("nonbiri to yu-ami", "のんびりとゆあみし", "ノンビリトユアミシ", "のんびりと湯浴みし", "soaking leisurely in hot cedar bath", "Home & Living"),
    ("nozomi o kanaete", "のぞみをかなえて", "ノゾミヲカナエテ", "望みを叶えて", "fulfilling one's fondest lifelong dream", "Feelings & Mood"),
    ("odayaka ni katarai", "おだやかにかたらい", "オダヤカニカタライ", "穏やかに語らい", "chatting warmly over steaming tea", "Social & Communication"),
    ("oishisa o wakeai", "おいしさをわけあい", "オイシサヲワケアイ", "美味しさを分け合い", "sharing delicious bites with friends", "Food & Dining"),
    ("omoi-kiri warai", "おもいきりわらい", "オモイキリワライ", "思い切り笑い", "laughing heartily from belly", "Feelings & Mood"),
    ("onwa na manazashi de", "おんわなまなざしで", "オンワナマナザシデ", "温和な眼差しで", "looking with gentle fatherly eyes", "Social & Communication"),
    ("raku-raku to suikou shi", "らくらくとすいこうし", "ラクラクトスイコウシ", "楽々と遂行し", "executing assignment without sweat", "Manner & State"),
    ("rakuten-teki na seikaku de", "らくてんてきなせいかくで", "ラクテンテキナセイカクデ", "楽天的な性格で", "with an irrepressibly cheerful nature", "Personality & Trait"),
    ("reikoku o haishi", "れいこくをはいし", "レイコクヲハイシ", "冷酷を排し", "banishing cruelty and harshness", "Manner & State"),
    ("reisei o torimodori", "れいせいをとりもどし", "レイセイヲトリモドシ", "冷静を取り戻し", "regaining one's poise and composure", "Feelings & Mood"),
    ("saiai no tomo to", "さいあいのともと", "サイアイノトモト", "最愛の友と", "together with beloved lifelong friend", "People & Family"),
    ("saikouchou no moriagari", "さいこうちょうのもりあがり", "サイコウチョウノモリアガリ", "最高潮の盛り上がり", "surging to the ecstatic crescendo", "Degree & Extent"),
    ("sakura ga chiru koro", "さくらがちるころ", "サクラガチルコロ", "桜が散る頃", "when pink cherry petals swirl in wind", "Nature & Climate"),
    ("sassa to katazuke", "さっさとかたづけ", "サッサトカタヅケ", "さっさと片付け", "tidying up swiftly before dinner", "Home & Living"),
    ("sayuu o tashikamete", "さゆうをたしかめて", "サユウヲタシカメテ", "左右を確かめて", "verifying both ways before crossing", "Safety & Health"),
    ("seichou o yorokobi", "せいちょうをよろこび", "セイチョウヲヨロコビ", "成長を喜び", "celebrating student's wonderful growth", "Feelings & Mood"),
    ("shinpi o himeta", "しんぴをひめた", "シンピヲヒメタ", "神秘を秘めた", "shrouded in mystical allure", "Appearance & Style"),
    ("shinjitsu o tsuranuite", "しんじつをつらぬいて", "シンジツヲツラヌイテ", "真実を貫いて", "staying unyieldingly true to truth", "Manner & State"),
    ("shoujiki na kokoro de", "しょうじきなこころで", "ショウジキナココロデ", "正直な心で", "with pure, transparent sincerity", "Feelings & Mood"),
    ("taikyuu-sei o tashikame", "たいきゅうせいをたしかめ", "タイキュウセイヲタシカメ", "耐久性を確かめ", "stress-testing materials for durability", "Appearance & Style"),
    ("tekisetsu ni taisho shi", "てきせつにたいしょし", "テキセツニタイショシ", "適切に対処し", "handling problem with perfect tact", "Manner & State"),
    ("tokubetsu na kimochi de", "とくべつなきもちで", "トクベツナキモチデ", "特別な気持ちで", "with feelings of deep fondness", "Feelings & Mood"),
    ("tomoni yorokobi-ai", "ともによろこびあい", "トモニヨロコビアイ", "共に喜び合い", "rejoicing together in shared triumph", "Social & Communication"),
    ("touzen no kenri toshite", "とうぜんのけんりとして", "トウゼンノケンリトシテ", "当然の権利として", "claiming as an inalienable right", "Condition & Logic"),
    ("tsune-ni doryoku shi", "つねにどりょくし", "ツネニドリョクシ", "常に努力し", "tirelessly giving 100% every day", "Manner & State"),
    ("ugoki-yasusa o jyuushi", "うごきやすさをじゅうしし", "ウゴキヤスサヲジュウシシ", "動きやすさを重視し", "prioritizing freedom of motion", "Appearance & Style"),
    ("umaku matomari", "うまくまとまり", "ウマクマコマリ", "上手くまとまり", "coming together in neat agreement", "Social & Communication"),
    ("unmei o tomoni shi", "うんめいをともにし", "ウンメイヲトモニシ", "運命を共にし", "sharing one's life destiny together", "People & Family"),
    ("wasure-gatai egao de", "わすれがたいえがおで", "ワスレガタイエガオデ", "忘れ難い笑顔で", "with an unforgettable warm smile", "Feelings & Mood"),
    ("yuueki na jikan toshite", "ゆうえきなじかんとして", "ユウエキナジカントシテ", "有益な時間として", "spent as immensely fruitful time", "Speed & Time"),
    ("yuukan ni katsuyaku shi", "ゆうかんにかつやくし", "ユウカンニカツヤクシ", "勇敢に活躍し", "playing heroically on front lines", "Manner & State"),
    ("zenryoku de ouen shi", "ぜんりょくでおうえんし", "ゼンリョクデオウエンシ", "全力で応援し", "cheering passionately with all heart", "Social & Communication"),
    ("zutto zutto daisuki de", "ずっとずっとだいすきで", "ズットズットダイスキデ", "ずっとずっと大好きで", "loving dearly now and forever", "Feelings & Mood"),
    # Additional authentic Japanese adverbs
    ("arigataku choudai shi", "ありがたくちょうだいし", "アリガタクチョウダイシ", "有難く頂戴し", "gratefully and humbly receiving gift", "Social & Communication"),
    ("asa-moya no naka o", "あさもやのなかを", "アサモヤノナカヲ", "朝靄の中を", "walking through the morning mist", "Nature & Climate"),
    ("ase-bamu you ni", "あせばむように", "アセバムヨウニ", "汗ばむように", "feeling slightly clammy from warmth", "Nature & Climate"),
    ("atataka-na manazashi de", "あたたかなまなざしで", "アタタカナマナザシデ", "暖かな眼差しで", "looking with a gaze full of kindness", "Feelings & Mood"),
    ("ato-ato made", "あとあとまで", "アトアトマデ", "後々まで", "lasting far into the distant future", "Speed & Time"),
    ("ayamaru koto naku", "あやまることなく", "アヤマルコトナク", "誤ることなく", "without deviating from true path", "Condition & Logic"),
    ("azayaka ni sakihokori", "あざやかにさきほこり", "アザヤカニサキホコリ", "鮮やかに咲き誇り", "blooming gloriously in brilliant color", "Nature & Climate"),
    ("bannin ga yorokobu", "ばんにんがよろこぶ", "バンニンガヨロコブ", "万人が喜ぶように", "in a way that delights all humankind", "Social & Communication"),
    ("barabara ni nazu", "ばらばらにならず", "バラバラニナラズ", "バラバラにならず", "staying tightly unified as one", "Manner & State"),
    ("bassui shita bun de", "ばっすいしたぶんで", "バッスイシタブンテ", "抜粋した文で", "with curated concise excerpts", "Social & Communication"),
    ("batsu-gun no kirei sa", "ばつぐんのきれいさで", "バツグンノキレイサデ", "抜群の綺麗さで", "with peerless spotless beauty", "Appearance & Style"),
    ("betsu no kanten de", "べつのかんてんで", "ベツノカンテンデ", "別の観点で", "evaluating from an alternate vantage", "Sequence & Logic"),
    ("bita ichi-en kakezu", "びたいちえんかけず", "ビタイチエンカケズ", "一文も掛けずに", "without spending a single copper penny", "Degree & Quantity"),
    ("bousou o osae-tsutsu", "ぼうそうをおさえつつ", "ボウソウヲオサエツツ", "暴走を抑えつつ", "keeping explosive energy channeled", "Safety & Health"),
    ("bunrui-sareta naka de", "ぶんるいされたなかで", "ブンルイサレタナカデ", "分類された中で", "within neatly organized compartments", "Places & Spatial"),
    ("chakujitsu ni chikara o", "ちゃくじつにちからを", "チャクジツニチカラヲ", "着実に力をつけ", "consistently building real strength", "Condition & Logic"),
    ("chiisa na shiawase de", "ちいさなしあわせで", "チイサナシアワセデ", "小さな幸せで", "finding delight in modest everyday joy", "Feelings & Mood"),
    ("chitsujo-tadashiku koudou", "ちつじょただしくこうどう", "チツジョタダシクコウドウ", "秩序正しく行動し", "acting in disciplined coordinated team", "Manner & State"),
    ("chouwa o kyuumei shi", "ちょうわをきゅうめいし", "チョウワヲキュウメイシ", "調和を究明し", "seeking the perfection of harmony", "Manner & State"),
    ("chuuto de yaburezu", "ちゅうとでやぶれず", "チュウトデヤブレズ", "中途で破れず", "persevering without faltering halfway", "Condition & Logic"),
    ("daidai-iro no yuuyake", "だいだいいろのゆうやけで", "ダイダイイロノユウヤケデ", "橙色の夕焼けで", "under glowing tangerine sunset sky", "Nature & Climate"),
    ("danbou ga kiku heya de", "だんぼうがきくへやで", "ダンボウガキクヘヤデ", "暖房の効く部屋で", "in a comfortably heated room", "Home & Living"),
    ("dekitate no nioi de", "できたてのにおいで", "デキタテノニオイデ", "出来立ての匂いで", "fragrant with freshly baked aroma", "Food & Dining"),
    ("dokutoku no funiki de", "どくとくのふんいきで", "ドクトクノフンイキデ", "独特の雰囲気で", "radiating a singular evocative aura", "Appearance & Style"),
    ("doryoku ga minori", "どりょくがみのり", "ドリョクガミノリ", "努力が実り", "as hard work bears delicious fruit", "Condition & Logic"),
    ("eikyuu ni kagayaku", "えいきゅうにかがやく", "エイキュウニカガヤク", "永久に輝く", "shining with immortal brilliance", "Speed & Time"),
    ("ekiteki ni shinjou shi", "えきてきにしんじょうし", "エキテキニシンジョウシ", "劇的に伸長し", "expanding by leaps and bounds", "Degree & Extent"),
    ("enman ni owari", "えんまんにおわり", "エンマンニオワリ", "円満に終わり", "concluding in peaceful mutual joy", "Social & Communication"),
    ("eri-batsu no meishu", "えりすぐりのめいしゅ", "エリスグリノメイシュ", "選りすぐりの銘酒で", "toasting with select vintage sake", "Food & Dining"),
    ("fukami o kanji-tori", "ふかみをかんじとり", "フカミヲカンジトリ", "深みを感じ取り", "appreciating the rich layered subtlety", "Feelings & Mood"),
    ("fukusou o aratame", "ふくそうをあらため", "フクソウヲアラタメ", "服装を改め", "donning formal solemn ceremonial dress", "Appearance & Style"),
    ("funiki o moriage", "ふんいきをもりあげ", "フンイキヲモリアゲ", "雰囲気を盛り上げ", "elevating the festive party mood", "Social & Communication"),
    ("fuzei o ajiwai", "ふぜいをあじわい", "フゼイヲアジワイ", "風情を味わい", "savoring the poetic aesthetic of garden", "Travel & Places"),
    ("ganjou ni tsukuri-komi", "がんじょうにつくりこみ", "ガンジョウニツクリコミ", "頑丈に造り込み", "crafting with solid heavy joinery", "Appearance & Style"),
    ("geijutsu ni furete", "げいじゅつにふれて", "ゲイジュツニフレテ", "芸術に触れて", "communing with refined masterworks", "Feelings & Mood"),
    ("genmitsu ni shougou", "げんみつにしょうごうし", "ゲンミツニショウゴウシ", "厳密に照合し", "cross-referencing with meticulous care", "Condition & Logic"),
    ("gouin ni hikanazu", "ごういんにひきつけず", "ゴウインニヒキツケズ", "強引に引き付けず", "letting things unfold organically", "Manner & State"),
    ("haigo kara sasasa to", "はいごからさささと", "ハイゴカラサササト", "背後からサササと", "gliding quietly from the shadows", "Speed & Time"),
    ("hakken o tomoni yorokobi", "はっけんをともによろこび", "ハッケンヲトモニヨロコビ", "発見を共に喜び", "sharing excitement of eureka moment", "Social & Communication"),
    ("hamigaki o subete no ato", "はみがきをすべてのあと", "ハミガキヲスベテノアト", "歯磨きを食後に", "brushing teeth faithfully after meals", "Safety & Health"),
    ("hanayaka ni utai", "はなやかにうたい", "ハナヤカニウタイ", "華やかに歌い", "singing joyfully in dazzling chorus", "Social & Communication"),
    ("haritsumeta ito o toku", "はりつめたいとをとく", "ハリツメタイトヲトク", "張り詰めた糸を解く", "relaxing the taut tension smoothly", "Feelings & Mood"),
    ("hatten o kisei shi", "はってんをきせいし", "ハッテンヲキセイシ", "発展を期して", "in high anticipation of future triumphs", "Condition & Logic"),
    ("heibon no naka ni", "へいぼんのなかに", "ヘイボンノナカニ", "平凡の中に", "discovering precious gems in everyday", "Feelings & Mood"),
    ("hendou ni odorokazu", "へんどうにおどろかず", "ヘンドウニオドロカズ", "変動に驚かず", "unfazed by fluctuating conditions", "Feelings & Mood"),
    ("hifu ga kagayaki", "ひふがかがやき", "ヒフガカガヤキ", "肌が輝き", "radiating glowing youthful skin", "Appearance & Style"),
    ("hisshi ni tsuite-iki", "ひっしについていき", "ヒッシニツイテイキ", "必死について行き", "keeping up pace with desperate grit", "Manner & State"),
    ("hokorashiku tachi", "ほこらしくたち", "ホコラシクタチ", "誇らしく立ち", "standing tall and proud in triumph", "Feelings & Mood"),
    ("honki de mukai-ai", "ほんきでむかいあい", "ホンキデムカイアイ", "本気で向かい合い", "confronting issues with earnest soul", "Social & Communication"),
    ("horonigai ocha de", "ほろにがいおちゃで", "ホロニガイオチャデ", "ほろ苦いお茶で", "sipping contemplative bittersweet tea", "Food & Dining"),
    ("hyoujou-yutaka ni hohoemi", "ひょうじょうゆたかにほほえみ", "ヒョウジョウユタカニホホエミ", "表情豊かに微笑み", "smiling with expressive eyes", "Social & Communication"),
    ("ma-atarashii enogu de", "まあたらしいえのぐで", "マアタラシイエノグデ", "真新しい絵の具で", "painting with freshly opened paints", "Appearance & Style"),
    ("mame ni te o arai", "まめにてをあらい", "マメニテヲアライ", "忠実に手を洗い", "diligently washing hands with soap", "Safety & Health"),
    ("manzoku-kan o wakachi", "まんぞくかんをわかちあい", "マンゾクカンヲワカチアイ", "満足感を分かち合い", "basking in mutual shared achievement", "Social & Communication"),
    ("meikaku na shishi de", "めいかくなしじで", "メイカクナシジデ", "明確な指示で", "directing with unambiguous guidance", "Social & Communication"),
    ("mitsudo ga takai jikan", "みつどがたかいじかんで", "ミツドガタカイジカンデ", "密度の高い時間で", "spending deeply concentrated hours", "Speed & Time"),
    ("mizumizushii yasai de", "みずみずしいやさいで", "ミズミズシイヤサイデ", "瑞々しい野菜で", "feasting on crisp garden-fresh greens", "Food & Dining"),
    ("muda o sukkari naku shi", "むだをすっかりなくし", "ムダヲスッカリナクシ", "無駄をすっかり無くし", "eliminating waste down to zero", "Manner & State"),
    ("muga-muchuu de egaki", "むがむちゅうでえがき", "ムガムチュウデエガキ", "無我夢中で描き", "drawing in ecstatic creative flow", "Feelings & Mood"),
    ("mukizu de toudatsu shi", "むきずでとうたつし", "ムキズデトウタツシ", "無傷で到達し", "arriving safely without single injury", "Safety & Health"),
    ("naiteki na seichou o", "ないてきなせいちょうを", "ナイテキナセイチョウヲ", "内的な成長を遂げ", "attaining profound inward growth", "Feelings & Mood"),
    ("nando mo renshuu shi", "なんどもれんしゅうし", "ナンドモレンシュウシ", "何度も練習し", "practicing until second nature", "Frequency & Habit"),
    ("nobinobi to oyogi", "のびのびとおよぎ", "ノビノビトオヨギ", "のびのびと泳ぎ", "swimming comfortably in clear sea", "Travel & Places"),
    ("nonbiri to sanpo shi", "のんびりとさんぽし", "ノンビリトサンポシ", "のんびりと散歩し", "taking a tranquil unhurried stroll", "Travel & Places"),
    ("nozomi o mune ni", "のぞみをむねに", "ノゾミヲムネニ", "望みを胸に", "holding hopeful aspiration close to heart", "Feelings & Mood"),
    ("odayaka na nami no oto", "おだやかななみのおとで", "オダヤカナナミノオトデ", "穏やかな波の音で", "lulled by rhythmic gentle surf", "Nature & Climate"),
    ("oishisa ga hirogari", "おいしさがひろがり", "オイシサガヒロガリ", "美味しさが広がり", "flavor blossoming over palate", "Food & Dining"),
    ("omoi-kiri kakedashi", "おもいきりかけだし", "オモイキリカケダシ", "思い切り駆け出し", "sprinting out with ecstatic speed", "Speed & Time"),
    ("onwa na manazashi de mimamori", "おんわなまなざしでみまもり", "オンワナマナザシデミマモリ", "温和な眼差しで見守り", "watching over with warm maternal eyes", "People & Family"),
    ("raku-raku to suikou dekite", "らくらくとすいこうできて", "ラクラクトスイコウデキテ", "楽々と遂行できて", "accomplishing smoothly with ease", "Manner & State"),
    ("rakuten-teki ni mae o muki", "らくてんてきにまえをむき", "ラクテンテキニマエヲムキ", "楽天的に前を向き", "facing forward with irrepressible cheer", "Feelings & Mood"),
    ("reisei ni jyoukyou o haaku", "れいせいにじょうきょうをはあく", "レイセイニジョウキョウヲハアク", "冷静に状況を把握し", "gauging situation with cool precision", "Condition & Logic"),
    ("saiai no kazoku to", "さいあいのかぞくと", "サイアイノカゾクト", "最愛の家族と", "together with beloved home family", "People & Family"),
    ("saikouchou no netsukyou", "さいこうちょうのねっきょうで", "サイコウチョウノネッキョウデ", "最高潮の熱狂で", "amid fever-pitch ecstatic cheers", "Feelings & Mood"),
    ("sakura no hana-bira to tomo ni", "さくらのはなびらとともに", "サクラノハナビラトトモニ", "桜の花びらと共に", "swirling together with pink sakura petals", "Nature & Climate"),
    ("sassa to koudou ni utsushi", "さっさとこうどうにうつし", "サッサトコウドウニウツシ", "さっさと行動に移し", "leaping straight into prompt action", "Speed & Time"),
    ("sayuu o yoku miru shuukan", "さゆうをよくみるしゅうかんで", "サユウヲヨクミルシュウカンデ", "左右をよく見る習慣で", "habitually checking traffic both ways", "Safety & Health"),
    ("seichou o tomoni iwai", "せいちょうをともにいわい", "セイチョウヲトモニイワイ", "成長を共に祝い", "rejoicing together in milestone growth", "Social & Communication"),
    ("shinpi-teki na mori o", "しんぴてきなもりを", "シンピテキナモリヲ", "神秘的な森を抜け", "passing through enchanted mossy woods", "Travel & Places"),
    ("shinjitsu o katari-tsugi", "しんじつをかたりつぎ", "シンジツヲカタリツギ", "真実を語り継ぎ", "passing down historical truth to youth", "Social & Communication"),
    ("shoujiki ni uchiake", "しょうじきにうちあけ", "ショウジキニウチアケ", "正直に打ち明け", "confiding openly from heart of hearts", "Social & Communication"),
    ("taikyuu-sei o hokoru utsuwa", "たいきゅうせいをほこるうつわで", "タイキュウセイヲホコルウツワデ", "耐久性を誇る器で", "served in sturdy enduring porcelain", "Food & Dining"),
    ("tekisetsu na keikaku de", "てきせつなけいかくで", "テキセツナケイカクデ", "適切な計画で", "guided by thoughtful well-timed schedule", "Manner & State"),
    ("tokubetsu na hi toshite", "とくべつなひととして", "トクベツナヒトトシテ", "特別な日として祝い", "celebrating as an unforgettable milestone", "Frequency & Habit"),
    ("tomoni warai-atta", "ともにわらいあった", "トモニワライアッタ", "共に笑い合った", "laughing together in companionable joy", "Social & Communication"),
    ("touzen no houshuu toshite", "とうぜんのほうしゅうとして", "トウゼンノホウシュウトシテ", "当然の報酬として", "earning fair well-deserved reward", "Condition & Logic"),
    ("tsune-ni shinjiru koto", "つねにしんじることで", "ツネニシンジルコトデ", "常に信じることで", "by constantly holding fast to faith", "Feelings & Mood"),
    ("ugoki-yasui fukusou de", "うごきやすいふくそうで", "ウゴキヤスイフクソウデ", "動きやすい服装で", "attired in comfortable flexible gear", "Appearance & Style"),
    ("umaku kaiketsu dekite", "うまくかいけつできて", "ウマクカイケツデキテ", "上手く解決できて", "resolving smoothly without hitch", "Condition & Logic"),
    ("unmei no deai toshite", "うんめいのであいとして", "ウンメイノデアイトシテ", "運命の出会いとして", "cherishing as a fateful destiny meeting", "Feelings & Mood"),
    ("wasure-gatai toki o", "わすれがたいときを", "ワスレガタイトキヲ", "忘れ難い時を過ごし", "spending unforgettable precious moments", "Feelings & Mood"),
    ("yuueki na taiken toshite", "ゆうえきたいけんとして", "ユウエキタイケントシテ", "有益な体験として", "cherished as an invaluable learning voyage", "Social & Communication"),
    ("yuukan ni tachiagari", "ゆうかんにたちあがり", "ユウカンニタチアガリ", "勇敢に立ち上がり", "rising up heroically against odds", "Manner & State"),
    ("zenryoku de tsukushite", "ぜんりょくでつくして", "ゼンリョクデツクシテ", "全力で尽くして", "devoting oneself with all heart and soul", "Manner & State"),
    ("zutto zutto mimamori", "ずっとずっとみまもり", "ズットズットミマモリ", "ずっとずっと見守り", "watching over with love eternally", "Feelings & Mood")
]
