# Time, Frequency, Speed, Sequence, and Transition Japanese Adverbs
# (romaji, hiragana, katakana, kanji, meaning, topic)
DATA = [
    # A
    ("aida-mo naku", "あいだもなく", "アイダモナク", "間もなく", "without a moment's pause / shortly", "Speed & Time"),
    ("aikawarazu", "あいかわらず", "アイカワラズ", "相変わらず", "as usual / consistently as always", "Frequency & Habit"),
    ("akuruhi", "あくるひに", "アクルヒニ", "明くる日に", "on the very next day", "Speed & Time"),
    ("amari ni mo hayaku", "あまりにもはやく", "アマリニモハヤク", "余りにも早く", "far too early / prematurely", "Speed & Time"),
    ("ano toki", "あのとき", "アノトキ", "あの時", "back at that pivotal moment", "Speed & Time"),
    ("arakajime", "あらかじめ", "アラカジメ", "予め", "beforehand / in advance / preliminarily", "Sequence & Logic"),
    ("aratamete", "あらためて", "アラタメテ", "改めて", "afresh / anew / on a later occasion", "Speed & Time"),
    ("ari-ari to", "ありありと", "アリアリト", "ありありと", "vividly / distinctly recalled", "Manner & State"),
    ("asa ichiban ni", "あさいちばんに", "アサイチバンニ", "朝一番に", "first thing in the bright morning", "Frequency & Time"),
    ("asa kara ban made", "あさからばんまで", "アサカラバンマデ", "朝から晩まで", "from crack of dawn till dusk", "Frequency & Habit"),
    ("asatte", "あさって", "アサッテ", "明後日", "day after tomorrow", "Speed & Time"),
    ("ashikake de", "あしかけで", "アシカケデ", "足掛けで", "spanning across multiple calendar years", "Speed & Time"),
    ("ato de", "あとで", "アトデ", "後で", "later on / afterwards", "Sequence & Logic"),
    ("ato kara ato kara", "あとからあとから", "アトカラアトカラ", "後から後から", "one after another in succession", "Sequence & Logic"),
    ("ato-mawashini", "あとまわしに", "アトマワシニ", "後回しに", "putting off until later", "Sequence & Logic"),

    # B
    ("ban-nen ni", "ばんねんに", "バンネンニ", "晩年に", "in one's twilight / later years", "Speed & Time"),
    ("basshiri-to", "ばっさりと", "バッサリト", "ばっさりと", "severing cleanly / swiftly pruning", "Manner & State"),
    ("batsu-gun no hayasa", "ばつぐんのはやさで", "バツグンノハヤサデ", "抜群の速さで", "at extraordinary supersonic speed", "Speed & Time"),
    ("bijaku ni", "びじゃくに", "ビジャクニ", "微弱に", "faintly / subtly pulsating", "Degree & Extent"),
    ("bonyari shite iru ma", "ぼんやりしているまに", "ボンヤリシテイルマニ", "ぼんやりしている間に", "while spacing out obliviously", "Speed & Time"),
    ("bun-katsu de", "ぶんかつで", "ブンカツデ", "分割で", "by installments / in piecemeal", "Sequence & Logic"),
    ("byou-tani de", "びょうたんいで", "ビョウタンイデ", "秒単位で", "measured down to the second", "Speed & Time"),

    # C
    ("chanto teiki-teki ni", "ちゃんとていきてきに", "チャントテイキテキニ", "定期的にきちんと", "regularly on a disciplined schedule", "Frequency & Habit"),
    ("chikai-uchi ni", "ちかいうちに", "チカイウチニ", "近いうちに", "in the near foreseeable future", "Speed & Time"),
    ("chika-jika", "ちかぢか", "チカヂカ", "近々", "soon / in the coming days", "Speed & Time"),
    ("chiri mo tsumoreba", "ちりもつもれば", "チリモツモレバ", "塵も積もれば", "accumulating bit by bit into mountains", "Quantity & Degree"),
    ("chotto shita ma ni", "ちょっとしたまに", "チョットシタマニ", "ちょっとした間に", "in the blink of a brief interval", "Speed & Time"),
    ("chou-kikan ni watari", "ちょうきかんにわたり", "チョウキカンニワタリ", "長期間にわたり", "over an extended span of time", "Speed & Time"),
    ("choudo ima", "ちょうどいま", "チョウドイマ", "丁度今", "right this very instant", "Speed & Time"),
    ("chotto mae ni", "ちょっとまえに", "チョットマエニ", "ちょっと前に", "just a little while ago", "Speed & Time"),

    # D
    ("daidai", "だいだい", "ダイダイ", "代々", "from generation to generation", "Frequency & Habit"),
    ("dankai-teki ni", "だんかいてきに", "ダンカイテキニ", "段階的に", "step by step / in phased increments", "Sequence & Logic"),
    ("dan-zoku-teki ni", "だんぞくてきに", "ダンゾクテキニ", "断続的に", "intermittently / on and off", "Frequency & Habit"),
    ("denshou-jyou", "でんしょうじょう", "デンショウジョウ", "伝承上", "historically handed down orally", "Frequency & Habit"),
    ("doushi-youshi ni", "どうじに", "ドウジニ", "同時に", "simultaneously / concurrently", "Speed & Time"),

    # E
    ("eien ni", "えいえんに", "エイエンニ", "永遠に", "eternally / forevermore", "Speed & Time"),
    ("eizoku-teki ni", "えいぞくてきに", "エイゾクテキニ", "永続的に", "permanently / on a sustained basis", "Frequency & Habit"),
    ("en'en to", "えんえんと", "エンエント", "延々と", "endlessly dragging on without finish", "Speed & Time"),

    # F
    ("fudan kara", "ふだんから", "フダンカラ", "普段から", "ordinarily / habitually in everyday life", "Frequency & Habit"),
    ("fui ni", "ふいに", "フイニ", "不意に", "unexpectedly / abruptly catching unawares", "Speed & Time"),
    ("fui-uchi de", "ふいうちで", "フイウチデ", "不意打ちで", "by complete surprise attack", "Speed & Time"),
    ("furu-kaiten de", "ふるかいてんで", "フルカイテンデ", "フル回転で", "at full continuous capacity", "Speed & Time"),
    ("futatabi", "ふたたび", "フタタビ", "再び", "once again / a second time", "Frequency & Habit"),

    # G
    ("gankou ni", "がんこうに", "ガンコウニ", "眼光鋭く", "keeping a sharp watchful eye", "Manner & State"),
    ("gankai ni", "がんかいに", "ガンカイニ", "眼下に", "down below beneath one's vision", "Places & Spatial"),
    ("gappeishi-te", "がっぺいして", "ガッペイシテ", "合併して", "merging comprehensively together", "Sequence & Logic"),
    ("gendai ni oite", "げんだいにおいて", "ゲンダイニオイテ", "現代において", "in the contemporary modern era", "Speed & Time"),
    ("genzai dewa", "げんざいでは", "ゲンザイデワ", "現在では", "nowadays / under current circumstances", "Speed & Time"),
    ("gimon-naku", "ぎもんなく", "ギモンナク", "疑問なく", "unquestionably / without second thought", "Condition & Logic"),
    ("giri-giri made", "ぎりぎりまで", "ギリギリマデ", "ギリギリまで", "down to the absolute last second", "Speed & Time"),
    ("gogo ni natte", "ごごになって", "ゴゴニアッテ", "午後になって", "come the afternoon hours", "Speed & Time"),
    ("gozenchu ni", "ごぜんちゅうに", "ゴゼンチュウニ", "午前中に", "during the morning hours", "Speed & Time"),
    ("gyaku ni", "ぎゃくに", "ギャクニ", "逆に", "on the contrary / conversely", "Sequence & Logic"),

    # H
    ("haishin-go sugu", "はいしんごすぐ", "ハイシンゴスグ", "配信後すぐ", "immediately upon release / livestream", "Speed & Time"),
    ("hajimari kara", "はじまりから", "ハジマリカラ", "始まりから", "from the very inception", "Sequence & Logic"),
    ("hajimete", "はじめて", "ハジメテ", "初めて", "for the first time in one's life", "Frequency & Habit"),
    ("han-eikyuu-teki ni", "はんえいきゅうてきに", "ハンエイキュウテキニ", "半永久的に", "semi-permanently / durable for ages", "Speed & Time"),
    ("han-jikan mae ni", "はんじかんまえに", "ハンジカンマエニ", "半時間前に", "half an hour earlier", "Speed & Time"),
    ("han-nen-goto ni", "はんねんごとに", "ハンネンゴトニ", "半年毎に", "every half year / semi-annually", "Frequency & Habit"),
    ("haru-saki ni", "はるさきに", "ハルサキニ", "春先に", "at the earliest onset of spring", "Nature & Climate"),
    ("hata-mata", "はたまた", "ハタマタ", "将又", "or indeed / alternatively", "Sequence & Logic"),
    ("hayai uchi ni", "はやいうちに", "ハヤイウチニ", "早いうちに", "while it is still early / before late", "Speed & Time"),
    ("hayaku mo", "はやくも", "ハヤクモ", "早くも", "already / as early as now", "Speed & Time"),
    ("heijitsu ni", "へいじつに", "ヘイジツニ", "平日に", "on standard weekdays", "Frequency & Habit"),
    ("hidoku hisabisa ni", "ひどくひさびさに", "ヒドクヒサビサニ", "酷く久しぶりに", "after a dreadfully long absence", "Frequency & Habit"),
    ("hi-goto ni", "ひごとに", "ヒゴトニ", "日毎に", "day after day / with each passing day", "Frequency & Habit"),
    ("hima-naku", "ひまなく", "ヒマナク", "暇なく", "unceasingly / without breathing room", "Speed & Time"),
    ("hina-gata toshite", "ひながたとして", "ヒナガタトシテ", "雛形として", "serving as the initial prototype", "Sequence & Logic"),
    ("hinpan ni", "ひんぱんに", "ヒンパンニ", "頻繁に", "frequently / repeatedly / regularly", "Frequency & Habit"),
    ("hiruma ni", "ひるまに", "ヒルマニ", "昼間に", "during broad daylight hours", "Speed & Time"),
    ("hisabisa ni", "ひさびさに", "ヒサビサニ", "久しぶりに", "after a long while / for first time in ages", "Frequency & Habit"),
    ("hitazu-ra ni", "ひたすらに", "ヒタスラニ", "一筋に", "purely and relentlessly", "Manner & State"),
    ("hitomazu", "ひとまず", "ヒトマズ", "一先ず", "for the present / for now / tentatively", "Sequence & Logic"),
    ("hitori-de ni", "ひとりでに", "ヒトリデニ", "独りでに", "by itself / automatically", "Condition & Logic"),
    ("hitori-gurashi de", "ひとりぐらしで", "ヒトリグラシデ", "一人暮らしで", "living on one's own independently", "People & Family"),
    ("hitotabi", "ひとたび", "ヒトタビ", "一たび", "once / whenever once it occurs", "Condition & Logic"),
    ("hi-wo oite", "ひをおいて", "ヒヲオイテ", "日を置いて", "allowing several days to pass", "Speed & Time"),
    ("hokano toki ni", "ほかのときに", "ホカノトキニ", "他の時に", "on some other different occasion", "Speed & Time"),
    ("honrai wa", "ほんらいは", "ホンライワ", "本来は", "originally / fundamentally intended", "Sequence & Logic"),
    ("hyotto suru to", "ひょっとすると", "ヒョットスルト", "ひょっとすると", "possibly / by some outside chance", "Condition & Logic"),

    # I
    ("ichidou ni", "いちどうに", "イチドウニ", "一同に", "all gathered together in unison", "People & Family"),
    ("ichiji-teki ni", "いちじてきに", "イチジテキニ", "一時的に", "temporarily / for the interim", "Speed & Time"),
    ("ichinichi-juu", "いちにちじゅう", "イチニチジュウ", "一日中", "all day long / from morn till night", "Speed & Time"),
    ("ichiryuu no te de", "いちりゅうのてで", "イチリュウノテデ", "一流の手で", "by a master craftsman's hand", "Manner & State"),
    ("ima de koso", "いまでこそ", "イマデコソ", "今でこそ", "nowadays (in contrast with past)", "Speed & Time"),
    ("ima made", "いままで", "イママデ", "今まで", "up until this exact moment", "Speed & Time"),
    ("ima ni", "いまに", "イマニ", "今に", "before long / one of these days", "Speed & Time"),
    ("ima ni mo", "いまにも", "イマニモ", "今にも", "at any moment / on the verge of", "Speed & Time"),
    ("ima sara", "いまさら", "イマサラ", "今更", "at this late hour / too late now", "Speed & Time"),
    ("ima ya", "いまや", "イマヤ", "今や", "now at present / already in this era", "Speed & Time"),
    ("ima-jibun", "いまじぶん", "イマジブン", "今時分", "around this hour of the day", "Speed & Time"),
    ("inaba", "いなば", "イナバ", "否応なく", "willy-nilly / whether one likes it or not", "Condition & Logic"),
    ("ippou de", "いっぽうで", "イッポウデ", "一方で", "on the other hand / simultaneously", "Sequence & Logic"),
    ("issai gassai", "いっさいがっさい", "イッサイガッサイ", "一切合切", "everything lock, stock and barrel", "Degree & Quantity"),
    ("isshou-kenmei", "いっしょうけんめい", "イッショウケンメイ", "一生懸命", "with all one's might / desperately hard", "Manner & State"),
    ("isshun de", "いっしゅんで", "イッシュンデ", "一瞬で", "in a fleeting fraction of a second", "Speed & Time"),
    ("isshuukan-juu", "いっしゅうかんじゅう", "イッシュウカンジュウ", "一週間中", "throughout the entire seven-day week", "Speed & Time"),
    ("itsu de mo", "いつでも", "イツデモ", "いつでも", "anytime / whenever you like", "Frequency & Habit"),
    ("itsu ka", "いつか", "イツカ", "何時か", "someday / at some point", "Speed & Time"),
    ("itsu no ma ni ka", "いつのまにか", "イツノマニカ", "いつの間にか", "before one even realized it", "Speed & Time"),
    ("itsumo no you ni", "いつものように", "イツモノヨウニ", "いつものように", "just as usual / like clockwork", "Frequency & Habit"),
    ("izen toshite", "いぜんとして", "イゼントシテ", "依然として", "still / persisting unchanged", "Frequency & Habit"),

    # J
    ("jiki ni", "じきに", "ジキニ", "直に", "promptly / very soon", "Speed & Time"),
    ("jiko-hasshin de", "じこはっしんで", "ジコハッシンデ", "自己発信で", "proactively initiating on one's own", "Manner & State"),
    ("jimon-jitou shite", "じもんじとうして", "ジモンジトウシテ", "自問自答して", "soliloquizing / soul-searching inward", "Manner & State"),
    ("jin-soku ni", "じんそくに", "ジンソクニ", "迅速に", "swiftly / expeditiously / without delay", "Speed & Time"),
    ("jisoku de", "じそくで", "ジソクデ", "時速で", "at speed of kilometers per hour", "Speed & Time"),
    ("jitsugen-go", "じつげんご", "ジツゲンゴ", "実現後", "post-implementation / following realization", "Sequence & Logic"),
    ("jitsumu-jyou", "じつむじょう", "ジツムジョウ", "実務上", "in practical business reality", "Condition & Logic"),
    ("jouji", "じょうじ", "ジョウジ", "常時", "all times / 24/7 round the clock", "Frequency & Habit"),
    ("juukyuu-seiki ni", "じゅうきゅうせいきに", "ジュウキュウセイキニ", "19世紀に", "back during the 19th century", "Speed & Time"),
    ("juubun jikan o kakete", "じゅうぶんじかんをかけて", "ジュウブンジカンヲカケテ", "十分時間をかけて", "taking ample deliberate time", "Speed & Time"),

    # K
    ("kaishi-touji", "かいしとうじ", "カイシトウジ", "開始当時", "back when it initially launched", "Speed & Time"),
    ("kakugo o kimete", "かくごをきめて", "カクゴヲキメテ", "覚悟を決めて", "having braced oneself resolutely", "Feelings & Mood"),
    ("kakujitsu ni", "かくじつに", "カクジツニ", "確実に", "unfailingly / surely / reliably", "Condition & Logic"),
    ("kakushin-teki ni", "かくしんてきに", "カクシンテキニ", "確信的に", "with absolute conviction / intentionally", "Condition & Logic"),
    ("kanarazu", "かならず", "カナラズ", "必ず", "without fail / absolutely / surely", "Condition & Logic"),
    ("katsute", "かつて", "カツテ", "嘗て", "once in the past / former times", "Speed & Time"),
    ("kondo koso", "こんどこそ", "コンドコソ", "今度こそ", "this time for sure / this time around", "Frequency & Habit"),
    ("kon-go to mo", "こんごとも", "コンゴトモ", "今後とも", "from now onward / continuing forward", "Speed & Time"),
    ("kono aida", "このあいだ", "コノアイダ", "この間", "the other day / recently", "Speed & Time"),
    ("kono saki", "このさき", "コノサキ", "この先", "ahead from here / into future days", "Speed & Time"),
    ("kono-goro", "このごろ", "コノゴロ", "この頃", "lately / these days", "Speed & Time"),
    ("koushin-chuu ni", "こうしんちゅうに", "コウシンチュウニ", "更新中に", "while in the middle of updating", "Speed & Time"),
    ("kou-shite", "こうして", "コウシテ", "こうして", "in this manner / and thus", "Sequence & Logic"),
    ("kyuugyou-bi ni", "きゅうぎょうびに", "キュウギョウビニ", "休業日に", "on business scheduled holidays", "Frequency & Habit"),
    ("kyuuni", "きゅうに", "キュウニ", "急に", "suddenly / all of a sudden", "Speed & Time"),
    ("kyuugeki ni", "きゅうげきに", "キュウゲキニ", "急激に", "drastically / precipitously", "Speed & Time"),

    # M
    ("mae motte", "まえもって", "マエモッテ", "前もって", "in advance / beforehand", "Sequence & Logic"),
    ("mai-asa", "まいあさ", "マイアサ", "毎朝", "every single morning without fail", "Frequency & Habit"),
    ("mai-ban", "まいばん", "マイバン", "毎晩", "every night / night after night", "Frequency & Habit"),
    ("mai-do", "まいど", "マイド", "毎度", "each time / thank you for your patronage", "Frequency & Habit"),
    ("mai-getsu", "まいげつ", "マイゲツ", "毎月", "every month / monthly", "Frequency & Habit"),
    ("mai-nichi", "まいにち", "マイニチ", "毎日", "every day / daily routine", "Frequency & Habit"),
    ("mai-shu", "まいしゅう", "マイシュウ", "毎週", "every week / weekly", "Frequency & Habit"),
    ("mai-toshi", "まいとし", "マイトシ", "毎年", "every year / annually", "Frequency & Habit"),
    ("mamonaku", "まもなく", "マモナク", "間もなく", "shortly / before very long", "Speed & Time"),
    ("marude ima no you ni", "まるでいまのように", "マルデイマノヨウニ", "まるで今のように", "as if it were just occurring right now", "Speed & Time"),
    ("mattaku motte", "まったくもって", "マッタクモッテ", "全く以て", "most utterly / without a shadow of doubt", "Degree & Extent"),
    ("me no mae de", "めのまえで", "メノマエデ", "目の前で", "right before one's very eyes", "Places & Spatial"),
    ("me-sakki", "めさっき", "メサッキ", "目先", "in the immediate near horizon", "Speed & Time"),
    ("mijikai kikan de", "みじかいきかんで", "ミジカイキカンデ", "短い期間で", "in a remarkably short interval", "Speed & Time"),
    ("mirai-e mukatte", "みらいへむかって", "ミライヘムカッテ", "未来へ向かって", "heading toward the future horizon", "Speed & Time"),
    ("mizu-kara", "みずから", "ミズカラ", "自ら", "of one's own initiative / personally", "Manner & State"),
    ("mou sugu", "もうすぐ", "モウスグ", "もう直ぐ", "very soon / almost ready", "Speed & Time"),
    ("mou sudeni", "もうすでに", "モウスデニ", "もう既に", "already having taken place", "Speed & Time"),
    ("moto-moto", "もともと", "モトモト", "元々", "originally / from the start", "Sequence & Logic"),
    ("motto mae kara", "もっとまえから", "モットマエカラ", "もっと前から", "since much earlier than that", "Speed & Time"),

    # N - Z
    ("nagai me de mite", "ながいめでみて", "ナガイメデミテ", "長い目で見て", "taking a long-term patient view", "Speed & Time"),
    ("nagannen", "ながねん", "ナガネン", "長年", "over many enduring years", "Speed & Time"),
    ("nakaba", "なかば", "ナカバ", "半ば", "halfway / midway through", "Sequence & Logic"),
    ("nen-juu", "ねんじゅう", "ネンジュウ", "年中", "all year round / continuously", "Frequency & Habit"),
    ("nen-matsu ni", "ねんまつに", "ネンマツニ", "年末に", "at the year-end season", "Speed & Time"),
    ("nichijou-teki ni", "にちじょうてきに", "ニチジョウテキニ", "日常的に", "on a routine daily basis", "Frequency & Habit"),
    ("ni-do to", "にどと", "ニドト", "二度と", "never again (with negative verb)", "Frequency & Habit"),
    ("nokori wazuka de", "のこりわずかで", "ノコリワズカデ", "残り僅かで", "with only a tiny bit remaining", "Degree & Quantity"),
    ("norari-kurari to", "のらりくらりと", "ノラリクラリト", "のらりくらりと", "dodging and temporizing smoothly", "Manner & State"),
    ("nochi-hodo", "のちほど", "ノチホド", "後程", "a little later today", "Speed & Time"),
    ("oiraku ni", "おいらくに", "オイラクニ", "老いらくに", "in peaceful gentle retirement age", "Speed & Time"),
    ("omomuro ni", "おもむろに", "オモムロニ", "徐に", "slowly, deliberately and gracefully", "Speed & Time"),
    ("oriori", "おりおり", "オリオリ", "折々", "from time to time / occasionally", "Frequency & Habit"),
    ("orikaeshi", "おりかえし", "オリカイシ", "折り返し", "by immediate return call / reply", "Speed & Time"),
    ("osoraku", "おそらく", "オソラク", "恐らく", "in all likelihood / most probably", "Condition & Logic"),
    ("osoku tomo", "おそくとも", "オソクトモ", "遅くとも", "at the latest", "Speed & Time"),
    ("owari ni", "おわりに", "オワリニ", "終わりに", "in closing / at the conclusion", "Sequence & Logic"),
    ("rainen koso", "らいねんこそ", "ライネンコソ", "来年こそ", "next year without fail!", "Speed & Time"),
    ("renzoku shite", "れんぞくして", "レンゾクシテ", "連続して", "in continuous uninterrupted succession", "Frequency & Habit"),
    ("rinji ni", "りんじに", "リンジニ", "臨時に", "extraordinary / on special standby", "Frequency & Habit"),
    ("saigo ni", "さいごに", "サイゴニ", "最後に", "lastly / as the final step", "Sequence & Logic"),
    ("saisho ni", "さいしょに", "サイショニ", "最初に", "first and foremost / initially", "Sequence & Logic"),
    ("saishuu-teki ni", "さいしゅうてきに", "サイシュウテキニ", "最終的に", "ultimately in the end", "Sequence & Logic"),
    ("sakihodo", "さきほど", "サキホド", "先程", "a short while ago / just earlier", "Speed & Time"),
    ("sakki kara", "さっきから", "サッキカラ", "さっきから", "for quite a while now / since earlier", "Speed & Time"),
    ("sappari", "さっぱり", "サッパリ", "さっぱり", "completely not at all / refreshingly clean", "Degree & Extent"),
    ("shiba-shiba", "しばしば", "シバシバ", "屡々", "often / frequently / time and again", "Frequency & Habit"),
    ("shidaini", "しだいに", "シダイニ", "次第に", "gradually / little by little", "Speed & Time"),
    ("shikashi nagara", "しかしながら", "シカシナガラ", "しかしながら", "nevertheless / however that may be", "Sequence & Logic"),
    ("shoutou-go", "しょうとうご", "ショウトウゴ", "消灯後", "after lights-out at night", "Speed & Time"),
    ("shukujitsu ni", "しゅくじつに", "シュクジツニ", "祝日に", "on public national holidays", "Frequency & Habit"),
    ("shunkan-teki ni", "しゅんかんてきに", "シュンカンテキニ", "瞬間的に", "in an instantaneous flash", "Speed & Time"),
    ("sono ato", "そのあと", "ソノアト", "その後", "after that / subsequent to that", "Sequence & Logic"),
    ("sono ba de", "そのばで", "ソノバデ", "その場で", "on the spot / right there and then", "Speed & Time"),
    ("sono toki kara", "そのときから", "ソノトキカラ", "その時から", "ever since that fateful day", "Speed & Time"),
    ("sono uchi", "そのうち", "ソノウチ", "その内に", "before long / one of these days", "Speed & Time"),
    ("soro-soro", "そろそろ", "ソロソロ", "そろそろ", "about time to get going / soon", "Speed & Time"),
    ("sugu ni", "すぐに", "スグニ", "直ぐに", "immediately / right away", "Speed & Time"),
    ("sugu-sama", "すぐさま", "スグサマ", "直ぐ様", "instantly / without a split-second delay", "Speed & Time"),
    ("sukoshi-zutsu", "すこしずつ", "スコシズツ", "少しずつ", "little by little / in incremental steps", "Degree & Quantity"),
    ("tabi-tabi", "たびたび", "タビタビ", "度々", "frequently / repeatedly / again and again", "Frequency & Habit"),
    ("tachimachi", "たちまち", "タチマチ", "忽ち", "in a flash / in no time flat", "Speed & Time"),
    ("tadaima", "ただいま", "タダイマ", "只今", "just now / right at this present moment", "Speed & Time"),
    ("tama ni", "たまに", "タマニ", "偶に", "occasionally / once in a blue moon", "Frequency & Habit"),
    ("tatta ima", "たったいま", "タッタイマ", "たった今", "just this very instant", "Speed & Time"),
    ("teiki-teki ni", "ていきてきに", "テイキテキニ", "定期的に", "periodically / at regular intervals", "Frequency & Habit"),
    ("tetsuya de", "てつやで", "テツヤデ", "徹夜で", "pulling an all-nighter through dawn", "Speed & Time"),
    ("tokidoki", "ときどき", "トキドキ", "時々", "sometimes / at intervals", "Frequency & Habit"),
    ("tokori-ori", "ところおりおり", "トコロオリオリ", "所折々", "here and there throughout the seasons", "Frequency & Habit"),
    ("toubun no aida", "とうぶんのあいだ", "トウブンノアイダ", "当分の間", "for the time being / foreseeable future", "Speed & Time"),
    ("totsuzen", "とつぜん", "トツゼン", "突然", "suddenly / without warning", "Speed & Time"),
    ("tsune-ni", "つねに", "ツネニ", "常に", "always / perpetually / constantly", "Frequency & Habit"),
    ("tsuini", "ついに", "ツイニ", "遂に", "finally / at long last / ultimately", "Sequence & Logic"),
    ("tsugi-tsugi ni", "つぎつぎに", "ツギツギニ", "次々に", "one after another in rapid procession", "Sequence & Logic"),
    ("wazuka-na aida ni", "わずかなあいだに", "ワズカナアイダニ", "僅かな間に", "in just a brief fleeting moment", "Speed & Time"),
    ("yae-ba ni", "やがて", "ヤガテ", "軈て", "before long / soon / in due course", "Speed & Time"),
    ("yakan ni", "やかんに", "ヤカンニ", "夜間に", "during night hours", "Speed & Time"),
    ("yoku-asa", "よくあさ", "ヨクアサ", "翌朝", "the following morning", "Speed & Time"),
    ("yoku-jitsu", "よくじつ", "ヨクジツ", "翌日", "the next day", "Speed & Time"),
    ("yoku-nen", "よくねん", "ヨクネン", "翌年", "the following year", "Speed & Time"),
    ("yo-na yo-na", "よなよな", "ヨナヨナ", "夜な夜な", "night after night without exception", "Frequency & Habit"),
    ("yotori o motte", "ゆとりをもって", "ユトリヲモッテ", "ゆとりを持って", "with ample spare time in reserve", "Speed & Time"),
    ("yukkuri to", "ゆっくりと", "ユックリト", "ゆっくりと", "leisurely and unhurriedly", "Speed & Time"),
]
