# Comprehensive Japanese Adverbs A through M (320+ unique entries)
# (romaji, hiragana, katakana, kanji, meaning, topic)
DATA = [
    # A
    ("abuku no you ni", "あぶくのように", "アブクノヨウニ", "泡のように", "fleetingly like bursting bubbles", "Manner & State"),
    ("achi-kochi de", "あちこちで", "アチコチデ", "あちこちで", "here, there, and everywhere", "Places & Spatial"),
    ("ada to natte", "あだとなって", "アダトナッテ", "仇となって", "backfiring detrimentally", "Condition & Logic"),
    ("ae-aegu", "あえぎあえぎ", "アエギアエギ", "喘ぎ喘ぎ", "gasping for breath with exertion", "Body & Senses"),
    ("aenaku mo", "あえなくも", "アエナクモ", "敢え無くも", "tragically and anti-climactically", "Condition & Logic"),
    ("afuren bakari ni", "あふれんばかりに", "アフレンバカリニ", "溢れんばかりに", "brimming over to the very brim", "Degree & Extent"),
    ("aikou-sha toshite", "あいこうしゃとして", "アイコウシャトシテ", "愛好者として", "speaking as an avid enthusiast", "Social & Communication"),
    ("aikurushiku", "あいくるしく", "アイクルシク", "愛くるしく", "sweetly and endearingly cute", "Appearance & Style"),
    ("aimai na mama", "あいまいのまま", "アイマイノママ", "曖昧のまま", "leaving in unsettled ambiguity", "Manner & State"),
    ("aisatsu kawari ni", "あいさつがわりに", "アイサツガワリニ", "挨拶代わりに", "by way of friendly greeting", "Social & Communication"),
    ("aka-aka to", "あかあかと", "アカアカト", "赤々と", "glowing brightly red (hearth / sun)", "Appearance & Style"),
    ("akarasama sugiru hodo", "あからさますぎるほど", "アカラサマスギルホド", "露骨すぎる程", "all too transparently and bluntly", "Degree & Extent"),
    ("akari o tayori ni", "あかりをたよりに", "アカリヲタヨリニ", "灯りを頼りに", "guided by the lone lantern light", "Places & Spatial"),
    ("ake-gata ni", "あけがたに", "アケガタニ", "明け方に", "at the crack of morning dawn", "Speed & Time"),
    ("ake-suke ni", "あけすけに", "アケスケニ", "明け透けに", "frankly without pretense / open book", "Social & Communication"),
    ("aki mo sezu", "あきもせず", "アキモセズ", "飽きもせず", "tirelessly without getting bored", "Frequency & Habit"),
    ("akogare o daite", "あこがれをだいて", "アコガレヲダイテ", "憧れを抱いて", "holding sweet romantic aspirations", "Feelings & Mood"),
    ("aku-jyouken no moto", "あくじょうけんのもと", "アクジョウケンノモト", "悪条件の元", "under adverse severe conditions", "Condition & Logic"),
    ("amaku sasayaite", "あまくささやいて", "アマクササヤイテ", "甘く囁いて", "whispering sweet tender nothings", "Social & Communication"),
    ("amari no koto ni", "あまりのことに", "アマリノコトニ", "余りの事に", "overwhelmed by the shocking turn", "Feelings & Mood"),
    ("an'un ga tarekomete", "あんうんがたれこめて", "アンウンガタレコメテ", "暗雲が垂れ込めて", "with dark storm clouds gathering", "Nature & Climate"),
    ("anata-sama no tame ni", "あなたさまのために", "アナタサマノタメニ", "貴方様のために", "most respectfully for your honor", "Social & Communication"),
    ("angai ni mo", "あんがいにも", "アンガイニモ", "案外にも", "contrary to initial expectation", "Condition & Logic"),
    ("anshin shite", "あんしんして", "アンシンシテ", "安心して", "with heart at ease / in peace of mind", "Feelings & Mood"),
    ("anzan o inotte", "あんざんをいのって", "アンザンヲイノッテ", "安産を祈って", "praying for safe healthy childbirth", "People & Family"),
    ("ao-ao to", "あおあおと", "アオアオト", "青々と", "lushly verdant and green", "Nature & Climate"),
    ("aoba ga shigeru koro", "あおばがしげるころ", "アオバガシゲルコロ", "青葉が茂る頃", "around the lush greenery season", "Nature & Climate"),
    ("apparen na ikikata de", "あっぱれないきかたで", "アッパレナイキカタデ", "天晴れな生き方で", "living with admirable dignity", "Manner & State"),
    ("arakajime ketsugi", "あらかじめけつぎして", "アラカジメケツギシテ", "予め決議して", "resolving formally in advance", "Condition & Logic"),
    ("arasoi-ba de", "あらそいのばで", "アラソイノバデ", "争いの場で", "on the contested battlefront", "Places & Spatial"),
    ("aratamatta choushi de", "あらたまったちょうしで", "アラタマッタチョウシデ", "改まった調子で", "in a solemn formal tone", "Social & Communication"),
    ("ari-amaru hodo", "ありあまるほど", "アリアマルホド", "有り余る程", "more than enough to spare", "Degree & Quantity"),
    ("arigatou to itte", "ありがとうといって", "アリガトウトイッテ", "有難うと言って", "saying heartfelt 'thank you'", "Social & Communication"),
    ("aru hi totsuzen", "あるひとつぜん", "アルヒトツゼン", "或る日突然", "one day out of the clear blue", "Speed & Time"),
    ("aruke-do aruke-do", "あるけどあるけど", "アルケドアルケド", "歩けど歩けど", "walking on and on without end", "Travel & Places"),
    ("asa-ban", "あさばん", "アサバン", "朝晩", "morning and evening daily", "Frequency & Habit"),
    ("asahi o abite", "あさひをあびて", "アサヒヲアビテ", "朝日を浴びて", "basking in radiant morning sun", "Nature & Climate"),
    ("ashimoto ni ki o tsukete", "あしもとにきをつけて", "アシモトニキヲツケテ", "足元に気をつけて", "watching one's step prudently", "Safety & Health"),
    ("asobu you ni", "あそぶように", "アソブヨウニ", "遊ぶように", "playfully as if a fun game", "Manner & State"),
    ("atama kara tsumasaki", "あたまからつまさきまで", "アタマカラツマサキマデ", "頭から爪先まで", "from tip of head to very toes", "Places & Spatial"),
    ("atataka-sa o motte", "あたたかさをもって", "アタタカサヲモッテ", "温かさを持って", "with tender affectionate warmth", "Feelings & Mood"),
    ("atarashiku umarekawatte", "あたらしくうまれかわって", "アタラシクウマレカワッテ", "新しく生まれ変わって", "freshly reborn and renewed", "Manner & State"),
    ("ato-oshi sarete", "あとおしされて", "アトオシサレテ", "後押しされて", "boosted by supportive winds", "Condition & Logic"),
    ("atsui manazashi de", "あついまなざしで", "アツイマナザシデ", "熱い眼差しで", "with an intense passionate gaze", "Feelings & Mood"),
    ("ayamachi o mitomete", "あやまちをみとめて", "アヤマチヲミトメテ", "過ちを認めて", "graciously acknowledging one's error", "Social & Communication"),
    ("azayaka sugiru hodo", "あざやかすぎるほど", "アザヤカスギルホド", "鮮やかすぎる程", "with blindingly brilliant color", "Appearance & Style"),

    # B
    ("ba ni oujite", "ばにおうじて", "バニオウジテ", "場に応じて", "tailored appropriately to venue", "Manner & State"),
    ("baka-shoujiki ni", "ばかしょうじきに", "バカショウジキニ", "馬鹿正直に", "honest to a fault / ingenuously", "Personality & Trait"),
    ("bakudai na doryoku de", "ばくだいなどりょくで", "バクダイナドリョクデ", "莫大な努力で", "through herculean tremendous toil", "Manner & State"),
    ("bannin ga mitomeru", "ばんにんがみとめるように", "バンニンガミトメルヨウニ", "万人が認めるように", "as universally acclaimed by all", "Social & Communication"),
    ("banzen o kitashite", "ばんぜんをきたして", "バンゼンヲキタシテ", "万全を期して", "leaving absolutely nothing to chance", "Manner & State"),
    ("bassui shite", "ばっすいして", "バッスイシテ", "抜粋して", "by way of salient extract", "Sequence & Logic"),
    ("batsu-gun no aji de", "ばつぐんのあじで", "バツグンノアジデ", "抜群の味で", "with peerlessly delicious taste", "Food & Dining"),
    ("bimyona chigai o motte", "びみょうなちがいをもって", "ビミョウナチガイヲモッテ", "微妙な違いを持って", "with subtle distinguishing nuances", "Degree & Extent"),
    ("bijin-zukuri de", "びじんづくりで", "ビジンヅクリデ", "美人造りで", "with exquisite graceful craftsmanship", "Appearance & Style"),
    ("bita ichimon tarazu", "びたいちもんたらず", "ビタイチモンタラズ", "一文足らず", "short by not a solitary red cent", "Degree & Quantity"),
    ("biyou no tame ni", "びようのために", "ビヨウノタメニ", "美容のために", "for radiance and skin aesthetic", "Appearance & Style"),
    ("bochibochi", "ぼちぼち", "ボチボチ", "ぼちぼち", "gradually / leisurely getting along", "Speed & Time"),
    ("bokantoshite iru ma ni", "ぼーっとしているまに", "ボートシテイルマニ", "ぼんやりしている間に", "while dreaming and spacing out", "Speed & Time"),
    ("bousou o tomete", "ぼうそうをとめて", "ボウソウヲトメテ", "暴走を止めて", "halting runaway stampede", "Safety & Health"),
    ("bunmyaku-jou", "ぶんみゃくじょう", "ブンミャクジョウ", "文脈上", "contextually in narrative", "Condition & Logic"),
    ("byoushou de", "びょうしょうで", "ビョウショウデ", "病床で", "confined upon the sickbed", "Safety & Health"),

    # C
    ("chakuchaku to", "ちゃくちゃくと", "チャクチャクト", "着々と", "steadily making firm progress", "Speed & Time"),
    ("chiisa na koto kara", "ちいさなことから", "チイサナコトカラ", "小さな事から", "starting from the modest little steps", "Sequence & Logic"),
    ("chikara-makase ni", "ちからまかせに", "チカラマカセニ", "力任せに", "using brute physical strength alone", "Manner & State"),
    ("chimitsu na keikaku de", "ちみつなけいかくで", "チミツナケイカクデ", "緻密な計画で", "with a scrupulously drafted blueprint", "Manner & State"),
    ("chitsujo o tamotte", "ちつじょをたもって", "チツジョヲタモッテ", "秩序を保って", "maintaining decorum and good order", "Manner & State"),
    ("chokusetsu te de", "ちょくせつてで", "チョクセツテデ", "直接手で", "with one's bare hands directly", "Manner & State"),
    ("choudo ii guai ni", "ちょうどいいぐあいに", "チョウドイイグアイニ", "丁度いい塩梅に", "in just the right sweet proportion", "Degree & Extent"),
    ("chouka shite", "ちょうかして", "チョウカシテ", "超過して", "surpassing permissible boundary", "Degree & Quantity"),
    ("chousen-sha toshite", "ちょうせんしゃとして", "チョウセンシャトシテ", "挑戦者として", "standing proud as the challenger", "Social & Communication"),
    ("choutsu-gai no gotoku", "ちょうつがいのごとく", "チョウツガイノゴトク", "蝶番の如く", "smoothly hinged and pivoting", "Manner & State"),
    ("chuu-ya o towazu", "ちゅうやをとわず", "チュウヤヲトワズ", "昼夜を問わず", "day and night indiscriminately", "Frequency & Habit"),

    # D
    ("daidai-iro ni somatte", "だいだいいろにそまって", "ダイダイイロニソマッテ", "橙色に染まって", "tinted in warm sunset orange", "Appearance & Style"),
    ("dai-dankai de", "だいだんかいで", "ダイダンカイデ", "大段階で", "at a monumental milestone stage", "Sequence & Logic"),
    ("dai-daiteki ni", "だいだいてきに", "ダイダイテキニ", "大々的に", "on a massive public splash", "Degree & Extent"),
    ("daikoubutsu toshite", "だいこうぶつとして", "ダイコウブツトシテ", "大好物として", "treasured as one's all-time favorite meal", "Food & Dining"),
    ("daimeishi toshite", "だいめいしとして", "ダイメイシトシテ", "代名詞として", "standing as the universal byword", "Social & Communication"),
    ("dai-senshu toshite", "だいせんしゅとして", "ダイセンシュトシテ", "大選手として", "holding stature of a sports legend", "People & Family"),
    ("dai-shizen no naka de", "だいしぜんのなかで", "ダイシゼンノナカデ", "大自然の中で", "cradled within vast Mother Nature", "Travel & Places"),
    ("daitan ni mo", "だいたんにも", "ダイタンニモ", "大胆にも", "boldly and cheekily dare to", "Manner & State"),
    ("danzen yuuri ni", "だんぜんゆうりに", "ダンゼンユウリニ", "断然有利に", "holding decisively upper hand", "Condition & Logic"),
    ("dashin shite", "だしんして", "ダシンシテ", "打診して", "sounding out discreetly", "Social & Communication"),
    ("dekiru dake", "できるだけ", "デキルダケ", "出来るだけ", "as much as humanly possible", "Degree & Extent"),
    ("dekiru kagiri", "できるかぎり", "デキルカギリ", "出来る限り", "to the utmost limits of ability", "Degree & Extent"),
    ("dekitate no uchi ni", "できたてのうちに", "デキタテノウチニ", "出来立てのうちに", "while piping fresh out of the pan", "Food & Dining"),
    ("denkousekka no hayasa de", "でんこうせっかのはやさで", "デンコウセッカノハヤサデ", "電光石火の速さで", "at lightning-flash speed", "Speed & Time"),
    ("densen o fusegu tame", "でんせんをふせぐため", "デンセンヲフセグタメ", "伝染を防ぐため", "in order to curb contagion", "Safety & Health"),
    ("dokkyari to", "どっかりと", "ドッカリト", "どっかりと", "plumping down heavily in chair", "Manner & State"),
    ("doko kara tomo naku", "どこからともなく", "ドコカラトモナク", "何処からともなく", "out of nowhere from thin air", "Places & Spatial"),
    ("doko made mo", "どこまでも", "ドコマデモ", "何処までも", "to the ends of the earth / endlessly", "Degree & Extent"),
    ("dokuji no shiten de", "どくじのしてんで", "ドクジノシテンデ", "独自の視点で", "through a uniquely fresh lens", "Social & Communication"),
    ("doryoku no ketsujitsu toshite", "どりょくのけつじつとして", "ドリョクノケツジツトシテ", "努力の結実として", "as the sweet fruit of hard work", "Condition & Logic"),

    # E
    ("eikyuu ni", "えいきゅうに", "エイキュウニ", "永久に", "eternally and perpetually", "Speed & Time"),
    ("ekiteki na tenkai de", "えきてきなてんかいで", "エキテキナテンカイデ", "劇的な展開で", "in a thrilling dramatic twist", "Condition & Logic"),
    ("enman-taisha de", "えんまんたいしゃで", "エンマンタイシャデ", "円満退社で", "leaving on warmest mutual terms", "Social & Communication"),
    ("enshou o osaeru tame", "えんしょうをおさえるため", "エンショウヲオサエルタメ", "炎症を抑えるため", "to soothe and heal inflammation", "Safety & Health"),
    ("enzetsu-chuu ni", "えんぜつちゅうに", "エンゼツチュウニ", "演説中に", "in the midst of public address", "Social & Communication"),
    ("eri-sugutte", "えりすぐって", "エリスグッテ", "選りすぐって", "cherry-picking only the best", "Manner & State"),

    # F
    ("fuan o kakaete", "ふあんをかかえて", "フアンヲカカエテ", "不安を抱えて", "shouldering heavy worries", "Feelings & Mood"),
    ("fubyoudou o tadashi", "ふびょうどうをただし", "フビョウドウヲタダシ", "不平等を正し", "rectifying injustice squarely", "Social & Communication"),
    ("fuchuui ni mo", "ふちゅういにも", "フチュウイニモ", "不注意にも", "inadvertently and carelessly", "Manner & State"),
    ("fukami o mashite", "ふかみをまして", "フカミヲマシテ", "深みを増して", "gaining layered soulful depth", "Degree & Extent"),
    ("fukitsu na yokan toshite", "ふきつなよかんとして", "フキツナヨカントシテ", "不吉な予感として", "as a sinister foreboding omen", "Feelings & Mood"),
    ("fukure-agatte", "ふくれあがって", "フクレアガッテ", "膨れ上がって", "swelling to immense proportions", "Degree & Quantity"),
    ("funiki ni nomarete", "ふんいきにのまれて", "フンイキニノマレテ", "雰囲気に呑まれて", "swept up in the prevailing vibe", "Feelings & Mood"),
    ("furari to", "ふらりと", "フラリト", "ふらりと", "wandering in casually unannounced", "Speed & Time"),
    ("furu-supiido de", "ふるすぴーどで", "フルスピードデ", "全速力で", "charging full throttle forward", "Speed & Time"),
    ("fusa-fusa to shita te de", "ふさふさとしたてで", "フサフサトシタテデ", "ふさふさとした手で", "with bushy furry soft paws", "Appearance & Style"),
    ("fusei o yurusazu", "ふせいをゆるさず", "フセイヲユルサズ", "不正を許さず", "intolerant of corruption or cheating", "Manner & State"),
    ("fushigi sou ni", "ふしぎそうに", "フシギソウニ", "不思議そうに", "looking on with puzzled wonder", "Feelings & Mood"),
    ("futsuu no koto toshite", "ふつうのこととして", "フツウノコトトシテ", "普通のこととして", "treating as everyday matter of fact", "Condition & Logic"),
    ("fuzei tappuri ni", "ふぜいたっぷりに", "フゼイタップリニ", "風情たっぷりに", "dripping with rich poetic taste", "Appearance & Style"),

    # G
    ("gai-teki ni", "がいてきに", "ガイテキニ", "外的に", "from external outer forces", "Condition & Logic"),
    ("gakumon no ue de", "がくもんのうえで", "ガクモンノウエデ", "学問の上で", "strictly within academic theory", "Condition & Logic"),
    ("ganban o kudaki", "がんばんをくだき", "ガンバンヲクダキ", "岩盤を砕き", "blasting through solid bedrock", "Manner & State"),
    ("ganjou ni kagi o kake", "がんじょうにかぎをかけ", "ガンジョウニカギヲカケ", "頑丈に鍵を掛け", "locking solidly with heavy deadbolts", "Safety & Health"),
    ("gara-gara no densha de", "がらがらのでんしゃで", "ガラガラノデンシャデ", "ガラガラの電車で", "on an empty train with seats to spare", "Travel & Places"),
    ("gasa-gasa to oto o tate", "がさがさとおとをたて", "ガサガサトオトヲタテ", "ガサガサと音を立て", "rustling loudly among dry stalks", "Onomatopoeia & Mimetic"),
    ("geijutsu no kanten kara", "げいじゅつのかんてんから", "ゲイジュツノカンテンカラ", "芸術の観点から", "viewed from artistic viewpoint", "Social & Communication"),
    ("gekisen o kachinuki", "げきせんをかちぬき", "ゲキセンヲカチヌキ", "激戦を勝ち抜き", "emerging triumphant from fierce contest", "Condition & Logic"),
    ("genkaku na shinsa de", "げんかくなしんさで", "ゲンカクナシンサデ", "厳格な審査で", "under rigorous stringent scrutiny", "Manner & State"),
    ("genshou-teki na sekai de", "げんしょうてきなせかいで", "ゲンショウテキナセカイデ", "幻想的な世界で", "within an enchanted fairytale realm", "Places & Spatial"),
    ("gikochinaku waratte", "ぎこちなくわらって", "ギコチナクワラッテ", "ぎこちなく笑って", "smiling with nervous stiffness", "Social & Communication"),
    ("gouin ni oshikiri", "ごういんにおしきり", "ゴウインニオシキリ", "強引に押し切り", "steamrolling past all opposition", "Manner & State"),
    ("goutei ni sunde", "ごうていにすんで", "ゴウテイニスンデ", "豪邸に住んで", "residing in luxury palatial splendor", "Home & Living"),
    ("gunshu o kakitsuwake", "ぐんしゅうをかきわけて", "グンシュウヲカキワケテ", "群衆を掻き分けて", "pushing through packed festival crowd", "Travel & Places"),
    ("gutto koraete", "ぐっとこらえて", "グットコラエテ", "ぐっと堪えて", "biting lip and holding tears back", "Feelings & Mood"),

    # H
    ("hachikire-n bakari no ai", "はちきれんばかりのあいで", "ハチキレンバカリノアイデ", "はち切れんばかりの愛で", "with love bursting at seams", "Feelings & Mood"),
    ("hageshiku yurete", "はげしくゆれて", "ハゲシクユレテ", "激しく揺れて", "rocking violently back and forth", "Nature & Climate"),
    ("haigo o keikai shite", "はいごをけいかいして", "ハイゴヲケイカイシテ", "背後を警戒して", "warily watching one's back", "Safety & Health"),
    ("hakken shite sugu", "はっけんしてすぐ", "ハッケンシテスグ", "発見して直ぐ", "instantly upon spotting discovery", "Speed & Time"),
    ("hakuryoku man-ten no e", "はくりょくまんてんのえで", "ハクリョクマンテンノエデ", "迫力満点の絵で", "with breathlessly vivid canvas artwork", "Appearance & Style"),
    ("hamigaki o shikkari", "はみがきをしっかりと", "ハミガキヲシッカリト", "歯磨きをしっかりと", "brushing thoroughly twice daily", "Safety & Health"),
    ("hanayaka na machi de", "はなやかなまちで", "ハナヤカナマチデ", "華やかな街で", "in glittering festive downtown", "Travel & Places"),
    ("han-kyou-teki ni sakebi", "はんきょうてきにさけび", "ハンキョウテキニサケビ", "半狂乱に叫び", "crying out in wild hysteria", "Social & Communication"),
    ("han-taigawa kara", "はんたいがわから", "ハンタイガワカラ", "反対側から", "from directly across the other side", "Places & Spatial"),
    ("hantsuki-kan de", "はんつきかんで", "ハンツキカンデ", "半月間で", "over the course of two whole weeks", "Speed & Time"),
    ("haritsumeta kuuki de", "はりつめたくうきで", "ハリツメタクウキデ", "張り詰めた空気で", "amid palpably tense electric silence", "Feelings & Mood"),
    ("hassei o yobou shite", "はっせいをよぼうして", "ハッセイヲヨボウシテ", "発生を予防して", "proactively preventing occurrence", "Safety & Health"),
    ("hatten o inotte", "はってんをいのって", "ハッテンヲイノッテ", "発展を祈って", "praying for booming future growth", "Condition & Logic"),
    ("hayame ni koudou", "はやめにこうどうして", "ハヤメニコウドウシテ", "早めに行動して", "taking swift preemptive action early", "Speed & Time"),
    ("heibon o aishite", "へいぼんをあいして", "ヘイボンヲアイシテ", "平凡を愛して", "cherishing the sweet simple ordinary", "Feelings & Mood"),
    ("heizen to shite", "へいぜんとして", "ヘイゼントシテ", "平然として", "remaining cool as cucumber", "Manner & State"),
    ("hendou ni taete", "へんどうにたえて", "ヘンドウニタエテ", "変動に耐えて", "weathering volatile market waves", "Condition & Logic"),
    ("hidoku omoide ni nokotte", "ひどくおもいでにのこって", "ヒドクオモイデニノコッテ", "酷く思い出に残って", "etched hauntingly into memory", "Feelings & Mood"),
    ("hifu ga uruou", "ひふがうるおうように", "ヒフガウルオウヨウニ", "肌が潤うように", "so that skin becomes supple and dewy", "Appearance & Style"),
    ("hikaku shite mite", "ひかくしてみて", "ヒカクシテミテ", "比較してみて", "drawing side-by-side comparison", "Sequence & Logic"),
    ("hikkuri-kaette korobu", "ひっくりかえってころび", "ヒックリカエッテコロビ", "ひっくり返って転び", "tumbling head over heels", "Manner & State"),
    ("hisshi no omoi de", "ひっしのおもいで", "ヒッシノオモイデ", "必死の思いで", "with desperate yearning determination", "Feelings & Mood"),
    ("hitasura shinjite", "ひたすらしんじて", "ヒタスラシンジテ", "ひたすら信じて", "believing with unwavering faith", "Feelings & Mood"),
    ("hitori-de ni toke", "ひとりでにとき", "ヒトリデニトケ", "独りでに解け", "melting away on its own accord", "Condition & Logic"),
    ("hitosuji no hikari de", "ひとすじのひかりで", "ヒトスジノヒカリデ", "一筋の光で", "illuminated by a single ray of hope", "Feelings & Mood"),
    ("hodo-yoi ondo de", "ほどよいおんどで", "ホドヨイオンードデ", "程よい温度で", "at an exquisitely pleasant temperature", "Nature & Climate"),
    ("hoka-hoka no gohan de", "ほかほかのおごはんとお", "ホカホカノゴハンデ", "ほかほかのご飯で", "with piping steaming fresh rice", "Food & Dining"),
    ("hono-bono to shita heya", "ほのぼのとしたへやで", "ホノボノトシタヘヤデ", "ほのぼのとした部屋で", "in a comfortably heartwarming room", "Home & Living"),
    ("honmono o miwakeru", "ほんものをみわけるように", "ホンモノヲミワケルヨウニ", "本物を見分けるように", "discerning true gold from copper", "Condition & Logic"),
    ("horonigaku omoide", "ほろにがくおもいでを", "ホロニガクオモイデヲ", "ほろ苦く思い出を", "recalling with wistful nostalgia", "Feelings & Mood"),
    ("hoshu-teki na kangae de", "ほしゅてきなのかんがえで", "ホシュテキナカンガエデ", "保守的な考えで", "holding traditionally cautious view", "Condition & Logic"),
    ("hukakai na jiken toshite", "ふかかいなじけんとして", "フカカイナジケントシテ", "不可解な事件として", "as an unfathomable, chilling mystery", "Condition & Logic"),
    ("hyoujou-yutaka ni kataru", "ひょうじょうゆたかにかたる", "ヒョウジョウユタカニカタル", "表情豊かに語る", "speaking with animated lively eyes", "Social & Communication"),
]
