"""
Comprehensive JLPT N4 Master Vocabulary Dataset
Covers Nouns, Verbs, Adjectives, Adverbs, and Phrases
"""

NOUNS = [
    # N4 Nouns A-Z
    ("aida", "あいだ", "アイダ", "間", "interval / space / between", "Time & Space"),
    ("aisatsu", "あいさつ", "アイサツ", "挨拶", "greeting / address", "Society"),
    ("aji", "あじ", "アジ", "味", "flavor / taste", "Food & Dining"),
    ("akachan", "あかちゃん", "アカチャン", "赤ちゃん", "baby / infant", "People & Family"),
    ("annai", "あんない", "アンナイ", "案内", "guidance / information / tour", "Travel & Places"),
    ("anshin", "あんしん", "アンシン", "安心", "peace of mind / relief", "Emotions"),
    ("anzen", "あんぜん", "アンゼン", "安全", "safety / security", "Society"),
    ("arubaito", "あるばいと", "アルバイト", "アルバイト", "part-time job", "Work & Study"),
    ("asagohan", "あさごはん", "アサゴハン", "朝ご飯", "breakfast", "Food & Dining"),
    ("ashi", "あし", "アシ", "足", "foot / leg", "Body & Health"),
    ("atama", "あたま", "アタマ", "頭", "head / mind", "Body & Health"),
    ("baai", "ばあい", "バアイ", "場合", "case / situation / circumstance", "Abstract"),
    ("bangou", "ばんごう", "バンゴウ", "番号", "number / series", "General"),
    ("bangohan", "ばんごはん", "バンゴハン", "晩ご飯", "dinner / evening meal", "Food & Dining"),
    ("basho", "ばしょ", "バショ", "場所", "place / location", "Travel & Places"),
    ("bijutsukan", "びじゅつかん", "ビジュツカン", "美術館", "art museum / gallery", "Culture & Arts"),
    ("bikkuri", "びっくり", "ビックリ", "吃驚", "surprise / astonishment", "Emotions"),
    ("biru", "びる", "ビル", "ビル", "building / high-rise", "Travel & Places"),
    ("boushi", "ぼうし", "ボウシ", "帽子", "hat / cap", "Clothing"),
    ("bouenkyou", "ぼうえんきょう", "ボウエンキョウ", "望遠鏡", "telescope", "Science"),
    ("bunka", "ぶんか", "ブンカ", "文化", "culture / civilization", "Culture & Arts"),
    ("bungaku", "ぶんがく", "ブンガク", "文学", "literature", "Culture & Arts"),
    ("bunpou", "ぶんぽう", "ブンポウ", "文法", "grammar", "Work & Study"),
    ("bunshou", "ぶんしょう", "ブンショウ", "文章", "sentence / composition / writing", "Work & Study"),
    ("buta-niku", "ぶたにく", "ブタニク", "豚肉", "pork meat", "Food & Dining"),
    ("byouin", "びょういん", "ビョウイン", "病院", "hospital / clinic", "Body & Health"),
    ("byouki", "びょうき", "ビョウキ", "病気", "illness / disease / sickness", "Body & Health"),
    ("chawan", "ちゃわん", "チャワン", "茶碗", "rice bowl / tea cup", "Home & Daily"),
    ("chichi", "ちち", "チチ", "父", "father (one's own)", "People & Family"),
    ("chikadousha", "ちかどうしゃ", "チカドウシャ", "地下自動車", "underground transit car", "Travel & Places"),
    ("chiketsu", "ちけつ", "チケツ", "地下鉄", "subway / underground train", "Travel & Places"),
    ("chikara", "ちから", "チカラ", "力", "power / strength / ability", "Abstract"),
    ("chiri", "ちり", "チリ", "地理", "geography", "Work & Study"),
    ("chizu", "ちず", "チズ", "地図", "map / atlas", "Travel & Places"),
    ("choushi", "ちょうし", "チョウシ", "調子", "condition / state / tune", "Abstract"),
    ("chousetsu", "ちょうせつ", "チョウセツ", "調節", "regulation / adjustment", "Abstract"),
    ("chuui", "ちゅうい", "チュウイ", "注意", "caution / attention / warning", "Society"),
    ("chuumon", "ちゅうもん", "チュウモン", "注文", "order (food, goods)", "Food & Dining"),
    ("chuushajou", "ちゅうしゃじょう", "チュウシャジョウ", "駐車場", "parking lot", "Travel & Places"),
    ("daigaku", "だいがく", "ダイガク", "大学", "university / college", "Work & Study"),
    ("daigakuin", "だいがくいん", "ダイガクイン", "大学院", "graduate school", "Work & Study"),
    ("daiji", "だいじ", "ダイジ", "大事", "importance / serious matter", "Abstract"),
    ("daidokoro", "だいどころ", "ダイドコロ", "台所", "kitchen", "Home & Daily"),
    ("danbou", "だんぼう", "ダンボウ", "暖房", "indoor heating", "Home & Daily"),
    ("dansei", "だんせい", "ダンセイ", "男性", "man / male", "People & Family"),
    ("densha", "でんしゃ", "デンシャ", "電車", "electric train", "Travel & Places"),
    ("denki", "でんき", "デンキ", "電気", "electricity / light", "Home & Daily"),
    ("denwa", "でんわ", "デンワ", "電話", "telephone / phone call", "Home & Daily"),
    ("dento", "でんとう", "デントウ", "伝統", "tradition / heritage", "Culture & Arts"),
    ("doubutsu", "どうぶつ", "ドウブツ", "動物", "animal / living creature", "Nature & Animals"),
    ("doubutsuen", "どうぶつえん", "ドウブツエン", "動物園", "zoo", "Nature & Animals"),
    ("dougu", "どうぐ", "ドウグ", "道具", "tool / implement / instrument", "Home & Daily"),
    ("dokusho", "どくしょ", "ドクショ", "読書", "reading books", "Culture & Arts"),
    ("douryo", "どうりょう", "ドウリョウ", "同僚", "work colleague / coworker", "Work & Study"),
    ("doragon", "どらごん", "ドラゴン", "竜", "dragon / mythical beast", "Culture & Arts"),
    ("doryoku", "どりょく", "ドリョク", "努力", "effort / great exertion", "Abstract"),
    ("eiga", "えいが", "エイガ", "映画", "movie / cinema film", "Culture & Arts"),
    ("eigakan", "えいがかん", "エイガカン", "映画館", "movie theater / cinema", "Culture & Arts"),
    ("eigo", "えいご", "エイゴ", "英語", "English language", "Work & Study"),
    ("ekimae", "えきまえ", "エキマエ", "駅前", "in front of the station", "Travel & Places"),
    ("enikki", "えにっき", "エニッキ", "絵日記", "picture diary", "Culture & Arts"),
    ("enjin", "えんじん", "エンジン", "エンジン", "mechanical engine", "Technology"),
    ("ensoku", "えんそく", "エンソク", "遠足", "school excursion / picnic outing", "Travel & Places"),
    ("fuku", "ふく", "フク", "服", "clothes / clothing / garment", "Clothing"),
    ("fukuro", "ふくろ", "フクロ", "袋", "bag / sack / pouch", "Home & Daily"),
    ("fukushuu", "ふくしゅう", "フクシュウ", "復習", "review of study material", "Work & Study"),
    ("fune", "ふね", "フネ", "船", "ship / boat / vessel", "Travel & Places"),
    ("furigana", "ふりがな", "フリガナ", "振り仮名", "ruby kana pronunciation guide", "Work & Study"),
    ("futon", "ふとん", "フトン", "布団", "Japanese bedding mattress / futon", "Home & Daily"),
    ("fuyuyasumi", "ふゆやすみ", "フユヤスミ", "冬休み", "winter vacation / holidays", "Time & Space"),
    ("gaikoku", "がいこく", "ガイコク", "外国", "foreign country", "Travel & Places"),
    ("gaikokujin", "がいこくじん", "ガイコクジン", "外国人", "foreign national / foreigner", "People & Family"),
    ("gakusei", "がくせい", "ガクセイ", "学生", "student", "Work & Study"),
    ("gakkou", "がっこう", "ガッコウ", "学校", "school institution", "Work & Study"),
    ("ginko", "ぎんこう", "ギンコウ", "銀行", "bank / financial institution", "Society"),
    ("gomi", "ごみ", "ゴミ", "塵", "garbage / rubbish / trash", "Home & Daily"),
    ("gomibako", "ごみばこ", "ゴミバコ", "ゴミ箱", "trash can / dustbin", "Home & Daily"),
    ("goshujin", "ごしゅじん", "ゴシュジン", "ご主人", "husband (someone else's)", "People & Family"),
    ("haisha", "はいしゃ", "ハイシャ", "歯医者", "dentist clinic", "Body & Health"),
    ("hanami", "はなみ", "ハナミ", "花見", "cherry blossom viewing", "Culture & Arts"),
    ("hanashi", "はなし", "ハナシ", "話", "talk / story / conversation", "Communication"),
    ("hanbun", "はんぶん", "ハンブン", "半分", "half / fifty percent", "Abstract"),
    ("hankou", "はんこう", "ハンコウ", "判子", "personal name seal / stamp", "Society"),
    ("haru", "はる", "ハル", "春", "spring season", "Time & Space"),
    ("hashi", "はし", "ハシ", "箸", "chopsticks", "Food & Dining"),
    ("hashi_bridge", "はし", "ハシ", "橋", "bridge (Lighthouse 橋)", "Travel & Places"),
    ("hatake", "はたけ", "ハタケ", "畑", "cultivated crop field", "Nature & Animals"),
    ("heya", "へや", "ヘヤ", "部屋", "room / chamber", "Home & Daily"),
    ("hikouki", "ひこうき", "ヒコウキ", "飛行機", "airplane / aircraft", "Travel & Places"),
    ("hirusumi", "ひるやすみ", "ヒルヤスミ", "昼休み", "noon lunch break", "Time & Space"),
    ("hitorigurashi", "ひとりぐらし", "ヒトリグラシ", "一人暮らし", "living alone / single life", "Society"),
    ("hizuke", "ひづけ", "ヒヅケ", "日付", "calendar date", "Time & Space"),
    ("hondana", "ほんだな", "ホンダナ", "本棚", "bookshelf / bookcase", "Home & Daily"),
    ("hontou", "ほんとう", "ホントウ", "本当", "truth / reality / fact", "Abstract"),
    ("honya", "ほんや", "ホンヤ", "本屋", "bookstore / bookshop", "Travel & Places"),
    ("hoshou", "ほしょう", "ホショウ", "保証", "guarantee / warranty", "Society"),
    ("hyou", "ひょう", "ヒョウ", "表", "table / chart / list", "Work & Study"),
    ("ichiba", "いちば", "イチバ", "市場", "open marketplace", "Travel & Places"),
    ("iken", "いけん", "イケン", "意見", "personal opinion / viewpoint", "Communication"),
    ("inaka", "いなか", "イナカ", "田舎", "countryside / rural hometown", "Travel & Places"),
    ("inori", "いのり", "イノリ", "祈り", "prayer / wish", "Culture & Arts"),
    ("isha", "いしゃ", "イシャ", "医者", "medical doctor / physician", "Body & Health"),
    ("itoko", "いとこ", "イトコ", "従兄弟", "cousin relative", "People & Family"),
    ("jiko", "じこ", "ジコ", "事故", "traffic accident / mishap", "Society"),
    ("jimusho", "じむしょ", "ジムショ", "事務所", "business office", "Work & Study"),
    ("jinja", "じんじゃ", "ジンジャ", "神社", "Shinto shrine", "Culture & Arts"),
    ("jinkou", "じんこう", "ジンコウ", "人口", "population count", "Society"),
    ("jisho", "じしょ", "ジショ", "辞書", "lexicon dictionary", "Work & Study"),
    ("jishin", "じしん", "ジシン", "地震", "earthquake tremor", "Nature & Animals"),
    ("jitensha", "じてんしゃ", "ジテンシャ", "自転車", "bicycle / bike", "Travel & Places"),
    ("jidouhanbaiki", "じどうはんばいき", "ジドウハンバイキ", "自動販売機", "vending machine", "Travel & Places"),
    ("jiyuu", "じゆう", "ジユウ", "自由", "freedom / liberty", "Abstract"),
    ("josei", "じょせい", "ジョセイ", "女性", "woman / female", "People & Family"),
    ("jugyou", "じゅぎょう", "ジュギョウ", "授業", "class / academic lesson", "Work & Study"),
    ("junbi", "じゅんび", "ジュンビ", "準備", "preparation / arrangement", "Abstract"),
    ("juusho", "じゅうしょ", "ジュウショ", "住所", "residential address", "Society"),
    ("kaigi", "かいぎ", "カイギ", "会議", "business meeting / conference", "Work & Study"),
    ("kaigishitsu", "かいぎしつ", "カイギシツ", "会議室", "conference meeting room", "Work & Study"),
    ("kaimono", "かいもの", "カイモノ", "買い物", "shopping / purchases", "Society"),
    ("kaisai", "かいさい", "カイサイ", "開催", "holding an event / hosting", "Society"),
    ("kaisha", "かいしゃ", "カイシャ", "会社", "company / firm / enterprise", "Work & Study"),
    ("kaishain", "かいしゃいん", "カイシャイン", "会社員", "company employee / office worker", "Work & Study"),
    ("kamisama", "かみさま", "カミサマ", "神様", "deity / God", "Culture & Arts"),
    ("kanji", "かんじ", "カンジ", "漢字", "Chinese characters (Kanji)", "Work & Study"),
    ("kankou", "かんこう", "カンコウ", "観光", "sightseeing / tourism", "Travel & Places"),
    ("kanrinin", "かんりにん", "カンリニン", "管理人", "building manager / caretaker", "People & Family"),
    ("kare", "かれ", "カレ", "彼", "he / boyfriend", "People & Family"),
    ("kanojo", "かのじょ", "カノジョ", "彼女", "she / girlfriend", "People & Family"),
    ("kasa", "かさ", "カサ", "傘", "umbrella", "Home & Daily"),
    ("kazoku", "かぞく", "カゾク", "家族", "family members", "People & Family"),
    ("keiken", "けいけん", "ケイケン", "経験", "personal experience", "Abstract"),
    ("keikaku", "けいかく", "ケイカク", "計画", "strategic plan / project", "Work & Study"),
    ("keizai", "けいざい", "ケイザイ", "経済", "economics / economy", "Society"),
    ("kega", "けが", "ケガ", "怪我", "physical injury / wound", "Body & Health"),
    ("kekkon", "けっこん", "ケッコン", "結婚", "marriage / wedding", "Society"),
    ("keshiki", "けしき", "ケシキ", "景色", "scenery / landscape / view", "Travel & Places"),
    ("kisetsu", "きせつ", "キセツ", "季節", "annual season", "Time & Space"),
    ("kibou", "きぼう", "キボウ", "希望", "hope / aspiration / wish", "Abstract"),
    ("kikan", "きかん", "キカン", "期間", "term / duration period", "Time & Space"),
    ("kikai", "きかい", "キカイ", "機械", "machine / mechanical device", "Technology"),
    ("kikai_opp", "きかい", "キカイ", "機会", "opportunity / auspicious chance", "Abstract"),
    ("kinshi", "きんし", "キンシ", "禁止", "prohibition / strict ban", "Society"),
    ("kinjo", "きんじょ", "キンジョ", "近所", "neighborhood / vicinity", "Society"),
    ("kinnen", "きんねん", "キンネン", "近年", "in recent years", "Time & Space"),
    ("kitte", "きって", "キッテ", "切手", "postage stamp", "Home & Daily"),
    ("kippu", "きっぷ", "キップ", "切符", "ticket (train, transit)", "Travel & Places"),
    ("kissa-ten", "きっさてん", "キッサテン", "喫茶店", "traditional Japanese coffee shop", "Food & Dining"),
    ("kodomo", "こども", "コドモ", "子供", "child / children", "People & Family"),
    ("kouen", "こうえん", "コウエン", "公園", "public park", "Travel & Places"),
    ("koujou", "こうじょう", "コウジョウ", "工場", "manufacturing factory / plant", "Work & Study"),
    ("koukou", "こうこう", "コウコウ", "高校", "senior high school", "Work & Study"),
    ("koukousei", "こうこうせい", "コウコウセイ", "高校生", "high school student", "Work & Study"),
    ("kousaten", "こうさてん", "コウサテン", "交差点", "street intersection", "Travel & Places"),
    ("koutsuu", "こうつう", "コウツウ", "交通", "traffic / transport / communication", "Travel & Places"),
    ("kuni", "くに", "クニ", "国", "country / state / home nation", "Society"),
    ("kuruma", "くるま", "クルマ", "車", "car / vehicle / automobile", "Travel & Places"),
    ("kyaku", "きゃく", "キャク", "客", "guest / customer / client", "Society"),
    ("kyuukou", "きゅうこう", "キュウコウ", "急行", "express rapid train", "Travel & Places"),
    ("kyuuryou", "きゅうりょう", "キュウリョウ", "給料", "salary / wage payment", "Work & Study"),
    ("kyoumi", "きょうみ", "キョウミ", "興味", "intellectual interest / curiosity", "Abstract"),
    ("machi", "まち", "マチ", "町", "town / city block", "Travel & Places"),
    ("mannaka", "まんなか", "マンナカ", "真ん中", "dead center / middle", "Time & Space"),
    ("matsuri", "まつり", "マツリ", "祭り", "traditional Japanese festival", "Culture & Arts"),
    ("meishi", "めいし", "メイシ", "名刺", "business card", "Work & Study"),
    ("midori", "みどり", "ミドリ", "緑", "green color / greenery foliage", "Nature & Animals"),
    ("minato", "みなと", "ミナト", "港", "harbor / shipping port", "Travel & Places"),
    ("mise", "みせ", "ミセ", "店", "shop / store / restaurant", "Society"),
    ("mizuumi", "みずうみ", "ミズウミ", "湖", "freshwater lake", "Nature & Animals"),
    ("mokuteki", "もくてき", "モクテキ", "目的", "purpose / goal / objective", "Abstract"),
    ("mon", "もん", "モン", "門", "gate / monumental entrance", "Travel & Places"),
    ("mondai", "もんだい", "モンダイ", "問題", "problem / issue / question", "Abstract"),
    ("mono", "もの", "モノ", "物", "tangible thing / object", "General"),
    ("moratta mono", "もらいましたもの", "モライマシタモノ", "貰った物", "received gifts", "Culture & Arts"),
    ("mura", "むら", "ムラ", "村", "rural village", "Travel & Places"),
    ("natsu", "なつ", "ナツ", "夏", "summer season", "Time & Space"),
    ("natsuyasumi", "なつやすみ", "ナツヤスミ", "夏休み", "summer school vacation", "Time & Space"),
    ("nedan", "ねだん", "ネダン", "値段", "monetary price / cost", "Society"),
    ("netsu", "ねつ", "ネツ", "熱", "fever / physical heat", "Body & Health"),
    ("nihonshu", "にほんしゅ", "ニホンシュ", "日本酒", "Japanese rice wine (Sake)", "Food & Dining"),
    ("nikki", "にっき", "ニッキ", "日記", "personal daily diary / journal", "Culture & Arts"),
    ("nimotsu", "にもつ", "ニモツ", "荷物", "luggage / baggage / parcel", "Travel & Places"),
    ("ningyou", "にんぎょう", "ニンギョウ", "人形", "doll / puppet / figurine", "Culture & Arts"),
    ("nouka", "のうか", "ノウカ", "農家", "farming household / farmer", "Society"),
    ("norikae", "のりかえ", "ノリカエ", "乗り換え", "transit transfer / switching trains", "Travel & Places"),
    ("norimono", "のりもの", "ノリモノ", "乗り物", "vehicle / transit ride", "Travel & Places"),
    ("obasan", "おばさん", "オバサン", "伯母さん", "aunt / middle-aged lady", "People & Family"),
    ("ojisan", "おじさん", "オジサン", "伯父さん", "uncle / middle-aged man", "People & Family"),
    ("okane", "おかね", "オカネ", "お金", "money / currency", "Society"),
    ("okashi", "おかし", "オカシ", "お菓子", "sweets / confectionery / snacks", "Food & Dining"),
    ("omiyage", "おみやげ", "オミヤゲ", "お土産", "souvenir / travel present", "Travel & Places"),
    ("omatsuri", "おまつり", "オマツリ", "お祭り", "festival event", "Culture & Arts"),
    ("omoide", "おもいで", "オモイデ", "思い出", "cherished memory / recollection", "Emotions"),
    ("omote", "おもて", "オモテ", "表", "front surface / face", "Time & Space"),
    ("onsen", "おんせん", "オンセン", "温泉", "natural hot spring", "Travel & Places"),
    ("oto", "おと", "オト", "音", "auditory sound / noise", "Nature & Animals"),
    ("otona", "おとな", "オトナ", "大人", "adult / grown-up", "People & Family"),
    ("reizouko", "れいぞうこ", "レイゾウコ", "冷蔵庫", "refrigerator / fridge", "Home & Daily"),
    ("rekishi", "れきし", "レキシ", "歴史", "chronological history", "Culture & Arts"),
    ("renshuu", "れんしゅう", "レンシュウ", "練習", "practice session / drill", "Work & Study"),
    ("renraku", "れんらく", "レンラク", "連絡", "contact / liaison / message", "Communication"),
    ("ryokou", "りょこう", "リョコウ", "旅行", "travel / voyage / journey", "Travel & Places"),
    ("ryoushin", "りょうしん", "リョウシン", "両親", "parents (mother & father)", "People & Family"),
    ("ryouri", "りょうり", "リョウリ", "料理", "cooking / cuisine / culinary dish", "Food & Dining"),
    ("ryokan", "りょかん", "リョカン", "旅館", "traditional Japanese inn", "Travel & Places"),
    ("sakura", "さくら", "サクラ", "桜", "cherry blossom flowers", "Nature & Animals"),
    ("sakubun", "さくぶん", "サクブン", "作文", "essay / school composition", "Work & Study"),
    ("saifu", "さいふ", "サイフ", "財布", "money wallet / purse", "Home & Daily"),
    ("saigo", "さいご", "サイゴ", "最後", "the very end / last", "Time & Space"),
    ("saisho", "さいしょ", "サイショ", "最初", "the very beginning / first", "Time & Space"),
    ("sankaryou", "さんかりょう", "サンカリョウ", "参加料", "participation entry fee", "Society"),
    ("seikatsu", "せいかつ", "セイカツ", "生活", "daily living / lifestyle", "Home & Daily"),
    ("seiseki", "せいせき", "セイセキ", "成績", "academic grades / performance", "Work & Study"),
    ("seijin", "せいじん", "セイジン", "成人", "legal adult", "Society"),
    ("sekaichi", "せかいち", "セカイチ", "世界一", "number one in the whole world", "Abstract"),
    ("seki", "せき", "セキ", "席", "seat / assigned place", "Travel & Places"),
    ("senpai", "せんぱい", "センパイ", "先輩", "senior colleague or student", "People & Family"),
    ("senshu", "せんしゅ", "センシュ", "選手", "sports athlete / player", "People & Family"),
    ("sentaku", "せんたく", "センタク", "洗濯", "doing laundry", "Home & Daily"),
    ("sentakuki", "せんたくき", "センタクキ", "洗濯機", "washing machine", "Home & Daily"),
    ("setsumei", "せつめい", "セツメイ", "説明", "explanation / clarification", "Communication"),
    ("setsumeisho", "せつめいしょ", "セツメイショ", "説明書", "manual instructions booklet", "Work & Study"),
    ("shakai", "しゃかい", "シャカイ", "社会", "human society / public world", "Society"),
    ("shashin", "しゃしん", "シャシン", "写真", "photograph / picture", "Culture & Arts"),
    ("shiai", "しあい", "シアイ", "試合", "sports match / contest / game", "Society"),
    ("shigoto", "しごと", "シゴト", "仕事", "employment / job / work", "Work & Study"),
    ("shiken", "しけん", "シケン", "試験", "academic exam / test", "Work & Study"),
    ("shikata", "しかた", "シカタ", "仕方", "way of doing / method", "Abstract"),
    ("shimai", "しまい", "シマイ", "姉妹", "sisters", "People & Family"),
    ("shimin", "しみん", "シミン", "市民", "citizens / townspeople", "Society"),
    ("shinamono", "しなもの", "シナモノ", "品物", "merchandise goods / items", "Society"),
    ("shingou", "しんごう", "シンゴウ", "信号", "traffic lights / signaling", "Travel & Places"),
    ("shinkansen", "しんかんせん", "シンカンセン", "新幹線", "bullet train (Shinkansen)", "Travel & Places"),
    ("shiryou", "しりょう", "シリョウ", "資料", "documents / handout materials", "Work & Study"),
    ("shitsumon", "しつもん", "シツモン", "質問", "inquiry / question", "Communication"),
    ("shizen", "しぜん", "シゼン", "自然", "nature / natural environment", "Nature & Animals"),
    ("shokuji", "しょくじ", "ショクジ", "食事", "meal / dining", "Food & Dining"),
    ("shokudou", "しょくどう", "ショクドウ", "食堂", "dining hall / cafeteria", "Food & Dining"),
    ("shouryuu", "しょうりゅう", "ショウリュウ", "昇竜", "rising mythical dragon", "Culture & Arts"),
    ("shumi", "しゅみ", "シュミ", "趣味", "personal hobby / pastime", "Culture & Arts"),
    ("shuppatsu", "しゅっぱつ", "シュッパツ", "出発", "departure / setting out", "Travel & Places"),
    ("shusseki", "しゅっせき", "シュッセキ", "出席", "attendance / presence", "Work & Study"),
    ("souji", "そうじ", "ソウジ", "掃除", "cleaning / tidying up", "Home & Daily"),
    ("soudan", "そうだん", "ソウダン", "相談", "consultation / asking advice", "Communication"),
    ("sotsugyou", "そつぎょう", "ソツギョウ", "卒業", "graduation from school", "Work & Study"),
    ("suiei", "すいえい", "スイエイ", "水泳", "swimming sport", "Body & Health"),
    ("suizokukan", "すいぞくかん", "スイゾクカン", "水族館", "public aquarium", "Nature & Animals"),
    ("taikou", "たいこう", "タイコウ", "太鼓", "traditional Japanese Taiko drum", "Culture & Arts"),
    ("taishikan", "たいしかん", "タイシカン", "大使館", "foreign embassy", "Society"),
    ("taisetsu", "たいせつ", "タイセツ", "大切", "precious / important", "Abstract"),
    ("taiyou", "たいよう", "タイヨウ", "太陽", "the sun", "Nature & Animals"),
    ("tatemono", "たてもの", "タテモノ", "建物", "building / architecture", "Travel & Places"),
    ("tenki", "てんき", "テンキ", "天気", "weather conditions", "Nature & Animals"),
    ("tenrankai", "てんらんかい", "テンランカイ", "展覧会", "exhibition / gallery showcase", "Culture & Arts"),
    ("tesuto", "てすと", "テスト", "試験", "test / quiz", "Work & Study"),
    ("tochuu", "とちゅう", "トチュウ", "途中", "on the way / halfway through", "Time & Space"),
    ("tokkyuu", "とっきゅう", "トッキュウ", "特急", "limited express train", "Travel & Places"),
    ("tokoro", "ところ", "トコロ", "所", "place / spot / scene", "Travel & Places"),
    ("tomodachi", "ともだち", "トモダチ", "友達", "friend / companion", "People & Family"),
    ("tonari", "となり", "トナリ", "隣", "next-door neighbor / adjacent", "Time & Space"),
    ("toriniku", "とりにく", "トリニク", "鶏肉", "chicken poultry meat", "Food & Dining"),
    ("tsugou", "つごう", "ツゴウ", "都合", "convenience / schedule circumstances", "Abstract"),
    ("tsuki", "つき", "ツキ", "月", "moon / calendar month", "Nature & Animals"),
    ("undou", "うんどう", "ウンドウ", "運動", "physical exercise / workout", "Body & Health"),
    ("undoukai", "うんどうかい", "ウンドウカイ", "運動会", "school sports festival day", "Culture & Arts"),
    ("unten", "うんてん", "ウンテン", "運転", "driving a motor vehicle", "Travel & Places"),
    ("untenshu", "うんてんしゅ", "ウンテンシュ", "運転手", "professional driver", "People & Family"),
    ("yakusoku", "やくそく", "ヤクソク", "約束", "promise / appointment", "Communication"),
    ("yotei", "よてい", "ヨテイ", "予定", "plan / calendar schedule", "Work & Study"),
    ("yoyaku", "よやく", "ヨヤク", "予約", "reservation / advance booking", "Travel & Places"),
    ("yuugata", "ゆうがた", "ユウガタ", "夕方", "early evening / dusk", "Time & Space"),
    ("yuumeijin", "ゆうめいじん", "ユウメイジン", "有名人", "celebrity / famous person", "People & Family"),
    ("zangyou", "ざんぎょう", "ザンギョウ", "残業", "workplace overtime work", "Work & Study"),
    ("zasshi", "ざっし", "ザッシ", "雑誌", "printed magazine", "Culture & Arts"),
    ("zubon", "ずぼん", "ズボン", "ズボン", "trousers / pants", "Clothing")
]

VERBS = [
    # N4 Verbs
    ("annai suru", "あんないする", "アンナイスル", "案内する", "to guide / show around", "Irregular", "Travel & Places"),
    ("anshin suru", "あんしんする", "アンシンスル", "安心する", "to feel relieved / be reassured", "Irregular", "Emotions"),
    ("ayamaru", "あやまる", "アヤマル", "謝る", "to apologize / ask forgiveness", "Godan", "Communication"),
    ("atsumeru", "あつめる", "アツメル", "集める", "to collect / assemble / gather", "Ichidan", "Daily Life"),
    ("chuumon suru", "ちゅうもんする", "チュウモンスル", "注文する", "to order food or items", "Irregular", "Food & Dining"),
    ("chousetsu suru", "ちょうせつする", "チョウセツスル", "調節する", "to adjust / regulate", "Irregular", "Abstract"),
    ("dekakeru", "でかける", "デカケル", "出かける", "to depart / go out for leisure", "Ichidan", "Travel & Places"),
    ("enryo suru", "えんりょする", "エンリョスル", "遠慮する", "to hold back / hesitate / decline politely", "Irregular", "Social & Communication"),
    ("erabu", "えらぶ", "エラブ", "選ぶ", "to choose / select from options", "Godan", "Abstract"),
    ("fueru", "ふえる", "フエル", "増える", "to increase / multiply", "Ichidan", "Abstract"),
    ("fukushuu suru", "ふくしゅうする", "フクシュウスル", "復習する", "to review study material", "Irregular", "Work & Study"),
    ("furidasu", "ふりだす", "フリダス", "降り出す", "to start raining or snowing", "Godan", "Nature & Animals"),
    ("futoru", "ふとる", "フトル", "太る", "to gain weight / grow plump", "Godan", "Body & Health"),
    ("ganbaru", "がんばる", "ガンバル", "頑張る", "to persevere / do one's utmost best", "Godan", "Emotions"),
    ("gochisou suru", "ごちそうする", "ゴチソウスル", "ご馳走する", "to treat someone to a meal", "Irregular", "Food & Dining"),
    ("hajimeru", "はじめる", "ハジメル", "始める", "to begin / initiate something", "Ichidan", "Actions"),
    ("hakarau", "はからう", "ハカラウ", "計らう", "to arrange / manage thoughtfully", "Godan", "Social & Communication"),
    ("hakobu", "はこぶ", "ハコブ", "運ぶ", "to transport / carry luggage", "Godan", "Actions"),
    ("harau", "はらう", "ハラウ", "払う", "to pay money or attention", "Godan", "Society"),
    ("hiku", "ひく", "ヒク", "引く", "to pull / draw / catch a cold", "Godan", "Actions"),
    ("hikarasu", "ひからす", "ヒカラス", "光らす", "to shine / make glow", "Godan", "Nature & Animals"),
    ("hikkosu", "ひっこす", "ヒッコス", "引っ越す", "to relocate / move house", "Godan", "Daily Life"),
    ("hirou", "ひろう", "ヒロウ", "拾う", "to pick up / gather from ground", "Godan", "Actions"),
    ("homeru", "ほめる", "ホメル", "褒める", "to praise / commend highly", "Ichidan", "Social & Communication"),
    ("ijimeru", "いじめる", "イジメル", "苛める", "to tease / bully", "Ichidan", "Social & Communication"),
    ("inoru", "いのる", "イノル", "祈る", "to pray / wish deeply", "Godan", "Culture & Arts"),
    ("isogu", "いそぐ", "イソグ", "急ぐ", "to hurry / rush", "Godan", "Actions"),
    ("itasu", "いたす", "イタス", "致す", "to do (humble form of suru)", "Godan", "Social & Communication"),
    ("itadaku", "いただく", "イタダク", "頂く", "to receive / eat (humble)", "Godan", "Food & Dining"),
    ("junbi suru", "じゅんびする", "ジュンビスル", "準備する", "to prepare / get ready", "Irregular", "Daily Life"),
    ("kaeru", "かえる", "カエル", "変える", "to alter / change something", "Ichidan", "Actions"),
    ("katazukeru", "かたづける", "カタヅケル", "片付ける", "to tidy up / put things in order", "Ichidan", "Daily Life"),
    ("katsugu", "かつぐ", "カツグ", "担ぐ", "to shoulder / carry on shoulders", "Godan", "Actions"),
    ("kayou", "かよう", "カヨウ", "通う", "to commute regularly to school/work", "Godan", "Travel & Places"),
    ("kazaru", "かざる", "カザル", "飾る", "to decorate / adorn beautifully", "Godan", "Culture & Arts"),
    ("kekkon suru", "けっこんする", "ケッコンスル", "結婚する", "to marry / wed", "Irregular", "Society"),
    ("kimeru", "きめる", "キメル", "決める", "to decide / make up mind", "Ichidan", "Abstract"),
    ("kikoeru", "きこえる", "キコエル", "聞こえる", "to be audible / hear naturally", "Ichidan", "Senses"),
    ("komaru", "こまる", "コマル", "困る", "to be troubled / in distress", "Godan", "Emotions"),
    ("konderu", "こんでいる", "コンデイル", "混んでいる", "to be crowded / congested", "Ichidan", "Travel & Places"),
    ("kowareru", "こわれる", "コワレル", "壊れる", "to break down / be damaged", "Ichidan", "Daily Life"),
    ("kowasu", "こわす", "コワス", "壊す", "to break / destroy something", "Godan", "Actions"),
    ("kuraberu", "くらべる", "クラベル", "比べる", "to compare side by side", "Ichidan", "Abstract"),
    ("kureru", "くれる", "クレル", "呉れる", "to give (to speaker or speaker's group)", "Ichidan", "Social & Communication"),
    ("machigaeru", "まちがえる", "マチガエル", "間違える", "to make a mistake / blunder", "Ichidan", "Abstract"),
    ("maniau", "まにあう", "マニアウ", "間に合う", "to be in time for / suffice", "Godan", "Time & Space"),
    ("mieru", "みえる", "ミエル", "見える", "to be visible / in view", "Ichidan", "Senses"),
    ("mitsukaru", "みつかる", "ミツカル", "見つかる", "to be discovered / found", "Godan", "Abstract"),
    ("mitsukeru", "みつける", "ミツケル", "見つける", "to find / actively discover", "Ichidan", "Actions"),
    ("moushi-ageru", "もうしあげる", "モウシアゲル", "申し上げる", "to say / state (humble)", "Ichidan", "Social & Communication"),
    ("mousu", "もうす", "モウス", "申す", "to be called / say (humble)", "Godan", "Social & Communication"),
    ("mukaeru", "むかえる", "ムカエル", "迎える", "to welcome / greet / go meet", "Ichidan", "Travel & Places"),
    ("mukauni", "むかう", "ムカウ", "向かう", "to head toward / face forward", "Godan", "Actions"),
    ("nagameru", "ながめる", "ナガメル", "眺める", "to gaze at / view scenic vista", "Ichidan", "Senses"),
    ("naku", "なく", "ナク", "泣く", "to weep / cry tears", "Godan", "Emotions"),
    ("nakunaru", "なくなる", "ナクナル", "無くなる", "to disappear / be lost / pass away", "Godan", "Abstract"),
    ("naosu", "なおす", "ナオス", "直す", "to repair / cure / correct", "Godan", "Actions"),
    ("narabu", "ならぶ", "ナラブ", "並ぶ", "to stand in line / queue up", "Godan", "Actions"),
    ("naraberu", "ならべる", "ナラベル", "並べる", "to line up / display in order", "Ichidan", "Actions"),
    ("naru", "なる", "ナル", "鳴る", "to ring / chime / sound", "Godan", "Senses"),
    ("niru", "にる", "ニル", "似る", "to resemble / look alike", "Ichidan", "Abstract"),
    ("noboru", "のぼる", "ノボル", "登る", "to climb (a mountain) / ascend", "Godan", "Actions"),
    ("nokosu", "のこす", "ノコス", "残す", "to leave behind / preserve", "Godan", "Actions"),
    ("norikaeru", "のりかえる", "ノリカエル", "乗り換える", "to transfer trains or vehicles", "Ichidan", "Travel & Places"),
    ("ochiru", "おちる", "オチル", "落ちる", "to fall / drop down", "Ichidan", "Actions"),
    ("odoroku", "おどろく", "オドロク", "驚く", "to be startled / astonished", "Godan", "Emotions"),
    ("okuru", "おくる", "オクル", "送る", "to send / dispatch / see off", "Godan", "Actions"),
    ("okureru", "おくれる", "オクレル", "遅れる", "to be late / delayed", "Ichidan", "Time & Space"),
    ("omoidasu", "おもいだす", "オモイダス", "思い出す", "to recall / remember", "Godan", "Mind & Memory"),
    ("omou", "おもう", "オモウ", "思う", "to think / feel / suppose", "Godan", "Mind & Memory"),
    ("oriru", "おりる", "オリル", "降りる", "to get off (train) / disembark", "Ichidan", "Travel & Places"),
    ("orosu", "おろす", "オロス", "降ろす", "to unload / bring down / withdraw money", "Godan", "Actions"),
    ("oshieru", "おしえる", "オシエル", "教える", "to teach / explain / instruct", "Ichidan", "Work & Study"),
    ("renshuu suru", "れんしゅうする", "レンシュウスル", "練習する", "to practice / rehearse", "Irregular", "Work & Study"),
    ("ryokou suru", "りょこうする", "リョコウスル", "旅行する", "to take a trip / travel", "Irregular", "Travel & Places"),
    ("sagasu", "さがす", "サガス", "探す", "to search for / seek", "Godan", "Actions"),
    ("sagaru", "さがる", "サガル", "下がる", "to go down / drop in price or level", "Godan", "Abstract"),
    ("sageru", "さげる", "サゲル", "下げる", "to lower / hang down", "Ichidan", "Actions"),
    ("saku", "さく", "サク", "咲く", "to bloom / blossom", "Godan", "Nature & Animals"),
    ("sawagu", "さわぐ", "サワグ", "騒ぐ", "to make loud noise / clamor", "Godan", "Communication"),
    ("sawaru", "さわる", "サワル", "触る", "to touch / feel with hand", "Godan", "Senses"),
    ("shiraberu", "しらべる", "シラベル", "調べる", "to investigate / check / inspect", "Ichidan", "Work & Study"),
    ("shiraseru", "しらせる", "シラセル", "知らせる", "to notify / inform", "Ichidan", "Communication"),
    ("shodai suru", "しょうたいする", "ショウタイスル", "招待する", "to invite to event", "Irregular", "Social & Communication"),
    ("shoukai suru", "しょうかいする", "ショウカイスル", "紹介する", "to introduce someone", "Irregular", "Social & Communication"),
    ("shusseki suru", "しゅっせきする", "シュッセキスル", "出席する", "to attend a class or meeting", "Irregular", "Work & Study"),
    ("shuppatsu suru", "しゅっぱつする", "シュッパツスル", "出発する", "to depart / set off", "Irregular", "Travel & Places"),
    ("sodateru", "そだてる", "ソダテル", "育てる", "to raise / nurture / rear", "Ichidan", "Daily Life"),
    ("souji suru", "そうじする", "ソウジスル", "掃除する", "to clean up / vacuum", "Irregular", "Daily Life"),
    ("soudan suru", "そうだんする", "ソウダンスル", "相談する", "to consult / ask advice", "Irregular", "Communication"),
    ("sugiru", "すぎる", "スギル", "過ぎる", "to pass by / exceed limit", "Ichidan", "Time & Space"),
    ("suku", "すく", "スク", "空く", "to become empty / less crowded", "Godan", "Abstract"),
    ("susumu", "すすむ", "ススム", "進む", "to advance / progress forward", "Godan", "Actions"),
    ("suteru", "すてる", "ステル", "捨てる", "to throw away / discard trash", "Ichidan", "Daily Life"),
    ("tashikameru", "たしかめる", "タシカメル", "確かめる", "to confirm / verify with certainty", "Ichidan", "Work & Study"),
    ("tasukeru", "たすける", "タスケル", "助ける", "to help / rescue / save", "Ichidan", "Social & Communication"),
    ("tateru", "たてる", "タテル", "建てる", "to build / construct architecture", "Ichidan", "Actions"),
    ("tazuneru", "たずねる", "タズネル", "尋ねる", "to inquire / ask question", "Ichidan", "Communication"),
    ("todokeru", "とどける", "トドケル", "届ける", "to deliver / send parcel", "Ichidan", "Actions"),
    ("tomaru", "とまる", "トマル", "泊まる", "to lodge / stay overnight at hotel", "Godan", "Travel & Places"),
    ("tomeru", "とめる", "トメル", "止める", "to stop / park a vehicle", "Ichidan", "Actions"),
    ("torikaeru", "とりかえる", "トリカエル", "取り替える", "to exchange / replace item", "Ichidan", "Daily Life"),
    ("tsukamaeru", "つかまえる", "ツカマエル", "捕まえる", "to catch / seize / arrest", "Ichidan", "Actions"),
    ("tsukare-hateru", "つかれはてる", "ツカレハテル", "疲れ果てる", "to be thoroughly exhausted", "Ichidan", "Body & Health"),
    ("tsukiau", "つきあう", "ツキアウ", "付き合う", "to date / keep company with", "Godan", "Social & Communication"),
    ("tsutaeru", "つたえる", "ツタエル", "伝える", "to convey a message", "Ichidan", "Communication"),
    ("tsuzukeru", "つづける", "ツヅケル", "続ける", "to continue / keep going", "Ichidan", "Actions"),
    ("tsuzuku", "つづく", "ツヅク", "続く", "to continue on / carry over", "Godan", "Abstract"),
    ("ugokasu", "うごかす", "ウゴカス", "動かす", "to move / operate machinery", "Godan", "Actions"),
    ("ugoku", "うごく", "ウゴク", "動く", "to move / function / work", "Godan", "Actions"),
    ("ukeru", "うける", "ウケル", "受ける", "to take an exam / receive", "Ichidan", "Work & Study"),
    ("utsusu", "うつす", "ウツス", "写す", "to copy / photograph / transcribe", "Godan", "Actions"),
    ("wakareru", "わかれる", "ワカレル", "別れる", "to part ways / say goodbye / separate", "Ichidan", "Social & Communication"),
    ("wakasu", "わかす", "ワカス", "沸かす", "to boil water", "Godan", "Food & Dining"),
    ("warau", "わらう", "ワラウ", "笑う", "to laugh / smile warmly", "Godan", "Emotions"),
    ("wareru", "われる", "ワレル", "割れる", "to crack / shatter / split", "Ichidan", "Daily Life"),
    ("wasureru", "わすれる", "ワスレル", "忘れる", "to forget / leave behind", "Ichidan", "Mind & Memory"),
    ("yakusoku suru", "やくそくする", "ヤクソクスル", "約束する", "to promise / make appointment", "Irregular", "Communication"),
    ("yameru", "やめる", "ヤメル", "辞める", "to quit / resign / discontinue", "Ichidan", "Work & Study"),
    ("yaru", "やる", "ヤル", "遣る", "to do / perform casual task", "Godan", "Actions"),
    ("yogoreru", "よごれる", "ヨゴレル", "汚れる", "to get soiled / dirty", "Ichidan", "Daily Life"),
    ("yoyaku suru", "よやくする", "ヨヤクスル", "予約する", "to reserve a table or room", "Irregular", "Travel & Places")
]

ADJECTIVES = [
    # N4 Adjectives (i-adj & na-adj)
    ("anzen na", "あんぜんな", "アンゼンナ", "安全な", "safe / secure", "na-adjective", "Society"),
    ("benri na", "べんりな", "ベンリナ", "便利な", "convenient / handy", "na-adjective", "Daily Life"),
    ("bimyouna", "びみょうな", "ビミョウナ", "微妙な", "delicate / subtle", "na-adjective", "Abstract"),
    ("chanto shita", "ちゃんとした", "チャントシタ", "確りした", "proper / respectable", "na-adjective", "Social"),
    ("daiji na", "だいじな", "ダイジナ", "大事な", "crucial / precious / important", "na-adjective", "Abstract"),
    ("dame na", "だめな", "ダメナ", "駄目な", "no good / useless / forbidden", "na-adjective", "Abstract"),
    ("fuben na", "ふべんな", "フベンナ", "不便な", "inconvenient", "na-adjective", "Daily Life"),
    ("fushigi na", "ふしぎな", "フシギナ", "不思議な", "mysterious / miraculous", "na-adjective", "Abstract"),
    ("fukuzatsu na", "ふくざつな", "フクザツナ", "複雑な", "complex / complicated", "na-adjective", "Abstract"),
    ("genki na", "げんきな", "ゲンキナ", "元気な", "healthy / energetic / lively", "na-adjective", "Body & Health"),
    ("hageshii", "はげしい", "ハゲシイ", "激しい", "intense / fierce / violent", "i-adjective", "Nature & Animals"),
    ("hazukashii", "はずかしい", "ハズカシイ", "恥ずかしい", "embarrassed / shy / ashamed", "i-adjective", "Emotions"),
    ("hidoi", "ひどい", "ヒドイ", "酷い", "terrible / awful / cruel", "i-adjective", "Emotions"),
    ("hitsuyou na", "ひつような", "ヒツヨウナ", "必要な", "essential / necessary", "na-adjective", "Abstract"),
    ("hitoribotchi na", "ひとりぼっちな", "ヒトリボッチナ", "一人ぼっちな", "lonely / all alone", "na-adjective", "Emotions"),
    ("hosoi", "ほそい", "ホソイ", "細い", "slender / thin / fine", "i-adjective", "Appearance"),
    ("hontou na", "ほんとうな", "ホントウナ", "本当な", "real / true / genuine", "na-adjective", "Abstract"),
    ("ippai na", "いっぱいな", "イッパイナ", "一杯な", "full / packed to the brim", "na-adjective", "Abstract"),
    ("itai", "いたい", "イタイ", "痛い", "painful / sore / aching", "i-adjective", "Body & Health"),
    ("jama na", "じゃまな", "ジャマナ", "邪魔な", "in the way / hindering", "na-adjective", "Social"),
    ("jiyuu na", "じゆうな", "ジユウナ", "自由な", "free / unrestricted", "na-adjective", "Abstract"),
    ("joubu na", "じょうぶな", "ジョウブナ", "丈夫な", "durable / robust / sturdy", "na-adjective", "Home & Daily"),
    ("jouzu na", "じょうずな", "ジョウズナ", "上手な", "skillful / proficient", "na-adjective", "Work & Study"),
    ("kanashii", "かなしい", "カナシイ", "悲しい", "sorrowful / sad", "i-adjective", "Emotions"),
    ("kantan na", "かんたんな", "カンタンナ", "簡単な", "simple / easy / straightforward", "na-adjective", "Work & Study"),
    ("kawaii", "かわいい", "カワイイ", "可愛い", "cute / adorable", "i-adjective", "Appearance"),
    ("kiken na", "きけんな", "キケンナ", "危険な", "hazardous / dangerous", "na-adjective", "Society"),
    ("kirai na", "きらいな", "クライナ", "嫌いな", "disliked / distasteful", "na-adjective", "Emotions"),
    ("kirei na", "きれいな", "キレイナ", "綺麗な", "pretty / beautiful / clean", "na-adjective", "Appearance"),
    ("komakai", "こまかい", "コマカイ", "細かい", "detailed / small-scale / fine", "i-adjective", "Abstract"),
    ("kowai", "こわい", "コワイ", "怖い", "frightening / scary / terrifying", "i-adjective", "Emotions"),
    ("kurai", "くらい", "クライ", "暗い", "dim / dark / gloomy", "i-adjective", "Senses"),
    ("kusai", "くさい", "クサイ", "臭い", "foul-smelling / stinky", "i-adjective", "Senses"),
    ("majime na", "まじめな", "マジメナ", "真面目な", "serious / diligent / earnest", "na-adjective", "Personality"),
    ("manzoku na", "まんぞくな", "マンゾクナ", "満足な", "satisfactory / contented", "na-adjective", "Emotions"),
    ("mazui", "まずい", "マズイ", "不味い", "unpalatable / bad tasting / awkward", "i-adjective", "Food & Dining"),
    ("mezurashii", "めずらしい", "メズラシイ", "珍しい", "rare / uncommon / curious", "i-adjective", "Abstract"),
    ("muda na", "むだな", "ムダナ", "無駄な", "wasteful / pointless / futile", "na-adjective", "Abstract"),
    ("muzukashii", "むずかしい", "ムズカシイ", "難しい", "challenging / difficult", "i-adjective", "Work & Study"),
    ("nemui", "ねむい", "ネムイ", "眠い", "sleepy / drowsy", "i-adjective", "Body & Health"),
    ("nigiyaka na", "にぎやかな", "ニギヤカナ", "賑やかな", "bustling / lively / vibrant", "na-adjective", "Travel & Places"),
    ("nigai", "にがい", "ニガイ", "苦い", "bitter in taste", "i-adjective", "Food & Dining"),
    ("omoshiroi", "おもしろい", "オモシロイ", "面白い", "fascinating / entertaining", "i-adjective", "Emotions"),
    ("otona-rashii", "おとならしい", "オトナラシイ", "大人らしい", "mature / adult-like", "i-adjective", "Personality"),
    ("rippa na", "りっぱな", "リッパナ", "立派な", "splendid / magnificent / honorable", "na-adjective", "Society"),
    ("sabishii", "さびしい", "サビシイ", "寂しい", "lonely / desolate", "i-adjective", "Emotions"),
    ("shinsetsuna", "しんせつな", "シンセツナ", "親切な", "kind-hearted / gentle", "na-adjective", "Personality"),
    ("shinpai na", "しんぱいな", "シンパイナ", "心配な", "worrisome / anxious", "na-adjective", "Emotions"),
    ("shizuka na", "しずかな", "シズカナ", "静かな", "serene / peaceful / quiet", "na-adjective", "Senses"),
    ("sodate-yasui", "そだてやすい", "ソダテヤスイ", "育てやすい", "easy to raise or cultivate", "i-adjective", "Nature & Animals"),
    ("subarashii", "すばらしい", "スバラシイ", "素晴らしい", "magnificent / wonderful / splendid", "i-adjective", "Emotions"),
    ("suki na", "すきな", "スキナ", "好きな", "beloved / well-liked / favorite", "na-adjective", "Emotions"),
    ("sukunai", "すくない", "スクナイ", "少ない", "scarce / few in number", "i-adjective", "Abstract"),
    ("tadashii", "ただしい", "タダシイ", "正しい", "correct / righteous / accurate", "i-adjective", "Abstract"),
    ("taihen na", "たいへんな", "タイヘンナ", "大変な", "tough / arduous / momentous", "na-adjective", "Abstract"),
    ("taikutsuna", "たいくつな", "タイクツナ", "退屈な", "boring / tedious / dull", "na-adjective", "Emotions"),
    ("taisetsu na", "たいせつな", "タイセツナ", "大切な", "cherished / precious / vital", "na-adjective", "Abstract"),
    ("teinei na", "ていねいな", "テイネイナ", "丁寧な", "polite / courteous / meticulous", "na-adjective", "Social"),
    ("tekisetsu na", "てきせつな", "テキセツナ", "適切な", "appropriate / fitting / adequate", "na-adjective", "Abstract"),
    ("tokubetsu na", "とくべつな", "トクベツナ", "特別な", "extraordinary / special", "na-adjective", "Abstract"),
    ("tsuyoi", "つよい", "ツヨイ", "強い", "strong / powerful / resilient", "i-adjective", "Body & Health"),
    ("utsukushii", "うつくしい", "ウツクシイ", "美しい", "exquisitely beautiful", "i-adjective", "Appearance"),
    ("wakai", "わかい", "ワカイ", "若い", "youthful / young", "i-adjective", "People & Family"),
    ("warui", "わるい", "ワルイ", "悪い", "bad / evil / inferior", "i-adjective", "Abstract"),
    ("yasashii_kind", "やさしい", "ヤサシイ", "優しい", "gentle / tender / affectionate", "i-adjective", "Personality"),
    ("yasashii_easy", "やさしい", "ヤサシイ", "易しい", "easy / uncomplicated", "i-adjective", "Work & Study"),
    ("yoi / ii", "よい / いい", "ヨイ / イイ", "良い", "good / fine / pleasant", "i-adjective", "Abstract"),
    ("yuumei na", "ゆうめいな", "ユウメイナ", "有名な", "renowned / well-known / famous", "na-adjective", "Society"),
    ("zeitaku na", "ぜいたくな", "ゼイタクナ", "贅沢な", "luxurious / extravagant", "na-adjective", "Society")
]

ADVERBS = [
    # N4 Adverbs
    ("aida mo naku", "あいだもなく", "アイダモナク", "間もなく", "soon / before long", "Time & Frequency"),
    ("amari", "あまり", "アマリ", "余り", "not very (with negative)", "Degree"),
    ("chanto", "ちゃんと", "チャント", "確り", "properly / neatly / faithfully", "Manner"),
    ("chitto mo", "ちっとも", "チットモ", "些とも", "not in the least / not at all", "Degree"),
    ("choudo", "ちょうど", "チョウド", "丁度", "precisely / exactly right", "Degree"),
    ("daitai", "だいたい", "ダイタイ", "大体", "generally / mostly / substantially", "Degree"),
    ("dan-dan", "だんだん", "ダンダン", "段々", "gradually / step by step", "Degree"),
    ("doushite", "どうして", "ドウシテ", "如何して", "why / for what reason", "Discourse"),
    ("doutemo", "どうしても", "ドウシテモ", "どうしても", "at all costs / no matter what", "Discourse"),
    ("hajimeni", "はじめに", "ハジメニ", "初めに", "at the very beginning / first of all", "Sequence"),
    ("hakkiri", "はっきり", "ハッキリ", "明瞭", "clearly / distinctly / plainly", "Manner"),
    ("hotondo", "ほとんど", "ホトンド", "殆ど", "almost all / practically", "Degree"),
    ("ichidoni", "いちどに", "イチドニ", "一度に", "all at once / simultaneously", "Time & Frequency"),
    ("ikaga", "いかが", "イカガ", "如何", "how about / would you care for", "Discourse"),
    ("ikura", "いくら", "イクラ", "幾ら", "how much (price/degree)", "Degree"),
    ("ippai", "いっぱい", "イッパイ", "一杯", "fully / to capacity", "Degree"),
    ("isshou-kenmei", "いっしょうけんめい", "イッショウケンメイ", "一生懸命", "with utmost effort / devotedly", "Manner"),
    ("itsumo", "いつも", "イツモ", "何時も", "always / perpetually", "Time & Frequency"),
    ("jitsu wa", "じつは", "ジツハ", "実は", "to tell the truth / as a matter of fact", "Discourse"),
    ("kanarazu", "かならず", "カナラズ", "必ず", "definitely / without fail", "Modal"),
    ("kesshite", "けっして", "ケッシテ", "決して", "never by any means (with neg)", "Modal"),
    ("kyuu ni", "きゅうに", "キュウニ", "急に", "suddenly / unexpectedly", "Time & Frequency"),
    ("mada", "まだ", "マダ", "未だ", "still / not yet", "Time & Frequency"),
    ("masumasu", "ますます", "マスマス", "益々", "more and more / increasingly", "Degree"),
    ("mazu", "まず", "マズ", "先ず", "first of all / to begin with", "Sequence"),
    ("motto", "もっと", "モット", "尤も", "even more / further", "Degree"),
    ("mou", "もう", "モウ", "既に", "already / yet / more", "Time & Frequency"),
    ("moshikashitara", "もしかしたら", "モシカシタラ", "若しかしたら", "possibly / perhaps / maybe", "Modal"),
    ("moshimo", "もしも", "モシモ", "若しも", "if (hypothetically)", "Discourse"),
    ("nakanaka", "なかなか", "ナカナカ", "中々", "considerably / quite / not easily", "Degree"),
    ("naruhodo", "なるほど", "ナルホド", "成る程", "indeed / I see! / that makes sense", "Discourse"),
    ("nikoniko", "にこにこ", "ニコニコ", "微笑", "smiling happily / beaming", "Onomatopoeia"),
    ("nando mo", "なんども", "ナンドモ", "何度も", "many times / repeatedly", "Time & Frequency"),
    ("sassa to", "さっさと", "サッサト", "疾々と", "promptly / briskly without delay", "Manner"),
    ("sappari", "さっぱり", "サッパリ", "洒脱", "refreshed / completely (not)", "Manner"),
    ("sasuga", "さすが", "サスガ", "流石", "as expected of / truly admirable", "Discourse"),
    ("shikkari", "しっかり", "シッカリ", "確り", "firmly / steadily / reliably", "Manner"),
    ("shibaraku", "しばらく", "シバラク", "暫く", "for a while / for some time", "Time & Frequency"),
    ("sono mama", "そのまま", "ソノママ", "其の儘", "just as it is / unchanged", "Manner"),
    ("sorosoro", "そろそろ", "ソロソロ", "徐々", "soon / high time to get moving", "Time & Frequency"),
    ("souji te", "そうじて", "ソウジテ", "総じて", "in general / overall", "Degree"),
    ("subete", "すべて", "スベテ", "全て", "all / everything / completely", "Degree"),
    ("sugu ni", "すぐに", "スグニ", "直ぐに", "immediately / right away", "Time & Frequency"),
    ("sukoshi", "すこし", "スコシ", "少し", "a little / a bit", "Degree"),
    ("sukkari", "すっかり", "スッカリ", "全く", "completely / totally / thoroughly", "Degree"),
    ("tabun", "たぶん", "タブン", "多分", "probably / most likely", "Modal"),
    ("taihen", "たいへん", "タイヘン", "大変", "greatly / immensely / very", "Degree"),
    ("tama ni", "たまに", "タマニ", "偶に", "occasionally / once in a while", "Time & Frequency"),
    ("tashika ni", "たしかに", "タシカニ", "確かに", "certainly / surely / without doubt", "Modal"),
    ("tatoeba", "たとえば", "タトエバ", "例えば", "for example / for instance", "Discourse"),
    ("tokidoki", "ときどき", "トキドキ", "時々", "sometimes / at times", "Time & Frequency"),
    ("tokuni", "とくに", "トクニ", "特に", "especially / particularly", "Degree"),
    ("totemo", "とても", "トテモ", "迚も", "very / extraordinarily", "Degree"),
    ("touzen", "とうぜん", "トウゼン", "当然", "naturally / of course / as a matter of course", "Discourse"),
    ("tsuini", "ついに", "ツイニ", "遂に", "finally / at long last (after effort)", "Time & Frequency"),
    ("ukkari", "うっかり", "ウッカリ", "不覚", "carelessly / thoughtlessly / inadvertently", "Manner"),
    ("yappari", "やっぱり", "ヤッパリ", "矢張り", "as I thought / after all", "Discourse"),
    ("yatto", "やっと", "ヤット", "漸と", "at last / barely made it", "Time & Frequency"),
    ("yukkuri", "ゆっくり", "ユックリ", "緩り", "slowly / taking one's time / comfortably", "Manner"),
    ("zenzen", "ぜんぜん", "ゼンゼン", "全然", "not at all (with negative)", "Degree"),
    ("zutto", "ずっと", "ズット", "長年", "by far / much more / all along", "Degree")
]

PHRASES = [
    # N4 Phrases
    ("arigatou gozaimashita", "ありがとうございました", "アリガトウゴザイマシタ", "有難うございました", "Thank you very much (for what you did)", "Polite Daily"),
    ("chotto onegai ga arimasu", "ちょっとおねがいがあります", "チョットオネガイガアリマス", "ちょっとお願いがあります", "I have a small favor to ask you", "Polite Daily"),
    ("douzo o-hairi kudasai", "どうぞおはいりください", "ドウゾオハイリクダサイ", "どうぞお入りください", "Please come on in / welcome inside", "Hospitality"),
    ("go-shoushin kudasai", "ごしょうしんください", "ゴショウシンクダサイ", "ご安心ください", "Please rest assured / don't worry", "Polite Daily"),
    ("hajimemashite, douzo yoroshiku", "はじめまして、どうぞよろしく", "ハジメマシテ、ドウゾヨロシク", "初めまして、どうぞ宜しく", "Nice to meet you, looking forward to working with you", "Greetings"),
    ("itte kimasu", "いってきます", "イッテキマス", "行って来ます", "I'm heading out (and will return)!", "Daily Living"),
    ("itte rasshai", "いってらっしゃい", "イッテラッシャイ", "行ってらっしゃい", "Take care on your way out!", "Daily Living"),
    ("tadaima", "ただいま", "タダイマ", "只今", "I'm back home!", "Daily Living"),
    ("o-kaerinasai", "おかえりなさい", "オカエリナサイ", "お帰りなさい", "Welcome home!", "Daily Living"),
    ("itadakimasu", "いただきます", "イタダキマス", "頂きます", "Thank you for the meal (before eating)", "Dining"),
    ("gochisousama deshita", "ごちそうさまでした", "ゴチソウサマデシタ", "ご馳走様でした", "Thank you for the delicious meal (after eating)", "Dining"),
    ("o-kage sama de", "おかげさまで", "オカゲサマデ", "お陰様で", "Thanks to you / thankfully all is well", "Social Connection"),
    ("o-daiji ni", "おだいじに", "オダイジニ", "お大事に", "Please take good care of yourself (to sick person)", "Health & Care"),
    ("o-saki ni shitsurei shimasu", "おさきにしつれいします", "オサキニシツレイシマス", "お先に失礼します", "Excuse me for leaving ahead of you (workplace)", "Business"),
    ("o-tsukaresama deshita", "おつかれさまでした", "オツカレサマデシタ", "お疲れ様でした", "Thank you for your hard work!", "Workplace"),
    ("moushiwake arimasen", "もうしわけありません", "モウシワケアリマセン", "申し訳ありません", "I am terribly sorry / I offer my deepest apologies", "Polite Apology"),
    ("sumimasen ga, chotto...", "すみませんが、ちょっと...", "スミマセンガ、チョット...", "すみませんが、ちょっと...", "Excuse me, but that is a bit inconvenient for me...", "Soft Refusal"),
    ("kore de onegai shimasu", "これでおねがいします", "コレデオネガイシマス", "これでお願いします", "I'll take this one, please (shopping/ordering)", "Shopping"),
    ("o-kaikei o onegai shimasu", "おかいけいをおねがいします", "オカイケイヲオネガイシマス", "お会計をお願いします", "Check / bill please!", "Dining"),
    ("kore wa nihongo de nan to iimasu ka?", "これはにほんごでなんといいますか？", "コレハニホンゴデナントイイマスカ？", "これは日本語で何と言いますか？", "What do you call this in Japanese?", "Classroom & Study"),
    ("mou ichido itte kudasai", "もういちどいってください", "モウイチドイッテクダサイ", "もう一度言ってください", "Could you please say that once more?", "Classroom & Study"),
    ("yukkuri hanashite kudasai", "ゆっくりはなしてください", "ユックリハナシテクダサイ", "ゆっくり話してください", "Could you speak a little slower, please?", "Classroom & Study"),
    ("eigo ga hanasemasu ka?", "えいごがはなせますか？", "エイゴガハナセマスカ？", "英語が話せますか？", "Can you speak English?", "Travel & Places"),
    ("shashin o totte mo ii desu ka?", "しゃしんをとってもいいですか？", "シャシンヲトッテモイイデスカ？", "写真を撮ってもいいですか？", "May I take a photo here?", "Travel & Sightseeing"),
    ("kore o kudasai", "これをください", "コレヲクダサイ", "これを下さい", "I'll take this one, please.", "Shopping"),
    ("ikura desu ka?", "いくらですか？", "イクラデスカ？", "幾らですか？", "How much does this cost?", "Shopping"),
    ("eki wa doko desu ka?", "えきはどこですか？", "エキハドコデスカ？", "駅はどこですか？", "Where is the train station?", "Travel & Directions"),
    ("toirè wa doko desu ka?", "トイレはどこですか？", "トイレハドコデスカ？", "トイレはどこですか？", "Where is the restroom?", "Travel & Places"),
    ("tasukete kudasai!", "たすけてください！", "タスケテクダサイ！", "助けてください！", "Please help me!", "Emergency"),
    ("daijoubu desu ka?", "だいじょうぶですか？", "ダイジョウブデスカ？", "大丈夫ですか？", "Are you all right? / Is everything okay?", "Care & Sympathy"),
    ("ganbatte kudasai!", "がんばってください！", "ガンバッテクダサイ！", "頑張ってください！", "Do your best! / You can do it!", "Encouragement"),
    ("yokatta desu ne!", "よかったですね！", "ヨカッタデスネ！", "良かったですね！", "That's wonderful! I'm so glad for you!", "Sympathy & Joy"),
    ("shitsurei shimasu", "しつれいします", "シツレイシマス", "失礼します", "Excuse me (entering room / hanging up call)", "Polite Manner"),
    ("doko kara kimashita ka?", "どこからきましたか？", "ドコカラキマシタカ？", "どこから来ましたか？", "Where did you come from?", "Social Conversation"),
    ("nihon wa hajimete desu ka?", "にほんははじめてですか？", "ニホンハハジメテデスカ？", "日本は初めてですか？", "Is this your first time in Japan?", "Social Conversation"),
    ("kore wa oishii desu ne!", "これはおいしいですね！", "コレハオイシイデスネ！", "これは美味しいですね！", "This is truly delicious, isn't it!", "Dining"),
    ("zehi asobi ni kite kudasai", "ぜひあそびにきてください", "ゼヒアソビニキテクダサイ", "ぜひ遊びに来てください", "You must definitely come visit us!", "Hospitality")
]
