# Food, Beverage, Ingredients, Cooking, Utensils, Dishes
DATA = [
    # A
    ("aburaage", "あぶらあげ", "アブラアゲ", "油揚げ", "deep-fried tofu pouch", "Food & Dining"),
    ("agedashi", "あげだし", "アゲダシ", "揚げ出し", "deep-fried tofu in dashi broth", "Food & Dining"),
    ("agemono", "あげもの", "アゲモノ", "揚げ物", "fried food / deep-fried dish", "Food & Dining"),
    ("aji", "あじ", "アジ", "鰺", "horse mackerel", "Food & Dining"),
    ("akagai", "あかがい", "アカガイ", "赤貝", "ark shell / red clam", "Food & Dining"),
    ("akami", "あかみ", "アカミ", "赤身", "lean tuna / red meat", "Food & Dining"),
    ("akarumaguro", "あかまぐろ", "アカマグロ", "赤鮪", "red tuna meat", "Food & Dining"),
    ("amadare", "あまだれ", "アマダレ", "甘だれ", "sweet glaze sauce", "Food & Dining"),
    ("amazake", "あまざけ", "アマザケ", "甘酒", "sweet non-alcoholic fermented rice drink", "Food & Dining"),
    ("anago", "あなご", "アナゴ", "穴子", "saltwater conger eel", "Food & Dining"),
    ("anpan", "あんぱん", "アンパン", "あんパン", "red bean bun", "Food & Dining"),
    ("ankake", "あんかけ", "アンカケ", "あんかけ", "thick starchy sauce", "Food & Dining"),
    ("anmitsu", "あんみつ", "アンミツ", "あんみつ", "traditional agar jelly dessert with red bean", "Food & Dining"),
    ("aojiru", "あおじる", "アオジル", "青汁", "green vegetable juice", "Food & Dining"),
    ("aonori", "あおのり", "アオノリ", "青海苔", "dried green laver seaweed", "Food & Dining"),
    ("asazuke", "あさづけ", "アサヅケ", "浅漬け", "lightly pickled seasonal vegetables", "Food & Dining"),
    ("atsuyakitamago", "あつやきたまご", "アツヤキタマゴ", "厚焼き卵", "thick sweet rolled omelet", "Food & Dining"),
    # B
    ("baamu", "ばーむ", "バーム", "バームクーヘン", "baumkuchen cake", "Food & Dining"),
    ("baasudee keeki", "ばーすでーけーき", "バースデーケーキ", "バースデーケーキ", "birthday cake", "Food & Dining"),
    ("bagetto", "ばげっと", "バゲット", "バゲット", "baguette bread", "Food & Dining"),
    ("bainiku", "ばいにく", "バイニク", "梅肉", "plum flesh / umeboshi paste", "Food & Dining"),
    ("bakku ribbu", "ばっくりぶ", "バックリブ", "バックリブ", "back ribs", "Food & Dining"),
    ("banya kauda", "ばにゃかうだ", "バーニャカウダ", "バーニャカウダ", "bagna càuda dip", "Food & Dining"),
    ("barasushi", "ばらずし", "バラズシ", "ばら寿司", "scattered sushi bowl", "Food & Dining"),
    ("bebii riifu", "べびーりーふ", "ベビーリーフ", "ベビーリーフ", "baby leaf greens", "Food & Dining"),
    ("beni shouga", "べにしょうが", "ベニショウガ", "紅生姜", "red pickled ginger", "Food & Dining"),
    ("biifun", "びーふん", "ビーフン", "米粉", "rice vermicelli noodles", "Food & Dining"),
    ("biiru", "びーる", "ビール", "ビール", "beer", "Food & Dining"),
    ("bisuketto", "びすけっと", "ビスケット", "ビスケット", "biscuit / cookie", "Food & Dining"),
    ("botamochi", "ぼたもち", "ボタモチ", "牡丹餅", "sweet rice ball coated with red bean paste", "Food & Dining"),
    ("burokkorii", "ぶろっこりー", "ブロッコリー", "ブロッコリー", "broccoli", "Food & Dining"),
    ("buruuberii", "ぶるーべりー", "ブルーベリー", "ブルーベリー", "blueberry", "Food & Dining"),
    ("butadon", "ぶたどん", "ブタドン", "豚丼", "pork rice bowl", "Food & Dining"),
    ("butakatsu", "ぶたかつ", "ブタカツ", "豚カツ", "pork cutlet (tonkatsu)", "Food & Dining"),
    ("butakoma", "ぶたこま", "ブタコマ", "豚小間", "sliced pork scraps", "Food & Dining"),
    # C
    ("chaahan", "ちゃーはん", "チャーハン", "炒飯", "fried rice", "Food & Dining"),
    ("chaashuu", "ちゃーしゅー", "チャーシュー", "叉焼", "roasted pork slices", "Food & Dining"),
    ("chameshi", "ちゃめし", "チャメシ", "茶飯", "rice cooked in tea or dashi", "Food & Dining"),
    ("chanpuruu", "ちゃんぷるー", "チャンプルー", "チャンプルー", "Okinawan stir-fry", "Food & Dining"),
    ("chanko nabe", "ちゃんこなべ", "チャンコナベ", "ちゃんこ鍋", "sumo wrestler hot pot stew", "Food & Dining"),
    ("chawanmushi", "ちゃわんむし", "チャワンムシ", "茶碗蒸し", "savory steamed egg custard", "Food & Dining"),
    ("chiizu", "ちーず", "チーズ", "チーズ", "cheese", "Food & Dining"),
    ("chiizukeeki", "ちーずけーき", "チーズケーキ", "チーズケーキ", "cheesecake", "Food & Dining"),
    ("chikuzen'ni", "ちくぜんに", "チクゼンニ", "筑前煮", "chicken and root vegetable braise", "Food & Dining"),
    ("chirashizushi", "ちらしずし", "チラシズシ", "ちらし寿司", "scattered raw fish sushi bowl", "Food & Dining"),
    ("chokoreeto", "ちょこれーと", "チョコレート", "チョコレート", "chocolate", "Food & Dining"),
    ("choumiryou", "ちょうみりょう", "チョウミリョウ", "調味料", "seasoning / condiment", "Food & Dining"),
    ("chuuhaai", "ちゅうはい", "チュウハイ", "酎ハイ", "shochu highball cocktail", "Food & Dining"),
    # D
    ("daifuku", "だいふく", "ダイフク", "大福", "rice cake stuffed with sweet bean paste", "Food & Dining"),
    ("daikonoroshi", "だいこのおろし", "ダイコンオロシ", "大根おろし", "grated daikon radish", "Food & Dining"),
    ("dango", "だんご", "ダンゴ", "団子", "chewy sweet dumpling skewer", "Food & Dining"),
    ("dashijiru", "だしじる", "ダシジル", "出汁汁", "dashi broth soup", "Food & Dining"),
    ("dashimakitomago", "だしまきたまご", "ダシマキタマゴ", "だし巻き卵", "dashi-infused rolled omelet", "Food & Dining"),
    ("dezaato", "でざーと", "デザート", "デザート", "dessert", "Food & Dining"),
    ("doonatsu", "どーなつ", "ドーナツ", "ドーナツ", "doughnut", "Food & Dining"),
    ("dorayaki", "どらやき", "ドラヤキ", "どら焼き", "red bean pancake sandwich", "Food & Dining"),
    ("doria", "どりあ", "ドリア", "ドリア", "rice gratin / doria", "Food & Dining"),
    # E
    ("ebifurai", "えびふらい", "エビフライ", "エビフライ", "deep-fried breaded shrimp", "Food & Dining"),
    ("ebichiri", "えびちり", "エビチリ", "エビチリ", "shrimp in spicy chili sauce", "Food & Dining"),
    ("ebitendon", "えびてんどん", "エビテンドン", "海老天丼", "shrimp tempura rice bowl", "Food & Dining"),
    ("edamame", "えだまめ", "エダマメ", "枝豆", "boiled young green soybeans", "Food & Dining"),
    ("ekisu", "えきす", "エキス", "エキス", "extract / essence", "Food & Dining"),
    ("ensou", "えんそう", "エンソウ", "塩辛", "salted fish viscera / fermented seafood", "Food & Dining"),
    ("esupuresso", "えすぷれっそ", "エスプレッソ", "エスプレッソ", "espresso coffee", "Food & Dining"),
    # F
    ("focaccia", "ふぉかっちゃ", "フォカッチャ", "フォカッチャ", "focaccia bread", "Food & Dining"),
    ("fondue", "ふぉんでゅ", "フォンデュ", "フォンデュ", "cheese / chocolate fondue", "Food & Dining"),
    ("fugu", "ふぐ", "フグ", "河豚", "pufferfish / blowfish", "Food & Dining"),
    ("fukujinzuke", "ふくじんづけ", "フクジンヅケ", "福神漬け", "pickled vegetable relish for curry", "Food & Dining"),
    ("furafuchiino", "ふらぺちーの", "フラペチーノ", "フラペチーノ", "frappuccino", "Food & Dining"),
    ("furansupan", "ふらんすぱん", "フランスパン", "フランスパン", "french bread / baguette", "Food & Dining"),
    ("furaipan", "ふらいぱん", "フライパン", "フライパン", "frying pan / skillet", "Food & Dining"),
    ("furutsu", "ふるーつ", "フルーツ", "フルーツ", "fruits", "Food & Dining"),
    ("futomaki", "ふとまき", "フトマキ", "太巻き", "thick sushi roll", "Food & Dining"),
    # G
    ("ganmodoki", "がんもどき", "ガンモドキ", "雁擬き", "fried tofu dumpling with vegetables", "Food & Dining"),
    ("gari", "がり", "ガリ", "ガリ", "sweet pickled sliced sushi ginger", "Food & Dining"),
    ("gejigeji", "げじげじ", "ゲジゲジ", "蚰蜒", "house centipede", "Nature & Animals"),
    ("gekikara", "げきから", "ゲキカラ", "激辛", "ultra-spicy hot", "Food & Dining"),
    ("gindara", "ぎんだら", "ギンダラ", "銀鱈", "sablefish / black cod", "Food & Dining"),
    ("gingnan", "ぎんなん", "ギンナン", "銀杏", "ginkgo nut", "Food & Dining"),
    ("gobou", "ごぼう", "ゴボウ", "牛蒡", "burdock root", "Food & Dining"),
    ("goma", "ごま", "ゴマ", "胡麻", "sesame seeds", "Food & Dining"),
    ("gomaabura", "ごまあぶら", "ゴマアブラ", "ごま油", "sesame oil", "Food & Dining"),
    ("gomashio", "ごましお", "ゴマシオ", "ごま塩", "sesame seed and salt mix", "Food & Dining"),
    ("goya", "ごーや", "ゴーヤ", "苦瓜", "bitter melon / bitter gourd", "Food & Dining"),
    ("gyuudon", "ぎゅうどん", "ギュウドン", "牛丼", "beef rice bowl", "Food & Dining"),
    ("gyuukatsu", "ぎゅうかつ", "ギュウカツ", "牛カツ", "deep-fried beef cutlet", "Food & Dining"),
    ("gyuuniku", "ぎゅうにく", "ギュウニク", "牛肉", "beef", "Food & Dining"),
    ("gyuutan", "ぎゅうたん", "ギュウタン", "牛タン", "beef tongue", "Food & Dining"),
    ("gyousho", "ぎょしょ", "ギョショ", "魚醤", "fish sauce", "Food & Dining"),
    # H
    ("hakusai", "はくさい", "ハクサイ", "白菜", "Napa cabbage / Chinese cabbage", "Food & Dining"),
    ("hamu", "はむ", "ハム", "ハム", "ham", "Food & Dining"),
    ("hambaagu", "はんばーぐ", "ハンバーグ", "ハンバーグ", "Hamburg steak patty", "Food & Dining"),
    ("hanbaagaa", "はんばーがー", "ハンバーガー", "ハンバーガー", "hamburger sandwich", "Food & Dining"),
    ("harumaki", "はるまき", "ハルマキ", "春巻き", "spring roll", "Food & Dining"),
    ("harusame", "はるさめ", "ハルサメ", "春雨", "glass noodles / bean thread", "Food & Dining"),
    ("hashi", "はし", "ハシ", "箸", "chopsticks", "Food & Dining"),
    ("hashioki", "はしおき", "ハシオキ", "箸置き", "chopstick rest", "Food & Dining"),
    ("hayashirausu", "はやしらいす", "ハヤシライス", "ハヤシライス", "hashed beef and rice", "Food & Dining"),
    ("hiyayakko", "ひややっこ", "ヒヤヤッコ", "冷奴", "chilled tofu with toppings", "Food & Dining"),
    ("hiyashichuuka", "ひやしちゅうか", "ヒヤシチュウカ", "冷やし中華", "chilled ramen noodles with toppings", "Food & Dining"),
    ("horenso", "ほうれんそう", "ホウレンソウ", "ほうれん草", "spinach", "Food & Dining"),
    ("horumon", "ほるもん", "ホルモン", "ホルモン", "beef or pork offal / entrails", "Food & Dining"),
    ("hoshigaki", "ほしがき", "ホシガキ", "干し柿", "dried persimmon", "Food & Dining"),
    ("hotate", "ほたて", "ホタテ", "帆立", "scallop", "Food & Dining"),
    ("hotto doonatsu", "ほっとどっぐ", "ホットドッグ", "ホットドッグ", "hot dog", "Food & Dining"),
    ("hotto keeki", "ほっとけーき", "ホットケーキ", "ホットケーキ", "pancake / hotcake", "Food & Dining"),
    # I
    ("ichimi", "いちみ", "イチミ", "一味", "ground red chili pepper powder", "Food & Dining"),
    ("ikayaki", "いかやき", "イカヤキ", "イカ焼き", "grilled whole squid", "Food & Dining"),
    ("ikura", "いくら", "イクラ", "イクラ", "salmon roe / red caviar", "Food & Dining"),
    ("imo", "いも", "イモ", "芋", "potato / yam / tuber", "Food & Dining"),
    ("imojiru", "いもじる", "イモジル", "芋汁", "taro soup", "Food & Dining"),
    ("inari", "いなり", "イナリ", "稲荷寿司", "fried bean curd pouch sushi", "Food & Dining"),
    ("inoshishiniku", "いのししにく", "イノシシニク", "猪肉", "wild boar meat", "Food & Dining"),
    ("iriko", "いりこ", "イリコ", "炒り子", "dried baby sardines / niboshi", "Food & Dining"),
    ("itawasa", "いたわさ", "イタワサ", "板わさ", "sliced fish cake with wasabi", "Food & Dining"),
    # J
    ("jagaimo", "じゃがいも", "ジャガイモ", "じゃが芋", "potato", "Food & Dining"),
    ("jagasutakku", "じゃがばたー", "ジャガバター", "じゃがバター", "baked potato with melted butter", "Food & Dining"),
    ("jamu", "じゃむ", "ジャム", "ジャム", "fruit jam", "Food & Dining"),
    ("jindara", "じんだら", "ジンダラ", "甚鱈", "Alaska pollock / cod", "Food & Dining"),
    ("juusu", "じゅーす", "ジュース", "ジュース", "fruit juice", "Food & Dining"),
    # K
    ("kabu", "かぶ", "カブ", "蕪", "turnip", "Food & Dining"),
    ("kabochasoupu", "かぼちゃすーぷ", "カボチャスープ", "南瓜スープ", "pumpkin soup", "Food & Dining"),
    ("kaisen", "かいせん", "カイセン", "海鮮", "fresh seafood", "Food & Dining"),
    ("kaisendon", "かいせんどん", "カイセンドン", "海鮮丼", "fresh seafood rice bowl", "Food & Dining"),
    ("kaisekiryouri", "かいせきりょうり", "カイセキリョウリ", "懐石料理", "traditional Japanese multi-course banquet", "Food & Dining"),
    ("kaki", "かき", "カキ", "牡蠣", "oyster", "Food & Dining"),
    ("kakifurai", "かきふらい", "カキフライ", "カキフライ", "deep-fried breaded oysters", "Food & Dining"),
    ("kakigoori", "かきごおり", "カキゴオリ", "かき氷", "shaved ice with flavored syrup", "Food & Dining"),
    ("kakiage", "かきあげ", "カキアゲ", "かき揚げ", "mixed vegetable & seafood tempura fritter", "Food & Dining"),
    ("kamaboko", "かまぼこ", "カマボコ", "蒲鉾", "steamed fish cake loaf", "Food & Dining"),
    ("kanikan", "かにかん", "カニカン", "蟹缶", "canned crab meat", "Food & Dining"),
    ("kanimeshi", "かにめし", "カニメシ", "蟹飯", "crab rice bowl", "Food & Dining"),
    ("kanten", "かんてん", "カンテン", "寒天", "agar-agar jelly", "Food & Dining"),
    ("kanpyou", "かんぴょう", "カンピョウ", "干瓢", "dried gourd strips for sushi", "Food & Dining"),
    ("karaage", "からあげ", "カラアゲ", "唐揚げ", "Japanese seasoned fried chicken", "Food & Dining"),
    ("karashi", "からし", "カラシ", "芥子", "Japanese hot yellow mustard", "Food & Dining"),
    ("karee", "かれー", "カレー", "カレー", "curry stew", "Food & Dining"),
    ("kareeraisu", "かれーらいす", "カレーライス", "カレーライス", "Japanese curry rice", "Food & Dining"),
    ("kareepan", "かれーぱん", "カレーパン", "カレーパン", "curry bread pastry", "Food & Dining"),
    ("kasutera", "かすてら", "カステラ", "カステラ", "Castella sponge cake", "Food & Dining"),
    ("katsuobushi", "かつおぶし", "カツオブシ", "鰹節", "dried bonito flakes", "Food & Dining"),
    ("katsudon", "かつどん", "カツドン", "カツ丼", "pork cutlet and egg rice bowl", "Food & Dining"),
    ("katsusando", "かつさんど", "カツサンド", "カツサンド", "pork cutlet sandwich", "Food & Dining"),
    ("kinako", "きなこ", "キナコ", "黄粉", "roasted soybean flour", "Food & Dining"),
    ("kiritanpo", "きりたんぽ", "キリタンポ", "きりたんぽ", "toasted rice skewers for hot pot", "Food & Dining"),
    ("kishimen", "きしめん", "キシメン", "きしめん", "flat udon noodles", "Food & Dining"),
    ("kitanose", "きたのせ", "キタノセ", "北の瀬", "northern fishery catch", "Food & Dining"),
    ("kitsuneudon", "きつねうどん", "キツネウドン", "きつねうどん", "udon topped with sweet fried tofu", "Food & Dining"),
    ("koohii", "こーひー", "コーヒー", "コーヒー", "coffee", "Food & Dining"),
    ("kochoujan", "こちゅじゃん", "コチュジャン", "コチュジャン", "gochujang chili paste", "Food & Dining"),
    ("konnyaku", "こんにゃく", "コンニャク", "蒟蒻", "konjac yam cake", "Food & Dining"),
    ("korokke", "ころっけ", "コロッケ", "コロッケ", "croquette / fried mashed potato patty", "Food & Dining"),
    ("koushinryou", "こうしんりょう", "コウシンリョウ", "香辛料", "spices / condiments", "Food & Dining"),
    ("kurogoma", "くろごま", "クロゴマ", "黒胡麻", "black sesame seeds", "Food & Dining"),
    ("kuromitsu", "くろみつ", "クロミツ", "黒蜜", "black sugar syrup / molasses", "Food & Dining"),
    ("kushikatsu", "くしかつ", "クシカツ", "串カツ", "deep-fried skewered meat and vegetables", "Food & Dining"),
    ("kushiyaki", "くしやき", "クシヤキ", "串焼き", "grilled skewers", "Food & Dining"),
    # M
    ("macha", "まっちゃ", "マッチャ", "抹茶", "powdered green tea / matcha", "Food & Dining"),
    ("magurodon", "まぐろどん", "マグロドン", "鮪丼", "tuna sashimi bowl", "Food & Dining"),
    ("makizushi", "まきずし", "マキズシ", "巻き寿司", "rolled sushi", "Food & Dining"),
    ("manjuu", "まんじゅう", "マンジュウ", "饅頭", "steamed sweet bean bun", "Food & Dining"),
    ("mayoneezu", "まよねーず", "マヨネーズ", "マヨネーズ", "mayonnaise", "Food & Dining"),
    ("menchi katsu", "めんちかつ", "メンチカツ", "メンチカツ", "fried minced meat cutlet", "Food & Dining"),
    ("mentaiko", "めんたいこ", "メンタイコ", "明太子", "spicy seasoned pollock roe", "Food & Dining"),
    ("menma", "めんま", "メンマ", "メンマ", "seasoned bamboo shoots for ramen", "Food & Dining"),
    ("meronpan", "めろんぱん", "メロンパン", "メロンパン", "melon-shaped sweet cookie bun", "Food & Dining"),
    ("mirin", "みりん", "ミリン", "味醂", "sweet cooking rice wine", "Food & Dining"),
    ("misoshiru", "みそしる", "ミソシル", "味噌汁", "miso soup", "Food & Dining"),
    ("mitarashi dango", "みたらしだんご", "ミタラシダンゴ", "みたらし団子", "skewered dumplings in sweet soy glaze", "Food & Dining"),
    ("mizore", "みぞれ", "ミゾレ", "みぞれ", "grated daikon garnish / sleet", "Food & Dining"),
    ("mizugashi", "みずがし", "ミズガシ", "水菓子", "fresh fruit served as dessert", "Food & Dining"),
    ("mizuyoukan", "みずようかん", "ミズヨウカン", "水羊羹", "soft sweet bean jelly", "Food & Dining"),
    ("motsunabe", "もつなべ", "モツナベ", "もつ鍋", "beef or pork tripe hot pot", "Food & Dining"),
    ("moyashi", "もやし", "モヤシ", "豆やし", "bean sprouts", "Food & Dining"),
    ("mugi cha", "むぎちゃ", "ムギチャ", "麦茶", "roasted barley tea", "Food & Dining"),
    # N
    ("nabemono", "なべもの", "ナベモノ", "鍋物", "hot pot stew dishes", "Food & Dining"),
    ("nama biiru", "なまびーる", "ナマビール", "生ビール", "draft beer", "Food & Dining"),
    ("namagashi", "なまがし", "ナマガシ", "生菓子", "fresh traditional confectionery", "Food & Dining"),
    ("namaham", "なまはむ", "ナマハム", "生ハム", "prosciutto / cured raw ham", "Food & Dining"),
    ("namasake", "なまざけ", "ナマザケ", "生酒", "unpasteurized sake", "Food & Dining"),
    ("nanbanzuke", "なんばんづけ", "ナンバンヅケ", "南蛮漬け", "fried fish pickled in sweet vinegar", "Food & Dining"),
    ("natto", "なっとう", "ナットウ", "納豆", "fermented soybeans", "Food & Dining"),
    ("negitoro", "ねぎとろ", "ネギトロ", "ネギトロ", "minced tuna with green onions", "Food & Dining"),
    ("negiyaki", "ねぎやき", "ネギヤキ", "ねぎ焼き", "scallion savory pancake", "Food & Dining"),
    ("niboshi", "にぼし", "ニボシ", "煮干し", "dried baby sardines for stock", "Food & Dining"),
    ("nigirizushi", "にぎりずし", "ニギリズシ", "握り寿司", "hand-pressed sushi piece", "Food & Dining"),
    ("nikujaga", "にくじゃが", "ニクジャガ", "肉じゃが", "beef and potato simmered stew", "Food & Dining"),
    ("nikuman", "にくまん", "ニクマン", "肉まん", "steamed pork meat bun", "Food & Dining"),
    # O
    ("oden", "おでん", "オデン", "おでん", "simmered fishcake and daikon hot pot", "Food & Dining"),
    ("ogurapan", "おぐらぱん", "オグラパン", "小倉パン", "sweet red bean paste bread", "Food & Dining"),
    ("ocha", "おちゃ", "オチャ", "お茶", "green tea", "Food & Dining"),
    ("ochazuke", "おちゃづけ", "オチャヅケ", "お茶漬け", "dashi or tea poured over rice", "Food & Dining"),
    ("okonomiyaki", "おこのみやき", "オコノミヤキ", "お好み焼き", "savory cabbage and pork pancake", "Food & Dining"),
    ("omuraisu", "おむらいす", "オムライス", "オムライス", "omelet-wrapped fried rice", "Food & Dining"),
    ("onigiri", "おにぎり", "オニギリ", "お握り", "rice ball", "Food & Dining"),
    ("onigirazu", "おにぎらず", "オニギラズ", "おにぎらず", "rice sandwich wrapped in seaweed", "Food & Dining"),
    ("onsen tamago", "おんせんたまご", "オンセンタマゴ", "温泉卵", "soft-poached hot spring egg", "Food & Dining"),
    ("ootoro", "おおとろ", "オオトロ", "大トロ", "fatty tuna belly sashimi", "Food & Dining"),
    ("oyakodon", "おやこどん", "オヤコドン", "親子丼", "chicken and egg rice bowl", "Food & Dining"),
    # P
    ("pan", "ぱん", "パン", "パン", "bread", "Food & Dining"),
    ("pan ko", "ぱんこ", "パンコ", "パン粉", "panko bread crumbs", "Food & Dining"),
    ("parufe", "ぱふぇ", "パフェ", "パフェ", "ice cream parfait", "Food & Dining"),
    ("pasuta", "ぱすた", "パスタ", "パスタ", "pasta noodles", "Food & Dining"),
    ("piiman", "ぴーまん", "ピーマン", "ピーマン", "green bell pepper", "Food & Dining"),
    ("piinatsu", "ぴーなっつ", "ピーナッツ", "ピーナッツ", "peanuts", "Food & Dining"),
    ("piiza", "ぴざ", "ピザ", "ピザ", "pizza", "Food & Dining"),
    ("purin", "ぷりん", "プリン", "プリン", "custard pudding / flan", "Food & Dining"),
    # R
    ("raamen", "らーめん", "ラーメン", "ラーメン", "ramen noodles in savory broth", "Food & Dining"),
    ("raayu", "らーゆ", "ラー油", "ラー油", "spicy chili oil", "Food & Dining"),
    ("rakkyo", "らっきょう", "ラッキョウ", "辣韮", "pickled shallots / scallions", "Food & Dining"),
    ("rebaa", "ればー", "レバー", "レバー", "liver meat", "Food & Dining"),
    ("renkon", "れんこん", "レンコン", "蓮根", "lotus root", "Food & Dining"),
    ("roosuto biifu", "ろーすとびーふ", "ローストビーフ", "ローストビーフ", "roast beef slices", "Food & Dining"),
    # S
    ("saaba", "さば", "サバ", "鯖", "mackerel fish", "Food & Dining"),
    ("saamon", "さーもん", "サーモン", "サーモン", "salmon sashimi / fillet", "Food & Dining"),
    ("sake", "さけ", "サケ", "鮭", "salmon", "Food & Dining"),
    ("sakura mochi", "さくらもち", "サクラモチ", "桜餅", "pink cherry blossom rice cake", "Food & Dining"),
    ("sanshou", "さんしょう", "サンショウ", "山椒", "Japanese pepper spice", "Food & Dining"),
    ("sasami", "ささみ", "ササミ", "笹身", "tender chicken tenderloin", "Food & Dining"),
    ("sashimi", "さしみ", "サシミ", "刺身", "sliced raw fresh fish", "Food & Dining"),
    ("satou", "さとう", "サトウ", "砂糖", "granulated sugar", "Food & Dining"),
    ("sembei", "せんべい", "センベイ", "煎餅", "toasted rice cracker", "Food & Dining"),
    ("shabu shabu", "しゃぶしゃぶ", "シャブシャブ", "しゃぶしゃぶ", "thinly sliced beef hot pot", "Food & Dining"),
    ("shiitake", "しいたけ", "シイタケ", "椎茸", "shiitake mushroom", "Food & Dining"),
    ("shimeji", "しめじ", "シメジ", "占地", "shimeji mushroom clusters", "Food & Dining"),
    ("shincha", "しんちゃ", "シンチャ", "新茶", "first-picked green tea of season", "Food & Dining"),
    ("shio", "しお", "シオ", "塩", "cooking salt", "Food & Dining"),
    ("shiruko", "しるこ", "シルコ", "汁粉", "sweet red bean soup with mochi", "Food & Dining"),
    ("shirataki", "しらたき", "シラタキ", "白滝", "translucent konjac noodles", "Food & Dining"),
    ("shiroutoro", "しろとろ", "シロトロ", "白とろ", "white fatty fish slice", "Food & Dining"),
    ("shiso", "しそ", "シソ", "紫蘇", "perilla leaf herb", "Food & Dining"),
    ("shochu", "しょうちゅう", "ショウチュウ", "焼酎", "distilled Japanese spirit", "Food & Dining"),
    ("shouga", "しょうが", "ショウガ", "生姜", "ginger root", "Food & Dining"),
    ("shouyu", "しょうゆ", "ショウユ", "醤油", "soy sauce", "Food & Dining"),
    ("shuumai", "しゅうまい", "シュウマイ", "焼売", "steamed pork dumpling", "Food & Dining"),
    ("soba", "そば", "ソバ", "蕎麦", "buckwheat noodles", "Food & Dining"),
    ("sukiyaki", "すきやき", "スキヤキ", "すき焼き", "simmered sweet soy beef pot", "Food & Dining"),
    ("supagetti", "すぱげってぃ", "スパゲッティ", "スパゲッティ", "spaghetti", "Food & Dining"),
    ("sushi", "すし", "スシ", "寿司", "sushi", "Food & Dining"),
    # T
    ("taiyaki", "たいやき", "タイヤキ", "たい焼き", "fish-shaped sweet waffle cake", "Food & Dining"),
    ("takoyaki", "たこやき", "タコヤキ", "たこ焼き", "octopus dough balls", "Food & Dining"),
    ("tamagoyaki", "たまごやき", "タマゴヤキ", "卵焼き", "Japanese rolled omelet", "Food & Dining"),
    ("tantanmen", "たんたんめん", "タンタンメン", "担々麺", "spicy sesame ramen", "Food & Dining"),
    ("tempura", "てんぷら", "テンプラ", "天ぷら", "light battered tempura", "Food & Dining"),
    ("tendon", "てんどん", "テンドン", "天丼", "tempura rice bowl", "Food & Dining"),
    ("teppanyaki", "てっぱんやき", "テッパンヤキ", "鉄板焼き", "iron griddle grilled cuisine", "Food & Dining"),
    ("tokoroten", "ところてん", "トコロテン", "心太", "agar noodle jelly strips", "Food & Dining"),
    ("tonkatsu", "とんかつ", "トンカツ", "豚カツ", "deep-fried breaded pork cutlet", "Food & Dining"),
    ("tonkotsu", "とんこつ", "トンコツ", "豚骨", "pork bone ramen broth", "Food & Dining"),
    ("tonjiru", "とんじる", "トンジル", "豚汁", "pork and root vegetable miso soup", "Food & Dining"),
    ("toriniku", "とりにく", "トリニク", "鶏肉", "chicken meat", "Food & Dining"),
    ("tsukemono", "つけもの", "ツケモノ", "漬物", "pickled preserved vegetables", "Food & Dining"),
    ("tsukemen", "つけめん", "ツケメン", "つけ麺", "dipping noodles with rich broth", "Food & Dining"),
    # U
    ("udon", "うどん", "ウドン", "うどん", "thick wheat flour noodles", "Food & Dining"),
    ("umeboshi", "うめぼし", "ウメボシ", "梅干し", "pickled salt plum", "Food & Dining"),
    ("umeshu", "うめしゅ", "ウメシュ", "梅酒", "sweet Japanese plum liqueur", "Food & Dining"),
    ("unadon", "うなどん", "ウナドン", "鰻丼", "grilled eel rice bowl", "Food & Dining"),
    ("unajuu", "うなじゅう", "ウナジュウ", "鰻重", "broiled eel in tiered lacquer box", "Food & Dining"),
    ("uni", "うに", "ウニ", "海胆", "sea urchin gonads / uni sashimi", "Food & Dining"),
    # W
    ("waagyuu", "わぎゅう", "ワギュウ", "和牛", "premium Japanese beef", "Food & Dining"),
    ("wakame", "わかめ", "ワカメ", "若布", "wakame seaweed", "Food & Dining"),
    ("warabimochi", "わらびもち", "ワラビモチ", "わらび餅", "bracken starch mochi with kinako", "Food & Dining"),
    ("wasabi", "わさび", "ワサビ", "山葵", "Japanese spicy green horseradish", "Food & Dining"),
    # Y
    ("yakisoba", "やきそば", "ヤキソバ", "焼きそば", "fried noodles with cabbage and pork", "Food & Dining"),
    ("yakitori", "やきとり", "ヤキトリ", "焼き鳥", "charcoal grilled chicken skewers", "Food & Dining"),
    ("yakiniku", "やきにく", "ヤキニク", "焼肉", "grilled meat barbecue", "Food & Dining"),
    ("yokan", "ようかん", "ヨウカン", "羊羹", "sweet thick red bean jelly block", "Food & Dining"),
    ("yudofu", "ゆどうふ", "ユドウフ", "湯豆腐", "hot boiled tofu pot", "Food & Dining"),
    ("yuzu", "ゆず", "ユズ", "柚子", "aromatic yuzu citrus fruit", "Food & Dining"),
    ("yuzukoshou", "ゆずこしょう", "ユズコショウ", "柚子胡椒", "yuzu peel and chili pepper paste", "Food & Dining"),
    # Z
    ("zarusoba", "ざるそば", "ザルソバ", "ざる蕎麦", "chilled soba noodles on bamboo tray", "Food & Dining"),
    ("zenzai", "ぜんざい", "ゼンザイ", "善哉", "warm sweet azuki bean soup with mochi", "Food & Dining"),
    ("zousui", "ぞうすい", "ゾウスイ", "雑炊", "rice porridge in seasoned soup", "Food & Dining")
]
