# People, Roles, Professions, Relationships, Body & Health, Education, Society
DATA = [
    # A
    ("akachan", "あかちゃん", "アカチャン", "赤ちゃん", "baby / infant", "People & Family"),
    ("akubi", "あくび", "アクビ", "欠伸", "yawn", "Body & Health"),
    ("ane", "あね", "アネ", "姉", "older sister (humble)", "People & Family"),
    ("ani", "あに", "アニ", "兄", "older brother (humble)", "People & Family"),
    ("anata", "あなた", "アナタ", "貴方", "you (polite)", "People & Family"),
    ("anesthesiologist", "ますいかい", "マスイカイ", "麻酔科医", "anesthesiologist", "People & Family"),
    ("animeeta", "あにめーたー", "アニメーター", "アニメーター", "animator", "School & Work"),
    ("aniki", "あにき", "アニキ", "兄貴", "older brother / big bro", "People & Family"),
    ("annaijo", "あんないじょ", "アンナイジョ", "案内所", "information desk", "Travel & Places"),
    ("annainin", "あんないにん", "アンナイニン", "案内人", "guide / usher", "People & Family"),
    ("ashikubi", "あしくび", "アシクビ", "足首", "ankle", "Body & Health"),
    ("ashinoyubi", "あしのゆび", "アシノユビ", "足の指", "toe", "Body & Health"),
    ("ashikase", "あしかせ", "アシカセ", "足枷", "shackles / fetters", "Culture & Society"),
    ("atama", "あたま", "アタマ", "頭", "head / brain", "Body & Health"),
    # B
    ("baaba", "ばあば", "バアバ", "祖母", "grandma (affectionate)", "People & Family"),
    ("baaten", "ばーてんだー", "バーテンダー", "バーテンダー", "bartender", "People & Family"),
    ("babaa", "ばばあ", "ババア", "婆", "old woman (informal)", "People & Family"),
    ("bakkuen", "ばっくえんど", "バックエンド", "バックエンド", "backend engineering", "School & Work"),
    ("bando man", "ばんどまん", "バンドマン", "バンドマン", "band musician", "People & Family"),
    ("bengoshi", "べんごし", "ベンゴシ", "弁護士", "lawyer / attorney", "People & Family"),
    ("bijutsuka", "びじゅつか", "ビジュツカ", "美術家", "fine artist", "People & Family"),
    ("biyoushi", "びようし", "ビヨウシ", "美容師", "hairdresser / beautician", "People & Family"),
    ("boushisou", "ぼうはん", "ボウハン", "防犯", "crime prevention", "Culture & Society"),
    ("buchou", "ぶちょう", "ブチョウ", "部長", "department manager / director", "School & Work"),
    ("bunka", "ぶんか", "ブンカ", "文化", "culture", "Culture & Society"),
    ("bunkazai", "ぶんかざい", "ブンカザイ", "文化財", "cultural property / national treasure", "Culture & Society"),
    # C
    ("chekkua", "ちぇっかー", "チェッカー", "チェッカー", "inspector / supermarket cashier", "People & Family"),
    ("chichi", "ちち", "チチ", "父", "father (humble)", "People & Family"),
    ("chikara", "ちから", "チカラ", "力", "strength / power / force", "Body & Health"),
    ("chinou", "ちのう", "チノウ", "知能", "intelligence / intellect", "Emotions & Mind"),
    ("chiryou", "ちりょう", "チリョウ", "治療", "medical treatment / therapy", "Body & Health"),
    ("chiwa", "ちわ", "チワ", "痴話", "lovers' quarrel", "Social & Communication"),
    # D
    ("daihyou", "だいひょう", "ダイヒョウ", "代表", "representative / delegate", "School & Work"),
    ("daigakusei", "だいがくせい", "ダイガクセイ", "大学生", "university student", "School & Work"),
    ("daiku", "だいく", "ダイク", "大工", "carpenter", "People & Family"),
    ("daitouryou", "だいとうりょう", "ダイトウリョウ", "大統領", "president (of a country)", "People & Family"),
    ("dansei", "だんせい", "ダンセイ", "男性", "male / gentleman", "People & Family"),
    ("dantai", "だんたい", "ダンタイ", "団体", "group / organization", "Culture & Society"),
    ("dansa", "だんさー", "ダンサー", "ダンサー", "dancer", "People & Family"),
    ("dekigoto", "できごと", "デキゴト", "出来事", "event / incident / happening", "Daily Life"),
    ("denryoku", "でんりょく", "デンリョク", "電力", "electric power", "Science & Nature"),
    ("deshi", "でし", "デシ", "弟子", "disciple / apprentice / pupil", "People & Family"),
    ("dokutaa", "どくたー", "ドクター", "ドクター", "doctor / PhD", "People & Family"),
    ("dokusha", "どくしゃ", "ドクシャ", "読者", "reader / subscriber", "People & Family"),
    ("doukyuusei", "どうきゅうせい", "ドウキュウセイ", "同級生", "classmate", "People & Family"),
    ("douryou", "どうりょう", "ドウリョウ", "同僚", "work coworker / colleague", "People & Family"),
    # E
    ("eiyoushi", "えいようし", "エイヨウシ", "栄養士", "nutritionist / dietitian", "People & Family"),
    ("enjinia", "えんじにあ", "エンジニア", "エンジニア", "engineer / software developer", "People & Family"),
    ("enzetsu", "えんぜつ", "エンゼツ", "演説", "speech / address / oration", "Social & Communication"),
    ("erabarebi", "えらばれしもの", "エラバレシモノ", "選ばれし者", "chosen one", "Culture & Society"),
    ("ereki", "えれき", "エレキ", "エレキ", "electric guitar / electronics", "Hobbies & Media"),
    # F
    ("fujin", "ふじん", "フジン", "夫人", "madam / lady / wife", "People & Family"),
    ("fujinka", "ふじんか", "フジンカ", "婦人科", "gynecology department", "Body & Health"),
    ("fukainin", "ふかいにん", "フカイニン", "深い人", "profound deep person", "People & Family"),
    ("fukusou", "ふくそう", "フクソウ", "服装", "attire / clothing outfit", "Clothes & Fashion"),
    ("fuufu", "ふうふ", "フウフ", "夫婦", "married couple / husband and wife", "People & Family"),
    ("furuuto", "ふるーと", "フルート", "フルート", "flute (instrument)", "Hobbies & Media"),
    ("furonto", "ふろんと", "フロント", "フロント", "hotel reception front desk", "Travel & Places"),
    # G
    ("gaka", "がか", "ガカ", "画家", "painter / artist", "People & Family"),
    ("gakusei", "がくせい", "ガクセイ", "学生", "student", "People & Family"),
    ("gakusha", "がくしゃ", "ガクシャ", "学者", "scholar / academic researcher", "People & Family"),
    ("gakuchou", "がくちょう", "ガクチョウ", "学長", "university president", "People & Family"),
    ("ganka", "がんか", "ガンカ", "眼科", "ophthalmology / eye doctor clinic", "Body & Health"),
    ("gankou", "がんこう", "ガンコウ", "眼孔", "eye socket / eye orbit", "Body & Health"),
    ("gekijou", "げきじょう", "ゲキジョウ", "劇場", "theater / auditorium", "Culture & Society"),
    ("geinoujin", "げいのうじん", "ゲイノウジン", "芸能人", "entertainer / celebrity / TV personality", "People & Family"),
    ("gishi", "ぎし", "ギシ", "技師", "technician / technical specialist", "People & Family"),
    ("gitaarisuto", "ぎたーりすと", "ギタリスト", "ギタリスト", "guitarist", "People & Family"),
    ("gousei", "ごうせい", "ゴウセイ", "剛性", "rigidity / stiffness", "Science & Nature"),
    ("gunjin", "ぐんじん", "グンジン", "軍人", "military officer / soldier", "People & Family"),
    ("gyomin", "ぎょみん", "ギョミン", "漁民", "fisherfolk / fisherman", "People & Family"),
    # H
    ("ha", "は", "ハ", "歯", "tooth / teeth", "Body & Health"),
    ("hachigatsu", "はちがつ", "ハチガツ", "八月", "August", "Time & Calendar"),
    ("haisha", "はいしゃ", "ハイシャ", "歯医者", "dentist", "People & Family"),
    ("haiyuu", "はいゆう", "ハイユウ", "俳優", "actor / performer", "People & Family"),
    ("hakase", "はかせ", "ハカセ", "博士", "doctor / PhD / erudite scholar", "People & Family"),
    ("han", "はん", "ハン", "班", "squad / group / team", "School & Work"),
    ("hana", "はな", "ハナ", "鼻", "nose", "Body & Health"),
    ("hanayome", "はなよめ", "ハナヨメ", "花嫁", "bride", "People & Family"),
    ("hanmuku", "はなむけ", "ハナムケ", "餞", "farewell parting gift", "Culture & Society"),
    ("hanshi", "はんし", "ハンシ", "藩士", "feudal samurai retainer", "Culture & Society"),
    ("hatachi", "はたち", "ハタチ", "二十歳", "twenty years of age (coming of age)", "People & Family"),
    ("hatake", "はたけ", "ハタケ", "畑", "cultivated field / vegetable garden", "Travel & Places"),
    ("hifu", "ひふ", "ヒフ", "皮膚", "skin / epidermis", "Body & Health"),
    ("hifuka", "ひふか", "ヒフカ", "皮膚科", "dermatology clinic", "Body & Health"),
    ("higemusha", "ひげ", "ヒゲ", "髭", "beard / mustache / facial hair", "Body & Health"),
    ("hiji", "ひじ", "ヒジ", "肘", "elbow", "Body & Health"),
    ("hikitsugi", "ひきつぎ", "ヒキツギ", "引き継ぎ", "handover of duties", "School & Work"),
    ("hikouki", "ひこうき", "ヒコウキ", "飛行機", "airplane", "Travel & Places"),
    ("hiza", "ひざ", "ヒザ", "膝", "knee / lap", "Body & Health"),
    ("hizakozou", "ひざこぞう", "ヒザコゾウ", "膝小僧", "kneecap", "Body & Health"),
    ("hitorigurashi", "ひとりぐらし", "ヒトリグラシ", "一人暮らし", "living alone / bachelor life", "Daily Life"),
    ("hoken", "ほけん", "ホケン", "保険", "medical / health insurance", "Culture & Society"),
    ("honmono", "ほんもの", "ホンモノ", "本物", "genuine article / real thing", "Culture & Society"),
    ("hoikushi", "ほいくし", "ホイクシ", "保育士", "nursery school teacher / childcare worker", "People & Family"),
    ("hone", "ほね", "ホネ", "骨", "bone", "Body & Health"),
    ("houhou", "ほうほう", "ホウホウ", "方法", "method / technique", "School & Work"),
    ("hyoujou", "ひょうじょう", "ヒョウジョウ", "表情", "facial expression", "Emotions & Mind"),
    # I
    ("ibukuro", "いぶくろ", "イブクロ", "胃袋", "stomach organ", "Body & Health"),
    ("igaku", "いがく", "イガク", "医学", "medical science / medicine", "School & Work"),
    ("iinkai", "いいんかい", "イインカイ", "委員会", "committee / board", "School & Work"),
    ("ika", "いか", "イカ", "医科", "medical department", "Body & Health"),
    ("imouto", "いもうと", "イモウト", "妹", "younger sister", "People & Family"),
    ("insho", "いんしょう", "インショウ", "印象", "impression", "Emotions & Mind"),
    ("insutarakuta", "いんすとらくたー", "インストラクター", "インストラクター", "fitness instructor / trainer", "People & Family"),
    ("itoko", "いとこ", "イトコ", "従兄弟", "cousin", "People & Family"),
    ("izou", "いぞう", "イゾウ", "遺贈", "bequest / inheritance", "Culture & Society"),
    # J
    ("jieitai", "じえいたい", "ジエイタイ", "自衛隊", "Japan Self-Defense Forces", "Culture & Society"),
    ("jikka", "じっか", "ジッカ", "実家", "one's parents' home / family home", "People & Family"),
    ("jinbutsu", "じんぶつ", "ジンブツ", "人物", "person / character / figure", "People & Family"),
    ("jinjika", "じんじか", "ジンジカ", "人事課", "HR human resources section", "School & Work"),
    ("jinzou", "じんぞう", "ジンゾウ", "腎臓", "kidney organ", "Body & Health"),
    ("jishin", "じしん", "ジシン", "自信", "self-confidence", "Emotions & Mind"),
    ("josei", "じょせい", "ジョセイ", "女性", "woman / female", "People & Family"),
    ("joshu", "じょしゅ", "ジョシュ", "助手", "assistant / helper / tutor", "People & Family"),
    ("juui", "じゅうい", "ジュウイ", "獣医", "veterinarian", "People & Family"),
    ("juumin", "じゅうみん", "ジュウミン", "住民", "resident / citizen", "People & Family"),
    # K
    ("kaigoshi", "かいごし", "カイゴシ", "介護士", "caregiver / nursing care worker", "People & Family"),
    ("kaisenshi", "かいせんし", "カイセンシ", "海戦士", "naval warrior", "Culture & Society"),
    ("kakari", "かかり", "カカリ", "係", "person in charge / official", "School & Work"),
    ("kakushin", "かくしん", "カクシン", "確信", "conviction / strong belief", "Emotions & Mind"),
    ("kanbu", "かんぶ", "カンブ", "幹部", "executive management / key official", "School & Work"),
    ("kanja", "かんじゃ", "カンジャ", "患者", "patient / sick person", "People & Family"),
    ("kankyakusen", "かんきゃく", "カンキャク", "観客", "spectators / audience", "People & Family"),
    ("kanren", "かんれん", "カンレン", "関連", "relation / relevance / connection", "School & Work"),
    ("kanrinin", "かんりにん", "カンリニン", "管理人", "caretaker / building manager / admin", "People & Family"),
    ("kanzou", "かんぞう", "カンゾウ", "肝臓", "liver organ", "Body & Health"),
    ("kaoshou", "かお", "カオ", "顔", "human face", "Body & Health"),
    ("karada", "からだ", "カラダ", "体", "human body / health", "Body & Health"),
    ("karasuma", "からすま", "カラスマ", "烏丸", "crow circle / Kyoto boulevard", "Travel & Places"),
    ("kashu", "かしゅ", "カシュ", "歌手", "singer / vocalist", "People & Family"),
    ("kata", "かた", "カタ", "肩", "shoulder", "Body & Health"),
    ("kazoku", "かぞく", "カゾク", "家族", "family", "People & Family"),
    ("keisatsukan", "けいさつかん", "ケイサツカン", "警察官", "police officer", "People & Family"),
    ("kemuri", "けむり", "ケムリ", "煙", "smoke", "Nature & Weather"),
    ("kenchitsuka", "けんちくか", "ケンチクカ", "建築家", "architect", "People & Family"),
    ("kenkyuusha", "けんきゅうしゃ", "ケンキュウシャ", "研究者", "researcher / scientist", "People & Family"),
    ("ketsuekigata", "けつえきがた", "ケツエキガタ", "血液型", "blood type (A, B, O, AB)", "Body & Health"),
    ("kodomo", "こども", "コドモ", "子供", "child / children", "People & Family"),
    ("koibito", "こいびと", "コイビト", "恋人", "sweetheart / boyfriend / girlfriend", "People & Family"),
    ("kokoro", "こころ", "ココロ", "心", "heart / mind / spirit", "Emotions & Mind"),
    ("kouhai", "こうはい", "コウハイ", "後輩", "junior colleague / younger student", "People & Family"),
    ("koumuin", "こうむいん", "コウムイン", "公務員", "civil servant / public employee", "People & Family"),
    ("koushi", "こうし", "コウシ", "講師", "lecturer / university instructor", "People & Family"),
    ("kotsuban", "こつばん", "コツバン", "骨盤", "pelvis", "Body & Health"),
    ("kuchibiru", "くちびる", "クチビル", "唇", "lips", "Body & Health"),
    ("kubi", "くび", "クビ", "首", "neck", "Body & Health"),
    ("kuraberu", "くらぶ", "クラブ", "クラブ", "club / society", "School & Work"),
    ("kyaku", "きゃく", "キャク", "客", "guest / customer / client", "People & Family"),
    ("kyoushi", "きょうし", "キョウシ", "教師", "schoolteacher", "People & Family"),
    ("kyoudai", "きょうだい", "キョウダイ", "兄弟", "siblings / brothers", "People & Family"),
    # M
    ("mago", "まご", "マゴ", "孫", "grandchild", "People & Family"),
    ("magomusume", "まごむすめ", "マゴムスメ", "孫娘", "granddaughter", "People & Family"),
    ("magomusuko", "まごむすこ", "マゴムスコ", "孫息子", "grandson", "People & Family"),
    ("manaa", "まなー", "マナー", "マナー", "manners / etiquette", "Culture & Society"),
    ("maneeja", "まねーじゃー", "マネージャー", "マネージャー", "business manager", "People & Family"),
    ("matawa", "また", "マタ", "股", "crotch / thigh joint", "Body & Health"),
    ("mayu", "まゆ", "マユ", "眉", "eyebrow", "Body & Health"),
    ("me", "め", "メ", "目", "eye / vision", "Body & Health"),
    ("meishi", "めいし", "メイシ", "名刺", "business card", "School & Work"),
    ("meisou", "めいそう", "メイソウ", "瞑想", "meditation / mindfulness", "Emotions & Mind"),
    ("mimi", "みみ", "ミミ", "耳", "ear / hearing", "Body & Health"),
    ("musuko", "むすこ", "ムスコ", "息子", "son", "People & Family"),
    ("musume", "むすめ", "ムスメ", "娘", "daughter", "People & Family"),
    # N
    ("nakama", "なかま", "ナカマ", "仲間", "comrade / fellow companion", "People & Family"),
    ("ninshin", "にんしん", "ニンシン", "妊娠", "pregnancy", "Body & Health"),
    ("nou", "のう", "ノウ", "脳", "brain", "Body & Health"),
    ("nodo", "のど", "ノド", "喉", "throat", "Body & Health"),
    # O
    ("oba", "おば", "オバ", "伯母", "aunt", "People & Family"),
    ("obaasan", "おばあさん", "オバアサン", "お祖母さん", "grandmother / elderly woman", "People & Family"),
    ("ojousan", "おじょうさん", "オジョウサン", "お嬢さん", "young lady / daughter (polite)", "People & Family"),
    ("oji", "おじ", "オジ", "伯父", "uncle", "People & Family"),
    ("ojiisan", "おじいさん", "オジイサン", "お祖父さん", "grandfather / elderly man", "People & Family"),
    ("okane", "おかね", "オカネ", "お金", "money / funds", "Shopping & Money"),
    ("okusan", "おくさん", "オクサン", "奥さん", "wife (polite, someone else's)", "People & Family"),
    ("onaka", "おなか", "オナカ", "お腹", "belly / stomach", "Body & Health"),
    ("oneesan", "おねえさん", "オネエサン", "お姉さん", "older sister (polite)", "People & Family"),
    ("oniisan", "おにいさん", "オニイサン", "お兄さん", "older brother (polite)", "People & Family"),
    ("otohto", "おとうと", "オトウト", "弟", "younger brother", "People & Family"),
    ("otona", "おとな", "オトナ", "大人", "adult / mature person", "People & Family"),
    ("otto", "おっと", "オット", "夫", "husband (humble)", "People & Family"),
    ("oyaji", "おやじ", "オヤジ", "親父", "old man / father (colloquial)", "People & Family"),
    # P
    ("pairotto", "ぱいろっと", "パイロット", "パイロット", "airline pilot", "People & Family"),
    ("purogurama", "ぷろぐらまー", "プログラマー", "プログラマー", "programmer / software coder", "People & Family"),
    ("purezento", "ぷれぜんと", "プレゼント", "プレゼント", "gift / present", "Culture & Society"),
    # R
    ("rengou", "れんごう", "レンゴウ", "連合", "union / alliance / coalition", "Culture & Society"),
    ("ren'ai", "れんあい", "レンアイ", "恋愛", "romantic love", "Emotions & Mind"),
    ("rijichou", "りじちょう", "リジチョウ", "理事長", "board chairperson", "People & Family"),
    ("riron", "りろん", "リロン", "理論", "theory", "School & Work"),
    ("ryoushin", "りょうしん", "リョウシン", "両親", "both parents", "People & Family"),
    # S
    ("saiban", "さいばん", "サイバン", "裁判", "trial / judgment in court", "Culture & Society"),
    ("saibankan", "さいばんかん", "サイバンカン", "裁判官", "judge / justice", "People & Family"),
    ("sakka", "さっか", "サッカ", "作家", "novelist / writer", "People & Family"),
    ("seito", "せいと", "セイト", "生徒", "school pupil", "People & Family"),
    ("sekai", "せかい", "セカイ", "世界", "world / universe / society", "Culture & Society"),
    ("senpai", "せんぱい", "センパイ", "先輩", "senior classmate / mentor", "People & Family"),
    ("sensei", "せんせい", "センセイ", "先生", "teacher / master / doctor", "People & Family"),
    ("senshu", "せんしゅ", "センシュ", "選手", "athlete / player", "People & Family"),
    ("shachou", "しゃちょう", "シャチョウ", "社長", "company president / CEO", "People & Family"),
    ("shain", "しゃいん", "シャイン", "社員", "company employee", "People & Family"),
    ("shimin", "しみん", "シミン", "市民", "citizen / townsfolk", "People & Family"),
    ("shin'yuu", "しんゆう", "シンユウ", "親友", "best friend / bosom friend", "People & Family"),
    ("shinrui", "しんるい", "シンルイ", "親類", "relatives / kinfolk", "People & Family"),
    ("shinzou", "しんぞう", "シンゾウ", "心臓", "heart (organ)", "Body & Health"),
    ("shokunin", "しょくにん", "ショクニン", "職人", "craftsman / master artisan", "People & Family"),
    ("shounen", "しょうねん", "ショウネン", "少年", "boy / youth", "People & Family"),
    ("shoujo", "しょうじょ", "ショウジョ", "少女", "young girl", "People & Family"),
    ("shukudai", "しゅくだい", "シュクダイ", "宿題", "homework assignment", "School & Work"),
    ("shuto", "しゅと", "シュト", "首都", "capital city", "Travel & Places"),
    ("sosen", "そせん", "ソセン", "祖先", "ancestor", "People & Family"),
    ("sutaffu", "すたっふ", "スタッフ", "スタッフ", "staff member", "People & Family"),
    # T
    ("taikou", "たいこう", "タイコウ", "対向", "opposition / rivalry", "Culture & Society"),
    ("tannin", "たんにん", "タンニン", "担任", "homeroom teacher in charge", "People & Family"),
    ("tarou", "たろう", "タロウ", "太郎", "eldest son / Taro (common name)", "People & Family"),
    ("ten'in", "てんいん", "テンイン", "店員", "store clerk / shop assistant", "People & Family"),
    ("tensai", "てんさい", "テンサイ", "天才", "genius / prodigy", "People & Family"),
    ("tomodachi", "ともだち", "トモダチ", "友達", "friend / companion", "People & Family"),
    ("tsuma", "つま", "ツマ", "妻", "wife (humble)", "People & Family"),
    # U
    ("ude", "うで", "ウデ", "腕", "arm / skill capability", "Body & Health"),
    ("unten shu", "うんてんしゅ", "ウンテンシュ", "運転手", "driver / chauffeur", "People & Family"),
    # Y
    ("yakuin", "やくいん", "ヤクイン", "役員", "officer / executive board member", "People & Family"),
    ("yakusha", "やくしゃ", "ヤクシャ", "役者", "stage actor / performer", "People & Family"),
    ("yome", "よめ", "ヨメ", "嫁", "bride / daughter-in-law", "People & Family"),
    ("yubi", "ゆび", "ユビ", "指", "finger / toe", "Body & Health"),
    ("yubina", "ゆびわ", "ユビワ", "指輪", "finger ring", "Clothes & Fashion"),
    # Z
    ("zaibatsu", "ざいばつ", "ザイバツ", "財閥", "financial clique / conglomerate", "Culture & Society"),
    ("zenkoku", "ぜんこく", "ゼンコク", "全国", "whole nation / nationwide", "Travel & Places")
]
