# Culture, Traditions, Business, Economy, Hobbies, Media, Emotions, Abstract
DATA = [
    # A
    ("aidentiti", "あいでんてぃてぃ", "アイデンティティ", "同一性", "identity", "Culture & Society"),
    ("aikouka", "あいこうか", "アイコウカ", "愛好家", "enthusiast / lover of a hobby", "Hobbies & Media"),
    ("aisatsu", "あいさつ", "アイサツ", "挨拶", "greeting / formal address", "Social & Communication"),
    ("aisetsu", "あいせつ", "アイセツ", "哀切", "pathetic sorrow / grief", "Emotions & Mind"),
    ("aishou", "あいしょう", "アイショウ", "相性", "compatibility / chemistry", "Social & Communication"),
    ("aizu", "あいず", "アイズ", "合図", "sign / cue / signal", "Daily Life"),
    ("akugi", "あくぎ", "アクギ", "悪戯", "mischief / practical joke", "Daily Life"),
    ("akushu", "あくしゅ", "アクシュ", "握手", "handshake", "Social & Communication"),
    ("anshin", "あんしん", "アンシン", "安心", "peace of mind / relief", "Emotions & Mind"),
    ("anshou", "あんしょう", "アンショウ", "暗礁", "sunken reef / unforeseen hurdle", "School & Work"),
    ("anzen", "あんぜん", "アンゼン", "安全", "safety / security", "Culture & Society"),
    ("aomori", "あおもり", "アオモリ", "青森", "Aomori prefecture", "Travel & Places"),
    ("araburu", "あらぶる", "アラブル", "荒ぶる", "raging wild spirit", "Culture & Society"),
    ("araware", "あらわれ", "アラワレ", "現れ", "manifestation / expression", "Culture & Society"),
    ("arigatasa", "ありがたさ", "アリガタサ", "有り難さ", "blessedness / value / gratitude", "Emotions & Mind"),
    ("asobi", "あそび", "アソビ", "遊び", "play / recreation / game", "Hobbies & Media"),
    ("atsuryoku", "あつりょく", "アツリョク", "圧力", "pressure / stress", "Science & Nature"),
    # B
    ("baai", "ばあい", "バアイ", "場合", "case / situation / occasion", "Daily Life"),
    ("bamen", "ばめん", "バメン", "場面", "scene / situation in a story", "Hobbies & Media"),
    ("bangumi", "ばんぐみ", "バングミ", "番組", "television or radio program", "Hobbies & Media"),
    ("bijinesu", "びじねす", "ビジネス", "ビジネス", "business enterprise", "School & Work"),
    ("bijon", "びじょん", "ビジョン", "ビジョン", "vision / future outlook", "School & Work"),
    ("boken", "ぼうけん", "ボウケン", "冒険", "adventure / quest", "Hobbies & Media"),
    ("bon'odori", "ぼんおどり", "ボンオドリ", "盆踊り", "Bon festival folk dance", "Culture & Society"),
    ("bonsai", "ぼんさい", "ボンサイ", "盆栽", "bonsai miniature tree cultivation", "Culture & Society"),
    ("boueki", "ぼうえき", "ボウエキ", "貿易", "foreign international trade", "School & Work"),
    ("bungaku", "ぶんがく", "ブンガク", "文学", "literature", "Hobbies & Media"),
    ("bunmei", "ぶんめい", "ブンメイ", "文明", "civilization", "Culture & Society"),
    ("bunshou", "ぶんしょう", "ブンショウ", "文章", "sentence / writing passage", "School & Work"),
    ("butai", "ぶたい", "ブタイ", "舞台", "stage / theatrical scene", "Culture & Society"),
    ("budou", "ぶどう", "ブドウ", "武道", "martial arts", "Culture & Society"),
    ("buyou", "ぶよう", "ブヨウ", "舞踊", "traditional dance", "Culture & Society"),
    # C
    ("chaneri", "ちゃんねる", "チャンネル", "チャンネル", "broadcast TV channel", "Hobbies & Media"),
    ("chano yu", "ちゃのゆ", "チャノユ", "茶の湯", "traditional tea ceremony", "Culture & Society"),
    ("chanto", "ちゃんと", "チャント", "ちゃんと", "properly / precisely", "Daily Life"),
    ("charenji", "ちゃれんじ", "チャレンジ", "チャレンジ", "challenge / trial", "School & Work"),
    ("chiiki", "ちいき", "チイキ", "地域", "region / local area", "Travel & Places"),
    ("chisiki", "ちしき", "チシキ", "知識", "knowledge / information", "School & Work"),
    ("chitsujo", "ちつじょ", "チツジョ", "秩序", "order / public order", "Culture & Society"),
    ("chouwa", "ちょうわ", "チョウワ", "調和", "harmony / balance", "Culture & Society"),
    ("chuushou", "ちゅうしょう", "チュウショウ", "抽象", "abstraction / conceptual idea", "School & Work"),
    # D
    ("danketsu", "だんけつ", "ダンケツ", "団結", "solidarity / union of minds", "Culture & Society"),
    ("dansu", "だんす", "ダンス", "ダンス", "dancing", "Hobbies & Media"),
    ("deeta", "でーた", "データ", "データ", "digital data", "School & Work"),
    ("dentou", "でんとう", "デントウ", "伝統", "tradition / heritage", "Culture & Society"),
    ("dezaing", "でざいん", "デザイン", "デザイン", "graphic or industrial design", "Hobbies & Media"),
    ("dokushou", "どくしょう", "ドクショウ", "独唱", "vocal vocal solo", "Hobbies & Media"),
    ("dokusho", "どくしょ", "ドクショ", "読書", "reading books", "Hobbies & Media"),
    ("doryoku", "どりょく", "ドリョク", "努力", "effort / great diligence", "Emotions & Mind"),
    ("douga", "どうが", "ドウガ", "動画", "video / motion picture clip", "Hobbies & Media"),
    ("douwa", "どうわ", "ドウワ", "童話", "fairy tale / children's story", "Hobbies & Media"),
    # E
    ("eiga", "えいが", "エイガ", "映画", "motion picture film / movie", "Hobbies & Media"),
    ("eigakan", "えいがかん", "エイガカン", "映画館", "movie theater / cinema", "Hobbies & Media"),
    ("eigo", "えいご", "エイゴ", "英語", "English language", "School & Work"),
    ("eikyou", "えいきょう", "エイキョウ", "影響", "influence / effect", "Culture & Society"),
    ("enjuku", "えんじゅく", "エンジュク", "円熟", "maturity / mellow perfection", "Culture & Society"),
    ("ennichi", "えんにち", "エンニチ", "縁日", "temple fair day / festival", "Culture & Society"),
    ("ensou", "えんそう", "エンソウ", "演奏", "musical performance", "Hobbies & Media"),
    # F
    ("fashon", "ふぁっしょん", "ファッション", "ファッション", "fashion style", "Clothes & Fashion"),
    ("fuukei", "ふうけい", "フウケイ", "風景", "scenery / landscape view", "Travel & Places"),
    ("fuuryuu", "ふうりゅう", "フウリュウ", "風流", "elegance / aesthetic taste", "Culture & Society"),
    ("fuuzoku", "ふうぞく", "フウゾク", "風俗", "manners / customs", "Culture & Society"),
    # G
    ("gagaku", "ががく", "ガガク", "雅楽", "ancient imperial court music", "Culture & Society"),
    ("gakkou", "がっこう", "ガッコウ", "学校", "school", "School & Work"),
    ("gakki", "がっき", "ガッキ", "楽器", "musical instrument", "Hobbies & Media"),
    ("gasshou", "がっしょう", "ガッショウ", "合唱", "choir / chorus singing", "Hobbies & Media"),
    ("geijutsu", "げいじゅつ", "ゲイジュツ", "芸術", "fine arts / artistry", "Hobbies & Media"),
    ("geisha", "げいしゃ", "ゲイシャ", "芸者", "geisha artist", "Culture & Society"),
    ("genba", "げんば", "ゲンバ", "現場", "actual site / scene / workshop", "School & Work"),
    ("gijutsu", "ぎじゅつ", "ギジュツ", "技術", "technology / engineering skill", "School & Work"),
    ("gimon", "ぎもん", "ギモン", "疑問", "doubt / question / inquiry", "School & Work"),
    ("giri", "ぎり", "ギリ", "義理", "sense of duty / social obligation", "Culture & Society"),
    # H
    ("haiku", "はいく", "ハイク", "俳句", "17-syllable haiku poetry", "Culture & Society"),
    ("hajimari", "はじまり", "ハジマリ", "始まり", "beginning / dawn / inception", "Time & Calendar"),
    ("hamonii", "はーもにー", "ハーモニー", "ハーモニー", "harmony", "Hobbies & Media"),
    ("hanabi", "はなび", "ハナビ", "花火", "fireworks display", "Culture & Society"),
    ("hanashiai", "はなしあい", "ハナシアイ", "話し合い", "discussion / conference", "Social & Communication"),
    ("happyousei", "はっぴょう", "ハッピョウ", "発表", "presentation / announcement", "School & Work"),
    ("hatsumei", "はつめい", "ハツメイ", "発明", "invention", "School & Work"),
    ("heikou", "へいこう", "ヘイコウ", "平衡", "equilibrium / balance", "Science & Nature"),
    ("heiwa", "へいわ", "ヘイワ", "平和", "world peace / tranquility", "Culture & Society"),
    ("henka", "へんか", "ヘンカ", "変化", "change / transformation", "Culture & Society"),
    ("hikaku", "ひかく", "ヒカク", "比較", "comparison", "School & Work"),
    ("hizuke", "ひづけ", "ヒヅケ", "日付", "date on calendar", "Time & Calendar"),
    ("hangeki", "はんげき", "ハンゲキ", "反撃", "counterattack", "Culture & Society"),
    ("honki", "ほんき", "ホンキ", "本気", "earnestness / dead seriousness", "Emotions & Mind"),
    ("hontou", "ほんとう", "ホントウ", "本当", "truth / reality", "Daily Life"),
    ("hyougen", "ひょうげん", "ヒョウゲン", "表現", "expression / representation", "Culture & Society"),
    # I
    ("ibento", "いべんと", "イベント", "イベント", "public event / festival gathering", "Culture & Society"),
    ("iken", "いけん", "イケン", "意見", "opinion / perspective", "Social & Communication"),
    ("ikigai", "いきがい", "イキガイ", "生きがい", "purpose in life / reason for being", "Culture & Society"),
    ("ikebana", "いけばな", "イケバナ", "生け花", "traditional flower arrangement", "Culture & Society"),
    ("imi", "いみ", "イミ", "意味", "meaning / significance", "School & Work"),
    ("inori", "いのり", "イノリ", "祈り", "prayer / supplication", "Culture & Society"),
    ("inochi", "いのち", "イノチ", "命", "life / vital spark", "Nature & Animals"),
    ("isshou", "いっしょう", "イッショウ", "一生", "whole lifetime", "Time & Calendar"),
    ("itadakimasu", "いただきます", "イタダキマス", "いただきます", "grateful meal blessing", "Food & Dining"),
    # J
    ("jikan", "じかん", "ジカン", "時間", "time / hours", "Time & Calendar"),
    ("jitsuryoku", "じつりょく", "ジツリョク", "実力", "true capability / merit", "School & Work"),
    ("jiyuu", "じゆう", "ジユウ", "自由", "freedom / liberty", "Culture & Society"),
    ("jouhou", "じょうほう", "ジョウホウ", "情報", "information / data intelligence", "School & Work"),
    ("joushikishin", "じょうしき", "ジョウシキ", "常識", "common sense / accepted norms", "Culture & Society"),
    ("juudou", "じゅうどう", "ジュウドウ", "柔道", "judo martial art", "Culture & Society"),
    # K
    ("kabuki", "かぶき", "カブキ", "歌舞伎", "kabuki classical theater", "Culture & Society"),
    ("kagaku", "かがく", "カガク", "科学", "science / natural science", "School & Work"),
    ("kankou", "かんこう", "カンコウ", "観光", "sightseeing / tourism", "Travel & Places"),
    ("kanji", "かんじ", "カンジ", "漢字", "kanji Chinese characters", "School & Work"),
    ("kanso", "かんそう", "カンソウ", "感想", "impression / personal thoughts", "Social & Communication"),
    ("karate", "からて", "カラテ", "空手", "karate martial art", "Culture & Society"),
    ("keizai", "けいざい", "ケイザイ", "経済", "economy / economics", "Culture & Society"),
    ("kendo", "けんどう", "ケンドウ", "剣道", "kendo swordsmanship", "Culture & Society"),
    ("kibou", "きぼう", "キボウ", "希望", "hope / aspiration", "Emotions & Mind"),
    ("kioku", "きおく", "キオク", "記憶", "memory / recollection", "Emotions & Mind"),
    ("kizuna", "きずな", "キズナ", "絆", "heartfelt bond of affection", "Culture & Society"),
    ("koukoku", "こうこく", "コウコク", "広告", "advertisement / commercial", "Hobbies & Media"),
    ("kyoudou", "きょうどう", "キョウドウ", "共同", "collaboration / partnership", "Culture & Society"),
    # M
    ("manga", "まんが", "マンガ", "漫画", "Japanese comic book / manga", "Hobbies & Media"),
    ("meiyo", "めいよ", "メイヨ", "名誉", "honor / prestige / glory", "Culture & Society"),
    ("mokuteki", "もくてき", "モクテキ", "目的", "purpose / objective / goal", "School & Work"),
    ("monogatari", "ものがたり", "モノガタリ", "物語", "epic tale / story / legend", "Hobbies & Media"),
    ("mottainai", "もったいない", "モッタイナイ", "もったいない", "regret over waste / preciousness", "Culture & Society"),
    # N
    ("nihongo", "にほんご", "ニホンゴ", "日本語", "Japanese language", "Culture & Society"),
    ("noh", "のう", "ノウ", "能", "noh classical drama", "Culture & Society"),
    # O
    ("ongaku", "おんがく", "オンガク", "音楽", "music", "Hobbies & Media"),
    ("origami", "おりがみ", "オリガミ", "折り紙", "origami paper folding art", "Culture & Society"),
    # R
    ("rakugo", "らくご", "ラクゴ", "落語", "comic storytelling monologue", "Culture & Society"),
    ("rekishi", "れきし", "レキシ", "歴史", "history", "Culture & Society"),
    # S
    ("sadou", "さどう", "サドウ", "茶道", "way of tea / tea ceremony", "Culture & Society"),
    ("seikatsu", "せいかつ", "セイカツ", "生活", "daily living life", "Daily Life"),
    ("shakai", "しゃかい", "シャカイ", "社会", "society / community", "Culture & Society"),
    ("shodou", "しょどう", "ショドウ", "書道", "Japanese calligraphy", "Culture & Society"),
    ("shougi", "しょうぎ", "ショウギ", "将棋", "Japanese chess / shogi", "Culture & Society"),
    ("shumi", "しゅみ", "シュミ", "趣味", "hobby / personal pastime", "Hobbies & Media"),
    ("sumo", "すもう", "スモウ", "相撲", "sumo wrestling", "Culture & Society"),
    # T
    ("tanka", "たんか", "タンカ", "短歌", "31-syllable tanka poem", "Culture & Society"),
    ("tegami", "てがみ", "テガミ", "手紙", "postal letter / correspondence", "Social & Communication"),
    # U
    ("ukiyo-e", "うきよえ", "ウキヨエ", "浮世絵", "woodblock prints", "Culture & Society"),
    ("uta", "うた", "ウタ", "歌", "song / melody", "Hobbies & Media"),
    # W
    ("wa", "わ", "ワ", "和", "peace / harmony / Japanese essence", "Culture & Society"),
    ("wadaiko", "わだいこ", "ワダイコ", "和太鼓", "traditional taiko drums", "Culture & Society"),
    ("waka", "わか", "ワカ", "和歌", "classical Japanese court poetry", "Culture & Society"),
    ("washi-paper", "わし", "ワシ", "和紙", "handcrafted Japanese paper", "Culture & Society"),
    # Y
    ("yume", "ゆめ", "ユメ", "夢", "dream / aspiration", "Emotions & Mind"),
    ("yuujou", "ゆうじょう", "ユウジョウ", "友情", "friendship / comradeship", "Social & Communication"),
    ("yuuki", "ゆうき", "ユウキ", "勇気", "courage / bravery", "Emotions & Mind"),
    # Z
    ("zen", "ぜん", "ゼン", "禅", "Zen meditation Buddhism", "Culture & Society")
]
