# Home, Household, Appliances, Furniture, Tools, Personal Care, Daily Items
DATA = [
    # A
    ("airon", "あいろん", "アイロン", "アイロン", "clothes iron", "Home & Living"),
    ("airondai", "あいろんだい", "アイロンダイ", "アイロン台", "ironing board", "Home & Living"),
    ("akusera", "あくせさりー", "アクセサリー", "アクセサリー", "accessory / jewelry", "Clothes & Fashion"),
    ("amadotobi", "あまど", "アマド", "雨戸", "storm shutter", "Home & Living"),
    ("anrakuisu", "あんらくいす", "アンラクイス", "安楽椅子", "easy chair / armchair", "Home & Living"),
    ("arami", "あらーむ", "アラーム", "アラーム", "alarm clock / buzzer", "Tools & Goods"),
    ("aromaoiru", "あろまおいる", "アロマオイル", "アロマオイル", "aroma oil / essential oil", "Daily Life"),
    ("asagohan", "あさごはん", "アサゴハン", "朝ご飯", "breakfast", "Daily Life"),
    ("asatsuyu", "あさつゆ", "アサツユ", "朝露", "morning dew", "Nature & Weather"),
    # B
    ("baba", "ばば", "ババ", "姥", "elderly woman / old grandma", "People & Family"),
    ("bando", "ばんど", "バンド", "バンド", "band / belt", "Clothes & Fashion"),
    ("barukan", "ばるこにー", "バルコニー", "バルコニー", "balcony", "Home & Living"),
    ("basu matto", "ばすまっと", "バスマット", "バスマット", "bath mat", "Home & Living"),
    ("basu taoru", "ばすたおる", "バスタオル", "バスタオル", "bath towel", "Home & Living"),
    ("batto", "ばっと", "バット", "バット", "baseball bat / kitchen tray", "Tools & Goods"),
    ("beddo", "べっど", "ベッド", "ベッド", "bed", "Home & Living"),
    ("beddosupiika", "べっどさいど", "ベッドサイド", "ベッドサイド", "bedside table", "Home & Living"),
    ("biniirubukuro", "びにーるぶくろ", "ビニールブクロ", "ビニール袋", "plastic bag / shopping bag", "Tools & Goods"),
    ("boorumoji", "ぼーるぺん", "ボールペン", "ボールペン", "ballpoint pen", "Tools & Goods"),
    ("boushi", "ぼうし", "ボウシ", "帽子", "hat / cap", "Clothes & Fashion"),
    ("burausu", "ぶらうす", "ブラウス", "ブラウス", "blouse", "Clothes & Fashion"),
    ("burashi", "ぶらし", "ブラシ", "ブラシ", "hairbrush / brush", "Tools & Goods"),
    ("butaniku", "ぶたにく", "ブタニク", "豚肉", "pork meat", "Food & Dining"),
    ("byoubu", "びょうぶ", "ビョウブ", "屏風", "folding decorative screen", "Home & Living"),
    # C
    ("chabudai", "ちゃぶだい", "チャブダイ", "ちゃぶ台", "low Japanese dining table", "Home & Living"),
    ("chakku", "ちゃっく", "チャック", "チャック", "zipper / fastener", "Clothes & Fashion"),
    ("chazutsu", "ちゃづつ", "チャヅツ", "茶筒", "tea caddy / tea canister", "Home & Living"),
    ("chiri tori", "ちりとり", "チリトリ", "塵取り", "dustpan", "Home & Living"),
    ("chouji", "ちょうじ", "チョウジ", "丁子", "clove spice", "Tools & Goods"),
    ("chouchin", "ちょうちん", "チョウチン", "提灯", "paper lantern", "Culture & Society"),
    ("chuubun", "ちゅうしゃき", "チュウシャキ", "注射器", "syringe", "Body & Health"),
    # D
    ("daidokoro", "だいどころ", "ダイドコロ", "台所", "kitchen room", "Home & Living"),
    ("daininguteeburu", "だいにんぐてーぶる", "ダイニングテーブル", "ダイニングテーブル", "dining table", "Home & Living"),
    ("danbou", "だんぼう", "ダンボウ", "暖房", "indoor heating / heater", "Home & Living"),
    ("dappi", "だっぴ", "ダッピ", "脱皮", "shedding / molting skin", "Nature & Animals"),
    ("denchi", "でんち", "デンチ", "電池", "battery", "Tools & Goods"),
    ("dengeki", "でんげき", "デンゲキ", "電撃", "electric shock", "Daily Life"),
    ("denki sutando", "でんきすたんど", "デンキスタンド", "電気スタンド", "desk lamp / study light", "Home & Living"),
    ("denkyuu", "でんきゅう", "デンキュウ", "電球", "light bulb", "Home & Living"),
    ("denshirenji", "でんしれんじ", "デンシレンジ", "電子レンジ", "microwave oven", "Home & Living"),
    ("denshoku", "でんしょく", "デンショク", "電飾", "illuminations / decorative lighting", "Culture & Society"),
    ("doanobu", "どあのぶ", "ドアノブ", "ドアノブ", "door knob / handle", "Home & Living"),
    ("dokushin", "どくしん", "ドクシン", "独身", "unmarried / single person", "People & Family"),
    ("doraibaa", "どらいばー", "ドライバー", "ドライバー", "screwdriver", "Tools & Goods"),
    ("doraiyaa", "どらいやー", "ドライヤー", "ドライヤー", "hair dryer", "Home & Living"),
    ("douko", "どうこ", "ドウコ", "銅壺", "copper water warmer", "Tools & Goods"),
    # E
    ("ea con", "えあこん", "エアコン", "エアコン", "air conditioner / AC", "Home & Living"),
    ("efude", "えふで", "エフデ", "絵筆", "paintbrush for art", "Tools & Goods"),
    ("egao", "えがお", "エガオ", "笑顔", "smiling face / smile", "Emotions & Mind"),
    ("enogu", "えのぐ", "エノグ", "絵の具", "paints / pigments", "Tools & Goods"),
    ("epuron", "えぷろん", "エプロン", "エプロン", "kitchen apron", "Clothes & Fashion"),
    ("erebeetaa", "えれべーたー", "エレベーター", "エレベーター", "elevator", "Travel & Places"),
    ("esukareetaa", "えすかれーたー", "エスカレーター", "エスカレーター", "escalator", "Travel & Places"),
    # F
    ("fashina", "ふぁすなー", "ファスナー", "ファスナー", "zipper / slide fastener", "Clothes & Fashion"),
    ("fuusen", "ふうせん", "フウセン", "風船", "toy balloon", "Hobbies & Media"),
    ("fukin", "ふきん", "フキン", "布巾", "dishcloth / kitchen towel", "Home & Living"),
    ("furoba", "ふろば", "フロバ", "風呂場", "bathroom / bathing room", "Home & Living"),
    ("furoshiki", "ふろしき", "フロシキ", "風呂敷", "traditional wrapping cloth", "Culture & Society"),
    ("fushin", "ふしん", "フシン", "不信", "distrust / suspicion", "Emotions & Mind"),
    ("futon", "ふとん", "フトン", "布団", "Japanese floor mattress futon", "Home & Living"),
    ("fuutou", "ふうとう", "フウトウ", "封筒", "mailing envelope", "Tools & Goods"),
    # G
    ("gabusuru", "がびょう", "ガビョウ", "画鋲", "thumbtack / pushpin", "Tools & Goods"),
    ("gakubuchi", "がくぶち", "ガクブチ", "額縁", "picture frame", "Home & Living"),
    ("gara", "がら", "ガラ", "柄", "pattern / design on fabric", "Clothes & Fashion"),
    ("garasu", "がらす", "ガラス", "ガラス", "window glass / drinking glass", "Home & Living"),
    ("garasudo", "がらすど", "ガラスド", "ガラス戸", "glass sliding door", "Home & Living"),
    ("gomibako", "ごみばこ", "ゴミバコ", "ゴミ箱", "trash can / wastebasket", "Home & Living"),
    ("guraun", "ぐらうんど", "グラウンド", "グラウンド", "athletic sports field / ground", "School & Work"),
    ("gurabu", "ぐろーぶ", "グローブ", "グローブ", "sports glove / mitten", "Clothes & Fashion"),
    ("gunte", "ぐんて", "グンテ", "軍手", "cotton work gloves", "Tools & Goods"),
    # H
    ("haizara", "はいざら", "ハイザラ", "灰皿", "ashtray", "Home & Living"),
    ("hake", "はけ", "ハケ", "刷毛", "brush / basting brush", "Tools & Goods"),
    ("hako", "はこ", "ハコ", "箱", "box / crate", "Tools & Goods"),
    ("hakari", "はかり", "ハカリ", "秤", "measuring scale", "Tools & Goods"),
    ("hanko", "はんこ", "ハンコ", "判子", "personal name seal / stamp", "Tools & Goods"),
    ("hangaa", "はんがー", "ハンガー", "ハンガー", "clothes hanger", "Home & Living"),
    ("hankachi", "はんかち", "ハンカチ", "ハンカチ", "handkerchief", "Clothes & Fashion"),
    ("hanmubaggu", "はんどばっぐ", "ハンドバッグ", "ハンドバッグ", "handbag / purse", "Clothes & Fashion"),
    ("hari", "はり", "ハリ", "針", "sewing needle / watch hand", "Tools & Goods"),
    ("hasami", "はさみ", "ハサミ", "鋏", "scissors", "Tools & Goods"),
    ("hasan", "はさん", "ハサン", "破産", "bankruptcy", "Shopping & Money"),
    ("hibachi", "ひばち", "ヒバチ", "火鉢", "charcoal brazier bowl", "Home & Living"),
    ("hikidashi", "ひきだし", "ヒキダシ", "引き出し", "cabinet drawer", "Home & Living"),
    ("himo", "ひも", "ヒモ", "紐", "cord / string / twine", "Tools & Goods"),
    ("hitasura", "ひたむき", "ヒタムキ", "直向き", "single-minded earnestness", "Emotions & Mind"),
    ("hokori", "ほこり", "ホコリ", "埃", "household dust", "Home & Living"),
    ("hondana", "ほんだな", "ホンダナ", "本棚", "bookshelf / bookcase", "Home & Living"),
    ("honegumi", "ほねぐみ", "ホネグミ", "骨組み", "skeleton / structural framework", "Tools & Goods"),
    ("hoochiki", "ほうちき", "ホウチキ", "報知器", "fire alarm / detector", "Home & Living"),
    ("houki", "ほうき", "ホウキ", "箒", "straw broom", "Home & Living"),
    # I
    ("ichidai", "いちだい", "イチダイ", "一代", "one lifetime / single generation", "Time & Calendar"),
    ("idobata", "いどばた", "イドバタ", "井戸端", "well-side (neighborhood gossip)", "Culture & Society"),
    ("inka", "いんかん", "インカン", "印鑑", "official registered seal stamp", "Tools & Goods"),
    ("inku", "いんく", "インク", "インク", "writing ink", "Tools & Goods"),
    ("iriguchi", "いりぐち", "イリグチ", "入り口", "entrance doorway", "Home & Living"),
    ("ishou", "いしょう", "イショウ", "衣装", "costume / garment", "Clothes & Fashion"),
    ("isu", "いす", "イス", "椅子", "chair / seat", "Home & Living"),
    ("itome", "いとめ", "イトメ", "糸目", "purse strings / kite strings", "Tools & Goods"),
    # J
    ("juutan", "じゅうたん", "ジュウタン", "絨毯", "carpet / floor rug", "Home & Living"),
    ("junbi", "じゅんび", "ジュンビ", "準備", "preparation / readiness", "Daily Life"),
    ("jyaketto", "じゃけっと", "ジャケット", "ジャケット", "formal or casual jacket", "Clothes & Fashion"),
    ("jyawan", "ちゃわん", "チャワン", "茶碗", "rice or tea bowl", "Home & Living"),
    # K
    ("kaban", "かばん", "カバン", "鞄", "bag / briefcase / tote", "Clothes & Fashion"),
    ("kagami", "かがみ", "カガミ", "鏡", "mirror / looking glass", "Home & Living"),
    ("kagi", "かぎ", "カギ", "鍵", "key / padlock", "Tools & Goods"),
    ("kago", "かご", "カゴ", "籠", "woven basket", "Home & Living"),
    ("kaidan", "かいだん", "カイダン", "階段", "staircase / stairs", "Home & Living"),
    ("kaiteki", "かいてき", "カイテキ", "快適", "comfort / pleasantness", "Home & Living"),
    ("kami", "かみ", "カミ", "紙", "writing paper / sheet", "Tools & Goods"),
    ("kamikuzu", "かみくず", "カミクズ", "紙屑", "waste paper scraps", "Home & Living"),
    ("kamisori", "かみそり", "カミソリ", "剃刀", "shaving razor", "Daily Life"),
    ("kanazuchi", "かなづち", "カナヅチ", "金槌", "hammer / non-swimmer", "Tools & Goods"),
    ("kanban", "かんばん", "カンバン", "看板", "signboard / storefront billboard", "Culture & Society"),
    ("kane", "かね", "カネ", "鐘", "bell / chime / gong", "Culture & Society"),
    ("kanzashi", "かんざし", "カンザシ", "簪", "traditional ornate hairpin", "Clothes & Fashion"),
    ("kapuseru", "かぷせる", "カプセル", "カプセル", "capsule / pill", "Body & Health"),
    ("kasa", "かさ", "カサ", "傘", "umbrella / parasol", "Daily Life"),
    ("kasutamu", "かすたむ", "カスタム", "カスタム", "customization", "Hobbies & Media"),
    ("katei", "かてい", "カテイ", "家庭", "home / household family", "People & Family"),
    ("kawa", "かわ", "カワ", "革", "leather / animal hide", "Clothes & Fashion"),
    ("kega", "けが", "ケガ", "怪我", "injury / wound", "Body & Health"),
    ("keito", "けいと", "ケイト", "毛糸", "knitting yarn / wool yarn", "Clothes & Fashion"),
    ("ketsueki", "けつえき", "ケツエキ", "血液", "blood / bloodstream", "Body & Health"),
    ("kirei", "きれい", "キレイ", "綺麗", "cleanliness / beauty", "Appearance & Quality"),
    ("kodawari", "こだわり", "コダワリ", "こだわり", "meticulous devotion / obsession with quality", "Culture & Society"),
    ("kooto", "こーと", "コート", "コート", "overcoat / winter coat", "Clothes & Fashion"),
    ("koppu", "こっぷ", "コップ", "コップ", "drinking glass / cup", "Home & Living"),
    ("kousui", "こうすい", "コウスイ", "香水", "perfume / fragrance", "Daily Life"),
    ("kutsushita", "くつした", "クツシタ", "靴下", "socks / stockings", "Clothes & Fashion"),
    ("kyatapira", "きゃたぴら", "キャタピラ", "キャタピラ", "caterpillar track", "Tools & Goods"),
    # M
    ("madori", "まどり", "マドリ", "間取り", "floor plan / layout of a house", "Home & Living"),
    ("mafuraa", "まふらー", "マフラー", "マフラー", "winter scarf / muffler", "Clothes & Fashion"),
    ("makura", "まくら", "マクラ", "枕", "bed pillow", "Home & Living"),
    ("manaita", "まないた", "マナイタ", "まな板", "cutting board", "Home & Living"),
    ("masuku", "ますく", "マスク", "マスク", "face mask / protective mask", "Daily Life"),
    ("matsuri", "まつり", "マツリ", "祭り", "traditional festival", "Culture & Society"),
    ("megane", "めがね", "メガネ", "眼鏡", "eyeglasses / spectacles", "Daily Life"),
    ("mokuzou", "もくぞう", "モクゾウ", "木造", "wooden structure / timber frame", "Home & Living"),
    ("monooki", "ものおき", "モノオキ", "物置", "storage shed / closet", "Home & Living"),
    ("moufu", "もうふ", "モウフ", "毛布", "woolen blanket", "Home & Living"),
    # N
    ("nabe", "なべ", "ナベ", "鍋", "cooking pot / pan", "Home & Living"),
    ("nagagutsu", "ながぐつ", "ナガグツ", "長靴", "rain boots / wellingtons", "Clothes & Fashion"),
    ("nagashi", "ながし", "ナガシ", "流し", "kitchen sink", "Home & Living"),
    ("naifu", "ないふ", "ナイフ", "ナイフ", "table knife / pocket knife", "Tools & Goods"),
    ("nawabashigo", "なわばしご", "ナワバシゴ", "縄梯子", "rope ladder", "Tools & Goods"),
    ("nebukuro", "ねぶくろ", "ネブクロ", "寝袋", "sleeping bag", "Hobbies & Media"),
    ("negishi", "ねまき", "ネマキ", "寝巻き", "sleepwear / nightclothes", "Clothes & Fashion"),
    ("nekutai", "ねくたい", "ネクタイ", "ネクタイ", "necktie", "Clothes & Fashion"),
    ("nendo", "ねんど", "ネンド", "粘土", "modeling clay", "Tools & Goods"),
    ("norikae", "のりかえ", "ノリカエ", "乗り換え", "transit transfer / switching trains", "Travel & Places"),
    ("noren", "のれん", "ノレン", "暖簾", "shopfront fabric split curtain", "Culture & Society"),
    ("nuno", "ぬの", "ヌノ", "布", "cloth / textile fabric", "Clothes & Fashion"),
    # O
    ("obento", "おべんとう", "オベントウ", "お弁当", "boxed bento lunch", "Daily Life"),
    ("ofuro", "おふろ", "オフロ", "お風呂", "deep Japanese bath", "Home & Living"),
    ("omoteno", "おもてなし", "オモテナシ", "おもてなし", "traditional Japanese hospitality", "Culture & Society"),
    ("omutsu", "おむつ", "オムツ", "おむつ", "baby diaper / nappy", "Daily Life"),
    ("onigiri kago", "おにぎりかご", "オニギリカゴ", "おにぎり籠", "bamboo rice ball basket", "Home & Living"),
    ("oshiire", "おしいれ", "オシイレ", "押し入れ", "Japanese-style built-in closet", "Home & Living"),
    ("otoshidama", "おとしだま", "オトシダマ", "お年玉", "New Year monetary gift envelope", "Culture & Society"),
    # P
    ("pajama", "ぱじゃま", "パジャマ", "パジャマ", "pajamas", "Clothes & Fashion"),
    ("poketto", "ぽけっと", "ポケット", "ポケット", "coat / pant pocket", "Clothes & Fashion"),
    ("posuta", "ぽすたー", "ポスター", "ポスター", "wall poster", "Hobbies & Media"),
    # R
    ("rajio", "らじお", "ラジオ", "ラジオ", "radio receiver", "Hobbies & Media"),
    ("reizouko", "れいぞうこ", "レイゾウコ", "冷蔵庫", "refrigerator / fridge", "Home & Living"),
    ("reitouko", "れいとうこ", "レイトウコ", "冷凍庫", "freezer compartment", "Home & Living"),
    ("rimokon", "りもこん", "リモコン", "リモコン", "remote control", "Tools & Goods"),
    ("roosoku", "ろうそく", "ロウソク", "蝋燭", "wax candle", "Home & Living"),
    ("ruumu", "るーむ", "ルーム", "ルーム", "room", "Home & Living"),
    # S
    ("saifu", "さいふ", "サイフ", "財布", "money wallet / coin purse", "Daily Life"),
    ("sakka", "さっか", "サッカ", "作家", "author / novelist / writer", "People & Family"),
    ("sandaru", "さんだる", "サンダル", "サンダル", "sandals / flip-flops", "Clothes & Fashion"),
    ("sarada", "さらだ", "サラダ", "サラダ", "vegetable salad", "Food & Dining"),
    ("sawaa", "さわー", "サワー", "サワー", "sour cocktail drink", "Food & Dining"),
    ("sebiro", "せびろ", "セビロ", "背広", "men's business suit", "Clothes & Fashion"),
    ("seetaa", "せーたー", "セーター", "セーター", "knit sweater", "Clothes & Fashion"),
    ("sekken", "せっけん", "セッケン", "石鹸", "hand / body soap", "Daily Life"),
    ("senmentai", "せんめんだい", "センメンダイ", "洗面台", "washstand / bathroom vanity", "Home & Living"),
    ("sentakki", "せんたくき", "センタクキ", "洗濯機", "washing machine", "Home & Living"),
    ("sensu", "せんす", "センス", "扇子", "folding hand fan", "Culture & Society"),
    ("shatsu", "しゃつ", "シャツ", "シャツ", "collared shirt / t-shirt", "Clothes & Fashion"),
    ("shawaa", "しゃわー", "シャワー", "シャワー", "shower head / shower", "Home & Living"),
    ("shinju", "しんじゅ", "シンジュ", "真珠", "pearl gem", "Clothes & Fashion"),
    ("shitsudo", "しつど", "シツド", "湿度", "air humidity level", "Nature & Weather"),
    ("shitsunai", "しつない", "シツナイ", "室内", "indoor interior", "Home & Living"),
    ("shouji", "しょうじ", "ショウジ", "障子", "paper sliding door screen", "Home & Living"),
    ("sofaa", "そふぁー", "ソファー", "ソファー", "sofa / couch", "Home & Living"),
    ("suitchi", "すいっち", "スイッチ", "スイッチ", "light switch / button", "Tools & Goods"),
    ("sukaato", "すかーと", "スカート", "スカート", "skirt", "Clothes & Fashion"),
    ("sutando", "すたんど", "スタンド", "スタンド", "desk lamp stand", "Home & Living"),
    ("surippa", "すりっぱ", "スリッパ", "スリッパ", "indoor slippers", "Home & Living"),
    # T
    ("taoru", "たおる", "タオル", "タオル", "hand towel", "Home & Living"),
    ("tanbuta", "たんぶらー", "タンブラー", "タンブラー", "insulated drinking tumbler", "Tools & Goods"),
    ("tansu", "たんす", "タンス", "箪笥", "wooden chest of drawers", "Home & Living"),
    ("tatami", "たたみ", "タタミ", "畳", "traditional straw tatami mat", "Home & Living"),
    ("teeburu", "てーぶる", "テーブル", "テーブル", "table", "Home & Living"),
    ("terebi", "てれび", "テレビ", "テレビ", "television screen", "Home & Living"),
    ("tenjou", "てんじょう", "テンジョウ", "天井", "room ceiling", "Home & Living"),
    ("tetsubin", "てつびん", "テツビン", "鉄瓶", "cast iron kettle", "Home & Living"),
    ("tisshu", "てぃっしゅ", "ティッシュ", "ティッシュ", "facial tissue paper", "Daily Life"),
    ("tokonoma", "とこのま", "トコノマ", "床の間", "traditional display alcove", "Home & Living"),
    ("tokei", "とけい", "トケイ", "時計", "clock / watch", "Daily Life"),
    ("toire", "といれ", "トイレ", "トイレ", "restroom / toilet", "Home & Living"),
    # U
    ("uchiwabi", "うちわ", "ウチワ", "団扇", "flat round hand fan", "Culture & Society"),
    ("ude dokei", "うでどけい", "ウデドケイ", "腕時計", "wristwatch", "Clothes & Fashion"),
    ("ueki", "うえき", "ウエキ", "植木", "potted plant / garden tree", "Home & Living"),
    ("uekibachi", "うえきばち", "ウエキバチ", "植木鉢", "flower pot / planter", "Home & Living"),
    ("uwagi", "うわぎ", "ウワギ", "上着", "outer jacket / coat", "Clothes & Fashion"),
    # W
    ("wafuku", "わふく", "ワフク", "和服", "traditional Japanese clothing / kimono", "Clothes & Fashion"),
    ("washitsu", "わしつ", "ワシツ", "和室", "Japanese-style tatami room", "Home & Living"),
    ("washlet", "うぉしゅれっと", "ウォシュレット", "ウォシュレット", "electronic bidet toilet seat", "Home & Living"),
    # Y
    ("yakan", "やかん", "ヤカン", "薬缶", "stovetop tea kettle", "Home & Living"),
    ("youshitsume", "ようしつ", "ヨウシツ", "洋室", "Western-style room", "Home & Living"),
    ("yukata", "ゆかた", "ユカタ", "浴衣", "casual cotton summer kimono", "Clothes & Fashion"),
    ("yunomi", "ゆのみ", "ユノミ", "湯呑み", "handleless teacup", "Home & Living"),
    # Z
    ("zabuton", "ざぶとん", "ザブトン", "座布団", "floor sitting cushion", "Home & Living"),
    ("zarukago", "ざる", "ザル", "笊", "bamboo colander / strainer", "Home & Living"),
    ("zori", "ぞうり", "ゾウリ", "草履", "traditional thonged straw sandals", "Clothes & Fashion"),
    ("zoukin", "ぞうきん", "ゾウキン", "雑巾", "cleaning wiping rag", "Home & Living")
]
