# Comprehensive A-Z Nouns across everyday life, school, work, nature, commerce
DATA = [
    # A
    ("aburae", "あぶらえ", "アブラエ", "油絵", "oil painting", "Hobbies & Media"),
    ("achi", "あーち", "アーチ", "アーチ", "arch", "Travel & Places"),
    ("aidea", "あいでぃあ", "アイディア", "アイディア", "creative idea / suggestion", "School & Work"),
    ("aidoru", "あいどる", "アイドル", "アイドル", "pop idol / singer", "Hobbies & Media"),
    ("aikuchi", "あいくち", "アイクチ", "合口", "dagger / knife without guard", "Culture & Society"),
    ("aimu", "あいむ", "アイム", "愛慕", "affectionate devotion", "Emotions & Mind"),
    ("aipon", "あいほん", "アイホン", "アイホン", "smartphone", "Tools & Goods"),
    ("aisukuriimu", "あいすくりーむ", "アイスクリーム", "アイスクリーム", "ice cream", "Food & Dining"),
    ("akachan yohin", "あかちゃんようひん", "アカチャンヨウヒン", "赤ちゃん用品", "baby goods / nursery supplies", "Daily Life"),
    ("akaji", "あかじ", "アカジ", "赤字", "financial deficit / red ink", "Shopping & Money"),
    ("akane", "あかね", "アカネ", "茜", "madder red dye / sunset glow", "Nature & Weather"),
    ("akarusa", "あかるさ", "アカルサ", "明るさ", "brightness / cheerfulness", "Appearance & Quality"),
    ("akikan", "あきかん", "アキカン", "空き缶", "empty beverage can", "Daily Life"),
    ("akibin", "あきびん", "アキビン", "空き瓶", "empty glass bottle", "Daily Life"),
    ("akibeya", "あきべや", "アキベヤ", "空き部屋", "vacant room", "Home & Living"),
    ("akusesu", "あくせす", "アクセス", "アクセス", "network access / transit access", "Travel & Places"),
    ("akushitsunin", "あくしつ", "アクシツ", "悪質", "bad quality / malice", "Culture & Society"),
    ("amaoto", "あまおと", "アマオト", "雨音", "sound of raindrops", "Nature & Weather"),
    ("amazora", "あまぞら", "アマゾラ", "雨空", "rainy sky", "Nature & Weather"),
    ("ame", "あめ", "アメ", "雨", "rain", "Nature & Weather"),
    ("ame-candy", "あめ", "アメ", "飴", "candy / sweet drop", "Food & Dining"),
    ("anata-tachi", "あなたたち", "アナタタチ", "貴方達", "you all (plural)", "People & Family"),
    ("annai", "あんない", "アンナイ", "案内", "guidance / orientation", "Travel & Places"),
    ("anzenki", "あんぜんき", "アンゼンキ", "安全器", "safety device / fuse", "Tools & Goods"),
    ("aoiro", "あおいろ", "アオイロ", "青色", "blue color", "Colors & Styles"),
    ("aomono", "あおもの", "アオモノ", "青物", "green vegetables / greens", "Food & Dining"),
    ("aratana", "あらた", "アラタ", "新た", "novelty / freshness", "Culture & Society"),
    ("are", "あれ", "アレ", "あれ", "that over there", "Daily Life"),
    ("arukou", "あるこうる", "アルコール", "酒精", "alcohol beverage / rubbing alcohol", "Food & Dining"),
    ("asa", "あさ", "アサ", "朝", "morning", "Time & Calendar"),
    ("asagao-hana", "あさがお", "アサガオ", "牽牛花", "morning glory vine", "Nature & Weather"),
    ("asatte", "あさって", "アサッテ", "明後日", "day after tomorrow", "Time & Calendar"),
    ("ashi", "あし", "アシ", "足", "foot / leg", "Body & Health"),
    ("ashimoto-chuu", "あしもと", "アシモト", "足下", "underfoot safety", "Daily Life"),
    ("ashita", "あした", "アシタ", "明日", "tomorrow", "Time & Calendar"),
    ("asoko", "あそこ", "アソコ", "あそこ", "that place over there", "Travel & Places"),
    ("atatakasa-shin", "ぬくもり", "ヌクモリ", "温もり", "cozy human warmth", "Emotions & Mind"),
    ("atarimae", "あたりまえ", "アタリマエ", "当たり前", "natural / matters of course", "Daily Life"),
    ("ato", "あと", "アト", "後", "afterward / later / behind", "Time & Calendar"),
    ("atsusa", "あつさ", "アツサ", "暑さ", "summer heat / sultry weather", "Nature & Weather"),
    # B
    ("ba", "ば", "バ", "場", "venue / arena / space", "Travel & Places"),
    ("baai-jyou", "ばあい", "バアイ", "境遇", "circumstance / case", "Daily Life"),
    ("bai", "ばい", "バイ", "倍", "double / times fold", "School & Work"),
    ("baio", "ばいお", "バイオ", "バイオ", "biotechnology", "Science & Nature"),
    ("baito", "ばいと", "バイト", "バイト", "part-time job", "School & Work"),
    ("baka", "ばか", "バカ", "馬鹿", "fool / idiot / absurdity", "Social & Communication"),
    ("bakemono", "ばけもの", "バケモノ", "化け物", "monster / ghost", "Culture & Society"),
    ("ban", "ばん", "バン", "晩", "evening / night", "Time & Calendar"),
    ("bangou", "ばんごう", "バンゴウ", "番号", "identification number", "School & Work"),
    ("bangohan", "ばんごはん", "バンゴハン", "晩ご飯", "evening dinner", "Daily Life"),
    ("bari", "ばり", "バリ", "バリ", "burr (on molded metal)", "Tools & Goods"),
    ("basu", "ばす", "バス", "バス", "bus transit", "Travel & Places"),
    ("basutei", "ばすてい", "バステイ", "バス停", "bus stop station", "Travel & Places"),
    ("batoru", "ばとる", "バトル", "バトル", "battle / duel", "Hobbies & Media"),
    ("batsu", "ばつ", "バツ", "罰", "penalty / cross mark (X)", "Culture & Society"),
    ("bazaar", "ばざーる", "バザール", "バザール", "bazaar / marketplace", "Shopping & Money"),
    ("benri", "べんり", "ベンリ", "便利", "convenience / handiness", "Daily Life"),
    ("bentou", "べんとう", "ベントウ", "弁当", "boxed lunch bento", "Food & Dining"),
    ("bentoubako", "べんとうばこ", "ベントウバコ", "弁当箱", "bento lunch box container", "Home & Living"),
    ("beru", "べる", "ベル", "ベル", "doorbell / chime", "Tools & Goods"),
    ("betsubetsu", "べつべつ", "ベツベツ", "別々", "separately / each apart", "Daily Life"),
    ("bijin", "びじん", "ビジン", "美人", "beautiful woman / beauty", "People & Family"),
    ("bimyousei", "びみょう", "ビミョウ", "微妙", "subtlety / delicate nuance", "Emotions & Mind"),
    ("bin", "びん", "ビン", "瓶", "glass bottle / jar", "Tools & Goods"),
    ("biniiru", "びにーる", "ビニール", "ビニール", "vinyl plastic", "Tools & Goods"),
    ("biri", "びり", "ビリ", "最下位", "last place / tail end", "School & Work"),
    ("biza", "びざ", "ビザ", "査証", "travel entry visa", "Travel & Places"),
    ("boku", "ぼく", "ボク", "僕", "I / me (casual masculine)", "People & Family"),
    ("bokura", "ぼくら", "ボクラ", "僕ら", "we / us (casual masculine)", "People & Family"),
    ("bon", "ぼん", "ボン", "盆", "tray / Obon lantern festival", "Culture & Society"),
    ("bou", "ぼう", "ボウ", "棒", "stick / pole / rod", "Tools & Goods"),
    ("bouenkyou", "ぼうえんきょう", "ボウエンキョウ", "望遠鏡", "telescope", "Science & Nature"),
    ("bousai", "ぼうさい", "ボウサイ", "防災", "disaster prevention", "Culture & Society"),
    ("boushi-cap", "ぼうし", "ボウシ", "冠", "hat / headgear", "Clothes & Fashion"),
    ("bousui", "ぼうすい", "ボウスイ", "防水", "waterproofing", "Tools & Goods"),
    ("boya", "ぼや", "ボヤ", "小火", "small localized fire", "Daily Life"),
    ("booru", "ぼーる", "ボール", "ボール", "spherical ball", "Hobbies & Media"),
    ("bu", "ぶ", "ブ", "部", "department / section / club", "School & Work"),
    ("budo", "ぶどう", "ブドウ", "葡萄", "grape fruit cluster", "Food & Dining"),
    ("bukka", "ぶっか", "ブッカ", "物価", "commodity prices / cost of living", "Shopping & Money"),
    ("bun", "ぶん", "ブン", "文", "sentence / written prose", "School & Work"),
    ("bunpou", "ぶんぽう", "ブンポウ", "文法", "grammar rules", "School & Work"),
    ("bushi", "ぶし", "ブシ", "武士", "samurai warrior", "Culture & Society"),
    ("butaniku-pork", "ぶたにく", "ブタニク", "猪肉", "pork meat cut", "Food & Dining"),
    ("byou", "びょう", "ビョウ", "秒", "second (time unit)", "Time & Calendar"),
    # C
    ("cha", "ちゃ", "チャ", "茶", "tea / brown color", "Food & Dining"),
    ("chakushin", "ちゃくしん", "チャクシン", "着信", "incoming phone call", "Social & Communication"),
    ("chanto-manner", "ぎょうぎ", "ギョウギ", "行儀", "manners / behavior", "Culture & Society"),
    ("chawan", "ちゃわん", "チャワン", "茶碗", "rice bowl / ceramic teacup", "Home & Living"),
    ("chichi-oya", "ちちおや", "チチオヤ", "父親", "father (formal)", "People & Family"),
    ("chie", "ちえ", "チエ", "知恵", "wisdom / sagacity", "Emotions & Mind"),
    ("chigai", "ちがい", "チガイ", "違い", "difference / disparity", "Daily Life"),
    ("chiho", "ちほう", "チホウ", "地方", "province / region / countryside", "Travel & Places"),
    ("chika", "ちか", "チカ", "地下", "underground / basement floor", "Travel & Places"),
    ("chikashitsu", "ちかしつ", "チカシツ", "地下室", "basement cellar", "Home & Living"),
    ("chiketto", "ちけっと", "チケット", "チケット", "admission ticket", "Travel & Places"),
    ("chinetsu", "ちねつ", "チネツ", "地熱", "geothermal heat", "Science & Nature"),
    ("chirigami", "ちりがみ", "チリガミ", "塵紙", "toilet paper / tissue scrap", "Daily Life"),
    ("chizu", "ちず", "チズ", "地図", "geographical map", "Travel & Places"),
    ("chou", "ちょう", "チョウ", "町", "town district", "Travel & Places"),
    ("choumi", "ちょうみ", "チョウミ", "調味", "flavor seasoning", "Food & Dining"),
    ("chousan", "ちょうさん", "チョウサン", "朝餐", "morning breakfast banquet", "Food & Dining"),
    ("chousen", "ちょうせん", "チョウセン", "挑戦", "bold challenge / trial", "School & Work"),
    ("choushi", "ちょうし", "チョウシ", "調子", "condition / tune / rhythm", "Daily Life"),
    ("chotto", "ちょっと", "チョット", "一寸", "a little / brief moment", "Time & Calendar"),
    ("chuubou", "ちゅうぼう", "チュウボウ", "厨房", "restaurant kitchen", "Food & Dining"),
    ("chuugaku", "ちゅうがく", "チュウガク", "中学", "junior high school", "School & Work"),
    ("chuugakkou", "ちゅうがっこう", "チュウガッコウ", "中学校", "middle school", "School & Work"),
    ("chuuka", "ちゅうか", "チュウカ", "中華", "Chinese cuisine / culture", "Food & Dining"),
    ("chuumon", "ちゅうもん", "チュウモン", "注文", "food order / purchase request", "Food & Dining"),
    ("chuushin", "ちゅうしん", "チュウシン", "中心", "center / nucleus / heart", "Travel & Places"),
    ("chuuou", "ちゅうおう", "チュウオウ", "中央", "center / central station", "Travel & Places"),
    # D
    ("daidokoro-sink", "だいどころば", "ダイドコロバ", "台所場", "kitchen workspace", "Home & Living"),
    ("daigaku", "だいがく", "ダイガク", "大学", "university / college", "School & Work"),
    ("daigakuin", "だいがくいん", "ダイガクイン", "大学院", "graduate school", "School & Work"),
    ("daiji", "だいじ", "ダイジ", "大事", "importance / momentous affair", "Culture & Society"),
    ("daimyou", "だいみょう", "ダイミョウ", "大名", "feudal lord / daimyo", "Culture & Society"),
    ("dainingu", "だいにんぐ", "ダイニング", "ダイニング", "dining room area", "Home & Living"),
    ("daitai", "だいたい", "ダイタイ", "大体", "general outline / gist", "Daily Life"),
    ("dan", "だん", "ダン", "段", "step / rank / level", "School & Work"),
    ("dangi", "だんぎ", "ダンギ", "談義", "friendly sermon / discussion", "Social & Communication"),
    ("danran", "だんらん", "ダンラン", "団らん", "happy family circle / gathering", "People & Family"),
    ("dansei-fuku", "だんせいふく", "ダンセイフク", "男性服", "men's apparel", "Clothes & Fashion"),
    ("date", "でーと", "デート", "デート", "romantic date", "Social & Communication"),
    ("deguchi-mon", "でぐちもん", "デグチモン", "出口門", "exit gate", "Travel & Places"),
    ("dempa", "でんぱ", "デンパ", "電波", "radio waves / cell signal", "Science & Nature"),
    ("densha", "でんしゃ", "デンシャ", "電車", "electric train", "Travel & Places"),
    ("dentou-lamp", "でんとう", "デントウ", "電灯", "electric lantern / lamp", "Home & Living"),
    ("denwa", "でんわ", "デンワ", "電話", "telephone / phone call", "Tools & Goods"),
    ("denwabangou", "でんわばんごう", "デンワバンゴウ", "電話番号", "telephone number", "Social & Communication"),
    ("do", "ど", "ド", "度", "degree / counter for times", "Science & Nature"),
    ("doa", "どあ", "ドア", "ドア", "room door", "Home & Living"),
    ("dokugaku", "どくがく", "ドクガク", "独学", "self-study / autodidactism", "School & Work"),
    ("doko", "どこ", "ドコ", "何処", "where / which place", "Travel & Places"),
    ("donata", "どなた", "ドナタ", "何方", "who (polite)", "People & Family"),
    ("dono", "どの", "ドノ", "どの", "which", "Daily Life"),
    ("dore", "どれ", "ドレ", "どれ", "which one", "Daily Life"),
    ("doro", "どろ", "ドロ", "泥", "mud / sludge", "Nature & Weather"),
    ("doushi", "どうし", "ドウシ", "同志", "fellow comrade / kindred spirit", "People & Family"),
    ("doushi-verb", "どうし", "ドウシ", "動詞", "verb part of speech", "School & Work"),
    ("doyoubi", "どようび", "ドヨウビ", "土曜日", "Saturday", "Time & Calendar"),
    # E
    ("e", "え", "エ", "絵", "picture / drawing / painting", "Hobbies & Media"),
    ("ehon", "えほん", "エホン", "絵本", "illustrated picture book", "Hobbies & Media"),
    ("eki", "えき", "エキ", "駅", "train station", "Travel & Places"),
    ("ekicho", "えきちょう", "エキチョウ", "駅長", "station master", "People & Family"),
    ("ekiben", "えきべん", "エキベン", "駅弁", "boxed train bento meal", "Food & Dining"),
    ("emaki", "えまき", "エマキ", "絵巻", "illustrated picture scroll", "Culture & Society"),
    ("emonkake", "えもんかけ", "エモンカケ", "衣紋掛け", "traditional kimono hanger", "Clothes & Fashion"),
    ("en", "えん", "エン", "円", "Japanese yen / circle", "Shopping & Money"),
    ("empitsu", "えんぴつ", "エンピツ", "鉛筆", "graphite pencil", "Tools & Goods"),
    ("engeki", "えんげき", "エンゲキ", "演劇", "theatrical play / drama", "Hobbies & Media"),
    ("enshuu", "えんしゅう", "エンシュウ", "演習", "practice exercise / seminar", "School & Work"),
    ("eri", "えり", "エリ", "襟", "collar / lapel", "Clothes & Fashion"),
    # F
    ("fune-bune", "ふね", "フネ", "小舟", "small rowboat", "Travel & Places"),
    ("furo", "ふろ", "フロ", "風呂", "hot bath / tub", "Home & Living"),
    ("furu", "ふる", "フル", "古", "old antiquity", "Culture & Society"),
    ("furugi", "ふるぎ", "フルギ", "古着", "vintage used clothing", "Clothes & Fashion"),
    ("futa", "ふた", "フタ", "蓋", "lid / pot cover", "Tools & Goods"),
    ("futari", "ふたり", "フタリ", "二人", "two persons / pair", "People & Family"),
    ("futsuka", "ふつか", "フツカ", "二日", "second day of the month / two days", "Time & Calendar"),
    ("fuyu", "ふゆ", "フユ", "冬", "winter season", "Time & Calendar"),
    ("fuyuyasumi", "ふゆやすみ", "フユヤスミ", "冬休み", "winter holidays", "Time & Calendar"),
    # G
    ("gaijin", "がいじん", "ガイジン", "外人", "foreigner (colloquial)", "People & Family"),
    ("gaikoku", "がいこく", "ガイコク", "外国", "foreign foreign country", "Travel & Places"),
    ("gaikokujin", "がいこくじん", "ガイコクジン", "外国人", "foreign national", "People & Family"),
    ("gaishutsu", "がいしゅつ", "ガイシュツ", "外出", "going outdoors / outing", "Daily Life"),
    ("gakkou-sha", "こうしゃ", "コウシャ", "校舎", "school school building", "School & Work"),
    ("gamen", "がめん", "ガメン", "画面", "display monitor screen", "Tools & Goods"),
    ("gatsu", "がつ", "ガツ", "月", "counter for months", "Time & Calendar"),
    ("genba-work", "さぎょうば", "サギョウバ", "作業場", "workspace / workshop", "School & Work"),
    ("genkan", "げんかん", "ゲンカン", "玄関", "entryway foyer", "Home & Living"),
    ("genki", "げんき", "ゲンキ", "元気", "vigor / vitality / good health", "Body & Health"),
    ("getsuyoubi", "げつようび", "ゲツヨウビ", "月曜日", "Monday", "Time & Calendar"),
    ("gimon-fu", "ぎもんふ", "ギモンフ", "疑問符", "question mark (?)", "School & Work"),
    ("ginkou-in", "ぎんこういん", "ギンコウイン", "銀行員", "bank teller clerk", "People & Family"),
    ("go", "ご", "ゴ", "五", "number five (5)", "School & Work"),
    ("gogo", "ごご", "ゴゴ", "午後", "afternoon / PM", "Time & Calendar"),
    ("gohan", "ごはん", "ゴハン", "ご飯", "steamed rice / cooked meal", "Food & Dining"),
    ("gozen", "ごぜん", "ゴゼン", "午前", "morning / AM", "Time & Calendar"),
    ("gun", "ぐん", "グン", "郡", "rural county district", "Travel & Places"),
    ("gyunyu", "ぎゅうにゅう", "ギュウニュウ", "牛乳", "cow's milk", "Food & Dining"),
    # H
    ("ha-tooth", "は", "ハ", "歯牙", "tooth / enamel", "Body & Health"),
    ("hagaki", "はがき", "ハガキ", "葉書", "postcard", "Tools & Goods"),
    ("haha", "はは", "ハハ", "母", "mother (humble)", "People & Family"),
    ("haha-oya", "ははおや", "ハハオヤ", "母親", "mother (formal)", "People & Family"),
    ("hai", "はい", "ハイ", "灰", "fire ashes", "Nature & Weather"),
    ("haizara-plate", "はいざら", "ハイザラ", "灰皿", "ashtray dish", "Home & Living"),
    ("hako-box", "はこ", "ハコ", "小箱", "small storage casket", "Tools & Goods"),
    ("hana-flower", "はな", "ハナ", "花", "flower / blossom", "Nature & Weather"),
    ("hanami-party", "はなみざけ", "ハナミザケ", "花見酒", "cherry blossom viewing sake party", "Culture & Society"),
    ("haru-season", "はる", "ハル", "芳春", "flowering spring season", "Time & Calendar"),
    ("hashi-bridge", "はし", "ハシ", "橋", "river bridge / overpass", "Travel & Places"),
    ("hashi-edge", "はし", "ハシ", "端", "edge / border / tip", "Travel & Places"),
    ("hatake-farm", "はたけ", "ハタケ", "菜園", "vegetable plot garden", "Nature & Animals"),
    ("hatsuka", "はつか", "ハツカ", "二十日", "twentieth day of month / 20 days", "Time & Calendar"),
    ("hayasa", "はやさ", "ハヤサ", "速さ", "velocity / quick speed", "Science & Nature"),
    ("heya", "へや", "ヘヤ", "部屋", "room / chamber", "Home & Living"),
    ("hidari", "ひだり", "ヒダリ", "左", "left side", "Travel & Places"),
    ("higaeri", "ひがえり", "ヒガエリ", "日帰り", "day excursion / return in same day", "Travel & Places"),
    ("hikoujou", "ひこうじょう", "ヒコウジョウ", "飛行場", "airfield / airport runway", "Travel & Places"),
    ("hima", "ひま", "ヒマ", "暇", "free spare time / leisure", "Time & Calendar"),
    ("hi", "ひ", "ヒ", "日", "day / sunshine / date", "Time & Calendar"),
    ("hi-fire", "ひ", "ヒ", "火", "flame / fire", "Nature & Weather"),
    ("hitori", "ひとり", "ヒトリ", "一人", "one person / alone", "People & Family"),
    ("hon", "ほん", "ホン", "本", "book / volume", "Hobbies & Media"),
    ("honya", "ほんや", "ホンヤ", "本屋", "bookstore / bookseller", "Travel & Places"),
    # I
    ("ie", "いえ", "イエ", "家", "house / home residence", "Home & Living"),
    ("ii-koto", "いいこと", "イイコト", "良い事", "good deed / pleasant thing", "Daily Life"),
    ("ikikata", "いきかた", "イキカタ", "生き方", "way of life / lifestyle", "Culture & Society"),
    ("ikioi", "いきおい", "イキオイ", "勢い", "vigor / momentum / drive", "Emotions & Mind"),
    ("ikuji", "いくじ", "イクジ", "育児", "childcare / child rearing", "People & Family"),
    ("ima", "いま", "イマ", "居間", "living room / family sitting room", "Home & Living"),
    ("ima-now", "いま", "イマ", "今", "the present moment / right now", "Time & Calendar"),
    ("inshi", "いんし", "インシ", "印紙", "revenue stamp", "Shopping & Money"),
    ("inu", "いぬ", "イヌ", "犬", "domestic dog", "Nature & Animals"),
    ("ippon", "いっぽん", "イッポン", "一本", "one long cylindrical item / full point in kendo", "Sports & Leisure"),
    ("iro", "いろ", "イロ", "色", "color / hue / tint", "Colors & Styles"),
    ("iroiro", "いろいろ", "イロイロ", "色々", "variety / assortment", "Daily Life"),
    ("itoko-female", "いとこ", "イトコ", "従姉妹", "female cousin", "People & Family"),
    ("itsumo", "いつも", "イツモ", "平生", "ordinary times / always", "Time & Calendar"),
    # J
    ("jaama", "じゃーまね", "ジャーマネ", "マネージャー", "celebrity road manager", "People & Family"),
    ("jibun", "じぶん", "ジブン", "自分", "oneself / myself", "People & Family"),
    ("jidousha", "じどうしゃ", "ジドウシャ", "自動車", "automobile / motor car", "Travel & Places"),
    ("jikan-wari", "じかんわり", "ジカンワリ", "時間割", "class timetable / schedule", "School & Work"),
    ("jisho", "じしょ", "ジショ", "辞書", "lexicon / dictionary", "Tools & Goods"),
    ("jitensha", "じてんしゃ", "ジテンシャ", "自転車", "bicycle / bike", "Travel & Places"),
    ("jitsumu", "じつむ", "ジツム", "実務", "practical practical business work", "School & Work"),
    ("juu", "じゅう", "ジュウ", "十", "number ten (10)", "School & Work"),
    ("juusho", "じゅうしょ", "ジュウショ", "住所", "residential street address", "Travel & Places"),
    # K
    ("kaban-bag", "かばん", "カバン", "手提げ", "tote bag", "Clothes & Fashion"),
    ("kabuki-za", "かぶきざ", "カブキザ", "歌舞伎座", "Kabuki-za theater", "Culture & Society"),
    ("kafe", "かふぇ", "カフェ", "カフェ", "coffee cafe", "Travel & Places"),
    ("kai", "かい", "カイ", "貝", "shellfish / clam shell", "Nature & Animals"),
    ("kaigi", "かいぎ", "カイギ", "会議", "business conference / meeting", "School & Work"),
    ("kaigishitsu", "かいぎしつ", "カイギシツ", "会議室", "conference meeting room", "School & Work"),
    ("kaimono", "かいもの", "カイモノ", "買い物", "shopping / purchased goods", "Shopping & Money"),
    ("kaisha", "かいしゃ", "カイシャ", "会社", "commercial business company", "School & Work"),
    ("kami-hair", "かみ", "カミ", "髪", "head hair", "Body & Health"),
    ("kami-god", "かみ", "カミ", "神", "deity / God / spirit", "Culture & Society"),
    ("kanojo", "かのじょ", "カノジョ", "彼女", "she / her / girlfriend", "People & Family"),
    ("kare", "かれ", "カレ", "彼", "he / him / boyfriend", "People & Family"),
    ("karada-body", "からだ", "カラダ", "身体", "physical body", "Body & Health"),
    ("kasa-umbrella", "かさ", "カサ", "雨傘", "rain umbrella", "Daily Life"),
    ("kawa-river", "かわ", "カワ", "川", "river / freshwater stream", "Nature & Weather"),
    ("kayoubi", "かようび", "カヨウビ", "火曜日", "Tuesday", "Time & Calendar"),
    ("kiku", "きく", "キク", "菊", "chrysanthemum flower", "Nature & Weather"),
    ("kin'youbi", "きんようび", "キンヨウビ", "金曜日", "Friday", "Time & Calendar"),
    ("kippu", "きっぷ", "キップ", "切符", "train passenger ticket", "Travel & Places"),
    ("kitte", "きって", "キッテ", "切手", "postage stamp", "Tools & Goods"),
    ("koban-police", "こうばん", "コウバン", "交番", "neighborhood police box", "Travel & Places"),
    ("koe", "こえ", "コエ", "声", "human voice / cry", "Social & Communication"),
    ("koko", "ここ", "ココ", "此処", "here / this place", "Travel & Places"),
    ("kotoshi", "ことし", "コトシ", "今年", "this year", "Time & Calendar"),
    ("koto", "こと", "コト", "事", "matter / intangible thing", "Daily Life"),
    ("kotoba", "ことば", "コトバ", "言葉", "spoken word / spoken language", "Social & Communication"),
    ("kudamono", "くだもの", "クダモノ", "果物", "fresh fruit", "Food & Dining"),
    ("kuni", "くに", "クニ", "国", "country / homeland", "Travel & Places"),
    ("kuruma", "くるま", "クルマ", "車", "motor car / automobile", "Travel & Places"),
    ("kuro", "くろ", "クロ", "黒", "black color", "Colors & Styles"),
    ("kyou", "きょう", "キョウ", "今日", "today", "Time & Calendar"),
    ("kyoushitsu", "きょうしつ", "キョウシツ", "教室", "school classroom", "School & Work"),
    ("kyuujitsu", "きゅうじつ", "キュウジツ", "休日", "holiday / day off", "Time & Calendar"),
    # M
    ("mado", "まど", "マド", "窓", "window pane", "Home & Living"),
    ("mae", "まえ", "マエ", "前", "front / previous / before", "Time & Calendar"),
    ("mainichi", "まいにち", "マイニチ", "毎日", "every single day", "Time & Calendar"),
    ("maiasaku", "まいあさ", "マイアサ", "毎朝", "every morning", "Time & Calendar"),
    ("maiban", "まいばん", "マイバン", "毎晩", "every evening", "Time & Calendar"),
    ("maishuu", "まいしゅう", "マイシュウ", "毎週", "every week", "Time & Calendar"),
    ("maitsuki", "まいつき", "マイツキ", "毎月", "every month", "Time & Calendar"),
    ("maitoshi", "まいとし", "マイトシ", "毎年", "every year", "Time & Calendar"),
    ("migi", "みぎ", "ミギ", "右", "right side", "Travel & Places"),
    ("mizu", "みず", "ミズ", "水", "fresh cool water", "Food & Dining"),
    ("mise", "みせ", "ミセ", "店", "shop / retail store", "Travel & Places"),
    ("michi", "みち", "ミチ", "道", "road / pathway / street", "Travel & Places"),
    ("mokuyoubi", "もくようび", "モクヨウビ", "木曜日", "Thursday", "Time & Calendar"),
    ("mono", "もの", "モノ", "物", "physical object / tangible thing", "Tools & Goods"),
    ("mon", "もん", "モン", "門", "gate / entrance portal", "Travel & Places"),
    # N
    ("namae", "なまえ", "ナマエ", "名前", "given name / full name", "People & Family"),
    ("nani", "なに", "ナニ", "何", "what / which", "Daily Life"),
    ("natsu-summer", "なつ", "ナツ", "盛夏", "height of summer", "Time & Calendar"),
    ("nichiyoubi", "にちようび", "ニチヨウビ", "日曜日", "Sunday", "Time & Calendar"),
    ("nihon", "にほん", "ニホン", "日本", "Japan nation", "Travel & Places"),
    ("nikki", "にっき", "ニッキ", "日記", "personal diary / journal", "Hobbies & Media"),
    ("niku", "にく", "ニク", "肉", "meat / flesh", "Food & Dining"),
    ("nimotsu", "にもつ", "ニモツ", "荷物", "luggage / parcel / baggage", "Travel & Places"),
    ("niwa", "にわ", "ニワ", "庭", "home garden / courtyard", "Home & Living"),
    ("nooto", "のーと", "ノート", "ノート", "notebook / paper pad", "Tools & Goods"),
    ("nomimono", "のみもの", "ノミモノ", "飲み物", "refreshing beverage / drink", "Food & Dining"),
    # O
    ("oba-san", "おばさん", "オバサン", "伯母さん", "auntie / middle-aged lady", "People & Family"),
    ("ochazuke-dish", "ぶぶづけ", "ブブヅケ", "ぶぶ漬け", "Kyoto ochazuke rice with tea", "Food & Dining"),
    ("ofukuro", "おふくろ", "オフクロ", "お袋", "one's own mother (affectionate)", "People & Family"),
    ("omiyage", "おみやげ", "オミヤゲ", "お土産", "souvenir / travel present", "Culture & Society"),
    ("onaji", "おなじ", "オナジ", "同じ", "the same / identical", "Daily Life"),
    ("ongakuka", "おんがくか", "オンガクカ", "音楽家", "musician / composer", "People & Family"),
    ("onsen-ryokan", "ゆやど", "ユヤド", "湯宿", "hot spring bathhouse inn", "Travel & Places"),
    ("osatsu", "おさつ", "オサツ", "お札", "paper money banknote", "Shopping & Money"),
    ("otera", "おてら", "オテラ", "お寺", "Buddhist temple", "Culture & Society"),
    ("otoko", "おとこ", "オトコ", "男", "man / male", "People & Family"),
    ("otokonoko", "おとこのこ", "オトコノコ", "男の子", "little boy", "People & Family"),
    ("otouto-bro", "おとうと", "オトウト", "舎弟", "younger brother / junior", "People & Family"),
    # P
    ("panya", "ぱんや", "パンヤ", "パン屋", "bakery / bread shop", "Travel & Places"),
    ("pasokon", "ぱそこん", "パソコン", "パソコン", "personal computer / PC", "Tools & Goods"),
    ("pen", "ぺん", "ペン", "ペン", "ink pen", "Tools & Goods"),
    ("petto", "ぺっと", "ペット", "ペット", "domestic companion pet", "Nature & Animals"),
    ("purinto", "ぷりんと", "プリント", "プリント", "handout printout", "School & Work"),
    # R
    ("raigetsu", "らいげつ", "ライゲツ", "来月", "next month", "Time & Calendar"),
    ("rainen", "らいねん", "ライネン", "来年", "next year", "Time & Calendar"),
    ("raishuu", "らいしゅう", "ライシュウ", "来週", "next week", "Time & Calendar"),
    ("rajio-kase", "らじかせ", "ラジカセ", "ラジカセ", "radio cassette boombox", "Hobbies & Media"),
    ("ringo", "りんご", "リンゴ", "林檎", "sweet apple", "Food & Dining"),
    ("ryokousei", "たびびと", "タビビト", "旅人", "traveler / wayfarer", "People & Family"),
    ("ryou", "りょう", "リョウ", "寮", "student dormitory / boarding house", "Home & Living"),
    ("ryourinin", "りょうりにん", "リョウリニン", "料理人", "chef / professional cook", "People & Family"),
    ("ryuugaku", "りゅうがく", "リュウガク", "留学", "studying abroad in foreign land", "School & Work"),
    ("ryuugakusei", "りゅうがくせい", "リュウガクセイ", "留学生", "international exchange student", "People & Family"),
    # S
    ("sakubun", "さくぶん", "サクブン", "作文", "school essay / composition", "School & Work"),
    ("sakura-tree", "さくらぎ", "サクラギ", "桜木", "cherry blossom tree", "Nature & Weather"),
    ("sakuranbo", "さくらんぼ", "サクランボ", "桜桃", "cherry fruit", "Food & Dining"),
    ("sara", "さら", "サラ", "皿", "dining plate / dish", "Home & Living"),
    ("seikatsu-hi", "せいかつひ", "セイカツヒ", "生活費", "living expenses", "Shopping & Money"),
    ("seiseki", "せいせき", "セイセキ", "成績", "grade results / academic score", "School & Work"),
    ("senshuu", "せんしゅう", "センシュウ", "先週", "last week", "Time & Calendar"),
    ("sengetsu", "せんげつ", "センゲツ", "先月", "last month", "Time & Calendar"),
    ("sentaku", "せんたく", "センタク", "洗濯", "laundry washing", "Daily Life"),
    ("sentakumono", "せんたくもの", "センタクモノ", "洗濯物", "laundry clothes to wash", "Daily Life"),
    ("shashin", "しゃしん", "シャシン", "写真", "photograph", "Hobbies & Media"),
    ("shashinki", "しゃしんき", "シャシンキ", "写真機", "camera", "Tools & Goods"),
    ("shatsu-t", "てぃーしゃつ", "ティーシャツ", "Tシャツ", "t-shirt", "Clothes & Fashion"),
    ("shi", "し", "シ", "市", "city / municipality", "Travel & Places"),
    ("shigotoba", "しごとば", "シゴトバ", "仕事場", "workplace / office", "School & Work"),
    ("shiken", "しけん", "シケン", "試験", "school examination / test", "School & Work"),
    ("shimai", "しまい", "シマイ", "姉妹", "sisters", "People & Family"),
    ("shinbun", "しんぶん", "シンブン", "新聞", "newspaper", "Hobbies & Media"),
    ("shirou", "しろ", "シロ", "白", "white color", "Colors & Styles"),
    ("shita", "した", "シタ", "下", "under / below / underneath", "Travel & Places"),
    ("shitsumon", "しつもん", "シツモン", "質問", "question / inquiry", "School & Work"),
    ("shokuji", "しょくじ", "ショクジ", "食事", "meal dining", "Food & Dining"),
    ("shokudou", "しょくどう", "ショクドウ", "食堂", "dining hall / cafeteria", "Travel & Places"),
    ("shourai", "しょうらい", "ショウライ", "将来", "future prospects", "Time & Calendar"),
    ("shuumatsu", "しゅうまつ", "シュウマツ", "週末", "weekend", "Time & Calendar"),
    ("soto", "そと", "ソト", "外", "outdoors / outside", "Travel & Places"),
    ("suiyoubi", "すいようび", "スイヨウビ", "水曜日", "Wednesday", "Time & Calendar"),
    ("supuun", "すぷーん", "スプーン", "スプーン", "eating spoon", "Food & Dining"),
    ("suriru", "すりる", "スリル", "スリル", "thrill / suspense", "Hobbies & Media"),
    # T
    ("tabemono", "たべもの", "タベモノ", "食べ物", "food / edible provisions", "Food & Dining"),
    ("tamago", "たまご", "タマゴ", "卵", "egg", "Food & Dining"),
    ("tegami-letter", "しょかん", "ショカン", "書簡", "epistle / formal letter", "Social & Communication"),
    ("tegoro", "てごろ", "テゴロ", "手頃", "affordable price / handy", "Shopping & Money"),
    ("te", "て", "テ", "手", "human hand", "Body & Health"),
    ("ten'in-clerk", "てんぽいん", "テンポイン", "店舗員", "storefront employee", "People & Family"),
    ("todana", "とだな", "トダナ", "戸棚", "cupboard / kitchen cabinet", "Home & Living"),
    ("tori", "とり", "トリ", "鳥", "bird", "Nature & Animals"),
    ("toshokan", "としょかん", "トショカン", "図書館", "public library", "Travel & Places"),
    ("tsukue", "つくえ", "ツクエ", "机", "study desk / writing table", "Home & Living"),
    ("tsuma-wife", "かない", "カナイ", "家内", "my wife (humble traditional)", "People & Family"),
    # U
    ("ue", "うえ", "ウエ", "上", "top / above / upward", "Travel & Places"),
    ("uma", "うま", "ウマ", "馬", "horse", "Nature & Animals"),
    ("ushiro", "うしろ", "ウシロ", "後ろ", "behind / rear", "Travel & Places"),
    ("uta-song", "がっきょく", "ガッキョク", "楽曲", "musical piece / track", "Hobbies & Media"),
    # Y
    ("yakusoku", "やくそく", "ヤクソク", "約束", "promise / appointment", "Social & Communication"),
    ("yama-mountain", "やまやま", "ヤマヤマ", "連山", "mountain chain", "Nature & Weather"),
    ("yasumi", "やすみ", "ヤスミ", "休み", "rest / vacation / holiday", "Time & Calendar"),
    ("yasumijikan", "やすみじかん", "ヤスミジカン", "休み時間", "recess / break time", "School & Work"),
    ("yasai", "やさい", "ヤサイ", "野菜", "fresh vegetables", "Food & Dining"),
    ("yoru", "よる", "ヨル", "夜", "night / evening hours", "Time & Calendar"),
    ("yuubinkyoku-po", "ゆうびんきょく", "ユウビンキョク", "郵便局", "central post office", "Travel & Places"),
    ("yuube", "ゆうべ", "ユウベ", "夕べ", "yesterday evening / last night", "Time & Calendar"),
    ("yuugata-dusk", "たそがれ", "タソガレ", "黄昏", "twilight dusk", "Time & Calendar"),
    # Z
    ("zasshi-mag", "ていきかんこうぶつ", "テイキカンコウブツ", "定期刊行物", "periodical magazine", "Hobbies & Media"),
    ("zubon-pants", "ぱんつ", "パンツ", "パンツ", "pants / trousers", "Clothes & Fashion")
]
