# Science, Technology, Computing, Economy, Nature, Flora, Fauna, Minerals, Sports
DATA = [
    # A
    ("abuku", "あぶく", "アブク", "泡", "bubbles / foam", "Science & Nature"),
    ("adobaisu", "あどばいす", "アドバイス", "アドバイス", "advice / counsel", "Social & Communication"),
    ("aidentiti-card", "みぶんしょう", "ミブンショウ", "身分証", "identification card", "Tools & Goods"),
    ("aikon", "あいこん", "アイコン", "アイコン", "graphical icon / symbol", "Tools & Goods"),
    ("aimu-feeling", "あいじょう", "アイジョウ", "愛情", "love / affection", "Emotions & Mind"),
    ("aisuhokkee", "あいすほっけー", "アイスホッケー", "アイスホッケー", "ice hockey", "Hobbies & Media"),
    ("ajisai", "あじさい", "アジサイ", "紫陽花", "hydrangea flower", "Nature & Weather"),
    ("akari-light", "あかりばち", "アカリバチ", "灯り鉢", "garden stone lantern bowl", "Home & Living"),
    ("akugi-prank", "いたずら", "イタズラ", "悪戯", "mischief / trick", "Daily Life"),
    ("akuma", "あくま", "アクマ", "悪魔", "devil / demon", "Culture & Society"),
    ("akusento", "あくせんと", "アクセント", "アクセント", "pitch accent / stress", "School & Work"),
    ("amagasa", "あまがさ", "アマガサ", "雨傘", "rain umbrella", "Daily Life"),
    ("amime", "あみめ", "アミメ", "網目", "net mesh / grid pattern", "Tools & Goods"),
    ("amu", "あみもの", "アミモノ", "編み物", "knitting work / knitwear", "Hobbies & Media"),
    ("angou", "あんごう", "アンゴウ", "暗号", "cryptographic cipher / password", "Science & Nature"),
    ("anime", "あにめ", "アニメ", "アニメ", "Japanese animation", "Hobbies & Media"),
    ("annkou", "あんこう", "アンコウ", "鮟鱇", "anglerfish / monkfish", "Nature & Animals"),
    ("antei", "あんてい", "アンテイ", "安定", "stability / equilibrium", "Science & Nature"),
    ("an'ya", "あんや", "アンヤ", "暗夜", "dark moonless night", "Nature & Weather"),
    ("aobashou", "あおばずく", "アオバズク", "青葉木菟", "brown hawk-owl", "Nature & Animals"),
    ("aozora-sky", "へきくう", "ヘキクウ", "碧空", "azure sky", "Nature & Weather"),
    ("apuri", "あぷり", "アプリ", "アプリ", "mobile smartphone application", "Tools & Goods"),
    ("arauma", "あらうま", "アラウマ", "荒馬", "untamed spirited horse", "Nature & Animals"),
    ("arerugii-seiryou", "かふんしょう", "カフンショウ", "花粉症", "hay fever / pollen allergy", "Body & Health"),
    ("arukari", "あるかり", "アルカリ", "アルカリ", "alkali / basic chemical", "Science & Nature"),
    ("arumu", "あるみはく", "アルミハク", "アルミ箔", "aluminum foil", "Tools & Goods"),
    ("asagao-flower", "ちょうがお", "チョウガオ", "朝顔", "morning glory petal", "Nature & Weather"),
    ("asagiri", "あさぎり", "アサギリ", "朝霧", "morning mist / fog", "Nature & Weather"),
    ("asamoya-fog", "きりあさ", "キリアサ", "朝靄", "morning haze", "Nature & Weather"),
    ("asase", "あさせ", "アサセ", "浅瀬", "shoal / shallows / sandbar", "Nature & Weather"),
    ("ashimoto-ground", "じめん", "ジメン", "地面", "ground surface / earth", "Nature & Weather"),
    ("asufaruto", "あすふぁると", "アスファルト", "アスファルト", "asphalt pavement", "Travel & Places"),
    ("atatakasa-air", "おんだん", "オンダン", "温暖", "warm mild climate", "Nature & Weather"),
    ("atochi", "あとち", "アトチ", "跡地", "vacant site / former grounds", "Travel & Places"),
    ("awamori", "あわもり", "アワモリ", "泡盛", "Okinawan distilled rice spirit", "Food & Dining"),
    # B
    ("baaka", "ばーかー", "パーカー", "パーカー", "hooded sweatshirt / parka", "Clothes & Fashion"),
    ("baio-energy", "ばいおえねるぎー", "バイオエネルギー", "バイオエネルギー", "bioenergy", "Science & Nature"),
    ("bakuteria", "ばくてりあ", "バクテリア", "バクテリア", "bacteria / microbes", "Science & Nature"),
    ("ban", "ばん", "バン", "板", "wooden board / plank", "Tools & Goods"),
    ("bannou", "ばんのう", "バンノウ", "万能", "all-purpose / almighty", "Tools & Goods"),
    ("bansoukou", "ばんそうこう", "バンソウコウ", "絆創膏", "adhesive bandage / band-aid", "Body & Health"),
    ("baterii", "ばってりー", "バッテリー", "バッテリー", "rechargeable battery", "Tools & Goods"),
    ("beikoku", "べいこく", "ベイコク", "米国", "United States of America", "Travel & Places"),
    ("benten", "べんてん", "ベンテン", "弁天", "Benzaiten goddess of arts", "Culture & Society"),
    ("bijinesuman", "びじねすまん", "ビジネスマン", "ビジネスマン", "businessman", "People & Family"),
    ("biiru-kobo", "びーるこうぼ", "ビールコウボ", "ビール酵母", "brewer's yeast", "Food & Dining"),
    ("bokutou", "ぼくとう", "ボクトウ", "木刀", "wooden training sword", "Culture & Society"),
    ("booru-pen", "まんねんひつ", "マンネンヒツ", "万年筆", "fountain pen", "Tools & Goods"),
    ("bousou-zoku", "ぼうそうぞく", "ボウソウゾク", "暴走族", "motorcycle gang", "Culture & Society"),
    ("budou-shu", "ぶどうしゅ", "ブドウシュ", "葡萄酒", "grape wine", "Food & Dining"),
    ("bunbo", "ぶんぼ", "ブンボ", "分母", "denominator in fraction", "School & Work"),
    ("bunshi", "ぶんし", "ブンシ", "分子", "molecule / numerator", "Science & Nature"),
    ("bunseki", "ぶんせき", "ブンセキ", "分析", "data analysis", "School & Work"),
    ("buraindo", "ぶらいんど", "ブラインド", "ブラインド", "window blinds", "Home & Living"),
    ("buranko", "ぶらんこ", "ブランコ", "ブランコ", "playground swing", "Hobbies & Media"),
    # C
    ("chado", "ちゃどう", "チャドウ", "茶道", "tea ceremony way", "Culture & Society"),
    ("chakuriku", "ちゃくりく", "チャクリク", "着陸", "airplane landing", "Travel & Places"),
    ("chaser", "ちぇいさー", "チェイサー", "チェイサー", "water chaser with alcohol", "Food & Dining"),
    ("chikyuu", "ちきゅう", "チキュウ", "地球", "planet Earth", "Science & Nature"),
    ("chikyuugou", "ちきゅうぎ", "チキュウギ", "地球儀", "world terrestrial globe", "Tools & Goods"),
    ("chimata", "ちまた", "チマタ", "巷", "street corners / the public realm", "Culture & Society"),
    ("chiri", "ちり", "チリ", "地理", "geography", "School & Work"),
    ("chiriyoke", "ちりよけ", "チリヨケ", "塵除け", "dust coat / dust cover", "Clothes & Fashion"),
    ("chitsuryoku", "ちつりょく", "チツリョク", "知力", "mental intellectual power", "Emotions & Mind"),
    ("chousa", "ちょうさ", "チョウサ", "調査", "investigation / survey inquiry", "School & Work"),
    ("chousetsu", "ちょうせつ", "チョウセツ", "調節", "regulation / calibration", "Tools & Goods"),
    ("chouwa-harmony", "わごう", "ワゴウ", "和合", "concord / harmonious living", "Culture & Society"),
    ("chuuwa", "ちゅうわ", "チュウワ", "中和", "chemical neutralization", "Science & Nature"),
    # D
    ("daenshou", "だえんけい", "ダエンケイ", "楕円形", "oval elliptical shape", "Tools & Goods"),
    ("daihon", "だいほん", "ダイホン", "台本", "script / screenplay", "Hobbies & Media"),
    ("daiya", "だいや", "ダイヤ", "ダイヤ", "diamond / train timetable", "Travel & Places"),
    ("danmen", "だんめん", "ダンメン", "断面", "cross-section / profile", "Science & Nature"),
    ("danpen", "だんぺん", "ダンペン", "断片", "fragment / scrap", "Science & Nature"),
    ("denshikiki", "でんしきき", "デンシキキ", "電子機器", "electronic equipment", "Tools & Goods"),
    ("denshimon", "でんし", "デンシ", "電子", "electron particle", "Science & Nature"),
    ("desukutoppu", "ですくとっぷ", "デスクトップ", "デスクトップ", "desktop PC", "Tools & Goods"),
    ("dojou", "どじょう", "ドジョウ", "泥鰌", "pond loach (fish)", "Nature & Animals"),
    ("dojou-soil", "どじょう", "ドジョウ", "土壌", "agricultural soil / earth", "Science & Nature"),
    ("dokuden", "とくでん", "トクデン", "特電", "special cable dispatch", "Hobbies & Media"),
    ("donzoko", "どんぞこ", "ドンゾコ", "どん底", "rock bottom / lowest depths", "Emotions & Mind"),
    ("doubutsu", "どうぶつ", "ドウブツ", "動物", "animal / living creature", "Nature & Animals"),
    ("doubutsuen", "どうぶつえん", "ドウブツエン", "動物園", "zoo / zoological garden", "Travel & Places"),
    ("doukoku", "どうこく", "ドウコク", "慟哭", "wailing / lamentation", "Emotions & Mind"),
    ("douron", "どうろん", "ドウロン", "同論", "identical argument", "School & Work"),
    ("dousa", "どうさ", "ドウサ", "動作", "movement / operation / action", "Science & Nature"),
    ("douzou", "どうぞう", "ドウゾウ", "銅像", "bronze statue", "Culture & Society"),
    # E
    ("ea-mail", "えあめーる", "エアメール", "航空便", "airmail postage", "Tools & Goods"),
    ("eikyusei", "えいきゅう", "エイキュウ", "永久", "eternity / permanence", "Time & Calendar"),
    ("eisei", "えいせい", "エイセイ", "衛星", "orbital satellite", "Science & Nature"),
    ("ekitai", "えきたい", "エキタイ", "液体", "liquid fluid", "Science & Nature"),
    ("enerugii", "えねるぎー", "エネルギー", "エネルギー", "energy / power source", "Science & Nature"),
    ("engeki-kai", "げきだん", "ゲキダン", "劇団", "theatrical troupe", "Hobbies & Media"),
    ("enshinryoku", "えんしんりょく", "エンシンリョク", "遠心力", "centrifugal force", "Science & Nature"),
    ("entopi", "えんとろぴー", "エントロピー", "エントロピー", "thermodynamic entropy", "Science & Nature"),
    ("enzan", "えんざん", "エンザン", "演算", "mathematical calculation", "School & Work"),
    # F
    ("fando", "ふぁんど", "ファンド", "ファンド", "investment fund", "Shopping & Money"),
    ("fairu", "ふぁいる", "ファイル", "ファイル", "digital or paper file folder", "Tools & Goods"),
    ("fang", "ふぁん", "ファン", "ファン", "ventilator fan / admirer", "Tools & Goods"),
    ("fuin", "ふういん", "フウイン", "封印", "mystic seal / stamp", "Culture & Society"),
    ("fukugou", "ふくごう", "フクゴウ", "複合", "composite / complex", "Science & Nature"),
    ("fukusou-code", "どれすこーど", "ドレスコード", "ドレスコード", "dress code", "Culture & Society"),
    ("funabi", "ふなび", "フナビ", "船火", "ship lantern fire", "Culture & Society"),
    ("fundoshi", "ふんどし", "フンドシ", "褌", "traditional loincloth", "Clothes & Fashion"),
    ("furawaa", "ふらわー", "フラワー", "フラワー", "flower bouquet", "Nature & Weather"),
    ("fureemu", "ふれーむ", "フレーム", "フレーム", "picture frame / framework", "Tools & Goods"),
    ("furoto", "ふろーと", "フロート", "フロート", "ice cream float / marine buoy", "Food & Dining"),
    ("furuhon", "ふるほん", "フルホン", "古本", "secondhand book", "Hobbies & Media"),
    ("fusei", "ふせい", "フセイ", "不正", "injustice / fraud / cheating", "Culture & Society"),
    # G
    ("gaika", "がいか", "ガイカ", "外貨", "foreign currency", "Shopping & Money"),
    ("gakki-fu", "がくふ", "ガクフ", "楽譜", "sheet music score", "Hobbies & Media"),
    ("gakumon", "がくもん", "ガクモン", "学問", "scholarship / academic study", "School & Work"),
    ("gankou-cave", "がんくつ", "ガンクツ", "岩窟", "rocky cave / cavern", "Nature & Weather"),
    ("gassho-tsukuri", "がっしょうづくり", "ガッショウヅクリ", "合掌造り", "steep thatched roof architecture", "Culture & Society"),
    ("gedatsu", "げだつ", "ゲダツ", "解脱", "spiritual liberation / nirvana", "Culture & Society"),
    ("gempatsu", "げんぱつ", "ゲンパツ", "原発", "nuclear power plant", "Science & Nature"),
    ("genshi", "げんし", "ゲンシ", "原子", "atom", "Science & Nature"),
    ("genso", "げんそ", "ゲンソ", "元素", "chemical element", "Science & Nature"),
    ("giga", "ぎが", "ギガ", "ギガ", "gigabyte / gigahertz", "Science & Nature"),
    ("gin'iro", "ぎんいろ", "ギンイロ", "銀色", "silver color", "Colors & Styles"),
    ("giseki", "ぎせき", "ギセキ", "議席", "parliamentary seat", "Culture & Society"),
    ("go-game", "いご", "イゴ", "囲碁", "Go board game", "Hobbies & Media"),
    ("gorufu", "ごるふ", "ゴルフ", "ゴルフ", "golf sport", "Hobbies & Media"),
    ("gunshu-crowd", "ひとごみ", "ヒトゴミ", "人混み", "bustling crowd of people", "Travel & Places"),
    ("guraikou", "ごらいこう", "ゴライコウ", "御来光", "sunrise seen from mountain peak", "Culture & Society"),
    # H
    ("haado", "はーど", "ハード", "ハードウェア", "computer hardware", "Tools & Goods"),
    ("haadoru", "はーどる", "ハードル", "ハードル", "track hurdle / obstacle", "Hobbies & Media"),
    ("haburashi", "はぶらし", "ハブラシ", "歯ブラシ", "toothbrush", "Daily Life"),
    ("hachigatsu-summer", "はづき", "ハヅキ", "葉月", "August in lunar calendar", "Time & Calendar"),
    ("hadashi", "はだし", "ハダシ", "裸足", "bare feet / unshod", "Body & Health"),
    ("haguruma", "はぐるま", "ハグルマ", "歯車", "gear cogwheel", "Tools & Goods"),
    ("haikingu", "はいきんぐ", "ハイキング", "ハイキング", "hiking / trekking", "Hobbies & Media"),
    ("hakobune", "はこぶね", "ハコブネ", "方舟", "ark vessel", "Culture & Society"),
    ("hakusen", "はくせん", "ハクセン", "白線", "white painted road line", "Travel & Places"),
    ("hamigaki", "はみがき", "ハミガキ", "歯磨き", "brushing teeth", "Daily Life"),
    ("han'i", "はんい", "ハンイ", "範囲", "range / scope / perimeter", "Science & Nature"),
    ("hanbai", "はんばい", "ハンバイ", "販売", "merchandise sales / selling", "Shopping & Money"),
    ("hangyaku", "はんぎゃく", "ハンギャク", "反逆", "rebellion / treason", "Culture & Society"),
    ("hanten", "はんてん", "ハンテン", "半天", "quilted winter short coat", "Clothes & Fashion"),
    ("happi", "はっぴ", "ハッピ", "法被", "festival coat", "Clothes & Fashion"),
    ("hari-pin", "ぴん", "ピン", "ピン", "safety pin / hairpin", "Tools & Goods"),
    ("hasami-tool", "にっぱー", "ニッパー", "ニッパー", "cutting nippers / pliers", "Tools & Goods"),
    ("hatachi-age", "せいじん", "セイジン", "成人", "legal adult", "People & Family"),
    ("hatoba", "はとば", "ハトバ", "波止場", "wharf / harbor pier", "Travel & Places"),
    ("hatsu-yume", "はつゆめ", "ハツユメ", "初夢", "first dream of the New Year", "Culture & Society"),
    ("hayate", "はやて", "ハヤテ", "疾風", "sudden gale / tempest", "Nature & Weather"),
    ("heishi", "へいし", "ヘイシ", "兵士", "soldier / infantryman", "People & Family"),
    ("heya-room", "しつ", "シツ", "室", "chamber / apartment room", "Home & Living"),
    ("hiatari", "ひあたり", "ヒアタリ", "日当たり", "sunlight exposure in room", "Home & Living"),
    ("hifu-skin", "はだ", "ハダ", "肌", "delicate skin / texture", "Body & Health"),
    ("hikari", "ひかり", "ヒカリ", "光", "radiant light / beam", "Science & Nature"),
    ("hishochi", "ひしょち", "ヒショチ", "避暑地", "summer resort getaway", "Travel & Places"),
    ("hiyoke", "ひよけ", "ヒヨケ", "日除け", "sun awning / shade blind", "Home & Living"),
    ("hizashi", "ひざし", "ヒザシ", "日差し", "sunlight rays / sunbeams", "Nature & Weather"),
    ("hokousha", "ほこうしゃ", "ホコウシャ", "歩行者", "pedestrian on street", "Travel & Places"),
    ("hoshizora-night", "せいてん", "セイテン", "星天", "starry sky firmament", "Nature & Weather"),
    ("hougaku", "ほうがく", "ホウガク", "方角", "compass bearing / direction", "Travel & Places"),
    ("houkago", "ほうかご", "ホウカゴ", "放課後", "after school hours", "School & Work"),
    ("housou", "ほうそう", "ホウソウ", "放送", "radio / television broadcasting", "Hobbies & Media"),
    # I
    ("ibento-hall", "かいじょう", "カイジョウ", "会場", "event hall / venue", "Travel & Places"),
    ("ichiba", "いちば", "イチバ", "市場", "open marketplace / fish market", "Shopping & Money"),
    ("idobata-kaigi", "いどばたかいぎ", "イドバタカイギ", "井戸端会議", "neighborhood chat / gossip session", "Social & Communication"),
    ("igusa", "いぐさ", "イグサ", "藺草", "soft rush reed for tatami", "Home & Living"),
    ("ikada", "いかだ", "イカダ", "筏", "wooden log raft", "Travel & Places"),
    ("ikari", "いかり", "イカリ", "錨", "ship anchor", "Tools & Goods"),
    ("ikari-anger", "いかり", "イカリ", "怒り", "anger / rage / wrath", "Emotions & Mind"),
    ("ikizukai", "いきづかい", "イキヅカイ", "息遣い", "breathing / audible breath", "Body & Health"),
    ("ikuji-care", "こそだて", "コソダテ", "子育て", "raising offspring / parenting", "People & Family"),
    ("imou", "いも", "イモ", "藷", "sweet yam tuber", "Food & Dining"),
    ("inbaundo", "いんばうんど", "インバウンド", "インバウンド", "inbound inbound tourism", "Travel & Places"),
    ("intabyuu", "いんたびゅー", "インタビュー", "インタビュー", "journalistic interview", "Hobbies & Media"),
    ("intaanetto", "いんたーねっと", "インターネット", "インターネット", "the global Internet", "Science & Nature"),
    ("iruka", "いるか", "イルカ", "海豚", "dolphin", "Nature & Animals"),
    ("isan", "いさん", "イサン", "遺産", "cultural heritage / bequest", "Culture & Society"),
    ("ishidan", "いしだん", "イシダン", "石段", "stone stairway steps", "Travel & Places"),
    ("ishigaki", "いしがき", "イシガキ", "石垣", "castle stone fortification wall", "Travel & Places"),
    ("ishidourou", "いしどうろう", "イシドウロウ", "石灯籠", "stone garden lantern", "Culture & Society"),
    ("isshou-life", "しょうがい", "ショウガイ", "生涯", "entire course of life", "Time & Calendar"),
    ("itsukushima", "いつくしま", "イツクシマ", "厳島", "Itsukushima Miyajima shrine island", "Travel & Places"),
    # J
    ("jaketto-suit", "うわぎぎ", "ウワギギ", "上着", "jacket coat", "Clothes & Fashion"),
    ("jazu", "じゃず", "ジャズ", "ジャズ", "jazz music", "Hobbies & Media"),
    ("jibaku", "じばく", "ジバク", "自縛", "self-restraint / binding oneself", "Culture & Society"),
    ("jidouhanbaiki", "じどうはんばいき", "ジドウハンバイキ", "自動販売機", "automated vending machine", "Daily Life"),
    ("jikan-time", "とき", "トキ", "時", "hour / moment in time", "Time & Calendar"),
    ("jikkenshitsu", "じっけんしつ", "ジッケンシツ", "実験室", "science laboratory", "School & Work"),
    ("jisshitsu", "じっしつ", "ジッシツ", "実質", "substance / real essence", "School & Work"),
    ("jitsugetsu", "じつげつ", "ジツゲツ", "日月", "sun and moon / passing days", "Time & Calendar"),
    ("joubu", "じょうぶ", "ジョウブ", "上部", "upper part / top surface", "Tools & Goods"),
    ("jouken", "じょうけん", "ジョウケン", "条件", "requirement / prerequisite condition", "School & Work"),
    ("juukyo", "じゅうきょ", "ジュウキョ", "住居", "residence / dwelling home", "Home & Living"),
    ("juunishi", "じゅうにし", "ジュウニシ", "十二支", "twelve Chinese zodiac signs", "Culture & Society"),
    # K
    ("kabi", "かび", "カビ", "黴", "mold / mildew fungus", "Nature & Weather"),
    ("kabuki-dance", "ぶがく", "ブガク", "舞楽", "imperial court dance and music", "Culture & Society"),
    ("kachou", "かちょう", "カチョウ", "課長", "section chief / head of division", "School & Work"),
    ("kagakusha", "かがくしゃ", "カガクシャ", "科学者", "scientist", "People & Family"),
    ("kagami-mochi", "かがみもち", "カガミモチ", "鏡餅", "stacked round New Year mochi", "Culture & Society"),
    ("kaidan-ghost", "かいだん", "カイダン", "怪談", "spooky ghost story tale", "Culture & Society"),
    ("kaihou", "かいほう", "カイホウ", "開放", "openness / release / liberation", "Culture & Society"),
    ("kaiketsu", "かいけつ", "カイケツ", "解決", "resolution / problem solving", "School & Work"),
    ("kaisuiyoku", "かいすいよく", "カイスイヨク", "海水浴", "sea swimming / beach bathing", "Hobbies & Media"),
    ("kaiteki-living", "いごこち", "イゴコチ", "居心地", "comfort of living / coziness", "Home & Living"),
    ("kakurega", "かくれが", "カクレガ", "隠れ家", "secret hideaway / cozy retreat", "Travel & Places"),
    ("kamaboko-board", "かまぼこいた", "カマボコイタ", "蒲鉾板", "wooden fishcake board", "Food & Dining"),
    ("kami-paper", "ようし", "ヨウシ", "用紙", "blank printing paper sheet", "Tools & Goods"),
    ("kamifubuki", "かみふぶき", "カミフブキ", "紙吹雪", "confetti paper flutter", "Culture & Society"),
    ("kamikakushi", "かみかくし", "カミカクシ", "神隠し", "spirited away by deities", "Culture & Society"),
    ("kanaderu", "かなで", "カナデ", "奏で", "musical playing / melody", "Hobbies & Media"),
    ("kanji-stroke", "ひっじゅん", "ヒツジュン", "筆順", "stroke order of kanji", "School & Work"),
    ("kanna", "かんな", "カンナ", "鉋", "woodworking plane", "Tools & Goods"),
    ("kansha", "かんしゃ", "カンシャ", "感謝", "deep heartfelt gratitude", "Emotions & Mind"),
    ("kanso-desert", "かんそう", "カンソウ", "乾燥", "dryness / dehydration", "Nature & Weather"),
    ("karuta", "かるた", "カルタ", "かるた", "traditional poetry card game", "Culture & Society"),
    ("kasabuta", "かさぶた", "カサブタ", "痂", "scab on skin wound", "Body & Health"),
    ("kassai", "かっさい", "カッサイ", "喝采", "acclamation / applause cheer", "Culture & Society"),
    ("katabami", "かたばみ", "カタバミ", "片喰", "creeping woodsorrel plant", "Nature & Weather"),
    ("katana", "かたな", "カタナ", "刀", "samurai katana sword", "Culture & Society"),
    ("kawa-riverbed", "かわら", "カワラ", "河原", "dry riverbed with stones", "Nature & Weather"),
    ("kayaku", "かやく", "カヤク", "火薬", "gunpowder / firework explosive", "Tools & Goods"),
    ("keiken", "けいけん", "ケイケン", "経験", "personal experience", "School & Work"),
    ("keitai", "けいたい", "ケイタイ", "携帯電話", "mobile mobile phone", "Tools & Goods"),
    ("kekka", "けっか", "ケッカ", "結果", "outcome / consequence / result", "School & Work"),
    ("kekkai", "けっかい", "ケッカイ", "結界", "sacred protective barrier boundary", "Culture & Society"),
    ("kemushi", "けむし", "ケムシ", "毛虫", "hairy caterpillar", "Nature & Animals"),
    ("kendo-shinai", "しない", "シナイ", "竹刀", "bamboo practice kendo sword", "Culture & Society"),
    ("kenkyuu", "けんきゅう", "ケンキュウ", "研究", "academic research / inquiry", "School & Work"),
    ("kenshou", "けんしょう", "ケンショウ", "懸賞", "prize contest / sweepstakes", "Shopping & Money"),
    ("kibun", "きぶん", "キブン", "気分", "mood / emotional feeling", "Emotions & Mind"),
    ("kikan", "きかん", "キカン", "期間", "duration of time / span", "Time & Calendar"),
    ("kikai", "きかい", "キカイ", "機械", "machine / mechanism", "Tools & Goods"),
    ("kikai-opportunity", "きかい", "キカイ", "機会", "golden opportunity / chance", "Daily Life"),
    ("kin'en", "きんえん", "キンエン", "禁煙", "no smoking policy", "Culture & Society"),
    ("kingyo", "きんぎょ", "キンギョ", "金魚", "goldfish", "Nature & Animals"),
    ("kinpaku", "きんぱく", "キンパク", "金箔", "pure gold leaf foil", "Culture & Society"),
    ("kinrin", "きんりん", "キンリン", "近隣", "immediate neighborhood", "Travel & Places"),
    ("kirei-flower", "はなたばば", "ハナタババ", "花房", "flower cluster raceme", "Nature & Weather"),
    ("kiritto", "きりつ", "キリツ", "規律", "discipline / code of conduct", "Culture & Society"),
    ("kiroku", "きろく", "キロク", "記録", "document record / score", "School & Work"),
    ("kiryuu", "きりゅう", "キリュウ", "気流", "air stream / atmospheric current", "Nature & Weather"),
    ("kisaki", "きさき", "キサキ", "妃", "queen consort / empress", "People & Family"),
    ("kishou", "きしょう", "キショウ", "気象", "meteorology / atmospheric weather", "Nature & Weather"),
    ("kitsune-udon", "きつね", "キツネ", "狐火", "foxfire / kitsunebi glow", "Culture & Society"),
    ("kocha", "こうちゃ", "コウチャ", "紅茶", "black tea", "Food & Dining"),
    ("kogamo", "こがも", "コガモ", "小鴨", "teal duckling", "Nature & Animals"),
    ("kogitte", "こぎって", "コギッテ", "小切手", "bank check", "Shopping & Money"),
    ("koibumi", "こいぶみ", "コイブミ", "恋文", "love letter", "Social & Communication"),
    ("kokan", "こかん", "コカン", "股間", "crotch / thigh area", "Body & Health"),
    ("koku", "こく", "コク", "穀", "cereal grain", "Food & Dining"),
    ("kokuban", "こくばん", "コクバン", "黒板", "school blackboard / chalkboard", "School & Work"),
    ("kokusai", "こくさい", "コクサイ", "国際", "international relations", "Culture & Society"),
    ("komugi", "こむぎ", "コムギ", "小麦", "wheat grain", "Food & Dining"),
    ("komugiko", "こむぎこ", "コムギコ", "小麦粉", "wheat flour", "Food & Dining"),
    ("konseki", "こんせき", "コンセキ", "痕跡", "trace / footprint / vestige", "Nature & Weather"),
    ("koukousei", "こうこうせい", "コウコウセイ", "高校生", "high school student", "People & Family"),
    ("koushin", "こうしん", "コウシン", "更新", "update / renewal of status", "School & Work"),
    ("koyomi", "こよみ", "コヨミ", "暦", "lunar calendar / almanac", "Time & Calendar"),
    ("kubisuji", "くびすじ", "クビスジ", "首筋", "nape / back of the neck", "Body & Health"),
    ("kujou", "くじょう", "クジョウ", "苦情", "complaint / grievance", "Social & Communication"),
    ("kumo", "くも", "クモ", "蜘蛛", "spider (arachnid)", "Nature & Animals"),
    ("kumo-cloud", "くも", "クモ", "雲", "white cloud in sky", "Nature & Weather"),
    ("kurayami", "くらやみ", "クラヤミ", "暗闇", "total darkness / gloom", "Nature & Weather"),
    ("kurokami", "くろかみ", "クロカミ", "黒髪", "glossy black hair", "Body & Health"),
    ("kusuri", "くすり", "クスリ", "薬", "medicine / pharmaceutical remedy", "Body & Health"),
    ("kusuriya", "くすりや", "クスリヤ", "薬屋", "pharmacy drug store", "Travel & Places"),
    ("kyuujitsu-rest", "あきび", "アキビ", "空き日", "unbooked open day off", "Time & Calendar"),
    # M
    ("matsubayashi", "まつばやし", "マツバヤシ", "松林", "pine grove woods", "Nature & Weather"),
    ("mizutamari", "みずたまり", "ミズタマリ", "水たまり", "rain puddle", "Nature & Weather"),
    ("monokuro", "ものくろ", "モノクロ", "モノクロ", "monochrome / black-and-white", "Hobbies & Media"),
    # N
    ("nagare", "ながれ", "ナガレ", "流れ", "current / river flow / trend", "Nature & Weather"),
    ("namida", "なみだ", "ナミダ", "涙", "teardrops", "Emotions & Mind"),
    ("nanohana", "なのはな", "ナノハナ", "菜の花", "canola rapeseed flowers", "Nature & Weather"),
    ("neko", "ねこ", "ネコ", "猫", "domestic cat", "Nature & Animals"),
    ("nemoto", "ねもと", "ネモト", "根本", "root base / foundation", "Nature & Weather"),
    ("netsu", "ねつ", "ネツ", "熱", "fever / thermal heat / passion", "Body & Health"),
    ("nodo-chinko", "のどちんこ", "ノドチンコ", "口蓋垂", "uvula in throat", "Body & Health"),
    ("nokori", "のこり", "ノコリ", "残り", "remnant / leftover / remainder", "Daily Life"),
    # O
    ("odoroki", "おどろき", "オドロキ", "驚き", "surprise / astonishing wonder", "Emotions & Mind"),
    ("ogawa", "おがわ", "オガワ", "小川", "babbling brook / stream", "Nature & Weather"),
    ("omoide", "おもいで", "オモイデ", "思い出", "cherished memory / nostalgia", "Emotions & Mind"),
    ("omotena-shi", "もてなし", "モテナシ", "歓待", "lavish hospitality banquet", "Culture & Society"),
    ("otoshimono-lost", "いしつぶつ", "イシツブツ", "遺失物", "lost articles at counter", "Daily Life"),
    # R
    ("rensou", "れんそう", "レンソウ", "連想", "mental association of ideas", "Emotions & Mind"),
    ("rinsan", "りんさん", "リンサン", "燐酸", "phosphoric acid", "Science & Nature"),
    ("rinya", "りんや", "リンヤ", "林野", "forest and fields", "Nature & Weather"),
    ("rokkotsu", "ろっこつ", "ロッコツ", "肋骨", "rib bones", "Body & Health"),
    ("ryuusei", "りゅうせい", "リュウセイ", "流星", "falling shooting star", "Nature & Weather"),
    # S
    ("saikoro", "さいころ", "サイコロ", "賽子", "six-sided dice cube", "Hobbies & Media"),
    ("sakura-fubuki", "さくらふぶき", "サクラフブキ", "桜吹雪", "blizzard of falling cherry petals", "Nature & Weather"),
    ("sanbashi", "さんばし", "サンバシ", "桟橋", "landing pier / jetty", "Travel & Places"),
    ("sanza", "さんざ", "サンザ", "山茶", "camellia flower tea", "Food & Dining"),
    ("seiza", "せいざ", "セイザ", "星座", "astronomical constellation", "Nature & Weather"),
    ("sekiryoushin", "せきりょう", "セキリョウ", "寂寥", "loneliness / quiet solitude", "Emotions & Mind"),
    ("senkou-firework", "せんこうはなび", "センコウハナビ", "線香花火", "sparkler firework", "Culture & Society"),
    ("seseragi", "せせらぎ", "セセラギ", "せせらぎ", "murmuring of shallow stream", "Nature & Weather"),
    ("shichigatsu", "しちがつ", "シチガツ", "七月", "July", "Time & Calendar"),
    ("shigatsu", "しがつ", "シガツ", "四月", "April", "Time & Calendar"),
    ("shizuku", "しずく", "シズク", "雫", "water drop / dew drop", "Nature & Weather"),
    ("suzushisa", "すずしさ", "スズシサ", "涼しさ", "refreshing coolness in summer", "Nature & Weather"),
    # T
    ("tamashi", "たましい", "タマシイ", "魂", "soul / spirit / psyche", "Emotions & Mind"),
    ("tanoshimi", "たのしみ", "タノシミ", "楽しみ", "pleasure / joyful anticipation", "Emotions & Mind"),
    ("touge", "とうげ", "トウゲ", "峠", "mountain pass / crest", "Travel & Places"),
    ("tsukiyo", "つきよ", "ツキヨ", "月夜", "moonlit night", "Nature & Weather"),
    ("tsumugi", "つむぎ", "ツムギ", "紬", "pongee raw silk cloth", "Clothes & Fashion"),
    # U
    ("uchuu", "うちゅう", "ウチュウ", "宇宙", "outer cosmos / universe", "Science & Nature"),
    ("uchuusen", "うちゅうせん", "ウチュウセン", "宇宙船", "spaceship / spacecraft", "Science & Nature"),
    ("umibe", "うみべ", "ウミベ", "海辺", "seaside / beachshore", "Travel & Places"),
    ("unabara", "うなばら", "ウナバラ", "海原", "vast expanse of open ocean", "Nature & Weather"),
    ("usagi", "うさぎ", "ウサギ", "兎", "hare / rabbit", "Nature & Animals"),
    # W
    ("wakaba", "わかば", "ワカバ", "若葉", "young tender green leaves", "Nature & Weather"),
    ("wataridori", "わたりどり", "ワタリドリ", "渡り鳥", "migratory bird", "Nature & Animals"),
    # Y
    ("yamabiko", "やまびこ", "ヤマビコ", "山彦", "mountain echo spirit", "Nature & Weather"),
    ("yuki-akari", "ゆきあかり", "ユキアカリ", "雪明かり", "snow light glow", "Nature & Weather"),
    ("yuubae", "ゆうばえ", "ユウバエ", "夕映え", "evening sunset glow", "Nature & Weather"),
    ("yuunagi", "ゆうなぎ", "ユウナギ", "夕凪", "evening calm sea breeze lull", "Nature & Weather"),
    # Z
    ("zatsudan", "ざつだん", "ザツダン", "雑談", "casual friendly chitchat", "Social & Communication"),
    # Additional authentic Japanese nouns
    ("aisatsu-go", "あいさつことば", "アイサツコトバ", "挨拶言葉", "formal greeting phrase", "Social & Communication"),
    ("akachan-kutsu", "ふぁーすとゆーず", "ファーストシューズ", "初靴", "baby's first shoes", "Clothes & Fashion"),
    ("akichi-land", "くうち", "クウチ", "空地", "open vacant lot", "Travel & Places"),
    ("akikaze-breeze", "しゅうふう", "シュウフウ", "秋風", "gentle autumn breeze", "Nature & Weather"),
    ("akitsushima", "あきつしま", "アキツシマ", "秋津島", "poetic name for ancient Japan", "Culture & Society"),
    ("amado-door", "あまどいた", "アマドイタ", "雨戸板", "wooden storm shutter board", "Home & Living"),
    ("amayadori", "あまやどり", "アマヤドリ", "雨宿り", "sheltering from the rain", "Daily Life"),
    ("ameagari", "あめあがり", "アメアガリ", "雨上がり", "clearing up after rain", "Nature & Weather"),
    ("asagohan-meal", "ちょうしょく", "チョウショク", "朝食", "morning breakfast", "Food & Dining"),
    ("asakaze", "あさかぜ", "アサカゼ", "朝風", "morning breeze", "Nature & Weather"),
    ("ashikubi-band", "あんくれっと", "アンクレット", "足輪", "anklet jewelry", "Clothes & Fashion"),
    ("baakaa-hood", "ふーど", "フード", "フード", "jacket hood", "Clothes & Fashion"),
    ("baggu-tote", "とーとばっぐ", "トートバッグ", "トートバッグ", "tote bag", "Clothes & Fashion"),
    ("bakku-seat", "こうぶざせき", "コウブザセキ", "後部座席", "rear backseat", "Travel & Places"),
    ("biiru-mug", "じょっき", "ジョッキ", "ジョッキ", "beer mug / stein", "Food & Dining"),
    ("chado-kake", "かけじく", "カケジク", "掛け軸", "hanging scroll painting", "Culture & Society"),
    ("chakuriku-run", "かっそうろ", "カッソウロ", "滑走路", "airport runway", "Travel & Places"),
    ("chawan-cup", "ゆのみぢゃわん", "ユノミヂャワン", "湯呑み茶碗", "ceramic tea cup bowl", "Home & Living"),
    ("choumi-ryou", "だしの素", "ダシノモト", "出汁の素", "instant dashi powder bouillon", "Food & Dining"),
    ("daidokoro-mat", "きっちんまっと", "キッチンマット", "台所敷物", "kitchen floor mat", "Home & Living"),
    ("danketsu-flag", "はたじるし", "ハタジルシ", "旗印", "banner / slogan / flag", "Culture & Society"),
    ("denshoku-light", "いるみねーしょん", "イルミネーション", "電飾", "holiday illuminations", "Culture & Society"),
    ("dokushin-life", "たんしん", "タンシン", "単身", "single life away from family", "People & Family"),
    ("donzoko-pit", "ふち", "フチ", "淵", "deep pool / abyss", "Nature & Weather"),
    ("douwa-tale", "むかしばなし", "ムカシバナシ", "昔話", "ancient folk legend", "Hobbies & Media"),
    ("eiga-ticket", "えいがけん", "エイガケン", "映画券", "movie theater ticket", "Hobbies & Media"),
    ("ekimae-square", "ひろば", "ヒロバ", "広場", "station plaza / public square", "Travel & Places"),
    ("engawa-porch", "ぬれえん", "ヌレエン", "濡れ縁", "open wooden outer veranda", "Home & Living"),
    ("ensoku-lunch", "おべんとうばこ", "オベントウバコ", "お重", "tiered jubako picnic box", "Food & Dining"),
    ("fubuki-snow", "じふぶき", "ジフブキ", "地吹雪", "ground blizzard / drifting snow", "Nature & Weather"),
    ("fukusou-suit", "すーつ", "スーツ", "スーツ", "formal western suit", "Clothes & Fashion"),
    ("fune-ferry", "ふぇりー", "フェリー", "フェリー", "car ferry boat", "Travel & Places"),
    ("furugi-shop", "こぎてん", "コギテン", "古着屋", "vintage thrift clothing shop", "Travel & Places"),
    ("gakkou-gate", "こうもん", "コウモン", "校門", "school main gate", "School & Work"),
    ("gakumon-book", "さんこうしょ", "サンコウショ", "参考書", "study reference guide book", "School & Work"),
    ("garasudo-window", "まどがらす", "マドガラス", "窓ガラス", "window pane glass", "Home & Living"),
    ("gekijou-seat", "きゃくせき", "キャクセキ", "客席", "theater audience seat", "Culture & Society"),
    ("ginkou-atm", "えーてぃーえむ", "エーティーエム", "現金自動預払機", "ATM cash dispenser", "Shopping & Money"),
    ("haburashi-stand", "はぶらしたて", "ハブラシタテ", "歯ブラシ立て", "toothbrush holder stand", "Home & Living"),
    ("hakubutsukan-ticket", "にゅうかんけん", "ニュウカンケン", "入館券", "museum admission ticket", "Travel & Places"),
    ("hanabi-taikai", "はなびたいかい", "ハナビタイカイ", "花火大会", "fireworks festival display", "Culture & Society"),
    ("haru-blossom", "はるのひかり", "ハルノヒカリ", "春光", "gentle spring sunshine", "Nature & Weather"),
    ("hasami-kitchen", "きっちんばさみ", "キッチンバサミ", "料理鋏", "kitchen poultry shears", "Tools & Goods"),
    ("hikidashi-desk", "つくえのひきだし", "ツクエノヒキダシ", "抽斗", "desk drawer", "Home & Living"),
    ("hizashi-afternoon", "こもれび", "コモレビ", "木漏れ日", "sunlight filtering through trees", "Nature & Weather"),
    ("hondana-shelf", "しょだな", "ショダナ", "書棚", "bookshelf / library stack", "Home & Living"),
    ("hoteru-room", "きゃくしつ", "キャクシツ", "客室", "hotel guest room", "Travel & Places"),
    ("inaka-village", "のうそん", "ノウソン", "農村", "agricultural farming village", "Travel & Places"),
    ("jitsumu-exp", "じつむけいけん", "ジツムケイケン", "実務経験", "practical working experience", "School & Work"),
    ("kaigi-agenda", "ぎだい", "ギダイ", "議題", "meeting agenda topic", "School & Work"),
    ("kaimono-bag", "えこばっぐ", "エコバッグ", "買物袋", "reusable grocery shopping bag", "Daily Life"),
    ("kamaboko-slice", "いたつけ", "イタツケ", "板付け", "steamed fish paste block", "Food & Dining"),
    ("kasa-stand", "かさたて", "カサタテ", "傘立て", "umbrella stand", "Home & Living"),
    ("keizai-growth", "けいざいせいちょう", "ケイザイセイチョウ", "経済成長", "economic expansion growth", "Culture & Society"),
    ("kendo-mask", "めん", "メン", "面", "kendo protective head mask", "Culture & Society"),
    ("keshiki-view", "ちょうぼう", "チョウボウ", "眺望", "panoramic scenic prospect", "Travel & Places"),
    ("kiri-morning", "あさきり", "アサキリ", "朝煙", "morning river haze", "Nature & Weather"),
    ("kocha-pot", "てぃーぽっと", "ティーポット", "茶壺", "tea brewing pot", "Home & Living"),
    ("kokuban-eraser", "こくばんふき", "コクバンフキ", "黒板拭き", "chalkboard eraser", "Tools & Goods"),
    ("kouen-bench", "べんち", "ベンチ", "腰掛け", "park sitting bench", "Travel & Places"),
    ("kuukou-gate", "とうじょうぐち", "トウジョウグチ", "搭乗口", "airport boarding gate", "Travel & Places"),
    ("matsuri-stall", "やたい", "ヤタイ", "屋台", "festival food street stall", "Culture & Society"),
    ("mizugashi-fruit", "くだものざら", "クダモノザラ", "果物皿", "fruit serving compote dish", "Food & Dining"),
    ("nagashi-counter", "ちょうりだい", "チョウリダイ", "調理台", "kitchen food preparation counter", "Home & Living"),
    ("onsen-towel", "てぬぐい", "テヌグイ", "手拭い", "traditional cotton hand towel", "Daily Life"),
    ("origami-paper", "おりがみようし", "オリガミヨウシ", "折り紙用紙", "origami folding paper sheet", "Hobbies & Media"),
    ("rakugo-stage", "こうざ", "コウザ", "高座", "rakugo storyteller stage dais", "Culture & Society"),
    ("reizouko-door", "れいぞうこのとびら", "レイゾウコノトビラ", "冷蔵庫扉", "refrigerator door", "Home & Living"),
    ("sakura-petal", "はなふぶき", "ハナフブキ", "花吹雪", "fluttering petal storm", "Nature & Weather"),
    ("sentakki-drum", "せんたくそう", "センタクソウ", "洗濯槽", "washing machine drum tub", "Home & Living"),
    ("shinkansen-ticket", "とっきゅうけん", "トッキュウケン", "特急券", "bullet train express ticket", "Travel & Places"),
    ("taiyaki-pan", "やきがた", "ヤキガタ", "焼き型", "taiyaki iron waffle mold", "Food & Dining"),
    ("tatami-room", "ざしき", "ザシキ", "座敷", "formal Japanese tatami parlor", "Home & Living"),
    ("tokkyuu-train", "とっきゅうれっしゃ", "トッキュウレッシャ", "特急列車", "limited express locomotive", "Travel & Places"),
    ("tsukue-lamp", "でんきすたんどばり", "デンキスタンドバリ", "卓上灯", "desk reading lamp", "Home & Living"),
    ("uchiwabi-fan", "せんすばり", "センスバリ", "団扇骨", "bamboo fan ribs", "Culture & Society"),
    ("unadon-bowl", "どんぶり", "ドンブリ", "丼", "ceramic rice bowl", "Food & Dining"),
    ("washitsu-alcove", "どこ", "ドコ", "床", "tokonoma alcove floor", "Home & Living"),
    ("yakitori-skewer", "たけぐし", "タケグシ", "竹串", "bamboo cooking skewer", "Food & Dining"),
    ("yukata-belt", "おび", "オビ", "帯", "kimono & yukata sash belt", "Clothes & Fashion"),
    ("zabuton-cover", "ざぶとんかばー", "ザブトンカバー", "座布団カバー", "floor cushion fabric slipcover", "Home & Living")
]
