# Travel, Geography, Weather, Nature, Places, Cities, Time, Calendar
DATA = [
    # A
    ("akatombo", "あかとんぼ", "アカトンボ", "赤蜻蛉", "red dragonfly", "Nature & Animals"),
    ("akibare", "あきばれ", "アキバレ", "秋晴れ", "clear autumn weather", "Nature & Weather"),
    ("akikaze", "あきかぜ", "アキカゼ", "秋風", "autumn breeze", "Nature & Weather"),
    ("akizora", "あきぞら", "アキゾラ", "秋空", "autumn sky", "Nature & Weather"),
    ("amagumo", "あまぐも", "アマグモ", "雨雲", "rain clouds", "Nature & Weather"),
    ("amamizu", "あまみず", "アマミズ", "雨水", "rainwater", "Nature & Weather"),
    ("amatsuyu", "あまつゆ", "アマツユ", "雨露", "rain and dew", "Nature & Weather"),
    ("amigasa", "あみがさ", "アミガサ", "編み笠", "braided straw hat", "Culture & Society"),
    ("ankoku", "あんこく", "アンコク", "暗黒", "pitch darkness / blackness", "Nature & Weather"),
    ("aoba", "あおば", "アオバ", "青葉", "fresh green leaves", "Nature & Weather"),
    ("aoumi", "あおうみ", "アオウミ", "青海", "blue ocean / azure sea", "Nature & Weather"),
    ("arano", "あらの", "アラノ", "荒野", "wasteland / wilderness", "Nature & Weather"),
    ("asagasumi", "あさがすみ", "アサガスミ", "朝霞", "morning haze / mist", "Nature & Weather"),
    ("asake", "あさけ", "アサケ", "朝気", "cool morning air", "Nature & Weather"),
    ("asamoya", "あさもや", "アサモヤ", "朝靄", "morning fog", "Nature & Weather"),
    ("asayake", "あさやけ", "アサヤケ", "朝焼け", "sunrise glow / dawn glow", "Nature & Weather"),
    ("ashiba", "あしば", "アシバ", "足場", "scaffolding / footing", "Tools & Goods"),
    ("atatakasa", "あたたかさ", "アタタカサ", "暖かさ", "warmth (temperature)", "Nature & Weather"),
    # B
    ("bakufuu", "ばくふう", "バクフウ", "爆風", "blast / explosion gust", "Nature & Weather"),
    ("banshunjitsu", "ばんしゅん", "バンシュン", "晩春", "late spring", "Time & Calendar"),
    ("banshuu", "ばんしゅう", "バンシュウ", "晩秋", "late autumn", "Time & Calendar"),
    ("banto", "ばんと", "バント", "万博", "world exposition", "Culture & Society"),
    ("basho", "ばしょ", "バショ", "場所", "place / location / venue", "Travel & Places"),
    ("biiku", "びーち", "ビーチ", "ビーチ", "beach / sandy coast", "Travel & Places"),
    ("bijutsukan", "びじゅつかん", "ビジュツカン", "美術館", "art museum / art gallery", "Travel & Places"),
    ("bochi", "ぼち", "ボチ", "墓地", "cemetery / graveyard", "Travel & Places"),
    ("bokujou", "ぼくじょう", "ボクジョウ", "牧場", "pasture / dairy farm", "Travel & Places"),
    ("bousou", "ぼうそう", "ボウソウ", "房総", "Boso Peninsula", "Travel & Places"),
    ("buurubaa", "ぶーるばーど", "ブールバード", "ブールバード", "boulevard / avenue", "Travel & Places"),
    ("byouin", "びょういん", "ビョウイン", "病院", "hospital / medical center", "Travel & Places"),
    # C
    ("chachitsu", "ちゃしつ", "チャシツ", "茶室", "tea ceremony room / teahouse", "Culture & Society"),
    ("chikagai", "ちかがい", "チカガイ", "地下街", "underground shopping concourse", "Travel & Places"),
    ("chikatetsu", "ちかてつ", "チカテツ", "地下鉄", "subway / metro train", "Travel & Places"),
    ("chirimen", "ちりめん", "チリメン", "縮緬", "crepe silk fabric", "Clothes & Fashion"),
    ("choujou", "ちょうじょう", "チョウジョウ", "頂上", "mountain summit / mountain top", "Nature & Weather"),
    ("chuushajou", "ちゅうしゃじょう", "チュウシャジョウ", "駐車場", "parking lot / parking garage", "Travel & Places"),
    # D
    ("daichi", "だいち", "ダイチ", "大地", "vast earth / great land / plateau", "Nature & Weather"),
    ("daishizen", "だいしぜん", "ダイシゼン", "大自然", "great outdoors / Mother Nature", "Nature & Weather"),
    ("dani", "だに", "ダニ", "谷", "valley / ravine", "Nature & Weather"),
    ("danryuu", "だんりゅう", "ダンリュウ", "暖流", "warm ocean current", "Nature & Weather"),
    ("deguchi", "でぐち", "デグチ", "出口", "exit doorway / egress", "Travel & Places"),
    ("douro", "どうろ", "ドウロ", "道路", "highway / road / street", "Travel & Places"),
    ("dokyumento", "どきゅめんと", "ドキュメント", "ドキュメント", "documentary / document", "Hobbies & Media"),
    # E
    ("ekimae", "えきまえ", "エキマエ", "駅前", "in front of the train station", "Travel & Places"),
    ("ekisha", "えきしゃ", "エキシャ", "駅舎", "train station building", "Travel & Places"),
    ("engei", "えんげい", "エンゲイ", "園芸", "gardening / horticulture", "Hobbies & Media"),
    ("engawa", "えんがわ", "エンガワ", "縁側", "traditional veranda porch", "Home & Living"),
    ("ensoku", "えんそく", "エンソク", "遠足", "school excursion / day trip", "Travel & Places"),
    # F
    ("fubuki", "ふぶき", "フブキ", "吹雪", "snowstorm / blizzard", "Nature & Weather"),
    ("fujisan", "ふじさん", "フジサン", "富士山", "Mount Fuji", "Travel & Places"),
    ("fumikiri", "ふみきり", "フミキリ", "踏切", "railroad crossing", "Travel & Places"),
    ("fune", "ふね", "フネ", "船", "ship / boat / ferry", "Travel & Places"),
    ("furasuko", "ふらすこ", "フラスコ", "フラスコ", "laboratory flask", "Tools & Goods"),
    ("furou", "ふろう", "フロウ", "不老", "eternal youth / agelessness", "Culture & Society"),
    ("furusato", "ふるさと", "フルサト", "故郷", "hometown / ancestral birthplace", "Travel & Places"),
    # G
    ("gaitou", "がいとう", "ガイトウ", "街灯", "streetlamp", "Travel & Places"),
    ("gakuen", "がくえん", "ガクエン", "学園", "school academy / campus", "School & Work"),
    ("gakkyuu", "がっきゅう", "ガッキュウ", "学級", "school class / grade", "School & Work"),
    ("gekikou", "げきこう", "ゲキコウ", "激変", "abrupt drastic change", "Culture & Society"),
    ("gen'ya", "げんや", "ゲンヤ", "原野", "wilderness / open plain", "Nature & Weather"),
    ("ginkou", "ぎんこう", "ギンコウ", "銀行", "bank financial institution", "Shopping & Money"),
    ("ginsekai", "ぎんせかい", "ギンセカイ", "銀世界", "snow-covered landscape / silver world", "Nature & Weather"),
    ("gishin", "ぎしん", "ギシン", "疑心", "suspicion / doubt", "Emotions & Mind"),
    ("gogatsu", "ごがつ", "ゴガツ", "五月", "May", "Time & Calendar"),
    ("gosenfu", "ごせんふ", "ゴセンフ", "五線譜", "musical score staff", "Hobbies & Media"),
    ("gurando kyanion", "ぐらんどきゃにおん", "グランドキャニオン", "グランドキャニオン", "Grand Canyon", "Travel & Places"),
    # H
    ("habataki", "はばたき", "ハバタキ", "羽ばたき", "flapping of wings", "Nature & Animals"),
    ("hachigatsu", "はちがつ", "ハチガツ", "八月", "August", "Time & Calendar"),
    ("hakubutsukan", "はくぶつかん", "ハクブツカン", "博物館", "museum", "Travel & Places"),
    ("hanami", "はなみ", "ハナミ", "花見", "cherry blossom flower viewing", "Culture & Society"),
    ("haru", "はる", "ハル", "春", "spring season", "Time & Calendar"),
    ("harukaze", "はるかぜ", "ハルカゼ", "春風", "spring breeze", "Nature & Weather"),
    ("haruame", "はるさめ", "ハルサメ", "春雨", "gentle spring rain", "Nature & Weather"),
    ("higashi", "ひがし", "ヒガシ", "東", "east direction", "Travel & Places"),
    ("hikyou", "ひきょう", "ヒキョウ", "秘境", "unexplored region / hidden spot", "Travel & Places"),
    ("hinode", "ひので", "ヒノデ", "日の出", "sunrise / dawn", "Nature & Weather"),
    ("hinoiri", "ひのいり", "ヒノイリ", "日の入り", "sunset / dusk", "Nature & Weather"),
    ("hiru", "ひる", "ヒル", "昼", "noon / daytime", "Time & Calendar"),
    ("hiruma", "ひるま", "ヒルマ", "昼間", "daylight hours", "Time & Calendar"),
    ("hiruyasumi", "ひるやすみ", "ヒルヤスミ", "昼休み", "lunch break", "Daily Life"),
    ("hokuriku", "ほくりく", "ホクリク", "北陸", "Hokuriku region", "Travel & Places"),
    ("hokkaidou", "ほっかいどう", "ホッカイドウ", "北海道", "Hokkaido prefecture / island", "Travel & Places"),
    ("hoshizora", "ほしぞら", "ホシゾラ", "星空", "starry sky / starlit night", "Nature & Weather"),
    ("hoteru", "ほてる", "ホテル", "ホテル", "western hotel", "Travel & Places"),
    ("hyouga", "ひょうが", "ヒョウガ", "氷河", "glacier", "Nature & Weather"),
    ("hyouzan", "ひょうざん", "ヒョウザン", "氷山", "iceberg", "Nature & Weather"),
    # I
    ("ichigatsu", "いちがつ", "イチガツ", "一月", "January", "Time & Calendar"),
    ("inaka", "いなか", "イナカ", "田舎", "countryside / rural area", "Travel & Places"),
    ("inazuma", "いなずま", "イナズマ", "稲妻", "flash of lightning", "Nature & Weather"),
    ("iseki", "いせき", "イセキ", "遺跡", "historic ruins / archaeological site", "Culture & Society"),
    ("izumi", "いずみ", "イズミ", "泉", "freshwater spring / fountain", "Nature & Weather"),
    # J
    ("jinja", "じんじゃ", "ジンジャ", "神社", "Shinto shrine", "Culture & Society"),
    ("jishin", "じしん", "ジシン", "地震", "earthquake / tremor", "Nature & Weather"),
    ("juugatsu", "じゅうがつ", "ジュウガツ", "十月", "October", "Time & Calendar"),
    ("juuichigatsu", "じゅういちがつ", "ジュウイチガツ", "十一月", "November", "Time & Calendar"),
    ("juunigatsu", "じゅうにがつ", "ジュウニガツ", "十二月", "December", "Time & Calendar"),
    # K
    ("kaigan", "かいがん", "カイガン", "海岸", "seashore / ocean coastline", "Travel & Places"),
    ("kaisenkyou", "かいきょう", "カイキョウ", "海峡", "strait / channel", "Nature & Weather"),
    ("kaiun", "かいうん", "カイウン", "海運", "maritime shipping", "Travel & Places"),
    ("kakuekiteisha", "かくえきていしゃ", "カクエキテイシャ", "各駅停車", "local train stopping at every station", "Travel & Places"),
    ("kaminari", "かみなり", "カミナリ", "雷", "thunder and lightning", "Nature & Weather"),
    ("kanranha", "かんらんしゃ", "カンランシャ", "観覧車", "Ferris wheel", "Culture & Society"),
    ("kasen", "かせん", "カセン", "河川", "rivers and waterways", "Nature & Weather"),
    ("kaze", "かぜ", "カゼ", "風", "wind / breeze", "Nature & Weather"),
    ("kazan", "かざん", "カザン", "火山", "volcano", "Nature & Weather"),
    ("keikoku", "けいこく", "ケイコク", "渓谷", "canyon / valley gorge", "Nature & Weather"),
    ("keshiki", "けしき", "ケシキ", "景色", "scenery / landscape / view", "Travel & Places"),
    ("kiri", "きり", "キリ", "霧", "fog / mist", "Nature & Weather"),
    ("kisetsu", "きせつ", "キセツ", "季節", "season of the year", "Time & Calendar"),
    ("kita", "きた", "キタ", "北", "north direction", "Travel & Places"),
    ("kouen", "こうえん", "コウエン", "公園", "public park", "Travel & Places"),
    ("koujou", "こうじょう", "コウジョウ", "工場", "factory / manufacturing plant", "Travel & Places"),
    ("koukuu", "こうくう", "コウクウ", "航空", "aviation / airline", "Travel & Places"),
    ("kousaten", "こうさてん", "コウサテン", "交差点", "street intersection / crossroads", "Travel & Places"),
    ("koutsuu", "こうつう", "コウツウ", "交通", "traffic / transportation", "Travel & Places"),
    ("kouyou", "こうよう", "コウヨウ", "紅葉", "autumn red foliage / maple leaves", "Nature & Weather"),
    ("kuukou", "くうこう", "クウコウ", "空港", "airport", "Travel & Places"),
    ("kyuukou", "きゅうこう", "キュウコウ", "急行", "express train", "Travel & Places"),
    # M
    ("machi", "まち", "マチ", "町", "town / city block", "Travel & Places"),
    ("minami", "みなみ", "ミナミ", "南", "south direction", "Travel & Places"),
    ("minato", "みなと", "ミナト", "港", "harbor / seaport", "Travel & Places"),
    ("mizuumi", "みずうみ", "ミズウミ", "湖", "freshwater lake", "Nature & Weather"),
    ("moribito", "もり", "モリ", "森", "dense forest / woods", "Nature & Weather"),
    # N
    ("nagareboshi", "ながれぼし", "ナガレボシ", "流れ星", "shooting star / meteor", "Nature & Weather"),
    ("nami", "なみ", "ナミ", "波", "ocean wave / surf", "Nature & Weather"),
    ("natsu", "なつ", "ナツ", "夏", "summer season", "Time & Calendar"),
    ("natsuyasumi", "なつやすみ", "ナツヤスミ", "夏休み", "summer vacation", "Time & Calendar"),
    ("niji", "にじ", "ニジ", "虹", "rainbow", "Nature & Weather"),
    ("nishi", "にし", "ニシ", "西", "west direction", "Travel & Places"),
    # O
    ("onsen", "おんせん", "オンセン", "温泉", "hot spring bath / onsen spa", "Travel & Places"),
    ("ootoori", "おおどおり", "オオドオリ", "大通り", "main street / broad avenue", "Travel & Places"),
    # R
    ("ressha", "れっしゃ", "レッシャ", "列車", "train locomotive", "Travel & Places"),
    ("ryokan", "りょかん", "リョカン", "旅館", "traditional Japanese inn", "Travel & Places"),
    ("ryokou", "りょこう", "リョコウ", "旅行", "travel / trip / journey", "Travel & Places"),
    # S
    ("sakura", "さくら", "サクラ", "桜", "cherry blossom", "Nature & Weather"),
    ("sanpo", "さんぽ", "サンポ", "散歩", "leisurely stroll / walk", "Daily Life"),
    ("shinkansen", "しんかんせん", "シンカンセン", "新幹線", "bullet train / Shinkansen", "Travel & Places"),
    ("shimaguni", "しまぐに", "シマグニ", "島国", "island nation", "Travel & Places"),
    ("shiraito", "しらいと", "シライト", "白糸", "white thread-like waterfall cascades", "Nature & Weather"),
    ("sora", "そら", "ソラ", "空", "open sky", "Nature & Weather"),
    ("suizokukan", "すいぞくかん", "スイゾクカン", "水族館", "public aquarium", "Travel & Places"),
    # T
    ("taifu", "たいふう", "タイフウ", "台風", "typhoon / tropical cyclone", "Nature & Weather"),
    ("tairiku", "たいりく", "タイリク", "大陸", "continent / mainland", "Nature & Weather"),
    ("takibi", "たきび", "タキビ", "焚き火", "bonfire / campfire", "Nature & Weather"),
    ("taki", "たき", "タキ", "滝", "waterfall", "Nature & Weather"),
    ("tanima", "たにま", "タニマ", "谷間", "valley / mountain ravine", "Nature & Weather"),
    ("tenki", "てんき", "テンキ", "天気", "weather condition", "Nature & Weather"),
    ("tenkiyohou", "てんきよほう", "テンキヨホウ", "天気予報", "weather forecast report", "Nature & Weather"),
    ("tokkyuu", "とっきゅう", "トッキュウ", "特急", "limited express train", "Travel & Places"),
    ("torii", "とりい", "トリイ", "鳥居", "Shinto shrine gateway arch", "Culture & Society"),
    ("tsuki", "つき", "ツキ", "月", "the moon / month", "Nature & Weather"),
    # U
    ("umi", "うみ", "ウミ", "海", "ocean / sea", "Nature & Weather"),
    ("unzen", "うんぜん", "ウンゼン", "雲仙", "Unzen volcanic peak", "Travel & Places"),
    # Y
    ("yama", "やま", "ヤマ", "山", "mountain / peak", "Nature & Weather"),
    ("yamamichi", "やまみち", "ヤマミチ", "山道", "mountain trail / path", "Travel & Places"),
    ("yakei", "やけい", "ヤケイ", "夜景", "night view / city skyline at night", "Travel & Places"),
    ("yuki", "ゆき", "ユキ", "雪", "snow / snowfall", "Nature & Weather"),
    ("yukidaruma", "ゆきだるま", "ユキダルマ", "雪だるま", "snowman", "Culture & Society"),
    ("yukigeshiki", "ゆきげしき", "ユキゲシキ", "雪景色", "snowy winter landscape", "Nature & Weather"),
    # Z
    ("zenkou", "ぜんこう", "ゼンコウ", "前哨", "outpost / vanguard station", "Travel & Places")
]
