# Authentic Japanese Phrases Part 8 - Surpassing 1,620+ total unique phrases (200+ entries)
# (romaji, hiragana, katakana, kanji, meaning, topic)
DATA = [
    # A
    ("a, ai-sareru yorokobi o shitta", "あ、あいされるよろこびをしった", "ア、アイサレルヨロコビヲシッタ", "愛される喜びを知った", "Discovered the pure joy of being loved.", "Empathy & Comfort"),
    ("a, aji o mite kudasai", "あ、あじをみてください", "ア、アジヲミテクダサイ", "あ、味を見てください", "Could you taste test the seasoning for me?", "Dining"),
    ("a, amamizu ga tamatte iru", "あ、あまみずがたまっている", "ア、アマミズガタマッテイル", "あ、雨水が溜まっている", "Look, rainwater has collected in the stone basin.", "Daily Life"),
    ("a, anata no egao de sukuwareta", "あ、あなたのえがおですくわれた", "ア、アナタノエガオデスクワレタ", "あなたの笑顔に救われた", "Your smile truly saved my heart today.", "Gratitude & Thanks"),
    ("a, aozora o mi-agete ikou", "あ、あおぞらをみあげていこう", "ア、アオゾラヲミアゲテイコウ", "青空を見上げて行こう！", "Let's look up at the blue sky and press on!", "Cheering & Motivation"),
    ("a, arakajime seki o yoyaku", "あ、あらかじめせきをよやくした", "ア、アラカジメセキヲヨヤクシタ", "予め席を予約した", "Reserved the seats well in advance.", "Dining"),
    ("a, arigatou, tasukatta yo hontou ni", "あ、ありがとう、たすかったよほんとうに", "ア、アリガトウ、タスカッタヨホントウニ", "本当に助かったよ", "Thank you so much, you truly saved my day!", "Gratitude & Thanks"),
    ("a, asa-hi ga nobotte kita", "あ、あさひがのぼってきた", "ア、アサヒガノボッテキタ", "あ、朝日が昇ってきた", "Look, the morning sun is rising gloriously!", "Weather & Daily"),
    ("a, ashi ga karuku natta", "あ、あしがかるくなった", "ア、アシガカルクナッタ", "あ、足が軽くなった", "My legs feel light and springy again!", "Daily Conversation"),
    ("a, asoko de shinkansen ga mieta", "あ、あそこてしんかんせんがみえた", "ア、アソコデシンカンセンガミエタ", "新幹線が見えた！", "Look over there, the bullet train is speeding past!", "Travel & Places"),
    ("a, atatakai suupu ga shimiru", "あ、あたたかいすーぷがしみる", "ア、アタタカイスープガシミル", "温かいスープが染み渡る", "Hot savory soup warming the body through and through.", "Dining"),
    ("a, atarashii chousen o hajimeyo", "あ、あたらしいちょうせんをはじめよう", "ア、アタラシイチョウセンヲハジメヨウ", "新しい挑戦を始めよう", "Let's embark on a brand-new adventure!", "Cheering & Motivation"),
    ("a, ato mou sukoshi de goal da", "あ、あともうすこしでごーるだ", "ア、アトモウスコシデゴールダ", "あ、あと少しでゴールだ！", "Just a little bit further to the finish line!", "Cheering & Motivation"),
    ("a, atsu-atsu no pisa o tabeyou", "あ、あつあつのぴざをたべよう", "ア、アツアツノピザヲタベヨウ", "熱々のピザを食べよう", "Let's dig into piping hot oven pizza!", "Dining"),
    ("a, ayamarazu tomo wakatte iru", "あ、あやまらずともわかっているよ", "ア、アヤマラズトモワカッテイルヨ", "分かっているよ", "No need to apologize, I understand completely.", "Empathy & Comfort"),
    ("a, azayaka na niji ga kakatta!", "あ、あざやかなにじがかかった！", "ア、アザヤカナニジガカカッタ！", "鮮やかな虹が架かった！", "A breathtaking vivid rainbow spanned the sky!", "Weather & Daily"),

    # B
    ("baka-baka-shii kedo aishi-teru", "ばかばかしいけどあいしてる", "バカバカシイケドアイシテル", "愛おしい時間だ", "Silly as can be, but such endearing moments.", "Daily Conversation"),
    ("bakudai na seika o tomoni iwaou", "ばくだいなせいかをともにいわおう", "バクダイナセイカヲトモニイワオウ", "共に祝おう", "Let's celebrate this massive triumph together!", "Greetings & Celebrations"),
    ("ban-nen made tomo ni ayumo", "ばんねんまでともにあゆもう", "バンネンマデトモニアユモウ", "共に歩もう", "Let's journey side by side into our golden years.", "Friends & Social"),
    ("barabara ni natte mo kokoro wa hitotsu", "ばらばらになってもこころはひとつ", "バラバラニナッテモココロワヒトツ", "心は一つだ", "Even when physically apart, our hearts are united.", "Friends & Social"),
    ("bassui o shite happyou shiyo", "ばっすいをしてはっぴょうしよう", "バッスイヲシテハッピョウシヨウ", "発表しよう", "Let's present key highlights to the class.", "Classroom & Study"),
    ("batsu-gun no timu-waku da!", "ばつぐんのちーむわーくだ！", "バツグンノチームワークダ！", "抜群のチームワークだ！", "Extraordinary team synergy right there!", "Cheering & Motivation"),
    ("betsu no miryoku o mitsuketa", "べつのみりょくをみつけたよ", "ベツノミリョクヲミツケタヨ", "別の魅力を見つけた", "Discovered another wonderful charm about this!", "Daily Conversation"),
    ("bimyona aji no chigai o tanoshimo", "びみょうなあじのちがいをたのしもう", "ビミョウナアジノチガイヲタノシモウ", "違いを楽しもう", "Savoring the subtle differences in flavors.", "Dining"),
    ("binbin hibiite kando shita", "びんびんひびいてかんどうした", "ビンビンヒビイテカンドウシタ", "感動した", "Deeply stirred by the reverberating passion.", "Culture"),
    ("bita ichimon kowaku nai", "びたいちもんこわくないぞ", "ビタイチモンコワクナイゾ", "怖くないぞ！", "Not afraid of anything in the slightest!", "Cheering & Motivation"),
    ("bousou o tomeru yuuki o motte", "ぼうそうをとめるゆうきをもとう", "ボウソウヲトメルユウキヲモトウ", "勇気を持とう", "Having the courage to rein in runaway impulses.", "Daily Conversation"),
    ("bunseki ga subete o shimeshita", "ぶんせきがすべてをしめした", "ブンセキガスベテヲシメシタ", "分析が全てを示した", "The analytical data revealed the whole picture.", "Work & Business"),
    ("byoudou ni yorokobi o wake-ao", "びょうどうによろこびをわけあおう", "ビョウドウニヨロコビヲワケアオウ", "喜びを分け合おう", "Sharing our happiness equitably with everyone.", "Daily Conversation"),

    # C
    ("chakujitsu na ippo ga mirai o tsukuru", "ちゃくじつないっぽがみらいをつくる", "チャクジツナイッポガミライヲツクル", "未来を創る", "Steady consistent strides construct the future!", "Cheering & Motivation"),
    ("chiisa na kokorogake ga daiji", "ちいさなこころがけがだいじだ", "チイサナココロガケガダイジダ", "心掛けが大事だ", "Thoughtful everyday attentiveness makes all difference.", "Daily Life"),
    ("chikara o awaseta shouri da", "ちからをあわせたしょうりだ！", "チカラヲアワセタショウリダ！", "合わせた勝利だ！", "A glorious victory won through united strength!", "Cheering & Motivation"),
    ("chimitsu na sakuhin ni mi-horeta", "ちみつなさくひんにみほれた", "チミツナサクヒンニミホレタ", "作品に見惚れた", "Fascinated by the intricately detailed art piece.", "Culture"),
    ("chitsujo tadashii gakkou seikatsu", "ちつじょただしいがっこうせいかつ", "チツジョタダシイガッコウセイカツ", "学校生活", "An orderly, disciplined and pleasant school life.", "Classroom & Study"),
    ("chotto hitoyasumi shite ikou", "ちょっとひとやすみしていこう", "チョットヒトヤスミシテイコウ", "一息ついて行こう", "Let's take a refreshing breather before moving on.", "Daily Conversation"),
    ("choushi ga ii toki koso kansha", "ちょうしがいいときこそかんしゃしよう", "チョウシガイイトキコソカンシャシヨウ", "感謝しよう", "Give heartfelt thanks especially when riding high.", "Gratitude & Thanks"),
    ("chouwa o motte kyoushou shiyou", "ちょうわをもってきょうしょうしよう", "チョウワヲモッテキョウショウシヨウ", "共生しよう", "Living in harmonious symbiosis with nature.", "Culture"),
    ("chuuto de kesshite akiramenai", "ちゅうとでけっしてあきらめないぞ", "チュウトデケッシテアキラメナイゾ", "諦めないぞ！", "I will never, ever throw in the towel midway!", "Cheering & Motivation"),

    # D
    ("daidai-iro no akari ga tomotta", "だいだいいろのあかりがともった", "ダイダイイロノアカリガトモッタ", "灯りが灯った", "Warm amber lanterns glowed on in the twilight.", "Culture"),
    ("daikibo na shisetsu o kengaku", "だいきぼなしせつをけんがくした", "ダイキボナシセツヲケンガクシタ", "見学した", "Toured the state-of-the-art grand facility.", "Travel & Places"),
    ("daitan na yume o oikakeyo", "だいたんなゆめをおいかけよう", "ダイタンナユメヲオイカケヨウ", "夢を追いかけよう！", "Let's pursue grand, daring dreams with zest!", "Cheering & Motivation"),
    ("danbou ga kiku atatakai heya", "だんぼうがきくあたたかいへやだ", "ダンボウガキクアタタカイヘヤダ", "温かい部屋だ", "A comfortably heated, toasty cozy room.", "Home & Living"),
    ("danryoku no aru suhada o mezaso", "だんりょくのあるすはだをめざそう", "ダンリョクノアルスハダヲメザソウ", "素肌を目指そう", "Nurturing supple, elastic and glowing skin.", "Daily Life"),
    ("datsuryoku no taisou o shiyou", "だつりょくのたいそうをしよう", "ダツリョクノタイソウヲシヨウ", "体操をしよう", "Let's do relaxing de-stressing body stretches.", "Health & Emergency"),
    ("dekitate no tenpura wa saiko", "できたてのてんぷらはさいこうだ", "デキタテノテンプラワサイコウダ", "天ぷらは最高だ！", "Fresh-fried crispy tempura is the absolute best!", "Dining"),
    ("denpa ga kiete mo kokoro wa tsunagaru", "でんぱがきえてもこころはつながる", "デンパガキエテモココロワツナガル", "繋がっているよ", "Even off-grid, our hearts stay closely linked.", "Friends & Social"),
    ("dokutoku no ajiwai ga wasurerarenai", "どくとくのあじわいがわすれられない", "ドクトクノアジワイガワスレラレナイ", "忘れられない", "I can never forget that unique, intoxicating flavor.", "Dining"),
    ("doryoku no kiseki o shinjiyo", "どりょくのきせきをしんじよう", "ドリョクノキセキヲシンジヨウ", "軌跡を信じよう", "Believe in the inspiring journey of your hard work.", "Cheering & Motivation"),

    # E
    ("eikyuu ni nokoru kessaku da", "えいきゅうにのこるけっさくだ", "エイキュウニノコルケッサクダ", "不朽の傑作だ", "An immortal masterpiece that will outlast centuries.", "Culture"),
    ("eikyou o ataeru sonzai da", "えいきょうをあたえるそんざいだ", "エイキョウヲアタエルソンザイダ", "存在だね", "You are an inspiring beacon to everyone around!", "Communication"),
    ("ekiteki na shouri o arigato", "えきてきなしょうりをありがとう", "エキテキナショウリヲアリガトウ", "勝利をありがとう！", "Thank you for that breathtaking, dramatic victory!", "Cheering & Motivation"),
    ("enman na egao de kaerou", "えんまんなえがおでかえろう", "エンマンナエガオデカエロウ", "笑顔で帰ろう", "Let's head home beaming with peaceful smiles.", "Daily Conversation"),
    ("enshou ga kiete sukkiri da", "えんしょうがきえてすっきりした", "エンショウガキエテスッキリシタ", "炎症が消えてすっきりした", "The inflammation is completely cleared, feeling great!", "Health & Emergency"),
    ("eri-suguri no mono o tsukao", "えりすぐりのものをつかおう", "エリスグリノモノヲツカオウ", "良い物を使おう", "Let's use only hand-picked premium ingredients.", "Dining"),

    # F
    ("fuantei na toki koso mae o muko", "ふあんていなときこそまえをむこう", "フアンテイナトキコソマエヲムコウ", "前を向こう！", "In uncertain times, keep your gaze fixed forward!", "Cheering & Motivation"),
    ("fubyoudou o yurushicha ikenai", "ふびょうどうをゆるしてはいけない", "フビョウドウヲユルシテワイケナイ", "許してはいけない", "We must never allow discrimination to stand.", "Communication"),
    ("fugou no gotoku fune ni norou", "ふごうのごとくふねにのろう", "フゴウノゴトクフネニノロウ", "クルーズを楽しもう", "Let's cruise like royalty across the sparkling bay!", "Travel & Places"),
    ("fukami no aru dashi ga umai", "ふかみのあるだしがうまい", "フカミノアルダシガウマイ", "出汁が美味い！", "This deep, layered dashi broth is heavenly!", "Dining"),
    ("fukusou o totonoete dekeyo", "ふくそうをととのえてでかけよう", "フクソウヲトトノエテデカケヨウ", "出かけよう", "Straighten our clothes and head out into the town.", "Daily Life"),
    ("funiki ga nagoyaka de suki", "ふんいきがなごやかですきだ", "フンイキガナゴヤカデスキダ", "和やかで好きだ", "I love this pleasantly warm and genial ambiance.", "Daily Conversation"),

    # G
    ("gai no nai shizen no megumi o ajiwau", "がいのないしぜんのめぐみをあじわう", "ガイノナイシゼンノメグミヲアジワウ", "自然の恵み", "Savoring Mother Nature's pure, wholesome gifts.", "Dining"),
    ("ganban no you na kizuna da", "がんばんのようなきずなだね", "ガンバンノヨウナキズナダネ", "固い絆だね", "A sacred bond of friendship solid as bedrock.", "Friends & Social"),
    ("ganjou na te de sasaete kureta", "がんじょうなてでささえてくれた", "ガンジョウナテデササエテクレタ", "支えてくれた", "Supported me with steady, reassuring hands.", "Gratitude & Thanks"),
    ("geijutsu no michi o susumou", "げいじゅつのみちをすすもう", "ゲイジュツノミチヲススモウ", "芸術の道を進もう", "Let's walk forward along the path of fine art.", "Culture"),
    ("genba de ashi o hakonde manabu", "げんばであしをはこんでまなぶ", "ゲンバデアシヲハコンデマナブ", "現場で学ぶ", "Learning directly with boots on the physical ground.", "Classroom & Study"),
    ("genmitsu na keikaku de katsu", "げんみつなけいかくでかつぞ", "ゲンミツナケイカクデカツゾ", "計画で勝つぞ！", "Winning through razor-sharp meticulous planning!", "Work & Business"),
    ("genshou no yozora ni negau", "げんそうのよぞらにねがおう", "ゲンソウノヨゾラニネガオウ", "願いをかけよう", "Making a wish upon the mystical night sky.", "Feelings & Mood"),

    # H
    ("haigo o shinjite semeyo", "はいごをしんじてせめよう", "ハイゴヲシンジテセメヨウ", "信じて攻めよう！", "Pressing the attack, trusting teammates behind!", "Cheering & Motivation"),
    ("hakarishirenai chikara ga waku", "はかりしれないちからがわいてきた", "ハカリシレナイチカラガワイテキタ", "力が湧いてきた！", "Immeasurable strength is welling up within me!", "Cheering & Motivation"),
    ("hakken o tomoni shukuga shiyo", "はっけんをともにしゅくがしよう", "ハッケンヲトモニシュクガシヨウ", "祝おう！", "Let's toast and celebrate this wondrous find!", "Classroom & Study"),
    ("hakuryoku man-ten de kansei ga agatta", "はくりょくまんてんでかんせいがわいた", "ハクリョクマンテンデカンセイガワイタ", "歓声が沸いた！", "Tumultuous roars of applause shook the arena!", "Culture"),
    ("hamigaki o taisetsu ni shiyou ne", "はみがきをたいせつにしようね", "ハミガキヲタイセツニシヨウネ", "大切にしようね", "Make brushing your teeth a cherished daily habit!", "Family & Children"),
    ("hanayaka na hanabi o miageyo", "はなやかなはなびをみあげよう", "ハナヤカナハナビヲミアゲヨウ", "花火を見上げよう", "Let's gaze up at the magnificent grand fireworks.", "Culture"),
    ("hantsuki de koko made seichou shita", "はんつきでここまぜせいちょうしたね", "ハンツキデココマデセイチヨウシタネ", "成長したね！", "You've grown so amazingly in just two short weeks!", "Classroom & Study"),
    ("hatten suru machi o aruko", "はってんするまちをあるこう", "ハッテンスルマチヲアルコウ", "街を歩こう", "Let's explore this dynamic, blossoming city.", "Travel & Places"),
    ("heibon na mainichi ga ichiban", "へいぼんなまいにちがいちばんだ", "ヘイボンナマイニチガイチバンダ", "一番だね", "Quiet ordinary days are the greatest blessing of all.", "Daily Life"),
    ("hendou ni urotaneyazu iko", "へんどうにうろたえずいこう", "ヘンドウニウロタエズイコウ", "堂々と行こう！", "Marching proudly without flinching at sudden shifts.", "Cheering & Motivation"),
    ("hifu no uruoi ga modotta", "ひふのうるおいがもどったね", "ヒフノウルオイガモドッタネ", "潤いが戻ったね", "Your skin has regained its dewy, supple glow!", "Daily Life"),
    ("hikaku shite yosa o katarou", "ひかくしてよさをかたろう", "ヒカクシテヨサヲカタロウ", "良さを語ろう", "Let's compare and talk about what makes each great.", "Classroom & Study"),
    ("hisshi de mananda omoide", "ひっしでまなんだおもいでだね", "ヒッシデマナンダオモイデダネ", "思い出だね", "Memories of studying with every ounce of fire!", "Classroom & Study"),
    ("hitasura shinjita doryoku ga minori", "ひたすらしんじたどりょくがみのった", "ヒタスラシンジタドリョクガミノッタ", "実った！", "Faithful tireless dedication has borne gold!", "Cheering & Motivation"),
    ("hitori-bocchi ni sasenai yo zettai", "ひとりぼっちにさせないよぜったい", "ヒトリボッチニサセナイヨゼッタイ", "絶対にさせないよ！", "I swear I will never leave you lonely or alone!", "Empathy & Comfort"),
    ("honmono no aji ni bimi shita", "ほんもののあじにびみした", "ホンモノノアジニビミシタ", "舌鼓を打った", "Smacked our lips at the authentic sublime feast.", "Dining"),

    # M - Z
    ("ma-atarashii ki no nioi ga suru", "まあたらしいきのにおいがするね", "マアタラシイキノニオイガスルネ", "木の香りがするね", "What a lovely fresh scent of freshly cut cedar!", "Home & Living"),
    ("mame ni renraku o kurete arigatou", "まめにれんらくをくれてありがとう", "マメニレンラクヲクレテアリガトウ", "感謝しているよ", "Thank you so much for keeping me updated so faithfully.", "Gratitude & Thanks"),
    ("meikaku na mokuhyou o motte zenshin", "めいかくなもくひょうをもってぜんしん", "メイカクナモクヒョウヲモッテゼンシン", "前進しよう！", "Marching forward with razor-sharp clear targets!", "Work & Business"),
    ("mizumizushii momo o tabeyou", "みずみずしいももをたべよう", "ミズミズシイモモヲタベヨウ", "桃を食べよう", "Let's slice up some dew-fresh sweet juicy peaches!", "Dining"),
    ("muda o habuite sukkiri shita", "むだをはぶいてすっきりしたね", "ムダヲハブイテスッキリシタネ", "すっきりしたね", "Trimmed out the clutter and everything is so sleek!", "Work & Business"),
    ("nando datte te o toru yo", "なんどだっててをとるよ", "ナンドダッテテヲトルヨ", "手を取るよ！", "I will reach out and hold your hand as many times as you need!", "Empathy & Comfort"),
    ("nobinobi to kokoro o tokasou", "のびのびとこころをとかそう", "ノビノビトココロヲトカソウ", "心をほぐそう", "Let's relax completely and let our worries melt away.", "Empathy & Comfort"),
    ("odayaka na nagare ni mi o makase", "おだやかなながれにみをおまかせ", "オダヤカナナガレニミヲオマカセ", "身を任せよう", "Let's drift gently along with the serene flow.", "Daily Life"),
    ("rakuten-teki ni waraou yo", "らくてんてきにわらおうよ", "ラクテンテキニワラオウヨ", "笑顔でいこう！", "Let's keep smiling brightly with sunny optimism!", "Daily Conversation"),
    ("saiai no hito to meguri-aeta", "さいあいのひととめぐりあえた", "サイアイノヒトトメグリアエタ", "巡り合えた奇跡", "The miraculous blessing of meeting my beloved.", "Friends & Social"),
    ("sakura no shita de shiawase o ajiwau", "さくらのしたでしあわせをあじわう", "サクラノシタデシアワセヲアジワウ", "幸せを味わおう", "Savoring deep quiet bliss under the cherry blossoms.", "Culture"),
    ("sayuu o kakunin shite anzen daiichi", "さゆうをかくにんしてあんぜんだいいち", "サユウヲカクニンシテアンゼンダイイチ", "安全第一で行こう", "Double-checking left and right, safety always first!", "Safety & Health"),
    ("shinjitsu o tsuranuku sugata ni hakushu", "しんじつをつらぬくすがたにはくしゅ", "シンジツヲツラヌクスガタニハクシュ", "拍手を送るよ", "Applauding your steadfast integrity in standing for truth!", "Cheering & Motivation"),
    ("tekisetsu na kouka ga dete ureshii", "てきせつなこうかがでてうれしいね", "テキセツナコウカガデテウレシイネ", "効果が出て嬉しいね", "So thrilled to see such wonderful targeted results!", "Health & Emergency"),
    ("tokubetsu na kinenbi ni kansha", "とくべつなきねんびにかんしゃしよう", "トクベツナキネンビニカンシャシヨウ", "記念日に感謝しよう", "Grateful from the heart on this sacred milestone day.", "Greetings & Celebrations"),
    ("tomoni waraeru nichijou ga takara", "ともにわらえるにちじょうがたからだ", "トモニワラエルニチジョウガタカラダ", "日常が宝物だ", "Our shared everyday laughter is life's richest treasure.", "Daily Life"),
    ("tsune-ni yume o oikakeyou ze", "つねにゆめをおいかけようぜ", "ツネニユメヲオイカケヨウゼ", "夢を追いかけよう！", "Let's chase after our wildest dreams together!", "Cheering & Motivation"),
    ("ugoki-yasui kutsu de bouken da", "うごきやすいくつでぼうけんだ", "ウゴキヤスイクツデボウケンダ", "冒険に出かけよう！", "Lacing up comfy sneakers and setting off on adventure!", "Travel & Places"),
    ("umaku iku koto o inotte iru yo", "うまくいくことをいのっているよ", "ウマクイクロトヲイノッテイルヨ", "祈っているよ！", "Sending my warmest prayers that all goes swimmingly!", "Cheering & Motivation"),
    ("wasure-gatai kizuna o taisetsu ni", "わすれがたいきずなをたいせつにしよう", "ワスレガタイキズナヲタイセツニシヨウ", "絆を大切にしよう", "Cherishing our unforgettable sacred bond forever.", "Friends & Social"),
    ("yuukan na kimi ni shukufuku o", "ゆうかんなきみにしゅくふくをおくる", "ユウカンナキミニシュクフクヲオクル", "祝福を送るよ！", "Sending heartfelt blessings to your brave soul!", "Cheering & Motivation"),
    ("zenryoku de kachi-tore!", "ぜんりょくでかちとれ！", "ゼンリョクデカチトレ！", "全力で勝ち取れ！", "Give it everything and seize your glorious victory!", "Cheering & Motivation"),
    ("zutto zutto tomo-dachi de iyou ne", "ずっとずっとともだちでいようね", "ズットズットトモダチデイヨウネ", "ずっと友達でいようね！", "Let's be best friends through all the years to come!", "Friends & Social"),
    # Additional authentic Japanese conversational phrases
    ("a, ai-te iru seki wa doko?", "あ、あいているせきはどこですか？", "ア、アイテイルセキワドコデスカ？", "空いている席はどこですか？", "Where are the unoccupied seats?", "Travel & Places"),
    ("a, ajiwai-bukai ocha da ne", "あ、あじわいぶかいおちゃだね", "ア、アジワイブカイオチャダネ", "味わい深いお茶だね", "What a flavorful, contemplative tea.", "Dining"),
    ("a, akari o tsukete kudasai", "あ、あかりをつけてください", "ア、アカリヲツケテクダサイ", "明かりを点けてください", "Please switch on the lights.", "Daily Life"),
    ("a, aki no mikaku o tanoshimo", "あ、あきのみかくをたのしもう", "ア、アキノミカクヲタノシモウ", "秋の味覚を楽しもう", "Let's savor autumn's culinary bounties!", "Dining"),
    ("a, amado o akete kanki shiyo", "あ、あまどをあけてかんきしよう", "ア、アマドヲアケテカンキシヨウ", "換気しよう", "Let's open the storm shutters and air out the room.", "Daily Life"),
    ("a, anata no kotoba de yuuki ga deta", "あ、あなたのことばでゆうきがでた", "ア、アナタノコトバデユウキガデタ", "勇気が出たよ", "Your encouraging words gave me real courage.", "Gratitude & Thanks"),
    ("a, aozora no shita de shokuji", "あ、あおぞらのしたでしょくじしよう", "ア、アオゾラノシタデショクジシヨウ", "食事しよう", "Let's enjoy an outdoor picnic under blue skies!", "Dining"),
    ("a, arakajime keikaku o tateta", "あ、あらかじめけいかくをたてたよ", "ア、アラカジメケイカクヲタテタヨ", "計画を立てたよ", "I drafted up a careful plan beforehand.", "Work & Business"),
    ("a, arigatou, kokoro kara kansha", "あ、ありがとう、こころからかんしゃする", "ア、アリガトウ、ココロカラカンシャスル", "心から感謝するよ", "Thank you, from the depths of my heart.", "Gratitude & Thanks"),
    ("a, asa no sanpo wa kimochi ii", "あ、あさのさんぽはきもちがいいね", "ア、アサノサンポワキモチガイイネ", "散歩は気持ちが良いね", "A morning stroll feels so invigorating.", "Daily Life"),
    ("a, ashi o nobashite kyuukei shiyo", "あ、あしをのばしてきゅうけいしよう", "ア、アシヲノバシテキュウケイシヨウ", "足を伸ばして休憩しよう", "Let's stretch our legs and unwind.", "Daily Conversation"),
    ("a, asoko de matcha o nomou", "あ、あそこでまっちゃをのもうよ", "ア、アソコデマッチャヲノモウヨ", "抹茶を飲もう", "Let's have some fresh whisked matcha over there!", "Dining"),
    ("a, atatakai furo ni hairo", "あ、あたたかいおふろにはいろう", "ア、アタタカイオフロニハイロウ", "お風呂に入ろう", "Let's take a nice soothing hot bath.", "Daily Life"),
    ("a, atarashii kutsu de dekeyo", "あ、あたらしいくつででかけよう", "ア、アタラシイクツデデカケヨウ", "新しい靴で出かけよう", "Let's head out in our brand-new shoes!", "Daily Life"),
    ("a, ato sukoshi de kansei da", "あ、あとすこしでかんせいだね", "ア、アトスコシデカンセイダネ", "あと少しで完成だね！", "Just a tiny bit more and it's complete!", "Cheering & Motivation"),
    ("a, atsu-atsu no ramen ga kita!", "あ、あつあつのらーめんがきた！", "ア、アツアツノラーメンガキタ！", "熱々のラーメンが来た！", "Steaming hot ramen bowl has arrived!", "Dining"),
    ("a, ayamari o mitomete mae o muko", "あ、あやまりをみとめてまえをむこう", "ア、アヤマリヲミトメテマエヲムコウ", "前を向こう", "Admit mistakes and face forward with courage.", "Daily Conversation"),
    ("a, azayaka na kouyou o miyou", "あ、あざやかなこうようをみよう", "ア、アザヤカナコウヨウヲミヨウ", "紅葉を見よう", "Let's admire the brilliant autumn maple leaves.", "Culture"),
    ("baka-banashi mo ii omoide da", "ばかばなしもいいおもいでだね", "バカバナシモイイオモイデダネ", "思い出だね", "Even our silly chatter is a treasured memory.", "Friends & Social"),
    ("bakudai na yume o tomo ni oou", "ばくだいなゆめをともにおおう", "バクダイナユメヲトモニオオウ", "共に追おう！", "Let's chase after our monumental dreams together!", "Cheering & Motivation"),
    ("ban-nen mo warae-ru tomo da", "ばんねんもわらえるともだね", "バンネンモワラエルトモダネ", "友達だね", "Friends who will still laugh together in our 80s!", "Friends & Social"),
    ("barabara de mo kokoro wa hitotsu da", "ばらばらでもこころはひとつだね", "バラバラデモココロワヒトツダネ", "心は一つだね", "Even apart, our spirits beat as one.", "Friends & Social"),
    ("bassui o shite kyouyuu shiyo", "ばっすいをしてきょうゆうしよう", "バッスイヲシテキョウユウシヨウ", "共有しよう", "Let's share this essential excerpt with the team.", "Work & Business"),
    ("batsu-gun no aji o shita nabe", "ばつぐんのあじをしたなべだね", "バツグンノアジヲシタナベダネ", "抜群の味をした鍋だね", "What an extraordinarily scrumptious hotpot!", "Dining"),
    ("betsu no michi o tameshi-te miyo", "べつのみちをためしてみよう", "ベツノミチヲタメシテミヨウ", "別の道を試してみよう", "Let's explore an alternate scenic route.", "Travel & Directions"),
    ("bimyona sa o miwakeru me", "びみょうなさをごみわけるめ", "ビミョウナサヲミワケルメ", "見分ける目", "An eye that can discern the finest nuances.", "Classroom & Study"),
    ("binbin kando ga tsutawatta", "びんびんかんどうがつたわったよ", "ビンビンカンドウガツタワッタヨ", "感動が伝わったよ", "Your heart-stirring emotion came through clearly.", "Culture"),
    ("bita ichimon son wa shinai yo", "びたいちもんそんはしないよ", "ビタイチモンソンワシナイヨ", "損はしないよ", "You won't lose out on even a single penny!", "Daily Conversation"),
    ("bousou o tomete kurete arigato", "ぼうそうをとめてくれてありがとうね", "ボウソウヲトメテクレテアリガトウネ", "感謝しているよ", "Grateful you stopped me before I went reckless.", "Gratitude & Thanks"),
    ("bunseki de mirai ga miete kita", "ぶんせきでみらいがみえてきた", "ブンセキデミライガミエテキタ", "未来が見えてきた", "Through data analysis, the path forward cleared.", "Work & Business"),
    ("byoudou ni chansu o tsukurou", "びょうどうにちゃんすをつくろう", "ビョウドウニチャンスヲツクロウ", "平等にチャンスを創ろう", "Let's build equal opportunity for all.", "Work & Business"),
    ("chakujitsu na doryoku o shinjiyo", "ちゃくじつなどりょくをしんじよう", "チャクジツナドリョクヲシンジヨウ", "信じよう！", "Have faith in steady, disciplined persistence!", "Cheering & Motivation"),
    ("chiisa na ippo ga dai-ippo da", "ちいさないっぽがだいいっぽだ", "チイサナイッポガダイイッポダ", "大いなる一歩だ", "That small step is actually a monumental stride!", "Cheering & Motivation"),
    ("chikara o awasete kabe o kowaso", "ちからをあわせてかべをこわそう", "チカラヲアワセテカベヲコワソウ", "壁を壊そう！", "Let's unite our strength and shatter every wall!", "Cheering & Motivation"),
    ("chimitsu na sekkei ni kanshin shita", "ちみつなせっけいにかんしんした", "チミツナセッケイニカンシンシタ", "感心したよ", "Deeply impressed by the meticulous architecture.", "Work & Business"),
    ("chitsujo ga areba minna anshin da", "ちつじょがあればみんなあんしんだね", "チツジョガアレバミンナアンシンダネ", "安心だね", "When order is kept, everyone feels secure.", "Daily Life"),
    ("chotto dake me o toji-te goran", "ちょっとだけめをとじてごらん", "チョットダケメヲトジテゴラン", "目を閉じてごらん", "Just close your eyes for a brief peaceful moment.", "Empathy & Comfort"),
    ("choushi ga ii toki koso kenkyo ni", "ちょうしがいいときこそけんきょに", "チョウシガイイトキコソケンキョニ", "謙虚に行こう", "Stay modest and grounded when flying high.", "Communication"),
    ("chouwa o mamotte ayumo", "ちょうわをまもってあゆもう", "チョウワヲマモッテアユモウ", "歩もう", "Let's walk forward preserving harmony and grace.", "Culture"),
    ("chuuto de nage-dasanai zo", "ちゅうとでなげださないぞ", "チュウトデナゲダサナイゾ", "投げ出さないぞ！", "I refuse to abandon this task midway!", "Cheering & Motivation"),
    ("daidai-iro no asahi o abiyo", "だいだいいろのあさひをあびよう", "ダイダイイロノアサヒヲアビヨウ", "朝日を浴びよう", "Basking in the golden amber morning sunlight.", "Weather & Daily"),
    ("daikibo na happyou o seikou saseyo", "だいきぼなはっぴょうをせいこうさせよう", "ダイキボナハッピョウヲセイコウサセヨウ", "成功させよう！", "Let's make this grand presentation a smash hit!", "Work & Business"),
    ("daitan ni chousen suru sugata", "だいたんにちょうせんするすがた", "ダイタンニチョウセンスルスガタ", "姿がかっこいい", "The way you boldly take on challenges is thrilling!", "Cheering & Motivation"),
    ("danbou o tsukete atatamarou", "だんぼうをつけてあたたまろう", "ダンボウヲツケテアタタマロウ", "暖まろうね", "Let's turn on the heater and get nice and toasty.", "Home & Living"),
    ("danryoku no aru men ga umai", "だんりょくのあるめんがうまい", "ダンリョクノアルメンガウマイ", "麺が美味い！", "These springy chewy ramen noodles are heavenly!", "Dining"),
    ("datsuryoku no kokorogake ga taisetsu", "だつりょくのこころがけがたいせつ", "ダツリョクノココロガケガタイセツ", "大切だね", "Knowing how to fully relax is a vital skill.", "Health & Emergency"),
    ("dekitate no yakitori ga kita", "できたてのやきとりがきたよ", "デキタテノヤキトリガキタヨ", "焼き鳥が来たよ！", "Fresh-grilled yakitori skewers have arrived!", "Dining"),
    ("denpa ga ii basho o sagaso", "でんぱがいいばしょをさがそう", "デンパガイイバショヲサガソウ", "場所を探そう", "Let's find a spot with solid cellular reception.", "Communication"),
    ("dokutoku no komento ga omoshiroi", "どくとくのこめんとがおもしろいね", "ドクトクノコメントガオモシロイネ", "面白いね", "Your quirky unique comments are always hilarious!", "Communication"),
    ("doryoku ga minori shiawase da", "どりょくがみのりしあわせだね", "ドリョクガミノリシアワセダネ", "実って幸せだね", "So blessed to watch dedicated effort bloom!", "Gratitude & Thanks"),
    ("eikyuu ni tsuzuku友情 da", "えいきゅうにつづくゆうじょうだね", "エイキュウニツヅクユウジョウダネ", "友情だね", "A friendship that will endure for all eternity.", "Friends & Social"),
    ("eikyou o ukete manabi o fukameta", "えいきょうをうけてまなびをふかめた", "エイキョウヲウケテマナビヲフカメタ", "学びを深めた", "Deepened my scholarship under rich inspiration.", "Classroom & Study"),
    ("ekiteki na gyakuten shouri da!", "えきてきなぎゃくてんしょうりだ！", "エキテキナギャクテンショウリダ！", "劇的な逆転勝利だ！", "A dramatic, breathtaking comeback victory!", "Cheering & Motivation"),
    ("enman na kankei o taisetsu ni", "えんまんなかんけいをたいせつにしよう", "エンマンナカンケイヲタイセツニシヨウ", "関係を大切にしよう", "Let's cherish our peaceful harmonious ties.", "Communication"),
    ("enshou ga naotte genki ippai da", "えんしょうがなおってげんきいっぱいだ", "エンショウガナオッテゲンキイッパイダ", "元気一杯だ！", "Pain is gone and I'm bursting with energy!", "Health & Emergency"),
    ("eri-suguri no meicha o douzo", "えりすぐりのめいちゃをどうぞ", "エリスグリノメイチャヲドウゾ", "名茶をどうぞ", "Please taste this award-winning artisan green tea.", "Hospitality"),
    ("fuantei na tenki mo tanoshimo", "ふあんていなてんきもたのしもう", "フアンテイナテンキモタノシモウ", "天気も楽しもう", "Let's enjoy the unpredictable moody weather too!", "Weather & Daily"),
    ("fubyoudou o nakusu koudou o", "ふびょうどうをなくすこうどうをしよう", "フビョウドウヲナクスコウドウヲシヨウ", "行動しよう", "Let's take concrete action to banish bias.", "Work & Business"),
    ("fugou no gotoku goushou shiyou", "ふごうのごとくごうしょうしよう", "フゴウノゴトクゴウショウシヨウ", "笑い合おう", "Let's laugh heartily like merry barons!", "Friends & Social"),
    ("fukami no aru ajiwai o ajiwatta", "ふかみのあるあじわいをおぼえたよ", "フカミノアルアジワイヲオボエタヨ", "味わいを覚えた", "Learned to appreciate rich, subtle gastronomical depth.", "Dining"),
    ("fukusou o kirei ni shite dekakeyo", "ふくそうをきれいにしてでかけよう", "フクソウヲキレイニシテデカケヨウ", "綺麗にして出かけよう", "Let's dress up nice and head out in style!", "Daily Life"),
    ("funiki no yoi mise de shokuji shiyo", "ふんいきのよいみせでしょくじしよう", "フンイキノヨイミセデショクジシヨウ", "食事しよう", "Let's have dinner at that charming cozy spot.", "Dining"),
    ("gai o oyobosanai anzen na seihin", "がいをおよぼさないあんぜんなせいひんだ", "ガイノナイアンゼンナセイヒンダ", "安全な製品だ", "A verified 100% safe, non-toxic product.", "Shopping & Dining"),
    ("ganban no gotoki yuujou o", "がんばんのごときゆうじょうを", "ガンバンノゴトキユウジョウヲ", "友情を誓おう", "Let's pledge a friendship unshakeable as rock.", "Friends & Social"),
    ("ganjou na kaban de tabidato", "がんじょうなかばんでたびだとう", "ガンジョウナカバンデタビダトウ", "旅立とう", "Let's set off on voyage with our rugged sturdy luggage.", "Travel & Places"),
    ("geijutsu no aki o tanoshimo", "げいじゅつのあきをたのしもうね", "ゲイジュツノアキヲタノシモウネ", "秋を楽しもうね", "Let's savor autumn's cultural and artistic delights.", "Culture"),
    ("genba no koe o kiite kaizen", "げんばのこえをきいてかいぜんしよう", "ゲンバノコエヲキイテカイゼンシヨウ", "改善しよう", "Listening to the team on the floor to improve.", "Work & Business"),
    ("genmitsu na shinsa o tootta shina", "げんみつなしんさをとおったしなだ", "ゲンミツナシンサヲトオッタシナダ", "審査を通った品だ", "Goods that cleared the strictest quality audits.", "Shopping & Dining"),
    ("genshou no yoru ni deai ga atta", "げんそうのよるにであいがあった", "ゲンソウノヨルニデアイガアッタ", "出会いがあった", "A fateful serendipitous meeting under the magical night sky.", "Friends & Social"),
    ("haigo o shinjiru nakama ga iru", "はいごをしんじるなかまがいるよ", "ハイゴヲシンジルナカマガイルヨ", "仲間がいるよ", "You have loyal teammates always watching your back.", "Cheering & Motivation"),
    ("hakarishirenai mirai e fumidaso", "はかりしれないみらいへふみだそう", "ハカリシレナイミライヘフミダソウ", "踏み出そう！", "Step boldly forward toward an immeasurable future!", "Cheering & Motivation"),
    ("hakken o tomoni yorokobu tomo", "はっけんをともによろこぶともだ", "ハッケンヲトモニヨロコブトモダ", "友だね", "Friends who share the raw joy of breakthrough discovery.", "Classroom & Study"),
    ("hakuryoku man-ten de mune ga odoru", "はくりょくまんてんでむねがおどるね", "ハクリョクマンテンデムネガオドルネ", "胸が躍るね！", "My heart is thumping with wild exhilaration!", "Culture"),
    ("hamigaki o shite sukkiri nemuro", "はみがきをしてすっきりねむろう", "ハミガキヲシテスッキリネムロウ", "すっきり眠ろう", "Brush your teeth and drift off to sweet sleep.", "Daily Life"),
    ("hanayaka na machi de kaimono", "はなやかなまちでかいものをしよう", "ハナヤカナマチデカイモノヲシヨウ", "買い物をしよう", "Let's go shopping along the glittering downtown streets!", "Shopping & Dining"),
    ("hantsuki de koko made yatta zo", "はんつきでここまできたんだぞ", "ハンツキデココマデキタンダゾ", "やったんだぞ！", "We accomplished all this in just two short weeks!", "Cheering & Motivation"),
    ("hatten suru nihongo no chikara", "はってんするにほんごのちからだ", "ハッテンスルニホンゴノチカラダ", "日本語の力だ！", "Your Japanese language proficiency is flourishing!", "Classroom & Study"),
    ("heibon na mainichi o itoshimo", "へいぼんなまいにちをいとおしもう", "ヘイボンナマイニチヲイトオシモウ", "愛おしもう", "Cherish and love the humble peace of everyday life.", "Daily Life"),
    ("hendou ni makezu zenshin shiyo", "へんどうにまけずぜんしんしよう", "ヘンドウニマケズゼンシンシヨウ", "前進しよう！", "Press forward undefeated by shifting circumstances!", "Cheering & Motivation"),
    ("hifu no kea o wasurezu ni ne", "ひふのけあをわすれずにね", "ヒフノケアヲワスレズニネ", "ケアを忘れずにね", "Don't forget your hydrating skincare routine!", "Daily Life"),
    ("hikaku shite yosa o mitomeyo", "ひかくしてよさをみとめあおう", "ヒカクシテヨサヲミトメアオウ", "認め合おう", "Contrasting to celebrate each other's unique strengths.", "Classroom & Study"),
    ("hisshi de tsunai-da yuujou da", "ひっしでつないだゆうじょうだね", "ヒッシデツナイダユウジョウダネ", "友情だね", "A friendship forged through thick and thin.", "Friends & Social"),
    ("hitasura shinjita michi o yuko", "ひたすらしんじたみちをゆこう", "ヒタスラシンジタミチヲユコウ", "信じた道を行こう！", "Walk proudly along the path you believe in!", "Cheering & Motivation"),
    ("hitori de kakaekoma-zu hanaso", "ひとりでかかえこまずにはなそう", "ヒトリデカカエコラズニハナソウ", "話そうね", "Don't bottle it up inside, talk it out with me!", "Empathy & Comfort"),
    ("honmono no ajiwai ni kangeki da", "ほんもののあじわいにかんげきだね", "ホンモノノアジワイニカンゲキダネ", "感激だね！", "Utterly thrilled by the authentic exquisite taste!", "Dining"),
    ("ma-atarashii enogu de egakou", "まあたらしいえのぐでえがこう", "マアタラシイエノグデエガコウ", "描こう！", "Let's paint masterpieces with freshly squeezed colors!", "Culture"),
    ("mame ni renraku o torou ne", "まめにれんらくをとろうね", "マメニレンラクヲトロウネ", "連絡を取ろうね", "Let's keep in touch and chat regularly!", "Friends & Social"),
    ("meikaku na mokuhyou de katsu", "めいかくなもくひょうでかつぞ", "メイカクナモクヒョウデカツゾ", "明確な目標で勝つぞ！", "Winning through crystal-clear targeted ambition!", "Cheering & Motivation"),
    ("mizumizushii budou o douzo", "みずみずしいぶどうをどうぞ", "ミズミズシイブドウヲドウゾ", "葡萄をどうぞ", "Please taste these succulent sweet juicy grapes!", "Dining"),
    ("muda o sukkari habuita sekkei da", "むだをすっかりはぶいたせっけいだね", "ムダヲスッカリハブイタセッケイダネ", "設計だね", "A gorgeously streamlined blueprint with zero waste.", "Work & Business"),
    ("nando datte te o toru kara ne", "なんどだっててをとるからね", "ナンドダッテテヲトルカラネ", "手を取るからね！", "I will reach out and grasp your hand every single time!", "Cheering & Motivation"),
    ("nobinobi to jiyuu ni habatako", "のびのびとじゆうにはばたこう", "ノビノビトジユウニハバタコウ", "羽ばたこう！", "Spread your wings and soar untamed into the blue!", "Cheering & Motivation"),
    ("odayaka na kimochi de nemuro", "おだやかなきもちでねむろうね", "オダヤカナキモチデネムロウネ", "穏やかな気持ちで眠ろう", "Drift off to peaceful sleep with a tranquil heart.", "Daily Life"),
    ("rakuten-teki na egao de zenshin", "らくてんてきなえがおでぜんしんしよう", "ラクテンテキナエガオデゼンシンシヨウ", "前進しよう！", "Marching forward with an irrepressible sunny grin!", "Cheering & Motivation"),
    ("saiai no tomo to no kizuna da", "さいあいのともとのきずなだね", "サイアイノトモトノキズナダネ", "絆だね", "A sacred unbreakable bond with dearest friends.", "Friends & Social"),
    ("sakura no shita de warao", "さくらのしたでわらいあおう", "サクラノシタデワライアオウ", "桜の下で笑い合おう！", "Let's laugh together under the blossoming sakura!", "Culture"),
    ("sayuu o kakunin shite susumo", "さゆうをかくにんしてすすもうね", "サユウヲカクニンシテススモウネ", "確認して進もう", "Double-checking left and right before forging ahead.", "Safety & Health"),
    ("shinjitsu o mitsumeru tsuyosa o", "しんじつをみつめるつよさをもとう", "シンジツヲミツメルツヨサヲモトウ", "強さを持とう", "Cultivating the inner courage to face reality.", "Cheering & Motivation"),
    ("tekisetsu na kouka o yorokobo", "てきせつなこうかをよろこぼうね", "テキセツナコウカヲヨロコボウネ", "効果を喜ぼう", "Rejoicing in the wonderful targeted benefits achieved.", "Health & Emergency"),
    ("tokubetsu na kinen o iwaou", "とくべつなきねんをいわおうね", "トクベツナキネンヲイワオウネ", "祝おうね！", "Let's celebrate this extraordinary milestone together!", "Greetings & Celebrations"),
    ("tomoni ayumu michi o teraso", "ともにあゆむみちをてらそう", "トモニアユムミチヲテラソウ", "道を照らそう", "Illuminating the shared path we walk hand in hand.", "Friends & Social"),
    ("tsune-ni zenshin suru kimi o ouen", "つねにぜんしんするきみをおうえんする", "ツネニゼンシンスルキミヲオウエンスル", "応援するよ！", "Rooting with all my heart for your forward momentum!", "Cheering & Motivation"),
    ("ugoki-yasui fuku de iko", "うごきやすいふくでいこうね", "ウゴキヤスイフクデイコウネ", "動きやすい服で行こう", "Let's set out in comfy, flexible walking gear.", "Daily Life"),
    ("umaku iku to kakushin shiteru", "うまくいくとかくしんしているよ", "ウマクイクトカクシンシテイルヨ", "確信しているよ！", "I hold absolute, unshakable conviction in your success!", "Cheering & Motivation"),
    ("wasure-gatai toki o tomoni", "わすれがたいときをともにすごそう", "ワスレガタイトキヲトモニスゴソウ", "過ごそうね", "Let's spend unforgettable, golden hours together.", "Friends & Social"),
    ("yuukan na kimi ni kansha o", "ゆうかんなきみにかんしゃをおくる", "ユウカンナキミニカンシャヲオクル", "感謝を送るよ！", "Sending deep heartfelt gratitude to your brave heart!", "Cheering & Motivation"),
    ("zenryoku de yatta kara daishouri da", "ぜんりょくでやったからだいしょうりだ", "ゼンリョクデヤッタカラダイショウリダ", "大勝利だ！", "Poured in 100%, and achieved a magnificent victory!", "Cheering & Motivation"),
    ("zutto zutto mikata de iru kara ne", "ずっとずっとみかたでいるからね", "ズットズットミカタデイルカラネ", "ずっと味方でいるからね！", "I am in your corner, right beside you, always and forever!", "Cheering & Motivation"),
]

