# Authentic Japanese Daily Conversation Phrases
# (romaji, hiragana, katakana, kanji, meaning, topic)
DATA = [
    # A
    ("a, bikkuri shita!", "あ、びっくりした！", "ア、ビックリシタ！", "あ、驚いた！", "Oh, you startled me!", "Daily Conversation"),
    ("a, choudo yokatta desu", "あ、ちょうどよかったです", "ア、チョウドヨカッタデス", "あ、丁度良かったです", "Ah, that is just perfect timing!", "Daily Conversation"),
    ("a, hontou da!", "あ、ほんとうだ！", "ア、ホントウダ！", "あ、本当だ！", "Oh, you're right! / Wow, truly!", "Daily Conversation"),
    ("a, ii tenki desu ne", "あ、いいてんきですね", "ア、イイテンキデスネ", "あ、良い天気ですね", "Ah, beautiful weather today, isn't it?", "Daily Conversation"),
    ("a, ki o tsukete kudasai", "あ、きをつけてください", "ア、キヲツケテクダサイ", "あ、気をつけてください", "Oh, please take care! / Watch out!", "Daily Conversation"),
    ("a, kore oishii desu yo", "あ、これおいしいですよ", "ア、コレオイシイデスヨ", "あ、これ美味しいですよ", "Oh, this is really tasty, you know!", "Daily Conversation"),
    ("a, ma ni aimashita", "あ、まにあいました", "ア、マニアイマシタ", "あ、間に合いました", "Phew, made it just in time!", "Daily Conversation"),
    ("a, naruhodo sou iu koto desu ka", "あ、なるほどそういうことですか", "ア、ナルホドソウイウコトデスカ", "あ、成程そういう事ですか", "Oh, I see, so that's how it is!", "Daily Conversation"),
    ("a, omatase shimashita", "あ、おまたせしました", "ア、オマタセシマシタ", "あ、お待たせしました", "Ah, so sorry to have kept you waiting!", "Daily Conversation"),
    ("a, sasuga desu ne!", "あ、さすがですね！", "ア、サスガデスネ！", "あ、流石ですね！", "Ah, just as impressive as expected!", "Daily Conversation"),
    ("a, sou iu koto deshita ka", "あ、そういうことでしたか", "ア、ソウイウコトデシタカ", "あ、そういう事でしたか", "Oh, so that was the explanation!", "Daily Conversation"),
    ("a, sumimasen, mou ichido", "あ、すみません、もういちど", "ア、スミマセン、モウイチド", "あ、すみません、もう一度", "Ah excuse me, one more time please?", "Daily Conversation"),
    ("a, wasurete shimatta", "あ、わすれてしまった", "ア、ワスレテシマッタ", "あ、忘れてしまった", "Ah, I completely clean forgot!", "Daily Conversation"),
    ("a, yokatta desu", "あ、よかったです", "ア、ヨカッタデス", "あ、良かったです", "Oh, what a huge relief!", "Daily Conversation"),
    ("aenai toki mo genki de ne", "あえないときもげんきでね", "アエナイトキモゲンキデネ", "会えない時も元気でね", "Stay healthy and cheerful while we're apart!", "Daily Conversation"),
    ("ashita mata hanashimashou", "あしたまたはなしましょう", "アシタマタハナシマショウ", "明日また話しましょう", "Let's talk more tomorrow!", "Daily Conversation"),
    ("ashita no yotei wa dou desu ka", "あしたのよていはどうですか", "アシタノヨテイワドウデスカ", "明日の予定はどうですか", "How does tomorrow's schedule look?", "Daily Conversation"),
    ("ano, chotto ii desu ka", "あの、ちょっといいですか", "アノ、チョットイイデスカ", "あの、一寸いいですか", "Um, do you have a quick second?", "Daily Conversation"),
    ("ano hito wa dare desu ka", "あのひとはだれですか", "アノヒトワダレデスカ", "あの人は誰ですか", "Who is that person over there?", "Daily Conversation"),
    ("ano mise, ninki rashii yo", "あのみせ、にんきらしいよ", "アノミセ、ニンキラシイヨ", "あの店、人気らしいよ", "Word is that shop is super popular!", "Daily Conversation"),
    ("anzen daiichi de ikimashou", "あんぜんだいいちでいきましょう", "アンゼンダライイチデイキマショウ", "安全第一で行きましょう", "Let's proceed safety first!", "Daily Conversation"),
    ("apparen na deki-bae da ne", "あっぱれなできばえだね", "アッパレナデキバエダネ", "天晴れな出来栄えだね", "Splendid craftsmanship right there!", "Daily Conversation"),
    ("arigatou, tasukatta yo", "ありがとう、たすかったよ", "アリガトウ、タスカッタヨ", "ありがとう、助かったよ", "Thanks a bunch, you really saved me!", "Gratitude & Thanks"),
    ("arittake no genki o dashite", "ありったけのげんきをだして", "アリッタケノゲンキヲダシテ", "ありったけの元気を出して", "Muster every drop of energy you've got!", "Cheering & Motivation"),
    ("asa gohan wa tabemashita ka", "あさごはんわたべましたか", "アサゴハンワタベマシタカ", "朝ご飯は食べましたか", "Did you have breakfast this morning?", "Daily Conversation"),
    ("asa hayaku kara gokurousama", "あさはやくからごくろうさま", "アサハヤクカラゴクロウサマ", "朝早くからご苦労様", "Appreciate your hard work so early!", "Greetings"),
    ("ase o kaite sukkiri shita", "あせをかいてすっきりした", "アセヲカイテスッキリシタ", "汗をかいてすっきりした", "Worked up a good sweat, feeling refreshed!", "Daily Conversation"),
    ("atatakaku shite nete ne", "あたたかくしてねてね", "アタタカクシテネテネ", "暖かくして寝てね", "Keep warm and sleep tight!", "Empathy & Comfort"),
    ("atarashii koto ni chousen shiyou", "あたらしいことにちょうせんしよう", "アタラシイコトニチョウセンシヨウ", "新しい事に挑戦しよう", "Let's take on fresh challenges!", "Cheering & Motivation"),
    ("atsui kara ki o tsukete ne", "あついからきをつけてね", "アツイカラキヲツケテネ", "熱いから気をつけてね", "It's piping hot, so be careful!", "Daily Conversation"),
    ("ayamaru hitsuyou wa nai yo", "あやまるひつようはないよ", "アヤマロヒツヨウワナイヨ", "謝る必要は無いよ", "No need to apologize at all, really!", "Empathy & Comfort"),

    # B
    ("baka na koto iwanaide", "ばかなこといわないで", "バカナコトイワナイデ", "馬鹿なこと言わないで", "Don't talk nonsense! / Come on!", "Daily Conversation"),
    ("barabara de ikimashou ka", "ばらばらでいきましょうか", "バラバラデイキマショウカ", "別々に行きましょうか", "Shall we head over separately?", "Daily Conversation"),
    ("batsu-gun ni omoshiroi yo", "ばつぐんにおもしろいよ", "バツグンニオモシロイヨ", "抜群に面白いよ", "It is extraordinarily hilarious and fun!", "Daily Conversation"),
    ("benkyou wa junchou desu ka", "べんきょうはじゅんちょうですか", "ベンキョウワジュンチョウデスカ", "勉強は順調ですか", "Are your Japanese studies going well?", "Classroom & Study"),
    ("betsu ni kinishite nai yo", "べつにきにしてないよ", "ベツニキニシテナイヨ", "別に気にしてないよ", "I don't mind at all, don't worry!", "Daily Conversation"),
    ("bikkuri shite tobi-okita", "びっくりしてとびおきた", "ビックリシテトビオキタ", "驚いて飛び起きた", "Leaped out of bed in surprise!", "Daily Conversation"),
    ("boku mo sou omoimasu", "ぼくもそうおもいます", "ボクモソウオモイマス", "僕もそう思います", "I feel the exact same way!", "Daily Conversation"),
    ("bonyari shite te kikoenakatta", "ぼんやりしててきこえなかった", "ボンヤリシテテキコエナカッタ", "ぼんやりしてて聞こえなかった", "Was daydreaming and didn't catch that!", "Daily Conversation"),
    ("bura-bura sanpo shiyou", "ぶらぶらさんぽしよう", "ブラブラサンポシヨウ", "ぶらぶら散歩しよう", "Let's go for a leisurely stroll!", "Daily Conversation"),
    ("byou-in ni itta hou ga ii yo", "びょういんにいったほうがいいよ", "ビョウインニイッタホウガイイヨ", "病院に行った方がいいよ", "You really ought to see a doctor!", "Health & Emergency"),

    # C
    ("chanto gohan tabeta?", "ちゃんとごはんたべた？", "チャントゴハンタベタ？", "ちゃんとご飯食べた？", "Did you eat a proper hearty meal?", "Daily Conversation"),
    ("chanto renraku shite ne", "ちゃんとれんらくしてね", "チャントレンラクシテネ", "ちゃんと連絡してね", "Make sure to keep me posted!", "Communication"),
    ("chotto dake kashite kudasai", "ちょっとだけかしてください", "チョットダケカシテクダサイ", "一寸だけ貸してください", "Could you lend that for just a second?", "Daily Conversation"),
    ("chotto kangaesashite", "ちょっとかんがえさせて", "チョットカンガエサセテ", "一寸考えさせて", "Let me think about it for a bit!", "Daily Conversation"),
    ("chotto michi ni mayoimashita", "ちょっとみちにまよいましました", "チョットミチニマヨイマシタ", "一寸道に迷いました", "I've gotten a little lost on the road.", "Travel & Directions"),
    ("chotto otowarai shite mo ii?", "ちょっとおといれにいってもいい？", "チョットオトイレニイッテモイイ？", "一寸お手洗いに行ってもいい？", "May I run to the restroom real quick?", "Daily Conversation"),
    ("chotto sabishii na", "ちょっとさびしいな", "チョットサビシイナ", "一寸寂しいな", "Feeling a little bit lonely...", "Empathy & Comfort"),
    ("chotto tetsudatte kuremasen ka", "ちょっとてつだってくれませんか", "チョットテツダッテクレマセンカ", "一寸手伝ってくれませんか", "Could you lend me a hand with this?", "Daily Conversation"),
    ("choushi wa dou desu ka", "ちょうしはどうですか", "チョウシワドウデスカ", "調子はどうですか", "How are things going with you?", "Daily Conversation"),

    # D
    ("daibutsuryou da ne, kore", "だいぶつりょうだね、これ", "ダイブツリョウダネ、コレ", "大物量だね、これ", "Whoa, that is a massive heap of stuff!", "Daily Conversation"),
    ("daibu yoku narimashita", "だいぶよくなりました", "ダイブヨクナリマシタ", "大分良くなりました", "I'm feeling considerably better now!", "Health & Emergency"),
    ("daijoubu desu ka, daiji ni", "だいじょうぶですか、おだいじに", "ダイジョウブデスカ、オダイジニ", "大丈夫ですか、お大事に", "Are you alright? Please take gentle care!", "Health & Emergency"),
    ("daitan na ketsudan da ne", "だいたんなけつだんだね", "ダイタンナケツダンダネ", "大胆な決断だね", "That's quite a bold, daring move!", "Daily Conversation"),
    ("dakara itta deshou!", "だからいったでしょう！", "ダカライッタデショウ！", "だから言ったでしょう！", "See, didn't I tell you so?!", "Daily Conversation"),
    ("dare ni mo iwanaide ne", "だれにもいわないでね", "ダレニモイワナイデネ", "誰にも言わないでね", "Keep this between you and me!", "Communication"),
    ("dekiru dake hayaku ikimasu", "できるだけはやく行きます", "デキルダケハヤクイキマス", "出来るだけ早く行きます", "I will get there as fast as I can!", "Daily Conversation"),
    ("denwa bango o oshiete", "でんわばんごうをおしえて", "デンワバンゴウヲオシエテ", "電話番号を教えて", "Could you share your phone number?", "Communication"),
    ("densha ga okurete imasu", "でんしゃがおくれています", "デンシャガオクレテイマス", "電車が遅れています", "The train is currently running behind.", "Travel & Directions"),
    ("doko de aimashou ka", "どこであいましょうか", "ドコデアイマショウカ", "何処で会いましょうか", "Where shall we rendezvous?", "Daily Conversation"),
    ("doko ka de mita koto aru", "どこかでみたことある", "ドコカデミタコトアル", "何処かで見たことある", "I feel like I've seen that somewhere!", "Daily Conversation"),
    ("dondon meshiagatte kudasai", "どんどんめしあがってください", "ドンドンメシアガッテクダサイ", "どんどん召し上がってください", "Please dig in and enjoy plenty!", "Dining"),
    ("douzo o-suwari kudasai", "どうぞおすわりください", "ドウゾオスワリクダサイ", "どうぞお座りください", "Please, go right ahead and have a seat!", "Hospitality"),
    ("doushite mo ikitai n desu", "どうしてもいきたいんです", "ドウシテモイキタインデス", "どうしても行きたいんです", "I really, truly want to go no matter what!", "Daily Conversation"),

    # E
    ("e, uso deshou?!", "え、うそでしょう？！", "エ、ウソデショウ？！", "え、嘘でしょう？！", "Wait, you've got to be kidding me?!", "Daily Conversation"),
    ("eiga demo mi ni ikou ka", "えいがでもみにいこうか", "エイガデモミニイコウカ", "映画でも見に行こうか", "Shall we catch a movie or something?", "Friends & Social"),
    ("egao ga suteki desu ne", "えがおがすてきですね", "エガオガステキデスネ", "笑顔が素敵ですね", "You have such a lovely, radiant smile!", "Communication"),
    ("enryo naku itte kudasai", "えんりょなくいってください", "エンリョナクイッテクダサイ", "遠慮なく言ってください", "Please speak freely without holding back!", "Communication"),

    # F
    ("fuan na toki wa itsudemo kiite", "ふあんなときわいつでもきいて", "フアンナトキワイツデモキイテ", "不安な時はいつでも聞いて", "Whenever you're worried, just ask me anytime!", "Empathy & Comfort"),
    ("fuku ga yogorechatta", "ふくがよごれちゃった", "フクガヨゴレチャッタ", "服が汚れちゃった", "Aw, my clothes got smudged!", "Daily Conversation"),
    ("fukuro wa irimasen", "ふくろはいりません", "フクロワイリマセン", "袋は要りません", "No shopping bag needed, thank you!", "Shopping & Dining"),
    ("furusato ga koishii", "ふるさとがこいしい", "フルサトガコイシイ", "故郷が恋しい", "I'm feeling a bit homesick for home.", "Empathy & Comfort"),
    ("futari de chikara o awasete", "ふたりでちからをあわせて", "フタリデチカラヲアワセテ", "二人で力を合わせて", "Let's join forces, the two of us!", "Cheering & Motivation"),
    ("futsuu no koto da yo", "ふつうのことだよ", "フツウノコトダヨ", "普通のことだよ", "It's totally ordinary / completely normal!", "Daily Conversation"),

    # G
    ("ganbatte kudasai ne!", "がんばってくださいね！", "ガンバッテクダサイネ！", "頑張ってくださいね！", "Hang in there and give it your best!", "Cheering & Motivation"),
    ("gasshirishita tsukuri da", "がっしりしたつくりだ", "ガッシリシタツクリダ", "がっしりした造りだ", "That is exceptionally solid craftsmanship!", "Daily Conversation"),
    ("gata-gata itte iru yo", "がたがたいっているよ", "ガタガタイッテイルヨ", "ガタガタ言っているよ", "Something is rattling over there!", "Daily Conversation"),
    ("gatten shouchi no suke!", "がってんしょうちのすけ！", "ガッテンショウチノスケ！", "合点承知の助！", "Roger that, consider it done with joy!", "Daily Conversation"),
    ("genki ga dete kita!", "げんきがでてきた！", "ゲンキガデテキタ！", "元気が出てきた！", "My spirits are surging back up!", "Cheering & Motivation"),
    ("gokigen ikaga desu ka", "ごきげんいかがですか", "ゴキゲンイカガデスカ", "ご機嫌いかがですか", "How are your honorable spirits today?", "Greetings"),
    ("gomen kudasai, dareka imasen ka", "ごめんください、だれかいませんか", "ゴメンクダサイ、ダレカイマセンカ", "ごめんください、誰かいませんか", "Excuse me, hello? Is anybody home?", "Greetings"),
    ("gomen ne, yurushite kurete", "ごめんね、ゆるしてくれてありがとう", "ゴメンネ、ユルシテクレテアリガトウ", "ごめんね、許してくれてありがとう", "I'm so sorry, and thank you for forgiving me!", "Apologies & Regrets"),
    ("gotsun to butsukatta", "ごつんとぶつかった", "ゴツントブツカッタ", "ごつんとぶつかった", "Bumped my noggin with a loud thud!", "Health & Emergency"),
    ("gutto koraemashita", "ぐっとこらえました", "グットコラエマシタ", "ぐっと堪えました", "I clamped down and held back tears!", "Daily Conversation"),

    # H
    ("ha o migaki-mashou", "はをみがきましょう", "ハヲミガキマショウ", "歯を磨きましょう", "Let's brush our teeth thoroughly!", "Daily Life"),
    ("hachikire-sou na egao da ne", "はちきれそうなえがおだね", "ハチキレソウナエガオダネ", "はち切れそうな笑顔だね", "What a dazzling, ear-to-ear smile!", "Communication"),
    ("hai, shouchi itashimashita", "はい、しょうちいたしました", "ハイ、ショウチイタシマシタ", "はい、承知いたしました", "Understood, right away with pleasure!", "Service & Hospitality"),
    ("hajimemashite, douzo yoroshiku", "はじめまして、どうぞよろしく", "ハジメマシテ、ドウゾヨロシク", "初めまして、どうぞよろしく", "Nice to meet you, looking forward to working with you!", "Greetings"),
    ("hakkiri to itte kurete arigatou", "はっきりといってくれてありがとう", "ハッキリトイッテクレテアリガトウ", "はっきりと言ってくれてありがとう", "Thank you for speaking with frank clarity!", "Gratitude & Thanks"),
    ("hanashi ga aima-su ne", "はなしがあいますね", "ハナシガアイマスネ", "話が合いますね", "We really hit it off and share great chemistry!", "Friends & Social"),
    ("harete kimashita yo", "はれてきましたよ", "ハレテキマシタヨ", "晴れてきましたよ", "Look, the skies are clearing up blue!", "Weather & Daily"),
    ("hayaku naotte kudasai ne", "は早くなおってくださいね", "ハヤクナオッテクダサイネ", "早く治ってくださいね", "Wishing you a swift, speedy recovery!", "Health & Emergency"),
    ("heiki, heiki, daijoubu!", "へいき、へいき、だいじょうぶ！", "ヘイキ、ヘイキ、ダイジョウブ！", "平気、平気、大丈夫！", "No sweat at all, totally fine!", "Daily Conversation"),
    ("heya o katazukemashita", "へやをかたづけました", "ヘヤヲカタヅケマシタ", "部屋を片付けました", "Tidied up the bedroom sparkling clean!", "Daily Life"),
    ("hidoku o-sawa-gase shimashita", "ひどくおさわがせしました", "ヒドクオサワガセシマシタ", "酷くお騒がせしました", "So very sorry for causing such commotion!", "Apologies & Regrets"),
    ("hima na toki ni renraku shite", "ひまなときにれんらくして", "ヒマナトキニレンラクシテ", "暇な時に連絡して", "Hit me up whenever you've got spare time!", "Friends & Social"),
    ("hisa-bisa ni aete ureshii!", "ひさびさにあえてうれしい！", "ヒサビサニアエテウレシイ！", "久しぶりに会えて嬉しい！", "So wonderful to see you after ages!", "Greetings & Celebrations"),
    ("hitori de nayamanaide", "ひとりでなやまないで", "ヒトリデナヤマナイデ", "一人で悩まないで", "Don't carry all those worries alone!", "Empathy & Comfort"),
    ("honto ni tasukatta, arigatou", "ほんとうにたすかった、ありがとう", "ホントウニタスカッタ、アリガトウ", "本当に助かった、ありがとう", "You truly saved my day, thank you!", "Gratitude & Thanks"),
    ("hotto hito-iki tsukou", "ほっとひといきつこう", "ホットヒトイキツコウ", "ほっと一息つこう", "Let's take a deep breath and unwind!", "Daily Conversation"),

    # I
    ("i-bukashiku omowanaide", "いぶかしくおもわないで", "イブカシクオモワナイデ", "訝しく思わないで", "Please don't look on with suspicion!", "Communication"),
    ("ichi-go ichi-e o taisetsu ni", "いちごいちえをたいせつに", "イチゴイチエヲタイセツニ", "一期一会を大切に", "Treasuring each once-in-a-lifetime encounter!", "Culture"),
    ("ii aidea da to omoimasu", "いいあいであだとおもいます", "イイアイデアダトオモイマス", "良いアイデアだと思います", "I think that's a stellar idea!", "Communication"),
    ("ii yume o mite ne", "いいゆめをみてね", "イイユメヲミテネ", "良い夢を見てね", "Sweet dreams tonight!", "Daily Conversation"),
    ("ikaga desu ka, o-aji wa", "いかがですか、おあじは", "イカガデスカ、オアジワ", "いかがですか、お味は", "How do you find the seasoning / flavor?", "Dining"),
    ("ima nani shite iru no?", "いまなにしているの？", "イマナニシテイルノ？", "今何しているの？", "What are you up to right now?", "Daily Conversation"),
    ("ima sugu ikimasu", "いますぐいきます", "イマスグイキマス", "今すぐ行きます", "I'm heading right over this instant!", "Daily Conversation"),
    ("issho ni kangaemashou", "いっしょにかんがえましょう", "イッショニカンガエマショウ", "一緒に考えましょう", "Let's brainstorm this out together!", "Classroom & Study"),
    ("itte kimasu! itte rasshai!", "いってきます！いってらっしゃい！", "イッテキマス！イッテラッシャイ！", "行ってきます！行ってらっしゃい！", "I'm off! Have a great safe day!", "Greetings"),
    ("itsu demo denwa shite ne", "いつでもでんわしてね", "イツデモデンワシテネ", "いつでも電話してね", "Call me anytime, day or night!", "Friends & Social"),

    # J - Z
    ("jikan ga attara asobou", "じかんがあったらあそぼう", "ジカンガアッタラアソボウ", "時間があったら遊ぼう", "If you have free time, let's hang out!", "Friends & Social"),
    ("jiko-shoukai o onegai shimasu", "じこしょうかいをおねがいします", "ジコショウカイヲオネガイシマス", "自己紹介をお願いします", "Please share a brief self-introduction!", "Communication"),
    ("jitsuwa sou nan desu", "じつはそうなんです", "ジツワソウナンデス", "実はそうなんです", "As a matter of fact, that's exactly true!", "Daily Conversation"),
    ("jiyuu ni tsukatte kudasai", "じゆうにつかってください", "ジユウニツカッテクダサイ", "自由に使ってください", "Please feel free to make use of it!", "Hospitality"),
    ("juubun ki o tsukete ne", "じゅうぶんきをつけてね", "ジュウブンキヲツケテネ", "十分気をつけてね", "Be extra careful on your journey!", "Safety & Health"),
    ("kaerimichi, ki o tsukete", "かえりみち、きをつけて", "カエリミチ、キヲツケテ", "帰り道、気をつけて", "Watch your step on the way back home!", "Daily Conversation"),
    ("kanpai shimashou!", "かんぱいしましょう！", "カンパイシマショウ！", "乾杯しましょう！", "Cheers everyone, bottoms up!", "Dining"),
    ("kaze o hikanai you ni ne", "かぜをひかないようにね", "カゼヲヒカナイヨウニネ", "風邪を引かないようにね", "Bundle up so you don't catch a cold!", "Health & Emergency"),
    ("kore kara mo yoroshiku", "これからもよろしく", "コレカラモヨロシク", "これからもよろしく", "Looking forward to continuing our friendship!", "Greetings"),
    ("kore, purezento da yo", "これ、ぷれぜんとだよ", "コレ、プレゼントダヨ", "これ、プレゼントだよ", "Here, this is a little present for you!", "Gratitude & Thanks"),
    ("kyou mo ichi-nichi ganbarou", "きょうもいちにちがんばろう", "キョウモイチニチガンバロウ", "今日も一日頑張ろう", "Let's give today our absolute best!", "Cheering & Motivation"),
    ("mata ashita aimashou", "またあしたあいましょう", "マタアシタアイマショウ", "また明日会いましょう", "See you again bright and early tomorrow!", "Greetings"),
    ("o-tsukaresama deshita", "おつかれさまでした", "オツカレサマデシタ", "お疲れ様でした", "Thank you for all your tireless effort!", "Work & Business"),
    ("shoujiki ni itte kurete ureshii", "しょうじきにいってくれてうれしい", "ショウジキニイッテクレテウレシイ", "正直に言ってくれて嬉しい", "I'm genuinely glad you told me truthfully!", "Communication"),
    ("taihen osewa ni narimashita", "たいへんおせわになりました", "タイヘンオセワニナリマシタ", "大変お世話になりました", "I am deeply indebted for your wonderful care!", "Gratitude & Thanks"),
    ("yukkuri yasunde kudasai", "ゆっくりやすんでください", "ユックリヤスンデクダサイ", "ゆっくり休んでください", "Please relax and rest up well!", "Empathy & Comfort"),
]
