# Authentic Japanese Conversational Expressions & Situational Phrases Part 3 (320+ entries)
# (romaji, hiragana, katakana, kanji, meaning, topic)
DATA = [
    # A
    ("a, amado o shimemashou", "あ、あまどをしめましょう", "ア、アマドヲシメマショウ", "あ、雨戸を閉めましょう", "Oh, let's close the storm shutters.", "Home & Living"),
    ("a, aozora ga miete kimashita", "あ、あおぞらがみえてきました", "ア、アオゾラガミエテキマシタ", "あ、青空が見えてきました", "Look, patches of blue sky are peeking through!", "Weather & Daily"),
    ("a, appurike ga kawaii ne", "あ、あっぷりけがかわいいね", "ア、アップリケガカワイイネ", "あ、アップリケが可愛いね", "Oh, what an adorable patch embroidery!", "Daily Life"),
    ("a, arakajime kakunin shite okou", "あ、あらかじめかくにんしておこう", "ア、アラカジメカクニンシテオコウ", "あ、予め確認しておこう", "Let's double-check that beforehand.", "Daily Conversation"),
    ("a, arasoi wa yamemashou yo", "あ、あらそいはやめましょうよ", "ア、アラソイワヤメマショウヨ", "あ、争いはやめましょうよ", "Come on, let's put an end to fighting.", "Communication"),
    ("a, arigatasa ga mi ni shimiru", "あ、ありがたさがみにしみる", "ア、アリガタサガミニシミル", "あ、有難さが身に染みる", "The kindness truly touches me to the core.", "Gratitude & Thanks"),
    ("a, asa-giri ga kirei da na", "あ、あさぎりがきれいだな", "ア、アサギリガキレイダナ", "あ、朝霧が綺麗だな", "What ethereal morning fog rolling in.", "Weather & Daily"),
    ("a, ase o fuite kudasai ne", "あ、あせをふいてくださいね", "ア、アセヲフイテクダサイネ", "あ、汗を拭いてくださいね", "Please wipe your forehead dry!", "Daily Life"),
    ("a, ashita mo ii hi ni naru yo", "あ、あしたもいいひになるよ", "ア、アシタモイイヒニナルヨ", "あ、明日も良い日になるよ", "Tomorrow is sure to be wonderful too!", "Empathy & Comfort"),
    ("a, asobi ni kite kurete arigatou", "あ、あそびにきてくれてありがとう", "ア、アソビニキテクレテアリガトウ", "あ、遊びに来てくれてありがとう", "Thank you so much for coming over to visit!", "Friends & Social"),
    ("a, atatakai ocha o douzo", "あ、あたたかいおちゃをどうぞ", "ア、アタタカイオチャヲドウゾ", "あ、温かいお茶をどうぞ", "Please enjoy this hot steaming tea.", "Hospitality"),
    ("a, atarashii fuku, niaimasu ne", "あ、あたらしいふく、にあいますね", "ア、アタラシイフク、ニアイマスネ", "あ、新しい服、似合いますね", "That new outfit suits you wonderfully!", "Communication"),
    ("a, ato chotto de kyuukei da", "あ、あとちょっとできゅうけいだ", "ア、アトチョットデキュウケイダ", "あ、あと一寸で休憩だ", "Just a few more minutes until break time!", "Work & Business"),
    ("a, atsu-atsu no nabe o kakomou", "あ、あつあつのなべをかこもう", "ア、アツアツノナベヲカコモウ", "あ、熱々の鍋を囲もう", "Let's gather round the piping hot hotpot!", "Dining"),
    ("a, ayashii hito wa inai yo", "あ、あやしいひとはいないよ", "ア、アヤシイヒトワイナイヨ", "あ、怪しい人はいないよ", "No suspicious figures around, all clear!", "Safety & Health"),
    ("a, azayaka na keshiki ni kangeki", "あ、あざやかなけしきにかんげき", "ア、アザヤカナケシキニカンゲキ", "あ、鮮やかな景色に感激した", "Utterly captivated by the vivid scenery!", "Travel & Places"),

    # B
    ("baka-banashi de moriagatta", "ばかばなしでもりあがった", "バカバナシデモリアガッタ", "馬鹿話で盛り上がった", "We had a riot laughing over silly banter.", "Friends & Social"),
    ("bakudai na yume o katarou", "ばくだいなゆめをかたろう", "バクダイナユメヲカタロウ", "莫大な夢を語ろう", "Let's share grand, boundless dreams!", "Cheering & Motivation"),
    ("ban-nen mo nakayoku kuroso", "ばんねんもなかよくくらそう", "バンネンモナカヨククラソウ", "晩年も仲良く暮らそう", "Let's live companionably into golden years.", "Family & Children"),
    ("baransu no ii shokuji o", "ばらんすのいいしょくじを", "バランスノイイショクジヲ", "バランスの良い食事を", "Eat a well-balanced healthy diet.", "Health & Emergency"),
    ("bassui o shite memo shita", "ばっすいをしてめもした", "バッスイヲシテメモシタ", "抜粋してメモした", "Took notes on the core excerpts.", "Classroom & Study"),
    ("batsu-gun no haigo da ne", "ばつぐんのうしろだね", "バツグンノウシロダネ", "抜群の配合だね", "An extraordinarily balanced blend!", "Dining"),
    ("betsu no koto mo kiite ii?", "べつのこともきいていい？", "ベツノコトモキイテイイ？", "別の事も聞いていい？", "May I ask about another matter as well?", "Communication"),
    ("bimyona iro-ai ga suteki", "びみょうないろあいがすてき", "ビミョウナイロアイガステキ", "微妙な色合いが素敵", "That nuanced hue is simply exquisite.", "Daily Life"),
    ("binbin kanjiru jounetsu da", "びんびんかんじるじょうねつだ", "ビンビンカンジルジョウネツダ", "情熱が伝わる", "Your electric passion comes through loud and clear!", "Cheering & Motivation"),
    ("bita ichimon son shinai", "びたいちもんそんしない", "ビタイチモンソンシナイ", "一文も損しない", "Not losing a single fraction of a penny.", "Work & Business"),
    ("bousou o osaeru chie", "ぼうそうをおさえるちえ", "ボウソウヲオサエルチエ", "暴走を抑える知恵", "The wisdom to keep wild impulses in check.", "Daily Conversation"),
    ("bunseki kekka o gokakunin o", "ぶんせきけっかをごかくにんを", "ブンセキケッカヲゴカクニンヲ", "分析結果をご確認ください", "Please inspect the analytical findings.", "Work & Business"),
    ("byoudou na shisen de miyou", "びょうどうなしせんでみよう", "ビョウドウナシセンデミヨウ", "平等な視点で見よう", "Let's view through an egalitarian lens.", "Communication"),

    # C
    ("chakujitsu na doryoku no seika", "ちゃくじつなどりょくのせいかだ", "チャクジツナドリョクノセイカダ", "着実な努力の成果だ", "The sweet fruit of consistent effort!", "Cheering & Motivation"),
    ("chiisa na kizuki o taisetsu ni", "ちいさなきづきをたいせつに", "チイサナキヅキヲタイセツニ", "小さな気づきを大切に", "Treasuring subtle little epiphanies.", "Classroom & Study"),
    ("chikara o nukeba umaku iku yo", "ちからをぬけばうまくいくよ", "チカラヲヌケバウマクイクセ", "力を抜けば上手くいくよ", "Relax your muscles and it will flow easy.", "Cheering & Motivation"),
    ("chimitsu na gijutsu ni odoroku", "ちみつなぎじゅつにおどろく", "チミツナギジュツニオドロク", "緻密な技術に驚く", "Awestruck by the hyper-fine technique.", "Culture"),
    ("chitsujo ga areba ansinda", "ちつじょがあればあんしんだ", "チツジョガアレバアンシンダ", "秩序があれば安心だ", "When good order reigns, everyone is at ease.", "Daily Life"),
    ("chotto sanpo shite kimasu ne", "ちょっとさんぽしてきますね", "チョットサンポシテキマスネ", "一寸散歩してきますね", "I'm going to take a short stroll outside.", "Daily Life"),
    ("choushi ga warui toki wa nete", "ちょうしがわるいときはねてね", "チョウシガワルイトキワネテネ", "調子が悪い時は寝てね", "When feeling sick, sleep is best medicine!", "Health & Emergency"),
    ("chouwa o midasanaide ne", "ちょうわをみださないでね", "チョウワヲミダサナイデネ", "調和を乱さないでね", "Please maintain harmony in the group.", "Communication"),
    ("chuuto-hanpa wa iya da kara", "ちゅうとはんぱはいやだから", "チュウトハンパワイヤダカラ", "中途半端は嫌だから", "Because I detest leaving things half-done.", "Daily Conversation"),

    # D
    ("daidai-iro no kajitsu ga jukushita", "だいだいいろのかじつがじゅくした", "ダイダイイロノカジツガジュクシタ", "果実が熟した", "The bright orange citrus has ripened sweet.", "Dining"),
    ("daikibo na keikaku o tateta", "だいきぼなけいかくをたてた", "ダイキボナケイカクヲタテタ", "大規模な計画を立てた", "Drafted an ambitious grand master plan.", "Work & Business"),
    ("daitan ni ippo o fumidasou", "だいたんにいっぽをふみだそう", "ダイタンニイッポヲフミダソウ", "大胆に一歩を踏み出そう", "Let's take a daring, bold first leap!", "Cheering & Motivation"),
    ("danbou o tsuyomete mo ii?", "だんぼうをつよめてもいい？", "ダンボウヲツヨメテモイイ？", "暖房を強めてもいい？", "May I turn the room heating up a notch?", "Home & Living"),
    ("danryoku-sei no aru sozaida", "だんりょくせいのあるそざいだ", "ダンリョクセイノアルソザイダ", "弾力性のある素材だ", "A springy, resilient flexible material.", "Shopping & Dining"),
    ("datsuryoku shite fukaku nemurou", "だつりょくしてふかくねむろう", "ダツリョクシテフカクネムロウ", "脱力して深く眠ろう", "Let all tension go and sleep soundly.", "Daily Life"),
    ("dekitate no sandoicchi o douzo", "できたてのさんどいっちをどうぞ", "デキタテノサンドイッチヲドウゾ", "出来立てのサンドイッチをどうぞ", "Please enjoy this freshly made sandwich!", "Dining"),
    ("denpa ga kaifuku shimashita", "でんぱがかいふくしました", "デンパガカイフクシマシタ", "電波が回復しました", "Cellular signal reception has restored!", "Communication"),
    ("densen-byou o yobou shiyou", "でんせんびょうをよぼうしよう", "デンセンビョウヲヨボウシヨウ", "感染症を予防しよう", "Let's practice diligent preventive hygiene.", "Health & Emergency"),
    ("dokutoku no aji de yamitsuki", "どくとくのあじでやみつきだ", "ドクトクノアジデヤミツキダ", "独特の味で病みつきだ", "Addictively delicious idiosyncratic flavor!", "Dining"),
    ("doryoku ga jitsuritsu shita!", "どりょくがみのりをむすんだ！", "ドリョクガミノリヲムスンダ！", "努力が実を結んだ！", "All that hard work has borne wonderful fruit!", "Cheering & Motivation"),

    # E
    ("eikyuu ni tsuzuku ai da", "えいきゅうにつづくあいだ", "エイキュウニツヅクアイダ", "永久に続く愛だ", "A love that endures throughout eternity.", "Friends & Social"),
    ("eikyou-ryoku ga takai sakuhin", "えいきょうりょくがたかいさくひんだ", "エイキョウリョクガタカイサクヒンダ", "影響力が高い作品だ", "An immensely impactful, influential work.", "Culture"),
    ("ekiteki na kangeki o arigatou", "えきてきなかんげきをありがとう", "エキテキナカンゲキヲアリガトウ", "劇的な感激をありがとう", "Thank you for such breathtaking thrills!", "Gratitude & Thanks"),
    ("enman na taiwa o tsuzukeyou", "えんまんなたいわをつづけよう", "エンマンナタイワヲツヅケヨウ", "円満な対話を続けよう", "Let's keep up warm, amicable dialogue.", "Communication"),
    ("enshou ga shizumatte anshin", "えんしょうがしずまってあんしんだ", "エンショウガシズマッテアンシンダ", "炎症が鎮まって安心だ", "Relieved that the inflammation cooled down.", "Health & Emergency"),
    ("eri-suguri no cha-ba o douzo", "えりすぐりのちゃばをどうぞ", "エリスグリノチャバヲドウゾ", "選りすぐりの茶葉をどうぞ", "Enjoy these choice, selected green tea leaves.", "Hospitality"),

    # F
    ("fuantei na kokoro o iyaso", "ふあんていなこころをいやそう", "フアンテイナココロヲイヤソウ", "心を癒やそう", "Let's soothe and heal unsteady feelings.", "Empathy & Comfort"),
    ("fubyoudou o naku-shite ikou", "ふびょうどうをなくしていこう", "フビョウドウヲナクシテイコウ", "不平等を無くしていこう", "Let's work steadily to stamp out unfairness.", "Communication"),
    ("fuchuui na kega o fusego", "ふちゅういなけがをふせごう", "フチュウイナケガヲフセゴウ", "不注意な怪我を防ごう", "Let's guard against accidental injuries.", "Safety & Health"),
    ("fugou no gotoku kanpai shiyou", "ふごうのごとくかんぱいしよう", "フゴウノゴトクカンパイシヨウ", "乾杯しよう", "Let's toast generously like royalty!", "Dining"),
    ("fujiyuu o kanjinai kurashi", "ふじゆうをかんじないくらしだ", "フジユウヲカンジナイクラシダ", "不自由のない暮らし", "Living in sweet abundance and comfort.", "Daily Life"),
    ("fukami no aru nioi ga suki", "ふかみのあるにおいがすき", "フカミノアルニオイガスキ", "深みのある香りが好き", "I love scents with rich, lingering depth.", "Daily Life"),
    ("fukitsu na koto wa wasureyou", "ふきつなことはわすれよう", "フキツナコトワワスレヨウ", "不吉なことは忘れよう", "Let's put superstitious bad omens out of mind.", "Empathy & Comfort"),
    ("fukouhei o zesei suru tame", "ふこうへいをぜせいするため", "フコウヘイヲゼセイスルタメ", "不公平を是正するため", "Working to correct inequitable treatment.", "Communication"),
    ("fukusou o totonoete shuppatsu", "ふくそうをととのえてしゅっぱつ", "フクソウヲトトノエテシュッパツ", "服装を整えて出発しよう", "Straighten our gear and head on out!", "Travel & Places"),
    ("fumi ga takai o-kashi da", "ふうみがたかいおかしだね", "フウミガタカイオカシダネ", "風味が高いお菓子だね", "A confection with wonderfully aromatic notes.", "Dining"),
    ("funiki no yoi machi o arukou", "ふんいきのよいまちをあるこう", "フンイキノヨイマチヲアルコウ", "雰囲気の良い街を歩こう", "Let's explore streets rich in ambiance.", "Travel & Places"),
    ("fusei o minuku me o motou", "ふせいをみぬくめをもとう", "フセイヲミヌクメヲモトウ", "不正を見抜く目を持とう", "Cultivating an eye to detect deceit.", "Classroom & Study"),
    ("futou na koto ni wa koushi", "ふとうなことにはこうししよう", "フトウナコトニワコウシシヨウ", "不当なことには抗議しよう", "Let's stand up against wrongful terms.", "Communication"),
    ("fuzei aru yado de kyuukei", "ふぜいあるやどできゅうけい", "フゼイアルヤドデキュウケイ", "風情ある宿で休憩しよう", "Let's rest at this quaint historic inn.", "Travel & Hotel"),

    # G
    ("gai o oyobosanai anshin", "がいをおよぼさないあんしんかん", "ガイヲオヨボサナイアンシンカン", "安心感", "True peace of mind from zero-harm products.", "Safety & Health"),
    ("gakumon no tanoshisa o shitta", "がくもんのたのしさをしった", "ガクモンノタノシサヲシッタ", "学問の楽しさを知った", "Discovered the sheer exhilaration of learning!", "Classroom & Study"),
    ("ganban no gotoki kesshin da", "がんばんのごときけっしんだ", "ガンバンノゴトキケッシンダ", "岩盤の如き決心だ", "A resolution solid as granite bedrock.", "Cheering & Motivation"),
    ("ganjou ni tsukuri-naoshita", "がんじょうにつくりなおした", "ガンジョウニツクリナオシタ", "頑丈に造り直した", "Rebuilt it stoutly to last through storms.", "Home & Living"),
    ("gara no yoi mise de shokuji", "がらのよいみせでしょくじしよう", "ガラノヨイミセデショクジシヨウ", "柄の良い店で食事しよう", "Let's dine at an establishment with class.", "Dining"),
    ("geijutsu no miryoku o katarou", "げいじゅつのみりょくをかたろう", "ゲイジュツノミリョクヲカタロウ", "芸術の魅力を語ろう", "Let's talk about the enchantment of fine art.", "Culture"),
    ("genba no chie o ikasou", "げんばのちえをいかそう", "ゲンバノチエヲイカソウ", "現場の知恵を生かそう", "Let's leverage the practical on-site wisdom.", "Work & Business"),
    ("genkaku na kanri ga hikaru", "げんかくなかんりがひかる", "ゲンカクナカンリガヒカル", "厳格な管理が光る", "Spotless, meticulous oversight.", "Work & Business"),
    ("genmitsu na kensa o tootta", "げんみつなけんさをとおった", "ゲンミツナケンサヲトオッタ", "厳密な検査を通った", "Passed rigorous laboratory inspections.", "Safety & Health"),
    ("genshou no tabi e dekeyou", "げんそうのたびへでかけよう", "ゲンソウノタビヘデカケヨウ", "幻想の旅へ出かけよう", "Let's embark on an enchanted fairytale quest.", "Travel & Places"),
    ("gikochinasa ga torete kita", "ぎこちなさがとれてきたね", "ギコチナサガトレテキタネ", "ぎこちなさが取れてきたね", "The stiff awkwardness is smoothing right out!", "Communication"),
    ("gouin na yarikata wa yameyo", "ごういんなやりかたはやめよう", "ゴウインナヤリカタワヤメヨウ", "強引なやり方はやめよう", "Let's put high-handed methods aside.", "Communication"),
    ("gouka na ryori o kakomou", "ごうかなりょうりをかこもう", "ゴウカナリョウリヲカコモウ", "豪華な料理を囲もう", "Let's gather round this sumptuous feast!", "Dining"),
    ("goutei no rekishi o kiku", "ごうていのれきしをきく", "ゴウテイノレキシヲキク", "豪邸の歴史を聴く", "Hearing tales of the grand manor's lore.", "Culture"),

    # H
    ("haigo o mamoru nakama da", "はいごをまもるなかまだ", "ハイゴヲマモルナカマダ", "背後を守る仲間だ", "Comrades who fiercely protect my back.", "Friends & Social"),
    ("hakarishirenai mirai ga matsu", "はかりしれないみらいがまつ", "ハカリシレナイミライガマツ", "計り知れない未来が待つ", "A future of boundless promise awaits!", "Cheering & Motivation"),
    ("hakken o tomoni shukufuku", "はっけんをともにしゅくふく", "ハッケンヲトモニシュクフク", "発見を共に祝福しよう", "Let's celebrate this breakthrough discovery!", "Classroom & Study"),
    ("hakuryoku man-ten de kansei", "はくりょくまんてんでかんせいした", "ハクリョクマンテンデカンセイシタ", "迫力満点で歓声が上がった", "Wild cheers erupted at the stunning scene!", "Culture"),
    ("hamigaki o shite oyasumi", "はみがきをしておやすみなさい", "ハミガキヲシテオヤスミナサイ", "歯磨きしておやすみなさい", "Brush your teeth and have sweet dreams!", "Family & Children"),
    ("hanayaka na hanabi o miyou", "はなやかなはなびをみよう", "ハナヤカナハナビヲミヨウ", "華やかな花火を見よう", "Let's watch the dazzling grand fireworks.", "Culture"),
    ("hantsuki no doryoku ga kansei", "はんつきのどりょくがみのった", "ハンツキノドリョクガミノッタ", "半月の努力が実った", "A half-month's hard work paid off!", "Work & Business"),
    ("haritsumeta kuuki ga yawaraida", "はりつめたくうきがやわらいだ", "ハリツメタクウキガヤワライダ", "張り詰めた空気が和らいだ", "The taut tension softened into smiles.", "Communication"),
    ("hassei o minikunde fusegu", "はっせいをみこんでふせぐ", "ハッセイヲミコンデフセグ", "先回りして防ぐ", "Anticipating problems and neutralizing them.", "Work & Business"),
    ("hatten no rekishi o manabou", "はってんのれきしをまなぼう", "ハッテンノレキシヲマナボウ", "発展の歴史を学ぼう", "Let's study the history of civic progress.", "Classroom & Study"),
    ("heibon na nichijou no takara", "へいぼんなにちじょうのたから", "ヘイボンナニチジョウノタカラ", "日常の宝物", "Finding precious gems in humble daily life.", "Daily Life"),
    ("heisateki na ba o kaifou shiyou", "へいさてきなばをかいほうしよう", "ヘイサテキナバヲカイホウシヨウ", "閉鎖的な場を開放しよう", "Let's open up this insular space to fresh air.", "Communication"),
    ("hendou ni urotaneyou", "へんどうにうろたえないようにしよう", "ヘンドウニウロタエナイヨウニシヨウ", "うろたえないようにしよう", "Let's stay unshaken by sudden fluctuations.", "Work & Business"),
    ("hidoku ochikonda toki wa", "ひどくおちこんだときはなそう", "ヒドクオチコンダトキワナソウ", "酷く落ち込んだ時は話そう", "When you feel terribly down, talk to me!", "Empathy & Comfort"),
    ("hifu ga uruotte kimashita", "ひふがうるおってきました", "ヒフガウルオッテキマシタ", "肌が潤ってきました", "My skin has become soft and nicely moisturized!", "Daily Life"),
    ("hikaku suru to chigai ga mieru", "ひかくするとちがいがみえる", "ヒカクスルトチガイガミエル", "比較すると違いが見える", "Contrasting them highlights the key differences.", "Classroom & Study"),
    ("hikkuri-kaette mo heiki!", "ひっくりかえってもへいきだ！", "ヒックリカエッテモヘイキダ！", "ひっくり返っても平気！", "Even if we tumble over, we bounce back!", "Cheering & Motivation"),
    ("hisshi de tsunai-da kizuna", "ひっしでつないだきずなだ", "ヒッシデツナイダキズナダ", "必死で繋いだ絆だ", "A sacred bond forged through sheer devotion.", "Friends & Social"),
    ("hitasura shoujin suru sugata", "ひたすらしょうじんするすがた", "ヒタスラショウジンスルスガタ", "ひたすら精進する姿", "The inspiring sight of tireless dedication.", "Cheering & Motivation"),
    ("hitori-bocchi ni sasenai yo", "ひとりぼっちにさせないよ", "ヒトリボッチニサセナイヨ", "一人ぼっちにさせないよ", "I will never leave you on your own!", "Empathy & Comfort"),
    ("hokorashiku susumou", "ほこらしくすすもう", "ホコラシクススモウ", "誇らしく進もう", "Let's march forward with head held high!", "Cheering & Motivation"),
    ("honki no koe ga kikoeta", "ほんきのこえがきこえた", "ホンキノコエガキコエタ", "本気の声が聞こえた", "I heard the genuine, serious conviction in your voice.", "Communication"),
    ("honmono no ajiwai o ajiwatta", "ほんもののあじわいをおぼえた", "ホンモノノアジワイヲオボエタ", "本物の味わいを覚えた", "Learned what true artisanal taste is.", "Dining"),
    ("horonigai ocha de hito-iki", "ほろにがいおちゃでひといき", "ホロニガイオチャデヒトイキ", "ほろ苦いお茶で一息つこう", "Take a breather with contemplative bitter tea.", "Daily Life"),
    ("hoshuteki na gawa to kyouzon", "ほしゅてきながわときょうぞん", "ホシュテキナガワトキョウゾン", "共存しよう", "Coexisting peacefully with traditional values.", "Communication"),
    ("hyoujou-yutaka na nakama-tachi", "ひょうじょうゆたかななかまたち", "ヒョウジョウユタカナナカマタチ", "表情豊かな仲間たち", "Expressive, animated and warm companions!", "Friends & Social"),
]
