# Authentic Japanese Phrases Part 5 - Daily Interactions & JLPT Dialogue (250+ entries)
# (romaji, hiragana, katakana, kanji, meaning, topic)
DATA = [
    # A
    ("a, ai-ta jikan ni yomou", "あ、あいたじかんにあよもう", "ア、アイタジカンニヨモウ", "あ、空いた時間に読もう", "I will read this during my free time.", "Daily Life"),
    ("a, aitsu wa ii yatsu da", "あ、あいつはいいやつだ", "ア、アイツワイイヤツダ", "あ、あいつは良い奴だ", "He's genuinely a great guy.", "Friends & Social"),
    ("a, akari ga kieta yo", "あ、あかりがきえたよ", "ア、アカリガキエタヨ", "あ、明かりが消えたよ", "Oh, the power / light went out!", "Daily Life"),
    ("a, aki no kehai ga suru", "あ、あきのけはいがする", "ア、アキノケハイガスル", "あ、秋の気配がする", "Ah, autumn is definitely in the air.", "Weather & Daily"),
    ("a, amamori ga shite iru", "あ、あまもりがしている", "ア、アマモリガシテイル", "あ、雨漏りがしている", "Oh, the roof is leaking a bit!", "Home & Living"),
    ("a, anata no okage desu", "あ、あなたのおかげです", "ア、アナタノオカゲデス", "あ、貴方のおかげです", "This was all thanks to you!", "Gratitude & Thanks"),
    ("a, anzen banto o shimete", "あ、あんぜんべるとをしめて", "ア、アンゼンベルトヲシメテ", "あ、シートベルトを締めて", "Please fasten your seatbelt.", "Safety & Health"),
    ("a, aoi ringo wa sappari", "あ、あおいりんごはさっぱり", "ア、アオオリンゴワサッパリ", "あ、青林檎はさっぱりしている", "Green apples are crisp and tangy.", "Dining"),
    ("a, arakajime shirabemashita", "あ、あらかじめしらべました", "ア、アラカジメシラベマシタ", "あ、予め調べました", "I researched that thoroughly in advance.", "Classroom & Study"),
    ("a, arigatou, ureshii yo", "あ、ありがとう、うれしいよ", "ア、アリガトウ、ウレシイヨ", "あ、ありがとう、嬉しいよ", "Thank you, that makes me so happy!", "Gratitude & Thanks"),
    ("a, asa no taisou o shiyou", "あ、あさのたいそうをしよう", "ア、アサノタイソウヲシヨウ", "あ、朝の体操をしよう", "Let's do morning radio calisthenics!", "Daily Life"),
    ("a, ashi ga tsukareta na", "あ、あしがつかれたな", "ア、アシガツカレタナ", "あ、足が疲れたな", "Phew, my feet are quite tired.", "Daily Conversation"),
    ("a, asobi-gokoro ga daiji", "あ、あそびごころがだいじだ", "ア、アソビゴコロガダイジダ", "あ、遊び心が大事だ", "A playful, curious spirit is key!", "Daily Conversation"),
    ("a, atatakai fuku o kite ne", "あ、あたたかいふくをきてね", "ア、アタタカイフクヲキテネ", "あ、温かい服を着てね", "Bundle up in nice warm clothes!", "Family & Children"),
    ("a, atarashii tomodachi ga dekita", "あ、あたらしいともだちができた", "ア、アタラシイトモダチガデキタ", "あ、新しい友達が出来た", "I made a wonderful new friend today!", "Friends & Social"),
    ("a, ato chotto de tsuku yo", "あ、あとちょっとでつくよ", "ア、アトチョットデツクヨ", "あ、あと一寸で着くよ", "We'll be arriving in just a few minutes!", "Travel & Places"),
    ("a, atsu-atsu no takoyaki da", "あ、あつあつのたこやきだ", "ア、アツアツノタコヤキダ", "あ、熱々のたこ焼きだ", "Piping hot fresh takoyaki octopus balls!", "Dining"),
    ("a, ayamaru koto wa nai yo", "あ、あやまることはないよ", "ア、アヤマルコトワナイヨ", "あ、謝る事はないよ", "There's really nothing to apologize for!", "Empathy & Comfort"),
    ("a, azayaka na hanabira da", "あ、あざやかなはなびらだ", "ア、アザヤカナハナビラダ", "あ、鮮やかな花びらだ", "What vibrant, colorful petals!", "Daily Life"),

    # B
    ("baka-baka-shikute kyuukutsu da", "ばかばかしくてきゅうくつだ", "バカバカシクテキュウクツダ", "窮屈な話だ", "A suffocating, absurd constraint.", "Daily Conversation"),
    ("bakudai na enajii o himete iru", "ばくだいなえなじーをひめている", "バクダイナエナジーヲヒメテイル", "エネルギーを秘めている", "Harboring vast reserves of potential!", "Cheering & Motivation"),
    ("ban-nen ni densetsu to natta", "ばんねんにでんせつとなった", "バンネンニデンセツトナッタ", "晩年に伝説となった", "Became a living legend in later years.", "Culture"),
    ("baransu ga kuzureta", "ばらんすがくずれた", "バランスガクズレタ", "バランスが崩れた", "Lost equilibrium for a second.", "Daily Conversation"),
    ("bassui o fukusha shite", "ばっすいをふくしゃして", "バッスイヲフクシャシテ", "抜粋を複写して", "Photocopying the key excerpts.", "Classroom & Study"),
    ("batsu-gun no kire o miseta", "ばつぐんのきれをみせた", "バツグンノキレヲミセタ", "抜群のキレを見せた", "Showcased razor-sharp crisp technique.", "Cheering & Motivation"),
    ("betsu no hito ni kiite miyou", "べつのひとにきいてみよう", "ベツノヒトニキイテミヨウ", "別の人に聞いてみよう", "Let's ask someone else for directions.", "Travel & Directions"),
    ("bimyona chigai o miwakeru", "びみょうなちがいをみわける", "ビミョウナチガイヲミワケル", "微妙な違いを見分ける", "Discerning delicate nuanced differences.", "Classroom & Study"),
    ("binbin to chikara ga waku", "びんびんとちからがわく", "ビンビントチカラガワク", "力が湧く", "Strength welling up with intense vigor!", "Cheering & Motivation"),
    ("bita ichimon modoranai", "びたいちもんもどらない", "ビタイチモンモドラナイ", "一文も戻らない", "Not a single coin refunded.", "Shopping & Dining"),
    ("bousou o seigyo suru", "ぼうそうをせいぎょする", "ボウソウヲセイギョスル", "暴走を制御する", "Reining in the runaway forces.", "Work & Business"),
    ("bunseki de shouko o tsukamu", "ぶんせきでしょうこをつかむ", "ブンセキデショウコヲツカム", "分析で証拠を掴む", "Grasping firm proof through analysis.", "Classroom & Study"),
    ("byoudou na chansu o ataeyo", "びょうどうなちゃんすをあたえよう", "ビョウドウナチャンスヲアタエヨウ", "平等なチャンスを与えよう", "Let's provide fair equal opportunity.", "Work & Business"),

    # C
    ("chakujitsu na fukushuu ga kagi", "ちゃくじつなふくしゅうがかぎだ", "チャクジツナフクシュウガカギダ", "着実な復習が鍵だ", "Steady review is the golden master key.", "Classroom & Study"),
    ("chiisa na koto kara kコツコツ", "ちいさなことからこつこつ", "チイサナコトカラコツコツ", "小さな事からコツコツと", "Chipping away diligently from small beginnings.", "Cheering & Motivation"),
    ("chikara o awasete kachimouk", "ちからをあわせてかちとろう", "チカラヲアワセテカチトロウ", "力を合わせて勝ち取ろう", "Let's unite forces and seize victory!", "Cheering & Motivation"),
    ("chimitsu na saiku ga sugoi", "ちみつなさいくがすごい", "チミツナサイクガスゴイ", "緻密な細工が凄い", "What breathtakingly intricate inlay craft!", "Culture"),
    ("chitsujo aru machi o tsukuro", "ちつじょあるまちをつくろう", "チツジョアルマチヲツクロウ", "秩序ある街を創ろう", "Let's build a safe and orderly community.", "Daily Life"),
    ("chotto me o tsubutte mite", "ちょっとめをつぶってみて", "チョットメヲツブッテミテ", "一寸目を瞑ってみて", "Close your eyes for just a moment.", "Daily Conversation"),
    ("choushi ga modotte ureshii", "ちょうしがもどってうれしい", "チョウシガモドッテウレシイ", "調子が戻って嬉しい", "So glad my groove is back in action!", "Daily Conversation"),
    ("chouwa no bi o kanjiru", "ちょうわのびをかんじる", "チョウワノビヲカンジル", "調和の美を感じる", "Feeling the sublime beauty of harmony.", "Culture"),
    ("chuuto de kangaenaoso", "ちゅうとでかんがえなおそう", "チュウトデカンガエナオソウ", "中途で考え直そう", "Let's pause mid-way and re-evaluate.", "Work & Business"),

    # D
    ("daidai-iro no yuubi o mita", "だいだいいろのゆうびをみた", "ダイダイイロノユウビヲミタ", "橙色の夕日を見た", "Gazed at the blazing orange sunset.", "Weather & Daily"),
    ("daikibo na koushin o jisshi", "だいきぼなこうしんをじっし", "ダイキボナコウシンヲジッシ", "大規模な更新を実施した", "Executed a massive infrastructure upgrade.", "Work & Business"),
    ("daitan ni idomou!", "だいたんにいどもう！", "ダイタンニイドモウ！", "大胆に挑もう！", "Let's take on the challenge with bold audacity!", "Cheering & Motivation"),
    ("danbou ga kiete samui", "だんぼうがきえてさむい", "ダンボウガキエテサムイ", "暖房が消えて寒い", "The heater shut off and it's chilly.", "Home & Living"),
    ("danryoku no aru suhada", "だんりょくのあるすはだ", "ダンリョクノアルスハダ", "弾力のある素肌", "Dewy, supple and resilient skin.", "Daily Life"),
    ("datsuryoku no jikan o tsukuro", "だつりょくのじかんをつくろう", "ダツリョクノジカンヲツクロウ", "脱力の時間を作ろう", "Let's carve out downtime to fully unwind.", "Empathy & Comfort"),
    ("dekitate no manjuu o douzo", "できたてのまんじゅうをどうぞ", "デキタテノマンジュウヲドウゾ", "出来立ての饅頭をどうぞ", "Have a piping fresh steamed sweet bean bun!", "Dining"),
    ("denpa ga kireta kamo", "でんぱがきれたかも", "デンパガキレタカモ", "電波が切れたかも", "The signal might have cut out briefly.", "Communication"),
    ("densen-kousho o kenshou", "でんせんこうしょをけんしょう", "デンセンコウショヲケンショウ", "経路を検証する", "Analyzing transmission pathways carefully.", "Health & Emergency"),
    ("dokutoku no risumu da ne", "どくとくのりずむだね", "ドクトクノリズムダネ", "独特のリズムだね", "What a singularly infectious rhythm!", "Culture"),
    ("doryoku no ashiato da", "どりょくのあしあとだ", "ドリョクノアシアトダ", "努力の足跡だ", "The proud footprints of honest effort.", "Cheering & Motivation"),

    # E
    ("eikyuu ni kagayaku hoshi", "えいきゅうにかがやくほし", "エイキュウニカガヤクホシ", "永久に輝く星", "Stars that shine for all eternity.", "Nature & Climate"),
    ("eikyou o fukaku uketa", "えいきょうをふかくうけた", "エイキョウヲフカクウケタ", "影響を深く受けた", "Deeply influenced and inspired by that.", "Classroom & Study"),
    ("ekiteki na deai ni kansha", "えきてきなであいにかんしゃ", "エキテキナデアインカンシャ", "劇的な出会いに感謝", "Grateful for this dramatic fateful meeting.", "Friends & Social"),
    ("enman na kankei o kizuko", "えんまんなかんけいをきずこう", "エンマンナカンケイヲキズコウ", "円満な関係を築こう", "Let's foster sweet harmonious relationships.", "Communication"),
    ("enshou ga hiite anshin", "えんしょうがひいてあんしんした", "エンショウガヒイテアンシンシタ", "炎症が引いて安心した", "Relieved that the irritation has subsided.", "Health & Emergency"),
    ("eri-suguri no meisho o meguro", "えりすぐりのめいしょをめぐろう", "エリスグリノメイショヲメグロウ", "名所を巡ろう", "Let's tour hand-picked scenic spots.", "Travel & Places"),

    # F
    ("fuantei na toki koso sasae-ao", "ふあんていなときこそささえあおう", "フアンテイナトキコソササエアオウ", "支え合おう", "In turbulent times, let's lean on each other.", "Empathy & Comfort"),
    ("fubyoudou o yurusanai", "ふびょうどうをゆるさない", "フビョウドウヲユルサナイ", "不平等を許さない姿勢", "An uncompromising stance against injustice.", "Communication"),
    ("fuchuui o kaishou shiyo", "ふちゅういをかいしょうしよう", "フチュウイヲカイショウシヨウ", "不注意を解消しよう", "Eliminating careless errors methodically.", "Work & Business"),
    ("fugou no gotoku furumaou", "ふごうのごとくふるまおう", "フゴウノゴトクフルマオウ", "気前よく振る舞おう", "Let's treat everyone with royal generosity!", "Dining"),
    ("fujiyuu o kanjinai kankyou", "ふじゆうをかんじないかんきょう", "フジユウヲカンジナイカンキョウ", "不自由のない環境", "An environment completely free of friction.", "Daily Life"),
    ("fukami no aru kotoba da", "ふかみのあることばだね", "フカミノアルコトバダネ", "深みのある言葉だね", "Those words possess extraordinary depth.", "Communication"),
    ("fukitsu na kage o haratta", "ふきつなかげをはらった", "フキツナカゲヲハラッタ", "不吉な影を払った", "Banished all lingering shadows of gloom.", "Daily Conversation"),
    ("fukouhei o naku-sou yo", "ふこうへいをなくそうよ", "フコウヘイヲナクソウヨ", "不公平を無くそうよ", "Let's banish unfairness once and for all.", "Communication"),
    ("fukusou o aratamete kyouketsu", "ふくそうをあらためてけいえい", "フクソウヲアラタメテケイエイ", "服装を正して", "Straightening attire respectfully.", "Classroom & Study"),
    ("fumi ga yutaka na matcha", "ふうみがゆたかなまっちゃ", "フウミガユタカナマッチャ", "風味豊かな抹茶", "Fragrant, deeply earthy authentic matcha.", "Dining"),
    ("funiki ga nagoyaka da", "ふんいきがなごやかだね", "フンイキガナゴヤカダネ", "雰囲気が和やかだね", "What a delightfully genial ambiance.", "Daily Conversation"),
    ("fusei o haishi shita", "ふせいをはいしした", "フセイヲハイシシタ", "不正を廃止した", "Abolished corrupt practices completely.", "Work & Business"),
    ("futou na koto wa yurushimasen", "ふとうなことはゆるしません", "フトウナコトワユルシマセン", "不当な事は許しません", "We will not tolerate unfair dealings.", "Work & Business"),
    ("fuzei no aru kofuu na machi", "ふぜいのあるこふうなまちだ", "フゼイノアルコフウナマチダ", "風情のある古風な街だ", "A historic town steeped in poetic antiquity.", "Travel & Places"),

    # G
    ("gai o komanukanai taisaku", "がいをこうむらないたいさく", "ガイヲコウムラナイタイサク", "対策を徹底する", "Taking airtight steps to prevent any harm.", "Safety & Health"),
    ("gakumon no tobira o hirako", "がくもんのとびらをひらこう", "ガクモンノトビラヲヒラコウ", "学問の扉を開こう", "Let's unlock the grand doors of learning.", "Classroom & Study"),
    ("ganban no you ni yuruganai", "がんばんのようにゆるがない", "ガンバンノヨウニユルガナイ", "岩盤のように揺るがない", "Unshakeable as bedrock in earthquake.", "Cheering & Motivation"),
    ("ganjou na kutsu de arukou", "がんじょうなくつであるこう", "ガンジョウナクツデアルコウ", "頑丈な靴で歩こう", "Let's hike in stout rugged boots.", "Travel & Places"),
    ("gara no yoi koto o shiyou", "がらのよいことをしよう", "ガラノヨイコトヲシヨウ", "品のある振る舞いをしよう", "Let's conduct ourselves with dignity.", "Communication"),
    ("geijutsu no honshitsu o saguro", "げいじゅつのほんしつをさぐろう", "ゲイジュツノホンシツヲサグロウ", "本質を探ろう", "Exploring the true essence of artistry.", "Culture"),
    ("genba no rikai o fukameru", "げんばのりかいをふかめる", "ゲンバノリカイヲフカメル", "理解を深める", "Deepening understanding of frontline reality.", "Work & Business"),
    ("genkaku na taisei de nozomo", "げんかくなたいせいでのぞもう", "ゲンカクナタイセイデノゾモウ", "厳格な態勢で臨もう", "Let's approach with rigorous vigilance.", "Work & Business"),
    ("genmitsu na suuchi o dashita", "げんみつなすうちをだした", "ゲンミツナスウチヲダシタ", "厳密な数値を算出した", "Derived precise, exact numerical metrics.", "Classroom & Study"),
    ("genshou no oto ni tsutsumare", "げんそうのおとにつつまれて", "ゲンソウノオトニツツマレテ", "幻想的な音に包まれて", "Enveloped by mystical ambient music.", "Culture"),
    ("gikochinai egao mo suki", "ぎこちないえがおもすきだよ", "ギコチナイエガオモスキダヨ", "ぎこちない笑顔も好きだよ", "Even your shy awkward smile is lovely!", "Friends & Social"),
    ("gouin na susumekata wa haishi", "ごういんなすすめかたははいし", "ゴウインナススメカタワハイシ", "強引な進め方はしない", "We refrain from bullying or coercion.", "Communication"),
    ("gouka na bafe o tanoshimou", "ごうかなばっふぇをたのしもう", "ゴウカナバッフェヲタノシモウ", "ビュッフェを楽しもう", "Let's enjoy the lavish luxury buffet!", "Dining"),
    ("goutei no niwa ga kirei da", "ごうていのにわがきれいだね", "ゴウテイノニワガキレイダネ", "豪邸の庭が綺麗だね", "The mansion's landscaped garden is stunning.", "Travel & Places"),

    # H
    ("haigo o shinjite yudane-yo", "はいごをしんじてゆだねよう", "ハイゴヲシンジテユダネヨウ", "背後を信じて委ねよう", "Trusting my comrades to guard my back.", "Friends & Social"),
    ("hakarishirenai yume o idako", "はかりしれないゆめをいだこう", "ハカリシレナイユメヲイダコウ", "計り知れない夢を抱こう", "Let's harbor boundless, daring dreams!", "Cheering & Motivation"),
    ("hakken no kando o tsutaeyo", "はっけんのかんどうをつたえよう", "ハッケンノカンドウヲツタエヨウ", "発見の感動を伝えよう", "Sharing the thrill of eureka breakthroughs.", "Classroom & Study"),
    ("hakuryoku man-ten no ensou da", "はくりょくまんてんのえんそうだ", "ハクリョクマンテンノエンソウダ", "迫力満点の演奏だ", "An overwhelmingly thrilling performance!", "Culture"),
    ("hamigaki de sukkiri asa", "はみがきですっきりあさ", "ハミガキデスッキリアサ", "歯磨きですっきり朝を迎えよう", "Greet the morning refreshed after brushing.", "Daily Life"),
    ("hanayaka na machi o aruita", "はなやかなまちをあるいた", "ハナヤカナマチヲアルイタ", "華やかな街を歩いた", "Strolled through glittering, festive streets.", "Travel & Places"),
    ("hantsuki no kikan ga owatta", "はんつきのきかんがおわった", "ハンツキノキカンガオワッタ", "半月の期間が終わった", "The two-week interim period has ended.", "Work & Business"),
    ("haritsumeta ito o yurume-yo", "はりつめたいとをゆるめよう", "ハリツメタイトヲユルメヨウ", "糸を緩めよう", "Let's ease the taut nervous strain.", "Empathy & Comfort"),
    ("hassei o yosoku shite fusegu", "はっせいをよそくしてふせぐ", "ハッセイヲヨソクシテフセグ", "先回りして予防する", "Forecasting risks and curbing them early.", "Work & Business"),
    ("hatten no saki ni aru mirai", "はってんのさきにあるみらい", "ハッテンノサキニアルミライ", "発展の先にある未来", "The bright future waiting beyond progress.", "Cheering & Motivation"),
    ("heibon na kurashi o aisuru", "へいぼんなくらしをあいする", "ヘイボンナクラシヲアイスル", "平凡な暮らしを愛する", "Loving the sweet peace of simple living.", "Daily Life"),
    ("heisateki na basho o kaizen", "へいさてきなばしょをかいぜん", "ヘイサテキナバショヲカイゼン", "改善しよう", "Improving enclosed spaces for better flow.", "Home & Living"),
    ("hendou o norikoeru tetsujin", "へんどうをのりこえるつよさ", "ヘンドウヲノリコエルツヨサ", "乗り越える強さ", "The fortitude to weather sudden swings.", "Cheering & Motivation"),
    ("hidoku omoi-dashite namida", "ひどくおもいだしてなみだ", "ヒドクオモイダシテナミダ", "思い出して涙が出た", "Recalling that memory brought sweet tears.", "Empathy & Comfort"),
    ("hifu no uruoi o tamotsu", "ひふのうるおいをたもつ", "ヒフノウルオイヲタモツ", "肌の潤いを保つ", "Preserving skin's radiant hydration.", "Daily Life"),
    ("hikaku shite yosa o mitsukeyo", "ひかくしてよさをみつけよう", "ヒカクシテヨサヲミツケヨウ", "比較して良さを見つけよう", "Comparing to discover unique merits.", "Classroom & Study"),
    ("hikkuri-kaette mo mata tatsu", "ひっくりかえってもまたたつ", "ヒックリカエッテモマタタツ", "倒れてもまた立ち上がる", "Tumble down, yet rise up once again!", "Cheering & Motivation"),
    ("hisshi de hashitta omoide", "ひっしではしったおもいでだ", "ヒッシデハシッタオモイデダ", "必死で走った思い出だ", "A cherished memory of running flat out.", "Friends & Social"),
    ("hitasura shinjita doryoku", "ひたすらしんじたどりょくだ", "ヒタスラシンジタドリョクダ", "ひたすら信じた努力だ", "Effort born of single-minded unwavering faith.", "Cheering & Motivation"),
    ("hitori-bocchi de nakanaide", "ひとりぼっちでなかないで", "ヒトリボッチデナカナイデ", "一人ぼっちで泣かないで", "Don't weep in lonely isolation!", "Empathy & Comfort"),
    ("hokorashiku tachi-mukau zo", "ほこらしくたちむかうぞ", "ホコラシクタチムカウゾ", "誇らしく立ち向かうぞ", "Facing up to the challenge with head high!", "Cheering & Motivation"),
    ("honki no koe ga todoku", "ほんきのこえがとどくよ", "ホンキノコエガトドクヨ", "本気の声が届くよ", "Your sincere heartfelt plea will be heard.", "Communication"),
    ("honmono no uta ni yotteru", "ほんもののうたによっている", "ホンモノノウタニヨッテイル", "本物の歌に酔いしれる", "Intoxicated by the sublime authentic vocals.", "Culture"),
    ("horonigai omoide mo kate da", "ほろにがいおもでもかてだ", "ホロニガイオモイデモカテダ", "ほろ苦い思い出も糧になる", "Bittersweet memories nourish the soul.", "Empathy & Comfort"),
    ("hoshuteki na gawa no iken", "ほしゅてきながわのいけん", "ホシュテキナガワノイケン", "保守的な側の意見も大切だ", "Traditionalist perspectives carry weight too.", "Communication"),
    ("hyoujou-yutaka ni hohoemou", "ひょうじょうゆたかにほほえもう", "ヒョウジョウユタカニホホエモウ", "表情豊かに微笑もう", "Let's beam with expressive, joyful eyes.", "Communication"),
]
