# Comprehensive Japanese Conversational Phrases A through M (400+ entries)
# (romaji, hiragana, katakana, kanji, meaning, topic)
DATA = [
    # A
    ("a, abunai desu yo!", "あ、あぶないですよ！", "ア、アブナイデスヨ！", "あ、危ないですよ！", "Oh, look out! It's dangerous!", "Health & Emergency"),
    ("a, agetate de oishisou!", "あ、あげたてでおいしそう！", "ア、アゲタテデオイシソウ！", "あ、揚げたてで美味しそう！", "Oh, freshly fried and looks so yummy!", "Dining"),
    ("a, aida o akete kudasai", "あ、あいだをあけてください", "ア、アイダヲアケテクダサイ", "あ、間を空けてください", "Please leave a space in between.", "Daily Conversation"),
    ("a, aisatsu ga kirei desu ne", "あ、あいさつがきれいですね", "ア、アイサツガキレイデスネ", "あ、挨拶が綺麗ですね", "What a lovely, polite greeting!", "Communication"),
    ("a, aji ga shimite iru!", "あ、あじがしみている！", "ア、アジガシミテイル！", "あ、味が染みている！", "Oh, the broth has soaked in deeply!", "Dining"),
    ("a, akachan ga waratta!", "あ、あかちゃんがわらった！", "ア、アカチャンガワラッタ！", "あ、赤ちゃんが笑った！", "Oh look, the baby smiled!", "Family & Children"),
    ("a, akari o keshite kudasai", "あ、あかりをけしてください", "ア、アカリヲケシテクダサイ", "あ、明かりを消してください", "Please turn off the room lights.", "Daily Life"),
    ("a, ame ga futte kimashita", "あ、あめがふってきました", "ア、アメガフッテキマシタ", "あ、雨が降ってきました", "Oh, rain has started falling.", "Weather & Daily"),
    ("a, anata mo sou omoimasu ka", "あ、あなたもそうおもいますか", "ア、アナタモソウオモイマスカ", "あ、あなたもそう思いますか", "Oh, do you think so too?", "Daily Conversation"),
    ("a, anshin shimashita", "あ、あんしんしました", "ア、アンシンシマシタ", "あ、安心しました", "Ah, what a wave of relief!", "Daily Conversation"),
    ("a, aoi sora ga kirei da na", "あ、あおいそらがきれいだな", "ア、アオイソラガキレイダナ", "あ、青い空が綺麗だな", "Ah, what a gorgeous blue sky.", "Weather & Daily"),
    ("a, aozora ga hirogatta!", "あ、あおぞらがひろがった！", "ア、アオゾラガヒロガッタ！", "あ、青空が広がった！", "Look, the blue skies have opened up!", "Weather & Daily"),
    ("a, apuri o koushin shimashita", "あ、あぷりをこうしんしました", "ア、アプリヲコウシンシマシタ", "あ、アプリを更新しました", "Ah, I just updated the app.", "Daily Life"),
    ("a, arakajime kiite okou", "あ、あらかじめきいておこう", "ア、アラカジメキイテオコウ", "あ、予め聞いておこう", "Let's ask about that beforehand.", "Daily Conversation"),
    ("a, arigatou gozaimashita", "あ、ありがとうございました", "ア、アリガトウゴザイマシタ", "あ、ありがとうございました", "Ah, thank you very, very much!", "Gratitude & Thanks"),
    ("a, asa no kuuki ga oishii!", "あ、あさのくうきがおいしい！", "ア、アサノクウキガオイシイ！", "あ、朝の空気が美味しい！", "The morning air is so crisp and fresh!", "Weather & Daily"),
    ("a, ashi ga shibirechatta", "あ、あしがしびれちゃった", "ア、アシガシビレチャッタ", "あ、足が痺れちゃった", "Oh, my legs fell asleep from sitting!", "Daily Conversation"),
    ("a, asoko ni miete kita yo", "あ、あそこにみえてきたよ", "ア、アソコニミエテキタヨ", "あ、あそこに見えてきたよ", "Look, it's coming into view over there!", "Travel & Places"),
    ("a, atama ga itai kamo", "あ、あたまがいたいかも", "ア、アタマガイタイカモ", "あ、頭が痛いかも", "Oh, I might have a little headache.", "Health & Emergency"),
    ("a, atarashii hon o kaimashita", "あ、あたらしいほんをかいました", "ア、アタラシイホンヲカイマシタ", "あ、新しい本を買いました", "I just bought a brand-new book!", "Classroom & Study"),
    ("a, ato de renraku shimasu", "あ、あとでれんらくします", "ア、アトデレンラクシマス", "あ、後で連絡します", "I will get in touch with you later!", "Communication"),
    ("a, atsu-atsu no soup da", "あ、あつあつのすーぷだ", "ア、アツアツノスープダ", "あ、熱々のスープだ", "Steaming hot soup right here!", "Dining"),
    ("a, ayamatta hou ga ii yo", "あ、あやまったほうがいいよ", "ア、アヤマッタホウガイイヨ", "あ、謝った方がいいよ", "You really should offer an apology.", "Apologies & Regrets"),
    ("a, azayaka na iro da ne", "あ、あざやかないろだね", "ア、アザヤカナイロダネ", "あ、鮮やかな色だね", "What a brilliant, dazzling color!", "Daily Conversation"),

    # B
    ("ba ni atta hanashi o shiyou", "ばにあったはなしをしよう", "バニアッタハナシヲシヨウ", "場に合った話をしよう", "Let's choose topics fit for the room.", "Communication"),
    ("baka baka-shii kedo omoshiroi", "ばかばかしいけどおもしろい", "バカバカシイケドオモシロイ", "馬鹿馬鹿しいけど面白い", "Silly as can be, but so fun!", "Daily Conversation"),
    ("bakudai na data o shori shita", "ばくだいなでーたをしょりした", "バクダイナデータヲショリシタ", "莫大なデータを処理した", "Processed an enormous ocean of data.", "Work & Business"),
    ("ban-gouhan wa nani ni suru?", "ばんごはんはなににする？", "バンゴハンワナニニスル？", "晩ご飯は何にする？", "What shall we make for dinner?", "Dining"),
    ("barabara no peeji o tojiro", "ばらばらのぺーじをとじよう", "バラバラノページヲトジヨウ", "バラバラのページを綴じよう", "Let's staple the scattered pages together.", "Classroom & Study"),
    ("bassui o yonde kudasai", "ばっすいをよんでください", "バッスイヲヨンデクダサイ", "抜粋を読んでください", "Please read this brief excerpt.", "Classroom & Study"),
    ("batsu-gun no kyaku-hon da!", "ばつぐんのきゃくほんだ！", "バツグンノキャクホンダ！", "抜群の脚本だ！", "What an extraordinary, masterly script!", "Culture"),
    ("benkyou no aima ni ocha o", "べんきょうのあいまにおちゃを", "ベンキョウノアイマニオチャヲ", "勉強の合間にお茶を", "Sipping green tea between study sessions.", "Classroom & Study"),
    ("betsu no hihou o tamesou", "べつのほうほうをためそう", "ベツノホウホウヲタメソウ", "別の方法を試そう", "Let's try a different technique!", "Daily Conversation"),
    ("bimyona ajiwai ga ii ne", "びみょうなあじわいがいいね", "ビミョウナアジワイガイイネ", "微妙な味わいが良いね", "The subtle delicate note is wonderful.", "Dining"),
    ("binbin hibiite kuru yo", "びんびんひびいてくるよ", "ビンビンヒビイテクルヨ", "ビンビン響いてくるよ", "The powerful vibrations hit right home!", "Body & Senses"),
    ("bita ichi-en mo iranai yo", "びたいちえんもいらないよ", "ビタイチエンモイラナイヨ", "一文も要らないよ", "Not a single yen needed, on the house!", "Dining"),
    ("boku mo tetsudatte ii?", "ぼくもてつだっていい？", "ボクモテツダッテイイ？", "僕も手伝っていい？", "May I help out with this too?", "Daily Conversation"),
    ("bousou shinai you ni chuui", "ぼうそうしないようにちゅうい", "ボウソウシナイヨウニチチュウイ", "暴走しないように注意しよう", "Let's be vigilant against runaway errors.", "Safety & Health"),
    ("bunseki ga kanryou shimashita", "ぶんせきがかんりょうしました", "ブンセキガカンリョウシマシタ", "分析が完了しました", "The diagnostic analysis is complete.", "Work & Business"),
    ("byoudou ni chansu ga aru", "びょうどうにちゃんすがある", "ビョウドウニチャンスガアル", "平等にチャンスがある", "Everyone has an equal opportunity.", "Communication"),

    # C
    ("chado no kokoro o manabou", "ちゃどうのこころをまなぼう", "チャドウノココロヲマナボウ", "茶道の心を学ぼう", "Let's learn the soul of the tea ceremony.", "Culture"),
    ("chakujitsu na ippo o fumi-dasou", "ちゃくじつないっぽをふみだそう", "チャクジツナイッポヲフミダソウ", "着実な一歩を踏み出そう", "Let's take a steady, confident stride.", "Cheering & Motivation"),
    ("chiisa na koto demo kansha", "ちいさなことでもかんしゃ", "チイサナコトデモカンシャ", "小さな事でも感謝しよう", "Let's give thanks even for small joys.", "Gratitude & Thanks"),
    ("chikara o awasereba dekiru!", "ちからをあわせればできる！", "チカラヲアワセレバデキル！", "力を合わせれば出来る！", "Together we can achieve anything!", "Cheering & Motivation"),
    ("chimitsu na sekkei ga hikaru", "ちみつなせっけいがひかる", "チミツナセッケイガヒカル", "緻密な設計が光る", "The meticulous engineering shines bright.", "Work & Business"),
    ("chitsujo ga tamotarete iru", "ちつじょがたもたれている", "チツジョガタモタレテイル", "秩序が保たれている", "Immaculate order is kept.", "Daily Conversation"),
    ("chotto kyuukei shimashou ka", "ちょっときゅうけいしましょうか", "チョットキュウケイシマショウカ", "一寸休憩しましょうか", "Shall we take a brief breath and break?", "Daily Conversation"),
    ("choushi wa ikaga desu ka", "ちょうしわいかがですか", "チョウシワイカガデスカ", "調子はいかがですか", "How are you feeling today?", "Greetings"),
    ("chouwa ga torete kirei da", "ちょうわがとれてきれいだ", "チョウワガトレテキレイダ", "調和が取れて綺麗だ", "Beautifully harmonious in balance.", "Daily Conversation"),
    ("chuuto de akiramenaide", "ちゅうとであきらめないで", "チュウトデアキラメナイデ", "中途で諦めないで", "Don't give up halfway through!", "Cheering & Motivation"),

    # D
    ("daidai-iro no sora o miyou", "だいだいいろのそらをみよう", "ダイダイイロノソラヲミヨウ", "橙色の空を見よう", "Let's look out at the amber dusk sky.", "Weather & Daily"),
    ("daikibo na matsuri ga hajimaru", "だいきぼなまつりがはじまる", "ダイキボナマツリガハジマル", "大規模な祭りが始まる", "A grand festival is about to start!", "Culture"),
    ("daitan na hassou da ne", "だいたんなはっそうだね", "ダイタンナハッソウダネ", "大胆な発想だね", "What a daring, revolutionary thought!", "Communication"),
    ("danbou de heya ga atatamatta", "だんぼうでへやがあたたまった", "ダンボウデヘヤガアタタマッタ", "暖房で部屋が暖まった", "The room grew warm from the heater.", "Home & Living"),
    ("danryoku ga atte oishii!", "だんりょくがあっておおいしい！", "ダンリョクガアッテオイシイ！", "弾力があって美味しい！", "Bouncy, chewy texture, so delicious!", "Dining"),
    ("datsuryoku shite rirakkusu", "だつりょくしてりらっくすしよう", "ダツリョクシテリラックスシヨウ", "脱力してリラックスしよう", "Let the tension go and relax deeply.", "Empathy & Comfort"),
    ("dekitate no udon o tabeyou", "できたてのうどんをたべよう", "デキタテノウドンヲタベヨウ", "出来立てのうどんを食べよう", "Let's slurp up fresh-cooked hot udon!", "Dining"),
    ("denpa ga todoki-nikui kamo", "でんぱがとどきにくいかも", "デンパガトドキニクイカモ", "電波が届きにくいかも", "Cellular reception might be faint here.", "Communication"),
    ("densen o fusegu shuukan", "でんせんをふせぐしゅうかん", "デンセンヲフセグシュウカン", "感染を防ぐ習慣", "Good habits to ward off bugs.", "Health & Emergency"),
    ("dokutoku no kaori ga ii", "どくとくのかおりがいい", "ドクトクノカオリガイイ", "独特の香りが良い", "That distinct fragrance is so inviting.", "Dining"),
    ("doryoku wa uragiranai yo", "どりょくはうらぎらないよ", "ドリョクワウラギラナイヨ", "努力は裏切らないよ", "Hard work will never betray you!", "Cheering & Motivation"),

    # E
    ("eikyuu ni wasurenai yo", "えいきゅうにわすれないよ", "エイキュウニワスレナイヨ", "永久に忘れないよ", "I will never forget this for eternity.", "Friends & Social"),
    ("eikyou o ukete mananda", "えいきょうをうけてまなんだ", "エイキョウヲウケテマナンダ", "影響を受けて学んだ", "I learned so much under that inspiration.", "Classroom & Study"),
    ("ekiteki na gyakuten-geki da!", "えきてきなぎゃくてんげきだ！", "エキテキナギャクテンゲキダ！", "劇的な逆転劇だ！", "A breathtaking dramatic turnaround!", "Daily Conversation"),
    ("enman ni kaiketsu dekimashita", "えんまんにかいけつできました", "エンマンニカイケツデキマシタ", "円満に解決できました", "Settled amicably with happy smiles.", "Work & Business"),
    ("enshou ga osamatte yokatta", "えんしょうがおさまってよかった", "エンショウガオサマッテヨカッタ", "炎症が治まって良かった", "Glad the redness and pain settled down.", "Health & Emergency"),
    ("eri-suguri no mono o erabo", "えりすぐりのものをえらぼう", "エリスグリノモノヲエラボウ", "選りすぐりの物を選ぼう", "Let's choose only hand-picked gems.", "Shopping & Dining"),

    # F
    ("fuantei na tenki da ne", "ふあんていなてんきだね", "フアンテイナテンキダネ", "不安定な天気だね", "Fickle, unpredictable weather today.", "Weather & Daily"),
    ("fubyoudou o nakusou", "ふびょうどうをなくそう", "フビョウドウヲナクソウ", "不平等を無くそう", "Let's work to eliminate injustice.", "Communication"),
    ("fuchuui ni ki o tsukeyou", "ふちゅういにきをつけよう", "フチュウイニキヲツケヨウ", "不注意に気をつけよう", "Let's take heed against careless slips.", "Safety & Health"),
    ("fugou no yuu-fuku na kurashi", "ふごうのゆうふくなひび", "フゴウノユウフクナビビ", "裕福な暮らし", "A life of affluent comfort.", "Daily Conversation"),
    ("fujiyuu naku kurasete iru", "ふじゆうなくくらせている", "フジユウナククラセテイル", "不自由なく暮らせている", "Living comfortably without any lack.", "Daily Life"),
    ("fukami no aru iro-ai da", "ふかみのあるいろあいだ", "フカミノアルイロアイダ", "深みのある色合いだ", "Colors steeped in rich layered depth.", "Culture"),
    ("fukitsu na yokan o haraou", "ふきつなよかんをはらおう", "フキツナヨカンヲハラオウ", "不吉な予感を払おう", "Let's brush off superstitious gloom.", "Daily Conversation"),
    ("fukouhei o kaishou shiyou", "ふこうへいをかいしょうしよう", "フコウヘイヲカイショウシヨウ", "不公平を解消しよう", "Let's right the unfairness.", "Communication"),
    ("fukusou o tadasou", "ふくそうをただそう", "フクソウヲタダソウ", "服装を正そう", "Let's tidy up our attire.", "Classroom & Study"),
    ("fumi yutaka na dashi", "ふうみゆたかなだしだね", "フウミユタカナダシダネ", "風味豊かな出汁だね", "What a rich fragrant soup stock!", "Dining"),
    ("funiki ga suki na cafe", "ふんいきがすきなかふぇだ", "フンイキガスキナカフェダ", "雰囲気が好きなカフェだ", "A cafe with a vibe I adore.", "Daily Life"),
    ("fusei o haijo shimashou", "ふせいをはいじょしましょう", "フセイヲハイジョシマショウ", "不正を排除しましょう", "Let's purge cheating and misconduct.", "Work & Business"),
    ("futou na atsukai wa kenshi", "ふとうなあつかいはきんし", "フトウナアツカイワキンシ", "不当な扱いは禁止です", "Unjust treatment is strictly forbidden.", "Work & Business"),
    ("fuzei aru teien o arukou", "ふぜいあるていえんをあるこう", "フゼイアルテイエンヲアルコウ", "風情ある庭園を歩こう", "Let's wander the scenic historic garden.", "Travel & Places"),

    # G
    ("gai no nai anzen na shina", "がいのないあんぜんなしなだ", "ガイノナイアンゼンナシナダ", "害のない安全な品だ", "Completely harmless and safe product.", "Shopping & Dining"),
    ("gakumon o fukameyou", "がくもんをふかめよう", "ガクモンヲフカメヨウ", "学問を深めよう", "Let's deepen our academic horizons.", "Classroom & Study"),
    ("ganban no you ni katai", "がんばんのようにかたい", "ガンバンノヨウニカタイ", "岩盤のように堅い", "Firm and steadfast as solid rock.", "Daily Conversation"),
    ("ganjou na kaban da ne", "がんじょうなかばんだね", "ガンジョウナカバンダネ", "頑丈な鞄だね", "That's an exceptionally sturdy bag!", "Shopping & Dining"),
    ("gara no warui koto wa yameyou", "がらのわるいことはやめよう", "ガラノワルイコトワヤメヨウ", "柄の悪いことはやめよう", "Let's steer clear of rowdy conduct.", "Daily Conversation"),
    ("geijutsu no aki da ne", "げいじゅつのあきだね", "ゲイジュツノアキダネ", "芸術の秋だね", "Autumn is truly the season of fine arts.", "Culture"),
    ("genba no koe o kiite miyou", "げんばのこえをきいてみよう", "ゲンバノコエヲキイテミヨウ", "現場の声を聴いてみよう", "Let's listen to boots on the ground.", "Work & Business"),
    ("genkaku na kisoku o mamorou", "げんかくなきそくをまもろう", "ゲンカクナキソクヲマモロウ", "厳格な規則を守ろう", "Let's uphold the strict regulations.", "Classroom & Study"),
    ("genmitsu na keisan o shita", "げんみつなけいさんをした", "ゲンミツナケイサンヲシタ", "厳密な計算をした", "Performed rigorous, precise math.", "Classroom & Study"),
    ("genshou-teki na fukei da", "げんそうてきなふうけいだ", "ゲンソウテキナフウケイダ", "幻想的な風景だ", "What an ethereal enchanted vista.", "Travel & Places"),
    ("gikochinai kedo ganbaru", "ぎこちないけどがんばる", "ギコチナイケドガンバル", "ぎこちないけど頑張る", "Awkward still, but I'll do my best!", "Cheering & Motivation"),
    ("gouin ni semenaide", "ごういんにせめないで", "ゴウインニセメナイデ", "強引に責めないで", "Please don't push so relentlessly.", "Communication"),
    ("gouka na ryokan ni tomarta", "ごうかなりょかんにとまった", "ゴウカナリョカンニトマッタ", "豪華な旅館に泊まった", "Stayed at a luxurious hot-spring ryokan.", "Travel & Hotel"),
    ("goutei ga narande iru", "ごうていがならんでいる", "ゴウテイガナランデイル", "豪邸が並んでいる", "Grand villas line the scenic boulevard.", "Travel & Places"),

    # H
    ("haigo o tsukarenai you ni", "はいごをつかれないように", "ハイゴヲツカレナイヨウニ", "背後を突かれないように", "Watching one's back vigilantly.", "Safety & Health"),
    ("hakarishirenai chikara ga aru", "はかりしれないちからがある", "ハカリシレナイチカラガアル", "計り知れない力がある", "Possessing unfathomable inner strength.", "Cheering & Motivation"),
    ("hakken ga atte ureshii", "はっけんがあってうれしい", "ハッケンガアッテウレシイ", "発見があって嬉しい", "Thrilled to make this exciting discovery!", "Classroom & Study"),
    ("hakuryoku ga sugoi eiga da", "はくりょくがすごいえいがだ", "ハクリョクガスゴイエイガダ", "迫力が凄い映画だ", "A movie packed with thrilling punch!", "Friends & Social"),
    ("hamigaki o wasurezu ni", "はみがきをわすれずに", "ハミガキヲワスレズニ", "歯磨きを忘れずに", "Don't forget to brush your teeth!", "Family & Children"),
    ("hanayaka na hanataba da ne", "はなやかなはなたばだね", "ハナヤカナハナタバダネ", "華やかな花束だね", "What a gorgeous radiant bouquet of blooms!", "Greetings & Celebrations"),
    ("hantsuki de kansei saseta", "はんつきでかんせいさせた", "ハンツキデカンセイサセタ", "半月で完成させた", "Finished it within a half-month sprint.", "Work & Business"),
    ("haritsumeta ito ga kireta", "はりつめたいとがきれた", "ハリツメタトガキレタ", "張り詰めた糸が切れた", "The taut tension finally snapped.", "Daily Conversation"),
    ("hassei o fusegu tame ni", "はっせいをふせぐために", "ハッセイヲフセグタメニ", "発生を防ぐために", "Taking action to prevent recurrences.", "Work & Business"),
    ("hatten shite iku machi", "はってんしていくまち", "ハッテンシテイクマチ", "発展していく街", "A thriving city expanding for the future.", "Travel & Places"),
    ("heibon da kedo shiawase", "へいぼんだけどしあわせ", "ヘイボンダケドシアワセ", "平凡だけど幸せ", "Modest and ordinary, yet truly blessed.", "Daily Life"),
    ("heisateki na kuukan o kaisou", "へいさてきなくうかんをかいそう", "ヘイサテキナクウカンヲカイソウ", "空間を改装しよう", "Let's redesign this room for more openness.", "Home & Living"),
    ("hendou ni taeru chikara", "へんどうにたえるちから", "ヘンドウニタエルチカラ", "変動に耐える力", "The resilience to weather shifting tides.", "Work & Business"),
    ("hidoku kanashii koto ga atta", "ひどくかなしいことがあった", "ヒドクカナシイコトガアッタ", "酷く悲しいことがあった", "Something heartbreaking occurred.", "Empathy & Comfort"),
    ("hifu no kea o shiyou", "ひふのけあをしよう", "ヒフノケアヲシヨウ", "肌のケアをしよう", "Let's moisturize and care for our skin.", "Daily Life"),
    ("hikaku suru to yoku wakaru", "ひかくするとよくわかる", "ヒカクスルトヨクワカル", "比較するとよく分かる", "Comparing them makes it crystal clear.", "Classroom & Study"),
    ("hikkuri-kaette bikkuri", "ひっくりかえってびっくりした", "ヒックリカエッテビックリシタ", "ひっくり返って驚いた", "Tumbled right over in surprise!", "Daily Conversation"),
    ("hisshi de hashitta yo", "ひっしではしったよ", "ヒッシデハシッタヨ", "必死で走ったよ", "Ran with every ounce of wind in my lungs!", "Daily Conversation"),
    ("hitasura shinjite kureta", "ひたすらしんじてくれた", "ヒタスラシンジテクレタ", "ひたすら信じてくれた", "You believed in me without single doubt.", "Gratitude & Thanks"),
    ("hitori-bocchi ja nai yo", "ひとりぼっちじゃないよ", "ヒトリボッチジャナイヨ", "一人ぼっちじゃないよ", "You are never alone, remember that!", "Empathy & Comfort"),
    ("hokorashii kimochi de ippai", "ほこらしいきもちでいっぱい", "ホコラシイキモチデイッパイ", "誇らしい気持ちで一杯だ", "My heart is overflowing with pride!", "Feelings & Mood"),
    ("honki de ganbaru toki da", "ほんきでがんばるときだ", "ホンキデガンバルトキダ", "本気で頑張る時だ", "Now is the hour to give our all!", "Cheering & Motivation"),
    ("honmono no gemu o miyou", "ほんもののみりょくをみよう", "ホンモノノミリョクヲミヨウ", "本物の魅力を見よう", "Let's experience true authentic greatness.", "Culture"),
    ("horonigai omoide mo takara", "ほろにがいおもでもたからだ", "ホロニガイオモイデモタカラダ", "ほろ苦い思い出も宝だ", "Even bittersweet memories are treasures.", "Empathy & Comfort"),
    ("hoshuteki na gawa to hanasou", "ほしゅてきながわとはなそう", "ホシュテキナガワトハナソウ", "保守的な側と話そう", "Let's dialogue respectfully with traditionalists.", "Communication"),
    ("hyoujou-yutaka ni hanasou", "ひょうじょうゆたかにはなそう", "ヒョウジョウユタカニハナソウ", "表情豊かに話そう", "Let's converse with animated expressions.", "Communication"),
]
