# Daily Actions, Cooking, Dining, Bodily Senses, Personal Routine verbs
# (romaji, hiragana, katakana, kanji, meaning, type, topic)
DATA = [
    # I
    ("ibiki o kaku", "いびきをかく", "イビキヲカク", "鼾をかく", "to snore while sleeping", "Godan", "Body & Actions"),
    ("ichidaiji to miru", "いちだいじとみる", "イチダイジトミル", "一大事と見る", "to view as great matter", "Ichidan", "Work & Study"),
    ("idou suru", "いどうする", "イドウスル", "移動する", "to relocate / migrate", "Suru Verb", "Actions & Movement"),
    ("ie o tateru", "いえをたてる", "イエヲタテル", "家を建てる", "to build a home house", "Ichidan", "Work & Study"),
    ("iidasu", "いいだす", "イイダス", "言い出す", "to break the ice / broach subject", "Godan", "Social & Communication"),
    ("iitsukeru", "いいつける", "イイツケル", "言い付ける", "to order / tell on someone", "Ichidan", "Social & Communication"),
    ("iitsutawaru", "いいつたわる", "イイツタワル", "言い伝わる", "to be handed down by oral tradition", "Godan", "Culture & Society"),
    ("iiwake o suru", "いいわけをする", "イイワケヲスル", "言い訳をする", "to make excuses", "Suru Verb", "Social & Communication"),
    ("ijimeru", "いじめる", "イジメル", "苛める", "to torment / bully", "Ichidan", "Social & Communication"),
    ("ijiru", "いじる", "イジル", "弄る", "to fiddle with / tinker", "Godan", "Actions & Movement"),
    ("ikasu", "いかす", "イカス", "生かす", "to keep alive / make best use of", "Godan", "Work & Study"),
    ("iken o iu", "いけんをいう", "イケンヲイウ", "意見を言う", "to voice one's opinion", "Godan", "Social & Communication"),
    ("ikiru", "いきる", "イキル", "生きる", "to live / exist / be alive", "Ichidan", "Nature & Animals"),
    ("ikitsuku", "いきつく", "イキツク", "行き着く", "to arrive at end destination", "Godan", "Movement & Travel"),
    ("iku", "いく", "イク", "行く", "to go / travel to", "Godan", "Movement & Travel"),
    ("inoru", "いのる", "イノル", "祈る", "to pray / wish well", "Godan", "Culture & Society"),
    ("inshou o ataeru", "いんしょうをあたえる", "インショウヲアタエル", "印象を与える", "to make an impression", "Ichidan", "Social & Communication"),
    ("ippuku suru", "いっぷくする", "イップクスル", "一服する", "to pause for tea / short rest", "Suru Verb", "Daily Actions"),
    ("irassharu", "いらっしゃる", "イラッシャルフ", "いらっしゃる", "to be / come / go (honorific)", "Godan", "Social & Communication"),
    ("ireru", "いれる", "イレル", "入れる", "to put into / pour tea", "Ichidan", "Daily Actions"),
    ("iradatsu", "いらだつ", "イラダツ", "苛立つ", "to get irritated / fret", "Godan", "Emotions & Mind"),
    ("iru", "いる", "イル", "居る", "to exist (animate beings)", "Ichidan", "Daily Actions"),
    ("iru-need", "いる", "イル", "要る", "to need / require", "Godan", "Daily Actions"),
    ("iru-roast", "いる", "イル", "炒る", "to roast beans / pan-fry seeds", "Godan", "Cooking & Dining"),
    ("isogu", "いそぐ", "イソグ", "急ぐ", "to hurry / hasten", "Godan", "Actions & Movement"),
    ("itamu", "いたむ", "イタム", "傷む", "to spoil (food) / be damaged", "Godan", "Nature & Weather"),
    ("itamu-pain", "いたむ", "イタム", "痛む", "to ache / feel pain", "Godan", "Body & Actions"),
    ("itawaru", "いたわる", "イタワル", "労る", "to treat kindly / comfort", "Godan", "Social & Communication"),
    ("itazura suru", "いたずらする", "イタズラスル", "悪戯する", "to play a practical joke", "Suru Verb", "Daily Actions"),
    ("itadaku", "いただく", "イタダク", "頂く", "to receive / eat humbly", "Godan", "Social & Communication"),
    ("itaru", "いたる", "イタル", "至る", "to lead to / reach climax", "Godan", "Movement & Travel"),
    ("iu", "いう", "イウ", "言う", "to say / speak word", "Godan", "Social & Communication"),
    ("iwau", "いわう", "イワウ", "祝う", "to celebrate / congratulate", "Godan", "Culture & Society"),
    # J
    ("jama o suru", "じゃまをする", "ジャマヲスル", "邪魔をする", "to hinder / get in the way", "Suru Verb", "Social & Communication"),
    ("jibun o shinjiru", "じぶんをしんじる", "ジブンヲシンジル", "自分を信じる", "to believe in oneself", "Ichidan", "Emotions & Mind"),
    ("jikan o kakeru", "じかんをかける", "ジカンヲカケル", "時間をかける", "to take ample time", "Ichidan", "Daily Actions"),
    ("jikkou suru", "じっこうする", "ジッコウスル", "実行する", "to put into practice", "Suru Verb", "Work & Study"),
    ("jiman suru", "じまんする", "ジマンスル", "自慢する", "to brag / show off with pride", "Suru Verb", "Social & Communication"),
    ("jimisen suru", "じみちにする", "ジミチニスル", "地道にする", "to persevere steadily", "Suru Verb", "Work & Study"),
    ("jinja ni mairu", "じんじゃにまいる", "ジンジャニマイル", "神社に参る", "to pay visit to Shinto shrine", "Godan", "Culture & Society"),
    ("jisshi suru", "じっしする", "ジッシスル", "実施する", "to enforce / implement policy", "Suru Verb", "Work & Study"),
    ("jitsugen suru", "じつげんする", "ジツゲンスル", "実現する", "to materialize / come true", "Suru Verb", "Work & Study"),
    ("jougo suru", "じょうごする", "ジョウゴスル", "漏斗する", "to pour through a funnel", "Suru Verb", "Cooking & Dining"),
    ("jouhou o eru", "じょうほうをえる", "ジョウホウヲエル", "情報を得る", "to obtain information", "Ichidan", "Work & Study"),
    ("joutatsu suru", "じょうたつする", "ジョウタツスル", "上達する", "to make progress / improve", "Suru Verb", "Work & Study"),
    ("junbi suru", "じゅんびする", "ジュンビスル", "準備する", "to prepare / set up", "Suru Verb", "Daily Actions"),
    ("juuden suru", "じゅうでんする", "ジュウデンスル", "充電する", "to charge battery", "Suru Verb", "Daily Actions"),
    # K
    ("kaeru", "かえる", "カエル", "帰る", "to return home", "Godan", "Movement & Travel"),
    ("kaeru-change", "かえる", "カエル", "変える", "to alter / change something", "Ichidan", "Daily Actions"),
    ("kaeru-exchange", "かえる", "カエル", "換える", "to exchange / swap", "Ichidan", "Shopping & Money"),
    ("kaesu", "かえす", "カエス", "返す", "to return borrowed item", "Godan", "Social & Communication"),
    ("kagaku suru", "かがくする", "カガクスル", "科学する", "to analyze scientifically", "Suru Verb", "Work & Study"),
    ("kagayaku", "かがやく", "カガヤク", "輝く", "to shine brilliantly / sparkle", "Godan", "Nature & Weather"),
    ("kagu", "かぐ", "カグ", "嗅ぐ", "to sniff scent / smell aroma", "Godan", "Perception & Senses"),
    ("kaita suru", "かいたくする", "カイタクスル", "開拓する", "to pioneer / open up land", "Suru Verb", "Work & Study"),
    ("kaizousuru", "かいぞうする", "カイゾウスル", "改造する", "to remodel / renovate", "Suru Verb", "Work & Study"),
    ("kakaeru", "かかえる", "カカエル", "抱える", "to hold in arms / face problem", "Ichidan", "Actions & Movement"),
    ("kakageru", "かかげる", "カカゲル", "掲げる", "to hoist flag / advocate motto", "Ichidan", "Actions & Movement"),
    ("kakaru", "かかる", "カカル", "掛かる", "to take (time/money) / hang", "Godan", "Daily Actions"),
    ("kakaseru", "かかせる", "カカセル", "欠かせる", "to let lack / miss out", "Ichidan", "Daily Actions"),
    ("kakawaru", "かかわる", "カカワル", "関わる", "to be involved with / affect", "Godan", "Social & Communication"),
    ("kakeru", "かける", "カケル", "掛ける", "to hang / sprinkle salt / call phone", "Ichidan", "Daily Actions"),
    ("kakeru-bet", "かける", "カケル", "賭ける", "to wager / stake one's life", "Ichidan", "Hobbies & Leisure"),
    ("kakeru-dash", "かける", "カケル", "駆ける", "to gallop / dash forward", "Ichidan", "Actions & Movement"),
    ("kaki-tomeru", "かきとめる", "カキトメル", "書き留める", "to jot down notes", "Ichidan", "Work & Study"),
    ("kaki-tsuzukeru", "かきつづける", "カキツヅケル", "書き続ける", "to continue writing", "Ichidan", "Work & Study"),
    ("kaku", "かく", "カク", "書く", "to write / compose text", "Godan", "Work & Study"),
    ("kaku-scratch", "かく", "カク", "掻く", "to scratch an itch", "Godan", "Body & Actions"),
    ("kaku-sweat", "かく", "カク", "汗をかく", "to perspire / sweat", "Godan", "Body & Actions"),
    ("kakureru", "かくれる", "カクレル", "隠れる", "to hide away / disappear", "Ichidan", "Actions & Movement"),
    ("kakusu", "かくす", "カクス", "隠す", "to conceal / cover up", "Godan", "Actions & Movement"),
    ("kamau", "かまう", "カマウ", "構う", "to care about / mind", "Godan", "Social & Communication"),
    ("kamikudaku", "かみくだく", "カミクダク", "噛み砕く", "to chew up / explain simply", "Godan", "Social & Communication"),
    ("kamu", "かむ", "カム", "噛む", "to bite / chew with teeth", "Godan", "Cooking & Dining"),
    ("kanaderu", "かなでる", "カナデル", "奏でる", "to play musical melody", "Ichidan", "Hobbies & Leisure"),
    ("kanau", "かなう", "カナウ", "叶う", "to come true (wish, dream)", "Godan", "Emotions & Mind"),
    ("kangaeru", "かんがえる", "カンガエル", "考える", "to ponder / consider deeply", "Ichidan", "Emotions & Mind"),
    ("kanjiru", "かんじる", "カンジル", "感じる", "to feel / sense emotion", "Ichidan", "Perception & Senses"),
    ("kankei suru", "かんけいする", "カンケイスル", "関係する", "to relate to / concern", "Suru Verb", "Social & Communication"),
    ("kansha suru", "かんしゃする", "カンシャスル", "感謝する", "to express profound thanks", "Suru Verb", "Social & Communication"),
    ("kanso suru", "かんそうする", "カンソウスル", "乾燥する", "to dry up / desiccate", "Suru Verb", "Nature & Weather"),
    ("karakarani naru", "からからになる", "カラカラニナル", "からからになる", "to become bone-dry / parched", "Godan", "Nature & Weather"),
    ("karakau", "からかう", "カラカウ", "揶揄う", "to tease / banter with", "Godan", "Social & Communication"),
    ("kariru", "かりる", "カリル", "借りる", "to borrow money / book", "Ichidan", "Daily Actions"),
    ("karu", "かる", "カル", "刈る", "to reap rice / mow lawn", "Godan", "Nature & Animals"),
    ("kasanaru", "かさなる", "カサナル", "重なる", "to pile up / coincide", "Godan", "Actions & Movement"),
    ("kasaneru", "かさねる", "カサネル", "重ねる", "to stack up / repeat efforts", "Ichidan", "Actions & Movement"),
    ("kasu", "かす", "カス", "貸す", "to lend out / loan", "Godan", "Social & Communication"),
    ("katazukeru", "かたづける", "カタヅケル", "片付ける", "to tidy up / put in order", "Ichidan", "Daily Actions"),
    ("katamaru", "かたまる", "カタマル", "固まる", "to harden / congeal", "Godan", "Actions & Movement"),
    ("katamukeru", "かたむける", "カタムケル", "傾ける", "to tilt / incline head", "Ichidan", "Actions & Movement"),
    ("katari-tsugu", "かたりつぐ", "カタリツグ", "語り継ぐ", "to pass on folklore tales", "Godan", "Culture & Society"),
    ("kataru", "かたる", "カタル", "語る", "to recount / narrate tale", "Godan", "Social & Communication"),
    ("katsu", "かつ", "カツ", "勝つ", "to win victory / triumph", "Godan", "Hobbies & Leisure"),
    ("kau", "かう", "カウ", "買う", "to purchase / buy at store", "Godan", "Shopping & Money"),
    ("kau-pet", "かう", "カウ", "飼う", "to keep / raise pet animal", "Godan", "Nature & Animals"),
    ("kawakasu", "かわかす", "カワカス", "乾かす", "to dry clothes / hair", "Godan", "Daily Actions"),
    ("kawaku", "かわく", "カワカク", "乾く", "to dry completely (intransitive)", "Godan", "Nature & Weather"),
    ("kawaku-throat", "かわく", "カワカク", "渇く", "to be thirsty (throat)", "Godan", "Body & Actions"),
    ("kayou", "かよう", "カヨウ", "通う", "to commute to school/work", "Godan", "Movement & Travel"),
    ("kazaru", "かざる", "カザル", "飾る", "to decorate with flowers", "Godan", "Home & Living"),
    ("kazoeru", "かぞえる", "カゾエル", "数える", "to count numbers", "Ichidan", "Work & Study"),
    ("keisan suru", "けいさんする", "ケイサンスル", "計算する", "to calculate sum", "Suru Verb", "Work & Study"),
    ("kenkyuu suru", "けんきゅうする", "ケンキュウスル", "研究する", "to research academic topic", "Suru Verb", "Work & Study"),
    ("kesshin suru", "けっしんする", "ケッシンスル", "決心する", "to resolve firmly", "Suru Verb", "Emotions & Mind"),
    ("kesu", "けす", "ケス", "消す", "to extinguish / turn off light", "Godan", "Daily Actions"),
    ("kibou suru", "きぼうする", "キボウスル", "希望する", "to hope for / desire", "Suru Verb", "Emotions & Mind"),
    ("kieru", "きえる", "キエル", "消える", "to vanish / go out (light)", "Ichidan", "Actions & Movement"),
    ("kigaeru", "きがえる", "キガエル", "着替える", "to change one's clothes", "Ichidan", "Daily Actions"),
    ("kikoeru", "きこえる", "キコエル", "聞こえる", "to be heard / audible", "Ichidan", "Perception & Senses"),
    ("kiku", "きく", "キク", "聞く", "to listen / hear / ask question", "Godan", "Perception & Senses"),
    ("kiku-effective", "きく", "キク", "利く", "to take effect (medicine)", "Godan", "Body & Actions"),
    ("kimaru", "きまる", "キマル", "決まる", "to be decided / settled", "Godan", "Daily Actions"),
    ("kimeru", "きめる", "キメル", "決める", "to make up mind / decide", "Ichidan", "Daily Actions"),
    ("kiru", "きる", "キル", "着る", "to put on / wear shirt", "Ichidan", "Daily Actions"),
    ("kiru-cut", "きる", "キル", "切る", "to cut with knife or scissors", "Godan", "Cooking & Dining"),
    ("kitsuku suru", "きつくする", "キツクスル", "きつくする", "to tighten belt / make strict", "Suru Verb", "Daily Actions"),
    ("kizuku", "きづく", "キヅク", "気付く", "to notice / become aware of", "Godan", "Emotions & Mind"),
    ("koboreru", "こぼれる", "コボレル", "零れる", "to spill out / overflow", "Ichidan", "Actions & Movement"),
    ("kobosu", "こぼす", "コボス", "零す", "to drop tears / spill coffee", "Godan", "Cooking & Dining"),
    ("koe o kakeru", "こえをかける", "コエヲカケル", "声をかける", "to call out to someone", "Ichidan", "Social & Communication"),
    ("kogeru", "こげる", "コゲル", "焦げる", "to burn / char (toast)", "Ichidan", "Cooking & Dining"),
    ("kogasu", "こがす", "コガス", "焦がす", "to scorch / burn food", "Godan", "Cooking & Dining"),
    ("kogu", "こぐ", "コグ", "漕ぐ", "to pedal bicycle / row boat", "Godan", "Actions & Movement"),
    ("koko ni kuru", "ここにくる", "ココニクル", "ここに来る", "to come here", "Irregular", "Movement & Travel"),
    ("kokeru", "こける", "コケル", "転ける", "to trip and tumble over", "Ichidan", "Actions & Movement"),
    ("kokoroeru", "こころえる", "ココロエル", "心得る", "to understand deeply / be versed in", "Ichidan", "Work & Study"),
    ("komaru", "こまる", "コマル", "困る", "to be troubled / at a loss", "Godan", "Emotions & Mind"),
    ("komu", "こむ", "コム", "混む", "to become crowded with people", "Godan", "Movement & Travel"),
    ("korobu", "ころぶ", "コロブ", "転ぶ", "to fall down / roll over", "Godan", "Actions & Movement"),
    ("korosu", "ころす", "コロス", "殺す", "to slay / kill pest", "Godan", "Actions & Movement"),
    ("kosuru", "こする", "コスル", "擦る", "to rub eyes / scrub surface", "Godan", "Daily Actions"),
    ("kotaeru", "こたえる", "コタエル", "答える", "to answer question / respond", "Ichidan", "Social & Communication"),
    ("kotowaru", "ことわる", "コトワル", "断る", "to refuse / decline invitation", "Godan", "Social & Communication"),
    ("koukan suru", "こうかんする", "コウカンスル", "交換する", "to trade / exchange goods", "Suru Verb", "Shopping & Money"),
    ("kouru", "こおる", "コオル", "凍る", "to freeze solid into ice", "Godan", "Nature & Weather"),
    ("kowagaraseru", "こわがらせる", "コワガラセル", "怖がらせる", "to scare / frighten someone", "Ichidan", "Emotions & Mind"),
    ("kowagaru", "こわがる", "コワガル", "怖がる", "to be afraid of / dread", "Godan", "Emotions & Mind"),
    ("kowareru", "こわれる", "コワレル", "壊れる", "to break down / shatter", "Ichidan", "Daily Actions"),
    ("kowasu", "こわす", "コワス", "壊す", "to break / demolish / ruin", "Godan", "Daily Actions"),
    ("kudaru", "くだる", "クダル", "下る", "to descend mountain / go down", "Godan", "Movement & Travel"),
    ("kudakeru", "くだける", "クダケル", "砕ける", "to smash into fragments", "Ichidan", "Actions & Movement"),
    ("kudaku", "くだく", "クダク", "砕く", "to crush ice / grind into bits", "Godan", "Cooking & Dining"),
    ("kufuu suru", "くふうする", "クフウスル", "工夫する", "to devise ingenious scheme", "Suru Verb", "Work & Study"),
    ("kumu", "くむ", "クム", "組む", "to braid / partner up / cross legs", "Godan", "Actions & Movement"),
    ("kumu-draw", "くむ", "クム", "汲む", "to draw water from well", "Godan", "Daily Actions"),
    ("kuraberu", "くらべる", "クラベル", "比べる", "to compare side by side", "Ichidan", "Work & Study"),
    ("kurasu", "くらす", "クラス", "暮らす", "to make one's living / dwell", "Godan", "Daily Actions"),
    ("kureru", "くれる", "クレル", "暮れる", "to grow dark / year to end", "Ichidan", "Time & Calendar"),
    ("kureru-give", "くれる", "クレル", "くれる", "to give to me (benefactive)", "Ichidan", "Social & Communication"),
    ("kurikaesu", "くりかえす", "クリカエス", "繰り返す", "to repeat over again", "Godan", "Work & Study"),
    ("kuru", "くる", "クル", "来る", "to come / approach", "Irregular", "Movement & Travel"),
    ("kurushimu", "くるしむ", "クルシム", "苦しむ", "to suffer / agonize over", "Godan", "Emotions & Mind"),
    ("kusaru", "くさる", "クサル", "腐る", "to rot / go bad / spoil", "Godan", "Nature & Animals"),
    ("kusuguru", "くすぐる", "クスグル", "擽る", "to tickle someone", "Godan", "Daily Actions"),
    ("kutsurogu", "くつろぐ", "クツログ", "寛ぐ", "to relax comfortably at home", "Godan", "Daily Actions"),
    ("kuwaeru", "くわえる", "クワエル", "加える", "to add ingredient / append", "Ichidan", "Cooking & Dining"),
    ("kuwaeru-mouth", "くわえる", "クワエル", "銜える", "to hold in mouth / clench pipe", "Ichidan", "Body & Actions"),
    ("kuwawaru", "くわわる", "クワワル", "加わる", "to join group / participate", "Godan", "Social & Communication"),
    ("kyoka suru", "きょかする", "キョカスル", "許可する", "to grant permission", "Suru Verb", "Social & Communication"),
    ("kyousou suru", "きょうそうする", "キョウソウスル", "競争する", "to compete in contest", "Suru Verb", "Hobbies & Leisure")
]
