# High-quality JLPT Compound & Core Japanese Verbs
DATA = [
    # Prefix: Tori- (Taking / Handling)
    ("toriageru", "とりあげる", "トリアゲル", "取り上げる", "to pick up / adopt proposal", "Ichidan", "Social & Communication"),
    ("toriatsukau", "とりあつかう", "トリアツカウ", "取り扱う", "to handle goods / treat topic", "Godan", "Work & Study"),
    ("toridasu", "とりだす", "トリダス", "取り出す", "to take out from drawer", "Godan", "Daily Actions"),
    ("torigawari suru", "とりかわりする", "トリカワリスル", "取り替わりする", "to take turns / substitute", "Suru Verb", "Social & Communication"),
    ("torikaeru", "とりかえる", "トリカエル", "取り替える", "to exchange / replace part", "Ichidan", "Daily Actions"),
    ("torikesu", "とりけす", "トリケス", "取り消す", "to cancel reservation / revoke", "Godan", "Social & Communication"),
    ("torikomu", "とりこむ", "トリコム", "取り込む", "to take in laundry / capture", "Godan", "Daily Actions"),
    ("torimodai", "とりもどす", "トリモドス", "取り戻す", "to regain / recover lost time", "Godan", "Actions & Movement"),
    ("torinokosu", "とりのこす", "トリノコス", "取り残す", "to leave behind / abandon", "Godan", "Actions & Movement"),
    ("toriosameru", "とりおさめる", "トリオサメル", "取り納める", "to accept payment / harvest", "Ichidan", "Shopping & Money"),
    ("torisaru", "とりさる", "トリサル", "取り去る", "to remove / clear away", "Godan", "Daily Actions"),
    ("torishimaru", "とりしまる", "トリシマル", "取り締まる", "to crack down on / oversee", "Godan", "Social & Communication"),
    ("torisugiru", "とりすぎる", "トリスギル", "取り過ぎる", "to take excessively", "Ichidan", "Daily Actions"),
    ("toritsukeru", "とりつける", "トリツケル", "取り付ける", "to install fixture / negotiate", "Ichidan", "Work & Study"),
    ("toriyoseru", "とりよせる", "トリヨセル", "取り寄せ", "to order in goods from afar", "Ichidan", "Shopping & Money"),
    # Prefix: Hiki- (Pulling / Drawing)
    ("hikiageru", "ひきあげる", "ヒキアゲル", "引き上げる", "to pull up / raise prices", "Ichidan", "Shopping & Money"),
    ("hikidasu", "ひきだす", "ヒキダス", "引き出す", "to withdraw cash / bring out talent", "Godan", "Shopping & Money"),
    ("hikikaesu", "ひきかえす", "ヒキカエス", "引き返す", "to turn back / retrace steps", "Godan", "Movement & Travel"),
    ("hikikomu", "ひきこむ", "ヒキコム", "引き込む", "to draw inside / drag into", "Godan", "Actions & Movement"),
    ("hikisageru", "ひきさげる", "ヒキサゲル", "引き下げる", "to lower prices / withdraw", "Ichidan", "Shopping & Money"),
    ("hikisaku", "ひきさく", "ヒキサク", "引き裂く", "to tear apart / rip asunder", "Godan", "Actions & Movement"),
    ("hikitateru", "ひきたてる", "ヒキタテル", "引き立てる", "to enhance flavor / favor pupil", "Ichidan", "Social & Communication"),
    ("hikitomeru", "ひきとめる", "ヒキトメル", "引き止める", "to detain / restrain friend", "Ichidan", "Social & Communication"),
    ("hikitsumuru", "ひきつめる", "ヒキツメル", "引き締める", "to tighten belt / discipline", "Ichidan", "Daily Actions"),
    ("hikiwake ni suru", "ひきわけにする", "ヒキワケニスル", "引き分けにする", "to end in a draw / tie", "Suru Verb", "Hobbies & Leisure"),
    ("hikiwatasu", "ひきわたす", "ヒキワタス", "引き渡す", "to hand over custody / surrender", "Godan", "Social & Communication"),
    # Prefix: Uke- (Receiving)
    ("ukedasu", "うけだす", "ウケダス", "受け出す", "to redeem pawn / bail out", "Godan", "Shopping & Money"),
    ("ukeireru", "うけいれる", "ウケイレル", "受け入れる", "to accept foreign students / adapt", "Ichidan", "Social & Communication"),
    ("ukemotsu", "うけもつ", "ウケモツ", "受け持つ", "to be in charge of class", "Godan", "Work & Study"),
    ("uketoru", "うけとる", "ウケトル", "受け取る", "to receive letter / interpret", "Godan", "Social & Communication"),
    ("uketsukeru", "うけつける", "ウケツケル", "受け付ける", "to accept applications", "Ichidan", "Work & Study"),
    ("uketsugu", "うけつぐ", "ウケツグ", "受け継ぐ", "to inherit family trade", "Godan", "People & Family"),
    ("ukeru", "うける", "ウケル", "受ける", "to catch ball / take exam / receive", "Ichidan", "Work & Study"),
    ("ukagau", "うかがう", "ウカガウ", "伺う", "to ask humbly / pay a visit", "Godan", "Social & Communication"),
    ("ukabu", "うかぶ", "ウカブ", "浮かぶ", "to float on water / idea to occur", "Godan", "Actions & Movement"),
    ("ukaberu", "うかべる", "ウカベル", "浮かべる", "to float a boat / show a smile", "Ichidan", "Emotions & Mind"),
    ("ukauka suru", "うかうかする", "ウカウカスル", "うかうかする", "to be daydreaming carelessly", "Suru Verb", "Daily Actions"),
    # Prefix: Oshi- (Pushing)
    ("oshiageru", "おしあげる", "オシアゲル", "押し上げる", "to push up / boost figures", "Ichidan", "Actions & Movement"),
    ("oshikakeru", "おしかける", "オシカケル", "押しかける", "to barge into home uninvited", "Ichidan", "Social & Communication"),
    ("oshikomu", "おしこむ", "オシコム", "押し込む", "to cram into suitcase", "Godan", "Actions & Movement"),
    ("oshitaosu", "おしたおす", "オシタオス", "押し倒す", "to shove down to ground", "Godan", "Actions & Movement"),
    ("oshitsukeru", "おしつける", "オシツケル", "押し付ける", "to press against / impose task", "Ichidan", "Social & Communication"),
    ("oshiyoseru", "おしよせる", "オシヨセル", "押し寄せる", "waves or crowds to surge forward", "Ichidan", "Actions & Movement"),
    # Prefix: Tachi- (Standing)
    ("tachiagaru", "たちあがる", "タチアガル", "立ち上がる", "to stand up / rise to feet", "Godan", "Actions & Movement"),
    ("tachidomaru", "たちどまる", "タチドマル", "立ち止まる", "to come to a halt and stand", "Godan", "Actions & Movement"),
    ("tachikaeru", "たちかえる", "タチカエル", "立ち返る", "to return to origin point", "Godan", "Work & Study"),
    ("tachisukumu", "たちすくむ", "タチスクム", "立ちすくむ", "to be petrified / rooted to spot", "Godan", "Emotions & Mind"),
    ("tachiyoru", "たちよる", "タチヨル", "立ち寄る", "to drop by convenience store", "Godan", "Movement & Travel"),
    ("tachifusagaru", "たちふさがる", "タチフサガル", "立ち塞がる", "to bar one's passage", "Godan", "Actions & Movement"),
    # Prefix: Mi- (Looking / Seeing)
    ("miageru", "みあげる", "ミアゲル", "見上げる", "to gaze up at starry sky", "Ichidan", "Perception & Senses"),
    ("miawaseru", "みあわせる", "ミアワセル", "見合わせる", "to look at each other / postpone", "Ichidan", "Social & Communication"),
    ("midasu", "みだす", "ミダス", "見出す", "to find out / discover meaning", "Godan", "Work & Study"),
    ("mihabaku", "みはる", "ミハル", "見張る", "to stand guard / open eyes wide", "Godan", "Daily Actions"),
    ("mihiraku", "みひらく", "ミヒラク", "見開く", "to open eyes wide in wonder", "Godan", "Perception & Senses"),
    ("mikakeru-spot", "みかける", "ミカケル", "見掛ける", "to catch a glimpse of", "Ichidan", "Perception & Senses"),
    ("mikomu", "みこむ", "ミコム", "見込む", "to anticipate / foresee potential", "Godan", "Work & Study"),
    ("mimi o katamukeru", "みみをかたむける", "ミミヲカタムケル", "耳を傾ける", "to lend an attentive ear", "Ichidan", "Social & Communication"),
    ("mimi ni suru", "みみにする", "ミミニスル", "耳にする", "to happen to hear", "Suru Verb", "Perception & Senses"),
    ("miokuru", "みおくる", "ミオクル", "見送る", "to see someone off at station", "Godan", "Social & Communication"),
    ("miorosu", "みおろす", "ミオロス", "見下ろす", "to overlook city from peak", "Godan", "Perception & Senses"),
    ("misadamaru", "みさだめる", "ミサダメ", "見定める", "to ascertain / judge carefully", "Ichidan", "Work & Study"),
    ("mitodosu", "みとどける", "ミトドケル", "見届ける", "to see through to very end", "Ichidan", "Social & Communication"),
    ("mitsumeru-gaze", "みつめる", "ミツメル", "凝視する", "to gaze steadily with affection", "Ichidan", "Emotions & Mind"),
    ("miwakeru", "みわける", "ミワケル", "見分ける", "to distinguish / tell apart", "Ichidan", "Perception & Senses"),
    ("miwatasu", "みわたす", "ミワタス", "見渡す", "to look far out over ocean", "Godan", "Perception & Senses"),
    # Suffix: -Dasu (Starting / Outward)
    ("aruki-dasu", "あるきだす", "アルキダス", "歩き出す", "to start walking forward", "Godan", "Actions & Movement"),
    ("hashiri-dasu", "はしりだす", "ハシリダス", "走り出す", "to burst into a sprint", "Godan", "Actions & Movement"),
    ("naki-dasu", "なきだす", "ナキダス", "泣き出す", "to burst into tears", "Godan", "Emotions & Mind"),
    ("warai-dasu", "わらいだす", "ワライダス", "笑い出す", "to burst out laughing", "Godan", "Emotions & Mind"),
    ("ame ga furi-dasu", "あめがふりだす", "アメガフリダス", "雨が降り出す", "rain to begin falling", "Godan", "Nature & Weather"),
    ("yuki ga furi-dasu", "ゆきがふりだす", "ユキガフリダス", "雪が降り出す", "snow to begin falling", "Godan", "Nature & Weather"),
    ("kaze ga fuki-dasu", "かぜがふきだす", "カゼガフキダス", "風が吹き出す", "wind to begin blowing", "Godan", "Nature & Weather"),
    ("oyogi-dasu", "およぎだす", "オヨギダス", "泳ぎ出す", "to begin swimming across", "Godan", "Hobbies & Leisure"),
    ("utai-dasu", "うたいだす", "ウタイダス", "歌い出す", "to break into song", "Godan", "Hobbies & Leisure"),
    ("odori-dasu", "おどりだす", "オドリダス", "踊り出す", "to start dancing with joy", "Godan", "Hobbies & Leisure"),
    ("sawagi-dasu", "さわぎだす", "サワギダス", "騒ぎ出す", "to begin making noise", "Godan", "Social & Communication"),
    ("ugoki-dasu", "うごきだす", "ウゴキダス", "動き出す", "to set into motion / stir", "Godan", "Actions & Movement"),
    ("tobi-dasu", "とびだす", "トビダス", "飛び出す", "to dart out into street", "Godan", "Actions & Movement"),
    ("nigedasu", "にげだす", "ニゲダス", "逃げ出す", "to take to one's heels / flee", "Godan", "Actions & Movement"),
    ("omoide-dasu", "おもいだす", "オモイダス", "思い出す", "to call back to memory", "Godan", "Emotions & Mind"),
    # Suffix: -Komu (Inward / Thoroughly)
    ("tobi-komu", "とびこむ", "トビコム", "飛び込む", "to dive headfirst into water", "Godan", "Actions & Movement"),
    ("hairi-komu", "はいりこむ", "ハイリコム", "入り込む", "to penetrate inside deep", "Godan", "Actions & Movement"),
    ("norikomu", "のりこむ", "ノリコム", "乗り込む", "to board express train", "Godan", "Movement & Travel"),
    ("ochi-komu", "おちこむ", "オチコム", "落ち込む", "to feel depressed / dip", "Godan", "Emotions & Mind"),
    ("kangaekomu", "かんがえこむ", "カンガエコム", "考え込む", "to be lost in deep thought", "Godan", "Emotions & Mind"),
    ("shinikomu", "しみこむ", "シミコム", "染み込む", "broth to soak into daikon", "Godan", "Cooking & Dining"),
    ("nemuri-komu", "ねむりこむ", "ネムリコム", "眠り込む", "to fall into profound slumber", "Godan", "Daily Actions"),
    ("tsume-komu", "つめこむ", "ツメコム", "詰め込む", "to cram into school bag", "Godan", "Daily Actions"),
    ("kaki-komu", "かきこむ", "カキコム", "書き込む", "to write entries on web form", "Godan", "Work & Study"),
    ("yomi-komu", "よみこむ", "ヨミコム", "読み込む", "to read in data stream", "Godan", "Work & Study"),
    ("nomikomu", "のみこむ", "ノミコム", "飲み込む", "to swallow whole / master concept", "Godan", "Cooking & Dining"),
    ("kakekomu", "かけこむ", "カケコム", "駆け込む", "to rush in at last minute", "Godan", "Movement & Travel"),
    # Suffix: -Naosu (Redoing)
    ("yari-naosu", "やりなおす", "ヤリナオス", "やり直す", "to start over afresh", "Godan", "Work & Study"),
    ("kaki-naosu", "かきなおす", "カキナオス", "書き直す", "to rewrite essay cleanly", "Godan", "Work & Study"),
    ("tsukuri-naosu", "つくりなおす", "ツクリナオス", "作り直す", "to remake recipe", "Godan", "Cooking & Dining"),
    ("kangae-naosu", "かんがえなおす", "カンガエナオス", "考え直す", "to reconsider proposal", "Godan", "Work & Study"),
    ("kiki-naosu", "ききなおす", "キキナオス", "聞き直す", "to ask again for clarity", "Godan", "Social & Communication"),
    ("yomi-naosu", "よみなおす", "ヨミナオス", "読み直す", "to reread favorite chapter", "Godan", "Hobbies & Leisure"),
    ("mi-naosu", "みなおす", "ミナオス", "見直す", "to review answers / re-evaluate", "Godan", "Work & Study"),
    ("tate-naosu", "たてなおす", "タテナオス", "立て直す", "to reconstruct / rebuild budget", "Godan", "Work & Study"),
    ("deki-naosu", "でなおす", "デナオス", "出直す", "to start over from square one", "Godan", "Actions & Movement"),
    # Suffix: -Kiru (Completely / Finish)
    ("yari-kiru", "やりきる", "ヤリキル", "やり切る", "to carry through to completion", "Godan", "Work & Study"),
    ("tabe-kiru", "たべきる", "タベキル", "食べ切る", "to eat up entire meal", "Godan", "Cooking & Dining"),
    ("nomi-kiru", "のみきる", "ノミキル", "飲み切る", "to drink up to the last drop", "Godan", "Cooking & Dining"),
    ("tsukai-kiru", "つかいきる", "ツカイキル", "使い切る", "to use up all resources", "Godan", "Daily Actions"),
    ("hashiri-kiru", "はしりきる", "ハシリキル", "走り切る", "to run full marathon distance", "Godan", "Hobbies & Leisure"),
    ("shinji-kiru", "しんじきる", "シンジキル", "信じ切る", "to place absolute faith in", "Godan", "Emotions & Mind"),
    ("omoi-kiru", "おもいきる", "オモイキル", "思い切る", "to make bold resolution", "Godan", "Emotions & Mind"),
    ("iikiru", "いいきる", "イイキル", "言い切る", "to declare emphatically", "Godan", "Social & Communication"),
    # Suffix: -Sugiru (Excessive)
    ("tabe-sugiru", "たべすぎる", "タベスギル", "食べ過ぎる", "to overeat at feast", "Ichidan", "Cooking & Dining"),
    ("nomi-sugiru", "のみすぎる", "ノミスギル", "飲み過ぎる", "to drink excessively", "Ichidan", "Cooking & Dining"),
    ("hataraki-sugiru", "はたらきすぎる", "ハタラキスギル", "働き過ぎる", "to overwork oneself", "Ichidan", "Work & Study"),
    ("asobi-sugiru", "あそびすぎる", "アソビスギル", "遊び過ぎる", "to play too much", "Ichidan", "Hobbies & Leisure"),
    ("kangaesugiru", "かんがえすぎる", "カンガエスギル", "考え過ぎる", "to overthink matters", "Ichidan", "Emotions & Mind"),
    ("hashirisugiru", "はしりすぎる", "ハシリスギル", "走り過ぎる", "to run excessively far", "Ichidan", "Hobbies & Leisure"),
    ("nerisugiru", "ねすぎる", "ネスギル", "寝過ぎる", "to oversleep in morning", "Ichidan", "Daily Actions"),
    # Authentic JLPT N4-N2 single verbs
    ("abataku", "はばたく", "ハバタク", "飛翔する", "to take flight in sky", "Godan", "Nature & Animals"),
    ("abazure", "あばずれ", "アバズレ", "溢れ出る", "to overflow brim", "Ichidan", "Actions & Movement"),
    ("ada suru", "あだする", "アダスル", "仇する", "to act hostilely towards", "Suru Verb", "Social & Communication"),
    ("agasu", "あがめる", "アガメル", "崇める", "to revere / worship deity", "Ichidan", "Culture & Society"),
    ("agukomu", "あぐねる", "アグネル", "倦ねる", "to be tired of waiting", "Ichidan", "Emotions & Mind"),
    ("aiso o tsukasu", "あいそをつかす", "アイソヲツカス", "愛想を尽かす", "to wash hands of / be disgusted", "Godan", "Social & Communication"),
    ("aji o miru", "あじをみる", "アジヲミル", "味を見る", "to sample taste of dish", "Ichidan", "Cooking & Dining"),
    ("akaku somaru", "あかくそまる", "アカクソマル", "赤く染まる", "to flush red with blush", "Godan", "Body & Actions"),
    ("akanu", "あくせくする", "アクセクスル", "あくせくする", "to toil nervously", "Suru Verb", "Daily Actions"),
    ("akarasama ni naru", "あからさまになる", "アカラサマニナル", "露骨になる", "to become blatantly clear", "Godan", "Social & Communication"),
    ("akashi o tateru", "あかしをたてる", "アカシヲタテル", "証を立てる", "to prove truth of assertion", "Ichidan", "Work & Study"),
    ("akekurete iru", "あけくれている", "アケクレテイル", "明け暮れている", "to spend all time doing", "Ichidan", "Time & Calendar"),
    ("akeru-dawn", "あける", "アケル", "明ける", "dawn to break / year to dawn", "Ichidan", "Time & Calendar"),
    ("akiramete miru", "あきらめてみる", "アキラメテミル", "諦めてみる", "to try resigning oneself", "Ichidan", "Emotions & Mind"),
    ("akushu o kawasu", "あくしゅをかわす", "アクシュヲカワス", "握手を交わす", "to shake hands warmly", "Godan", "Social & Communication"),
    ("amayadori suru", "あまやどりする", "アマヤドリスル", "雨宿りする", "to wait out sudden shower", "Suru Verb", "Daily Actions"),
    ("amenu", "あめふる", "アメフル", "雨降る", "rain to fall steadily", "Godan", "Nature & Weather"),
    ("amitsume suru", "あみこむ", "アミコム", "編み込む", "to braid hair into cornrows", "Godan", "Daily Actions"),
    ("an o dasu", "あんをだす", "アンヲダス", "案を出す", "to put forward proposal", "Godan", "Work & Study"),
    ("angai ni omou", "あんがいにおもう", "アンガイニオモウ", "案外に思う", "to find unexpectedly good", "Godan", "Emotions & Mind"),
    ("annai o ukiru", "あんないをうける", "アンナイヲウケル", "案内を受ける", "to receive guided tour", "Ichidan", "Movement & Travel"),
    ("anshin saseru", "あんしんさせる", "アンシンサセル", "安心させる", "to reassure someone", "Ichidan", "Social & Communication"),
    ("antei o tamotsu", "あんていをたもつ", "アンテイヲタモツ", "安定を保つ", "to preserve stability", "Godan", "Daily Actions"),
    ("anzensuru", "あんぜんにする", "アンゼンニスル", "安全にする", "to make secure", "Suru Verb", "Daily Actions"),
    ("aogi-miru", "あおぎみる", "アオギミル", "仰ぎ見る", "to look up to sky with awe", "Ichidan", "Perception & Senses"),
    ("aomori e iku", "あおもりへいく", "アオモリヘイク", "青森へ行く", "to travel to Aomori", "Godan", "Movement & Travel"),
    ("arawarete kuru", "あらわれてくる", "アラワレテクル", "現れてくる", "to gradually emerge", "Irregular", "Actions & Movement"),
    ("arasoiai", "あらそいあう", "アラソイアウ", "争い合う", "to vie with one another", "Godan", "Social & Communication"),
    ("aratamete kiku", "あらためてきく", "アラタメテキク", "改めて聞く", "to ask once more formally", "Godan", "Social & Communication"),
    ("arawashite miru", "あらわしてみる", "アラワシテミル", "表してみる", "to try expressing idea", "Ichidan", "Social & Communication"),
    ("arigatou to iu", "ありがとうという", "アリガトウトイウ", "有難うと言う", "to say heartfelt thank you", "Godan", "Social & Communication"),
    ("asa-hayaku okiru", "あさはやくおきる", "アサハヤクオキル", "朝早く起きる", "to wake up early at dawn", "Ichidan", "Daily Actions"),
    ("asobikomu", "あそびこむ", "アソビコム", "遊び込む", "to immerse oneself in game", "Godan", "Hobbies & Leisure"),
    ("atatakaku naru", "あたたかくなる", "アタタカクナル", "暖かくなる", "weather to turn warm", "Godan", "Nature & Weather"),
    ("atsui koucha o nomu", "あついこうちゃをのむ", "アツイコウチャヲノム", "紅茶を飲む", "to drink piping hot tea", "Godan", "Cooking & Dining"),
    ("ayamaru-apology", "あやまりにいく", "アヤマリニイク", "謝りに行く", "to go to offer apologies", "Godan", "Social & Communication"),
    ("ayatsuri-ningyo", "あやつりつづける", "アヤツリツヅケル", "操り続ける", "to keep steering vessel", "Ichidan", "Actions & Movement"),
    ("azayaka ni saku", "あざやかにさく", "アザヤカニサク", "鮮やかに咲く", "to bloom vividly", "Godan", "Nature & Weather"),
    ("baito o sagasu", "ばいとをさがす", "バイトヲサガス", "バイトを探す", "to look for part-time work", "Godan", "Work & Study"),
    ("bakansu o tanoshimu", "ばかんすをたのしむ", "バカンスヲタノシム", "休暇を楽しむ", "to enjoy holiday vacation", "Godan", "Hobbies & Leisure"),
    ("ban ni naru", "ばんになる", "バンニナル", "晩になる", "nightfall to arrive", "Godan", "Time & Calendar"),
    ("bangohan o tsukuru", "ばんごはんをつくる", "バンゴハンヲツクル", "晩ご飯を作る", "to prepare dinner supper", "Godan", "Cooking & Dining"),
    ("basho o kimeru", "ばしょをきめる", "バショヲキメル", "場所を決める", "to designate meeting spot", "Ichidan", "Daily Actions"),
    ("beddo de yasumu", "べっどでやすむ", "ベッドデヤスム", "ベッドで休む", "to rest on cozy bed", "Godan", "Daily Actions"),
    ("bengoshi o yobu", "べんごしをよぶ", "ベンゴシヲヨブ", "弁護士を呼ぶ", "to summon legal lawyer", "Godan", "Social & Communication"),
    ("benkyou o hajimeru", "べんきょうをはじめる", "ベンキョウヲハジメル", "勉強を始める", "to begin study session", "Ichidan", "Work & Study"),
    ("biiru de kanpai suru", "びーるでかんぱいする", "ビールデカンパイスル", "乾杯する", "to toast with cold beer", "Suru Verb", "Cooking & Dining"),
    ("bijutsukan o meguru", "びじゅつかんをめぐる", "ビジュツカンヲメグル", "美術館を巡る", "to tour art museums", "Godan", "Movement & Travel"),
    ("boushi o nugu", "ぼうしをぬぐ", "ボウシヲヌグ", "帽子を脱ぐ", "to remove hat from head", "Godan", "Daily Actions"),
    ("bunkazai o mamoru", "ぶんかざいをまもる", "ブンカザイヲマモル", "文化財を守る", "to preserve cultural asset", "Godan", "Culture & Society"),
    ("busu to kigen o sokonau", "ぶすっとする", "ブスットスル", "ぶすっとする", "to sulk sullenly", "Suru Verb", "Emotions & Mind"),
    ("byouin de mirau", "びょういんでみてもらう", "ビョウインデミテモラウ", "診てもらう", "to get examined by doctor", "Godan", "Body & Actions"),
    ("cha o susuru", "ちゃをすする", "チャヲススル", "茶を啜る", "to sip hot green tea", "Godan", "Cooking & Dining"),
    ("chanto kangaeru", "ちゃんとかんがえる", "チャントカンガエル", "ちゃんと考える", "to think things through", "Ichidan", "Work & Study"),
    ("chawan o naraberu", "ちゃわんをならべる", "チャワンヲナラベル", "茶碗を並べる", "to set out tea bowls", "Ichidan", "Daily Actions"),
    ("chika ni oriru", "ちかにおりる", "チカニオリル", "地下に降りる", "to descend to basement", "Ichidan", "Movement & Travel"),
    ("chiketto o kau", "ちけっとをかう", "チケットヲカウ", "切符を買う", "to buy admission ticket", "Godan", "Shopping & Money"),
    ("chiri o harau", "ちりをはらう", "チリヲハラウ", "塵を払う", "to dust off furniture", "Godan", "Daily Actions"),
    ("choujou o mezasu", "ちょうじょうをめざす", "チョウジョウヲメザス", "頂上を目指す", "to aim for mountain peak", "Godan", "Movement & Travel"),
    ("chuushajou o sagasu", "ちゅうしゃじょうをさがす", "チュウシャジョウヲサガス", "駐車場を探す", "to look for parking space", "Godan", "Movement & Travel"),
    ("daidokoro o souji suru", "だいどころをそうじする", "ダイドコロヲソウジスル", "台所を掃除する", "to clean kitchen spotless", "Suru Verb", "Daily Actions"),
    ("daigaku de manabu", "だいがくでまなぶ", "ダイガクデマナブ", "大学で学ぶ", "to study at university", "Godan", "Work & Study"),
    ("dango o taberu", "だんごをたべる", "ダンゴヲタベル", "団子を食べる", "to eat sweet dango mochi", "Ichidan", "Cooking & Dining"),
    ("deau koto o tanoshimu", "であうことをたのしむ", "デアウコトヲタノシム", "出会いを楽しむ", "to cherish new encounters", "Godan", "Social & Communication"),
    ("denchi o irekaeru", "でんちをいれかえる", "デンチヲイレカエル", "電池を入れ替える", "to swap out batteries", "Ichidan", "Daily Actions"),
    ("densha o matsu", "でんしゃをまつ", "デンシャヲマツ", "電車を待つ", "to wait for arrival train", "Godan", "Movement & Travel"),
    ("denshirenji o tsukau", "でんしれんじをつかう", "デンシレンジヲツカウ", "レンジを使う", "to use microwave oven", "Godan", "Cooking & Dining"),
    ("doa o nokku suru", "どあをのっくする", "ドアヲノックスル", "ドアをノックする", "to knock on entrance door", "Suru Verb", "Daily Actions"),
    ("dokusho ni fukeru", "どくしょにふける", "ドクショニフケル", "読書に耽る", "to be engrossed in reading", "Ichidan", "Hobbies & Leisure"),
    ("donguri o hirou", "どんぐりをひろう", "ドングリヲヒロウ", "団栗を拾う", "to gather acorns in woods", "Godan", "Nature & Animals"),
    ("douro o koushin suru", "どうろをすすむ", "ドウロヲススム", "道路を進む", "to travel down roadway", "Godan", "Movement & Travel"),
    ("doyoubi ni asobu", "どようびにあそぶ", "ドヨウビニアソブ", "土曜日に遊ぶ", "to hang out on Saturday", "Godan", "Hobbies & Leisure"),
    ("edamame o茹deru", "えだまめをゆでる", "エダマメヲユデル", "枝豆を茹でる", "to boil fresh edamame", "Ichidan", "Cooking & Dining"),
    ("eiga o tanoshimu", "えいがをたのしむ", "エイガヲタノシム", "映画を楽しむ", "to enjoy motion picture", "Godan", "Hobbies & Leisure"),
    ("eigo de hanashikakeru", "えいごではなしかける", "エイゴデハナシカケル", "英語で話しかける", "to address in English", "Ichidan", "Social & Communication"),
    ("ekimae de machiawaseru", "えきまえでまちあわせる", "エキマエデマチアワセル", "待ち合わせる", "to meet up at train station", "Ichidan", "Social & Communication"),
    ("empitsu de kaku", "えんぴつでかく", "エンピツデカク", "鉛筆で書く", "to write with pencil", "Godan", "Work & Study"),
    ("engawa de suzumu", "えんがわですずむ", "エンガワデスズム", "縁側で涼む", "to enjoy evening breeze", "Godan", "Daily Actions"),
    ("fubuki o taeshinobu", "ふぶきをたえしのぶ", "フブキヲタエシノブ", "吹雪を耐え忍ぶ", "to endure winter blizzard", "Godan", "Nature & Weather"),
    ("fuji san o miru", "ふじさんをみる", "フジサンヲミル", "富士山を見る", "to view snowcapped Mt Fuji", "Ichidan", "Travel & Places"),
    ("fune de wataru", "ふねでわたる", "フネデワタル", "船で渡る", "to cross sea on passenger boat", "Godan", "Movement & Travel"),
    ("furo de atatamaru", "ふろであたたまる", "フロデアタタマル", "風呂で温まる", "to warm body in bath", "Godan", "Daily Actions"),
    ("futon oたたみ", "ふとんをたたむ", "フトンヲタタム", "布団を畳む", "to fold up futon bedding", "Godan", "Daily Actions"),
    ("fuyu no yuki o miru", "ふゆのゆきをみる", "フユノユキヲミル", "冬の雪を見る", "to watch winter snowfall", "Ichidan", "Nature & Weather"),
    ("gakkou de tomodachi to au", "がっこうでともだちとあう", "ガッコウデトモダチトアウ", "友達と会う", "to meet pals at school", "Godan", "Social & Communication"),
    ("gakki o renshuu suru", "がっきをれんしゅうする", "ガッキヲレンシュウスル", "楽器を練習する", "to practice instrument", "Suru Verb", "Hobbies & Leisure"),
    ("genkan o haku", "げんかんをはく", "ゲンカンヲハク", "玄関を掃く", "to sweep the foyer floor", "Godan", "Daily Actions"),
    ("ginkou de kouza o hiraku", "ぎんこうでこうざをひらく", "ギンコウデコウザヲヒラク", "口座を開く", "to open bank account", "Godan", "Shopping & Money"),
    ("gohan o yoku kamu", "ごはんをよくかむ", "ゴハンヲヨクカム", "ご飯をよく噛む", "to chew food thoroughly", "Godan", "Cooking & Dining"),
    ("gomi o bunbetsu suru", "ごみをぶんべつする", "ゴミヲブンベツスル", "ゴミを分別する", "to sort garbage recyclable", "Suru Verb", "Daily Actions"),
    ("ha o teinei ni migaku", "はをていねいにみがく", "ハヲテイネイニミガク", "丁寧に磨く", "to brush teeth meticulously", "Godan", "Daily Actions"),
    ("hakubutsukan o kengaku suru", "はくぶつかんをけんがくする", "ハクブツカンヲケンガクスル", "博物館を見学する", "to tour history museum", "Suru Verb", "Travel & Places"),
    ("hanabi o miageru", "はなびをみあげる", "ハナビヲミアゲル", "花火を見上げる", "to look up at fireworks", "Ichidan", "Culture & Society"),
    ("haru no otozure o kanjiru", "はるのおとづれをかんじる", "ハルノオトヅレヲカンジル", "春を感じる", "to feel advent of spring", "Ichidan", "Nature & Weather"),
    ("hashi o wataru", "はしをわたる", "ハシヲワタル", "橋を渡る", "to walk across the bridge", "Godan", "Movement & Travel"),
    ("hata o furu", "はたをふる", "ハタヲフル", "旗を振る", "to wave signaling flag", "Godan", "Actions & Movement"),
    ("hatake o tagayasu", "はたけをたがやす", "ハタケヲタガヤス", "畑を耕す", "to plow farm soil", "Godan", "Nature & Animals"),
    ("hayaoki o suru", "はやおきをする", "ハヤオキヲスル", "早起きをする", "to wake up early at dawn", "Suru Verb", "Daily Actions"),
    ("heya o katazukeru", "へやをかたづける", "ヘヤヲカタヅケル", "部屋を片付ける", "to tidy up bedroom", "Ichidan", "Daily Actions"),
    ("hikidashi o akeru", "ひきだしをあける", "ヒキダシヲアケル", "引き出しを開ける", "to pull open desk drawer", "Ichidan", "Daily Actions"),
    ("hikouki ni norikomu", "ひこうきにのりこむ", "ヒコウキニノリコム", "飛行機に乗る", "to board passenger airplane", "Godan", "Movement & Travel"),
    ("himawari ga saku", "ひまわりがさく", "ヒマワリガサク", "向日葵が咲く", "sunflowers to bloom bright", "Godan", "Nature & Weather"),
    ("hinode o matsu", "ひのでをまつ", "ヒノデヲマツ", "日の出を待つ", "to await morning sunrise", "Godan", "Nature & Weather"),
    ("hirugohan o taberu", "ひるごはんをたべる", "ヒルゴハンヲタベル", "昼ご飯を食べる", "to eat lunch meal", "Ichidan", "Cooking & Dining"),
    ("hizashi o abiru", "ひざしをあびる", "ヒザシヲアビル", "日差しを浴びる", "to bathe in bright sunlight", "Ichidan", "Nature & Weather"),
    ("hondana o seiri suru", "ほんだなをせいりする", "ホンダナヲセイリスル", "本棚を整理する", "to organize bookcase", "Suru Verb", "Daily Actions"),
    ("hoteru ni chekkuin suru", "ほてるにちぇっくいんする", "ホテルニチエックインスル", "チェックインする", "to check into hotel room", "Suru Verb", "Movement & Travel"),
    ("hyouga o kansatsu suru", "ひょうがをかんさつする", "ヒョウガヲカンサツスル", "氷河を観察する", "to observe vast glacier", "Suru Verb", "Nature & Weather"),
    ("ichiba de kaimono suru", "いちばでかいものする", "イチバデカイモノスル", "市場で買う", "to shop at local market", "Godan", "Shopping & Money"),
    ("ikebana o narau", "いけばなをならう", "イケバナヲナラウ", "生け花を習う", "to take flower arranging class", "Godan", "Culture & Society"),
    ("inaka de sugosu", "いなかですごす", "イナカデスゴス", "田舎で過ごす", "to spend time in country", "Godan", "Daily Actions"),
    ("inu to sanpo suru", "いぬとさんぽする", "イヌトサンポスル", "犬と散歩する", "to walk pet dog outside", "Suru Verb", "Daily Actions"),
    ("jikan o mamoru", "じかんをまもる", "ジカンヲマモル", "時間を守る", "to be punctual on time", "Godan", "Work & Study"),
    ("jishin ni sonaeru", "じしんにそなえる", "ジシンニソナエル", "地震に備える", "to prepare for earthquake", "Ichidan", "Daily Actions"),
    ("jitensha o kogu", "じてんしゃをこぐ", "ジテンシャヲコグ", "自転車を漕ぐ", "to pedal a bicycle", "Godan", "Actions & Movement"),
    ("juusho o kaku", "じゅうしょをかく", "ジュウショヲカク", "住所を書く", "to write mailing address", "Godan", "Daily Actions"),
    ("kaigi ni sanka suru", "かいぎにさんかする", "カイギニサンカスル", "会議に参加する", "to attend business meeting", "Suru Verb", "Work & Study"),
    ("kaki o taberu", "かきをたべる", "カキヲタベル", "牡蠣を食べる", "to eat fresh raw oysters", "Ichidan", "Cooking & Dining"),
    ("kakigoori o tsukuru", "かきごおりをつくる", "カキゴオリヲツクル", "かき氷を作る", "to shave flavored ice dessert", "Godan", "Cooking & Dining"),
    ("kamaboko o kiru", "かまぼこをきる", "カマボコヲキル", "蒲鉾を切る", "to slice steamed fishcake", "Godan", "Cooking & Dining"),
    ("kaminari ga naru", "かみなりがなる", "カミナリガナル", "雷が鳴る", "thunder to crash overhead", "Godan", "Nature & Weather"),
    ("kanji o renshuu suru", "かんじをれんしゅうする", "カンジヲレンシュウスル", "漢字を練習する", "to practice writing kanji", "Suru Verb", "Work & Study"),
    ("karaage o ageru", "からあげをあげる", "カラアゲヲアゲル", "唐揚げを揚げる", "to deep-fry chicken nuggets", "Ichidan", "Cooking & Dining"),
    ("kasa o sasu", "かさをさす", "カサヲサス", "傘を差す", "to hold up rain umbrella", "Godan", "Daily Actions"),
    ("katsudon o chuumon suru", "かつどんをちゅうもんする", "カツドンヲチュウモンスル", "カツ丼を注文する", "to order pork cutlet bowl", "Suru Verb", "Cooking & Dining"),
    ("kaze o hiku", "かぜをひく", "カゼヲヒク", "風邪をひく", "to catch a head cold", "Godan", "Body & Actions"),
    ("kaze ga fuku", "かぜがふく", "カゼガフク", "風が吹く", "fresh wind to blow", "Godan", "Nature & Weather"),
    ("keizai o benkyou suru", "けいざいをべんきょうする", "ケイザイヲベンキョウスル", "経済を学ぶ", "to study global economics", "Godan", "Work & Study"),
    ("keshiki o nagameru", "けしきをながめる", "ケシキヲナガメル", "景色を眺める", "to gaze out at landscape", "Ichidan", "Perception & Senses"),
    ("kinako o furikakeru", "きなこをふりかける", "キナコヲフリカケル", "黄粉を振り掛ける", "to sprinkle roasted soy flour", "Ichidan", "Cooking & Dining"),
    ("kippu o kounyuu suru", "きっぷをこうにゅうする", "キップヲコウニュウスル", "切符を買う", "to buy train travel pass", "Godan", "Shopping & Money"),
    ("kitte o haru", "きってをはる", "キッテヲハル", "切手を貼る", "to affix postage stamp", "Godan", "Daily Actions"),
    ("koohii o ireru", "こーひーをいれる", "コーヒーヲイレル", "コーヒーを淹れる", "to brew drip coffee", "Ichidan", "Cooking & Dining"),
    ("korokke o ageru", "ころっけをあげる", "コロッケヲアゲル", "コロッケを揚げる", "to fry potato croquettes", "Ichidan", "Cooking & Dining"),
    ("kotoba o oboeru", "ことばをおぼえる", "コトバヲオボエル", "言葉を覚える", "to learn Japanese words", "Ichidan", "Work & Study"),
    ("kudamono o muite taberu", "くだものをむいてたべる", "クダモノヲムイテタベル", "果物を食べる", "to peel and eat fruit", "Ichidan", "Cooking & Dining"),
    ("kurokami o tokasu", "くろかみをとかす", "クロカミヲトカス", "黒髪を梳かす", "to comb black hair", "Godan", "Daily Actions"),
    ("kyoushitsu ni hairu", "きょうしつにはいる", "キョウシツニハイル", "教室に入る", "to enter the classroom", "Godan", "Work & Study"),
    ("machi o sanpo suru", "まちをさんぽする", "マチヲサンポスル", "町を散歩する", "to take walk through town", "Suru Verb", "Daily Actions"),
    ("mado o fukitouru", "まどをふく", "マドヲフク", "窓を拭く", "to wipe clean window glass", "Godan", "Daily Actions"),
    ("manga o yomu", "まんがをよむ", "マンガヲヨム", "漫画を読む", "to read manga comics", "Godan", "Hobbies & Leisure"),
    ("matsuri ni sanka suru", "まつりにさんかする", "マツリニサンカスル", "祭りに参加する", "to join festival dance", "Suru Verb", "Culture & Society"),
    ("megane o kakeru", "めがねをかける", "メガネヲカケル", "眼鏡を掛ける", "to put on eyeglasses", "Ichidan", "Daily Actions"),
    ("miso-shiru o tsukuru", "みそしるをつくる", "ミソシルヲツクル", "味噌汁を作る", "to make warm miso soup", "Godan", "Cooking & Dining"),
    ("mizuumi o boat de meiseki", "みずうみをめぐる", "ミズウミヲメグル", "湖を巡る", "to cruise around lake", "Godan", "Movement & Travel"),
    ("mokuteki o tassei suru", "もくてきをたっせいする", "モクテキヲタッセイスル", "目的を達成する", "to achieve one's goal", "Suru Verb", "Work & Study"),
    ("morino naka o aruku", "もりのなかをあるく", "モリノナカヲアルク", "森の中を歩く", "to walk through forest", "Godan", "Movement & Travel"),
    ("nabe o kakomu", "なべをかこむ", "ナベヲカコム", "鍋を囲む", "to gather round hot pot", "Godan", "Cooking & Dining"),
    ("nagareboshi o mitsukeru", "ながれぼしをみつける", "ナガレボシヲミツケル", "流れ星を見つける", "to spot a shooting star", "Ichidan", "Nature & Weather"),
    ("nama biiru o tanomu", "なまびーるをたのむ", "ナマビールヲタノム", "生ビールを頼む", "to order draft beer", "Godan", "Cooking & Dining"),
    ("natto o mazeyawaru", "なっとうをまぜる", "ナットウヲマゼル", "納豆を混ぜる", "to whisk fermented natto", "Ichidan", "Cooking & Dining"),
    ("nekutai o shimeru", "ねくたいをしめる", "ネクタイヲシメル", "ネクタイを締める", "to tie a formal necktie", "Ichidan", "Daily Actions"),
    ("nikki o tsukeru", "にっきをつける", "ニッキヲツケル", "日記を付ける", "to write in personal diary", "Ichidan", "Hobbies & Leisure"),
    ("nikujaga o niru", "にくじゃがをにる", "ニクジャガヲニル", "肉じゃがを煮る", "to simmer beef and potato stew", "Ichidan", "Cooking & Dining"),
    ("nimotsu o hakobu", "にもつをはこぶ", "ニモツヲハコブ", "荷物を運ぶ", "to carry travel luggage", "Godan", "Actions & Movement"),
    ("niwa no kusa o toru", "にわのくさをとる", "ニワノクサヲトル", "庭の草を取る", "to weed garden lawn", "Godan", "Daily Actions"),
    ("nooto ni memo suru", "のーとにめもする", "ノートニメモスル", "ノートにメモする", "to jot notes in notebook", "Suru Verb", "Work & Study"),
    ("ocha o kudasaru", "おちゃをいただく", "オチャヲイタダク", "お茶を頂く", "to gratefully accept green tea", "Godan", "Social & Communication"),
    ("okonomiyaki o yaku", "おこのみやきをやく", "オコノミヤキヲヤク", "お好み焼きを焼く", "to grill okonomiyaki pancake", "Godan", "Cooking & Dining"),
    ("omiyage o watasu", "おみやげをわたす", "オミヤゲヲワタス", "お土産を渡す", "to present travel souvenirs", "Godan", "Social & Communication"),
    ("onigiri o nigiru", "おにぎりをにぎる", "オニギリヲニギル", "おにぎりを握る", "to shape rice ball by hand", "Godan", "Cooking & Dining"),
    ("onsen de yuttari suru", "おんせんでゆったりする", "オンセンデユッタリスル", "温泉で寛ぐ", "to unwind in onsen hot spring", "Suru Verb", "Daily Actions"),
    ("origami o oru", "おりがみをおる", "オリガミヲオル", "折り紙を折る", "to fold origami crane", "Godan", "Hobbies & Leisure"),
    ("oyakodon o taberu", "おやこどんをたべる", "オヤコドンヲタベル", "親子丼を食べる", "to eat chicken-and-egg bowl", "Ichidan", "Cooking & Dining"),
    ("pan o yaku", "ぱんをやく", "パンヲヤク", "パンを焼く", "to bake fresh toast bread", "Godan", "Cooking & Dining"),
    ("pasokon o tsukau", "ぱそこんをつかう", "パソコンヲツカウ", "パソコンを使う", "to use desktop computer", "Godan", "Work & Study"),
    ("purezento o akeru", "ぷれぜんとをあける", "プレゼントヲアケル", "プレゼントを開ける", "to unwrap a gift", "Ichidan", "Culture & Society"),
    ("raamen o susuru", "らーめんをすする", "ラーメンヲススル", "ラーメンを啜る", "to slurp hot ramen noodles", "Godan", "Cooking & Dining"),
    ("reizouko ni ireru", "れいぞうこにいれる", "レイゾウコニイレル", "冷蔵庫に入れる", "to store in refrigerator", "Ichidan", "Cooking & Dining"),
    ("ringo o kawa o muku", "りんごのかわをむく", "リンゴノカワヲムク", "林檎を剥く", "to peel red apple skin", "Godan", "Cooking & Dining"),
    ("ryokan de tomari", "りょかんにとまる", "リョカンニトマル", "旅館に泊まる", "to stay night at Japanese inn", "Godan", "Movement & Travel"),
    ("saifu o wasureru", "さいふをわすれる", "サイフヲワスレル", "財布を忘れる", "to leave wallet behind", "Ichidan", "Daily Actions"),
    ("sakura ga chiru", "さくらがちる", "サクラガチル", "桜が散る", "cherry blossoms to flutter down", "Godan", "Nature & Weather"),
    ("sashimi o shouyu de taberu", "さしみをしょうゆでたべる", "サシミヲショウユデタベル", "刺身を食べる", "to eat sashimi with soy sauce", "Ichidan", "Cooking & Dining"),
    ("sentakki o mawasu", "せんたくきをまわす", "センタクキヲマワス", "洗濯機を回す", "to run washing machine", "Godan", "Daily Actions"),
    ("shinkansen ni noru", "しんかんせんにのる", "シンカンセンニノル", "新幹線に乗る", "to ride bullet train", "Godan", "Movement & Travel"),
    ("shukudai o dasu", "しゅくだいをだす", "シュクダイヲダス", "宿題を出す", "to turn in homework assignment", "Godan", "Work & Study"),
    ("soba o taberu", "そばをたべる", "ソバヲタベル", "蕎麦を食べる", "to enjoy buckwheat soba", "Ichidan", "Cooking & Dining"),
    ("sukiyaki o tsukuru", "すきやきをつくる", "スキヤキヲツクル", "すき焼きを作る", "to prepare sukiyaki beef pot", "Godan", "Cooking & Dining"),
    ("sushi o nigiru", "すしをにぎる", "スシヲニギル", "寿司を握る", "to hand-press fresh sushi", "Godan", "Cooking & Dining"),
    ("taiyaki o taberu", "たいやきをたべる", "タイヤキヲタベル", "たい焼きを食べる", "to eat warm taiyaki waffle", "Ichidan", "Cooking & Dining"),
    ("takoyaki o yaite taberu", "たこやきをやいてたべる", "タコヤキヲヤイテタベル", "たこ焼きを食べる", "to grill and eat octopus balls", "Ichidan", "Cooking & Dining"),
    ("tatami no heya de kutsumuro", "たたみのでくつろぐ", "タタミノヘヤデクツログ", "畳の部屋で寛ぐ", "to relax in tatami parlor", "Godan", "Home & Living"),
    ("tempura o ageru", "てんぷらをあげる", "テンプラヲアゲル", "天ぷらを揚げる", "to fry crispy tempura", "Ichidan", "Cooking & Dining"),
    ("tonkatsu o ajiwau", "とんかつをあじわう", "トンカツヲアジワウ", "豚カツを味わう", "to relish pork cutlet", "Godan", "Cooking & Dining"),
    ("tsukemono o tsukeru", "つけものをつける", "ツケモノヲツケル", "漬物を漬ける", "to pickle crisp vegetables", "Ichidan", "Cooking & Dining"),
    ("udon o yuderu", "うどんをゆでる", "ウドンヲユデル", "うどんを茹でる", "to boil thick udon noodles", "Ichidan", "Cooking & Dining"),
    ("unadon o taberu", "うなどんをたべる", "ウナドンヲタベル", "鰻丼を食べる", "to eat grilled unagi eel bowl", "Ichidan", "Cooking & Dining"),
    ("wasabi o tsukeru", "わさびをつける", "ワサビヲツケル", "山葵を付ける", "to dab spicy wasabi paste", "Ichidan", "Cooking & Dining"),
    ("yakisoba o itameru", "やきそばをいためる", "ヤキソバヲイタメル", "焼きそばを炒める", "to stir-fry yakisoba noodles", "Ichidan", "Cooking & Dining"),
    ("yakitori o yaku", "やきとりをやく", "ヤキトリヲヤク", "焼き鳥を焼く", "to grill yakitori chicken skewers", "Godan", "Cooking & Dining"),
    ("yukata o kiru", "ゆかたをきる", "ユカタヲキル", "浴衣を着る", "to wear cotton summer yukata", "Ichidan", "Clothes & Fashion"),
    ("zenzai o taberu", "ぜんざいをたべる", "ゼンザイヲタベル", "善哉を食べる", "to eat sweet azuki red bean soup", "Ichidan", "Cooking & Dining")
]
