# Extensive Authentic Japanese Verbs (JLPT N5-N2 & Conversational Compounds)
DATA = [
    # Compound verbs & Core actions
    ("abaredasu", "あばれだす", "アバレダス", "暴れ出す", "to begin to rage / run amok", "Godan", "Actions & Movement"),
    ("abareru", "あばれる", "アバレル", "暴れる", "to act violently / rampage", "Ichidan", "Actions & Movement"),
    ("aburidashite", "あぶりだす", "アブリダス", "炙り出す", "to bring to light / smoke out", "Godan", "Daily Actions"),
    ("aeru-dish", "あえる", "アエル", "和える", "to dress vegetables in sauce", "Ichidan", "Cooking & Dining"),
    ("agaki-mawaru", "あがきまわる", "アガキマワル", "足掻き回る", "to struggle restlessly", "Godan", "Actions & Movement"),
    ("agarikomu", "あがりこむ", "アガリコム", "上がり込む", "to barge into a room", "Godan", "Actions & Movement"),
    ("ageru-fry", "あげる", "アゲル", "揚げる", "to deep-fry tempura in oil", "Ichidan", "Cooking & Dining"),
    ("aijo o sosogu", "あいじょうをそそぐ", "アイジョウヲソソグ", "愛情を注ぐ", "to shower with tender love", "Godan", "Emotions & Mind"),
    ("aisatsu o suru", "あいさつをする", "アイサツヲスル", "挨拶をする", "to exchange formal greetings", "Suru Verb", "Social & Communication"),
    ("aishiau", "あいしあう", "アイシアウ", "愛し合う", "to love one another mutually", "Godan", "Emotions & Mind"),
    ("aiyoku suru", "あいよくする", "アイヨクスル", "愛浴する", "to cherish fondly", "Suru Verb", "Emotions & Mind"),
    ("ajitsuke o suru", "あじつけをする", "アジツケヲスル", "味付けをする", "to season food flavor", "Suru Verb", "Cooking & Dining"),
    ("akarasama ni iu", "あからさまにいう", "アカラサマニイウ", "露骨に言う", "to speak frankly / bluntly", "Godan", "Social & Communication"),
    ("akaruku naru", "あかるくなる", "アカルクナル", "明るくなる", "to brighten up / become cheerful", "Godan", "Nature & Weather"),
    ("akiramete shimau", "あきらめてしまう", "アキラメテシマウ", "諦めてしまう", "to give up completely", "Godan", "Emotions & Mind"),
    ("akiru made asobu", "あきるまであそぶ", "アキルマデアソブ", "飽きるまで遊ぶ", "to play until satisfied", "Godan", "Hobbies & Leisure"),
    ("aku-space", "あく", "アク", "空く", "to become empty / vacant", "Godan", "Daily Actions"),
    ("akumu o miru", "あくむをみる", "アクムヲミル", "悪夢を見る", "to have a nightmare", "Ichidan", "Emotions & Mind"),
    ("amado o shimeru", "あまどをしめる", "アマドヲシメル", "雨戸を閉める", "to shut storm shutters", "Ichidan", "Home & Living"),
    ("amami o kuwaeru", "あまみをくわえる", "アマミヲクワエル", "甘みを加える", "to add sweetness to taste", "Ichidan", "Cooking & Dining"),
    ("amari o kubaru", "あまりをくばる", "アマリヲクバル", "余りを配る", "to distribute surplus", "Godan", "Daily Actions"),
    ("amaru", "あまる", "アマル", "余る", "to remain over / be in excess", "Godan", "Daily Actions"),
    ("amatsuyu o harau", "あまつゆをはらう", "アマツユヲハラウ", "雨露を払う", "to brush off raindrops", "Godan", "Daily Actions"),
    ("amayadori o suru", "あまやどりをする", "アマヤドリヲスル", "雨宿りをする", "to shelter from sudden rain", "Suru Verb", "Daily Actions"),
    ("ana o horu", "あなをほる", "アナヲホル", "穴を掘る", "to dig a hole in ground", "Godan", "Actions & Movement"),
    ("an'ya o kakeru", "あんやをかける", "アンヤヲカケル", "暗夜を駆ける", "to run through dark night", "Ichidan", "Actions & Movement"),
    ("antei suru", "あんていする", "アンテイスル", "安定する", "to stabilize / settle down", "Suru Verb", "Daily Actions"),
    ("anzensaku o toru", "あんぜんさくをとる", "アンゼンサクヲトル", "安全策を取る", "to play it safe", "Godan", "Work & Study"),
    ("aoao to shigeru", "あおあおとしげる", "アオアオトシゲル", "青々と茂る", "to grow lush and green", "Godan", "Nature & Animals"),
    ("aoba ga moeru", "あおばがもえる", "アオバガモエル", "青葉が燃える", "green foliage to flourish", "Ichidan", "Nature & Weather"),
    ("aoku somaru", "あおくそまる", "アオクソマル", "青く染まる", "to turn deep azure", "Godan", "Nature & Weather"),
    ("aomuke ni neru", "あおむけにねる", "アオムケニネル", "仰向けに寝る", "to lie down face-up", "Ichidan", "Daily Actions"),
    ("aosa o tanoshimu", "あおさをたのしむ", "アオサヲタノシム", "青さを楽しむ", "to savor the lush green", "Godan", "Hobbies & Leisure"),
    ("apuri o kidou suru", "あぷりをきどうする", "アプリヲキドウスル", "アプリを起動する", "to launch smartphone app", "Suru Verb", "Daily Actions"),
    ("aragai-gataku naru", "あらがいがたくなる", "アラガイガタクナル", "抗い難くなる", "to become irresistible", "Godan", "Emotions & Mind"),
    ("aragau", "あらがう", "アラガウ", "抗う", "to oppose / defy fate", "Godan", "Social & Communication"),
    ("arata ni suru", "あらたにする", "アラタニスル", "新たにする", "to renew one's resolve", "Suru Verb", "Emotions & Mind"),
    ("aratamete omou", "あらためておもう", "アラメテオモウ", "改めて思う", "to reflect anew", "Godan", "Emotions & Mind"),
    ("arashi ga saru", "あらしがさる", "アラシガサル", "嵐が去る", "tempest to pass away", "Godan", "Nature & Weather"),
    ("arau-clean", "あらいながす", "アライナガス", "洗い流す", "to rinse thoroughly away", "Godan", "Daily Actions"),
    ("arawareru-feel", "あらわれる", "アラワレル", "顕れる", "to become manifest / reveal", "Ichidan", "Actions & Movement"),
    ("arigataku omou", "ありがたくおもう", "アリガタクオモウ", "有り難く思う", "to feel deeply appreciative", "Godan", "Emotions & Mind"),
    ("aru", "ある", "アル", "有る", "to exist (inanimate objects)", "Godan", "Daily Actions"),
    ("aruki-mawaru", "あるきまわる", "アルキマワル", "歩き回る", "to stroll all around", "Godan", "Movement & Travel"),
    ("asa o mukaeru", "あさをむかえる", "アサヲムカエル", "朝を迎える", "to greet the new dawn", "Ichidan", "Daily Actions"),
    ("asagohan o taberu", "あさごはんをたべる", "アサゴハンヲタベル", "朝ご飯を食べる", "to eat breakfast", "Ichidan", "Cooking & Dining"),
    ("asai kangaewasuru", "あさいかんがえをする", "アサイカンガエヲスル", "浅い考えをする", "to think shallowly", "Suru Verb", "Emotions & Mind"),
    ("asase o wataru", "あさせをわたる", "アサセヲワタル", "浅瀬を渡る", "to wade across shallow waters", "Godan", "Movement & Travel"),
    ("ase o fuku", "あせをふく", "アセヲフク", "汗を拭く", "to wipe away perspiration", "Godan", "Daily Actions"),
    ("ase o nagasu", "あせをながす", "アセヲナガス", "汗を流す", "to sweat hard / work diligently", "Godan", "Work & Study"),
    ("ashikase o hazusu", "あしかせをはずす", "アシカセヲハズス", "足枷を外す", "to cast off shackles", "Godan", "Actions & Movement"),
    ("ashimoto o miru", "あしもとをみる", "アシモトヲミル", "足元を見る", "to watch one's step / take advantage", "Ichidan", "Daily Actions"),
    ("ashinami o soroeru", "あしなみをそろえる", "アシナミヲソロエル", "足並みを揃える", "to keep in step / cooperate", "Ichidan", "Social & Communication"),
    ("atama o sageru", "あたまをさげる", "アタマヲサゲル", "頭を下げる", "to bow head in gratitude or apology", "Ichidan", "Social & Communication"),
    ("atama o tsukau", "あたまをつかう", "アタマヲツカウ", "頭を使う", "to use one's head / brainstorm", "Godan", "Work & Study"),
    ("atarashiku tsukuru", "あたらしくつくる", "アタラシクツクル", "新しく作る", "to craft anew", "Godan", "Daily Actions"),
    ("atatakaku tsutsumu", "あたたかくつつむ", "アタタカクツツム", "温かく包む", "to envelop with warmth", "Godan", "Emotions & Mind"),
    ("ate ni suru", "あてにする", "アテニスル", "当てにする", "to rely upon / bank on", "Suru Verb", "Social & Communication"),
    ("atenai tabi o suru", "あてないたびをする", "アテナイタビヲスル", "宛てない旅をする", "to travel without destination", "Suru Verb", "Movement & Travel"),
    ("ato o ou", "あとをおう", "アトヲオウ", "後を追う", "to follow closely behind", "Godan", "Actions & Movement"),
    ("ato o tsugu", "あとをつぐ", "アトヲツグ", "跡を継ぐ", "to inherit family legacy", "Godan", "People & Family"),
    ("atsumaru", "あつまる", "アツマル", "集まる", "to gather together / assemble", "Godan", "Social & Communication"),
    ("atsumeru", "あつめる", "アツメル", "集める", "to collect items / gather group", "Ichidan", "Daily Actions"),
    ("atsuku kataru", "あつくかたる", "アツクカタル", "熱く語る", "to speak with fiery passion", "Godan", "Social & Communication"),
    ("atsuryoku o kakeru", "あつりょくをかける", "アツリョクヲカケル", "圧力をかける", "to apply pressure", "Ichidan", "Social & Communication"),
    ("awateru", "あわてる", "アワテル", "慌てる", "to become flustered / panic", "Ichidan", "Emotions & Mind"),
    ("ayamachi o yurusu", "あやまちをゆるす", "アヤマチヲユルス", "過ちを許す", "to forgive an error", "Godan", "Social & Communication"),
    ("ayatsuru", "あやつる", "アヤツル", "操る", "to manipulate puppet / navigate", "Godan", "Actions & Movement"),
    ("ayumu", "あゆむ", "アユム", "歩む", "to walk life path / tread", "Godan", "Actions & Movement"),
    ("azayaka ni kimeru", "あざやかにきめる", "アザヤカニキメル", "鮮やかに決める", "to score brilliantly", "Ichidan", "Hobbies & Leisure"),
    # Compound and advanced Godan/Ichidan verbs
    ("bannou ni furumau", "ばんのうにふるまう", "バンノウニフルマウ", "万能に振る舞う", "to act versatilely", "Godan", "Social & Communication"),
    ("basho o kaeru", "ばしょをかえる", "バショヲカエル", "場所を変える", "to change venue location", "Ichidan", "Movement & Travel"),
    ("basho o toru", "ばしょをとる", "バショヲトル", "場所を取る", "to take up space", "Godan", "Daily Actions"),
    ("beikoku e iku", "べいこくへいく", "ベイコクヘイク", "米国へ行く", "to travel to the USA", "Godan", "Movement & Travel"),
    ("bengoshi ni tanomu", "べんごしにたのむ", "ベンゴシニタノム", "弁護士に頼む", "to hire legal counsel", "Godan", "Social & Communication"),
    ("benri ni naru", "べんりになる", "ベンリニナル", "便利になる", "to become very convenient", "Godan", "Daily Actions"),
    ("biiru o sosogu", "びーるをそそぐ", "ビールヲソソグ", "ビールを注ぐ", "to pour beer into glass", "Godan", "Cooking & Dining"),
    ("bijinesu o hajimeru", "びじねすをはじめる", "ビジネスヲハジメル", "ビジネスを始める", "to launch a enterprise", "Ichidan", "Work & Study"),
    ("bousai o kokoroeru", "ぼうさいをこころえる", "ボウサイヲココロエル", "防災を心得る", "to master disaster safety", "Ichidan", "Work & Study"),
    ("boushi o kaburu", "ぼうしをかぶる", "ボウシヲカブル", "帽子を被る", "to put on a hat", "Godan", "Daily Actions"),
    ("budou o tsumu", "ぶどうをつむ", "ブドウヲツム", "葡萄を摘む", "to pick ripe grapes", "Godan", "Cooking & Dining"),
    ("bunsho o kaku", "ぶんしょうをかく", "ブンショウヲカク", "文章を書く", "to write prose essay", "Godan", "Work & Study"),
    ("butsukari-au", "ぶつかりあう", "ブツカリアウ", "ぶつかり合う", "to collide into each other", "Godan", "Actions & Movement"),
    ("byouin ni iku", "びょういんにいく", "ビョウインニイク", "病院に行く", "to visit hospital clinic", "Godan", "Body & Actions"),
    # Ch- verbs
    ("cha o tateru", "ちゃをたてる", "チャヲタテル", "茶を点てる", "to whisk traditional matcha tea", "Ichidan", "Culture & Society"),
    ("chakuchaku to susumu", "ちゃくちゃくとすすむ", "チャクチャクトススム", "着実に進む", "to advance steadily", "Godan", "Work & Study"),
    ("chanto kiku", "ちゃんときく", "チャントキク", "ちゃんと聞く", "to listen attentively", "Godan", "Social & Communication"),
    ("chanto tsutaeru", "ちゃんとつたえる", "チャントツタエル", "ちゃんと伝える", "to convey accurately", "Ichidan", "Social & Communication"),
    ("chawan o arau", "ちゃわんをあらう", "チャワンヲアラウ", "茶碗を洗う", "to wash rice bowl dishes", "Godan", "Daily Actions"),
    ("chie o shiboru", "ちえをしぼる", "チエヲシボル", "知恵を絞る", "to rack one's brains", "Godan", "Work & Study"),
    ("chikai o tateru", "ちかいをたてる", "チカイヲタテル", "誓いを立てる", "to take a solemn vow", "Ichidan", "Culture & Society"),
    ("chikau", "ちかう", "チカウ", "誓う", "to swear an oath / vow", "Godan", "Social & Communication"),
    ("chizu o miru", "ちずをみる", "チズヲミル", "地図を見る", "to inspect roadmap", "Ichidan", "Movement & Travel"),
    ("choushi o totonoeru", "ちょうしをととのえる", "チョウシヲトトノエル", "調子を整える", "to tune instrument / condition", "Ichidan", "Daily Actions"),
    ("chuuui o harau", "ちゅういをはらう", "チュウイヲハラウ", "注意を払う", "to pay strict attention", "Godan", "Work & Study"),
    # D- verbs
    ("daidokoro ni tatsu", "だいどころにたつ", "ダイドコロニタツ", "台所に立つ", "to stand in kitchen to cook", "Godan", "Daily Actions"),
    ("daigaku o sotsugyou suru", "だいがくをそつぎょうする", "ダイガクヲソツギョウスル", "大学を卒業する", "to graduate from college", "Suru Verb", "Work & Study"),
    ("daitaishitsu o tsukuru", "だいたいあんをつくる", "ダイタイアンヲツクル", "代替案を作る", "to prepare fallback plan", "Godan", "Work & Study"),
    ("dame ni naru", "だめになる", "ダメニナル", "駄目になる", "to be spoiled / come to naught", "Godan", "Daily Actions"),
    ("danraku o tsukeru", "だんらくをつける", "ダンラクヲツケル", "段落を付ける", "to bring matter to a close", "Ichidan", "Work & Study"),
    ("dasidashi to aruku", "だんだんとあるく", "ダンダントアルク", "段々と歩く", "to walk step-by-step", "Godan", "Actions & Movement"),
    ("deiri suru", "でいりする", "デイリスル", "出入りする", "to frequent place / go in and out", "Suru Verb", "Movement & Travel"),
    ("dekagiru", "でぎる", "デギル", "出切る", "to be sold out / all emerged", "Godan", "Actions & Movement"),
    ("dekakeru-trip", "たびへでる", "タビヘデル", "旅へ出る", "to set out on voyage", "Ichidan", "Movement & Travel"),
    ("denchi o kaeru", "でんちをかえる", "デンチヲカエル", "電池を換える", "to replace battery", "Ichidan", "Daily Actions"),
    ("densha ni noru", "でんしゃにのる", "デンシャニノル", "電車に乗る", "to board passenger train", "Godan", "Movement & Travel"),
    ("denshirenji de atatameru", "でんしれんじであたためる", "デンシレンジデアタタメル", "レンジで温める", "to warm up in microwave", "Ichidan", "Cooking & Dining"),
    ("doa o akeru", "どあをあける", "ドアヲアケル", "ドアを開ける", "to open entrance door", "Ichidan", "Daily Actions"),
    ("doa o shimeru", "どあをしめる", "ドアヲシメル", "ドアを閉める", "to close entrance door", "Ichidan", "Daily Actions"),
    ("doko e mo ikanai", "どこへもいかない", "ドコヘモイカナイ", "何処へも行かない", "to not go anywhere", "Godan", "Daily Actions"),
    ("doryoku o kasaneru", "どりょくをかさねる", "ドリョクヲカサネル", "努力を重ねる", "to redouble one's efforts", "Ichidan", "Work & Study"),
    ("douro o wataru", "どうろをわたる", "ドウロヲワタル", "道路を渡る", "to cross over the street", "Godan", "Movement & Travel"),
    # E- verbs
    ("e o kaku", "えをかく", "エヲカク", "絵を描く", "to paint a picture", "Godan", "Hobbies & Leisure"),
    ("ehon o yonde ageru", "えほんをよんであげる", "エホンヲヨンデアゲル", "絵本を読んであげる", "to read picture book to child", "Ichidan", "People & Family"),
    ("eiga o miru", "えいがをみる", "エイガヲミル", "映画を見る", "to watch cinema movie", "Ichidan", "Hobbies & Leisure"),
    ("eigo o hanasu", "えいごをはなす", "エイゴヲハナス", "英語を話す", "to speak English fluently", "Godan", "Work & Study"),
    ("eki ni tsuku", "えきにつく", "エキニツク", "駅に着く", "to arrive at train station", "Godan", "Movement & Travel"),
    ("ekimae o tooru", "えきまえをとおる", "エキマエヲトオル", "駅前を通る", "to pass by the station square", "Godan", "Movement & Travel"),
    ("empitsu o kezuru", "えんぴつをけずる", "エンピツヲケズル", "鉛筆を削る", "to sharpen pencil", "Godan", "Tools & Goods"),
    ("engawa de yasumu", "えんがわでやすむ", "エンガワデヤスム", "縁側で休む", "to relax on veranda porch", "Godan", "Daily Actions"),
    ("ensou o kiku", "えんそうをきく", "エンソウヲキク", "演奏を聞く", "to listen to concert recital", "Godan", "Hobbies & Leisure"),
    ("eri o tadasu", "えりをただす", "エリヲタダス", "襟を正す", "to straighten collar / reform posture", "Godan", "Culture & Society"),
    # F- verbs
    ("fashon o tanoshimu", "ふぁっしょんをたのしむ", "ファッションヲタノシム", "ファッションを楽しむ", "to enjoy stylish fashion", "Godan", "Hobbies & Leisure"),
    ("fubin ni omou", "ふびんにおもう", "フビンニオモウ", "不憫に思う", "to feel tender pity for", "Godan", "Emotions & Mind"),
    ("fuji san ni noboru", "ふじさんにのぼる", "フジサンニノボル", "富士山に登る", "to scale Mount Fuji", "Godan", "Movement & Travel"),
    ("fukuro ni tsumeru", "ふくろにつめる", "フクロニツメル", "袋に詰める", "to pack into bag", "Ichidan", "Daily Actions"),
    ("fukusou o totonoeru", "ふくそうをととのえる", "フクソウヲトトノエル", "服装を整える", "to neaten one's attire", "Ichidan", "Daily Actions"),
    ("fune o kogu", "ふねをこぐ", "フネヲコグ", "船を漕ぐ", "to row rowboat", "Godan", "Actions & Movement"),
    ("furo ni hairu", "ふろにはいる", "フロニハイル", "風呂に入る", "to take hot bath", "Godan", "Daily Actions"),
    ("furu-hon o sagasu", "ふるほんをさがす", "フルホンヲサガス", "古本を探す", "to browse vintage bookshop", "Godan", "Hobbies & Leisure"),
    ("futa o akeru", "ふたをあける", "フタヲアケル", "蓋を開ける", "to uncover lid of pot", "Ichidan", "Cooking & Dining"),
    ("futon o hosu", "ふとんをほす", "フトンヲホス", "布団を干す", "to air futon under sun", "Godan", "Daily Actions"),
    ("futon o shiku", "ふとんをしく", "フトンヲシク", "布団を敷く", "to lay out futon bed", "Godan", "Daily Actions"),
    ("fuyu o sugosu", "ふゆをすごす", "フユヲスゴス", "冬を過ごす", "to spend winter season", "Godan", "Daily Actions"),
    # G- verbs
    ("gakkou ni kayou", "がっこうにかよう", "ガッコウニカヨウ", "学校に通う", "to attend school class", "Godan", "Work & Study"),
    ("gakki o kanaderu", "がっきのかなでる", "ガッキヲカナデル", "楽器を奏でる", "to play musical melody", "Ichidan", "Hobbies & Leisure"),
    ("garasu o fuku", "がらすをふく", "ガラスヲフク", "窓ガラスを拭く", "to wipe clean window pane", "Godan", "Daily Actions"),
    ("genkan de kutsu o nugu", "げんかんでくつをぬぐ", "ゲンカンデクツヲヌグ", "靴を脱ぐ", "to take shoes off at foyer", "Godan", "Daily Actions"),
    ("genki o dasu", "げんきをだす", "ゲンキヲダス", "元気を出す", "to cheer up / perk up", "Godan", "Emotions & Mind"),
    ("ginkou de orosu", "ぎんこうでおろす", "ギンコウデオロス", "銀行で下ろす", "to withdraw money from bank", "Godan", "Shopping & Money"),
    ("gohan o炊く", "ごはんをたく", "ゴハンヲタク", "ご飯を炊く", "to cook steamed rice", "Godan", "Cooking & Dining"),
    ("gomi o suteru", "ごみをすてる", "ゴミヲステル", "ゴミを捨てる", "to throw away garbage", "Ichidan", "Daily Actions"),
    ("goshigoshi migaku", "ごしごしみがく", "ゴシゴシミガク", "ごしごし磨く", "to scrub vigorously clean", "Godan", "Daily Actions"),
    ("gyuunyu o nomu", "ぎゅうにゅうをのむ", "ギュウニュウヲノム", "牛乳を飲む", "to drink dairy milk", "Godan", "Cooking & Dining")
]
