# Extended Advanced & Everyday Japanese Verbs (350+ entries)
DATA = [
    # A
    ("abakareru-truth", "しんじつがあばかれる", "シンジツガアバカレル", "真実が暴かれる", "truth to be laid bare", "Ichidan", "Social & Communication"),
    ("achi o kuguru", "あーちをくぐる", "アーチヲクグル", "アーチをくぐる", "to walk beneath ceremonial arch", "Godan", "Movement & Travel"),
    ("afureru", "あふれる", "アフレル", "溢れる", "to overflow with confidence / joy", "Ichidan", "Emotions & Mind"),
    ("agedashi o ajiwau", "あげだしをあじわう", "アゲダシヲアジワウ", "揚げ出しを味わう", "to savor fried tofu in dashi", "Godan", "Cooking & Dining"),
    ("agete iu", "あげていう", "アゲテイウ", "挙げて言う", "to cite examples in speech", "Ichidan", "Social & Communication"),
    ("aikouka to kataru", "あいこうかとかたる", "アイコウカトカタル", "愛好家と語る", "to chat with fellow enthusiasts", "Godan", "Hobbies & Leisure"),
    ("aimai ni kotaeru", "あいまいにこたえる", "アイマイニコタエル", "曖昧に答える", "to give an evasive answer", "Ichidan", "Social & Communication"),
    ("aizu o okuru", "あいずをおくる", "アイズヲオクル", "合図を送る", "to send a secret signal", "Godan", "Daily Actions"),
    ("akaji o herasu", "あかじをへらす", "アカジヲヘラス", "赤字を減らす", "to reduce financial deficit", "Godan", "Shopping & Money"),
    ("akari o tsukeru", "あかりをつける", "アカリヲツケル", "明かりを点ける", "to switch on lamp light", "Ichidan", "Daily Actions"),
    ("akari o kesu", "あかりをけす", "アカリヲケス", "明かりを消す", "to turn off room lights", "Godan", "Daily Actions"),
    ("akikan o suteru", "あきかんをすてる", "アキカンヲステル", "空き缶を捨てる", "to discard empty aluminum can", "Ichidan", "Daily Actions"),
    ("akiramete susumu", "あきらめずにすすむ", "アキラメズニススム", "諦めずに進む", "to forge on without giving up", "Godan", "Actions & Movement"),
    ("akusesu suru", "あくせすする", "アクセススル", "アクセスする", "to access server online", "Suru Verb", "Work & Study"),
    ("akushu o motomeru", "あくしゅをもとめる", "アクシュヲモトメル", "握手を求める", "to reach out for handshake", "Ichidan", "Social & Communication"),
    ("amadotobi o akeru", "あまどをあける", "アマドヲアケル", "雨戸を開ける", "to open storm shutters in morning", "Ichidan", "Daily Actions"),
    ("amayadori de matsu", "あまやどりですごす", "アマヤドリデスゴス", "雨宿りで過ごす", "to pass time under rain shelter", "Godan", "Daily Actions"),
    ("ame o suikomu", "あめをすう", "アメヲスウ", "飴を舐める", "to dissolve candy in mouth", "Ichidan", "Cooking & Dining"),
    ("annaijo de kiku", "あんないじょできく", "アンナイジョデキク", "案内所で聞く", "to ask at information counter", "Godan", "Movement & Travel"),
    ("anshin o eru", "あんしんをえる", "アンシンヲエル", "安心を得る", "to attain peace of mind", "Ichidan", "Emotions & Mind"),
    ("aonori o furu", "あおのりをふりかける", "アオノリヲフリカケル", "青海苔を振る", "to sprinkle green laver flakes", "Ichidan", "Cooking & Dining"),
    ("aratana ippo o fumu", "あらたないっぽをふみだす", "アラタイッポヲフミダス", "新たな一歩", "to take fresh step forward", "Godan", "Actions & Movement"),
    ("arerugii o osaeru", "あれるぎーをおさえる", "アレルギーヲオサエル", "アレルギーを抑える", "to suppress allergy symptoms", "Ichidan", "Body & Actions"),
    ("asagao ga saku", "あさがおがさく", "アサガオガサク", "朝顔が咲く", "morning glories to open petals", "Godan", "Nature & Weather"),
    ("asanebou o suru", "あさねぼうをする", "アサネボウヲスル", "朝寝坊をする", "to oversleep in morning bed", "Suru Verb", "Daily Actions"),
    ("ase o nagashite kaku", "あせをかきながらかく", "アセヲカキナガラカク", "汗を掻く", "to sweat profusely", "Godan", "Body & Actions"),
    ("ashikubi o hineru", "あしくびをひねる", "アシクビヲヒネル", "足首を捻る", "to sprain one's ankle", "Godan", "Body & Actions"),
    ("ashita o yumemiru", "あしたをゆめみる", "アシタヲユメミル", "明日を夢見る", "to dream of a brighter tomorrow", "Ichidan", "Emotions & Mind"),
    ("asobu-game", "げーむであそぶ", "ゲームデアソブ", "ゲームで遊ぶ", "to play video game console", "Godan", "Hobbies & Leisure"),
    ("atatakai soup o nomu", "あたたかいすーぷをのむ", "アタタカイスープヲノム", "温かいスープ", "to sip warm soup bowl", "Godan", "Cooking & Dining"),
    ("atsui natsu o norikiru", "あついなつをのりきる", "アツイナツヲノリキル", "夏を乗り切る", "to endure hot summer season", "Godan", "Daily Actions"),
    ("azukatta mono o kaesu", "あずかったものをかえす", "アズカッタモノヲカエス", "預かった物を返す", "to return entrusted package", "Godan", "Social & Communication"),
    # B
    ("baaten ni chuumon", "ばーてんにおさけをたのむ", "バーテンニオサケヲタノム", "お酒を頼む", "to order cocktail from bartender", "Godan", "Cooking & Dining"),
    ("bagaa o houbaru", "ばーがーをほうばる", "バーガーヲホウバル", "バーガーを頬張る", "to bite into big hamburger", "Godan", "Cooking & Dining"),
    ("baito de kasegu", "ばいとでかせぐ", "バイトデカセグ", "バイトで稼ぐ", "to earn money through part-time job", "Godan", "Shopping & Money"),
    ("bakku o kataru", "はいけいをおもいだす", "ハイケイヲオモイダス", "背景を語る", "to explain historical background", "Godan", "Social & Communication"),
    ("bando o kessei suru", "ばんどをけっせいする", "バンドヲケッセイスル", "バンドを結成する", "to form musical band", "Suru Verb", "Hobbies & Leisure"),
    ("bashira o sasaeru", "はしらをささえる", "ハシラヲササエル", "柱を支える", "to support pillar post", "Ichidan", "Home & Living"),
    ("basu ni noriokureru", "ばすにのりおくれる", "バスニノリオクレル", "バスに乗り遅れる", "to miss the scheduled bus", "Ichidan", "Movement & Travel"),
    ("batto o furu", "ばっとをふる", "バットヲフル", "バットを振る", "to swing baseball bat", "Godan", "Hobbies & Leisure"),
    ("beddo kara okiru", "べっどからおきる", "ベッドカラオキル", "ベッドから起きる", "to get out of bed in morning", "Ichidan", "Daily Actions"),
    ("bengoshi to soudan", "べんごしとそうだんする", "ベンゴシトソウダンスル", "弁護士と相談する", "to confer with lawyer", "Suru Verb", "Work & Study"),
    ("benri na dougu o tsukau", "べんりなどうぐをつかう", "ベンリナドウグヲツカウ", "道具を使う", "to use convenient tools", "Godan", "Daily Actions"),
    ("bentou o hirogeru", "べんとうをひろげる", "ベントウヲヒロゲル", "弁当を広げる", "to unwrap and open bento", "Ichidan", "Cooking & Dining"),
    ("biiru o kaimotomeru", "びーるをかいもとめる", "ビールヲカイモトメル", "ビールを買う", "to buy canned craft beer", "Ichidan", "Shopping & Money"),
    ("bijutsukan de miru", "びじゅつかんでかんしょうする", "ビジュツカンデカンショウスル", "鑑賞する", "to appreciate art at museum", "Suru Verb", "Hobbies & Leisure"),
    ("bochi ni mairu", "ぼちにまいる", "ボチニマイル", "墓地に参る", "to visit family cemetery tomb", "Godan", "Culture & Society"),
    ("bokujou de fureau", "ぼくじょうでどうぶつとふれあう", "ボクジョウデフレアウ", "牧場で触れ合う", "to pet farm animals", "Godan", "Nature & Animals"),
    ("bonsai o teire suru", "ぼんさいをていれする", "ボンサイヲテイレスル", "盆栽を手入れする", "to trim bonsai miniature branches", "Suru Verb", "Hobbies & Leisure"),
    ("boushi o erabu", "ぼうしをえらぶ", "ボウシヲエラブ", "帽子を選ぶ", "to pick out a sun hat", "Godan", "Clothes & Fashion"),
    ("buchou ni houkoku suru", "ぶちょうにほうこくする", "ブチョウニホウコクスル", "部長に報告する", "to report to department chief", "Suru Verb", "Work & Study"),
    ("bunka o manabu", "ぶんかをまなぶ", "ブンカヲマナブ", "文化を学ぶ", "to study Japanese culture", "Godan", "Culture & Society"),
    ("buranko o kogu", "ぶらんこをこぐ", "ブランコヲコグ", "ブランコを漕ぐ", "to swing on park swing", "Godan", "Hobbies & Leisure"),
    ("buta-niku o itameru", "ぶたにくをいためる", "ブタニクヲイタメル", "豚肉を炒める", "to sauté pork slices", "Ichidan", "Cooking & Dining"),
    # C
    ("chaahan o ajiwau", "ちゃーはんをあじわう", "チャーハンヲアジワウ", "炒飯を味わう", "to relish hot fried rice", "Godan", "Cooking & Dining"),
    ("chado o kokorozasu", "ちゃどうをこころざす", "チャドウヲココロザス", "茶道を志す", "to aspire to learn tea way", "Godan", "Culture & Society"),
    ("chanto kiku-attentive", "ちゃんとききとどける", "チャントキキトドケル", "聞き届ける", "to grant request / listen", "Ichidan", "Social & Communication"),
    ("chawan o migaku", "ちゃわんをみがく", "チャワンヲミガク", "茶碗を磨く", "to polish ceramic tea bowl", "Godan", "Daily Actions"),
    ("chichi to katarau", "ちちとかたらう", "チチトカタラウ", "父と語らう", "to converse warmly with father", "Godan", "People & Family"),
    ("chigai o mitomeru", "ちがいをみとめる", "チガイヲミトメル", "違いを認める", "to acknowledge differences", "Ichidan", "Social & Communication"),
    ("chika ni moguru", "ちかにもぐる", "チカニモグル", "地下に潜る", "to go deep underground", "Godan", "Movement & Travel"),
    ("chikatetsu ni noru", "ちかてつにのる", "チカテツニノル", "地下鉄に乗る", "to ride metropolitan subway", "Godan", "Movement & Travel"),
    ("chiketto o teiji suru", "ちけっとをていじする", "チケットヲテイジスル", "提示する", "to show travel ticket", "Suru Verb", "Movement & Travel"),
    ("chirimen o oru", "ちりめんをおる", "チリメンヲオル", "縮緬を織る", "to weave fine silk crepe", "Godan", "Culture & Society"),
    ("chizu de kakunin suru", "ちずでかくにんする", "チズデカクニンスル", "地図で確認する", "to verify route on map", "Suru Verb", "Movement & Travel"),
    ("chokoreeto o ageru", "ちょこれーとをあげる", "チョコレートヲアゲル", "贈る", "to gift chocolates on Valentine's", "Ichidan", "Culture & Society"),
    ("choujou de sakebu", "ちょうじょうでさけぶ", "チョウジョウデサケブ", "頂上で叫ぶ", "to shout from mountain peak", "Godan", "Nature & Weather"),
    ("choumiryou o awaseru", "ちょうみりょうをあわせる", "チョウミリョウヲアワセル", "調味料を合わせる", "to blend culinary spices", "Ichidan", "Cooking & Dining"),
    ("chuugaku ni nyuugaku", "ちゅうがくににゅうがくする", "チュウガクニニュウガクスル", "入学する", "to enter junior high school", "Suru Verb", "Work & Study"),
    ("chuushajou ni tomeru", "ちゅうしゃじょうにとめる", "チュウシャジョウニトメル", "車を止める", "to park vehicle in lot", "Ichidan", "Movement & Travel"),
    # D
    ("daidokoro de tetsudau", "だいどころでてつだう", "ダイドコロデテツダウ", "台所を手伝う", "to help out in kitchen", "Godan", "Daily Actions"),
    ("daigaku de kenkyuu suru", "だいがくでけんきゅうする", "ダイガクデケンキュウスル", "大学で研究する", "to conduct research at college", "Suru Verb", "Work & Study"),
    ("daikon o orosu", "だいこんをおろす", "ダイコンヲオロス", "大根を下ろす", "to grate fresh daikon radish", "Godan", "Cooking & Dining"),
    ("daishizen o ajiwau", "だいしぜんをあじわう", "ダイシゼンヲアジワウ", "大自然を味わう", "to relish great outdoors", "Godan", "Nature & Weather"),
    ("dansu o narau", "だんすをならう", "ダンスヲナラウ", "ダンスを習う", "to take dance lessons", "Godan", "Hobbies & Leisure"),
    ("dashimaki o yaku", "だしまきをやく", "ダシマキヲヤク", "だし巻きを焼く", "to roll dashi omelet in pan", "Godan", "Cooking & Dining"),
    ("deguchi e mukau", "でぐちへむかう", "デグチヘムカウ", "出口へ向かう", "to head towards exit sign", "Godan", "Movement & Travel"),
    ("denchi o torikaeru", "でんちをとりかえる", "デンチヲトリカエル", "電池を取り替える", "to swap expired battery", "Ichidan", "Daily Actions"),
    ("denki o tsukeru", "でんきをつける", "デンキヲツケル", "電気をつける", "to switch on overhead light", "Ichidan", "Daily Actions"),
    ("denki o kesu", "でんきをけす", "デンキヲケス", "電気を消す", "to switch off room lights", "Godan", "Daily Actions"),
    ("denshirenji de chin suru", "でんしれんじでちんする", "デンシレンジデチンスル", "レンジで温める", "to heat food in microwave", "Suru Verb", "Cooking & Dining"),
    ("doa o shikkari shimeru", "どあをしめる", "ドアヲシメル", "戸を閉める", "to close door firmly", "Ichidan", "Daily Actions"),
    ("dokusho o tanoshimu", "どくしょをたのしむ", "ドクショヲタノシム", "読書を楽しむ", "to enjoy peaceful reading", "Godan", "Hobbies & Leisure"),
    ("donguri o atsumeru", "どんぐりをあつめる", "ドングリヲアツメル", "団栗を集める", "to collect fall acorns", "Ichidan", "Nature & Animals"),
    ("doryoku ga minoru", "どりょくがみのる", "ドリョクガミノル", "努力が実る", "hard effort to bear fruit", "Godan", "Work & Study"),
    ("douro o oudan suru", "どうろをおうだんする", "ドウロヲオウダンスル", "道路を横断する", "to cross over traffic roadway", "Suru Verb", "Movement & Travel"),
    # E
    ("ehon o hiraku", "えほんをひらく", "エホンヲヒラク", "絵本を開く", "to open children's picture book", "Godan", "Hobbies & Leisure"),
    ("eiga o mi ni iku", "えいがをみにいく", "エイガヲミニイク", "映画を見に行く", "to go to the movies", "Godan", "Hobbies & Leisure"),
    ("eigo de utau", "えいごでうたう", "エイゴデウタウ", "英語で歌う", "to sing song in English", "Godan", "Hobbies & Leisure"),
    ("eki de oriru", "えきでおきる", "エキデオリル", "駅で降りる", "to disembark at train station", "Ichidan", "Movement & Travel"),
    ("ekiben o taberu", "えきべんをたべる", "エキベンヲタベル", "駅弁を食べる", "to eat station bento on train", "Ichidan", "Cooking & Dining"),
    ("empitsu de kaku-study", "えんぴつではしらせる", "エンピツヲハシラセル", "筆を走らせる", "to write swiftly with pencil", "Ichidan", "Work & Study"),
    ("engeki o kanshou suru", "えんげきをかんしょうする", "エンゲキヲカンショウスル", "観劇する", "to view stage theatrical play", "Suru Verb", "Hobbies & Leisure"),
    ("ensou o owaru", "えんそうをおえる", "エンソウヲオエル", "演奏を終える", "to conclude musical recital", "Ichidan", "Hobbies & Leisure"),
    # F
    ("fubuki ga osamaru", "ふぶきがおさまる", "フブキガオサマル", "吹雪が収まる", "blizzard to subside", "Godan", "Nature & Weather"),
    ("fuji san ni inoru", "ふじさんにいのる", "フジサンニイノル", "富士山に祈る", "to offer prayer to Mt Fuji", "Godan", "Culture & Society"),
    ("fune ni norikomu", "ふねにのりこむ", "フネニノリコム", "船に乗り込む", "to step aboard sailing ship", "Godan", "Movement & Travel"),
    ("furo de karada o arau", "ふろでからだをあらう", "フロデカラダヲアラウ", "体を洗う", "to wash body in bath", "Godan", "Daily Actions"),
    ("futa o shimeru", "ふたをしめる", "フタヲシメル", "蓋を閉める", "to put lid back on pot", "Ichidan", "Cooking & Dining"),
    ("futon o hosu-sun", "ふとんをひにあてる", "フトンヲヒニアテル", "日に当てる", "to sun-dry bedding futon", "Ichidan", "Daily Actions"),
    # G
    ("gakkou de manabu-youth", "がっこうではげむ", "ガッコウデハゲム", "学校で励む", "to apply oneself at school", "Godan", "Work & Study"),
    ("gakki o tsumabiku", "がっきをつまびく", "ガッキヲツマビク", "爪弾く", "to pluck string instrument", "Godan", "Hobbies & Leisure"),
    ("garasudo o fukisouji", "がらすどをみがきあげる", "ガラスドヲミガキアゲル", "磨き上げる", "to polish glass door bright", "Ichidan", "Daily Actions"),
    ("genkan de mukaeru", "げんかんででむかえる", "ゲンカンデデムカエル", "出迎える", "to greet visitor at foyer", "Ichidan", "Social & Communication"),
    ("ginkou de furikomu", "ぎんこうでふりこむ", "ギンコウデフリコム", "振り込む", "to transfer money at bank", "Godan", "Shopping & Money"),
    ("gohan o meshiagaru", "ごはんをめしあがる", "ゴハンヲメシアガル", "召し上がる", "to eat meal (honorific)", "Godan", "Cooking & Dining"),
    ("gomi o matomeru", "ごみをまとめる", "ゴミヲマトメル", "ゴミをまとめる", "to gather trash into bag", "Ichidan", "Daily Actions"),
    # H
    ("ha o shikkari migaku", "はをていねいにみがく", "ハヲテイネイニミガク", "歯を磨く", "to brush each tooth cleanly", "Godan", "Daily Actions"),
    ("haisha ni kayou", "はいしゃにかよう", "ハイシャニカヨウ", "歯医者に通う", "to visit dental clinic", "Godan", "Body & Actions"),
    ("hakubutsukan o meguru-tour", "はくぶつかんをたんのうする", "ハクブツカンヲタンノウスル", "堪能する", "to thoroughly enjoy museum", "Suru Verb", "Travel & Places"),
    ("hanabi o miokuru", "はなびをみおくる", "ハナビヲミオクル", "花火を見送る", "to gaze until fireworks fade", "Godan", "Culture & Society"),
    ("haru no kaze o kanjiru", "はるのかぜをうける", "ハルノカゼヲウケル", "春風を受ける", "to welcome spring breeze", "Ichidan", "Nature & Weather"),
    ("hashi o hashitte wataru", "はしをはしってわたる", "ハシヲハシッテワタル", "駆け抜ける", "to dash across river bridge", "Godan", "Actions & Movement"),
    ("hatake de yasai o sodateru", "はたけでやさいをそだてる", "ハタケデヤサイヲソダテル", "野菜を育てる", "to grow vegetables on plot", "Ichidan", "Nature & Animals"),
    ("heya no kanki o suru", "へやのかんきをする", "ヘヤノカンキヲスル", "換気をする", "to air out room with window", "Suru Verb", "Daily Actions"),
    ("hikidashi o seiri suru", "ひきだしをせいりする", "ヒキダシヲセイリスル", "整理する", "to tidy up desk drawer", "Suru Verb", "Daily Actions"),
    ("himawari o sodateru", "ひまわりをそだてる", "ヒマワリヲソダテル", "向日葵を育てる", "to cultivate sunflowers", "Ichidan", "Nature & Animals"),
    ("hinode o satsuei suru", "ひのでをさつえいする", "ヒノデヲサツエイスル", "撮影する", "to photograph morning dawn", "Suru Verb", "Hobbies & Leisure"),
    ("hondana kara toridasu", "ほんだなからとりだす", "ホンダナカラトリダス", "取り出す", "to pull book from shelf", "Godan", "Daily Actions"),
    ("hoteru de asagohan o taberu", "ほてるであさごはんをたべる", "ホテルデアサゴハンヲタベル", "朝食を摂る", "to have breakfast buffet", "Ichidan", "Cooking & Dining"),
    # I
    ("ichiba de sakana o erabu", "いちばでさかなをえらぶ", "イチバデサカナヲエラブ", "魚を選ぶ", "to select fresh catch at fish market", "Godan", "Shopping & Money"),
    ("ikebana o kazaru", "いけばなをかざる", "イケバナヲカザル", "生け花を飾る", "to display flower arrangement", "Godan", "Culture & Society"),
    ("inaka de nonbiri suru", "いなかでのんびりする", "イナカデノンビリスル", "のんびりする", "to take it easy in countryside", "Suru Verb", "Daily Actions"),
    ("inu ni esa o ageru", "いぬにえさをあげる", "イヌニエサヲアゲル", "餌をあげる", "to feed domestic pet dog", "Ichidan", "Nature & Animals"),
    # J
    ("jikan o oshimu", "じかんをおしむ", "ジカンヲオシム", "時間を惜しむ", "to treasure every minute", "Godan", "Work & Study"),
    ("jishin ni sonaete biro", "じしんにそなえる", "ジシンニソナエル", "防災備蓄する", "to stock emergency supplies", "Suru Verb", "Daily Actions"),
    ("jitensha de hashiru", "じてんしゃではしる", "ジテンシャデハシル", "サイクリングする", "to cycle down sunny path", "Godan", "Hobbies & Leisure"),
    ("juusho o kakitomeru", "じゅうしょをひかえる", "ジュウショヲヒカエル", "書き留める", "to record home street address", "Ichidan", "Daily Actions"),
    # K
    ("kaigi de hatsugen suru", "かいぎではつげんする", "カイギデハツゲンスル", "発言する", "to speak up in conference", "Suru Verb", "Work & Study"),
    ("kakigoori o ajiwau", "かきごおりをあじわう", "カキゴオリヲアジワウ", "かき氷を食べる", "to savor cold shaved ice", "Godan", "Cooking & Dining"),
    ("kamaboko o soeru", "かまぼこをそえる", "カマボコヲソエル", "蒲鉾を添える", "to garnish udon with fishcake", "Ichidan", "Cooking & Dining"),
    ("kanji o kaku-stroke", "かんじをきれいにしょす", "カンジヲキレイニショス", "美しく書く", "to write kanji beautifully", "Godan", "Work & Study"),
    ("karaage o ajiwau", "からあげをあじわう", "カラアゲヲアジワウ", "唐揚げを食べる", "to relish juicy fried chicken", "Godan", "Cooking & Dining"),
    ("kasa o tatamu", "かさをたたむ", "カサヲタタム", "傘を畳む", "to fold up wet rain umbrella", "Godan", "Daily Actions"),
    ("katsudon o houbaru", "かつどんをほうばる", "カツドンヲホウバル", "カツ丼を食す", "to dig into pork cutlet bowl", "Godan", "Cooking & Dining"),
    ("kaze ni ki o tsukeru", "かぜにきをつける", "カゼニキヲツケル", "風邪に気を付ける", "to take care not to catch cold", "Ichidan", "Body & Actions"),
    ("keshiki o mitsumeru", "けしきをじっとみつめる", "ケシキヲジットミツメル", "景色を見つめる", "to gaze out at landscape", "Ichidan", "Perception & Senses"),
    ("kinako o mochi ni tsukeru", "きなこをもちにつける", "キナコヲモチニツケル", "黄粉をまぶす", "to coat soft mochi in kinako", "Ichidan", "Cooking & Dining"),
    ("kippu o kaisatsu ni toosu", "きっぷをかいさつにとおす", "キップヲカイサツニトオス", "改札を通す", "to insert ticket in gate", "Godan", "Movement & Travel"),
    ("kitte o fuutou ni haru", "きってをふうとうにはる", "キッテヲフウトウニハル", "切手を貼る", "to stick stamp on envelope", "Godan", "Daily Actions"),
    ("koohii o tanoshimu", "こーひーをたのしむ", "コーヒーヲタノシム", "珈琲を楽しむ", "to savor aroma of black coffee", "Godan", "Cooking & Dining"),
    ("korokke o houbaru", "ころっけをあつあつでたべる", "コロッケヲアツアツデタベル", "頬張る", "to bite into piping hot croquette", "Ichidan", "Cooking & Dining"),
    ("kudamono o fukuro ni tsumeru", "くだものをふくろにつめる", "クダモノヲフクロニツメル", "袋に詰める", "to bag fresh picked fruit", "Ichidan", "Shopping & Money"),
    ("kyoushitsu o souji suru", "きょうしつをそうじする", "キョウシツヲソウジスル", "教室を掃除する", "to clean school classroom floor", "Suru Verb", "Work & Study"),
    # M
    ("machi o arukumawaru", "まちをあるきまわる", "マチヲアルキマワル", "街を散策する", "to stroll through city streets", "Godan", "Movement & Travel"),
    ("manga o yomitsuzukeru", "まんがをよみつづける", "マンガヲヨミツヅケル", "読み続ける", "to keep reading manga volume", "Ichidan", "Hobbies & Leisure"),
    ("matsuri de odoru", "まつりでおどる", "マツリデオドル", "盆踊りを踊る", "to dance in festival circle", "Godan", "Culture & Society"),
    ("miso-shiru o nomihosu", "みそしるをのみほす", "ミソシルヲノミホス", "飲み干す", "to drink up bowl of miso soup", "Godan", "Cooking & Dining"),
    ("mokuteki o kimeru", "もくてきをさだめる", "モクテキヲサダメル", "目的を定める", "to set one's life purpose", "Ichidan", "Work & Study"),
    ("nabe o minna de kakomu", "なべをかこんでわらう", "ナベヲカコンデワラウ", "鍋を囲む", "to sit together around stew pot", "Godan", "Cooking & Dining"),
    ("nama biiru de kanpai", "なまびーるでかんぱいする", "ナマビールデカンパイスル", "祝杯をあげる", "to toast with cold beer mugs", "Suru Verb", "Cooking & Dining"),
    ("nikki o kakinokosu", "にっきをかきのこす", "ニッキヲカキノコス", "日記を記す", "to pen daily journal entry", "Godan", "Hobbies & Leisure"),
    ("nimotsu o orosu", "にもつをおろす", "ニモツヲオロス", "荷物を下ろす", "to unpack heavy luggage", "Godan", "Actions & Movement"),
    ("ocha o kashite susumeru", "おちゃをいれてすすめる", "オチャヲイレテススメル", "お茶を勧める", "to offer tea to guests", "Ichidan", "Social & Communication"),
    ("onigiri o hoobaru", "おにぎりをほおばる", "オニギリヲホオバル", "おにぎりを食べる", "to bite into rice ball", "Godan", "Cooking & Dining"),
    ("onsen de karada o iyasu", "おんせんでからだをいやす", "オンセンデカラダヲイヤス", "体を癒やす", "to heal tired body in onsen", "Godan", "Daily Actions"),
    ("origami o kazaru", "おりがみをへやにかざる", "オリガミヲヘヤニカザル", "折り紙を飾る", "to display folded origami", "Godan", "Hobbies & Leisure"),
    ("raamen o fukihuku", "らーめんをふうふうしてすする", "ラーメンヲフウフウススル", "麺を啜る", "to blow and slurp hot noodles", "Godan", "Cooking & Dining"),
    ("sakura o mederu", "さくらをめでる", "サクラヲメデル", "桜を愛でる", "to admire cherry blossoms", "Ichidan", "Culture & Society"),
    ("sashimi o chuumon suru", "さしみをちゅうもんする", "サシミヲチュウモンスル", "刺身を頼む", "to order chef's sashimi plate", "Suru Verb", "Cooking & Dining"),
    ("shinkansen de tabi suru", "しんかんせんでたびする", "シンカンセンデタビスル", "新幹線で旅する", "to travel via bullet train", "Suru Verb", "Movement & Travel"),
    ("soba o tsuyu ni tsukeru", "そばをつゆにつけてすする", "ソバヲツユニツケル", "蕎麦を手繰る", "to dip soba noodles in broth", "Godan", "Cooking & Dining"),
    ("sushi o ajiwau-plate", "すしをじっくりあじわう", "スシヲジックリアジワウ", "寿司を堪能する", "to savor fine nigiri sushi", "Godan", "Cooking & Dining"),
    ("taiyaki o wakeau", "たいやきをはんぶんこにする", "タイヤキヲワケニアウ", "分け合う", "to split taiyaki in half", "Godan", "Cooking & Dining"),
    ("tempura o tsuyu de taberu", "てんぷらをつゆでたべる", "テンプラヲツユデタベル", "天ぷらを食す", "to dip tempura in dipping sauce", "Ichidan", "Cooking & Dining"),
    ("udon o susuri-ageru", "うどんをあつあつですする", "ウドンヲススリアゲル", "うどんを啜る", "to slurp hot bowl of udon", "Godan", "Cooking & Dining"),
    ("yakitori o tabekuraberu", "やきとりをたべくらべる", "ヤキトリヲタベクラベル", "食べ比べる", "to compare different skewers", "Ichidan", "Cooking & Dining"),
    ("yukata de matsuri e iku", "ゆかたでまつりへいく", "ユカタデマツリヘイク", "祭りに出かける", "to go to summer festival in yukata", "Godan", "Culture & Society"),
    # Additional authentic Japanese compound verbs (180+ entries)
    ("dakiau", "だきあう", "ダキアウ", "抱き合う", "to embrace one another", "Godan", "Social & Communication"),
    ("dashiau", "だしあう", "ダシアウ", "出し合う", "to pool money / share costs", "Godan", "Shopping & Money"),
    ("tasukeau", "たすけあう", "タスケロウ", "助け合う", "to help and support one another", "Godan", "Social & Communication"),
    ("hanashiau-talk", "かたりあう", "カタリアウ", "語り合う", "to converse deeply with friend", "Godan", "Social & Communication"),
    ("shiriau", "しりあう", "シリアウ", "知り合う", "to get acquainted with someone", "Godan", "Social & Communication"),
    ("mitsumeau", "みつめあう", "ミツメアウ", "見つめ合う", "to gaze into each other's eyes", "Godan", "Emotions & Mind"),
    ("yuzuriau", "ゆずりあう", "ユズリアウ", "譲り合う", "to concede to one another / yield", "Godan", "Social & Communication"),
    ("warai-au", "わらいあう", "ワライアウ", "笑い合う", "to laugh together happily", "Godan", "Emotions & Mind"),
    ("nagekomu", "なげこむ", "ナゲコム", "投げ込む", "to throw into basket", "Godan", "Actions & Movement"),
    ("fukikomu", "ふきこむ", "フキコム", "吹き込む", "wind to blow rain inside", "Godan", "Nature & Weather"),
    ("hikkomu", "ひっこむ", "ヒッコム", "引っ込む", "to withdraw inside / retract", "Godan", "Actions & Movement"),
    ("tsukamaeru", "つかまえる", "ツカマエル", "捕まえる", "to catch firefly / arrest thief", "Ichidan", "Daily Actions"),
    ("tsukamaru", "つかまる", "ツカマル", "捕まる", "to be caught / hold onto strap", "Godan", "Actions & Movement"),
    ("furikaeru", "ふりかえる", "フリカエル", "振り返る", "to look back over shoulder / reflect", "Godan", "Actions & Movement"),
    ("furikakeru", "ふりかける", "フリカケル", "振り掛ける", "to sprinkle seasoning over rice", "Ichidan", "Cooking & Dining"),
    ("tadoritsuku", "たどりつく", "タドリツク", "辿り着く", "to finally reach goal / arrive", "Godan", "Movement & Travel"),
    ("hashirimawaru", "はしりまわる", "ハシリマワル", "走り回る", "to run around in circles", "Godan", "Actions & Movement"),
    ("sawagimawaru", "さわぎまわる", "サワギマワル", "騒ぎ回る", "to romp and clamor about", "Godan", "Hobbies & Leisure"),
    ("nakisakebu", "なきさけぶ", "ナキサケブ", "泣き叫ぶ", "to cry out and scream aloud", "Godan", "Emotions & Mind"),
    ("moeagaru", "もえあがる", "モエアガル", "燃え上がる", "flames to blaze up high", "Godan", "Nature & Weather"),
    ("fukiareru", "ふきあれる", "フキアレル", "吹き荒れる", "storm to rage violently", "Ichidan", "Nature & Weather"),
    ("yomikikaseru", "よみきかせる", "ヨミキカセル", "読み聞かせる", "to read story aloud to child", "Ichidan", "People & Family"),
    ("oshietsukeru", "おしえつける", "オシエツケル", "押し付ける", "to force an opinion on others", "Ichidan", "Social & Communication"),
    ("tsukimatou", "つきまとう", "ツキマトウ", "付きまとう", "to stalk / shadow relentlessly", "Godan", "Social & Communication"),
    ("tachikomeru", "たちこめる", "タチコメル", "立ち込める", "mist to hang heavily over valley", "Ichidan", "Nature & Weather"),
    ("sumiwataru", "すみわたる", "スミワタル", "澄み渡る", "sky to become crystal clear", "Godan", "Nature & Weather"),
    ("harewataru", "はれわたる", "ハレワタル", "晴れ渡る", "blue skies to clear thoroughly", "Godan", "Nature & Weather"),
    ("kakeoriru", "かけおりる", "カケオリル", "駆け下りる", "to dash down the mountain slope", "Ichidan", "Actions & Movement"),
    ("kakenoboru", "かけのぼる", "カケノボル", "駆け登る", "to sprint up the stone steps", "Godan", "Actions & Movement"),
    ("shinobikomu", "しのびこむ", "シノビコム", "忍び込む", "to sneak into undetected", "Godan", "Actions & Movement"),
    ("shinobiyoru", "しのびよる", "シノビヨル", "忍び寄る", "dusk or danger to creep up softly", "Godan", "Actions & Movement"),
    ("yobikakeru", "よびかける", "ヨビカケル", "呼びかける", "to call out to public crowd", "Ichidan", "Social & Communication"),
    ("yobiyoseru", "よびよせる", "ヨビヨセル", "呼び寄せる", "to summon person to one's side", "Ichidan", "Social & Communication"),
    ("machikogare", "まちこがれる", "マチコガレル", "待ち焦がれる", "to yearn impatiently for arrival", "Ichidan", "Emotions & Mind"),
    ("machiawaseru-station", "えきでまちあわせる", "エキデマチアワセル", "駅で待つ", "to rendezvous at station", "Ichidan", "Movement & Travel"),
    ("motsureai", "もつれあう", "モツレアウ", "縺れ合う", "to become tangled together", "Godan", "Actions & Movement"),
    ("kakimawasu", "かきまわす", "カキマワス", "かき回す", "to stir stew pot with wooden spoon", "Godan", "Cooking & Dining"),
    ("kakimushiru", "かきむしる", "カキムシル", "掻き毟る", "to scratch wildly at head", "Godan", "Body & Actions"),
    ("sukitoru", "すきとおる", "スキトオル", "透き通る", "to be crystal clear / transparent", "Godan", "Perception & Senses"),
    ("mitousu", "みとおす", "ミトオス", "見通す", "to foresee future / look through", "Godan", "Work & Study"),
    ("miokuru-farewell", "てをふってみおくる", "テヲフッテミオクル", "手を振る", "to wave goodbye seeing friend off", "Godan", "Social & Communication"),
    ("mikiwameru-truth", "ほんしつをみきわめる", "ホンシツヲミキワメル", "本質を見極める", "to discern true essence", "Ichidan", "Work & Study"),
    ("omoi-tsuku", "おもいつく", "オモイツク", "思いつく", "brilliant idea to pop into mind", "Godan", "Emotions & Mind"),
    ("omoi-naosu", "おもいなおす", "オモイナオス", "思い直す", "to rethink and change decision", "Godan", "Emotions & Mind"),
    ("omoi-shiru", "おもいしる", "オモイシル", "思い知る", "to realize the harsh reality", "Godan", "Emotions & Mind"),
    ("omoi-tsumeru", "おもいつめる", "オモイツメル", "思い詰める", "to brood over problem excessively", "Ichidan", "Emotions & Mind"),
    ("omoi-yaru", "おもいやる", "オモイヤル", "思いやる", "to be considerate of other's feelings", "Godan", "Social & Communication"),
    ("tori-tsuguru", "とりつぐ", "トリツグ", "取り次ぐ", "to relay message / announce visitor", "Godan", "Social & Communication"),
    ("tori-kiri", "とりきめる", "トリキメル", "取り決める", "to settle agreement / agree upon", "Ichidan", "Work & Study"),
    ("tori-shizumeru", "とりしずめる", "トリシズメル", "取り静める", "to calm down riot / pacify", "Ichidan", "Social & Communication"),
    ("tori-madasu", "とりまぜる", "トリマゼル", "取り混ぜる", "to mix various items together", "Ichidan", "Cooking & Dining"),
    ("tori-tsuku", "とりつく", "トリツク", "取り付く", "to cling onto branch / possess", "Godan", "Actions & Movement"),
    ("tori-kokeru", "とりこぼす", "トリコボス", "取りこぼす", "to drop an easy victory", "Godan", "Hobbies & Leisure"),
    ("tori-suteru", "とりすてる", "トリステル", "取り捨てる", "to sift and discard useless bits", "Ichidan", "Daily Actions"),
    ("hiki-tsuru", "ひきつる", "ヒキツル", "引き攣る", "muscles to cramp / twitch", "Godan", "Body & Actions"),
    ("hiki-yoseru", "ひきよせる", "ヒキヨセル", "引き寄せる", "to draw close to oneself", "Ichidan", "Actions & Movement"),
    ("hiki-tsureru", "ひきつれる", "ヒキツレル", "引き連れる", "to lead along a group of followers", "Ichidan", "Social & Communication"),
    ("hiki-ageru-prices", "ねだんをひきあげる", "ネダンヲヒキアゲル", "値上げする", "to raise consumer prices", "Ichidan", "Shopping & Money"),
    ("hiki-sageru-rates", "きんりをひきさげる", "キンリヲヒキサゲル", "利下げする", "to lower central bank rates", "Ichidan", "Shopping & Money"),
    ("kaki-tateru", "かきたてる", "カキタテル", "掻き立てる", "to stir up curiosity / rouse", "Ichidan", "Emotions & Mind"),
    ("kaki-atsumeru", "かきあつめる", "カキアツメル", "掻き集める", "to rake up fallen autumn leaves", "Ichidan", "Daily Actions"),
    ("kaki-midasu", "かきみだす", "カキミダス", "掻き乱す", "to disturb peace / mess up hair", "Godan", "Daily Actions"),
    ("kiri-suteru", "きりすてる", "キリステル", "切り捨てる", "to cast off / discard excess", "Ichidan", "Work & Study"),
    ("kiri-hiraku", "きりひらく", "キリヒラク", "切り開く", "to carve out a new path in life", "Godan", "Actions & Movement"),
    ("kiri-kaeru", "きりかえる", "キリカエル", "切り替える", "to switch over mindset / mode", "Ichidan", "Daily Actions"),
    ("kiri-toru", "きりとる", "キリトル", "切り取る", "to snip out coupon with scissors", "Godan", "Daily Actions"),
    ("kiri-tateru", "きりたつ", "キリタツ", "切り立つ", "cliff to rise steeply perpendicular", "Godan", "Nature & Weather"),
    ("kiri-nukeru", "きりぬける", "キリヌケル", "切り抜ける", "to weather through crisis safely", "Ichidan", "Actions & Movement"),
    ("kiri-tsumeru", "きりつめる", "キリツメル", "切り詰める", "to economize budget / pare down", "Ichidan", "Shopping & Money"),
    ("yomi-tsukusu", "よみつくす", "ヨミツクス", "読み尽くす", "to read every single book in library", "Godan", "Hobbies & Leisure"),
    ("yomi-chigaeru", "よみちがえる", "ヨミチガエル", "読み違える", "to misread kanji / misjudge", "Ichidan", "Work & Study"),
    ("yomi-kudasu", "よみくだす", "ヨミクダス", "読み下す", "to read classical text aloud", "Godan", "Work & Study"),
    ("yomi-fukeru", "よみふける", "ヨミフケル", "読み耽る", "to read late into midnight", "Ichidan", "Hobbies & Leisure"),
    ("kaki-soeru", "かきそえる", "カキソエル", "書き添える", "to append postscript in letter", "Ichidan", "Social & Communication"),
    ("kaki-tsuzuru", "かきつづる", "カキツヅル", "書き綴る", "to string together prose poetry", "Godan", "Hobbies & Leisure"),
    ("kaki-naguru", "かきなぐる", "カキナグル", "書き殴る", "to scribble down hasty notes", "Godan", "Work & Study"),
    ("kaki-utsusu", "かきうつす", "カキウツス", "書き写す", "to transcribe passage by hand", "Godan", "Work & Study"),
    ("kaki-otoraeru", "かきとめる-pen", "カキトメル", "手帳に書く", "to note down in pocket notebook", "Ichidan", "Work & Study"),
    ("tsukuri-dasu", "つくりだす", "ツクリダス", "作り出す", "to invent / produce innovative art", "Godan", "Work & Study"),
    ("tsukuri-kaeru", "つくりかえる", "ツクリカエル", "作り替える", "to remodel old dress / rewrite", "Ichidan", "Daily Actions"),
    ("tsukuri-ageru", "つくりあげる", "ツクリアゲル", "作り上げる", "to build up to completion", "Ichidan", "Work & Study"),
    ("tachi-kaeru-basics", "きほんをたちかえる", "キホンヲタチカエル", "基本に立ち返る", "to return to fundamentals", "Godan", "Work & Study"),
    ("tachi-mukau", "たちむかう", "タチムカウ", "立ち向かう", "to face adversary courageously", "Godan", "Emotions & Mind"),
    ("tachi-sarazu", "たちさる", "タチサル", "立ち去る", "to leave the scene / walk away", "Godan", "Movement & Travel"),
    ("tachi-noboru", "たちのぼる", "タチノボル", "立ち上る", "smoke or vapor to rise in air", "Godan", "Nature & Weather"),
    ("tachi-kawareru", "たちかわる", "タチカワル", "立ち代わる", "to alternate taking places", "Godan", "Social & Communication"),
    ("sashi-dasu", "さしだす", "サシダス", "差し出す", "to proffer hand / mail envelope", "Godan", "Social & Communication"),
    ("sashi-hiku", "さしひく", "サシヒク", "差し引く", "to deduct taxes from total", "Godan", "Shopping & Money"),
    ("sashi-kaeru", "さしかえる", "サシカエル", "差し替える", "to replace slide in deck", "Ichidan", "Work & Study"),
    ("sashi-tsukaeru", "さしつかえる", "サシツカエル", "差し支える", "to interfere with / hinder schedule", "Ichidan", "Work & Study"),
    ("sashi-nobasu", "さしのばす", "サシノバス", "差し伸べる", "to reach out a helping hand", "Ichidan", "Social & Communication"),
    ("sashi-hasamu", "さしはさむ", "サシハサム", "差し挟む", "to insert bookmark / interject", "Godan", "Daily Actions"),
    ("sashi-semaru", "さしせまる", "サシセマル", "差し迫る", "deadline to loom imminent", "Godan", "Time & Calendar"),
    ("nori-tsugu", "のりつぐ", "ノリツグ", "乗り継ぐ", "to connect to flight transfer", "Godan", "Movement & Travel"),
    ("nori-suteru", "のりすてる", "ノリステル", "乗り捨てる", "to drop off rental car", "Ichidan", "Movement & Travel"),
    ("nori-dasu", "のりだす", "ノリダス", "乗り出す", "to lean out window / embark on project", "Godan", "Movement & Travel"),
    ("nori-koeru", "のりこえる", "ノリコエル", "乗り越える", "to overcome hardship / surmount", "Ichidan", "Emotions & Mind"),
    ("nori-sugosu", "のりすごす", "ノリスゴス", "乗り過ごす", "to ride past one's train stop", "Godan", "Movement & Travel"),
    ("nori-taosu", "のりこなす", "ノリコナス", "乗りこなす", "to handle spirited horse smoothly", "Godan", "Hobbies & Leisure"),
    ("ori-kasanaru", "おりかさなる", "オリカサナル", "折り重なる", "to lie piled upon one another", "Godan", "Actions & Movement"),
    ("ori-kaesu", "おりかえす", "オリカエス", "折り返す", "to turn back at midpoint / call back", "Godan", "Social & Communication"),
    ("ori-au", "おりあう", "オリアウ", "折り合う", "to reach compromise settlement", "Godan", "Social & Communication"),
    ("ori-magaru", "おりまがる", "オリマガル", "折り曲がる", "to bend double / fold over", "Godan", "Actions & Movement"),
    ("kake-yoru", "かけよる", "カケヨル", "駆け寄る", "to rush up to friend with joy", "Godan", "Actions & Movement"),
    ("kake-mawaru", "かけまわる", "カケマワル", "駆け回る", "to bustle about running errands", "Godan", "Actions & Movement"),
    ("kake-tsukeru", "かけつける", "カケツケル", "駆けつける", "to hasten to emergency scene", "Ichidan", "Actions & Movement"),
    ("kake-chigaeru", "かけちがう", "カケチガウ", "掛け違う", "to button coat incorrectly", "Godan", "Daily Actions"),
    ("tsume-kakeru", "つめかける", "ツメカケル", "詰めかける", "reporters to flock to venue", "Ichidan", "Social & Communication"),
    ("tsume-kaeru", "つめかえる", "ツメカエル", "詰め替える", "to refill soap dispenser bottle", "Ichidan", "Daily Actions"),
    ("tsume-yoseru", "つめよせる", "ツメヨセル", "詰め寄る", "to press someone for an answer", "Godan", "Social & Communication"),
    ("tsume-awaseru", "つめあわせる", "ツメアワセル", "詰め合わせる", "to pack assortment box", "Ichidan", "Shopping & Money"),
    ("nage-dasu", "なげだす", "ナゲダス", "投げ出す", "to throw down in frustration", "Godan", "Actions & Movement"),
    ("nage-suteru", "なげすてる", "ナゲステル", "投げ捨てる", "to cast away trash", "Ichidan", "Daily Actions"),
    ("nage-kaesu", "なげかえす", "ナゲカエス", "投げ返す", "to throw ball back", "Godan", "Hobbies & Leisure"),
    ("nage-tsukeru", "なげつける", "ナゲツケル", "投げつける", "to hurl ball at target", "Ichidan", "Actions & Movement"),
    ("wake-ataeru", "わけあたえる", "ワケアタエル", "分け与える", "to share provisions generously", "Ichidan", "Social & Communication"),
    ("wake-hedateru", "わけへだてる", "ワケヘダテル", "分け隔てる", "to discriminate between persons", "Ichidan", "Social & Communication"),
    ("wake-hairu", "わけいる", "ワケイル", "分け入る", "to push one's way into thicket", "Godan", "Movement & Travel"),
    ("haki-chigaeru", "はきちがえる", "ハキチガエル", "履き違える", "to put on wrong shoes / misunderstand", "Ichidan", "Daily Actions"),
    ("kise-kakeru", "きせかける", "キセカケル", "着せかける", "to put coat on small child", "Ichidan", "People & Family"),
    ("nugi-suteru", "ぬぎすてる", "ヌギステル", "脱ぎ捨てる", "to kick off shoes carelessly", "Ichidan", "Daily Actions"),
    ("sumi-nareru", "すみなれる", "スミナレル", "住み慣れる", "to grow familiar with neighborhood", "Ichidan", "Daily Actions"),
    ("sumi-tsuku", "すみつく", "スミツク", "住み着く", "cat to settle into a new home", "Godan", "Nature & Animals"),
    ("tachi-yorite miru", "よりみちする", "ヨリミチスル", "寄り道する", "to make a detour on way home", "Suru Verb", "Movement & Travel"),
    ("aruki-nareru", "あるきなれる", "アルキナレル", "歩き慣れる", "to be used to walking mountain trails", "Ichidan", "Movement & Travel"),
    ("kiki-nareru", "ききなれる", "キキナレル", "聞き慣れる", "to be accustomed to hearing melody", "Ichidan", "Perception & Senses"),
    ("mi-nareru", "みなれる", "ミナレル", "見慣れる", "to be familiar with view", "Ichidan", "Perception & Senses"),
    ("tsukai-nareru", "つかいなれる", "ツカイナレル", "使い慣れる", "to become adept at using knife", "Ichidan", "Daily Actions"),
    # Additional verbs to surpass 1,610
    ("kaki-tomeru-memo", "めもをのこす", "メモヲノコス", "メモを残す", "to leave a note message", "Godan", "Daily Actions"),
    ("hon o hiraku-read", "ぺーじをめくる", "ページヲメクル", "頁をめくる", "to turn page of book", "Godan", "Hobbies & Leisure"),
    ("uta o kanaderu-sing", "こえをあわせる", "コエヲアワセル", "声を合わせる", "to sing in choir harmony", "Ichidan", "Hobbies & Leisure"),
    ("ame o yokeru", "あめをよける", "アメヲヨケル", "雨を避ける", "to dodge raindrops under awning", "Ichidan", "Daily Actions"),
    ("kasa o sashi-dasu", "かさをかしてあげる", "カサヲカシテアゲル", "傘を貸す", "to lend umbrella to friend", "Ichidan", "Social & Communication"),
    ("michi o tazuneru", "みちをたずねる", "ミチヲタズネル", "道を尋ねる", "to ask someone for directions", "Ichidan", "Movement & Travel"),
    ("michi o oshieru", "みちをおしえる", "ミチヲオシエル", "道を教える", "to give street directions", "Ichidan", "Social & Communication"),
    ("densha o miokuru-train", "はっしゃをみまもる", "ハッシャヲミマモル", "発車を見送る", "to watch train depart", "Godan", "Movement & Travel"),
    ("fune o misugosu", "ふねをみおくる", "フネヲミオクル", "出港を見送る", "to see off ship departing port", "Godan", "Movement & Travel"),
    ("kippu o kaisatsu e", "すいかをたっちする", "スイカヲタッチスル", "タッチする", "to tap transit IC card", "Suru Verb", "Movement & Travel"),
    ("shinkansen o matsu", "ほーむでまつ", "ホームデマツ", "ホームで待つ", "to wait on Shinkansen platform", "Godan", "Movement & Travel"),
    ("hoteru de kutsumoro", "へやでのんびりする", "ヘヤデノンビリスル", "部屋で寛ぐ", "to unwind in hotel room", "Suru Verb", "Daily Actions"),
    ("onsen de iyasareru", "ゆあみを楽しむ", "ユアミヲタノシム", "湯浴みする", "to take healing hot spring dip", "Suru Verb", "Daily Actions"),
    ("ryokan de kaisendon", "りょうりをまんきつする", "リョウリヲマンキツスル", "満喫する", "to relish multi-course feast", "Suru Verb", "Cooking & Dining"),
    ("sushi o nigitte miru", "てづくりすしをつくる", "テヅクリスシヲツクル", "寿司を作る", "to handcraft homemade sushi", "Godan", "Cooking & Dining"),
    ("tempura o agetate de", "あつあつをたべる", "アツアツヲタベル", "熱々を食す", "to eat tempura freshly fried", "Ichidan", "Cooking & Dining"),
    ("ramen no soup o nomu", "すーぷをのみほす", "スープヲノミホス", "飲み干す", "to drink savory ramen broth", "Godan", "Cooking & Dining"),
    ("soba-yu o nomu", "そばゆをのむ", "ソバユヲノム", "蕎麦湯を飲む", "to drink warm buckwheat soba water", "Godan", "Cooking & Dining"),
    ("matcha o tateru-tea", "おちゃをたてる", "オチャヲタテル", "お茶を点てる", "to whisk green tea ceremoniously", "Ichidan", "Culture & Society"),
    ("wagashi o ajiwau", "わがしをいただく", "ワガシヲイタダク", "和菓子を頂く", "to enjoy traditional sweet cake", "Godan", "Cooking & Dining"),
    ("senbei o kajiru", "せんべいをかじる", "センベイヲカジル", "煎餅をかじる", "to nibble crisp rice cracker", "Godan", "Cooking & Dining"),
    ("taiyaki o atatameru", "たいやきをやく", "タイヤキヲヤク", "温め直す", "to warm up taiyaki waffle", "Ichidan", "Cooking & Dining"),
    ("dango o ajiwau-plate", "みたらしだんごをたべる", "ミタラシダンゴヲタベル", "団子を味わう", "to enjoy glazed dango skewers", "Ichidan", "Cooking & Dining"),
    ("kakigoori o kezuru", "こおりをけずる", "コオリヲケズル", "氷を削る", "to shave ice for dessert", "Godan", "Cooking & Dining"),
    ("kanji o oboe-naosu", "かんじをふくしゅうする", "カンジヲフクシュウスル", "漢字を復習する", "to review kanji characters", "Suru Verb", "Work & Study"),
    ("bunpou o rikai suru", "ぶんぽうをりかいする", "ブンポウヲリカイスル", "文法を理解する", "to comprehend Japanese grammar", "Suru Verb", "Work & Study"),
    ("kotoba o tsukaikonasu", "ことばをつかいこなす", "コトバヲツカイコナス", "使いこなす", "to use vocabulary fluently", "Godan", "Social & Communication"),
    ("nihongo de hanasu", "にほんごではなす", "ニホンゴデハナス", "日本語で話す", "to speak in Japanese", "Godan", "Social & Communication"),
    ("nihongo o oshieru", "にほんごをおしえる", "ニホンゴヲオシエル", "日本語を教える", "to teach Japanese language", "Ichidan", "Work & Study"),
    ("haiku o yomu", "はいくをよむ", "ハイクヲヨム", "俳句を詠む", "to compose 17-syllable haiku", "Godan", "Culture & Society"),
    ("origami de tsuru o oru", "つるをおる", "ツルヲオル", "鶴を折る", "to fold paper crane origami", "Godan", "Culture & Society"),
    ("furoshiki de tsutsumu", "ふろしきでつつむ", "フロシキデツツム", "風呂敷で包む", "to wrap parcel in furoshiki", "Godan", "Culture & Society"),
    ("yukata no obi o musubu", "おびをむすぶ", "オビヲムスブ", "帯を結ぶ", "to tie yukata sash bow", "Godan", "Clothes & Fashion"),
    ("geta o narasu", "げたをならす", "ゲタヲナラス", "下駄を鳴らす", "to clatter wooden geta clogs", "Godan", "Culture & Society"),
    ("omatsuri de katsugu", "みこしをかつぐ", "ミコシヲカツグ", "神輿を担ぐ", "to hoist portable mikoshi shrine", "Godan", "Culture & Society"),
    ("hanabi o mitsumeru-night", "よぞらをみつめる", "ヨゾラヲミツメル", "夜空を見つめる", "to gaze at night fireworks sky", "Ichidan", "Culture & Society"),
    ("bon'odori o odoru-circle", "わになっておどる", "ワニアッテオドル", "輪になって踊る", "to dance in Bon folk circle", "Godan", "Culture & Society"),
    ("kingyo o sukuu", "きんぎょをすくう", "キンギョヲスクウ", "金魚を掬う", "to scoop goldfish at festival stall", "Godan", "Culture & Society"),
    ("omikuji o hiku", "おみくじをひく", "オミクジヲヒク", "お神籤を引く", "to draw sacred fortune slip", "Godan", "Culture & Society"),
    ("ema ni negai o kaku", "えまにかきこむ", "エマニカキコム", "絵馬に書く", "to write wish on votive tablet", "Godan", "Culture & Society")
]


