# Movement, Physical Actions, Handling, Travel, Spatial verbs
# (romaji, hiragana, katakana, kanji, meaning, type, topic)
DATA = [
    # A
    ("abakareru", "あばかれる", "アバカレル", "暴かれる", "to be exposed / disclosed", "Ichidan", "Social & Communication"),
    ("abaku", "あばく", "アバク", "暴く", "to expose / unmask", "Godan", "Social & Communication"),
    ("abiru", "あびる", "アビル", "浴びる", "to take (a shower) / bathe", "Ichidan", "Daily Actions"),
    ("abiseru", "あびせる", "アビセル", "浴びせる", "to pour upon / shower with", "Ichidan", "Daily Actions"),
    ("aburu", "あぶる", "アブル", "炙る", "to scorch / broil / grill", "Godan", "Cooking & Dining"),
    ("aeru", "あえる", "アエル", "和える", "to dress (salad / food)", "Ichidan", "Cooking & Dining"),
    ("agaku", "あがく", "アガク", "足掻く", "to struggle / paw the ground", "Godan", "Actions & Movement"),
    ("agaru", "あがる", "アガル", "上がる", "to go up / rise", "Godan", "Actions & Movement"),
    ("ageru", "あげる", "アゲル", "上げる", "to give / raise / lift", "Ichidan", "Daily Actions"),
    ("agumu", "あぐむ", "アグム", "倦む", "to lose interest / tire of", "Godan", "Emotions & Mind"),
    ("aikou suru", "あいこうする", "アイコウスル", "愛好する", "to love / have a fondness for", "Suru Verb", "Hobbies & Leisure"),
    ("aisuru", "あいする", "アイスル", "愛する", "to love / hold dear", "Suru Verb", "Emotions & Mind"),
    ("ajiwau", "あじわう", "アジワウ", "味わう", "to taste / savor / relish", "Godan", "Cooking & Dining"),
    ("akirameru", "あきらめる", "アキラメル", "諦める", "to give up / resign oneself", "Ichidan", "Emotions & Mind"),
    ("akiru", "あきる", "アキル", "飽きる", "to get tired of / be satiated", "Ichidan", "Emotions & Mind"),
    ("akogareiru", "あこがれる", "アコガレル", "憧れる", "to yearn for / admire", "Ichidan", "Emotions & Mind"),
    ("akushu suru", "あくしゅする", "アクシュスル", "握手する", "to shake hands", "Suru Verb", "Social & Communication"),
    ("amayakasu", "あまやかす", "アマヤカス", "甘やかす", "to pamper / spoil rotten", "Godan", "Social & Communication"),
    ("amamu", "あむ", "アム", "編む", "to knit / braid / weave", "Godan", "Hobbies & Leisure"),
    ("annai suru", "あんないする", "アンナイスル", "案内する", "to guide / show around", "Suru Verb", "Movement & Travel"),
    ("anshin suru", "あんしんする", "アンシンスル", "安心する", "to feel relieved", "Suru Verb", "Emotions & Mind"),
    ("anzuru", "あんずる", "アンズル", "案ずる", "to be anxious about / consider", "Suru Verb", "Emotions & Mind"),
    ("aogu", "あおぐ", "アオグ", "仰ぐ", "to look up to / ask for respect", "Godan", "Actions & Movement"),
    ("aoru", "あおる", "アオル", "煽る", "to fan / instigate / agitate", "Godan", "Actions & Movement"),
    ("arasou", "あらそう", "アラソウ", "争う", "to dispute / compete / fight", "Godan", "Social & Communication"),
    ("aratameru", "あらためる", "アラタメル", "改める", "to reform / examine / renew", "Ichidan", "Daily Actions"),
    ("arau", "あらう", "アラウ", "洗う", "to wash / cleanse", "Godan", "Daily Actions"),
    ("arawareru", "あらわれる", "アラワレル", "現れる", "to appear / show up", "Ichidan", "Actions & Movement"),
    ("arawasu", "あらわす", "アラワス", "表す", "to express / signify / represent", "Godan", "Social & Communication"),
    ("aruku", "あるく", "アルク", "歩く", "to walk on foot", "Godan", "Actions & Movement"),
    ("aseru", "あせる", "アセル", "焦る", "to be in a hurry / panic", "Godan", "Emotions & Mind"),
    ("asobu", "あそぶ", "アソブ", "遊ぶ", "to play / enjoy recreation", "Godan", "Hobbies & Leisure"),
    ("ataeru", "あたえる", "アタエル", "与える", "to bestow / award / grant", "Ichidan", "Social & Communication"),
    ("atatamaru", "あたたまる", "アタタマル", "温まる", "to warm up / get warm", "Godan", "Daily Actions"),
    ("atatameru", "あたためる", "アタタメル", "温める", "to heat up / warm something", "Ichidan", "Cooking & Dining"),
    ("ataru", "あたる", "アタル", "当たる", "to strike / hit the mark", "Godan", "Actions & Movement"),
    ("ateru", "あてる", "アテル", "当てる", "to hit / guess correctly / apply", "Ichidan", "Actions & Movement"),
    ("au", "あう", "アウ", "会う", "to meet / see a person", "Godan", "Social & Communication"),
    ("ayamaru", "あやまる", "アヤマル", "謝る", "to apologize", "Godan", "Social & Communication"),
    ("ayamaru-err", "あやまる", "アヤマル", "誤る", "to make a mistake / err", "Godan", "Work & Study"),
    ("ayashimu", "あやしむ", "アヤシム", "怪しむ", "to suspect / doubt", "Godan", "Emotions & Mind"),
    ("azukaru", "あずかる", "アズカル", "預かる", "to keep in custody / take charge of", "Godan", "Social & Communication"),
    ("azukeru", "あずける", "アズケル", "預ける", "to entrust / deposit", "Ichidan", "Social & Communication"),
    # B
    ("baito suru", "ばいとする", "バイトスル", "バイトする", "to work a part-time job", "Suru Verb", "Work & Study"),
    ("bakeru", "ばける", "バケル", "化ける", "to transform oneself / disguise", "Ichidan", "Actions & Movement"),
    ("bakansu suru", "ばかんすする", "バカンススル", "バカンスする", "to take a holiday vacation", "Suru Verb", "Movement & Travel"),
    ("bakuhatsu suru", "ばくはつする", "バクハツスル", "爆発する", "to explode / detonate", "Suru Verb", "Nature & Weather"),
    ("barasu", "ばらす", "バラス", "ばらす", "to dismantle / reveal secret", "Godan", "Social & Communication"),
    ("bareru", "ばれる", "バレル", "ばれる", "to leak out / be found out", "Ichidan", "Social & Communication"),
    ("batsu suru", "ばつする", "バツスル", "罰する", "to punish / penalize", "Suru Verb", "Social & Communication"),
    ("bengou suru", "べんごする", "ベンゴスル", "弁護する", "to defend in court", "Suru Verb", "Work & Study"),
    ("benkyou suru", "べんきょうする", "ベンキョウスル", "勉強する", "to study / hit the books", "Suru Verb", "Work & Study"),
    ("bikkuri suru", "びっくりする", "ビックリスル", "吃驚する", "to be startled / surprised", "Suru Verb", "Emotions & Mind"),
    ("biru suru", "びるどする", "ビルドスル", "ビルドする", "to compile / build code", "Suru Verb", "Work & Study"),
    ("biyou suru", "びようする", "ビヨウスル", "美容する", "to perform beauty care", "Suru Verb", "Daily Actions"),
    ("biyori suru", "びよりする", "ビヨリスル", "日和見する", "to sit on the fence", "Suru Verb", "Social & Communication"),
    ("bonyari suru", "ぼんやりする", "ボンヤリスル", "ぼんやりする", "to daydream / be absent-minded", "Suru Verb", "Emotions & Mind"),
    ("bousou suru", "ぼうそうする", "ボウソウスル", "暴走する", "to run out of control", "Suru Verb", "Actions & Movement"),
    ("bouken suru", "ぼうけんする", "ボウケンスル", "冒険する", "to embark on adventure", "Suru Verb", "Movement & Travel"),
    ("bunkai suru", "ぶんかいする", "ブンカイスル", "分解する", "to disassemble / dismantle", "Suru Verb", "Work & Study"),
    ("bunseki suru", "ぶんせきする", "ブンセキスル", "分析する", "to analyze data", "Suru Verb", "Work & Study"),
    ("burasagaru", "ぶらさがる", "ブラサガル", "ぶら下がる", "to dangle / hang down", "Godan", "Actions & Movement"),
    ("buratsuku", "ぶらつく", "ブラツク", "ぶらつく", "to stroll aimlessly / loiter", "Godan", "Movement & Travel"),
    ("butsukaru", "ぶつかる", "ブツカル", "ぶつかる", "to collide with / clash", "Godan", "Actions & Movement"),
    ("butsukeru", "ぶつける", "ブツケル", "ぶつける", "to bump into / hit against", "Ichidan", "Actions & Movement"),
    # C
    ("chaahan suru", "ちゃーはんをつくる", "チャーハンヲツクル", "炒飯を作る", "to cook fried rice", "Godan", "Cooking & Dining"),
    ("charenji suru", "ちゃれんじする", "チャレンジスル", "挑戦する", "to take on a challenge", "Suru Verb", "Work & Study"),
    ("chanto suru", "ちゃんとする", "チャントスル", "ちゃんとする", "to act properly / behave", "Suru Verb", "Daily Actions"),
    ("chigau", "ちがう", "チガウ", "違う", "to differ / be distinct", "Godan", "Social & Communication"),
    ("chijimaru", "ちぢまる", "チヂマル", "縮まる", "to shrink / contract", "Godan", "Actions & Movement"),
    ("chijimu", "ちぢむ", "チヂム", "縮む", "to shrink in wash", "Godan", "Actions & Movement"),
    ("chijimeru", "ちぢめる", "チヂメル", "縮める", "to shorten / condense", "Ichidan", "Actions & Movement"),
    ("chikazuku", "ちかづく", "チカヅク", "近づく", "to approach / come near", "Godan", "Actions & Movement"),
    ("chikazukeru", "ちかづける", "チカヅケル", "近づける", "to bring close", "Ichidan", "Actions & Movement"),
    ("chirabaru", "ちらばる", "チラバル", "散らばる", "to be scattered about", "Godan", "Actions & Movement"),
    ("chirasu", "ちらす", "チラス", "散らす", "to scatter / disperse", "Godan", "Actions & Movement"),
    ("chiru", "ちる", "チル", "散る", "to scatter / fall (petals)", "Godan", "Nature & Weather"),
    ("chokkin suru", "ちょっきんする", "チョッキンスル", "ちょっきんする", "to snip with scissors", "Suru Verb", "Daily Actions"),
    ("chokushi suru", "ちょくしする", "チョクシスル", "直視する", "to look squarely in the face", "Suru Verb", "Perception & Senses"),
    ("chousei suru", "ちょうせいする", "チョウセイスル", "調整する", "to adjust / coordinate", "Suru Verb", "Work & Study"),
    ("chouwa suru", "ちょうわする", "チョウワスル", "調和する", "to harmonize with", "Suru Verb", "Social & Communication"),
    ("chuumon suru", "ちゅうもんする", "チュウモンスル", "注文する", "to place an order", "Suru Verb", "Cooking & Dining"),
    ("chuushi suru", "ちゅうしする", "チュウシスル", "中止する", "to call off / cancel", "Suru Verb", "Work & Study"),
    ("chuushin suru", "ちゅうしんとする", "チュウシントスル", "中心とする", "to center around", "Suru Verb", "Work & Study"),
    ("chuusuru", "ちゅうしゃする", "チュウシャスル", "駐車する", "to park a vehicle", "Suru Verb", "Movement & Travel"),
    # D
    ("daensuru", "だえんけいにする", "ダエンケイニスル", "楕円形にする", "to make into oval", "Suru Verb", "Work & Study"),
    ("daigaku e iku", "だいがくへいく", "ダイガクヘイク", "大学へ行く", "to attend university", "Godan", "Work & Study"),
    ("daihyou suru", "だいひょうする", "ダイヒョウスル", "代表する", "to represent / epitomize", "Suru Verb", "Social & Communication"),
    ("daisuki da", "だいすきだ", "ダイスキダ", "大好きだ", "to adore / love very much", "Suru Verb", "Emotions & Mind"),
    ("dakishimeru", "だきしめる", "ダキシメル", "抱きしめる", "to embrace tightly / hug", "Ichidan", "Actions & Movement"),
    ("daku", "だく", "ダク", "抱く", "to hug / embrace / harbor hope", "Godan", "Actions & Movement"),
    ("damakasu", "だます", "ダマス", "騙す", "to deceive / trick", "Godan", "Social & Communication"),
    ("damarikomu", "だまりこむ", "ダマリコム", "黙り込む", "to fall dead silent", "Godan", "Social & Communication"),
    ("damaru", "だまる", "ダマル", "黙る", "to keep quiet / be silent", "Godan", "Social & Communication"),
    ("dansu suru", "だんすする", "ダンススル", "ダンスする", "to dance to music", "Suru Verb", "Hobbies & Leisure"),
    ("daria o ueru", "だりあをうえる", "ダリアヲウエル", "ダリアを植える", "to plant dahlias", "Ichidan", "Nature & Animals"),
    ("dasu", "だす", "ダス", "出す", "to put out / take out / submit", "Godan", "Daily Actions"),
    ("deau", "であう", "デアウ", "出会う", "to encounter by chance", "Godan", "Social & Communication"),
    ("dekakeru", "でかける", "デカケル", "出かける", "to depart / go out", "Ichidan", "Movement & Travel"),
    ("dekiru", "できる", "デキル", "出来る", "to be able / be completed", "Ichidan", "Daily Actions"),
    ("demukaeru", "でむかえる", "デムカエル", "出迎える", "to greet / welcome arrivals", "Ichidan", "Social & Communication"),
    ("denwa suru", "でんわする", "デンワスル", "電話する", "to telephone / make a call", "Suru Verb", "Social & Communication"),
    ("deru", "でる", "デル", "出る", "to go out / appear / emerge", "Ichidan", "Actions & Movement"),
    ("dokusho suru", "どくしょする", "ドクショスル", "読書する", "to read books", "Suru Verb", "Hobbies & Leisure"),
    ("dokuritsu suru", "どくりつする", "ドクリツスル", "独立する", "to become independent", "Suru Verb", "Social & Communication"),
    ("doryoku suru", "どりょくする", "ドリョクスル", "努力する", "to make great efforts", "Suru Verb", "Work & Study"),
    ("doui suru", "どういする", "ドウイスル", "同意する", "to give consent / agree", "Suru Verb", "Social & Communication"),
    ("doujou suru", "どうじょうする", "ドウジョウスル", "同情する", "to sympathize with", "Suru Verb", "Emotions & Mind"),
    ("doukoku suru", "どうこくする", "ドウコクスル", "慟哭する", "to weep bitterly", "Suru Verb", "Emotions & Mind"),
    ("doraiya o kakeru", "どらいやーをかける", "ドライヤーヲカケル", "ドライヤーを掛ける", "to blow-dry hair", "Ichidan", "Daily Actions"),
    ("doraibu suru", "どらいぶする", "ドライブスル", "ドライブする", "to go on a drive", "Suru Verb", "Movement & Travel"),
    ("doutei suru", "どうていする", "ドウテイスル", "童貞する", "to stay pure and genuine", "Suru Verb", "Emotions & Mind")
]
