# Mind, Work, Study, Senses, Social verbs (M - Z)
# (romaji, hiragana, katakana, kanji, meaning, type, topic)
DATA = [
    # M
    ("machigaeru", "まちがえる", "マチガエル", "間違える", "to make mistake / err", "Ichidan", "Work & Study"),
    ("machigau", "まちがう", "マチガウ", "違う", "to be incorrect / wrong", "Godan", "Work & Study"),
    ("madowasu", "まどわす", "マドワス", "惑わす", "to bewilder / mislead", "Godan", "Social & Communication"),
    ("madoromu", "まどろむ", "マドロム", "微睡む", "to doze off / slumber gently", "Godan", "Daily Actions"),
    ("maesumari suru", "まえむきにする", "マエムキニスル", "前向きにする", "to face forward positively", "Suru Verb", "Emotions & Mind"),
    ("magaru", "まがる", "マガル", "曲がる", "to bend / turn corner", "Godan", "Actions & Movement"),
    ("mageru", "まげる", "マゲル", "曲げる", "to bend wire / distort truth", "Ichidan", "Actions & Movement"),
    ("mainichi manabu", "まいにちまなぶ", "マイニチマナブ", "毎日学ぶ", "to learn every single day", "Godan", "Work & Study"),
    ("mairu", "まいる", "マイル", "参る", "to go / come humbly / visit shrine", "Godan", "Movement & Travel"),
    ("makaseru", "まかせる", "マカセル", "任せる", "to entrust duty to someone", "Ichidan", "Social & Communication"),
    ("makanau", "まかなう", "マカナウ", "賄う", "to cover expenses / cater meals", "Godan", "Cooking & Dining"),
    ("makeru", "まける", "マケル", "負ける", "to lose game / be defeated", "Ichidan", "Hobbies & Leisure"),
    ("maku", "まく", "マク", "巻く", "to roll up sushi / wind clock", "Godan", "Cooking & Dining"),
    ("maku-scatter", "まく", "マク", "蒔く", "to sow seeds / scatter water", "Godan", "Nature & Animals"),
    ("mamoru", "まもる", "マモル", "守る", "to protect / defend / keep promise", "Godan", "Daily Actions"),
    ("manabu", "まなぶ", "マナブ", "学ぶ", "to study systematically / learn", "Godan", "Work & Study"),
    ("mane o suru", "まねをする", "マネヲスル", "真似をする", "to imitate / mimic", "Suru Verb", "Hobbies & Leisure"),
    ("maniau", "まにあう", "マニアウ", "間に合う", "to be on time for train", "Godan", "Movement & Travel"),
    ("manzoku suru", "まんぞくする", "マンゾクスル", "満足する", "to be fully satisfied", "Suru Verb", "Emotions & Mind"),
    ("massugu iku", "まっすぐいく", "マッスグイク", "真っ直ぐ行く", "to go straight ahead", "Godan", "Movement & Travel"),
    ("matomaru", "まとまる", "マトマル", "纏まる", "to come together / reach consensus", "Godan", "Work & Study"),
    ("matomeru", "まとめる", "マトメル", "纏める", "to synthesize / organize notes", "Ichidan", "Work & Study"),
    ("matsu", "まつ", "マツ", "待つ", "to wait / anticipate arrival", "Godan", "Daily Actions"),
    ("mawaru", "まわる", "マワル", "回る", "to rotate / go round and round", "Godan", "Actions & Movement"),
    ("mawasu", "まわす", "マワス", "回す", "to turn dial / spin wheels", "Godan", "Actions & Movement"),
    ("mayou", "まよう", "マヨウ", "迷う", "to lose way / hesitate in thought", "Godan", "Emotions & Mind"),
    ("mazaru", "まざる", "マザル", "混ざる", "to be blended together", "Godan", "Cooking & Dining"),
    ("mazeru", "まぜる", "マゼル", "混ぜる", "to mix / stir ingredients", "Ichidan", "Cooking & Dining"),
    ("me o samasu", "めをさます", "メヲサマス", "目を覚ます", "to wake up / awaken", "Godan", "Daily Actions"),
    ("me o toshite miru", "めをとおしてみる", "メヲトオシテミル", "目を通してみる", "to skim over document", "Ichidan", "Work & Study"),
    ("medatsu", "めだつ", "メダツ", "目立つ", "to stand out / be conspicuous", "Godan", "Social & Communication"),
    ("megumarete iru", "めぐまれている", "メグマレテイル", "恵まれている", "to be blessed with good fortune", "Ichidan", "Culture & Society"),
    ("meirei suru", "めいれいする", "メイレイスル", "命令する", "to give formal order", "Suru Verb", "Social & Communication"),
    ("meisou suru", "めいそうする", "メイソウスル", "瞑想する", "to meditate peacefully", "Suru Verb", "Emotions & Mind"),
    ("michi ni mayou", "みちにまよう", "ミチニマヨウ", "道に迷う", "to get lost on road", "Godan", "Movement & Travel"),
    ("mieru", "みえる", "ミエル", "見える", "to be visible / in view", "Ichidan", "Perception & Senses"),
    ("migaku", "みがく", "ミガク", "磨く", "to polish mirror / hone skills", "Godan", "Work & Study"),
    ("miidasu", "みいだす", "ミイダス", "見いだす", "to discover / find out talent", "Godan", "Work & Study"),
    ("mikiwameru", "みきわめる", "ミキワメル", "見極める", "to ascertain truth / see through", "Ichidan", "Work & Study"),
    ("mikakeru", "みかける", "ミカケル", "見かける", "to happen to catch sight of", "Ichidan", "Perception & Senses"),
    ("mimamoru", "みまもる", "ミマモル", "見守る", "to watch over protectively", "Godan", "People & Family"),
    ("minorasu", "みのらす", "ミノラス", "実らす", "to bear ripe fruit", "Godan", "Nature & Animals"),
    ("minoru", "みのる", "ミノル", "実る", "to ripen / bear fruitful results", "Godan", "Nature & Weather"),
    ("minogasu", "みのがす", "ミノガス", "見逃す", "to overlook / let pass by", "Godan", "Perception & Senses"),
    ("miru", "みる", "ミル", "見る", "to see / look at / watch", "Ichidan", "Perception & Senses"),
    ("misebirakasu", "みせびらかす", "ミセビラカス", "見せびらかす", "to show off ostentatiously", "Godan", "Social & Communication"),
    ("miseru", "みせる", "ミセル", "見せる", "to display / show to person", "Ichidan", "Social & Communication"),
    ("mitasu", "みたす", "ミタス", "満たす", "to fill cup / satisfy requirements", "Godan", "Actions & Movement"),
    ("mitomeru", "みとめる", "ミトメル", "認める", "to recognize / admit / acknowledge", "Ichidan", "Social & Communication"),
    ("mitsukaru", "みつかる", "ミツカル", "見つかる", "to be found (intransitive)", "Godan", "Daily Actions"),
    ("mitsukeru", "みつける", "ミツケル", "見つける", "to locate / discover (transitive)", "Ichidan", "Daily Actions"),
    ("mitsumeru", "みつめる", "ミツメル", "見つめる", "to gaze intently at / stare", "Ichidan", "Perception & Senses"),
    ("mizu o nomu", "みずをのむ", "ミズヲノム", "水を飲む", "to drink cool water", "Godan", "Cooking & Dining"),
    ("mizu o yaru", "みずをやる", "ミズヲヤル", "水をやる", "to water plants in garden", "Godan", "Nature & Animals"),
    ("moeru", "もえる", "モエル", "燃える", "to burn fiercely / blaze with passion", "Ichidan", "Nature & Weather"),
    ("mogeru", "もげる", "モゲル", "もげる", "to come off / be torn off", "Ichidan", "Actions & Movement"),
    ("mochikomu", "もちこむ", "モチコム", "持ち込む", "to bring in baggage", "Godan", "Actions & Movement"),
    ("mochiiru", "もちいる", "モチイル", "用いる", "to utilize / make use of", "Ichidan", "Work & Study"),
    ("mochi-tsuzukeru", "もちつづける", "モチツヅケル", "持ち続ける", "to hold onto conviction", "Ichidan", "Emotions & Mind"),
    ("motsu", "もつ", "モツ", "持つ", "to hold in hand / possess", "Godan", "Actions & Movement"),
    ("motarasu", "もたらす", "モタラス", "もたらす", "to bring about prosperity", "Godan", "Actions & Movement"),
    ("motomeru", "もとめる", "モトメル", "求める", "to seek after / request assistance", "Ichidan", "Social & Communication"),
    ("modoru", "もどる", "モドル", "戻る", "to turn back / return to original place", "Godan", "Movement & Travel"),
    ("modosu", "もどす", "モドス", "戻す", "to put back where it was", "Godan", "Daily Actions"),
    ("moreru", "もれる", "モレル", "漏れる", "to leak gas / be omitted", "Ichidan", "Actions & Movement"),
    ("morau", "もらう", "モラウ", "貰う", "to receive gift / obtain", "Godan", "Social & Communication"),
    ("moru", "もる", "モル", "盛る", "to pile up rice in bowl / serve food", "Godan", "Cooking & Dining"),
    ("mottainai to kanjiru", "もったいないとかんじる", "モッタイナイトカンジル", "もったいないと感じる", "to feel regret over waste", "Ichidan", "Emotions & Mind"),
    ("mukaeru", "むかえる", "ムカエル", "迎える", "to welcome guests / reach anniversary", "Ichidan", "Social & Communication"),
    ("mukau", "むかう", "ムカウ", "向かう", "to face toward / head for destination", "Godan", "Movement & Travel"),
    ("muku", "むく", "ムク", "剥く", "to peel apple skin", "Godan", "Cooking & Dining"),
    ("muku-face", "むく", "ムク", "向く", "to face south / be suited for", "Godan", "Actions & Movement"),
    ("musubu", "むすぶ", "ムスブ", "結ぶ", "to tie knot / bind contract", "Godan", "Actions & Movement"),
    # N
    ("nagameru", "ながめる", "ナガメル", "眺める", "to view panoramic scenery", "Ichidan", "Perception & Senses"),
    ("nagareru", "ながれる", "ナガレル", "流れる", "to flow down stream", "Ichidan", "Nature & Weather"),
    ("nagasu", "ながす", "ナガス", "流す", "to pour water / wash away tears", "Godan", "Daily Actions"),
    ("naguru", "なぐる", "ナグル", "殴る", "to punch / strike with fist", "Godan", "Actions & Movement"),
    ("nagusameru", "なぐさめる", "ナグサメル", "慰める", "to console / offer solace", "Ichidan", "Social & Communication"),
    ("naku", "なく", "ナク", "泣く", "to weep / cry tears", "Godan", "Emotions & Mind"),
    ("naku-sing", "なく", "ナク", "鳴く", "to bark / sing (birds, crickets)", "Godan", "Nature & Animals"),
    ("nakunaru", "なくなる", "ナクナル", "無くなる", "to run out / be lost", "Godan", "Daily Actions"),
    ("nakunaru-die", "なくなる", "ナクナル", "亡くなる", "to pass away / perish", "Godan", "People & Family"),
    ("nakusu", "なくす", "ナクス", "無くす", "to misplace / lose wallet", "Godan", "Daily Actions"),
    ("nameraka ni suru", "なめらかにする", "ナメラカニスル", "滑らかにする", "to smooth out surface", "Suru Verb", "Daily Actions"),
    ("nameru", "なめる", "ナメル", "舐める", "to lick ice cream / underestimate", "Ichidan", "Cooking & Dining"),
    ("naosu", "なおす", "ナオス", "直す", "to repair / fix / rectify", "Godan", "Work & Study"),
    ("naoru", "なおる", "ナオル", "治る", "to recover from illness", "Godan", "Body & Actions"),
    ("narabu", "ならぶ", "ナラブ", "並ぶ", "to stand in line / line up", "Godan", "Movement & Travel"),
    ("naraberu", "ならべる", "ナラベル", "並べる", "to line up plates / arrange", "Ichidan", "Daily Actions"),
    ("narau", "ならう", "ナラウ", "習う", "to take lessons / learn craft", "Godan", "Work & Study"),
    ("nareru", "なれる", "ナレル", "慣れる", "to grow accustomed to", "Ichidan", "Daily Actions"),
    ("naru", "なる", "ナル", "なる", "to become / turn into", "Godan", "Daily Actions"),
    ("naru-ring", "なる", "ナル", "鳴る", "to ring (telephone, bell)", "Godan", "Perception & Senses"),
    ("nayamu", "なやむ", "ナヤム", "悩む", "to fret / be anguished", "Godan", "Emotions & Mind"),
    ("negau", "ねがう", "ネガウ", "願う", "to entreat / wish from heart", "Godan", "Social & Communication"),
    ("nemuru", "ねむる", "ネムル", "眠る", "to sleep / fall into slumber", "Godan", "Daily Actions"),
    ("neru", "ねる", "ネル", "寝る", "to go to bed / lie down", "Ichidan", "Daily Actions"),
    ("neru-knead", "ねる", "ネル", "練る", "to knead bread dough / polish plan", "Godan", "Cooking & Dining"),
    ("netto o tsukau", "ねっとをつかう", "ネットヲツカウ", "ネットを使う", "to browse the Internet", "Godan", "Work & Study"),
    ("netsu o dasu", "ねつをだす", "ネツヲダス", "熱を出す", "to run a high fever", "Godan", "Body & Actions"),
    ("nigeru", "にげる", "ニゲル", "逃げる", "to flee / escape from danger", "Ichidan", "Actions & Movement"),
    ("nigiru", "にぎる", "ニギル", "握る", "to grasp sushi / hold hand", "Godan", "Cooking & Dining"),
    ("niru", "にる", "ニル", "煮る", "to boil / simmer in pot", "Ichidan", "Cooking & Dining"),
    ("niru-resemble", "にる", "ニル", "似る", "to resemble / look like", "Ichidan", "People & Family"),
    ("nobiru", "のびる", "ノビル", "伸びる", "to stretch out / lengthen", "Ichidan", "Actions & Movement"),
    ("nobosu", "のぼす", "ノボス", "伸す", "to roll out pastry dough", "Godan", "Cooking & Dining"),
    ("noboru", "のぼる", "ノボル", "登る", "to climb mountain peak", "Godan", "Movement & Travel"),
    ("nokoru", "のこる", "ノコル", "残る", "to stay behind / remain", "Godan", "Daily Actions"),
    ("nokosu", "のこす", "ノコス", "残す", "to leave over food / preserve", "Godan", "Cooking & Dining"),
    ("nomu", "のむ", "ノム", "飲む", "to drink / swallow medicine", "Godan", "Cooking & Dining"),
    ("norikaeru", "のりかえる", "ノリカエル", "乗り換える", "to transfer trains / switch", "Ichidan", "Movement & Travel"),
    ("noru", "のる", "ノル", "乗る", "to board train / ride bike", "Godan", "Movement & Travel"),
    ("nozomu", "のぞむ", "ノゾム", "望む", "to hope for / aspire to", "Godan", "Emotions & Mind"),
    ("nugamu", "ぬぐ", "ヌグ", "脱ぐ", "to take off clothes / shoes", "Godan", "Daily Actions"),
    ("nurasu", "ぬらす", "ヌラス", "濡らす", "to wet / soak with water", "Godan", "Daily Actions"),
    ("nureru", "ぬれる", "ヌレル", "濡れる", "to get drenched / wet", "Ichidan", "Nature & Weather"),
    ("nuru", "ぬる", "ヌル", "塗る", "to paint / spread butter", "Godan", "Daily Actions"),
    ("nusumu", "ぬすむ", "ヌスム", "盗む", "to steal / snatch secret", "Godan", "Social & Communication"),
    # O
    ("oboeru", "おぼえる", "オボエル", "覚える", "to memorize / master / recall", "Ichidan", "Work & Study"),
    ("ochiru", "おちる", "オチル", "落ちる", "to fall / drop down", "Ichidan", "Actions & Movement"),
    ("odoroku", "おどろく", "オドロク", "驚く", "to be astonished / shocked", "Godan", "Emotions & Mind"),
    ("odoru", "おどる", "オドル", "踊る", "to dance to traditional music", "Godan", "Hobbies & Leisure"),
    ("oitsuku", "おいつく", "オイツク", "追いつく", "to catch up with leader", "Godan", "Actions & Movement"),
    ("okiru", "おきる", "オキル", "起きる", "to wake up / happen", "Ichidan", "Daily Actions"),
    ("okonau", "おこなう", "オコナウ", "行う", "to carry out festival / conduct", "Godan", "Culture & Society"),
    ("okoru", "おこる", "オコル", "怒る", "to become angry / get mad", "Godan", "Emotions & Mind"),
    ("okosu", "おこす", "オコス", "起こす", "to awaken sleeper / cause event", "Godan", "Daily Actions"),
    ("oku", "おく", "オク", "置く", "to set down / place object", "Godan", "Daily Actions"),
    ("okuru", "おくる", "オクル", "送る", "to send letter / escort friend", "Godan", "Social & Communication"),
    ("okureru", "おくれる", "オクレル", "遅れる", "to be delayed / run late", "Ichidan", "Time & Calendar"),
    ("omou", "おもう", "オモウ", "思う", "to think / feel / consider", "Godan", "Emotions & Mind"),
    ("omoi-dasu", "おもいだす", "オモイダス", "思い出す", "to reminisce / recall memory", "Godan", "Emotions & Mind"),
    ("ori-tatsu", "おりたつ", "オリタツ", "降り立つ", "to step down onto platform", "Godan", "Movement & Travel"),
    ("oriru", "おりる", "オリル", "降りる", "to disembark from train", "Ichidan", "Movement & Travel"),
    ("oru", "おる", "オル", "折る", "to fold origami / break stick", "Godan", "Hobbies & Leisure"),
    ("oshieru", "おしえる", "オシエル", "教える", "to teach / explain / guide", "Ichidan", "Work & Study"),
    ("osu", "おす", "オス", "押す", "to push button / stamp seal", "Godan", "Daily Actions"),
    ("otoraeru", "おとろえる", "オトロエル", "衰える", "to wane / lose vigor", "Ichidan", "Body & Actions"),
    ("otosu", "おとす", "オトス", "落とす", "to drop coin / lose object", "Godan", "Daily Actions"),
    ("owaru", "おわる", "オワル", "終わる", "to end / conclude / terminate", "Godan", "Work & Study"),
    ("oyogu", "およぐ", "オヨグ", "泳ぐ", "to swim across water", "Godan", "Hobbies & Leisure"),
    # R
    ("renshuu suru", "れんしゅうする", "レンシュウスル", "練習する", "to practice instrument / sports", "Suru Verb", "Work & Study"),
    ("renraku suru", "れんらくする", "レンラクスル", "連絡する", "to get in touch / contact", "Suru Verb", "Social & Communication"),
    ("ryokou suru", "りょこうする", "リョコウスル", "旅行する", "to travel / take vacation", "Suru Verb", "Movement & Travel"),
    ("ryouri suru", "りょうりする", "リョウリスル", "料理する", "to cook meal", "Suru Verb", "Cooking & Dining"),
    # S
    ("sagashimawaru", "さがしまわる", "サガシマワル", "探し回る", "to search everywhere / scour", "Godan", "Daily Actions"),
    ("sagasu", "さがす", "サガス", "探す", "to search for lost item", "Godan", "Daily Actions"),
    ("sagaru", "さがる", "サガル", "下がる", "to hang down / step back", "Godan", "Actions & Movement"),
    ("sageru", "さげる", "サゲル", "下げる", "to lower hand / clear table", "Ichidan", "Daily Actions"),
    ("saigo made iku", "さいごまでいく", "サイゴマデイク", "最後まで行く", "to go all the way to end", "Godan", "Actions & Movement"),
    ("sakaseru", "さかせる", "サカセル", "咲かせる", "to cause flowers to blossom", "Ichidan", "Nature & Weather"),
    ("saku", "さく", "サク", "咲く", "to blossom / burst into bloom", "Godan", "Nature & Weather"),
    ("sasaeru", "ささえる", "ササエル", "支える", "to prop up / sustain family", "Ichidan", "Social & Communication"),
    ("sasou", "さそう", "サソウ", "誘う", "to invite friend to event", "Godan", "Social & Communication"),
    ("sasu", "さす", "サス", "刺す", "to prick / pierce / stab", "Godan", "Actions & Movement"),
    ("sasu-umbrella", "さす", "サス", "差す", "to hold up open umbrella", "Godan", "Daily Actions"),
    ("sawagu", "さわぐ", "サワグ", "騒ぐ", "to make a racket / clamor", "Godan", "Social & Communication"),
    ("sawaru", "さわる", "サワル", "触る", "to touch with fingers", "Godan", "Perception & Senses"),
    ("seikatsu suru", "せいかつする", "セイカツスル", "生活する", "to live everyday life", "Suru Verb", "Daily Actions"),
    ("seikou suru", "せいこうする", "セイコウスル", "成功する", "to succeed triumphantly", "Suru Verb", "Work & Study"),
    ("senkyo ni iku", "せんきょにいく", "センキョニイク", "選挙に行く", "to cast vote at election", "Godan", "Social & Communication"),
    ("sentaku suru", "せんたくする", "センタクスル", "洗濯する", "to wash laundry clothes", "Suru Verb", "Daily Actions"),
    ("setsumei suru", "せつめいする", "セツメイスル", "説明する", "to explain clearly", "Suru Verb", "Social & Communication"),
    ("shikaru", "しかる", "シカル", "叱る", "to scold / reprimand pupil", "Godan", "Social & Communication"),
    ("shinjiru", "しんじる", "シンジル", "信じる", "to believe in / trust", "Ichidan", "Emotions & Mind"),
    ("shinpai suru", "しんぱいする", "シンパイスル", "心配する", "to worry about safety", "Suru Verb", "Emotions & Mind"),
    ("shiru", "しる", "シル", "知る", "to know / recognize fact", "Godan", "Work & Study"),
    ("shitsumon suru", "しつもんする", "シツモンスル", "質問する", "to pose a question", "Suru Verb", "Work & Study"),
    ("shokuji suru", "しょくじする", "ショクジスル", "食事する", "to partake in dining meal", "Suru Verb", "Cooking & Dining"),
    ("shoukai suru", "しょうかいする", "ショウカイスル", "紹介する", "to introduce a colleague", "Suru Verb", "Social & Communication"),
    ("shukudai o suru", "しゅくだいをする", "シュクダイヲスル", "宿題をする", "to complete homework", "Suru Verb", "Work & Study"),
    ("shuppatsu suru", "しゅっぱつする", "シュッパツスル", "出発する", "to set out on journey", "Suru Verb", "Movement & Travel"),
    ("souji suru", "そうじする", "ソウジスル", "掃除する", "to clean room thoroughly", "Suru Verb", "Daily Actions"),
    ("soudan suru", "そうだんする", "ソウダンスル", "相談する", "to consult / confer with", "Suru Verb", "Social & Communication"),
    ("sugosu", "すごす", "スゴス", "過ごす", "to pass time / spend weekend", "Godan", "Daily Actions"),
    ("sumu", "すむ", "スム", "住む", "to dwell / reside in house", "Godan", "Daily Actions"),
    ("suru", "する", "スル", "する", "to do / execute action", "Suru Verb", "Daily Actions"),
    ("suwaru", "すわる", "スワル", "座る", "to sit down on chair or floor", "Godan", "Actions & Movement"),
    # T
    ("taberu", "たべる", "タベル", "食べる", "to eat delicious food", "Ichidan", "Cooking & Dining"),
    ("tanoshimu", "たのしむ", "タノシム", "楽しむ", "to savor pleasure / enjoy", "Godan", "Hobbies & Leisure"),
    ("tanomu", "たのむ", "タノム", "頼む", "to make request / ask favor", "Godan", "Social & Communication"),
    ("tashikameru", "たしかめる", "タシカメル", "確かめる", "to verify / make certain", "Ichidan", "Work & Study"),
    ("tateru", "たてる", "タテル", "立てる", "to stand something up / erect", "Ichidan", "Actions & Movement"),
    ("tatsu", "たつ", "タツ", "立つ", "to stand up on feet", "Godan", "Actions & Movement"),
    ("tetsudau", "てつだう", "テツダウ", "手伝う", "to lend a helping hand", "Godan", "Social & Communication"),
    ("todokeru", "とどける", "トドケル", "届ける", "to deliver parcel / report", "Ichidan", "Social & Communication"),
    ("tomaru", "とまる", "トマル", "止まる", "to come to a halt / stop", "Godan", "Actions & Movement"),
    ("tomaru-stay", "とまる", "トマル", "泊まる", "to lodge overnight at inn", "Godan", "Movement & Travel"),
    ("tomeru", "とめる", "トメル", "止める", "to halt vehicle / fasten", "Ichidan", "Daily Actions"),
    ("toru", "とる", "トル", "取る", "to take in hand / obtain", "Godan", "Daily Actions"),
    ("toru-photo", "とる", "トル", "撮る", "to take photograph", "Godan", "Hobbies & Leisure"),
    ("tsukau", "つかう", "ツカウ", "使う", "to utilize / spend / use", "Godan", "Daily Actions"),
    ("tsukuru", "つくる", "ツクル", "作る", "to craft / cook / manufacture", "Godan", "Daily Actions"),
    ("tsutaeru", "つたえる", "ツタエル", "伝える", "to convey message / pass down", "Ichidan", "Social & Communication"),
    ("tsutomeru", "つとめる", "ツトメル", "勤める", "to work for an employer", "Ichidan", "Work & Study"),
    ("tsuzukeru", "つづける", "ツヅケル", "続ける", "to continue onward", "Ichidan", "Work & Study"),
    ("tsuzuku", "つづく", "ツヅク", "続く", "to persist / carry on", "Godan", "Daily Actions"),
    # U
    ("ugoku", "うごく", "ウゴク", "動く", "to move / operate (machine)", "Godan", "Actions & Movement"),
    ("ugokasu", "うごかす", "ウゴカス", "動かす", "to set in motion / maneuver", "Godan", "Actions & Movement"),
    ("umareru", "うまれる", "ウマレル", "生まれる", "to be born into world", "Ichidan", "People & Family"),
    ("umu", "うむ", "ウム", "産む", "to give birth / produce eggs", "Godan", "Nature & Animals"),
    ("utau", "うたう", "ウタウ", "歌う", "to sing melody", "Godan", "Hobbies & Leisure"),
    ("utagau", "うたがう", "ウタガウ", "疑う", "to doubt / suspect sincerity", "Godan", "Emotions & Mind"),
    ("utsu", "うつ", "ウツ", "打つ", "to strike clock / hit baseball", "Godan", "Actions & Movement"),
    ("utsusu", "うつす", "ウツス", "写す", "to transcribe / photograph", "Godan", "Work & Study"),
    # W
    ("wakaru", "わかる", "ワカル", "分かる", "to comprehend / understand", "Godan", "Work & Study"),
    ("wakareru", "わかれる", "ワカレル", "別れる", "to part ways / say farewell", "Ichidan", "Social & Communication"),
    ("wakareru-branch", "わかれる", "ワカレル", "分かれる", "to branch off / divide", "Ichidan", "Actions & Movement"),
    ("wakeru", "わける", "ワケル", "分ける", "to divide portions / share", "Ichidan", "Daily Actions"),
    ("warau", "わらう", "ワラウ", "笑う", "to laugh / smile cheerfully", "Godan", "Emotions & Mind"),
    ("waru", "わる", "ワル", "割る", "to crack egg / divide number", "Godan", "Cooking & Dining"),
    ("wasureru", "わすれる", "ワスレル", "忘れる", "to forget / leave behind", "Ichidan", "Daily Actions"),
    ("wataru", "わたる", "ワタル", "渡る", "to cross over bridge / ocean", "Godan", "Movement & Travel"),
    ("watasu", "わたす", "ワタス", "渡す", "to hand over package", "Godan", "Social & Communication"),
    # Y
    ("yaku", "やく", "ヤク", "焼く", "to toast / grill over charcoal", "Godan", "Cooking & Dining"),
    ("yameru", "やめる", "ヤメル", "辞める", "to quit job / resign", "Ichidan", "Work & Study"),
    ("yameru-stop", "やめる", "ヤメル", "止める", "to cease / stop habit", "Ichidan", "Daily Actions"),
    ("yasumu", "やすむ", "ヤスム", "休む", "to rest / take a break", "Godan", "Daily Actions"),
    ("yaru", "やる", "ヤル", "やる", "to do / perform / give to junior", "Godan", "Daily Actions"),
    ("yobu", "よぶ", "ヨブ", "呼ぶ", "to summon / call taxi", "Godan", "Social & Communication"),
    ("yomu", "よむ", "ヨム", "読む", "to read book / poem", "Godan", "Hobbies & Leisure"),
    ("yorokobu", "よろこぶ", "ヨロコブ", "喜ぶ", "to rejoice / feel delight", "Godan", "Emotions & Mind"),
    # Z
    ("zasetsu suru", "ざせつする", "ザセツスル", "挫折する", "to suffer a setback", "Suru Verb", "Emotions & Mind"),
    ("zatsudan suru", "ざつだんする", "ザツダンスル", "雑談する", "to have friendly chitchat", "Suru Verb", "Social & Communication"),
    ("zenryoku o dasu", "ぜんりょくだす", "ゼンリョクヲダス", "全力を出す", "to put forth one's all", "Godan", "Work & Study")
]
