# Communication, Speaking, Social interactions, Greetings, Asking, Promising, Working
# (romaji, hiragana, katakana, kanji, meaning, type, topic)
DATA = [
    # E
    ("egaku", "えがく", "エガク", "描く", "to sketch / draw / depict", "Godan", "Hobbies & Leisure"),
    ("eikyousuru", "えいきょうする", "エイキョウスル", "影響する", "to exert an influence on", "Suru Verb", "Social & Communication"),
    ("eikyuu ni suru", "えいきゅうにする", "エイキュウニスル", "永久にする", "to perpetuate / make eternal", "Suru Verb", "Work & Study"),
    ("eita suru", "えいたする", "エイタスル", "詠嘆する", "to sigh with admiration", "Suru Verb", "Emotions & Mind"),
    ("ejiki ni suru", "えじきにする", "エジキニスル", "餌食にする", "to make a prey of", "Suru Verb", "Nature & Animals"),
    ("en'en to suru", "えんえんとする", "エンエントスル", "延々とする", "to drag on endlessly", "Suru Verb", "Work & Study"),
    ("enjo suru", "えんじょする", "エンジョスル", "援助する", "to assist / give aid", "Suru Verb", "Social & Communication"),
    ("enjiru", "えんじる", "エンジン", "演じる", "to perform / act a part", "Ichidan", "Hobbies & Leisure"),
    ("enryo suru", "えんりょする", "エンリョスル", "遠慮する", "to hold back / refrain politely", "Suru Verb", "Social & Communication"),
    ("ensou suru", "えんそうする", "エンソウスル", "演奏する", "to perform music on instrument", "Suru Verb", "Hobbies & Leisure"),
    ("erabu", "えらぶ", "エラブ", "選ぶ", "to choose / select", "Godan", "Daily Actions"),
    ("eru", "える", "エル", "得る", "to gain / acquire / earn", "Ichidan", "Work & Study"),
    # F
    ("fubuki ga fuku", "ふぶきがふく", "フブキガフク", "吹雪が吹く", "snowstorm to rage", "Godan", "Nature & Weather"),
    ("fueru", "ふえる", "フエル", "増える", "to multiply / increase", "Ichidan", "Actions & Movement"),
    ("fukameru", "ふかめる", "フカメル", "深める", "to deepen understanding", "Ichidan", "Work & Study"),
    ("fukamaru", "ふかまる", "フカマル", "深まる", "to deepen (autumn/ties)", "Godan", "Nature & Weather"),
    ("fuku", "ふく", "フク", "吹く", "to blow (wind) / play flute", "Godan", "Nature & Weather"),
    ("fuku-wipe", "ふく", "フク", "拭く", "to wipe dry / clean with rag", "Godan", "Daily Actions"),
    ("fukumu", "ふくむ", "フクム", "含む", "to contain / hold inside", "Godan", "Actions & Movement"),
    ("fukumeru", "ふくめる", "フクメル", "含める", "to include / incorporate", "Ichidan", "Work & Study"),
    ("fukuramu", "ふくらむ", "フクラム", "膨らむ", "to swell / puff up / expand", "Godan", "Actions & Movement"),
    ("fukusu", "ふくす", "フクス", "伏す", "to prostrate oneself / lie low", "Godan", "Actions & Movement"),
    ("fukushuu suru", "ふくしゅうする", "フクシュウスル", "復習する", "to review previous study", "Suru Verb", "Work & Study"),
    ("fumikomu", "ふみこむ", "フミコム", "踏み込む", "to step firmly into", "Godan", "Actions & Movement"),
    ("fumu", "ふむ", "フム", "踏む", "to step on / tread upon", "Godan", "Actions & Movement"),
    ("funbaeru", "ふんばる", "フンバル", "踏ん張る", "to hold one's ground / persevere", "Godan", "Actions & Movement"),
    ("furasu", "ふらす", "フラス", "降らす", "to cause rain to fall", "Godan", "Nature & Weather"),
    ("fureru", "ふれる", "フレル", "触れる", "to touch / brush against", "Ichidan", "Perception & Senses"),
    ("furi-muku", "ふりむく", "フリムク", "振り向く", "to turn around to look", "Godan", "Actions & Movement"),
    ("furu", "ふる", "フル", "降る", "to fall (rain, snow)", "Godan", "Nature & Weather"),
    ("furu-wave", "ふる", "フル", "振る", "to wave hand / shake / turn down", "Godan", "Actions & Movement"),
    ("furueru", "ふるえる", "フルエル", "震える", "to shiver / tremble with cold", "Ichidan", "Body & Actions"),
    ("fusegu", "ふせぐ", "フセグ", "防ぐ", "to ward off / prevent", "Godan", "Daily Actions"),
    ("fuseru", "ふせる", "フセル", "伏せる", "to lay face down / conceal", "Ichidan", "Actions & Movement"),
    ("futo-omou", "ふとおもう", "フトオモウ", "ふと思う", "to happen to think / cross mind", "Godan", "Emotions & Mind"),
    ("futoru", "ふとる", "フトル", "太る", "to gain weight / grow fat", "Godan", "Body & Actions"),
    # G
    ("gai suru", "がいする", "ガイスル", "害する", "to harm / injure / impair", "Suru Verb", "Social & Communication"),
    ("gakkari suru", "がっかりする", "ガッカリスル", "がっかりする", "to feel deeply disappointed", "Suru Verb", "Emotions & Mind"),
    ("gaman suru", "がまんする", "ガマンスル", "我慢する", "to endure / bear with patience", "Suru Verb", "Emotions & Mind"),
    ("ganbaru", "がんばる", "ガンバル", "頑張る", "to do one's very best / persist", "Godan", "Actions & Movement"),
    ("gassan suru", "がっさんする", "ガッサンスル", "合算する", "to sum up / aggregate", "Suru Verb", "Work & Study"),
    ("gattai suru", "がったいする", "ガッタイスル", "合体する", "to merge / unite together", "Suru Verb", "Actions & Movement"),
    ("gekikara ni suru", "げきからにする", "ゲキカラニスル", "激辛にする", "to make extra spicy hot", "Suru Verb", "Cooking & Dining"),
    ("gimon o motsu", "ぎもんをもつ", "ギモンヲモツ", "疑問を持つ", "to harbor doubts", "Godan", "Work & Study"),
    ("giron suru", "ぎろんする", "ギロンスル", "議論する", "to debate / argue points", "Suru Verb", "Social & Communication"),
    ("goshigoshi arau", "ごしごしあらう", "ゴシゴシアラウ", "ごしごし洗う", "to scrub vigorously", "Godan", "Daily Actions"),
    ("goukei suru", "ごうけいする", "ゴウケイスル", "合計する", "to add up to a total", "Suru Verb", "Work & Study"),
    ("goukaku suru", "ごうかくする", "ゴウカクスル", "合格する", "to pass exam / qualify", "Suru Verb", "Work & Study"),
    ("gouin ni iku", "ごういんにいく", "ゴウインニイク", "強引に行く", "to push forward forcefully", "Godan", "Actions & Movement"),
    ("guchi o kobosu", "ぐちをこぼす", "グチヲコボス", "愚痴をこぼす", "to grumble / complain", "Godan", "Social & Communication"),
    ("gussuri neru", "ぐっすりねる", "グッスリネル", "ぐっすり寝る", "to sleep soundly", "Ichidan", "Daily Actions"),
    ("guruguru mawaru", "ぐるぐるまわる", "グルグルマワル", "ぐるぐる回る", "to spin round and round", "Godan", "Actions & Movement"),
    # H
    ("ha o migaku", "はをみがく", "ハヲミガク", "歯を磨く", "to brush one's teeth", "Godan", "Daily Actions"),
    ("habaku", "はばく", "ハバク", "幅く", "to expand range", "Godan", "Actions & Movement"),
    ("habataku", "はばたく", "ハバタク", "羽ばたく", "to flap wings and soar", "Godan", "Nature & Animals"),
    ("habiku", "はびこる", "ハビコル", "蔓延る", "to overrun / grow rampantly", "Godan", "Nature & Animals"),
    ("habuku", "はぶく", "ハブク", "省く", "to omit / cut out / curtail", "Godan", "Work & Study"),
    ("hagasu", "はがす", "ハガス", "剥がす", "to tear off / peel off sticker", "Godan", "Daily Actions"),
    ("hagoku", "はぐくむ", "ハグクム", "育む", "to nurture / foster tenderly", "Godan", "People & Family"),
    ("haisuru", "はいする", "ハイスル", "拝する", "to worship / behold with reverence", "Suru Verb", "Culture & Society"),
    ("haitatsu suru", "はいたつする", "ハイタツスル", "配達する", "to deliver parcels", "Suru Verb", "Work & Study"),
    ("hajikaru", "はじく", "ハジク", "弾く", "to flick / snap / repel water", "Godan", "Actions & Movement"),
    ("hajimaru", "はじまる", "ハジマル", "始まる", "to start / begin (intransitive)", "Godan", "Actions & Movement"),
    ("hajimeru", "はじめる", "ハジメル", "始める", "to begin / initiate (transitive)", "Ichidan", "Daily Actions"),
    ("hakarau", "はからう", "ハカラウ", "計らう", "to manage / arrange tactfully", "Godan", "Work & Study"),
    ("hakaru", "はかる", "ハカル", "測る", "to measure length / time", "Godan", "Work & Study"),
    ("hakaru-plan", "はかる", "ハカル", "図る", "to plan / attempt / devise", "Godan", "Work & Study"),
    ("hakaru-weigh", "はかる", "ハカル", "量る", "to weigh weight / volume", "Godan", "Cooking & Dining"),
    ("haki-souji suru", "はきそうじする", "ハキソウジスル", "掃き掃除する", "to sweep and clean floors", "Suru Verb", "Daily Actions"),
    ("haku", "はく", "ハク", "履く", "to wear shoes / pants", "Godan", "Daily Actions"),
    ("haku-sweep", "はく", "ハク", "掃く", "to sweep with a broom", "Godan", "Daily Actions"),
    ("haku-vomit", "はく", "ハク", "吐く", "to vomit / exhale breath", "Godan", "Body & Actions"),
    ("hakobu", "はこぶ", "ハコブ", "運ぶ", "to transport / carry cargo", "Godan", "Actions & Movement"),
    ("hamaru", "はまる", "ハマル", "嵌まる", "to fit nicely into / be hooked on", "Godan", "Hobbies & Leisure"),
    ("hameru", "はめる", "ハメル", "嵌める", "to insert / wear ring / set up", "Ichidan", "Daily Actions"),
    ("hanakakeru", "はなしかける", "ハナシカケル", "話しかける", "to address / strike up talk", "Ichidan", "Social & Communication"),
    ("hanasu", "はなす", "ハナス", "話す", "to speak / converse / tell", "Godan", "Social & Communication"),
    ("hanasu-release", "はなす", "ハナス", "放す", "to let go / release fish", "Godan", "Actions & Movement"),
    ("hanasu-separate", "はなす", "ハナス", "離す", "to set apart / distance", "Godan", "Actions & Movement"),
    ("haneru", "はねる", "ハネル", "跳ねる", "to jump / splash water / bounce", "Ichidan", "Actions & Movement"),
    ("hankou suru", "はんこうする", "ハンコウスル", "反抗する", "to rebel / defy authority", "Suru Verb", "Social & Communication"),
    ("hansei suru", "はんせいする", "ハンセイスル", "反省する", "to reflect on mistakes", "Suru Verb", "Emotions & Mind"),
    ("hantai suru", "はんたいする", "ハンタイスル", "反対する", "to oppose / disagree with", "Suru Verb", "Social & Communication"),
    ("happyou suru", "はっぴょうする", "ハッピョウスル", "発表する", "to announce / present in public", "Suru Verb", "Work & Study"),
    ("harau", "はらう", "ハラウ", "払う", "to pay money / brush off dust", "Godan", "Shopping & Money"),
    ("hareru", "はれる", "ハレル", "晴れる", "to clear up (weather)", "Ichidan", "Nature & Weather"),
    ("haru", "はる", "ハル", "貼る", "to paste / stick stamp", "Godan", "Daily Actions"),
    ("haru-stretch", "はる", "ハル", "張る", "to stretch tight / pitch tent", "Godan", "Actions & Movement"),
    ("hasamu", "はさむ", "ハサム", "挟む", "to insert between / pinch", "Godan", "Actions & Movement"),
    ("hashigo suru", "はしごする", "ハシゴスル", "梯子する", "to bar-hop / visit consecutive places", "Suru Verb", "Hobbies & Leisure"),
    ("hashiru", "はしる", "ハシル", "走る", "to run / dash", "Godan", "Actions & Movement"),
    ("hataraku", "はたらく", "ハタラク", "働く", "to work at a company", "Godan", "Work & Study"),
    ("hatasu", "はたす", "ハタス", "果たす", "to accomplish / fulfill task", "Godan", "Work & Study"),
    ("hateru", "はてる", "ハテル", "果てる", "to come to an end / perish", "Ichidan", "Nature & Weather"),
    ("hayameru", "はやめる", "ハヤメル", "早める", "to accelerate / speed up date", "Ichidan", "Work & Study"),
    ("hayaru", "はやる", "ハヤル", "流行る", "to be in vogue / popular", "Godan", "Culture & Society"),
    ("hazukashigaru", "はずかしがる", "ハズカシガル", "恥ずかしがる", "to act shy / bashful", "Godan", "Emotions & Mind"),
    ("hazureru", "はずれる", "ハズレル", "外れる", "to disconnect / miss target", "Ichidan", "Actions & Movement"),
    ("hazusu", "はずす", "ハズス", "外す", "to unfasten / take off glasses", "Godan", "Daily Actions"),
    ("hedateru", "へだてる", "ヘダテル", "隔てる", "to separate by distance / partition", "Ichidan", "Actions & Movement"),
    ("heikou suru", "へいこうする", "ヘイコウスル", "平衡する", "to balance / be in equilibrium", "Suru Verb", "Actions & Movement"),
    ("henka suru", "へんかする", "ヘンカスル", "変化する", "to undergo transformation", "Suru Verb", "Nature & Weather"),
    ("henji o suru", "へんじをする", "ヘンジヲスル", "返事をする", "to answer / give reply", "Suru Verb", "Social & Communication"),
    ("herasu", "へらす", "ヘラス", "減らす", "to curtail / decrease (transitive)", "Godan", "Daily Actions"),
    ("heru", "へる", "ヘル", "減る", "to diminish / dwindle (intransitive)", "Godan", "Actions & Movement"),
    ("heru-pass", "へる", "ヘル", "経る", "to pass through time", "Ichidan", "Time & Calendar"),
    ("hibiku", "ひびく", "ヒビク", "響く", "to resound / echo / reverberate", "Godan", "Perception & Senses"),
    ("hiekou", "ひえる", "ヒエル", "冷える", "to get cold / chill down", "Ichidan", "Nature & Weather"),
    ("higurashi ga naku", "ひぐらしがなく", "ヒグラシガナク", "蜩が鳴く", "evening cicada to chant", "Godan", "Nature & Animals"),
    ("hikaku suru", "ひかくする", "ヒカクスル", "比較する", "to compare against", "Suru Verb", "Work & Study"),
    ("hikaru", "ひかる", "ヒカル", "光る", "to shine / sparkle / gleam", "Godan", "Nature & Weather"),
    ("hikikaeru", "ひきかえる", "ヒキカエル", "引き換える", "to exchange for token", "Ichidan", "Shopping & Money"),
    ("hikiokosu", "ひきおこす", "ヒキオコス", "引き起こす", "to cause / bring about incident", "Godan", "Actions & Movement"),
    ("hikitoru", "ひきとる", "ヒキトル", "引き取る", "to claim custody / take delivery", "Godan", "Social & Communication"),
    ("hikiukeru", "ひきうける", "ヒキウケル", "引き受ける", "to undertake responsibility", "Ichidan", "Work & Study"),
    ("hikitsugu", "ひきつぐ", "ヒキツグ", "引き継ぐ", "to take over duties", "Godan", "Work & Study"),
    ("hiku", "ひく", "ヒク", "引く", "to pull / draw / subtract", "Godan", "Actions & Movement"),
    ("hiku-play", "ひく", "ヒク", "弾く", "to play piano / string instrument", "Godan", "Hobbies & Leisure"),
    ("hikou suru", "ひこうする", "ヒコウスル", "飛行する", "to fly in aircraft", "Suru Verb", "Movement & Travel"),
    ("hikkosu", "ひっこす", "ヒッコす", "引っ越す", "to relocate / move home", "Godan", "Daily Actions"),
    ("hipparu", "ひっぱる", "ヒッパル", "引っ張る", "to tug / pull forcefully", "Godan", "Actions & Movement"),
    ("hiraku", "ひらく", "ヒラク", "開く", "to open book / hold an event", "Godan", "Daily Actions"),
    ("hirogaru", "ひろがる", "ヒロガル", "広がる", "to spread out / broaden", "Godan", "Actions & Movement"),
    ("hirogeru", "ひろげる", "ヒロゲル", "広げる", "to unfold / extend wings", "Ichidan", "Actions & Movement"),
    ("hirou", "ひろう", "ヒロウ", "拾う", "to pick up from ground / find", "Godan", "Daily Actions"),
    ("hisomu", "ひそむ", "ヒソム", "潜む", "to lurk / lie concealed", "Godan", "Nature & Animals"),
    ("hitasu", "ひたす", "ヒタス", "浸す", "to immerse / soak in water", "Godan", "Cooking & Dining"),
    ("hitorigoto o iu", "ひとりごとをいう", "ヒトリゴトヲイウ", "独り言を言う", "to murmur to oneself", "Godan", "Social & Communication"),
    ("hiyaku suru", "ひやくする", "ヒヤクスル", "飛躍する", "to make a rapid leap forward", "Suru Verb", "Actions & Movement"),
    ("hiyasu", "ひやす", "ヒヤス", "冷やす", "to chill beer in ice", "Godan", "Cooking & Dining"),
    ("hizamazuku", "ひざまずく", "ヒザマズク", "跪く", "to kneel down on knees", "Godan", "Actions & Movement"),
    ("hobo kakutei suru", "ほぼかくていする", "ホボカクテイスル", "ほぼ確定する", "to be virtually confirmed", "Suru Verb", "Work & Study"),
    ("hodokeru", "ほどける", "ホドケル", "解ける", "to come untied / unravel", "Ichidan", "Actions & Movement"),
    ("hodoku", "ほどく", "ホドク", "解く", "to untie knot / unpack", "Godan", "Daily Actions"),
    ("hogo suru", "ほごする", "ホゴスル", "保護する", "to shelter / protect wildlife", "Suru Verb", "Social & Communication"),
    ("hokoru", "ほこる", "ホコル", "誇る", "to take pride in / boast of", "Godan", "Emotions & Mind"),
    ("homeru", "ほめる", "ホメル", "褒める", "to praise / compliment", "Ichidan", "Social & Communication"),
    ("honki ni naru", "ほんきになる", "ホンキニナル", "本気になる", "to get thoroughly serious", "Godan", "Emotions & Mind"),
    ("hon'yaku suru", "ほんやくする", "ホンヤクスル", "翻訳する", "to translate text", "Suru Verb", "Work & Study"),
    ("horu", "ほる", "ホル", "掘る", "to dig earth / excavate", "Godan", "Actions & Movement"),
    ("horu-carve", "ほる", "ホル", "彫る", "to carve wood / sculpt", "Godan", "Hobbies & Leisure"),
    ("hoshigaru", "ほしがる", "ホシガル", "欲しがる", "to desire / covet", "Godan", "Emotions & Mind"),
    ("hosu", "ほす", "ホス", "干す", "to air dry clothes in sun", "Godan", "Daily Actions"),
    ("hottosuru", "ほっとする", "ホットスル", "ほっとする", "to sigh with warm relief", "Suru Verb", "Emotions & Mind"),
    ("houkoku suru", "ほうこくする", "ホウコクスル", "報告する", "to report findings", "Suru Verb", "Work & Study"),
    ("houmon suru", "ほうもんする", "ホウモンスル", "訪問する", "to pay a formal visit", "Suru Verb", "Social & Communication"),
    ("houshin o tateru", "ほうしんをたてる", "ホウシンヲタテル", "方針を立てる", "to lay down a policy", "Ichidan", "Work & Study"),
    ("houtsuru", "ほうむる", "ホウムル", "葬る", "to bury / inter with respect", "Godan", "Culture & Society")
]
