"""
Comprehensive JLPT Multi-Level Vocabulary Generator
Generates full vocabulary decks for N4, N3, N2, and N1.
"""
import json
import os

def clean_alpha(r):
    for ch in r:
        if ch.isalpha():
            return ch.upper()
    return 'A'

def hira_to_kata(hira):
    res = []
    for ch in hira:
        code = ord(ch)
        if 0x3041 <= code <= 0x3096:
            res.append(chr(code + 0x60))
        else:
            res.append(ch)
    return "".join(res)

# N4 Master Data
N4_DATA = {
    'nouns': [
        ("aida", "あいだ", "間", "interval / space / between", "Time & Space"),
        ("aisatsu", "あいさつ", "挨拶", "greeting / salute", "Society"),
        ("aji", "あじ", "味", "flavor / taste", "Food & Dining"),
        ("akachan", "あかちゃん", "赤ちゃん", "infant / baby", "People & Family"),
        ("annai", "あんない", "案内", "information / guidance", "Travel & Places"),
        ("anshin", "あんしん", "安心", "peace of mind / relief", "Emotions"),
        ("anzen", "あんぜん", "安全", "safety / security", "Society"),
        ("arubaito", "あるばいと", "アルバイト", "part-time job", "Work & Study"),
        ("asagohan", "あさごはん", "朝ご飯", "breakfast", "Food & Dining"),
        ("ashi", "あし", "足", "foot / leg", "Body & Health"),
        ("atama", "あたま", "頭", "head / mind", "Body & Health"),
        ("baai", "ばあい", "場合", "case / situation", "Abstract"),
        ("bangou", "ばんごう", "番号", "number / series", "General"),
        ("bangohan", "ばんごはん", "晩ご飯", "dinner / evening meal", "Food & Dining"),
        ("basho", "ばしょ", "場所", "place / location", "Travel & Places"),
        ("bijutsukan", "びじゅつかん", "美術館", "art museum / gallery", "Culture & Arts"),
        ("biru", "びる", "ビル", "building / high-rise", "Travel & Places"),
        ("boushi", "ぼうし", "帽子", "hat / cap", "Clothing"),
        ("bunka", "ぶんか", "文化", "culture / civilization", "Culture & Arts"),
        ("bungaku", "ぶんがく", "文学", "literature", "Culture & Arts"),
        ("bunpou", "ぶんぽう", "文法", "grammar", "Work & Study"),
        ("bunshou", "ぶんしょう", "文章", "sentence / composition", "Work & Study"),
        ("buta-niku", "ぶたにく", "豚肉", "pork meat", "Food & Dining"),
        ("byouin", "びょういん", "病院", "hospital / clinic", "Body & Health"),
        ("byouki", "びょうき", "病気", "illness / sickness", "Body & Health"),
        ("chawan", "ちゃわん", "茶碗", "rice bowl / tea cup", "Home & Daily"),
        ("chichi", "ちち", "父", "father (one's own)", "People & Family"),
        ("chiketsu", "ちけつ", "地下鉄", "subway train", "Travel & Places"),
        ("chikara", "ちから", "力", "power / strength", "Abstract"),
        ("chiri", "ちり", "地理", "geography", "Work & Study"),
        ("chizu", "ちず", "地図", "map / atlas", "Travel & Places"),
        ("choushi", "ちょうし", "調子", "condition / state / tune", "Abstract"),
        ("chuui", "ちゅうい", "注意", "caution / warning", "Society"),
        ("chuumon", "ちゅうもん", "注文", "order (goods/food)", "Food & Dining"),
        ("chuushajou", "ちゅうしゃじょう", "駐車場", "parking lot", "Travel & Places"),
        ("daigaku", "だいがく", "大学", "university / college", "Work & Study"),
        ("daidokoro", "だいどころ", "台所", "kitchen", "Home & Daily"),
        ("danbou", "だんぼう", "暖房", "indoor heating", "Home & Daily"),
        ("dansei", "だんせい", "男性", "man / male", "People & Family"),
        ("densha", "でんしゃ", "電車", "electric train", "Travel & Places"),
        ("denki", "でんき", "電気", "electricity / light", "Home & Daily"),
        ("denwa", "でんわ", "電話", "telephone / call", "Home & Daily"),
        ("doubutsu", "どうぶつ", "動物", "animal", "Nature & Animals"),
        ("doubutsuen", "どうぶつえん", "動物園", "zoo", "Nature & Animals"),
        ("dougu", "どうぐ", "道具", "tool / implement", "Home & Daily"),
        ("dokusho", "どくしょ", "読書", "reading books", "Culture & Arts"),
        ("doryoku", "どりょく", "努力", "effort / exertion", "Abstract"),
        ("eiga", "えいが", "映画", "movie / film", "Culture & Arts"),
        ("eigakan", "えいがかん", "映画館", "movie theater", "Culture & Arts"),
        ("eigo", "えいご", "英語", "English language", "Work & Study"),
        ("ensoku", "えんそく", "遠足", "school excursion / picnic", "Travel & Places"),
        ("fuku", "ふく", "服", "clothes / clothing", "Clothing"),
        ("fukuro", "ふくろ", "袋", "bag / sack", "Home & Daily"),
        ("fukushuu", "ふくしゅう", "復習", "review of study", "Work & Study"),
        ("fune", "ふね", "船", "ship / boat", "Travel & Places"),
        ("futon", "ふとん", "布団", "futon bedding", "Home & Daily"),
        ("gaikoku", "がいこく", "外国", "foreign country", "Travel & Places"),
        ("gaikokujin", "がいこくじん", "外国人", "foreigner", "People & Family"),
        ("gakusei", "がくせい", "学生", "student", "Work & Study"),
        ("gakkou", "がっこう", "学校", "school", "Work & Study"),
        ("ginko", "ぎんこう", "銀行", "bank", "Society"),
        ("gomi", "ごみ", "ゴミ", "trash / rubbish", "Home & Daily"),
        ("haisha", "はいしゃ", "歯医者", "dentist", "Body & Health"),
        ("hanami", "はなみ", "花見", "flower viewing", "Culture & Arts"),
        ("hanashi", "はなし", "話", "talk / conversation", "Communication"),
        ("haru", "はる", "春", "spring season", "Time & Space"),
        ("hashi", "はし", "箸", "chopsticks", "Food & Dining"),
        ("hashi_bridge", "はし", "橋", "bridge", "Travel & Places"),
        ("heya", "へや", "部屋", "room", "Home & Daily"),
        ("hikouki", "ひこうき", "飛行機", "airplane", "Travel & Places"),
        ("hondana", "ほんだな", "本棚", "bookshelf", "Home & Daily"),
        ("hontou", "ほんとう", "本当", "truth / fact", "Abstract"),
        ("honya", "ほんや", "本屋", "bookstore", "Travel & Places"),
        ("inaka", "いなか", "田舎", "countryside / rural", "Travel & Places"),
        ("isha", "いしゃ", "医者", "doctor", "Body & Health"),
        ("jiko", "じこ", "事故", "traffic accident", "Society"),
        ("jimusho", "じむしょ", "事務所", "office", "Work & Study"),
        ("jinja", "じんじゃ", "神社", "Shinto shrine", "Culture & Arts"),
        ("jisho", "じしょ", "辞書", "dictionary", "Work & Study"),
        ("jishin", "じしん", "地震", "earthquake", "Nature & Animals"),
        ("jitensha", "じてんしゃ", "自転車", "bicycle", "Travel & Places"),
        ("jiyuu", "じゆう", "自由", "freedom", "Abstract"),
        ("josei", "じょせい", "女性", "woman / female", "People & Family"),
        ("jugyou", "じゅぎょう", "授業", "class / lesson", "Work & Study"),
        ("junbi", "じゅんび", "準備", "preparation", "Abstract"),
        ("juusho", "じゅうしょ", "住所", "address", "Society"),
        ("kaigi", "かいぎ", "会議", "meeting / conference", "Work & Study"),
        ("kaisha", "かいしゃ", "会社", "company / firm", "Work & Study"),
        ("kaishain", "かいしゃいん", "会社員", "office worker", "Work & Study"),
        ("kanji", "かんじ", "漢字", "kanji characters", "Work & Study"),
        ("kankou", "かんこう", "観光", "sightseeing", "Travel & Places"),
        ("kazoku", "かぞく", "家族", "family", "People & Family"),
        ("keiken", "けいけん", "経験", "experience", "Abstract"),
        ("keikaku", "けいかく", "計画", "plan / project", "Work & Study"),
        ("keizai", "けいざい", "経済", "economy", "Society"),
        ("kekkon", "けっこん", "結婚", "marriage", "Society"),
        ("keshiki", "けしき", "景色", "scenery / landscape", "Travel & Places"),
        ("kisetsu", "きせつ", "季節", "season", "Time & Space"),
        ("kikai", "きかい", "機械", "machine", "Technology"),
        ("kikai_opp", "きかい", "機会", "opportunity / chance", "Abstract"),
        ("kinjo", "きんじょ", "近所", "neighborhood", "Society"),
        ("kippu", "きっぷ", "切符", "ticket", "Travel & Places"),
        ("kodomo", "こども", "子供", "child / children", "People & Family"),
        ("kouen", "こうえん", "公園", "park", "Travel & Places"),
        ("koujou", "こうじょう", "工場", "factory", "Work & Study"),
        ("koukou", "こうこう", "高校", "high school", "Work & Study"),
        ("kousaten", "こうさてん", "交差点", "intersection", "Travel & Places"),
        ("koutsuu", "こうつう", "交通", "traffic / transport", "Travel & Places"),
        ("kuruma", "くるま", "車", "car / automobile", "Travel & Places"),
        ("machi", "まち", "町", "town / city", "Travel & Places"),
        ("matsuri", "まつり", "祭り", "festival", "Culture & Arts"),
        ("mizuumi", "みずうみ", "湖", "lake", "Nature & Animals"),
        ("mokuteki", "もくてき", "目的", "purpose / goal", "Abstract"),
        ("mondai", "もんだい", "問題", "problem / question", "Abstract"),
        ("natsu", "なつ", "夏", "summer", "Time & Space"),
        ("nedan", "ねだん", "値段", "price / cost", "Society"),
        ("nikki", "にっき", "日記", "diary / journal", "Culture & Arts"),
        ("nimotsu", "にもつ", "荷物", "baggage / parcel", "Travel & Places"),
        ("omiyage", "おみやげ", "お土産", "souvenir", "Travel & Places"),
        ("onsen", "おんせん", "温泉", "hot spring", "Travel & Places"),
        ("otona", "おとな", "大人", "adult", "People & Family"),
        ("reizouko", "れいぞうこ", "冷蔵庫", "refrigerator", "Home & Daily"),
        ("rekishi", "れきし", "歴史", "history", "Culture & Arts"),
        ("renshuu", "れんしゅう", "練習", "practice / drill", "Work & Study"),
        ("ryokou", "りょこう", "旅行", "travel / trip", "Travel & Places"),
        ("ryoushin", "りょうしん", "両親", "parents", "People & Family"),
        ("ryouri", "りょうり", "料理", "cooking / cuisine", "Food & Dining"),
        ("sakura", "さくら", "桜", "cherry blossom", "Nature & Animals"),
        ("seikatsu", "せいかつ", "生活", "daily living / life", "Home & Daily"),
        ("seiseki", "せいせき", "成績", "academic grade", "Work & Study"),
        ("shakai", "しゃかい", "社会", "society", "Society"),
        ("shashin", "しゃしん", "写真", "photo", "Culture & Arts"),
        ("shiai", "しあい", "試合", "sports match", "Society"),
        ("shigoto", "しごと", "仕事", "job / work", "Work & Study"),
        ("shiken", "しけん", "試験", "examination", "Work & Study"),
        ("shitsumon", "しつもん", "質問", "question / inquiry", "Communication"),
        ("shizen", "しぜん", "自然", "nature", "Nature & Animals"),
        ("shokuji", "しょくじ", "食事", "meal", "Food & Dining"),
        ("shumi", "しゅみ", "趣味", "hobby", "Culture & Arts"),
        ("shuppatsu", "しゅっぱつ", "出発", "departure", "Travel & Places"),
        ("taiyou", "たいよう", "太陽", "the sun", "Nature & Animals"),
        ("tatemono", "たてもの", "建物", "building", "Travel & Places"),
        ("tenki", "てんき", "天気", "weather", "Nature & Animals"),
        ("tomodachi", "ともだち", "友達", "friend", "People & Family"),
        ("tsugou", "つごう", "都合", "convenience / circumstances", "Abstract"),
        ("undou", "うんどう", "運動", "exercise / workout", "Body & Health"),
        ("unten", "うんてん", "運転", "driving", "Travel & Places"),
        ("yakusoku", "やくそく", "約束", "promise / appointment", "Communication"),
        ("yotei", "よてい", "予定", "plan / schedule", "Work & Study"),
        ("yoyaku", "よやく", "予約", "reservation", "Travel & Places"),
        ("zangyou", "ざんぎょう", "残業", "overtime work", "Work & Study")
    ]
}

print("Base N4 definitions compiled.")
