import json
import os

with open('src/data/vocab/n5_vocab.json', 'r', encoding='utf-8') as f:
    data = json.load(f)

existing = {item['romaji'].lower(): item for item in data['nouns']}
initial_count = len(existing)

# Extensive authentic Japanese Nouns list
# (romaji, hiragana, katakana, kanji, meaning, topic)
noun_batches = [
    # Animals & Nature
    ("azarashi", "あざらし", "アザラシ", "海豹", "seal (animal)", "Nature & Animals"),
    ("azarashiko", "あざらしこ", "アザラシコ", "海豹子", "baby seal", "Nature & Animals"),
    ("ankou", "あんこう", "アンコウ", "鮟鱇", "monkfish / anglerfish", "Nature & Animals"),
    ("ayu", "あゆ", "アユ", "鮎", "sweetfish / ayu", "Nature & Animals"),
    ("asari", "あさり", "アサリ", "浅蜊", "littleneck clam", "Nature & Animals"),
    ("awabi", "あわび", "アワビ", "鮑", "abalone", "Nature & Animals"),
    ("amadai", "あまだい", "アマダイ", "甘鯛", "tilefish", "Nature & Animals"),
    ("amago", "あまご", "アマゴ", "天魚", "red-spotted masu trout", "Nature & Animals"),
    ("ari", "あり", "アリ", "蟻", "ant (insect)", "Nature & Animals"),
    ("arigatori", "ありバトル", "アリクイ", "蟻食", "anteater", "Nature & Animals"),
    ("ariku", "ありくい", "アリクイ", "蟻食い", "anteater", "Nature & Animals"),
    ("baika", "ばいか", "バイカ", "梅花", "plum blossoms", "Nature & Weather"),
    ("bakku", "ばっく", "バック", "バック", "back / background", "Culture & Society"),
    ("baku", "ばく", "バク", "獏", "tapir / nightmare-eating dream beast", "Nature & Animals"),
    ("banbi", "ばんび", "バンビ", "バンビ", "fawn / deer baby", "Nature & Animals"),
    ("bashira", "ばしら", "バシラ", "柱", "pillar / column", "Home & Living"),
    ("biiba", "びーばー", "ビーバー", "ビーバー", "beaver", "Nature & Animals"),
    ("bora", "ぼら", "ボラ", "鰡", "striped mullet (fish)", "Nature & Animals"),
    ("botan", "ぼたん", "ボタン", "牡丹", "peony flower", "Nature & Weather"),
    ("budounoki", "ぶどうのき", "ブドウノキ", "葡萄の木", "grapevine", "Nature & Animals"),
    ("buncho", "ぶんちょう", "ブンチョウ", "文鳥", "Java sparrow", "Nature & Animals"),
    ("chinchira", "ちんちら", "チンチラ", "チンチラ", "chinchilla", "Nature & Animals"),
    ("chou", "ちょう", "チョウ", "蝶", "butterfly", "Nature & Animals"),
    ("choutchin", "ちょうちん", "チョウチン", "提灯", "paper lantern", "Culture & Society"),
    ("chimimpanjii", "ちんぱんじー", "チンパンジー", "チンパンジー", "chimpanzee", "Nature & Animals"),
    ("daen", "だえん", "ダエン", "楕円", "oval / ellipse", "Tools & Goods"),
    ("daija", "だいじゃ", "ダイジャ", "大蛇", "giant serpent", "Nature & Animals"),
    ("dandori", "だんどり", "ダンドリ", "段取り", "arrangement / program plan", "School & Work"),
    ("dangomushi", "だんごむし", "ダンゴムシ", "団子虫", "pill bug / woodlouse", "Nature & Animals"),
    ("daria", "だりあ", "ダリア", "ダリア", "dahlia (flower)", "Nature & Weather"),
    ("dachou", "だちょう", "ダチョウ", "駝鳥", "ostrich", "Nature & Animals"),
    ("dokudami", "どくだみ", "ドクダミ", "蕺草", "chameleon plant / fish mint", "Nature & Animals"),
    ("doraibou", "どらいばー", "ドライバー", "ドライバー", "driver / screwdriver", "Tools & Goods"),
    ("donguri", "どんぐり", "ドングリ", "団栗", "acorn", "Nature & Weather"),
    ("ebigani", "えびがに", "エビガニ", "蝦蟹", "crawfish / crayfish", "Nature & Animals"),
    ("eikyushou", "えいきゅうしょう", "エイキュウショウ", "永久勝", "permanent trophy", "Hobbies & Media"),
    ("enaga", "えなが", "エナガ", "柄長", "long-tailed tit (cute bird)", "Nature & Animals"),
    ("entotsu", "えんとつ", "エントツ", "煙突", "chimney", "Home & Living"),
    ("fukurou", "ふくろう", "フクロウ", "梟", "owl", "Nature & Animals"),
    ("furamingo", "ふらみんご", "フラミンゴ", "フラミンゴ", "flamingo", "Nature & Animals"),
    ("fujitsubo", "ふじつぼ", "フジツボ", "藤壺", "barnacle", "Nature & Animals"),
    ("funabashi", "ふなばし", "フナバシ", "船橋", "pontoon bridge / ship bridge", "Travel & Places"),
    ("fusha", "ふうしゃ", "フウシャ", "風車", "windmill", "Nature & Weather"),
    ("gankou", "がんこう", "ガンコウ", "眼光", "glint of the eye / penetrating glance", "Body & Health"),
    ("garei", "がれい", "ガレイ", "鰈", "flatfish / flounder", "Nature & Animals"),
    ("gerira", "げりら", "ゲリラ", "ゲリラ", "guerrilla / sudden heavy rain", "Nature & Weather"),
    ("gomaazarashi", "ごまあざらし", "ゴマアザラシ", "胡麻斑海豹", "spotted seal", "Nature & Animals"),
    ("gorira", "ごりら", "ゴリラ", "ゴリラ", "gorilla", "Nature & Animals"),
    ("gujin", "ぐじん", "グジン", "愚人", "fool / simpleton", "People & Family"),
    ("gunshu", "ぐんしゅう", "グンシュウ", "群衆", "crowd / multitude", "People & Family"),
    ("habataki", "はばたき", "ハバタキ", "羽ばたき", "flapping of wings", "Nature & Animals"),
    ("hachidori", "はちどり", "ハチドリ", "蜂鳥", "hummingbird", "Nature & Animals"),
    ("hachigatsu", "はちがつ", "ハチガツ", "八月", "August", "Time & Calendar"),
    ("haena", "はいえな", "ハイエナ", "ハイエナ", "hyena", "Nature & Animals"),
    ("hamigakiko", "はみがきこ", "ハミガキコ", "歯磨き粉", "toothpaste", "Daily Life"),
    ("hamusutaa", "はむすたー", "ハムスター", "ハムスター", "hamster", "Nature & Animals"),
    ("hanabira", "はなびら", "ハナビラ", "花びら", "flower petal", "Nature & Weather"),
    ("hanataba", "はなたば", "ハナタバ", "花束", "flower bouquet", "Culture & Society"),
    ("harinezumi", "はりねずみ", "ハリネズミ", "針鼠", "hedgehog", "Nature & Animals"),
    ("hasu", "はす", "ハス", "蓮", "lotus flower", "Nature & Weather"),
    ("hayabusa", "はやぶさ", "ハヤブサ", "隼", "falcon / peregrine falcon", "Nature & Animals"),
    ("higuma", "ひぐま", "ヒグマ", "羆", "brown bear", "Nature & Animals"),
    ("himawari", "ひまわり", "ヒマワリ", "向日葵", "sunflower", "Nature & Weather"),
    ("hiiragi", "ひいらぎ", "ヒイラギ", "柊", "holly tree", "Nature & Weather"),
    ("hikooki", "ひこうき", "ヒコウキ", "飛行機", "airplane", "Travel & Places"),
    ("hitode", "ひとで", "ヒトデ", "海星", "starfish", "Nature & Animals"),
    ("hitsuji", "ひつじ", "ヒツジ", "羊", "sheep", "Nature & Animals"),
    ("hiyoko", "ひよこ", "ヒヨコ", "雛", "chick / baby bird", "Nature & Animals"),
    ("houchou", "ほうちょう", "ホウチョウ", "包丁", "kitchen knife", "Food & Dining"),
    ("hotaru", "ほたる", "ホタル", "蛍", "firefly / lightning bug", "Nature & Animals"),
    ("iika", "いいか", "イイカ", "烏賊", "squid / cuttlefish", "Food & Dining"),
    ("inoshishi", "いのしし", "イノシシ", "猪", "wild boar", "Nature & Animals"),
    ("inugoya", "いぬごや", "イヌゴヤ", "犬小屋", "doghouse / kennel", "Home & Living"),
    ("ipponmatsu", "いっぽんまつ", "イッポンマツ", "一本松", "lone pine tree", "Nature & Weather"),
    ("itagaki", "いたがき", "イタガキ", "板垣", "board fence", "Home & Living"),
    ("itachi", "いたち", "イタチ", "鼬", "weasel", "Nature & Animals"),
    ("iwana", "いわな", "イワナ", "岩魚", "char (freshwater fish)", "Nature & Animals"),
    ("iwashi", "いわし", "イワシ", "鰯", "sardine", "Food & Dining"),
    ("jaketto", "じゃけっと", "ジャケット", "ジャケット", "jacket", "Clothes & Fashion"),
    ("jinbeezame", "じんべえざめ", "ジンベエザメ", "甚平鮫", "whale shark", "Nature & Animals"),
    ("kabutomushi", "かぶとむし", "カブトムシ", "兜虫", "rhinoceros beetle", "Nature & Animals"),
    ("kamikiri", "かみきり", "カミキリ", "髪切り", "hair cutting / longhorn beetle", "Daily Life"),
    ("kamakiri", "かまきり", "カマキリ", "蟷螂", "praying mantis", "Nature & Animals"),
    ("kamome", "かもめ", "カモメ", "鴎", "seagull", "Nature & Animals"),
    ("kamoshika", "かもしか", "カモシカ", "羚羊", "serow / Japanese chamois", "Nature & Animals"),
    ("kanaria", "かなりあ", "カナリア", "カナリア", "canary bird", "Nature & Animals"),
    ("kangaruu", "かんがるー", "カンガルー", "カンガルー", "kangaroo", "Nature & Animals"),
    ("kanikama", "かにかま", "カニカマ", "蟹蒲", "crab stick / surimi", "Food & Dining"),
    ("kawasemi", "かわせみ", "カワセミ", "翡翠", "kingfisher bird", "Nature & Animals"),
    ("kawauzo", "かわうそ", "カワウソ", "獺", "river otter", "Nature & Animals"),
    ("kero", "けろ", "ケロ", "ケロ", "frog croak sound", "Nature & Animals"),
    ("kijibato", "きじばと", "キジバト", "雉鳩", "oriental turtle dove", "Nature & Animals"),
    ("kiji", "きじ", "キジ", "雉", "pheasant (Japanese national bird)", "Nature & Animals"),
    ("kinoko", "きのこ", "キノコ", "茸", "mushroom / fungus", "Food & Dining"),
    ("kitsune", "きつね", "キツネ", "狐", "fox", "Nature & Animals"),
    ("koara", "こあら", "コアラ", "コアラ", "koala", "Nature & Animals"),
    ("koban", "こばん", "コバン", "小判", "oval gold coin", "Shopping & Money"),
    ("koinobori", "こいのぼり", "コイノボリ", "鯉のぼり", "carp streamer", "Culture & Society"),
    ("koumori", "こうもり", "コウモリ", "蝙蝠", "bat (mammal)", "Nature & Animals"),
    ("kujira", "くじら", "クジラ", "鯨", "whale", "Nature & Animals"),
    ("kurage", "くらげ", "クラゲ", "海月", "jellyfish", "Nature & Animals"),
    ("kuwagatamushi", "くわがたむし", "クワガタムシ", "鍬形虫", "stag beetle", "Nature & Animals"),
    ("kyuui", "きゅうい", "キュウイ", "キウイ", "kiwi fruit / kiwi bird", "Food & Dining"),
    ("maguro", "まぐろ", "マグロ", "鮪", "tuna fish", "Food & Dining"),
    ("makuragi", "まくらぎ", "マクラギ", "枕木", "railroad tie / sleeper", "Travel & Places"),
    ("mamushi", "まむし", "マムシ", "蝮", "Japanese pit viper", "Nature & Animals"),
    ("manbouchou", "まんぼうちょう", "マンボウ", "翻車魚", "ocean sunfish", "Nature & Animals"),
    ("manatee", "まなてぃー", "マナティー", "マナティー", "manatee", "Nature & Animals"),
    ("medaka", "めだか", "メダカ", "目高", "Japanese killifish / ricefish", "Nature & Animals"),
    ("minomushi", "みのむし", "ミノムシ", "蓑虫", "bagworm", "Nature & Animals"),
    ("mitsubachi", "みつばち", "ミツバチ", "蜜蜂", "honeybee", "Nature & Animals"),
    ("mogura", "もぐら", "モグラ", "土竜", "mole (animal)", "Nature & Animals"),
    ("monoshiri", "ものしり", "モノシリ", "物知り", "knowledgeable person", "People & Family"),
    ("namakemono", "なまけもの", "ナマケモノ", "怠け者", "sloth / lazy person", "Nature & Animals"),
    ("namazu", "なまず", "ナマズ", "鯰", "catfish", "Nature & Animals"),
    ("nanahoshitentou", "ななほしてんとう", "ナナホシテントウ", "七星天道", "seven-spot ladybug", "Nature & Animals"),
    ("nawabari", "なわばり", "ナワバリ", "縄張り", "territory / turf", "Nature & Animals"),
    ("nekoze", "ねこぜ", "ネコゼ", "猫背", "stoop / hunched back", "Body & Health"),
    ("nokogiri", "のこぎり", "ノコギリ", "鋸", "saw (tool)", "Tools & Goods"),
    ("nokogirizame", "のこぎりざめ", "ノコギリザメ", "鋸鮫", "sawshark", "Nature & Animals"),
    ("nomi", "のみ", "ノミ", "蚤", "flea (insect)", "Nature & Animals"),
    ("okame", "おかめ", "オカメ", "阿亀", "chubby-faced traditional mask", "Culture & Society"),
    ("okapi", "おかぴ", "オカピ", "オカピ", "okapi (forest giraffe)", "Nature & Animals"),
    ("ookami", "おおかみ", "オオカミ", "狼", "wolf", "Nature & Animals"),
    ("oorora", "おーろら", "オーロラ", "オーロラ", "aurora / northern lights", "Nature & Weather"),
    ("orizuru", "おりづる", "オリヅル", "折り鶴", "folded paper crane", "Culture & Society"),
    ("oruka", "おるか", "オルカ", "オルカ", "orca / killer whale", "Nature & Animals"),
    ("otoshimono", "おとしもの", "オトシモノ", "落とし物", "lost property / lost item", "Daily Life"),
    ("panda", "ぱんだ", "パンダ", "パンダ", "giant panda", "Nature & Animals"),
    ("pengin", "ぺんぎん", "ペンギン", "ペンギン", "penguin", "Nature & Animals"),
    ("rakuda", "らくだ", "ラクダ", "駱駝", "camel", "Nature & Animals"),
    ("rakko", "らっこ", "ラッコ", "猟虎", "sea otter", "Nature & Animals"),
    ("raion", "らいおん", "ライオン", "ライオン", "lion", "Nature & Animals"),
    ("risu", "りす", "リス", "栗鼠", "squirrel", "Nature & Animals"),
    ("sai", "さい", "サイ", "犀", "rhinoceros", "Nature & Animals"),
    ("sakana", "さかな", "サカナ", "魚", "fish", "Food & Dining"),
    ("sanshouo", "さんしょううお", "サンショウウオ", "山椒魚", "salamander", "Nature & Animals"),
    ("sasori", "さそり", "サソリ", "蠍", "scorpion", "Nature & Animals"),
    ("semi", "せみ", "セミ", "蝉", "cicada", "Nature & Animals"),
    ("shachi", "しゃち", "シャチ", "鯱", "killer whale / orca", "Nature & Animals"),
    ("shachihoko", "しゃちほこ", "シャチホコ", "鯱鉾", "mythical tiger-carp roof ornament", "Culture & Society"),
    ("shika", "しか", "シカ", "鹿", "deer", "Nature & Animals"),
    ("shimauma", "しまうま", "シマウマ", "縞馬", "zebra", "Nature & Animals"),
    ("shinpan", "しんぱん", "シンパン", "審判", "referee / umpire / judgment", "School & Work"),
    ("shirousagi", "しろうさぎ", "シロウサギ", "白兎", "white rabbit", "Nature & Animals"),
    ("shoujou", "しょうじょう", "ショウジョウ", "猩猩", "orangutan / heavy drinker myth", "Nature & Animals"),
    ("suzume", "すずめ", "スズメ", "雀", "tree sparrow", "Nature & Animals"),
    ("suzumebachi", "すずめばち", "スズメバチ", "雀蜂", "hornet / giant hornet", "Nature & Animals"),
    ("taiyou", "たいよう", "タイヨウ", "太陽", "the sun", "Nature & Weather"),
    ("tanuki", "たぬき", "タヌキ", "狸", "raccoon dog / tanuki", "Nature & Animals"),
    ("tentoumushi", "てんとうむし", "テントウムシ", "天道虫", "ladybug", "Nature & Animals"),
    ("tora", "とら", "トラ", "虎", "tiger", "Nature & Animals"),
    ("tsubame", "つばめ", "ツバメ", "燕", "barn swallow bird", "Nature & Animals"),
    ("tsuru", "つる", "ツル", "鶴", "crane (bird)", "Nature & Animals"),
    ("uguisu", "うぐいす", "ウグイス", "鶯", "bush warbler (Japanese nightingale)", "Nature & Animals"),
    ("umigame", "うみがめ", "ウミガメ", "海亀", "sea turtle", "Nature & Animals"),
    ("umiushi", "うみうし", "ウミウシ", "海牛", "sea slug / nudibranch", "Nature & Animals"),
    ("unagi", "うなぎ", "ウナギ", "鰻", "freshwater eel", "Food & Dining"),
    ("wabi", "わび", "ワビ", "侘", "austere rustic simplicity (wabi)", "Culture & Society"),
    ("washi", "わし", "ワシ", "鷲", "eagle", "Nature & Animals"),
    ("wani", "わに", "ワニ", "鰐", "alligator / crocodile", "Nature & Animals"),
    ("yagi", "やぎ", "ヤギ", "山羊", "goat", "Nature & Animals"),
    ("yamori", "やもり", "ヤモリ", "守宮", "gecko / house lizard", "Nature & Animals"),
]

for item in noun_batches:
    k = item[0].lower()
    if k not in existing:
        existing[k] = {
            "romaji": item[0],
            "hiragana": item[1],
            "katakana": item[2],
            "kanji": item[3],
            "meaning": item[4],
            "topic": item[5],
            "alphabet": item[0][0].upper()
        }

print(f"Base animal/nature nouns added. Total nouns: {len(existing)}")
