import json
import os

with open('src/data/vocab/n5_vocab.json', 'r', encoding='utf-8') as f:
    vocab_data = json.load(f)

existing = {item['romaji'].lower(): item for item in vocab_data['nouns']}

new_nouns = [
    # A
    {"romaji": "abura", "hiragana": "あぶら", "katakana": "アブラ", "kanji": "油", "meaning": "oil / fat", "topic": "Food & Dining"},
    {"romaji": "afurika", "hiragana": "あふりか", "katakana": "アフリカ", "kanji": "アフリカ", "meaning": "Africa", "topic": "Travel & Places"},
    {"romaji": "ahiruguchi", "hiragana": "あひるぐち", "katakana": "アヒルグチ", "kanji": "アヒル口", "meaning": "duck face / pout", "topic": "Body & Health"},
    {"romaji": "aida", "hiragana": "あいだ", "katakana": "アイダ", "kanji": "間", "meaning": "space between / interval", "topic": "Time & Calendar"},
    {"romaji": "aijin", "hiragana": "あいじん", "katakana": "アイジン", "kanji": "愛人", "meaning": "lover / mistress", "topic": "People & Family"},
    {"romaji": "aimai", "hiragana": "あいまい", "katakana": "アイマイ", "kanji": "曖昧", "meaning": "vagueness / ambiguity", "topic": "Culture & Society"},
    {"romaji": "ainiku", "hiragana": "あいにく", "katakana": "アイニク", "kanji": "生憎", "meaning": "unfortunate circumstance", "topic": "Daily Life"},
    {"romaji": "aite", "hiragana": "あいて", "katakana": "アイテ", "kanji": "相手", "meaning": "partner / other party", "topic": "People & Family"},
    {"romaji": "aizu", "hiragana": "あいず", "katakana": "アイズ", "kanji": "合図", "meaning": "sign / signal", "topic": "Daily Life"},
    {"romaji": "akago", "hiragana": "あかご", "katakana": "アカゴ", "kanji": "赤子", "meaning": "baby / infant", "topic": "People & Family"},
    {"romaji": "akari", "hiragana": "あかり", "katakana": "アカリ", "kanji": "明かり", "meaning": "light / illumination", "topic": "Home & Living"},
    {"romaji": "akichi", "hiragana": "あきち", "katakana": "アキチ", "kanji": "空き地", "meaning": "vacant lot / empty plot", "topic": "Travel & Places"},
    {"romaji": "akushu", "hiragana": "あくしゅ", "katakana": "アクシュ", "kanji": "握手", "meaning": "handshake", "topic": "Culture & Society"},
    {"romaji": "amerikajin", "hiragana": "あめりかじん", "katakana": "アメリカジン", "kanji": "アメリカ人", "meaning": "American person", "topic": "People & Family"},
    {"romaji": "ami", "hiragana": "あみ", "katakana": "アミ", "kanji": "網", "meaning": "net / mesh", "topic": "Tools & Goods"},
    {"romaji": "ando", "hiragana": "あんど", "katakana": "アンド", "kanji": "安堵", "meaning": "relief / peace of mind", "topic": "Emotions & Mind"},
    {"romaji": "anzen", "hiragana": "あんぜん", "katakana": "アンゼン", "kanji": "安全", "meaning": "safety / security", "topic": "Culture & Society"},
    {"romaji": "anzu", "hiragana": "あんず", "katakana": "アンズ", "kanji": "杏", "meaning": "apricot", "topic": "Food & Dining"},
    {"romaji": "aozora", "hiragana": "あおぞら", "katakana": "アオゾラ", "kanji": "青空", "meaning": "blue sky", "topic": "Nature & Weather"},
    {"romaji": "arai", "hiragana": "あらい", "katakana": "アライ", "kanji": "洗い", "meaning": "washing", "topic": "Daily Life"},
    {"romaji": "arashi", "hiragana": "あらし", "katakana": "アラシ", "kanji": "嵐", "meaning": "storm / tempest", "topic": "Nature & Weather"},
    {"romaji": "arerugii", "hiragana": "あれるぎー", "katakana": "アレルギー", "kanji": "アレルギー", "meaning": "allergy", "topic": "Body & Health"},
    {"romaji": "arubamu", "hiragana": "あるばむ", "katakana": "アルバム", "kanji": "アルバム", "meaning": "photo album / music album", "topic": "Hobbies & Media"},
    {"romaji": "arukooru", "hiragana": "あるこーる", "katakana": "アルコール", "kanji": "アルコール", "meaning": "alcohol", "topic": "Food & Dining"},
    {"romaji": "arumi", "hiragana": "あるみ", "katakana": "アルミ", "kanji": "アルミ", "meaning": "aluminum", "topic": "Tools & Goods"},
    {"romaji": "asagao", "hiragana": "あさがお", "katakana": "アサガオ", "kanji": "朝顔", "meaning": "morning glory flower", "topic": "Nature & Weather"},
    {"romaji": "asahi", "hiragana": "あさひ", "katakana": "アサヒ", "kanji": "朝日", "meaning": "morning sun / sunrise", "topic": "Nature & Weather"},
    {"romaji": "asanebou", "hiragana": "あさねぼう", "katakana": "アサネボウ", "kanji": "朝寝坊", "meaning": "oversleeping / late riser", "topic": "Daily Life"},
    {"romaji": "ase", "hiragana": "あせ", "katakana": "アセ", "kanji": "汗", "meaning": "sweat / perspiration", "topic": "Body & Health"},
    {"romaji": "ashimoto", "hiragana": "あしもと", "katakana": "アシモト", "kanji": "足元", "meaning": "at one's feet", "topic": "Body & Health"},
    {"romaji": "ashikubi", "hiragana": "あしくび", "katakana": "アシクビ", "kanji": "足首", "meaning": "ankle", "topic": "Body & Health"},
    {"romaji": "ato", "hiragana": "あと", "katakana": "アト", "kanji": "後", "meaning": "afterwards / behind", "topic": "Time & Calendar"},
    {"romaji": "atsusa", "hiragana": "あつさ", "katakana": "アツサ", "kanji": "暑さ", "meaning": "heat (weather)", "topic": "Nature & Weather"},
    {"romaji": "atsuryoku", "hiragana": "あつりょく", "katakana": "アツリョク", "kanji": "圧力", "meaning": "pressure / stress", "topic": "Science & Nature"},

    # B
    {"romaji": "ba", "hiragana": "ば", "katakana": "バ", "kanji": "場", "meaning": "place / spot / venue", "topic": "Travel & Places"},
    {"romaji": "baa", "hiragana": "ばー", "katakana": "バー", "kanji": "バー", "meaning": "bar / pub", "topic": "Food & Dining"},
    {"romaji": "baai", "hiragana": "ばあい", "katakana": "バアイ", "kanji": "場合", "meaning": "case / situation", "topic": "School & Work"},
    {"romaji": "bai", "hiragana": "ばい", "katakana": "バイ", "kanji": "倍", "meaning": "double / times / fold", "topic": "Science & Nature"},
    {"romaji": "baiku", "hiragana": "ばいく", "katakana": "バイク", "kanji": "バイク", "meaning": "motorcycle", "topic": "Travel & Places"},
    {"romaji": "baiten", "hiragana": "ばいてん", "katakana": "バイテン", "kanji": "売店", "meaning": "kiosk / shop stall", "topic": "Shopping & Money"},
    {"romaji": "baketsu", "hiragana": "ばけつ", "katakana": "バケツ", "kanji": "バケツ", "meaning": "bucket / pail", "topic": "Home & Living"},
    {"romaji": "bakudan", "hiragana": "ばくだん", "katakana": "バクダン", "kanji": "爆弾", "meaning": "bomb", "topic": "Culture & Society"},
    {"romaji": "bamen", "hiragana": "ばめん", "katakana": "バメン", "kanji": "場面", "meaning": "scene / setting", "topic": "Hobbies & Media"},
    {"romaji": "bangou", "hiragana": "ばんごう", "katakana": "バンゴウ", "kanji": "番号", "meaning": "number", "topic": "Daily Life"},
    {"romaji": "bangumi", "hiragana": "ばんぐみ", "katakana": "バングミ", "kanji": "番組", "meaning": "TV / radio program", "topic": "Hobbies & Media"},
    {"romaji": "bansoukou", "hiragana": "ばんそうこう", "katakana": "バンソウコウ", "kanji": "絆創膏", "meaning": "band-aid / adhesive plaster", "topic": "Body & Health"},
    {"romaji": "baorin", "hiragana": "ばいおりん", "katakana": "バイオリン", "kanji": "バイオリン", "meaning": "violin", "topic": "Hobbies & Media"},
    {"romaji": "baransu", "hiragana": "ばらんす", "katakana": "バランス", "kanji": "バランス", "meaning": "balance", "topic": "Body & Health"},
    {"romaji": "bari", "hiragana": "ばり", "katakana": "バリ", "kanji": "バリ", "meaning": "Bali", "topic": "Travel & Places"},
    {"romaji": "batoru", "hiragana": "ばとる", "katakana": "バトル", "kanji": "バトル", "meaning": "battle / match", "topic": "Hobbies & Media"},
    {"romaji": "bebiikaa", "hiragana": "べびーかー", "katakana": "ベビーカー", "kanji": "ベビーカー", "meaning": "stroller / baby buggy", "topic": "Daily Life"},
    {"romaji": "beddoruumu", "hiragana": "べっどるーむ", "katakana": "ベッドルーム", "kanji": "ベッドルーム", "meaning": "bedroom", "topic": "Home & Living"},
    {"romaji": "beikon", "hiragana": "べーこん", "katakana": "ベーコン", "kanji": "ベーコン", "meaning": "bacon", "topic": "Food & Dining"},
    {"romaji": "bengoshi", "hiragana": "べんごし", "katakana": "ベンゴシ", "kanji": "弁護士", "meaning": "lawyer / attorney", "topic": "School & Work"},
    {"romaji": "bentoubako", "hiragana": "べんとうばこ", "katakana": "ベントウバコ", "kanji": "弁当箱", "meaning": "lunch box", "topic": "Food & Dining"},
    {"romaji": "betsu", "hiragana": "べつ", "katakana": "ベツ", "kanji": "別", "meaning": "different / another", "topic": "Daily Life"},
    {"romaji": "bijin", "hiragana": "びじん", "katakana": "ビジン", "kanji": "美人", "meaning": "beautiful woman", "topic": "People & Family"},
    {"romaji": "bikkuri", "hiragana": "びっくり", "katakana": "ビックリ", "kanji": "吃驚", "meaning": "surprise / astonishment", "topic": "Emotions & Mind"},
    {"romaji": "biru", "hiragana": "びる", "katakana": "ビル", "kanji": "ビル", "meaning": "building", "topic": "Travel & Places"},
    {"romaji": "biza", "hiragana": "びざ", "katakana": "ビザ", "kanji": "ビザ", "meaning": "visa (passport)", "topic": "Travel & Places"},
    {"romaji": "boji", "hiragana": "ぼち", "katakana": "ボチ", "kanji": "墓地", "meaning": "cemetery / graveyard", "topic": "Culture & Society"},
    {"romaji": "bokushi", "hiragana": "ぼくし", "katakana": "ボクシ", "kanji": "牧師", "meaning": "pastor / priest", "topic": "People & Family"},
    {"romaji": "bokutou", "hiragana": "ぼくとう", "katakana": "ボクトウ", "kanji": "木刀", "meaning": "wooden training sword", "topic": "Hobbies & Media"},
    {"romaji": "bonodori", "hiragana": "ぼんおどり", "katakana": "ボンオドリ", "kanji": "盆踊り", "meaning": "Bon festival dance", "topic": "Culture & Society"},
    {"romaji": "borantia", "hiragana": "ぼらんてぃあ", "katakana": "ボランティア", "kanji": "ボランティア", "meaning": "volunteer", "topic": "Culture & Society"},
    {"romaji": "booru", "hiragana": "ぼーる", "katakana": "ボール", "kanji": "ボール", "meaning": "ball / sphere", "topic": "Hobbies & Media"},
    {"romaji": "booru-pen", "hiragana": "ぼーるぺん", "katakana": "ボールペン", "kanji": "ボールペン", "meaning": "ballpoint pen", "topic": "School & Work"},
    {"romaji": "boushi", "hiragana": "ぼうし", "katakana": "ボウシ", "kanji": "帽子", "meaning": "hat / cap", "topic": "Clothes & Fashion"},
    {"romaji": "boutou", "hiragana": "ぼうとう", "katakana": "ボウトウ", "kanji": "冒頭", "meaning": "beginning / opening", "topic": "School & Work"},
    {"romaji": "budo", "hiragana": "ぶどう", "katakana": "ブドウ", "kanji": "葡萄", "meaning": "grape", "topic": "Food & Dining"},
    {"romaji": "buhin", "hiragana": "ぶひん", "katakana": "ブヒン", "kanji": "部品", "meaning": "parts / accessories / components", "topic": "Tools & Goods"},
    {"romaji": "buka", "hiragana": "ぶか", "katakana": "ブカ", "kanji": "部下", "meaning": "subordinate (worker)", "topic": "School & Work"},
    {"romaji": "bukatsu", "hiragana": "ぶかつ", "katakana": "ブカツ", "kanji": "部活", "meaning": "club activities", "topic": "School & Work"},
    {"romaji": "bukka", "hiragana": "ぶっか", "katakana": "ブッカ", "kanji": "物価", "meaning": "cost of living / prices", "topic": "Shopping & Money"},
    {"romaji": "bun", "hiragana": "ぶん", "katakana": "ブン", "kanji": "文", "meaning": "sentence / text", "topic": "School & Work"},
    {"romaji": "bunka", "hiragana": "ぶんか", "katakana": "ブンカ", "kanji": "文化", "meaning": "culture", "topic": "Culture & Society"},
    {"romaji": "bunpou", "hiragana": "ぶんぽう", "katakana": "ブンポウ", "kanji": "文法", "meaning": "grammar", "topic": "School & Work"},
    {"romaji": "bunshou", "hiragana": "ぶんしょう", "katakana": "ブンショウ", "kanji": "文章", "meaning": "writing / composition / article", "topic": "School & Work"},
    {"romaji": "burausu", "hiragana": "ぶらうす", "katakana": "ブラウス", "kanji": "ブラウス", "meaning": "blouse", "topic": "Clothes & Fashion"},
    {"romaji": "burijji", "hiragana": "ぶりっじ", "katakana": "ブリッジ", "kanji": "ブリッジ", "meaning": "bridge", "topic": "Travel & Places"},
    {"romaji": "buranko", "hiragana": "ぶらんこ", "katakana": "ブランコ", "kanji": "ブランコ", "meaning": "swing (playground)", "topic": "Daily Life"},
    {"romaji": "buta", "hiragana": "ぶた", "katakana": "ブタ", "kanji": "豚", "meaning": "pig", "topic": "Nature & Animals"},
    {"romaji": "butaniku", "hiragana": "ぶたにく", "katakana": "ブタニク", "kanji": "豚肉", "meaning": "pork meat", "topic": "Food & Dining"},
    {"romaji": "butsukari", "hiragana": "ぶつかり", "katakana": "ブツカリ", "kanji": "ぶつかり", "meaning": "collision / clash", "topic": "Daily Life"},
    {"romaji": "byouin", "hiragana": "びょういん", "katakana": "ビョウイン", "kanji": "病院", "meaning": "hospital / clinic", "topic": "Body & Health"},
    {"romaji": "byouki", "hiragana": "びょうき", "katakana": "ビョウキ", "kanji": "病気", "meaning": "illness / disease", "topic": "Body & Health"},

    # C
    {"romaji": "chabashira", "hiragana": "ちゃばしら", "katakana": "チャバシラ", "kanji": "茶柱", "meaning": "tea stalk floating upright (good luck sign)", "topic": "Culture & Society"},
    {"romaji": "chadou", "hiragana": "ちゃどう", "katakana": "チャドウ", "kanji": "茶道", "meaning": "tea ceremony", "topic": "Culture & Society"},
    {"romaji": "chairo", "hiragana": "ちゃいろ", "katakana": "チャイロ", "kanji": "茶色", "meaning": "brown color", "topic": "Clothes & Fashion"},
    {"romaji": "chaneru", "hiragana": "ちゃんねる", "katakana": "チャンネル", "kanji": "チャンネル", "meaning": "channel (TV/YouTube)", "topic": "Hobbies & Media"},
    {"romaji": "chansu", "hiragana": "ちゃんす", "katakana": "チャンス", "kanji": "チャンス", "meaning": "chance / opportunity", "topic": "Daily Life"},
    {"romaji": "chawan", "hiragana": "ちゃわん", "katakana": "チャワン", "kanji": "茶碗", "meaning": "rice bowl / teacup", "topic": "Home & Living"},
    {"romaji": "chekkuto", "hiragana": "ちぇっく", "katakana": "チェック", "kanji": "チェック", "meaning": "check / verification", "topic": "Daily Life"},
    {"romaji": "chi", "hiragana": "ち", "katakana": "チ", "kanji": "血", "meaning": "blood", "topic": "Body & Health"},
    {"romaji": "chichi", "hiragana": "ちち", "katakana": "チチ", "kanji": "父", "meaning": "father (humble/one's own)", "topic": "People & Family"},
    {"romaji": "chie", "hiragana": "ちえ", "katakana": "チエ", "kanji": "知恵", "meaning": "wisdom / wit", "topic": "Emotions & Mind"},
    {"romaji": "chiho", "hiragana": "ちほう", "katakana": "チホウ", "kanji": "地方", "meaning": "region / rural area", "topic": "Travel & Places"},
    {"romaji": "chiisana", "hiragana": "ちいさな", "katakana": "チイサナ", "kanji": "小さな", "meaning": "small / little (noun modifier)", "topic": "Daily Life"},
    {"romaji": "chika", "hiragana": "ちか", "katakana": "チカ", "kanji": "地下", "meaning": "underground / basement", "topic": "Travel & Places"},
    {"romaji": "chikaku", "hiragana": "ちかく", "katakana": "チカク", "kanji": "近く", "meaning": "vicinity / near place", "topic": "Travel & Places"},
    {"romaji": "chikara", "hiragana": "ちから", "katakana": "チカラ", "kanji": "力", "meaning": "power / strength / ability", "topic": "Body & Health"},
    {"romaji": "chikyuu", "hiragana": "ちきゅう", "katakana": "チキュウ", "kanji": "地球", "meaning": "Earth (planet)", "topic": "Science & Nature"},
    {"romaji": "chiri", "hiragana": "ちり", "katakana": "チリ", "kanji": "地理", "meaning": "geography", "topic": "School & Work"},
    {"romaji": "chishiki", "hiragana": "ちしき", "katakana": "チシキ", "kanji": "知識", "meaning": "knowledge / information", "topic": "School & Work"},
    {"romaji": "chizu", "hiragana": "ちず", "katakana": "チズ", "kanji": "地図", "meaning": "map", "topic": "Travel & Places"},
    {"romaji": "chotto", "hiragana": "ちょっと", "katakana": "チョット", "kanji": "一寸", "meaning": "a little / a moment", "topic": "Daily Life"},
    {"romaji": "chuugakusei", "hiragana": "ちゅうがくせい", "katakana": "チュウガクセイ", "kanji": "中学生", "meaning": "junior high student", "topic": "School & Work"},
    {"romaji": "chuugoku", "hiragana": "ちゅうごく", "katakana": "チュウゴク", "kanji": "中国", "meaning": "China", "topic": "Travel & Places"},
    {"romaji": "chuumon", "hiragana": "ちゅうもん", "katakana": "チュウモン", "kanji": "注文", "meaning": "order (restaurant / goods)", "topic": "Food & Dining"},
    {"romaji": "chuusha", "hiragana": "ちゅうしゃ", "katakana": "チュウシャ", "kanji": "注射", "meaning": "injection / vaccination", "topic": "Body & Health"},
    {"romaji": "chuushajou", "hiragana": "ちゅうしゃじょう", "katakana": "チュウシャジョウ", "kanji": "駐車場", "meaning": "parking lot", "topic": "Travel & Places"},

    # D
    {"romaji": "dadokoro", "hiragana": "だいどころ", "katakana": "ダイドコロ", "kanji": "台所", "meaning": "kitchen", "topic": "Home & Living"},
    {"romaji": "dai", "hiragana": "だい", "katakana": "ダイ", "kanji": "題", "meaning": "topic / title / subject", "topic": "School & Work"},
    {"romaji": "daigaku", "hiragana": "だいがく", "katakana": "ダイガク", "kanji": "大学", "meaning": "university / college", "topic": "School & Work"},
    {"romaji": "daigakusei", "hiragana": "だいがくせい", "katakana": "ダイガクセイ", "kanji": "大学生", "meaning": "college student", "topic": "School & Work"},
    {"romaji": "daiji", "hiragana": "だいじ", "katakana": "ダイジ", "kanji": "大事", "meaning": "important matter / serious affair", "topic": "Daily Life"},
    {"romaji": "daikon", "hiragana": "だいこん", "katakana": "ダイコン", "kanji": "大根", "meaning": "Japanese giant white radish", "topic": "Food & Dining"},
    {"romaji": "dainingu", "hiragana": "だいにんぐ", "katakana": "ダイニング", "kanji": "ダイニング", "meaning": "dining room", "topic": "Home & Living"},
    {"romaji": "daiou", "hiragana": "だいおう", "katakana": "ダイオウ", "kanji": "大王", "meaning": "great king", "topic": "Culture & Society"},
    {"romaji": "daitou", "hiragana": "だいとうりょう", "katakana": "ダイトウリョウ", "kanji": "大統領", "meaning": "president (of a country)", "topic": "Culture & Society"},
    {"romaji": "dango", "hiragana": "だんご", "katakana": "ダンゴ", "kanji": "団子", "meaning": "sweet dumpling", "topic": "Food & Dining"},
    {"romaji": "dansei", "hiragana": "だんせい", "katakana": "ダンセイ", "kanji": "男性", "meaning": "male / man", "topic": "People & Family"},
    {"romaji": "danwa", "hiragana": "だんわ", "katakana": "ダンワ", "kanji": "談話", "meaning": "talk / conversation / discourse", "topic": "Culture & Society"},
    {"romaji": "deeto", "hiragana": "でーと", "katakana": "デート", "kanji": "デート", "meaning": "romantic date", "topic": "People & Family"},
    {"romaji": "deguchi", "hiragana": "でぐち", "katakana": "デグチ", "kanji": "出口", "meaning": "exit", "topic": "Travel & Places"},
    {"romaji": "densha", "hiragana": "でんしゃ", "katakana": "デンシャ", "kanji": "電車", "meaning": "electric train", "topic": "Travel & Places"},
    {"romaji": "denwa", "hiragana": "でんわ", "katakana": "デンワ", "kanji": "電話", "meaning": "telephone / phone call", "topic": "Daily Life"},
    {"romaji": "denki", "hiragana": "でんき", "katakana": "デンキ", "kanji": "電気", "meaning": "electricity / light", "topic": "Home & Living"},
    {"romaji": "denpa", "hiragana": "でんぱ", "katakana": "デンパ", "kanji": "電波", "meaning": "radio waves / phone signal", "topic": "Tools & Goods"},
    {"romaji": "dentou", "hiragana": "でんとう", "katakana": "デントウ", "kanji": "伝統", "meaning": "tradition / heritage", "topic": "Culture & Society"},
    {"romaji": "dezaato", "hiragana": "でざーと", "katakana": "デザート", "kanji": "デザート", "meaning": "dessert", "topic": "Food & Dining"},
    {"romaji": "doitsu", "hiragana": "どいつ", "katakana": "ドイツ", "kanji": "ドイツ", "meaning": "Germany", "topic": "Travel & Places"},
    {"romaji": "dokushin", "hiragana": "どくしん", "katakana": "ドクシン", "kanji": "独身", "meaning": "single / bachelor", "topic": "People & Family"},
    {"romaji": "dokusho", "hiragana": "どくしょ", "katakana": "ドクショ", "kanji": "読書", "meaning": "reading books", "topic": "Hobbies & Media"},
    {"romaji": "donguri", "hiragana": "どんぐり", "katakana": "ドングリ", "kanji": "団栗", "meaning": "acorn", "topic": "Nature & Animals"},
    {"romaji": "donyu", "hiragana": "どうにゅう", "katakana": "ドウニュウ", "kanji": "導入", "meaning": "introduction / onboarding", "topic": "School & Work"},
    {"romaji": "doa", "hiragana": "どあ", "katakana": "ドア", "kanji": "ドア", "meaning": "door", "topic": "Home & Living"},
    {"romaji": "dorama", "hiragana": "どらま", "katakana": "ドラマ", "kanji": "ドラマ", "meaning": "TV drama", "topic": "Hobbies & Media"},
    {"romaji": "doraiyaa", "hiragana": "どらいやー", "katakana": "ドライヤー", "kanji": "ドライヤー", "meaning": "hair dryer", "topic": "Daily Life"},
    {"romaji": "doro", "hiragana": "どろ", "katakana": "ドロ", "kanji": "泥", "meaning": "mud / dirt", "topic": "Nature & Weather"},
    {"romaji": "dorobou", "hiragana": "どろぼう", "katakana": "ドロボウ", "kanji": "泥棒", "meaning": "thief / burglar", "topic": "Culture & Society"},
    {"romaji": "doubutsu", "hiragana": "どうぶつ", "katakana": "ドウブツ", "kanji": "動物", "meaning": "animal", "topic": "Nature & Animals"},
    {"romaji": "doubutsuen", "hiragana": "どうぶつえん", "katakana": "ドウブツエン", "kanji": "動物園", "meaning": "zoo", "topic": "Travel & Places"},
    {"romaji": "douga", "hiragana": "どうが", "katakana": "ドウガ", "kanji": "動画", "meaning": "video / movie clip", "topic": "Hobbies & Media"},
    {"romaji": "dougu", "hiragana": "どうぐ", "katakana": "ドウグ", "kanji": "道具", "meaning": "tool / equipment", "topic": "Tools & Goods"},
    {"romaji": "douryo", "hiragana": "どうりょう", "katakana": "ドウリョウ", "kanji": "同僚", "meaning": "colleague / coworker", "topic": "School & Work"},
    {"romaji": "douro", "hiragana": "どうろ", "katakana": "ドウロ", "kanji": "道路", "meaning": "road / highway", "topic": "Travel & Places"},

    # E
    {"romaji": "ebi", "hiragana": "えび", "katakana": "エビ", "kanji": "海老", "meaning": "shrimp / prawn", "topic": "Food & Dining"},
    {"romaji": "edamame", "hiragana": "えだまめ", "katakana": "エダマメ", "kanji": "枝豆", "meaning": "green soybeans", "topic": "Food & Dining"},
    {"romaji": "ehon", "hiragana": "えほん", "katakana": "エホン", "kanji": "絵本", "meaning": "picture book", "topic": "Hobbies & Media"},
    {"romaji": "eiga", "hiragana": "えいが", "katakana": "エイガ", "kanji": "映画", "meaning": "movie / cinema", "topic": "Hobbies & Media"},
    {"romaji": "eigakan", "hiragana": "えいがかん", "katakana": "エイガカン", "kanji": "映画館", "meaning": "movie theater", "topic": "Travel & Places"},
    {"romaji": "eigo", "hiragana": "えいご", "katakana": "エイゴ", "kanji": "英語", "meaning": "English language", "topic": "School & Work"},
    {"romaji": "eikyou", "hiragana": "えいきょう", "katakana": "エイキョウ", "kanji": "影響", "meaning": "influence / effect", "topic": "Culture & Society"},
    {"romaji": "eisei", "hiragana": "えいせい", "katakana": "エイセイ", "kanji": "衛星", "meaning": "satellite", "topic": "Science & Nature"},
    {"romaji": "eiyou", "hiragana": "えいよう", "katakana": "エイヨウ", "kanji": "栄養", "meaning": "nutrition / nourishment", "topic": "Food & Dining"},
    {"romaji": "eki", "hiragana": "えき", "katakana": "エキ", "kanji": "駅", "meaning": "train station", "topic": "Travel & Places"},
    {"romaji": "ekimae", "hiragana": "えきまえ", "katakana": "エキマエ", "kanji": "駅前", "meaning": "in front of the station", "topic": "Travel & Places"},
    {"romaji": "ekisupaato", "hiragana": "えきすぱーと", "katakana": "エキスパート", "kanji": "エキスパート", "meaning": "expert", "topic": "School & Work"},
    {"romaji": "en", "hiragana": "えん", "katakana": "エン", "kanji": "円", "meaning": "yen (currency) / circle", "topic": "Shopping & Money"},
    {"romaji": "enogu", "hiragana": "えのぐ", "katakana": "エノグ", "kanji": "絵の具", "meaning": "paints / colors", "topic": "Hobbies & Media"},
    {"romaji": "enpitsu", "hiragana": "えんぴつ", "katakana": "エンピツ", "kanji": "鉛筆", "meaning": "pencil", "topic": "School & Work"},
    {"romaji": "ensoku", "hiragana": "えんそく", "katakana": "エンソク", "kanji": "遠足", "meaning": "field trip / excursion", "topic": "School & Work"},
    {"romaji": "erebeetaa", "hiragana": "えれべーたー", "katakana": "エレベーター", "kanji": "エレベーター", "meaning": "elevator / lift", "topic": "Home & Living"},
    {"romaji": "esukareetaa", "hiragana": "えすかれーたー", "katakana": "エスカレーター", "kanji": "エスカレーター", "meaning": "escalator", "topic": "Travel & Places"},
    {"romaji": "eto", "hiragana": "えと", "katakana": "エト", "kanji": "干支", "meaning": "Chinese zodiac signs", "topic": "Culture & Society"},

    # F
    {"romaji": "faan", "hiragana": "ふぁん", "katakana": "ファン", "kanji": "ファン", "meaning": "fan / enthusiast / ventilator", "topic": "Hobbies & Media"},
    {"romaji": "fairu", "hiragana": "ふぁいる", "katakana": "ファイル", "kanji": "ファイル", "meaning": "file / binder", "topic": "School & Work"},
    {"romaji": "fakusu", "hiragana": "ふぁくす", "katakana": "ファクス", "kanji": "ファクス", "meaning": "fax", "topic": "School & Work"},
    {"romaji": "fasshon", "hiragana": "ふぁっしょん", "katakana": "ファッション", "kanji": "ファッション", "meaning": "fashion", "topic": "Clothes & Fashion"},
    {"romaji": "fooku", "hiragana": "ふぉーく", "katakana": "フォーク", "kanji": "フォーク", "meaning": "fork (eating utensil)", "topic": "Food & Dining"},
    {"romaji": "fuben", "hiragana": "ふべん", "katakana": "フベン", "kanji": "不便", "meaning": "inconvenience", "topic": "Daily Life"},
    {"romaji": "fuda", "hiragana": "ふだ", "katakana": "フダ", "kanji": "札", "meaning": "card / tag / amulet", "topic": "Tools & Goods"},
    {"romaji": "fude", "hiragana": "ふで", "katakana": "フデ", "kanji": "筆", "meaning": "calligraphy brush", "topic": "Culture & Society"},
    {"romaji": "fudebako", "hiragana": "ふでばこ", "katakana": "フデバコ", "kanji": "筆箱", "meaning": "pencil case", "topic": "School & Work"},
    {"romaji": "fue", "hiragana": "ふえ", "katakana": "フエ", "kanji": "笛", "meaning": "flute / whistle", "topic": "Hobbies & Media"},
    {"romaji": "fuji", "hiragana": "ふじさん", "katakana": "フジサン", "kanji": "富士山", "meaning": "Mount Fuji", "topic": "Travel & Places"},
    {"romaji": "fujin", "hiragana": "ふじん", "katakana": "フジン", "kanji": "夫人", "meaning": "madam / lady / wife", "topic": "People & Family"},
    {"romaji": "fukasa", "hiragana": "ふかさ", "katakana": "フカサ", "kanji": "深さ", "meaning": "depth", "topic": "Science & Nature"},
    {"romaji": "fukin", "hiragana": "ふきん", "katakana": "フキン", "kanji": "布巾", "meaning": "dishcloth / tea towel", "topic": "Home & Living"},
    {"romaji": "fukuro", "hiragana": "ふくろ", "katakana": "フクロウ", "kanji": "袋", "meaning": "bag / pouch", "topic": "Shopping & Money"},
    {"romaji": "fukusou", "hiragana": "ふくそう", "katakana": "フクソウ", "kanji": "服装", "meaning": "attire / clothing style", "topic": "Clothes & Fashion"},
    {"romaji": "fukushuu", "hiragana": "ふくしゅう", "katakana": "フクシュウ", "kanji": "復習", "meaning": "review (of study)", "topic": "School & Work"},
    {"romaji": "fumi", "hiragana": "ふみ", "katakana": "フミ", "kanji": "文", "meaning": "letter / note", "topic": "Daily Life"},
    {"romaji": "fune", "hiragana": "ふね", "katakana": "フネ", "kanji": "船", "meaning": "ship / boat", "topic": "Travel & Places"},
    {"romaji": "fuufu", "hiragana": "ふうふ", "katakana": "フウフ", "kanji": "夫婦", "meaning": "married couple / husband and wife", "topic": "People & Family"},
    {"romaji": "fuusen", "hiragana": "ふうせん", "katakana": "フウセン", "kanji": "風船", "meaning": "balloon", "topic": "Daily Life"},
    {"romaji": "fuutou", "hiragana": "ふうとう", "katakana": "フウトウ", "kanji": "封筒", "meaning": "envelope", "topic": "Daily Life"},
    {"romaji": "fuyu", "hiragana": "ふゆ", "katakana": "フユ", "kanji": "冬", "meaning": "winter", "topic": "Nature & Weather"},
    {"romaji": "fuyuyasumi", "hiragana": "ふゆやすみ", "katakana": "フユヤスミ", "kanji": "冬休み", "meaning": "winter vacation", "topic": "Time & Calendar"},

    # G
    {"romaji": "gaikoku", "hiragana": "がいこく", "katakana": "ガイコク", "kanji": "外国", "meaning": "foreign country", "topic": "Travel & Places"},
    {"romaji": "gaikokujin", "hiragana": "がいこくじん", "katakana": "ガイコクジン", "kanji": "外国人", "meaning": "foreigner", "topic": "People & Family"},
    {"romaji": "gakki", "hiragana": "がっき", "katakana": "ガッキ", "kanji": "楽器", "meaning": "musical instrument", "topic": "Hobbies & Media"},
    {"romaji": "gakkou", "hiragana": "がっこう", "katakana": "ガッコウ", "kanji": "学校", "meaning": "school", "topic": "School & Work"},
    {"romaji": "gakusei", "hiragana": "がくせい", "katakana": "ガクセイ", "kanji": "学生", "meaning": "student", "topic": "School & Work"},
    {"romaji": "gakumon", "hiragana": "がくもん", "katakana": "ガクモン", "kanji": "学問", "meaning": "scholarship / learning", "topic": "School & Work"},
    {"romaji": "gaman", "hiragana": "がまん", "katakana": "ガマン", "kanji": "我慢", "meaning": "patience / endurance", "topic": "Emotions & Mind"},
    {"romaji": "gamu", "hiragana": "がむ", "katakana": "ガム", "kanji": "ガム", "meaning": "chewing gum", "topic": "Food & Dining"},
    {"romaji": "garasu", "hiragana": "がらす", "katakana": "ガラス", "kanji": "ガラス", "meaning": "glass (material / pane)", "topic": "Home & Living"},
    {"romaji": "gasu", "hiragana": "がす", "katakana": "ガス", "kanji": "ガス", "meaning": "gas", "topic": "Home & Living"},
    {"romaji": "gasorin", "hiragana": "がそりん", "katakana": "ガソリン", "kanji": "ガソリン", "meaning": "gasoline / petrol", "topic": "Travel & Places"},
    {"romaji": "geijutsu", "hiragana": "げいじゅつ", "katakana": "ゲイジュツ", "kanji": "芸術", "meaning": "art / the fine arts", "topic": "Culture & Society"},
    {"romaji": "geinou", "hiragana": "げいのう", "katakana": "ゲイノウ", "kanji": "芸能", "meaning": "show business / entertainment", "topic": "Hobbies & Media"},
    {"romaji": "gekiryuu", "hiragana": "げきりゅう", "katakana": "ゲキリュウ", "kanji": "激流", "meaning": "torrent / raging stream", "topic": "Nature & Weather"},
    {"romaji": "gendaigaku", "hiragana": "げんだい", "katakana": "ゲンダイ", "kanji": "現代", "meaning": "modern era / present day", "topic": "Time & Calendar"},
    {"romaji": "genin", "hiragana": "げんいん", "katakana": "ゲンイン", "kanji": "原因", "meaning": "cause / origin", "topic": "School & Work"},
    {"romaji": "genkan", "hiragana": "げんかん", "katakana": "ゲンカン", "kanji": "玄関", "meaning": "entryway / front hall", "topic": "Home & Living"},
    {"romaji": "genki", "hiragana": "げんき", "katakana": "ゲンキ", "kanji": "元気", "meaning": "energy / vitality / good health", "topic": "Body & Health"},
    {"romaji": "genkou", "hiragana": "げんこう", "katakana": "ゲンコウ", "kanji": "原稿", "meaning": "manuscript / draft", "topic": "School & Work"},
    {"romaji": "ginko", "hiragana": "ぎんこう", "katakana": "ギンコウ", "kanji": "銀行", "meaning": "bank", "topic": "Shopping & Money"},
    {"romaji": "gin", "hiragana": "ぎん", "katakana": "ギン", "kanji": "銀", "meaning": "silver", "topic": "Tools & Goods"},
    {"romaji": "gitaa", "hiragana": "ぎたー", "katakana": "ギター", "kanji": "ギター", "meaning": "guitar", "topic": "Hobbies & Media"},
    {"romaji": "gomi", "hiragana": "ごみ", "katakana": "ゴミ", "kanji": "ゴミ", "meaning": "garbage / trash", "topic": "Daily Life"},
    {"romaji": "gomibako", "hiragana": "ごみばこ", "katakana": "ゴミバコ", "kanji": "ゴミ箱", "meaning": "trash can / dustbin", "topic": "Home & Living"},
    {"romaji": "gorufu", "hiragana": "ごるふ", "katakana": "ゴルフ", "kanji": "ゴルフ", "meaning": "golf", "topic": "Hobbies & Media"},
    {"romaji": "goshujin", "hiragana": "ごしゅじん", "katakana": "ゴシュジン", "kanji": "ご主人", "meaning": "someone else's husband", "topic": "People & Family"},
    {"romaji": "gogo", "hiragana": "ごご", "katakana": "ゴゴ", "kanji": "午後", "meaning": "afternoon / PM", "topic": "Time & Calendar"},
    {"romaji": "gozen", "hiragana": "ごぜん", "katakana": "ゴゼン", "kanji": "午前", "meaning": "morning / AM", "topic": "Time & Calendar"},
    {"romaji": "guntai", "hiragana": "ぐんたい", "katakana": "グンタイ", "kanji": "軍隊", "meaning": "army / military troops", "topic": "Culture & Society"},
    {"romaji": "gurando", "hiragana": "ぐらんど", "katakana": "グランド", "kanji": "グランド", "meaning": "sports field / grounds", "topic": "Hobbies & Media"},
    {"romaji": "gurume", "hiragana": "ぐるめ", "katakana": "グルメ", "kanji": "グルメ", "meaning": "gourmet food / foodie", "topic": "Food & Dining"},
    {"romaji": "gurasu", "hiragana": "ぐらす", "katakana": "グラス", "kanji": "グラス", "meaning": "drinking glass", "topic": "Food & Dining"},
    {"romaji": "gyakushuu", "hiragana": "ぎゃくしゅう", "katakana": "ギャクシュウ", "kanji": "逆襲", "meaning": "counterattack", "topic": "Hobbies & Media"},
    {"romaji": "gyouza", "hiragana": "ぎょうざ", "katakana": "ギョウザ", "kanji": "餃子", "meaning": "gyoza / fried dumplings", "topic": "Food & Dining"},
    {"romaji": "gyuuniku", "hiragana": "ぎゅうにく", "katakana": "ギュウニク", "kanji": "牛肉", "meaning": "beef", "topic": "Food & Dining"},
    {"romaji": "gyuunyuu", "hiragana": "ぎゅうにゅう", "katakana": "ギュウニュウ", "kanji": "牛乳", "meaning": "cow's milk", "topic": "Food & Dining"},

    # H
    {"romaji": "ha", "hiragana": "は", "katakana": "ハ", "kanji": "歯", "meaning": "tooth / teeth", "topic": "Body & Health"},
    {"romaji": "haba", "hiragana": "はば", "katakana": "ハバ", "kanji": "幅", "meaning": "width / breadth", "topic": "Science & Nature"},
    {"romaji": "haburashi", "hiragana": "はぶらし", "katakana": "ハブラシ", "kanji": "歯ブラシ", "meaning": "toothbrush", "topic": "Daily Life"},
    {"romaji": "hachi", "hiragana": "はち", "katakana": "ハチ", "kanji": "蜂", "meaning": "bee / wasp", "topic": "Nature & Animals"},
    {"romaji": "haeru", "hiragana": "はえ", "katakana": "ハエ", "kanji": "蝿", "meaning": "housefly", "topic": "Nature & Animals"},
    {"romaji": "hagaki", "hiragana": "はがき", "katakana": "ハガキ", "kanji": "葉書", "meaning": "postcard", "topic": "Daily Life"},
    {"romaji": "haizara", "hiragana": "はいざら", "katakana": "ハイザラ", "kanji": "灰皿", "meaning": "ashtray", "topic": "Daily Life"},
    {"romaji": "haiyuu", "hiragana": "はいゆう", "katakana": "ハイユウ", "kanji": "俳優", "meaning": "actor / performer", "topic": "People & Family"},
    {"romaji": "hakama", "hiragana": "はかま", "katakana": "ハカマ", "kanji": "袴", "meaning": "traditional pleated culottes/trousers", "topic": "Clothes & Fashion"},
    {"romaji": "hakubutsukan", "hiragana": "はくぶつかん", "katakana": "ハクブツカン", "kanji": "博物館", "meaning": "museum", "topic": "Travel & Places"},
    {"romaji": "hamu", "hiragana": "はむ", "katakana": "ハム", "kanji": "ハム", "meaning": "ham", "topic": "Food & Dining"},
    {"romaji": "hana", "hiragana": "はな", "katakana": "ハナ", "kanji": "花", "meaning": "flower", "topic": "Nature & Animals"},
    {"romaji": "hanabi", "hiragana": "はなび", "katakana": "ハナビ", "kanji": "花火", "meaning": "fireworks", "topic": "Culture & Society"},
    {"romaji": "hanami", "hiragana": "はなみ", "katakana": "ハナミ", "kanji": "花見", "meaning": "cherry blossom viewing", "topic": "Culture & Society"},
    {"romaji": "hanataba", "hiragana": "はなたば", "katakana": "ハナタバ", "kanji": "花束", "meaning": "bouquet of flowers", "topic": "Culture & Society"},
    {"romaji": "hanashi", "hiragana": "はなし", "katakana": "ハナシ", "kanji": "話", "meaning": "talk / story / conversation", "topic": "Daily Life"},
    {"romaji": "handobaggu", "hiragana": "はんどばっぐ", "katakana": "ハンドバッグ", "kanji": "ハンドバッグ", "meaning": "handbag", "topic": "Clothes & Fashion"},
    {"romaji": "hankachi", "hiragana": "はんかち", "katakana": "ハンカチ", "kanji": "ハンカチ", "meaning": "handkerchief", "topic": "Clothes & Fashion"},
    {"romaji": "hanko", "hiragana": "はんこ", "katakana": "ハンコ", "kanji": "判子", "meaning": "name stamp / seal", "topic": "Daily Life"},
    {"romaji": "hanmi", "hiragana": "はんぶん", "katakana": "ハンブン", "kanji": "半分", "meaning": "half", "topic": "Daily Life"},
    {"romaji": "haori", "hiragana": "はおり", "katakana": "ハオリ", "kanji": "羽織", "meaning": "Japanese kimono jacket", "topic": "Clothes & Fashion"},
    {"romaji": "hare", "hiragana": "はれ", "katakana": "ハレ", "kanji": "晴れ", "meaning": "clear sunny weather", "topic": "Nature & Weather"},
    {"romaji": "haru", "hiragana": "はる", "katakana": "ハル", "kanji": "春", "meaning": "spring season", "topic": "Nature & Weather"},
    {"romaji": "hasami", "hiragana": "はさみ", "katakana": "ハサミ", "kanji": "鋏", "meaning": "scissors", "topic": "Tools & Goods"},
    {"romaji": "hashi", "hiragana": "はし", "katakana": "ハシ", "kanji": "箸", "meaning": "chopsticks", "topic": "Food & Dining"},
    {"romaji": "hashigo", "hiragana": "はしご", "katakana": "ハシゴ", "kanji": "梯子", "meaning": "ladder", "topic": "Tools & Goods"},
    {"romaji": "hatake", "hiragana": "はたけ", "katakana": "ハタケ", "kanji": "畑", "meaning": "cultivated field / garden farm", "topic": "Nature & Animals"},
    {"romaji": "hatamoto", "hiragana": "はた", "katakana": "ハタ", "kanji": "旗", "meaning": "flag / banner", "topic": "Culture & Society"},
    {"romaji": "hatachi", "hiragana": "はたち", "katakana": "ハタチ", "kanji": "二十歳", "meaning": "twenty years of age", "topic": "People & Family"},
    {"romaji": "hato", "hiragana": "はと", "katakana": "ハト", "kanji": "鳩", "meaning": "pigeon / dove", "topic": "Nature & Animals"},
    {"romaji": "hatsuon", "hiragana": "はつおん", "katakana": "ハツオン", "kanji": "発音", "meaning": "pronunciation", "topic": "School & Work"},
    {"romaji": "hayashi", "hiragana": "はやし", "katakana": "ハヤシ", "kanji": "林", "meaning": "grove / woods", "topic": "Nature & Animals"},
    {"romaji": "heya", "hiragana": "へや", "katakana": "ヘヤ", "kanji": "部屋", "meaning": "room", "topic": "Home & Living"},
    {"romaji": "heiwa", "hiragana": "へいわ", "katakana": "ヘイワ", "kanji": "平和", "meaning": "peace / harmony", "topic": "Culture & Society"},
    {"romaji": "henka", "hiragana": "へんか", "katakana": "ヘンカ", "kanji": "変化", "meaning": "change / transformation", "topic": "Daily Life"},
    {"romaji": "henji", "hiragana": "へんじ", "katakana": "ヘンジ", "kanji": "返事", "meaning": "reply / answer", "topic": "Daily Life"},
    {"romaji": "heta", "hiragana": "へた", "katakana": "ヘタ", "kanji": "下手", "meaning": "unskilled / poor at", "topic": "School & Work"},
    {"romaji": "hige", "hiragana": "ひげ", "katakana": "ヒゲ", "kanji": "髭", "meaning": "beard / mustache", "topic": "Body & Health"},
    {"romaji": "hikari", "hiragana": "ひかり", "katakana": "ヒカリ", "kanji": "光", "meaning": "light / beam", "topic": "Nature & Weather"},
    {"romaji": "hikidashi", "hiragana": "ひきだし", "katakana": "ヒキダシ", "kanji": "引き出し", "meaning": "drawer (furniture)", "topic": "Home & Living"},
    {"romaji": "hikouki", "hiragana": "ひこうき", "katakana": "ヒコウキ", "kanji": "飛行機", "meaning": "airplane", "topic": "Travel & Places"},
    {"romaji": "hikoujou", "hiragana": "ひこうじょう", "katakana": "ヒコウジョウ", "kanji": "飛行場", "meaning": "airfield / airport", "topic": "Travel & Places"},
    {"romaji": "hima", "hiragana": "ひま", "katakana": "ヒマ", "kanji": "暇", "meaning": "free time / leisure", "topic": "Daily Life"},
    {"romaji": "himitsu", "hiragana": "ひみつ", "katakana": "ヒミツ", "kanji": "秘密", "meaning": "secret", "topic": "Daily Life"},
    {"romaji": "hiru", "hiragana": "ひる", "katakana": "ヒル", "kanji": "昼", "meaning": "daytime / noon", "topic": "Time & Calendar"},
    {"romaji": "hirugohan", "hiragana": "ひるごはん", "katakana": "ヒルゴハン", "kanji": "昼ご飯", "meaning": "lunch", "topic": "Food & Dining"},
    {"romaji": "hiruma", "hiragana": "ひるま", "katakana": "ヒルマ", "kanji": "昼間", "meaning": "daytime / during the day", "topic": "Time & Calendar"},
    {"romaji": "hiruyasumi", "hiragana": "ひるやすみ", "katakana": "ヒルヤスミ", "kanji": "昼休み", "meaning": "lunch break", "topic": "School & Work"},
    {"romaji": "hisa", "hiragana": "ひざ", "katakana": "ヒザ", "kanji": "膝", "meaning": "knee / lap", "topic": "Body & Health"},
    {"romaji": "hito", "hiragana": "ひと", "katakana": "ヒト", "kanji": "人", "meaning": "person / human", "topic": "People & Family"},
    {"romaji": "hitobito", "hiragana": "ひとびと", "katakana": "ヒトビト", "kanji": "人々", "meaning": "people", "topic": "People & Family"},
    {"romaji": "hitori", "hiragana": "ひとり", "katakana": "ヒトリ", "kanji": "一人", "meaning": "one person / alone", "topic": "People & Family"},
    {"romaji": "hitorigurashi", "hiragana": "ひとりぐらし", "katakana": "ヒトリグラシ", "kanji": "一人暮らし", "meaning": "living alone", "topic": "Daily Life"},
    {"romaji": "hitsuji", "hiragana": "ひつじ", "katakana": "ヒツジ", "kanji": "羊", "meaning": "sheep", "topic": "Nature & Animals"},
    {"romaji": "hiza", "hiragana": "ひじ", "katakana": "ヒジ", "kanji": "肘", "meaning": "elbow", "topic": "Body & Health"},
    {"romaji": "hoken", "hiragana": "ほけん", "katakana": "ホケン", "kanji": "保険", "meaning": "insurance", "topic": "Culture & Society"},
    {"romaji": "hondana", "hiragana": "ほんだな", "katakana": "ホンダナ", "kanji": "本棚", "meaning": "bookshelf", "topic": "Home & Living"},
    {"romaji": "hone", "hiragana": "ほね", "katakana": "ホネ", "kanji": "骨", "meaning": "bone", "topic": "Body & Health"},
    {"romaji": "honmono", "hiragana": "ほんもの", "katakana": "ホンモノ", "kanji": "本物", "meaning": "genuine article / the real thing", "topic": "Tools & Goods"},
    {"romaji": "honya", "hiragana": "ほんや", "katakana": "ホンヤ", "kanji": "本屋", "meaning": "bookstore", "topic": "Shopping & Money"},
    {"romaji": "hoshizora", "hiragana": "ほしぞら", "katakana": "ホシゾラ", "kanji": "星空", "meaning": "starry sky", "topic": "Nature & Weather"},
    {"romaji": "hoteru", "hiragana": "ほてる", "katakana": "ホテル", "kanji": "ホテル", "meaning": "hotel", "topic": "Travel & Places"},
    {"romaji": "hyaku", "hiragana": "ひゃく", "katakana": "ヒャク", "kanji": "百", "meaning": "hundred", "topic": "Shopping & Money"},
    {"romaji": "hyou", "hiragana": "ひょう", "katakana": "ヒョウ", "kanji": "表", "meaning": "table / chart / list", "topic": "School & Work"},
    {"romaji": "hyougen", "hiragana": "ひょうげん", "katakana": "ヒョウゲン", "kanji": "表現", "meaning": "expression", "topic": "School & Work"},

    # I
    {"romaji": "ichigo", "hiragana": "いちご", "katakana": "イチゴ", "kanji": "苺", "meaning": "strawberry", "topic": "Food & Dining"},
    {"romaji": "ichiba", "hiragana": "いちば", "katakana": "イチバ", "kanji": "市場", "meaning": "market / marketplace", "topic": "Shopping & Money"},
    {"romaji": "ichinichi", "hiragana": "いちにち", "katakana": "イチニチ", "kanji": "一日", "meaning": "one day", "topic": "Time & Calendar"},
    {"romaji": "idou", "hiragana": "いどう", "katakana": "イドウ", "kanji": "移動", "meaning": "movement / relocation", "topic": "Travel & Places"},
    {"romaji": "ie", "hiragana": "いえ", "katakana": "イエ", "kanji": "家", "meaning": "house / home", "topic": "Home & Living"},
    {"romaji": "iin", "hiragana": "いいん", "katakana": "イイン", "kanji": "委員", "meaning": "committee member", "topic": "School & Work"},
    {"romaji": "ikioi", "hiragana": "いきおい", "katakana": "イキオイ", "kanji": "勢い", "meaning": "momentum / vigor / force", "topic": "Science & Nature"},
    {"romaji": "ikimono", "hiragana": "いきもの", "katakana": "イキモノ", "kanji": "生き物", "meaning": "living thing / creature", "topic": "Nature & Animals"},
    {"romaji": "ikura", "hiragana": "いくら", "katakana": "イクラ", "kanji": "幾ら", "meaning": "how much (price) / salmon roe", "topic": "Shopping & Money"},
    {"romaji": "ima", "hiragana": "いま", "katakana": "イマ", "kanji": "今", "meaning": "now / present moment", "topic": "Time & Calendar"},
    {"romaji": "inaka", "hiragana": "いなか", "katakana": "イナカ", "kanji": "田舎", "meaning": "countryside / rural hometown", "topic": "Travel & Places"},
    {"romaji": "inori", "hiragana": "いのり", "katakana": "イノリ", "kanji": "祈り", "meaning": "prayer", "topic": "Culture & Society"},
    {"romaji": "inochi", "hiragana": "いのち", "katakana": "イノチ", "kanji": "命", "meaning": "life", "topic": "Body & Health"},
    {"romaji": "insutanto", "hiragana": "いんすたんと", "katakana": "インスタント", "kanji": "インスタント", "meaning": "instant (noodles/coffee)", "topic": "Food & Dining"},
    {"romaji": "intabyuu", "hiragana": "いんたびゅー", "katakana": "インタビュー", "kanji": "インタビュー", "meaning": "interview", "topic": "Hobbies & Media"},
    {"romaji": "intaanetto", "hiragana": "いんたーねっと", "katakana": "インターネット", "kanji": "インターネット", "meaning": "Internet", "topic": "Hobbies & Media"},
    {"romaji": "ippon", "hiragana": "いっぽん", "katakana": "イッポン", "kanji": "一本", "meaning": "one long cylindrical item / full point in martial arts", "topic": "Daily Life"},
    {"romaji": "iriguchi", "hiragana": "いりぐち", "katakana": "イリグチ", "kanji": "入口", "meaning": "entrance", "topic": "Travel & Places"},
    {"romaji": "iro", "hiragana": "いろ", "katakana": "イロ", "kanji": "色", "meaning": "color", "topic": "Clothes & Fashion"},
    {"romaji": "iroenpitsu", "hiragana": "いろえんぴつ", "katakana": "イロエンピツ", "kanji": "色鉛筆", "meaning": "colored pencil", "topic": "School & Work"},
    {"romaji": "iryou", "hiragana": "いりょう", "katakana": "イリョウ", "kanji": "医療", "meaning": "medical care / medicine", "topic": "Body & Health"},
    {"romaji": "ishi", "hiragana": "いし", "katakana": "イシ", "kanji": "石", "meaning": "stone / rock", "topic": "Nature & Weather"},
    {"romaji": "isha", "hiragana": "いしゃ", "katakana": "イシャ", "kanji": "医者", "meaning": "medical doctor", "topic": "People & Family"},
    {"romaji": "isu", "hiragana": "いす", "katakana": "イス", "kanji": "椅子", "meaning": "chair", "topic": "Home & Living"},
    {"romaji": "itoko", "hiragana": "いとこ", "katakana": "イトコ", "kanji": "従兄弟", "meaning": "cousin", "topic": "People & Family"},
    {"romaji": "itsuka", "hiragana": "いつか", "katakana": "イツカ", "kanji": "何時か", "meaning": "someday / fifth day of month", "topic": "Time & Calendar"},

    # J
    {"romaji": "jaketto", "hiragana": "じゃけっと", "katakana": "ジャケット", "kanji": "ジャケット", "meaning": "jacket", "topic": "Clothes & Fashion"},
    {"romaji": "jamu", "hiragana": "じゃむ", "katakana": "ジャム", "kanji": "ジャム", "meaning": "jam / fruit preserves", "topic": "Food & Dining"},
    {"romaji": "janru", "hiragana": "じゃんる", "katakana": "ジャンル", "kanji": "ジャンル", "meaning": "genre / category", "topic": "Hobbies & Media"},
    {"romaji": "jazu", "hiragana": "じゃず", "katakana": "ジャズ", "kanji": "ジャズ", "meaning": "jazz music", "topic": "Hobbies & Media"},
    {"romaji": "jazuya", "hiragana": "じゃずきっさ", "katakana": "ジャズキッサ", "kanji": "ジャズ喫茶", "meaning": "jazz café", "topic": "Food & Dining"},
    {"romaji": "jibun", "hiragana": "じぶん", "katakana": "ジブン", "kanji": "自分", "meaning": "myself / oneself", "topic": "People & Family"},
    {"romaji": "jidai", "hiragana": "じだい", "katakana": "ジダイ", "kanji": "時代", "meaning": "period / era / age", "topic": "Time & Calendar"},
    {"romaji": "jidousha", "hiragana": "じどうしゃ", "katakana": "ジドウシャ", "kanji": "自動車", "meaning": "automobile / car", "topic": "Travel & Places"},
    {"romaji": "jidouhanbaiki", "hiragana": "じどうはんばいき", "katakana": "ジドウハンバイキ", "kanji": "自動販売機", "meaning": "vending machine", "topic": "Shopping & Money"},
    {"romaji": "jikan", "hiragana": "じかん", "katakana": "ジカン", "kanji": "時間", "meaning": "time / hours", "topic": "Time & Calendar"},
    {"romaji": "jiko", "hiragana": "じこ", "katakana": "ジコ", "kanji": "事故", "meaning": "accident / incident", "topic": "Daily Life"},
    {"romaji": "jimusho", "hiragana": "じむしょ", "katakana": "ジムショ", "kanji": "事務所", "meaning": "office", "topic": "School & Work"},
    {"romaji": "jinja", "hiragana": "じんじゃ", "katakana": "ジンジャ", "kanji": "神社", "meaning": "Shinto shrine", "topic": "Culture & Society"},
    {"romaji": "jinkou", "hiragana": "じんこう", "katakana": "ジンコウ", "kanji": "人口", "meaning": "population", "topic": "Culture & Society"},
    {"romaji": "jinsei", "hiragana": "じんせい", "katakana": "ジンセイ", "kanji": "人生", "meaning": "human life", "topic": "Culture & Society"},
    {"romaji": "jinzou", "hiragana": "じんぞう", "katakana": "ジンゾウ", "kanji": "腎臓", "meaning": "kidney", "topic": "Body & Health"},
    {"romaji": "jishin", "hiragana": "じしん", "katakana": "ジシン", "kanji": "地震", "meaning": "earthquake", "topic": "Nature & Weather"},
    {"romaji": "jisho", "hiragana": "じしょ", "katakana": "ジショ", "kanji": "辞書", "meaning": "dictionary", "topic": "School & Work"},
    {"romaji": "jitensha", "hiragana": "じてんしゃ", "katakana": "ジテンシャ", "kanji": "自転車", "meaning": "bicycle", "topic": "Travel & Places"},
    {"romaji": "jouhou", "hiragana": "じょうほう", "katakana": "ジョウホウ", "kanji": "情報", "meaning": "information / data", "topic": "School & Work"},
    {"romaji": "juusu", "hiragana": "じゅーす", "katakana": "ジュース", "kanji": "ジュース", "meaning": "juice / soft drink", "topic": "Food & Dining"},
    {"romaji": "juusho", "hiragana": "じゅうしょ", "katakana": "ジュウショ", "kanji": "住所", "meaning": "address / residence", "topic": "Daily Life"},
    {"romaji": "juudou", "hiragana": "じゅうどう", "katakana": "ジュウドウ", "kanji": "柔道", "meaning": "judo martial art", "topic": "Hobbies & Media"},
    {"romaji": "juutaku", "hiragana": "じゅうたく", "katakana": "ジュウタク", "kanji": "住宅", "meaning": "housing / residence", "topic": "Home & Living"},

    # K
    {"romaji": "kabe", "hiragana": "かべ", "katakana": "カベ", "kanji": "壁", "meaning": "wall", "topic": "Home & Living"},
    {"romaji": "kabin", "hiragana": "かびん", "katakana": "カビン", "kanji": "花瓶", "meaning": "flower vase", "topic": "Home & Living"},
    {"romaji": "kado", "hiragana": "かど", "katakana": "カド", "kanji": "角", "meaning": "corner (street/room)", "topic": "Travel & Places"},
    {"romaji": "kaeri", "hiragana": "かえり", "katakana": "カエリ", "kanji": "帰り", "meaning": "return trip / way home", "topic": "Travel & Places"},
    {"romaji": "kagaku", "hiragana": "かがく", "katakana": "カガク", "kanji": "科学", "meaning": "science", "topic": "School & Work"},
    {"romaji": "kagami", "hiragana": "かがみ", "katakana": "カガミ", "kanji": "鏡", "meaning": "mirror", "topic": "Home & Living"},
    {"romaji": "kagi", "hiragana": "かぎ", "katakana": "カギ", "kanji": "鍵", "meaning": "key / lock", "topic": "Home & Living"},
    {"romaji": "kaidan", "hiragana": "かいだん", "katakana": "カイダン", "kanji": "階段", "meaning": "stairs / staircase", "topic": "Home & Living"},
    {"romaji": "kaigi", "hiragana": "かいぎ", "katakana": "カイギ", "kanji": "会議", "meaning": "meeting / conference", "topic": "School & Work"},
    {"romaji": "kaigishitsu", "hiragana": "かいぎしつ", "katakana": "カイギシツ", "kanji": "会議室", "meaning": "meeting room / conference hall", "topic": "School & Work"},
    {"romaji": "kaigan", "hiragana": "かいがん", "katakana": "カイガン", "kanji": "海岸", "meaning": "coast / seashore", "topic": "Travel & Places"},
    {"romaji": "kaimono", "hiragana": "かいもの", "katakana": "カイモノ", "kanji": "買い物", "meaning": "shopping", "topic": "Shopping & Money"},
    {"romaji": "kaisha", "hiragana": "かいしゃ", "katakana": "カイシャ", "kanji": "会社", "meaning": "company / firm", "topic": "School & Work"},
    {"romaji": "kaishain", "hiragana": "かいしゃいん", "katakana": "カイシャイン", "kanji": "会社員", "meaning": "company employee", "topic": "School & Work"},
    {"romaji": "kaji", "hiragana": "かじ", "katakana": "カジ", "kanji": "火事", "meaning": "fire (disaster)", "topic": "Daily Life"},
    {"romaji": "kamakura", "hiragana": "かまくら", "katakana": "カマクラ", "kanji": "鎌倉", "meaning": "snow hut / Kamakura city", "topic": "Culture & Society"},
    {"romaji": "kami", "hiragana": "かみ", "katakana": "カミ", "kanji": "紙", "meaning": "paper / hair / god", "topic": "Tools & Goods"},
    {"romaji": "kaminari", "hiragana": "かみなり", "katakana": "カミナリ", "kanji": "雷", "meaning": "thunder / lightning", "topic": "Nature & Weather"},
    {"romaji": "kanashimi", "hiragana": "かなしみ", "katakana": "カナシミ", "kanji": "悲しみ", "meaning": "sadness / sorrow", "topic": "Emotions & Mind"},
    {"romaji": "kanji", "hiragana": "かんじ", "katakana": "カンジ", "kanji": "漢字", "meaning": "Chinese characters", "topic": "School & Work"},
    {"romaji": "kankou", "hiragana": "かんこう", "katakana": "カンコウ", "kanji": "観光", "meaning": "sightseeing / tourism", "topic": "Travel & Places"},
    {"romaji": "kankokujin", "hiragana": "かんこくじん", "katakana": "カンコクジン", "kanji": "韓国人", "meaning": "Korean person", "topic": "People & Family"},
    {"romaji": "kanrinin", "hiragana": "かんりにん", "katakana": "カンリニン", "kanji": "管理人", "meaning": "caretaker / building manager", "topic": "School & Work"},
    {"romaji": "kaori", "hiragana": "かおり", "katakana": "カオリ", "kanji": "香り", "meaning": "scent / aroma / fragrance", "topic": "Daily Life"},
    {"romaji": "karaoke", "hiragana": "からおけ", "katakana": "カラオケ", "kanji": "カラオケ", "meaning": "karaoke singing", "topic": "Hobbies & Media"},
    {"romaji": "karada", "hiragana": "からだ", "katakana": "カラダ", "kanji": "体", "meaning": "body / physical health", "topic": "Body & Health"},
    {"romaji": "karashi", "hiragana": "からし", "katakana": "カラシ", "kanji": "芥子", "meaning": "Japanese spicy mustard", "topic": "Food & Dining"},
    {"romaji": "kasa", "hiragana": "かさ", "katakana": "カサ", "kanji": "傘", "meaning": "umbrella", "topic": "Tools & Goods"},
    {"romaji": "kawa", "hiragana": "かわ", "katakana": "カワ", "kanji": "川", "meaning": "river", "topic": "Nature & Weather"},
    {"romaji": "kawara", "hiragana": "かわら", "katakana": "カワラ", "kanji": "河原", "meaning": "dry riverbed", "topic": "Nature & Weather"},
    {"romaji": "kayoubi", "hiragana": "かようび", "katakana": "カヨウビ", "kanji": "火曜日", "meaning": "Tuesday", "topic": "Time & Calendar"},
    {"romaji": "kazari", "hiragana": "かざり", "katakana": "カザリ", "kanji": "飾り", "meaning": "decoration / ornament", "topic": "Home & Living"},
    {"romaji": "kazoku", "hiragana": "かぞく", "katakana": "カゾク", "kanji": "家族", "meaning": "family", "topic": "People & Family"},
    {"romaji": "keizai", "hiragana": "けいざい", "katakana": "ケイザイ", "kanji": "経済", "meaning": "economy / economics", "topic": "Culture & Society"},
    {"romaji": "kiken", "hiragana": "きけん", "katakana": "キケン", "kanji": "危険", "meaning": "danger / peril", "topic": "Daily Life"},
    {"romaji": "kimono", "hiragana": "きもの", "katakana": "キモノ", "kanji": "着物", "meaning": "kimono", "topic": "Clothes & Fashion"},
    {"romaji": "kitte", "hiragana": "きって", "katakana": "キッテ", "kanji": "切手", "meaning": "postage stamp", "topic": "Daily Life"},
    {"romaji": "kissa", "hiragana": "きっさてん", "katakana": "キッサテン", "kanji": "喫茶店", "meaning": "coffee shop / cafe", "topic": "Food & Dining"},
    {"romaji": "kittegire", "hiragana": "きっぷ", "katakana": "キップ", "kanji": "切符", "meaning": "ticket (train / bus)", "topic": "Travel & Places"},
    {"romaji": "kouban", "hiragana": "こうばん", "katakana": "コウバン", "kanji": "交番", "meaning": "police box", "topic": "Culture & Society"},
    {"romaji": "kouen", "hiragana": "こうえん", "katakana": "コウエン", "kanji": "公園", "meaning": "public park", "topic": "Travel & Places"},
    {"romaji": "kousaten", "hiragana": "こうさてん", "katakana": "コウサテン", "kanji": "交差点", "meaning": "intersection / crossroads", "topic": "Travel & Places"},
    {"romaji": "kudamono", "hiragana": "くだもの", "katakana": "クダモノ", "kanji": "果物", "meaning": "fruit", "topic": "Food & Dining"},
    {"romaji": "kusuri", "hiragana": "くすり", "katakana": "クスリ", "kanji": "薬", "meaning": "medicine / pharmaceuticals", "topic": "Body & Health"},
    {"romaji": "kutsu", "hiragana": "くつ", "katakana": "クツ", "kanji": "靴", "meaning": "shoes", "topic": "Clothes & Fashion"},
    {"romaji": "kutsushita", "hiragana": "くつした", "katakana": "クツシタ", "kanji": "靴下", "meaning": "socks", "topic": "Clothes & Fashion"},
    {"romaji": "kyuukousha", "hiragana": "きゅうこう", "katakana": "キュウコウ", "kanji": "急行", "meaning": "express train", "topic": "Travel & Places"},

    # M
    {"romaji": "machi", "hiragana": "まち", "katakana": "マチ", "kanji": "町", "meaning": "town / city street", "topic": "Travel & Places"},
    {"romaji": "mado", "hiragana": "まど", "katakana": "マド", "kanji": "窓", "meaning": "window", "topic": "Home & Living"},
    {"romaji": "maguro", "hiragana": "まぐろ", "katakana": "マグロ", "kanji": "鮪", "meaning": "tuna fish", "topic": "Food & Dining"},
    {"romaji": "maiban", "hiragana": "まいばん", "katakana": "マイバン", "kanji": "毎晩", "meaning": "every night", "topic": "Time & Calendar"},
    {"romaji": "mainichi", "hiragana": "まいにち", "katakana": "マイニチ", "kanji": "毎日", "meaning": "every day", "topic": "Time & Calendar"},
    {"romaji": "maiasa", "hiragana": "まいあさ", "katakana": "マイアサ", "kanji": "毎朝", "meaning": "every morning", "topic": "Time & Calendar"},
    {"romaji": "maishuu", "hiragana": "まいしゅう", "katakana": "マイシュウ", "kanji": "毎週", "meaning": "every week", "topic": "Time & Calendar"},
    {"romaji": "maitsuki", "hiragana": "まいつき", "katakana": "マイツキ", "kanji": "毎月", "meaning": "every month", "topic": "Time & Calendar"},
    {"romaji": "maitoshi", "hiragana": "まいとし", "katakana": "マイトシ", "kanji": "毎年", "meaning": "every year", "topic": "Time & Calendar"},
    {"romaji": "makkura", "hiragana": "まっくら", "katakana": "マックラ", "kanji": "真っ暗", "meaning": "pitch dark", "topic": "Nature & Weather"},
    {"romaji": "manga", "hiragana": "まんが", "katakana": "マンガ", "kanji": "漫画", "meaning": "manga / comic book", "topic": "Hobbies & Media"},
    {"romaji": "manshon", "hiragana": "まんしょん", "katakana": "マンション", "kanji": "マンション", "meaning": "apartment / condominium", "topic": "Home & Living"},
    {"romaji": "matchi", "hiragana": "まっち", "katakana": "マッチ", "kanji": "マッチ", "meaning": "match (fire)", "topic": "Tools & Goods"},
    {"romaji": "matsuri", "hiragana": "まつり", "katakana": "マツリ", "kanji": "祭り", "meaning": "festival / celebration", "topic": "Culture & Society"},
    {"romaji": "mayonaka", "hiragana": "まよなか", "katakana": "マヨナカ", "kanji": "真夜中", "meaning": "midnight / dead of night", "topic": "Time & Calendar"},
    {"romaji": "me", "hiragana": "め", "katakana": "メ", "kanji": "目", "meaning": "eye", "topic": "Body & Health"},
    {"romaji": "megane", "hiragana": "めがね", "katakana": "メガネ", "kanji": "眼鏡", "meaning": "glasses / eyeglasses", "topic": "Tools & Goods"},
    {"romaji": "meishi", "hiragana": "めいし", "katakana": "メイシ", "kanji": "名刺", "meaning": "business card", "topic": "School & Work"},
    {"romaji": "menkyo", "hiragana": "めんきょ", "katakana": "メンキョ", "kanji": "免許", "meaning": "license / permit", "topic": "Daily Life"},
    {"romaji": "midori", "hiragana": "みどり", "katakana": "ミドリ", "kanji": "緑", "meaning": "green color / greenery", "topic": "Nature & Animals"},
    {"romaji": "mikan", "hiragana": "みかん", "katakana": "ミカン", "kanji": "蜜柑", "meaning": "mandarin orange / satsuma", "topic": "Food & Dining"},
    {"romaji": "michi", "hiragana": "みち", "katakana": "ミチ", "kanji": "道", "meaning": "street / road / path", "topic": "Travel & Places"},
    {"romaji": "mimi", "hiragana": "みみ", "katakana": "ミミ", "kanji": "耳", "meaning": "ear", "topic": "Body & Health"},
    {"romaji": "minami", "hiragana": "みなみ", "katakana": "ミナミ", "kanji": "南", "meaning": "south", "topic": "Travel & Places"},
    {"romaji": "minato", "hiragana": "みなと", "katakana": "ミナト", "kanji": "港", "meaning": "harbor / port", "topic": "Travel & Places"},
    {"romaji": "misoshiru", "hiragana": "みそしる", "katakana": "ミソシル", "kanji": "味噌汁", "meaning": "miso soup", "topic": "Food & Dining"},
    {"romaji": "mizu", "hiragana": "みず", "katakana": "ミズ", "kanji": "水", "meaning": "water", "topic": "Food & Dining"},
    {"romaji": "mizugi", "hiragana": "みずぎ", "katakana": "ミズギ", "kanji": "水着", "meaning": "swimsuit", "topic": "Clothes & Fashion"},
    {"romaji": "mizuumi", "hiragana": "みずうみ", "katakana": "ミズウミ", "kanji": "湖", "meaning": "lake", "topic": "Nature & Weather"},
    {"romaji": "mokuyoubi", "hiragana": "もくようび", "katakana": "モクヨウビ", "kanji": "木曜日", "meaning": "Thursday", "topic": "Time & Calendar"},
    {"romaji": "mon", "hiragana": "もん", "katakana": "モン", "kanji": "門", "meaning": "gate", "topic": "Home & Living"},
    {"romaji": "mondai", "hiragana": "もんだい", "katakana": "モンダイ", "kanji": "問題", "meaning": "problem / question / issue", "topic": "School & Work"},
    {"romaji": "mori", "hiragana": "もり", "katakana": "モリ", "kanji": "森", "meaning": "forest", "topic": "Nature & Animals"},

    # N
    {"romaji": "nabe", "hiragana": "なべ", "katakana": "ナベ", "kanji": "鍋", "meaning": "pot / pan / hot pot dish", "topic": "Food & Dining"},
    {"romaji": "nagasa", "hiragana": "ながさ", "katakana": "ナガサ", "kanji": "長さ", "meaning": "length", "topic": "Science & Nature"},
    {"romaji": "natsu", "hiragana": "なつ", "katakana": "ナツ", "kanji": "夏", "meaning": "summer", "topic": "Nature & Weather"},
    {"romaji": "natsuyasumi", "hiragana": "なつやすみ", "katakana": "ナツヤスミ", "kanji": "夏休み", "meaning": "summer vacation", "topic": "Time & Calendar"},
    {"romaji": "nawa", "hiragana": "なわ", "katakana": "ナワ", "kanji": "縄", "meaning": "rope / cord", "topic": "Tools & Goods"},
    {"romaji": "neko", "hiragana": "ねこ", "katakana": "ネコ", "kanji": "猫", "meaning": "cat", "topic": "Nature & Animals"},
    {"romaji": "nekutai", "hiragana": "ねくたい", "katakana": "ネクタイ", "kanji": "ネクタイ", "meaning": "necktie", "topic": "Clothes & Fashion"},
    {"romaji": "netsu", "hiragana": "ねつ", "katakana": "ネツ", "kanji": "熱", "meaning": "fever / heat", "topic": "Body & Health"},
    {"romaji": "nichiyoubi", "hiragana": "にちようび", "katakana": "ニチヨウビ", "kanji": "日曜日", "meaning": "Sunday", "topic": "Time & Calendar"},
    {"romaji": "nihon", "hiragana": "にほん", "katakana": "ニホン", "kanji": "日本", "meaning": "Japan", "topic": "Travel & Places"},
    {"romaji": "nihonjin", "hiragana": "にほんじん", "katakana": "ニホンジン", "kanji": "日本人", "meaning": "Japanese person", "topic": "People & Family"},
    {"romaji": "nihongo", "hiragana": "にほんご", "katakana": "ニホンゴ", "kanji": "日本語", "meaning": "Japanese language", "topic": "School & Work"},
    {"romaji": "nikki", "hiragana": "にっき", "katakana": "ニッキ", "kanji": "日記", "meaning": "diary / journal", "topic": "Daily Life"},
    {"romaji": "niku", "hiragana": "にく", "katakana": "ニク", "kanji": "肉", "meaning": "meat", "topic": "Food & Dining"},
    {"romaji": "nimotsu", "hiragana": "にもつ", "katakana": "ニモツ", "kanji": "荷物", "meaning": "luggage / baggage / package", "topic": "Travel & Places"},
    {"romaji": "ninja", "hiragana": "にんじゃ", "katakana": "ニンジャ", "kanji": "忍者", "meaning": "ninja", "topic": "Culture & Society"},
    {"romaji": "ninjin", "hiragana": "にんじん", "katakana": "ニンジン", "kanji": "人参", "meaning": "carrot", "topic": "Food & Dining"},
    {"romaji": "niwa", "hiragana": "にわ", "katakana": "ニワ", "kanji": "庭", "meaning": "garden / yard", "topic": "Home & Living"},
    {"romaji": "nodo", "hiragana": "のど", "katakana": "ノド", "kanji": "喉", "meaning": "throat", "topic": "Body & Health"},
    {"romaji": "nomimono", "hiragana": "のみもの", "katakana": "ノミモノ", "kanji": "飲み物", "meaning": "drink / beverage", "topic": "Food & Dining"},
    {"romaji": "nooto", "hiragana": "のーと", "katakana": "ノート", "kanji": "ノート", "meaning": "notebook", "topic": "School & Work"},
    {"romaji": "nori", "hiragana": "のり", "katakana": "ノリ", "kanji": "海苔", "meaning": "dried seaweed / glue", "topic": "Food & Dining"},

    # O
    {"romaji": "oba", "hiragana": "おば", "katakana": "オバ", "kanji": "伯母", "meaning": "aunt (one's own)", "topic": "People & Family"},
    {"romaji": "obasan", "hiragana": "おばさん", "katakana": "オバサン", "kanji": "叔母さん", "meaning": "aunt / middle-aged lady", "topic": "People & Family"},
    {"romaji": "obaasan", "hiragana": "おばあさん", "katakana": "オバアサン", "kanji": "お祖母さん", "meaning": "grandmother / elderly woman", "topic": "People & Family"},
    {"romaji": "obentou", "hiragana": "おべんとう", "katakana": "オベントウ", "kanji": "お弁当", "meaning": "boxed lunch / bento", "topic": "Food & Dining"},
    {"romaji": "ocha", "hiragana": "おちゃ", "katakana": "オチャ", "kanji": "お茶", "meaning": "Japanese green tea", "topic": "Food & Dining"},
    {"romaji": "odori", "hiragana": "おどり", "katakana": "オドリ", "kanji": "踊り", "meaning": "dance", "topic": "Culture & Society"},
    {"romaji": "ofuro", "hiragana": "おふろ", "katakana": "オフロ", "kanji": "お風呂", "meaning": "bath", "topic": "Home & Living"},
    {"romaji": "oji", "hiragana": "おじ", "katakana": "オジ", "kanji": "伯父", "meaning": "uncle (one's own)", "topic": "People & Family"},
    {"romaji": "ojisan", "hiragana": "おじさん", "katakana": "オジサン", "kanji": "叔父さん", "meaning": "uncle / middle-aged man", "topic": "People & Family"},
    {"romaji": "ojiisan", "hiragana": "おじいさん", "katakana": "オジイサン", "kanji": "お祖父さん", "meaning": "grandfather / elderly man", "topic": "People & Family"},
    {"romaji": "oka", "hiragana": "おか", "katakana": "オカ", "kanji": "丘", "meaning": "hill", "topic": "Nature & Weather"},
    {"romaji": "okane", "hiragana": "おかね", "katakana": "オカネ", "kanji": "お金", "meaning": "money", "topic": "Shopping & Money"},
    {"romaji": "okashi", "hiragana": "おかし", "katakana": "オカシ", "kanji": "お菓子", "meaning": "sweets / confectionery / snacks", "topic": "Food & Dining"},
    {"romaji": "okusan", "hiragana": "おくさん", "katakana": "オクサン", "kanji": "奥さん", "meaning": "someone's wife", "topic": "People & Family"},
    {"romaji": "omatsuri", "hiragana": "おまつり", "katakana": "オマツリ", "kanji": "お祭り", "meaning": "festival", "topic": "Culture & Society"},
    {"romaji": "omiyage", "hiragana": "おみやげ", "katakana": "オミヤゲ", "kanji": "お土産", "meaning": "souvenir / gift", "topic": "Travel & Places"},
    {"romaji": "omoccha", "hiragana": "おもちゃ", "katakana": "オモチャ", "kanji": "玩具", "meaning": "toy", "topic": "Daily Life"},
    {"romaji": "onaka", "hiragana": "おなか", "katakana": "オナカ", "kanji": "お腹", "meaning": "stomach / belly", "topic": "Body & Health"},
    {"romaji": "ongaku", "hiragana": "おんがく", "katakana": "オンガク", "kanji": "音楽", "meaning": "music", "topic": "Hobbies & Media"},
    {"romaji": "onigiri", "hiragana": "おにぎり", "katakana": "オニギリ", "kanji": "お握り", "meaning": "rice ball", "topic": "Food & Dining"},
    {"romaji": "onsen", "hiragana": "おんせん", "katakana": "オンセン", "kanji": "温泉", "meaning": "hot spring", "topic": "Travel & Places"},
    {"romaji": "origami", "hiragana": "おりがみ", "katakana": "オリガミ", "kanji": "折り紙", "meaning": "paper folding art", "topic": "Culture & Society"},
    {"romaji": "oshiire", "hiragana": "おしいれ", "katakana": "オシイレ", "kanji": "押し入れ", "meaning": "Japanese closet (for futons)", "topic": "Home & Living"},
    {"romaji": "otoko", "hiragana": "おとこ", "katakana": "オトコ", "kanji": "男", "meaning": "man / male", "topic": "People & Family"},
    {"romaji": "otokonoko", "hiragana": "おとこのこ", "katakana": "オトコノコ", "kanji": "男の子", "meaning": "boy", "topic": "People & Family"},
    {"romaji": "otouto", "hiragana": "おとうと", "katakana": "オトウト", "kanji": "弟", "meaning": "younger brother", "topic": "People & Family"},
    {"romaji": "oto", "hiragana": "おと", "katakana": "オト", "kanji": "音", "meaning": "sound / noise", "topic": "Daily Life"},
    {"romaji": "otona", "hiragana": "おとな", "katakana": "オトナ", "kanji": "大人", "meaning": "adult", "topic": "People & Family"},
    {"romaji": "oyasumi", "hiragana": "おやすみ", "katakana": "オヤスミ", "kanji": "お休み", "meaning": "rest / vacation / good night", "topic": "Daily Life"},
    {"romaji": "oyu", "hiragana": "おゆ", "katakana": "オユ", "kanji": "お湯", "meaning": "hot water", "topic": "Daily Life"},

    # P
    {"romaji": "pan", "hiragana": "ぱん", "katakana": "パン", "kanji": "パン", "meaning": "bread", "topic": "Food & Dining"},
    {"romaji": "panya", "hiragana": "ぱんや", "katakana": "パンヤ", "kanji": "パン屋", "meaning": "bakery", "topic": "Shopping & Money"},
    {"romaji": "pasokon", "hiragana": "ぱそこん", "katakana": "パソコン", "kanji": "パソコン", "meaning": "personal computer", "topic": "Tools & Goods"},
    {"romaji": "pasupooto", "hiragana": "ぱすぽーと", "katakana": "パスポート", "kanji": "パスポート", "meaning": "passport", "topic": "Travel & Places"},
    {"romaji": "paatii", "hiragana": "ぱーてぃー", "katakana": "パーティー", "kanji": "パーティー", "meaning": "party", "topic": "Daily Life"},
    {"romaji": "pen", "hiragana": "ぺん", "katakana": "ペン", "kanji": "ペン", "meaning": "pen", "topic": "School & Work"},
    {"romaji": "petto", "hiragana": "ぺっと", "katakana": "ペット", "kanji": "ペット", "meaning": "pet", "topic": "Nature & Animals"},
    {"romaji": "piano", "hiragana": "ぴあの", "katakana": "ピアノ", "kanji": "ピアノ", "meaning": "piano", "topic": "Hobbies & Media"},
    {"romaji": "piza", "hiragana": "ぴざ", "katakana": "ピザ", "kanji": "ピザ", "meaning": "pizza", "topic": "Food & Dining"},
    {"romaji": "poketto", "hiragana": "ぽけっと", "katakana": "ポケット", "kanji": "ポケット", "meaning": "pocket", "topic": "Clothes & Fashion"},
    {"romaji": "posuto", "hiragana": "ぽすと", "katakana": "ポスト", "kanji": "ポスト", "meaning": "mailbox / postbox", "topic": "Daily Life"},
    {"romaji": "puresento", "hiragana": "ぷれぜんと", "katakana": "プレゼント", "kanji": "プレゼント", "meaning": "present / gift", "topic": "Shopping & Money"},
    {"romaji": "purintaa", "hiragana": "ぷりんたー", "katakana": "プリンター", "kanji": "プリンター", "meaning": "printer", "topic": "Tools & Goods"},
    {"romaji": "puuru", "hiragana": "ぷーる", "katakana": "プール", "kanji": "プール", "meaning": "swimming pool", "topic": "Hobbies & Media"},

    # R
    {"romaji": "raamen", "hiragana": "らーめん", "katakana": "ラーメン", "kanji": "ラーメン", "meaning": "ramen noodle soup", "topic": "Food & Dining"},
    {"romaji": "rajio", "hiragana": "らじお", "katakana": "ラジオ", "kanji": "ラジオ", "meaning": "radio", "topic": "Hobbies & Media"},
    {"romaji": "raigetsu", "hiragana": "らいげつ", "katakana": "ライゲツ", "kanji": "来月", "meaning": "next month", "topic": "Time & Calendar"},
    {"romaji": "rainen", "hiragana": "らいねん", "katakana": "ライネン", "kanji": "来年", "meaning": "next year", "topic": "Time & Calendar"},
    {"romaji": "raishuu", "hiragana": "らいしゅう", "katakana": "ライシュウ", "kanji": "来週", "meaning": "next week", "topic": "Time & Calendar"},
    {"romaji": "rakuda", "hiragana": "らくだ", "katakana": "ラクダ", "kanji": "駱駝", "meaning": "camel", "topic": "Nature & Animals"},
    {"romaji": "reizouko", "hiragana": "れいぞうこ", "katakana": "レイゾウコ", "kanji": "冷蔵庫", "meaning": "refrigerator / fridge", "topic": "Home & Living"},
    {"romaji": "rekisi", "hiragana": "れきし", "katakana": "レキシ", "kanji": "歴史", "meaning": "history", "topic": "School & Work"},
    {"romaji": "renshuu", "hiragana": "れんしゅう", "katakana": "レンシュウ", "kanji": "練習", "meaning": "practice / training", "topic": "School & Work"},
    {"romaji": "resutoran", "hiragana": "れすとらん", "katakana": "レストラン", "kanji": "レストラン", "meaning": "restaurant", "topic": "Food & Dining"},
    {"romaji": "ringo", "hiragana": "りんご", "katakana": "リンゴ", "kanji": "林檎", "meaning": "apple", "topic": "Food & Dining"},
    {"romaji": "rokugatsu", "hiragana": "ろくがつ", "katakana": "ロクガツ", "kanji": "六月", "meaning": "June", "topic": "Time & Calendar"},
    {"romaji": "rouka", "hiragana": "ろうか", "katakana": "ロウカ", "kanji": "廊下", "meaning": "hallway / corridor", "topic": "Home & Living"},
    {"romaji": "ryokan", "hiragana": "りょかん", "katakana": "リョカン", "kanji": "旅館", "meaning": "traditional Japanese inn", "topic": "Travel & Places"},
    {"romaji": "ryokou", "hiragana": "りょこう", "katakana": "リョコウ", "kanji": "旅行", "meaning": "travel / trip", "topic": "Travel & Places"},
    {"romaji": "ryouri", "hiragana": "りょうり", "katakana": "リョウリ", "kanji": "料理", "meaning": "cooking / cuisine", "topic": "Food & Dining"},
    {"romaji": "ryoushin", "hiragana": "りょうしん", "katakana": "リョウシン", "kanji": "両親", "meaning": "both parents", "topic": "People & Family"},
    {"romaji": "ryuugakusei", "hiragana": "りゅうがくせい", "katakana": "リュウガクセイ", "kanji": "留学生", "meaning": "international student", "topic": "School & Work"},

    # S
    {"romaji": "saifu", "hiragana": "さいふ", "katakana": "サイフ", "kanji": "財布", "meaning": "wallet / purse", "topic": "Shopping & Money"},
    {"romaji": "sakana", "hiragana": "さかな", "katakana": "サカナ", "kanji": "魚", "meaning": "fish", "topic": "Food & Dining"},
    {"romaji": "sakura", "hiragana": "さくら", "katakana": "サクラ", "kanji": "桜", "meaning": "cherry blossom", "topic": "Nature & Animals"},
    {"romaji": "sakubun", "hiragana": "さくぶん", "katakana": "サクブン", "kanji": "作文", "meaning": "essay / composition", "topic": "School & Work"},
    {"romaji": "sanpo", "hiragana": "さんぽ", "katakana": "サンポ", "kanji": "散歩", "meaning": "walk / stroll", "topic": "Daily Life"},
    {"romaji": "sashimi", "hiragana": "さしみ", "katakana": "サシミ", "kanji": "刺身", "meaning": "sliced raw fish / sashimi", "topic": "Food & Dining"},
    {"romaji": "satou", "hiragana": "さとう", "katakana": "サトウ", "kanji": "砂糖", "meaning": "sugar", "topic": "Food & Dining"},
    {"romaji": "seikatsu", "hiragana": "せいかつ", "katakana": "セイカツ", "kanji": "生活", "meaning": "life / livelihood", "topic": "Daily Life"},
    {"romaji": "seito", "hiragana": "せいと", "katakana": "セイト", "kanji": "生徒", "meaning": "pupil / student", "topic": "School & Work"},
    {"romaji": "sekken", "hiragana": "せっけん", "katakana": "セッケン", "kanji": "石鹸", "meaning": "soap", "topic": "Daily Life"},
    {"romaji": "sengetsu", "hiragana": "せんげつ", "katakana": "センゲツ", "kanji": "先月", "meaning": "last month", "topic": "Time & Calendar"},
    {"romaji": "sensei", "hiragana": "せんせい", "katakana": "センセイ", "kanji": "先生", "meaning": "teacher / professor", "topic": "School & Work"},
    {"romaji": "senshuu", "hiragana": "せんしゅう", "katakana": "センシュウ", "kanji": "先週", "meaning": "last week", "topic": "Time & Calendar"},
    {"romaji": "shashin", "hiragana": "しゃしん", "katakana": "シャシン", "kanji": "写真", "meaning": "photograph", "topic": "Hobbies & Media"},
    {"romaji": "shawaa", "hiragana": "しゃわー", "katakana": "シャワー", "kanji": "シャワー", "meaning": "shower", "topic": "Daily Life"},
    {"romaji": "shatsu", "hiragana": "しゃつ", "katakana": "シャツ", "kanji": "シャツ", "meaning": "shirt", "topic": "Clothes & Fashion"},
    {"romaji": "shigoto", "hiragana": "しごと", "katakana": "シゴト", "kanji": "仕事", "meaning": "work / job", "topic": "School & Work"},
    {"romaji": "shiken", "hiragana": "しけん", "katakana": "シケン", "kanji": "試験", "meaning": "exam / test", "topic": "School & Work"},
    {"romaji": "shinkansen", "hiragana": "しんかんせん", "katakana": "シンカンセン", "kanji": "新幹線", "meaning": "bullet train", "topic": "Travel & Places"},
    {"romaji": "shinbun", "hiragana": "しんぶん", "katakana": "シンブン", "kanji": "新聞", "meaning": "newspaper", "topic": "Hobbies & Media"},
    {"romaji": "shio", "hiragana": "しお", "katakana": "シオ", "kanji": "塩", "meaning": "salt", "topic": "Food & Dining"},
    {"romaji": "shokuji", "hiragana": "しょくじ", "katakana": "ショクジ", "kanji": "食事", "meaning": "meal / dining", "topic": "Food & Dining"},
    {"romaji": "shokudou", "hiragana": "しょくどう", "katakana": "ショクドウ", "kanji": "食堂", "meaning": "cafeteria / dining hall", "topic": "Food & Dining"},
    {"romaji": "shukudai", "hiragana": "しゅくだい", "katakana": "シュクダイ", "kanji": "宿題", "meaning": "homework", "topic": "School & Work"},
    {"romaji": "shumi", "hiragana": "しゅみ", "katakana": "シュミ", "kanji": "趣味", "meaning": "hobby / pastime", "topic": "Hobbies & Media"},
    {"romaji": "sofa", "hiragana": "そふぁ", "katakana": "ソファ", "kanji": "ソファ", "meaning": "sofa / couch", "topic": "Home & Living"},
    {"romaji": "sora", "hiragana": "そら", "katakana": "ソラ", "kanji": "空", "meaning": "sky", "topic": "Nature & Weather"},
    {"romaji": "sukii", "hiragana": "すきー", "katakana": "スキー", "kanji": "スキー", "meaning": "skiing", "topic": "Hobbies & Media"},
    {"romaji": "sukaato", "hiragana": "すかーと", "katakana": "スカート", "kanji": "スカート", "meaning": "skirt", "topic": "Clothes & Fashion"},
    {"romaji": "supuun", "hiragana": "すぷーん", "katakana": "スプーン", "kanji": "スプーン", "meaning": "spoon", "topic": "Food & Dining"},
    {"romaji": "supootsu", "hiragana": "すぽーつ", "katakana": "スポーツ", "kanji": "スポーツ", "meaning": "sports", "topic": "Hobbies & Media"},
    {"romaji": "sushi", "hiragana": "すし", "katakana": "スシ", "kanji": "寿司", "meaning": "sushi", "topic": "Food & Dining"},
    {"romaji": "suzu", "hiragana": "すず", "katakana": "スズ", "kanji": "鈴", "meaning": "small bell / chime", "topic": "Culture & Society"},

    # T
    {"romaji": "tabemono", "hiragana": "たべもの", "katakana": "タベモノ", "kanji": "食べ物", "meaning": "food", "topic": "Food & Dining"},
    {"romaji": "taishikan", "hiragana": "たいしかん", "katakana": "タイシカン", "kanji": "大使館", "meaning": "embassy", "topic": "Travel & Places"},
    {"romaji": "taiiku", "hiragana": "たいいく", "katakana": "タイイク", "kanji": "体育", "meaning": "physical education / gym", "topic": "School & Work"},
    {"romaji": "taionkei", "hiragana": "たいおんけい", "katakana": "タイオンケイ", "kanji": "体温計", "meaning": "clinical thermometer", "topic": "Body & Health"},
    {"romaji": "taira", "hiragana": "たいら", "katakana": "タイラ", "kanji": "平ら", "meaning": "flat surface", "topic": "Science & Nature"},
    {"romaji": "taoru", "hiragana": "たおる", "katakana": "タオル", "kanji": "タオル", "meaning": "towel", "topic": "Daily Life"},
    {"romaji": "tatami", "hiragana": "たたみ", "katakana": "タタミ", "kanji": "畳", "meaning": "tatami straw mat", "topic": "Home & Living"},
    {"romaji": "tegami", "hiragana": "てがみ", "katakana": "テガミ", "kanji": "手紙", "meaning": "letter (correspondence)", "topic": "Daily Life"},
    {"romaji": "tenki", "hiragana": "てんき", "katakana": "テンキ", "kanji": "天気", "meaning": "weather", "topic": "Nature & Weather"},
    {"romaji": "tenpura", "hiragana": "てんぷら", "katakana": "テンプラ", "kanji": "天ぷら", "meaning": "tempura (deep-fried fritters)", "topic": "Food & Dining"},
    {"romaji": "teeburu", "hiragana": "てーぶる", "katakana": "テーブル", "kanji": "テーブル", "meaning": "table", "topic": "Home & Living"},
    {"romaji": "terebi", "hiragana": "てれび", "katakana": "テレビ", "kanji": "テレビ", "meaning": "television / TV", "topic": "Home & Living"},
    {"romaji": "tokei", "hiragana": "とけい", "katakana": "トケイ", "kanji": "時計", "meaning": "clock / watch", "topic": "Daily Life"},
    {"romaji": "tomodachi", "hiragana": "ともだち", "katakana": "トモダチ", "kanji": "友達", "meaning": "friend", "topic": "People & Family"},
    {"romaji": "tonari", "hiragana": "となり", "katakana": "トナリ", "kanji": "隣", "meaning": "next door / neighbor", "topic": "People & Family"},
    {"romaji": "tori", "hiragana": "とり", "katakana": "トリ", "kanji": "鳥", "meaning": "bird", "topic": "Nature & Animals"},
    {"romaji": "toriniku", "hiragana": "とりにく", "katakana": "トリニク", "kanji": "鶏肉", "meaning": "chicken meat", "topic": "Food & Dining"},
    {"romaji": "toshokan", "hiragana": "としょかん", "katakana": "トショカン", "kanji": "図書館", "meaning": "library", "topic": "School & Work"},
    {"romaji": "tsukue", "hiragana": "つくえ", "katakana": "ツクエ", "kanji": "机", "meaning": "desk", "topic": "School & Work"},

    # U
    {"romaji": "uchi", "hiragana": "うち", "katakana": "ウチ", "kanji": "家", "meaning": "home / household", "topic": "Home & Living"},
    {"romaji": "ude", "hiragana": "うで", "katakana": "ウデ", "kanji": "腕", "meaning": "arm / skill", "topic": "Body & Health"},
    {"romaji": "udon", "hiragana": "うどん", "katakana": "ウドン", "kanji": "うどん", "meaning": "thick wheat noodles", "topic": "Food & Dining"},
    {"romaji": "ue", "hiragana": "うえ", "katakana": "ウエ", "kanji": "上", "meaning": "top / above / on", "topic": "Daily Life"},
    {"romaji": "uma", "hiragana": "うま", "katakana": "ウマ", "kanji": "馬", "meaning": "horse", "topic": "Nature & Animals"},
    {"romaji": "umi", "hiragana": "うみ", "katakana": "ウミ", "kanji": "海", "meaning": "sea / ocean", "topic": "Nature & Weather"},
    {"romaji": "unagi", "hiragana": "うなぎ", "katakana": "ウナギ", "kanji": "鰻", "meaning": "eel", "topic": "Food & Dining"},
    {"romaji": "undou", "hiragana": "うんどう", "katakana": "ウンドウ", "kanji": "運動", "meaning": "exercise / physical workout", "topic": "Body & Health"},
    {"romaji": "undoukai", "hiragana": "うんどうかい", "katakana": "ウンドウカイ", "kanji": "運動会", "meaning": "sports day festival", "topic": "School & Work"},
    {"romaji": "usagi", "hiragana": "うさぎ", "katakana": "ウサギ", "kanji": "兎", "meaning": "rabbit / hare", "topic": "Nature & Animals"},
    {"romaji": "ushi", "hiragana": "うし", "katakana": "ウシ", "kanji": "牛", "meaning": "cow / cattle", "topic": "Nature & Animals"},
    {"romaji": "ushiro", "hiragana": "うしろ", "katakana": "ウシロ", "kanji": "後ろ", "meaning": "back / behind", "topic": "Daily Life"},
    {"romaji": "uta", "hiragana": "うた", "katakana": "ウタ", "kanji": "歌", "meaning": "song", "topic": "Hobbies & Media"},

    # W
    {"romaji": "waishatsu", "hiragana": "わいしゃつ", "katakana": "ワイシャツ", "kanji": "ワイシャツ", "meaning": "business dress shirt", "topic": "Clothes & Fashion"},
    {"romaji": "wanpiisu", "hiragana": "わんぴーす", "katakana": "ワンピース", "kanji": "ワンピース", "meaning": "one-piece dress", "topic": "Clothes & Fashion"},
    {"romaji": "wani", "hiragana": "わに", "katakana": "ワニ", "kanji": "鰐", "meaning": "crocodile / alligator", "topic": "Nature & Animals"},
    {"romaji": "wasabi", "hiragana": "わさび", "katakana": "ワサビ", "kanji": "山葵", "meaning": "wasabi horseradish", "topic": "Food & Dining"},
    {"romaji": "washitsu", "hiragana": "わしつ", "katakana": "ワシツ", "kanji": "和室", "meaning": "Japanese-style tatami room", "topic": "Home & Living"},
    {"romaji": "watashi", "hiragana": "わたし", "katakana": "ワタシ", "kanji": "私", "meaning": "I / me", "topic": "People & Family"},
    {"romaji": "watashitachi", "hiragana": "わたしたち", "katakana": "ワタシタチ", "kanji": "私たち", "meaning": "we / us", "topic": "People & Family"},

    # Y
    {"romaji": "yama", "hiragana": "やま", "katakana": "ヤマ", "kanji": "山", "meaning": "mountain", "topic": "Nature & Weather"},
    {"romaji": "yaoya", "hiragana": "やおや", "katakana": "ヤオヤ", "kanji": "八百屋", "meaning": "greengrocer / fruit & vegetable shop", "topic": "Shopping & Money"},
    {"romaji": "yasai", "hiragana": "やさい", "katakana": "ヤサイ", "kanji": "野菜", "meaning": "vegetable", "topic": "Food & Dining"},
    {"romaji": "yasumi", "hiragana": "やすみ", "katakana": "ヤスミ", "kanji": "休み", "meaning": "rest / day off / holiday", "topic": "Daily Life"},
    {"romaji": "yokan", "hiragana": "よかん", "katakana": "ヨカン", "kanji": "予感", "meaning": "premonition / hunch", "topic": "Emotions & Mind"},
    {"romaji": "yokou", "hiragana": "よこう", "katakana": "ヨコウ", "kanji": "旅行", "meaning": "journey", "topic": "Travel & Places"},
    {"romaji": "yoru", "hiragana": "よる", "katakana": "ヨル", "kanji": "夜", "meaning": "night / evening", "topic": "Time & Calendar"},
    {"romaji": "yotei", "hiragana": "よてい", "katakana": "ヨテイ", "kanji": "予定", "meaning": "plan / schedule", "topic": "School & Work"},
    {"romaji": "youfuku", "hiragana": "ようふく", "katakana": "ヨウフク", "kanji": "洋服", "meaning": "Western-style clothes", "topic": "Clothes & Fashion"},
    {"romaji": "youshi", "hiragana": "ようし", "katakana": "ヨウシ", "kanji": "用紙", "meaning": "form / blank sheet of paper", "topic": "School & Work"},
    {"romaji": "yuki", "hiragana": "ゆき", "katakana": "ユキ", "kanji": "雪", "meaning": "snow", "topic": "Nature & Weather"},
    {"romaji": "yume", "hiragana": "ゆめ", "katakana": "ユメ", "kanji": "夢", "meaning": "dream", "topic": "Emotions & Mind"},
    {"romaji": "yuubin", "hiragana": "ゆうびん", "katakana": "ユウビン", "kanji": "郵便", "meaning": "postal mail", "topic": "Daily Life"},
    {"romaji": "yuubinkyoku", "hiragana": "ゆうびんきょく", "katakana": "ユウビンキョク", "kanji": "郵便局", "meaning": "post office", "topic": "Travel & Places"},
    {"romaji": "yuugata", "hiragana": "ゆうがた", "katakana": "ユウガタ", "kanji": "夕方", "meaning": "early evening / twilight", "topic": "Time & Calendar"},
    {"romaji": "yuuhan", "hiragana": "ゆうはん", "katakana": "ユウハン", "kanji": "夕飯", "meaning": "dinner / supper", "topic": "Food & Dining"},
    {"romaji": "yuumeijin", "hiragana": "ゆうめいじん", "katakana": "ユウメイジン", "kanji": "有名人", "meaning": "celebrity / famous person", "topic": "People & Family"},

    # Z
    {"romaji": "zasshi", "hiragana": "ざっし", "katakana": "ザッシ", "kanji": "雑誌", "meaning": "magazine", "topic": "Hobbies & Media"},
    {"romaji": "zenbu", "hiragana": "ぜんぶ", "katakana": "ゼンブ", "kanji": "全部", "meaning": "all / everything", "topic": "Daily Life"},
    {"romaji": "zubon", "hiragana": "ずぼん", "katakana": "ズボン", "kanji": "ズボン", "meaning": "trousers / pants", "topic": "Clothes & Fashion"},
    {"romaji": "zutsuu", "hiragana": "ずつう", "katakana": "ヅツウ", "kanji": "頭痛", "meaning": "headache", "topic": "Body & Health"}
]

added_count = 0
for n in new_nouns:
    key = n['romaji'].lower()
    if key not in existing:
        n['alphabet'] = n['romaji'][0].upper()
        existing[key] = n
        added_count += 1

all_nouns = list(existing.values())
all_nouns.sort(key=lambda x: x['romaji'].lower())

print(f"Added {added_count} nouns. Total nouns now: {len(all_nouns)}")
