import json

raw_phrases_1 = [
    # A
    ("a, sou desu ka", "あ、そうですか", "ア、ソウデスカ", "あ、そうですか", "Oh, is that so?", "Daily Conversation"),
    ("a, sou nan desu ne", "あ、そうなんですね", "ア、ソウナンデスネ", "あ、そうなんですね", "Ah, I see! / Got it!", "Daily Conversation"),
    ("achira e douzo", "あちらへどうぞ", "アチラヘドウゾ", "あちらへどうぞ", "This way, please / Right over there", "Service & Hospitality"),
    ("achira no hou ga ii desu", "あちらのほうがいいです", "アチラノホウガイイデス", "あちらの方がいいです", "That one over there is better", "Shopping & Dining"),
    ("agatte kudasai", "あがってください", "アガッテクダサイ", "上がってください", "Please come on up / Please step inside", "Daily Conversation"),
    ("ai ni kite kudasai", "あいにきてください", "アイニキテクダサイ", "会いに来てください", "Please come visit me", "Friends & Social"),
    ("aite imasu ka", "あいていますか", "アイテイマスカ", "開いていますか", "Is it open? / Is there a vacancy?", "Travel & Hotel"),
    ("akemashite omedetou gozaimasu", "あけましておめでとうございます", "アケマシテオメデトウゴザイマス", "明けましておめでとうございます", "Happy New Year! (Polite)", "Greetings & Celebrations"),
    ("akaruku ikimashou", "あかるくいきましょう", "アカルクイキマショウ", "明るく行きましょう", "Let's stay positive and upbeat!", "Daily Conversation"),
    ("akiramezu ni ganbarou", "あきらめずにがんばろう", "アキラメズニガンバロウ", "諦めずに頑張ろう", "Let's never give up!", "Classroom & Study"),
    ("aku made sankou desu", "あくまでさんこうです", "アクマデサンコウデス", "あくまで参考です", "This is strictly for reference", "Work & Business"),
    ("amari ki ni shinaide", "あまりきにしないで", "アマリキニシナイデ", "あまり気にしないで", "Don't sweat it / Don't worry about it", "Empathy & Comfort"),
    ("ame ga furi sou desu", "あめがふりそうです", "アメガフリソウデス", "雨が降りそうです", "It looks like it's going to rain", "Weather & Daily"),
    ("anata wa dou omoimasu ka", "あなたはどうおもいますか", "アナタワドウオモイマスカ", "あなたはどう思いますか", "What do you think?", "Daily Conversation"),
    ("anata no okage desu", "あなたのおかげです", "アナタノオカゲデス", "あなたのおかげです", "It's all thanks to you!", "Gratitude & Thanks"),
    ("anata ni aete yokatta", "あなたにあえてよかった", "アナタニアエテヨカッタ", "あなたに会えて良かった", "I am so glad I met you", "Friends & Social"),
    ("annai shite kuremasu ka", "あんないしてくれますか", "アンナイシテクレマスカ", "案内してくれますか", "Could you show me around / guide me?", "Travel & Directions"),
    ("anshin shimashita", "あんしんしました", "アンシンシマシタ", "安心しました", "What a relief! / I feel relieved now", "Empathy & Comfort"),
    ("anzen daiichi desu", "あんぜんだいいちです", "アンゼンダイイチデス", "安全第一です", "Safety comes first", "Work & Business"),
    ("aozora ga kirei desu ne", "あおぞらがきれいですね", "アオゾラガキレイデスネ", "青空が綺麗ですね", "The blue sky is so gorgeous, isn't it?", "Weather & Daily"),
    ("appuru pai o kudasai", "あっぷるぱいをください", "アップルパイヲクダサイ", "アップルパイをください", "Apple pie, please", "Shopping & Dining"),
    ("arata na kimochi de", "あらたなきもちで", "アラタナキモチデ", "新たな気持ちで", "With a fresh mindset", "Daily Conversation"),
    ("arigatou gozaimasu", "ありがとうございます", "アリガトウゴザイマス", "ありがとうございます", "Thank you very much (Polite)", "Gratitude & Thanks"),
    ("arigatou gozaimashita", "ありがとうございました", "アリガトウゴザイマシタ", "ありがとうございました", "Thank you for what you did (Past)", "Gratitude & Thanks"),
    ("arittake no chikara de", "ありったけのちからで", "アリッタケノチカラデ", "ありったけの力で", "With all the strength I possess", "Daily Conversation"),
    ("asa gohan o tabemashita ka", "あさごはんをたべましたか", "アサゴハンヲタベマシタカ", "朝ご飯を食べましたか", "Did you have breakfast?", "Daily Conversation"),
    ("asatte mata aimashou", "あさってまたあいましょう", "アサッテマタアイマショウ", "明後日また会いましょう", "Let's meet again the day after tomorrow", "Greetings & Farewells"),
    ("ashimoto ni go-chuui kudasai", "あしもとにごちゅういください", "アシモトニゴチュウイクダサイ", "足元にご注意ください", "Please mind your step / watch your feet", "Service & Hospitality"),
    ("ashita mata aimashou", "あしたまたあいましょう", "アシタマタアイマショウ", "明日また会いましょう", "See you tomorrow!", "Greetings & Farewells"),
    ("ashita tenki ni naare", "あしたてんきになあれ", "アシタテンキニナアレ", "明日天気になあれ", "May tomorrow bring fine sunny weather!", "Weather & Daily"),
    ("asobou yo", "あそぼうよ", "アソボウヨ", "遊ぼうよ", "Let's hang out / play!", "Friends & Social"),
    ("atama ga itai desu", "あたまがいたいです", "アタマガイタイデス", "頭が痛いです", "I have a headache", "Health & Emergency"),
    ("atatakaku shite kudasai", "あたたかくしてください", "アタタカクシテクダサイ", "暖かくしてください", "Please stay warm!", "Empathy & Comfort"),
    ("atode denwa shimasu", "あとででんわします", "アトデデンワシマス", "後で電話します", "I will call you later", "Daily Conversation"),
    ("atode renraku shimasu", "あとでれんらくします", "アトデレンラクシマス", "後で連絡します", "I'll contact you later", "Daily Conversation"),
    ("atsui desu ne", "あついですね", "アツイデスネ", "暑いですね", "It's so hot, isn't it?", "Weather & Daily"),
    ("atsuku natte kimashita", "あつくなってきました", "アツクナッテキマシタ", "暑くなってきました", "It has started warming up", "Weather & Daily"),
    ("ayamaru hitsuyou wa arimasen", "あやまるひつようはありません", "アヤマルヒツヨウワアリマセン", "謝る必要はありません", "There is no need to apologize", "Empathy & Comfort"),

    # B
    ("bai bai", "ばいばい", "バイバイ", "バイバイ", "Bye-bye! (Casual)", "Greetings & Farewells"),
    ("bannou da to omoimasu", "ばんのうだとおもいます", "バンノウダトオモイマス", "万能だと思います", "I think it's all-purpose / versatile", "Daily Conversation"),
    ("barechatta", "ばれちゃった", "バレチャッタ", "ばれちゃった", "Uh-oh, the cat's out of the bag!", "Friends & Social"),
    ("basu tei wa doko desu ka", "ばすていわどこですか", "バステイワドコデスカ", "バス停はどこですか", "Where is the bus stop?", "Travel & Directions"),
    ("bata- o kudasai", "ばたーをください", "バターヲクダサイ", "バターをください", "Butter, please", "Shopping & Dining"),
    ("batsu-gun no aji desu", "ばつぐんのあじです", "バツグンノアジデス", "抜群の味です", "The flavor is superlative!", "Shopping & Dining"),
    ("beddo no shita ni arimasu", "べっどのしたにあります", "ベッドノシタニアリマス", "ベッドの下にあります", "It's right under the bed", "Daily Conversation"),
    ("bengoshi ni soudan shimasu", "べんごしにそうだんします", "ベンゴシニソウダンシマス", "弁護士に相談します", "I will consult an attorney", "Work & Business"),
    ("benkyou ni narimashita", "べんきょうになりました", "ベンキョウニナリマシタ", "勉強になりました", "I learned a great deal from that!", "Gratitude & Thanks"),
    ("benri desu ne", "べんりですね", "ベンリデスネ", "便利ですね", "That's so handy / convenient, isn't it?", "Daily Conversation"),
    ("bento o hitotsu kudasai", "べんとうをひとつください", "ベントウヲヒトツクダサイ", "弁当を一つください", "One bento box, please", "Shopping & Dining"),
    ("betsu no mono o misete", "べつのものをみせて", "ベツノモノヲミセテ", "別の物を見せて", "Please show me another one", "Shopping & Dining"),
    ("betsu ni kamawanai yo", "べつにかまわないよ", "ベツニカマワナイヨ", "別にかまわないよ", "I don't mind at all", "Daily Conversation"),
    ("bikkuri shimashita", "びっくりしました", "ビックリシマシタ", "びっくりしました", "You surprised me! / What a shock!", "Daily Conversation"),
    ("biru ga takai desu", "びるがたかいです", "ビルガタカイデス", "ビルが高いです", "The buildings are so tall", "Travel & Directions"),
    ("biiru o mou ippai", "びーるをもういっぱい", "ビールヲモウイッパイ", "ビールをもう一杯", "One more beer, please!", "Shopping & Dining"),
    ("boku mo sou omoimasu", "ぼくもそうおもいます", "ボクモソウオモイマス", "僕もそう思います", "I think so too (Male)", "Daily Conversation"),
    ("boku ni makasete", "ぼくにまかせて", "ボクニマカセテ", "僕に任せて", "Leave it to me! (Male casual)", "Friends & Social"),
    ("boushi ga niai masu ne", "ぼうしがにあいますね", "ボウシガニアイマスネ", "帽子が似合いますね", "That hat suits you nicely!", "Daily Conversation"),
    ("boushi o wasuremashita", "ぼうしをわすれました", "ボウシヲワスレマシタ", "帽子を忘れました", "I forgot my hat", "Daily Conversation"),
    ("budo ga oishii desu", "ぶどうがおいしいです", "ブドウガオイシイデス", "葡萄が美味しいです", "These grapes are delicious", "Shopping & Dining"),
    ("buji de yokatta desu", "ぶじでよかったです", "ブジデヨカッタデス", "無事で良かったです", "Thank goodness you are safe!", "Empathy & Comfort"),
    ("buji ni tsukimashita", "ぶじにつきました", "ブジニツキマシタ", "無事に着きました", "I arrived safe and sound", "Travel & Hotel"),
    ("bunka o manabitai desu", "ぶんかをまなびたいです", "ブンカヲマナビタイデス", "文化を学びたいです", "I want to learn about the culture", "Classroom & Study"),
    ("bunpou ga muzukashii desu", "ぶんぽうがむずかしいです", "ブンポウガムズカシイデス", "文法が難しいです", "The grammar is tricky / difficult", "Classroom & Study"),
    ("byouin e ikimashou", "びょういんへいきましょう", "ビョウインヘイキマショウ", "病院へ行きましょう", "Let's go to the hospital", "Health & Emergency"),
    ("byouki ga naorimashita", "びょうきがなおりました", "ビョウキガナオリマシタ", "病気が治りました", "I have recovered from illness", "Health & Emergency"),

    # C
    ("chanto kiku yo", "ちゃんときくよ", "チャントキクヨ", "ちゃんと聞くよ", "I am listening closely", "Daily Conversation"),
    ("chanto setsumei shite", "ちゃんとせつめいして", "チャントセツメイシテ", "ちゃんと説明して", "Please explain it properly", "Daily Conversation"),
    ("chansu o nogasanaide", "ちゃんすをのがさないで", "チャンスヲノガサナイデ", "チャンスを逃さないで", "Don't miss this opportunity!", "Daily Conversation"),
    ("chawan o kudasai", "ちゃわんをください", "チャワンヲクダサイ", "茶碗をください", "A rice bowl, please", "Shopping & Dining"),
    ("chekkuauto o onegai shimasu", "ちぇっくあうとおねがいします", "チェックアウトオネガイシマス", "チェックアウトをお願いします", "Check-out, please", "Travel & Hotel"),
    ("chekkuin o onegai shimasu", "ちぇっくいんおねがいします", "チェックインオネガイシマス", "チェックインをお願いします", "Check-in, please", "Travel & Hotel"),
    ("chiisai koto wa ki ni suruna", "ちいさいことはきにするな", "チイサイコトワキニスルナ", "小さい事は気にするな", "Don't sweat the small stuff!", "Empathy & Comfort"),
    ("chika desu ka", "ちかですか", "チカデスカ", "地下ですか", "Is it in the basement / underground?", "Travel & Directions"),
    ("chikai desu ka", "ちかいですか", "チカイデスカ", "近いですか", "Is it close nearby?", "Travel & Directions"),
    ("chikara ni narimasu yo", "ちからになりますよ", "チカラニナリマスヨ", "力になりますよ", "I'll be happy to help you out!", "Empathy & Comfort"),
    ("chotto ii desu ka", "ちょっといいですか", "チョットイイデスカ", "一寸いいですか", "Do you have a quick minute?", "Daily Conversation"),
    ("chotto matte kudasai", "ちょっとまってください", "チョットマッテクダサイ", "一寸待ってください", "Just a moment, please", "Daily Conversation"),
    ("chotto komatte imasu", "ちょっとこまっています", "チョットコマッテイマス", "ちょっと困っています", "I'm in a bit of a bind", "Daily Conversation"),
    ("chotto kangaesasete", "ちょっとかんがえさせて", "チョットカンガエサセテ", "ちょっと考えさせて", "Let me think about it for a bit", "Daily Conversation"),
    ("chotto mite mo ii desu ka", "ちょっとみてもいいですか", "チョットミテモイイデスカ", "ちょっと見てもいいですか", "May I take a look?", "Shopping & Dining"),
    ("chotto o-kiki shimasu ga", "ちょっとおききしますが", "チョットオキキシマスガ", "一寸お聞きしますが", "Excuse me, may I ask you something?", "Travel & Directions"),
    ("chotto sabishii desu", "ちょっとさびしいです", "チョットサビシイデス", "ちょっと寂しいです", "I feel a bit lonely", "Empathy & Comfort"),
    ("chotto tsukaremashita", "ちょっとつかれました", "チョットツカレマシタ", "ちょっと疲れました", "I am a little fatigued", "Daily Conversation"),
    ("chotto yasumou", "ちょっとやすもう", "チョットヤスモウ", "ちょっと休もう", "Let's take a short rest", "Daily Conversation"),
    ("chuumon o onegai shimasu", "ちゅうもんをおねがいします", "チュウモンヲオネガイシマス", "注文をお願いします", "We are ready to order, please", "Shopping & Dining"),
    ("chuumon wa mada desu", "ちゅうもんわまだです", "チュウモンワマダデス", "注文はまだです", "We haven't ordered yet", "Shopping & Dining"),
    ("chuusha shite mo ii desu ka", "ちゅうしゃしてもいいですか", "チュウシャシテモイイデスカ", "駐車してもいいですか", "May I park my car here?", "Travel & Directions"),

    # D
    ("daiji ni shite kudasai", "だいじにしてください", "ダイジニシテクダサイ", "大事にしてください", "Please take good care of yourself / treasure it", "Empathy & Comfort"),
    ("daijoubu desu ka", "だいじょうぶですか", "ダイジョウブデスカ", "大丈夫ですか", "Are you alright? / Is everything okay?", "Empathy & Comfort"),
    ("daijoubu desu yo", "だいじょうぶですよ", "ダイジョウブデスヨ", "大丈夫ですよ", "No worries / It's all fine!", "Empathy & Comfort"),
    ("daisuki desu", "だいすきです", "ダイスキデス", "大好きです", "I love it / I like it very much!", "Friends & Social"),
    ("daitan ni ikou", "だいたんにいこう", "ダイタンニイコウ", "大胆に行こう", "Let's be bold!", "Daily Conversation"),
    ("dakara itta deshou", "だからいったでしょう", "ダカライッタデショウ", "だから言ったでしょう", "See? That's what I told you!", "Daily Conversation"),
    ("dame desu", "だめです", "ダメデス", "駄目です", "No, you cannot / It's forbidden", "Daily Conversation"),
    ("dare ni mo iwanai de", "だれにもいわないで", "ダレニモイワナイデ", "誰にも言わないで", "Please don't tell anyone", "Friends & Social"),
    ("dare desu ka", "だれですか", "ダレデスカ", "誰ですか", "Who is it? / Who are you?", "Daily Conversation"),
    ("de, doushimasu ka", "で、どうしますか", "デ、ドウシマスカ", "で、どうしますか", "So, what shall we do?", "Daily Conversation"),
    ("dekiru dake hayaku", "できるだけはやく", "デキルダケハヤク", "できるだけ早く", "As quickly as possible", "Work & Business"),
    ("dekiru kagiri yari masu", "できるかぎりやります", "デキルカギリヤリマス", "できる限りやります", "I'll do everything within my power", "Work & Business"),
    ("dekiru to omoimasu", "できるとおもいます", "デキルトオモイマス", "できると思います", "I believe I/we can do it", "Work & Business"),
    ("dekita yo", "できたよ", "デキタヨ", "出来たよ", "All done! / I did it!", "Daily Conversation"),
    ("demo, hontou ni ii no", "でも、ほんとうにいいの", "デモ、ホントウニイイノ", "でも、本当にいいの", "But are you truly sure it's alright?", "Daily Conversation"),
    ("denki o keshite kudasai", "でんきをけしてください", "デンキヲケシテクダサイ", "電気を消してください", "Please turn off the light", "Daily Conversation"),
    ("denki o tsukete kudasai", "でんきをつけてください", "デンキヲツケテクダサイ", "電気をつけてください", "Please turn on the light", "Daily Conversation"),
    ("densha ga kimashita", "でんしゃがきましました", "デンシャガキマシタ", "電車が来ました", "The train has arrived", "Travel & Directions"),
    ("denwa bango o oshiete", "でんわばんごうをおしえて", "デンワバンゴウヲオシエテ", "電話番号を教えて", "Could you share your phone number?", "Friends & Social"),
    ("denwa o kashite kudasai", "でんわをかしてください", "デンワヲカシテクダサイ", "電話を貸してください", "Could I please borrow your phone?", "Health & Emergency"),
    ("dezato o tabemasen ka", "でざーとをたべませんか", "デザートヲタベマセンカ", "デザートを食べませんか", "Would you like some dessert?", "Shopping & Dining"),
    ("doa o akete kudasai", "どあをあけてください", "ドアヲアケテクダサイ", "ドアを開けてください", "Please open the door", "Daily Conversation"),
    ("doa o shimete kudasai", "どあをしめてください", "ドアヲシメテクダサイ", "ドアを閉めてください", "Please close the door", "Daily Conversation"),
    ("doko e iku no", "どこへいくの", "ドコヘイクノ", "どこへ行くの", "Where are you heading?", "Daily Conversation"),
    ("doko kara kimashita ka", "どこからきましたか", "ドコカラキマシタカ", "どこから来ましたか", "Where are you from?", "Daily Conversation"),
    ("doko ni arimasu ka", "どこにありますか", "ドコニアリマスカ", "どこにありますか", "Where is it located?", "Travel & Directions"),
    ("donmai desu", "どんまいです", "ドンマイデス", "どんまいです", "Don't mind! / Shake it off!", "Empathy & Comfort"),
    ("donna aji desu ka", "どんなあじですか", "ドンナアジデスカ", "どんな味ですか", "What does it taste like?", "Shopping & Dining"),
    ("dono gurai kakarimasu ka", "どのごらいかかりますか", "ドノグライカカリマスカ", "どの位かかりますか", "How long / how much will it take?", "Travel & Directions"),
    ("dore ga o-susume desu ka", "どれがおおすすめですか", "ドレガオオスメデスカ", "どれがおすすめですか", "Which one do you recommend?", "Shopping & Dining"),
    ("dore ni shiyou ka na", "どれにしようかな", "ドレニシヨウカナ", "どれにしようかな", "Hmm, which one shall I pick?", "Shopping & Dining"),
    ("dou itashimashite", "どういたしまして", "ドウイタシマシテ", "どう致しまして", "You are very welcome / Don't mention it", "Gratitude & Thanks"),
    ("dou shita no", "どうしたの", "ドウシタノ", "どうしたの", "What's the matter? / What happened?", "Daily Conversation"),
    ("douzo o-hairi kudasai", "どうぞおはいりください", "ドウゾオハイリクダサイ", "どうぞお入りください", "Please come right on in", "Service & Hospitality"),
    ("douzo o-kake kudasai", "どうぞおかえください", "ドウゾオカケクダサイ", "どうぞお掛けください", "Please have a seat", "Service & Hospitality"),
    ("douzo meshiagare", "どうぞめしあがれ", "ドウゾメシアガレ", "どうぞ召し上がれ", "Bon appétit! / Enjoy your meal!", "Shopping & Dining"),
    ("douzo yoroshiku", "どうぞよろしく", "ドウゾヨロシク", "どうぞよろしく", "Nice to meet you / Pleased to work with you", "Greetings & Farewells"),
    ("doumo arigatou", "どうもありがとう", "ドウモアリガトウ", "どうもありがとう", "Thank you very much!", "Gratitude & Thanks"),
    ("doumo sumimasen", "どうもすみません", "ドウモスミマセン", "どうもすみません", "I'm very sorry / Thank you kindly", "Gratitude & Thanks")
]

with open('src/data/vocab/n5_vocab.json', 'r', encoding='utf-8') as f:
    data = json.load(f)

existing = {item['romaji'].lower(): item for item in data['phrases']}

for item in raw_phrases_1:
    key = item[0].lower()
    if key not in existing:
        existing[key] = {
            "alphabet": item[0][0].upper(),
            "romaji": item[0],
            "hiragana": item[1],
            "katakana": item[2],
            "kanji": item[3],
            "meaning": item[4],
            "topic": item[5]
        }

print(f"Current phrases part 1: {len(existing)}")
