import json

# Authentic list of JLPT / conversational Japanese verbs
# Each tuple: (romaji, hiragana, katakana, kanji, meaning, type, topic)
raw_verbs = [
    # A
    ("abakareru", "あばかれる", "アバカレル", "暴かれる", "to be exposed / disclosed", "Ichidan", "Social & Communication"),
    ("abaku", "あばく", "アバク", "暴く", "to expose / unmask", "Godan", "Social & Communication"),
    ("abiru", "あびる", "アビル", "浴びる", "to take (a shower) / bathe", "Ichidan", "Daily Actions"),
    ("abiseru", "あびせる", "アビセル", "浴びせる", "to pour upon / shower with", "Ichidan", "Daily Actions"),
    ("aburu", "あぶる", "アブル", "炙る", "to scorch / broil / grill", "Godan", "Cooking & Dining"),
    ("aeru", "あえる", "アエル", "和える", "to dress (salad / food)", "Ichidan", "Cooking & Dining"),
    ("agaku", "あがく", "アガク", "足掻く", "to struggle / paw the ground", "Godan", "Movement & Travel"),
    ("agaru", "あがる", "アガル", "上がる", "to go up / rise", "Godan", "Movement & Travel"),
    ("ageru", "あげる", "アゲル", "上げる", "to give / raise / lift", "Ichidan", "Daily Actions"),
    ("agumu", "あぐむ", "アグム", "倦む", "to lose interest / tire of", "Godan", "Emotions & Mind"),
    ("aisuru", "あいする", "アイスル", "愛する", "to love / hold dear", "Suru Verb", "Emotions & Mind"),
    ("ajiwau", "あじわう", "アジワウ", "味わう", "to taste / savor / relish", "Godan", "Cooking & Dining"),
    ("akirameru", "あきらめる", "アキラメル", "諦める", "to give up / resign", "Ichidan", "Emotions & Mind"),
    ("akiru", "あきる", "アキル", "飽きる", "to get tired of / be satiated", "Ichidan", "Emotions & Mind"),
    ("akogareiru", "あこがれる", "アコガレル", "憧れる", "to yearn for / admire", "Ichidan", "Emotions & Mind"),
    ("aku", "あく", "アク", "開く", "to open (doors/shops, intransitive)", "Godan", "Daily Actions"),
    ("akeru", "あける", "アケル", "開ける", "to open (transitive)", "Ichidan", "Daily Actions"),
    ("akushu suru", "あくしゅする", "アクシュスル", "握手する", "to shake hands", "Suru Verb", "Social & Communication"),
    ("amagasu", "あまやかす", "アマヤカス", "甘やかす", "to pamper / spoil", "Godan", "Social & Communication"),
    ("amaru", "あまる", "アマル", "余る", "to remain / be surplus", "Godan", "Daily Actions"),
    ("amu", "あむ", "アム", "編む", "to knit / braid", "Godan", "Work & Study"),
    ("annai suru", "あんないする", "アンナイスル", "案内する", "to guide / show around", "Suru Verb", "Movement & Travel"),
    ("anshin suru", "あんしんする", "アンシンスル", "安心する", "to feel at ease / relieved", "Suru Verb", "Emotions & Mind"),
    ("aogu", "あおぐ", "アオグ", "仰ぐ", "to look up to / fan oneself", "Godan", "Daily Actions"),
    ("aomuku", "あおむく", "アオムク", "仰向く", "to face upward", "Godan", "Body & Actions"),
    ("arasou", "あらそう", "アラソウ", "争う", "to dispute / contend / fight", "Godan", "Social & Communication"),
    ("aratameru", "あらためる", "アラタメル", "改める", "to revise / inspect / reform", "Ichidan", "Work & Study"),
    ("arau", "あらう", "アラウ", "洗う", "to wash / cleanse", "Godan", "Daily Actions"),
    ("arawareru", "あらわれる", "アラワレル", "現れる", "to appear / show up", "Ichidan", "Movement & Travel"),
    ("arawasu", "あらわす", "アラワス", "表す", "to express / symbolize", "Godan", "Social & Communication"),
    ("aruku", "あるく", "アルク", "歩く", "to walk / stroll", "Godan", "Movement & Travel"),
    ("aseru", "あせる", "アセル", "焦る", "to hurry nervously / panic", "Godan", "Emotions & Mind"),
    ("asobu", "あそぶ", "アソブ", "遊ぶ", "to play / enjoy oneself", "Godan", "Hobbies & Leisure"),
    ("atatamaru", "あたたまる", "アタタマル", "温まる", "to warm oneself up", "Godan", "Daily Actions"),
    ("atatameru", "あたためる", "アタタメル", "温める", "to warm up (food/bath)", "Ichidan", "Cooking & Dining"),
    ("ataru", "あたる", "アタル", "当たる", "to hit / strike / win (lottery)", "Godan", "Daily Actions"),
    ("ateru", "あてる", "アテル", "当てる", "to apply / direct toward / guess", "Ichidan", "Daily Actions"),
    ("atsukau", "あつかう", "アツカウ", "扱う", "to handle / operate / treat", "Godan", "Work & Study"),
    ("atsumaru", "あつまる", "アツマル", "集まる", "to gather / congregate", "Godan", "Social & Communication"),
    ("atsumeru", "あつめる", "アツメル", "集める", "to assemble / collect", "Ichidan", "Daily Actions"),
    ("au", "あう", "アウ", "会う", "to meet / see someone", "Godan", "Social & Communication"),
    ("ayamaru", "あやまる", "アヤマル", "謝る", "to apologize", "Godan", "Social & Communication"),
    ("ayashimu", "あやしむ", "アヤシム", "怪しむ", "to suspect / distrust", "Godan", "Emotions & Mind"),
    ("ayumu", "あゆむ", "アユム", "歩む", "to walk / tread (a path in life)", "Godan", "Movement & Travel"),
    ("azukaru", "あずかる", "アズカル", "預かる", "to look after / hold in trust", "Godan", "Daily Actions"),
    ("azukeru", "あずける", "アズケル", "預ける", "to deposit / leave in charge", "Ichidan", "Daily Actions"),

    # B
    ("bakusuru", "ばくする", "バクスル", "縛する", "to bind / tie down", "Suru Verb", "Daily Actions"),
    ("bakuhatsu suru", "ばくはつする", "バクハツスル", "爆発する", "to explode", "Suru Verb", "Nature & Weather"),
    ("bango o tsukeru", "ばんごうをつける", "バンゴウヲツケル", "番号を付ける", "to number / assign digits", "Ichidan", "Work & Study"),
    ("bando o kumu", "ばんどをくむ", "バンドヲクム", "バンドを組む", "to form a music band", "Godan", "Hobbies & Leisure"),
    ("benkyou suru", "べんきょうする", "ベンキョウスル", "勉強する", "to study", "Suru Verb", "Work & Study"),
    ("bengo suru", "べんごする", "ベンゴスル", "弁護する", "to defend / advocate", "Suru Verb", "Work & Study"),
    ("bikkuri suru", "びっくりする", "ビックリスル", "吃驚する", "to be surprised", "Suru Verb", "Emotions & Mind"),
    ("biru o tateru", "びるをたてる", "ビルヲタテル", "ビルを建てる", "to construct buildings", "Ichidan", "Work & Study"),
    ("bocchan to ochiru", "ぼっちゃんとおちる", "ボッチャントオチル", "ぽちゃんと落ちる", "to plop down", "Ichidan", "Movement & Travel"),
    ("bokin suru", "ぼきんする", "ボキンスル", "募金する", "to raise funds / donate", "Suru Verb", "Social & Communication"),
    ("bonyari suru", "ぼんやりする", "ボンヤリスル", "ぼんやりする", "to space out / daydream", "Suru Verb", "Emotions & Mind"),
    ("bouken suru", "ぼうけんする", "ボウケンスル", "冒険する", "to embark on an adventure", "Suru Verb", "Movement & Travel"),
    ("boushi suru", "ぼうしする", "ボウシスル", "防止する", "to prevent / forestall", "Suru Verb", "Work & Study"),
    ("bunkatsu suru", "ぶんかつする", "ブンカツスル", "分割する", "to divide / partition", "Suru Verb", "Work & Study"),
    ("bunseki suru", "ぶんせきする", "ブンセキスル", "分析する", "to analyze data", "Suru Verb", "Work & Study"),
    ("burasageru", "ぶらさげる", "ブラサゲル", "ぶら下げる", "to hang / suspend down", "Ichidan", "Daily Actions"),
    ("burabura suru", "ぶらぶらする", "ブラブラスル", "ぶらぶらする", "to stroll aimlessly", "Suru Verb", "Movement & Travel"),
    ("butsukaru", "ぶつかる", "ブツカル", "ぶつかる", "to bump into / clash", "Godan", "Movement & Travel"),
    ("butsukeru", "ぶつける", "ブツケル", "ぶつける", "to bump against / fling", "Ichidan", "Daily Actions"),

    # C
    ("chanto suru", "ちゃんとする", "チャントスル", "ちゃんとする", "to behave properly / be neat", "Suru Verb", "Daily Actions"),
    ("chekku suru", "ちぇっくする", "チェックスル", "チェックする", "to verify / check", "Suru Verb", "Work & Study"),
    ("chigau", "ちがう", "チガウ", "違う", "to differ / be mistaken", "Godan", "Daily Actions"),
    ("chijimu", "ちぢむ", "チジム", "縮む", "to shrink / contract", "Godan", "Daily Actions"),
    ("chijimeru", "ちぢめる", "チジメル", "縮める", "to shorten / curtail", "Ichidan", "Daily Actions"),
    ("chigiru", "ちぎる", "チギル", "千切る", "to tear off / rip to shreds", "Godan", "Daily Actions"),
    ("chikaduku", "ちかづく", "チカヅク", "近づく", "to approach / come near", "Godan", "Movement & Travel"),
    ("chikau", "ちかう", "チカウ", "誓う", "to swear / take an oath", "Godan", "Social & Communication"),
    ("chikoku suru", "ちこくする", "チコクスル", "遅刻する", "to be late / arrive tardy", "Suru Verb", "Daily Actions"),
    ("chirakasu", "ちらかす", "チラカス", "散らかす", "to scatter around / mess up", "Godan", "Daily Actions"),
    ("chirakaru", "ちらかる", "チラカル", "散らかる", "to be cluttered / messy", "Godan", "Daily Actions"),
    ("chiru", "ちる", "チル", "散る", "to fall / scatter (blossoms)", "Godan", "Nature & Weather"),
    ("chokin suru", "ちょきんする", "チョキンスル", "貯金する", "to save money", "Suru Verb", "Daily Actions"),
    ("chousa suru", "ちょうさする", "チョウサスル", "調査する", "to investigate / probe", "Suru Verb", "Work & Study"),
    ("chousetsu suru", "ちょうせつする", "チョウセツスル", "調節する", "to adjust / modulate", "Suru Verb", "Daily Actions"),
    ("chousen suru", "ちょうせんする", "チョウセンスル", "挑戦する", "to take on a challenge", "Suru Verb", "Work & Study"),
    ("chuumon suru", "ちゅうもんする", "チュウモンスル", "注文する", "to place an order", "Suru Verb", "Cooking & Dining"),
    ("chuusha suru", "ちゅうしゃする", "チュウシャスル", "駐車する", "to park a vehicle", "Suru Verb", "Movement & Travel"),
    ("chuushi suru", "ちゅうしする", "チュウシスル", "中止する", "to call off / cancel", "Suru Verb", "Daily Actions"),
    ("chuui suru", "ちゅういする", "チュウイスル", "注意する", "to be careful / warn", "Suru Verb", "Daily Actions"),

    # D
    ("daku", "だく", "ダク", "抱く", "to embrace / hug / hold", "Godan", "Body & Actions"),
    ("damakasu", "だます", "ダマス", "騙す", "to deceive / hoodwink", "Godan", "Social & Communication"),
    ("damaru", "だまる", "ダマル", "黙る", "to remain silent / hold tongue", "Godan", "Social & Communication"),
    ("dasu", "だす", "ダス", "出す", "to take out / submit / send", "Godan", "Daily Actions"),
    ("deau", "であう", "デアウ", "出会う", "to encounter / meet by chance", "Godan", "Social & Communication"),
    ("dekakeru", "でかける", "デカケル", "出かける", "to go out / leave home", "Ichidan", "Movement & Travel"),
    ("dekiru", "できる", "デキル", "出来る", "to be able / can do / be made", "Ichidan", "Daily Actions"),
    ("denwa suru", "でんわする", "デンワスル", "電話する", "to make a telephone call", "Suru Verb", "Social & Communication"),
    ("deru", "でる", "デル", "出る", "to emerge / exit / appear", "Ichidan", "Movement & Travel"),
    ("dokusho suru", "どくしょする", "ドクショスル", "読書する", "to read books", "Suru Verb", "Hobbies & Leisure"),
    ("doryoku suru", "どりょくする", "ドリョクスル", "努力する", "to exert effort / endeavor", "Suru Verb", "Work & Study"),
    ("doui suru", "どういする", "ドウイスル", "同意する", "to consent / agree", "Suru Verb", "Social & Communication"),

    # E
    ("egaku", "えがく", "エガク", "描く", "to sketch / depict / draw", "Godan", "Hobbies & Leisure"),
    ("enjiru", "えんじる", "エンジン", "演じる", "to enact / perform a drama", "Ichidan", "Hobbies & Leisure"),
    ("enjo suru", "えんじょする", "エンジョスル", "援助する", "to assist / give aid", "Suru Verb", "Social & Communication"),
    ("enki suru", "えんきする", "エンキスル", "延期する", "to defer / postpone", "Suru Verb", "Work & Study"),
    ("enryo suru", "えんりょする", "エンリョスル", "遠慮する", "to refrain / hesitate politely", "Suru Verb", "Social & Communication"),
    ("erabu", "えらぶ", "エラブ", "選ぶ", "to choose / select", "Godan", "Daily Actions"),
    ("eru", "える", "エル", "得る", "to gain / acquire / obtain", "Ichidan", "Work & Study"),

    # F
    ("fueru", "ふえる", "フエル", "増える", "to increase / multiply", "Ichidan", "Daily Actions"),
    ("fukameru", "ふかめる", "フカメル", "深める", "to deepen / enhance", "Ichidan", "Work & Study"),
    ("fuku", "ふく", "フク", "吹く", "to blow (wind) / breathe out", "Godan", "Nature & Weather"),
    ("fuku (wipe)", "ふく", "フク", "拭く", "to wipe clean / towel dry", "Godan", "Daily Actions"),
    ("fukumu", "ふくむ", "フクム", "含む", "to contain / hold / encompass", "Godan", "Daily Actions"),
    ("fukushuu suru", "ふくしゅうする", "フクシュウスル", "復習する", "to review previous study", "Suru Verb", "Work & Study"),
    ("fumu", "ふむ", "フム", "踏む", "to step on / tread upon", "Godan", "Body & Actions"),
    ("furimuku", "ふりむく", "フリムク", "振り向く", "to turn one's head around", "Godan", "Body & Actions"),
    ("furu", "ふる", "フル", "降る", "to fall (rain/snow) / wave hand", "Godan", "Nature & Weather"),
    ("furueru", "ふるえる", "フルエル", "震える", "to shiver / shake / quiver", "Ichidan", "Body & Actions"),
    ("fusegu", "ふせぐ", "フセグ", "防ぐ", "to ward off / safeguard against", "Godan", "Daily Actions"),
    ("futoru", "ふとる", "フトル", "太る", "to gain weight / grow stout", "Godan", "Body & Actions"),
    ("fuyasu", "ふやす", "フヤス", "増やす", "to augment / multiply numbers", "Godan", "Daily Actions"),

    # G
    ("gaman suru", "がまんする", "ガマンスル", "我慢する", "to bear patiently / endure", "Suru Verb", "Emotions & Mind"),
    ("ganbaru", "がんばる", "ガンバル", "頑張る", "to persevere / give one's best", "Godan", "Daily Actions"),
    ("genshou suru", "げんしょうする", "ゲンショウスル", "減少する", "to decrease in quantity", "Suru Verb", "Daily Actions"),
    ("giron suru", "ぎろんする", "ギロンスル", "議論する", "to deliberate / debate", "Suru Verb", "Social & Communication"),
    ("gorogoro suru", "ごろごろする", "ゴロゴロスル", "ごろごろする", "to lounge comfortably", "Suru Verb", "Daily Actions"),
    ("goukakusuru", "ごうかくする", "ゴウカクスル", "合格する", "to pass tests successfully", "Suru Verb", "Work & Study"),

    # H
    ("haeru", "はえる", "ハエル", "生える", "to sprout / germinate / grow", "Ichidan", "Nature & Weather"),
    ("hairu", "はいる", "ハイル", "入る", "to enter / go inside", "Godan", "Movement & Travel"),
    ("haitatsu suru", "はいたつする", "ハイタツスル", "配達する", "to deliver packages", "Suru Verb", "Work & Study"),
    ("hajikeru", "はじける", "ハジケル", "弾ける", "to pop open / burst", "Ichidan", "Daily Actions"),
    ("hajimaru", "はじまる", "ハジマル", "始まる", "to begin (intransitive)", "Godan", "Daily Actions"),
    ("hajimeru", "はじめる", "ハジメル", "始める", "to begin (transitive)", "Ichidan", "Daily Actions"),
    ("hakaru", "はかる", "ハカル", "測る", "to gauge / measure / weigh", "Godan", "Work & Study"),
    ("haku", "はく", "ハク", "履く", "to wear (shoes/pants)", "Godan", "Daily Actions"),
    ("hakobu", "はこぶ", "ハコブ", "運ぶ", "to transport / lug", "Godan", "Movement & Travel"),
    ("hamaru", "はまる", "ハマル", "嵌る", "to fit into / be hooked on", "Godan", "Daily Actions"),
    ("hanareru", "はなれる", "ハナレル", "離れる", "to part from / grow distant", "Ichidan", "Movement & Travel"),
    ("hanasu", "はなす", "ハナス", "話す", "to speak / converse", "Godan", "Social & Communication"),
    ("harau", "はらう", "ハラウ", "払う", "to pay funds / sweep away", "Godan", "Daily Actions"),
    ("hareru", "はれる", "ハレル", "晴れる", "to become sunny / clear up", "Ichidan", "Nature & Weather"),
    ("haru", "はる", "ハル", "貼る", "to paste / stick / apply", "Godan", "Daily Actions"),
    ("hasamu", "はさむ", "ハサム", "挟む", "to sandwich / pinch between", "Godan", "Daily Actions"),
    ("hashiru", "はしる", "ハシル", "走る", "to sprint / run", "Godan", "Movement & Travel"),
    ("hataraku", "はたらく", "ハタラク", "働く", "to work / labor", "Godan", "Work & Study"),
    ("hayaru", "はやる", "ハヤル", "流行る", "to become trendy / fashionable", "Godan", "Social & Communication"),
    ("hazusu", "はずす", "ハズス", "外す", "to unfasten / detach", "Godan", "Daily Actions"),
    ("heru", "へる", "ヘル", "減る", "to dwindle / diminish", "Godan", "Daily Actions"),
    ("herasu", "へらす", "ヘラス", "減らす", "to curtail / reduce amount", "Godan", "Daily Actions"),
    ("hiekomu", "ひえこむ", "ヒエコム", "冷え込む", "to turn bitingly cold", "Godan", "Nature & Weather"),
    ("hieru", "ひえる", "ヒエル", "冷える", "to grow cold / chill", "Ichidan", "Nature & Weather"),
    ("hikaku suru", "ひかくする", "ヒカクスル", "比較する", "to contrast / compare", "Suru Verb", "Work & Study"),
    ("hikaru", "ひかる", "ヒカル", "光る", "to gleam / shine / glitter", "Godan", "Nature & Weather"),
    ("hiku", "ひく", "ヒク", "引く", "to pull / draw / play (piano)", "Godan", "Daily Actions"),
    ("hikkosu", "ひっこす", "ヒッコス", "引っ越す", "to move residence", "Godan", "Movement & Travel"),
    ("hiraku", "ひらく", "ヒラク", "開く", "to open widely", "Godan", "Daily Actions"),
    ("hirogaru", "ひろがる", "ヒロガル", "広がる", "to broaden / expand out", "Godan", "Movement & Travel"),
    ("hirou", "ひろう", "ヒロウ", "拾う", "to pick up / gather from ground", "Godan", "Daily Actions"),
    ("hohoemu", "ほほえむ", "ホホエム", "微笑む", "to smile warmly", "Godan", "Body & Actions"),
    ("homeru", "ほめる", "ホメル", "褒める", "to laud / compliment", "Ichidan", "Social & Communication"),
    ("honyaku suru", "ほんやくする", "ホンヤクスル", "翻訳する", "to translate written works", "Suru Verb", "Work & Study"),
    ("horu", "ほる", "ホル", "掘る", "to scoop out / excavate", "Godan", "Daily Actions"),
    ("hosu", "ほす", "ホス", "干す", "to desiccate / hang dry", "Godan", "Daily Actions"),

    # I
    ("ibaru", "いばる", "イバル", "威張る", "to act haughty / strut", "Godan", "Social & Communication"),
    ("idou suru", "いどうする", "イドウスル", "移動する", "to relocate / move spots", "Suru Verb", "Movement & Travel"),
    ("iidasu", "いいだす", "イイダス", "言い出す", "to bring up in speech", "Godan", "Social & Communication"),
    ("iitsukeru", "いいつける", "イイツケル", "言い付ける", "to dictate / instruct", "Ichidan", "Social & Communication"),
    ("ijimeru", "いじめる", "イジメル", "苛める", "to tease / torment", "Ichidan", "Social & Communication"),
    ("ijiru", "いじる", "イジル", "弄る", "to tamper with / twiddle", "Godan", "Daily Actions"),
    ("ikiru", "いきる", "イキル", "生きる", "to live / survive", "Ichidan", "Daily Actions"),
    ("iku", "いく", "イク", "行く", "to journey / proceed to", "Godan", "Movement & Travel"),
    ("inoru", "いのる", "イノル", "祈る", "to pray / supplicate", "Godan", "Culture & Society"),
    ("irassharu", "いらっしゃる", "イラッシャイル", "いらっしゃる", "to graciously be/come/go", "Godan", "Social & Communication"),
    ("ireru", "いれる", "イレル", "入れる", "to put inside / pour in", "Ichidan", "Daily Actions"),
    ("iru", "いる", "イル", "居る", "to be present / exist", "Ichidan", "Daily Actions"),
    ("iru (need)", "いる", "イル", "要る", "to require / be necessary", "Godan", "Daily Actions"),
    ("isogu", "いそぐ", "イソグ", "急ぐ", "to make haste / rush", "Godan", "Movement & Travel"),
    ("itadaku", "いただく", "イタダク", "頂く", "to humbly partake / receive", "Godan", "Cooking & Dining"),
    ("itameru", "いためる", "イタメル", "炒める", "to saute / stir-fry", "Ichidan", "Cooking & Dining"),
    ("itamu", "いたむ", "イタム", "痛む", "to suffer pain / ache", "Godan", "Body & Actions"),
    ("iu", "いう", "イウ", "言う", "to utter / say", "Godan", "Social & Communication"),
    ("iwau", "いわう", "イワウ", "祝う", "to celebrate / commemorate", "Godan", "Culture & Society"),

    # J
    ("jama suru", "じゃまする", "ジャマスル", "邪魔する", "to interfere / obstruct", "Suru Verb", "Social & Communication"),
    ("jikken suru", "じっけんする", "ジッケンスル", "実験する", "to test empirically", "Suru Verb", "Work & Study"),
    ("jiman suru", "じまんする", "ジマンスル", "自慢する", "to boast / pride oneself", "Suru Verb", "Social & Communication"),
    ("joutatsu suru", "じょうたつする", "ジョウタツスル", "上達する", "to make progress / improve", "Suru Verb", "Work & Study"),
    ("junbi suru", "じゅんびする", "ジュンビスル", "準備する", "to prepare / outfit", "Suru Verb", "Daily Actions"),

    # K
    ("kaeru", "かえる", "カエル", "帰る", "to head back home", "Godan", "Movement & Travel"),
    ("kaeru (alter)", "かえる", "カエル", "変える", "to alter / swap", "Ichidan", "Daily Actions"),
    ("kaesu", "かえす", "カエス", "返す", "to give back / restore", "Godan", "Daily Actions"),
    ("kagayaku", "かがやく", "カガヤク", "輝く", "to sparkle / shine", "Godan", "Nature & Weather"),
    ("kagu", "かぐ", "カグ", "嗅ぐ", "to smell / take a whiff", "Godan", "Perception & Senses"),
    ("kakaru", "かかる", "カカル", "掛かる", "to require time / cost / hang", "Godan", "Daily Actions"),
    ("kakeru", "かける", "カケル", "掛ける", "to suspend / telephone / put on", "Ichidan", "Daily Actions"),
    ("kakusu", "かくす", "カクス", "隠す", "to conceal / cloak", "Godan", "Daily Actions"),
    ("kakureru", "かくれる", "カクレル", "隠れる", "to hide away / duck", "Ichidan", "Daily Actions"),
    ("kakunin suru", "かくにんする", "カクニンスル", "確認する", "to verify / double-check", "Suru Verb", "Work & Study"),
    ("kaku", "かく", "カク", "書く", "to write / pen", "Godan", "Work & Study"),
    ("kamu", "かむ", "カム", "噛む", "to gnaw / bite down", "Godan", "Cooking & Dining"),
    ("kanashimu", "かなしむ", "カナシム", "悲しむ", "to lament / feel sorrow", "Godan", "Emotions & Mind"),
    ("kangaeru", "かんがえる", "カンガエル", "考える", "to deliberate / meditate on", "Ichidan", "Work & Study"),
    ("kanjiru", "かんじる", "カンジル", "感じる", "to experience / perceive emotion", "Ichidan", "Perception & Senses"),
    ("kansha suru", "かんしゃする", "カンシャスル", "感謝する", "to offer gratitude", "Suru Verb", "Social & Communication"),
    ("kariru", "かりる", "カリル", "借りる", "to lease / borrow", "Ichidan", "Daily Actions"),
    ("kasu", "かす", "カス", "貸す", "to lend / loan out", "Godan", "Daily Actions"),
    ("katsu", "かつ", "カツ", "勝つ", "to conquer / triumph", "Godan", "Work & Study"),
    ("kau", "かう", "カウ", "買う", "to purchase / buy", "Godan", "Daily Actions"),
    ("kayou", "かよう", "カヨウ", "通う", "to attend / commute", "Godan", "Movement & Travel"),
    ("kazoeru", "かぞえる", "カゾエル", "数える", "to enumerate / tally", "Ichidan", "Work & Study"),
    ("keikaku suru", "けいかくする", "ケイカクスル", "計画する", "to devise a plan", "Suru Verb", "Work & Study"),
    ("keiken suru", "けいけんする", "ケイケンスル", "経験する", "to undergo / experience", "Suru Verb", "Daily Actions"),
    ("kesu", "けす", "ケス", "消す", "to switch off / erase", "Godan", "Daily Actions"),
    ("kieru", "きえる", "キエル", "消える", "to fade away / vanish", "Ichidan", "Daily Actions"),
    ("kikoeru", "きこえる", "キコエル", "聞こえる", "to be audible", "Ichidan", "Perception & Senses"),
    ("kiku", "きく", "キク", "聞く", "to hear / attend to / inquire", "Godan", "Perception & Senses"),
    ("kimeru", "きめる", "キメル", "決める", "to settle on / decide", "Ichidan", "Work & Study"),
    ("kiru", "きる", "キル", "着る", "to don / wear clothing", "Ichidan", "Daily Actions"),
    ("kiru (sever)", "きる", "キル", "切る", "to slice / shear / disconnect", "Godan", "Daily Actions"),
    ("kizuku", "きづく", "キヅク", "気づく", "to realize / catch sight of", "Godan", "Perception & Senses"),
    ("komaru", "こまる", "コマル", "困る", "to be perplexed / in trouble", "Godan", "Daily Actions"),
    ("komu", "こむ", "コム", "混む", "to become packed with people", "Godan", "Movement & Travel"),
    ("korobu", "ころぶ", "コロブ", "転ぶ", "to stumble / fall flat", "Godan", "Body & Actions"),
    ("korosu", "ころす", "コロス", "殺す", "to slay / kill", "Godan", "Daily Actions"),
    ("kotaeru", "こたえる", "コタエル", "答える", "to reply / answer back", "Ichidan", "Social & Communication"),
    ("kotowaru", "ことわる", "コトワル", "断る", "to refuse / decline courteously", "Godan", "Social & Communication"),
    ("koukan suru", "こうかんする", "コウカンスル", "交換する", "to barter / exchange", "Suru Verb", "Daily Actions"),
    ("kubaru", "くばる", "クバル", "配る", "to pass out / hand around", "Godan", "Work & Study"),
    ("kudaru", "くだる", "クダル", "下る", "to step down / descend", "Godan", "Movement & Travel"),
    ("kumu", "くむ", "クム", "組む", "to team up / interlock", "Godan", "Work & Study"),
    ("kuraberu", "くらべる", "クラベル", "比べる", "to compare against", "Ichidan", "Work & Study"),
    ("kurasu", "くらす", "クラス", "暮らす", "to make one's living / dwell", "Godan", "Daily Actions"),
    ("kureru", "くれる", "クレル", "暮れる", "to draw to twilight", "Ichidan", "Nature & Weather"),
    ("kuru", "くる", "クル", "来る", "to come hither", "Irregular", "Movement & Travel"),
    ("kurushimu", "くるしむ", "クルシム", "苦しむ", "to endure pain / distress", "Godan", "Emotions & Mind"),
    ("kusaru", "くさる", "クサル", "腐る", "to decay / turn rancid", "Godan", "Daily Actions"),

    # M
    ("machi-awaseru", "まちあわせる", "マチアワセル", "待ち合わせる", "to rendezvous / meet up", "Ichidan", "Social & Communication"),
    ("machigaeru", "まちがえる", "マチガエル", "間違える", "to mistake / err", "Ichidan", "Work & Study"),
    ("machigau", "まちがう", "マチガウ", "間違う", "to be in error", "Godan", "Work & Study"),
    ("madowasu", "まどわす", "マドワス", "惑わす", "to bewilder / mislead", "Godan", "Emotions & Mind"),
    ("magaru", "まがる", "マガル", "曲がる", "to take a turn / curve", "Godan", "Movement & Travel"),
    ("mageru", "まげる", "マゲル", "曲げる", "to bend / distort", "Ichidan", "Daily Actions"),
    ("mairu", "まいる", "マイル", "参る", "to humbly go/come", "Godan", "Movement & Travel"),
    ("makaseru", "まかせる", "マカセル", "任せる", "to delegate / entrust", "Ichidan", "Work & Study"),
    ("makeru", "まける", "マケル", "負ける", "to suffer defeat / concede", "Ichidan", "Work & Study"),
    ("maku", "まく", "マク", "巻く", "to roll up / wind / wrap", "Godan", "Daily Actions"),
    ("maku (scatter)", "まく", "マク", "蒔く", "to sow seeds / scatter water", "Godan", "Nature & Weather"),
    ("mamoru", "まもる", "マモル", "守る", "to defend / obey rules", "Godan", "Daily Actions"),
    ("manabu", "まなぶ", "マナブ", "学ぶ", "to study deeply / learn", "Godan", "Work & Study"),
    ("maniau", "まにあう", "マニアウ", "間に合う", "to be on schedule / suffice", "Godan", "Daily Actions"),
    ("maneku", "まねく", "マネク", "招く", "to beckon / invite", "Godan", "Social & Communication"),
    ("masu", "ます", "マス", "増す", "to heighten / swell", "Godan", "Daily Actions"),
    ("matomeru", "まとめる", "マトメル", "まとめる", "to synthesize / bring into order", "Ichidan", "Work & Study"),
    ("matsu", "まつ", "マツ", "待つ", "to wait / stay expectant", "Godan", "Daily Actions"),
    ("mawaru", "まわる", "マワル", "回る", "to spin / make rounds", "Godan", "Movement & Travel"),
    ("mawasu", "まわす", "マワス", "回す", "to rotate / pass around", "Godan", "Daily Actions"),
    ("mayou", "まよう", "マヨウ", "迷う", "to lose one's way / hesitate", "Godan", "Movement & Travel"),
    ("mazaru", "まざる", "マザル", "混ざる", "to blend / intermingle", "Godan", "Cooking & Dining"),
    ("mazeru", "まぜる", "マゼル", "混ぜる", "to stir together / blend", "Ichidan", "Cooking & Dining"),
    ("medatsu", "めだつ", "メダツ", "目立つ", "to attract attention / stand out", "Godan", "Social & Communication"),
    ("meirei suru", "めいれいする", "メイレイスル", "命令する", "to give orders", "Suru Verb", "Work & Study"),
    ("meguru", "めぐる", "メグル", "巡る", "to tour round / circumnavigate", "Godan", "Movement & Travel"),
    ("mieru", "みえる", "ミエル", "見える", "to be visible / in sight", "Ichidan", "Perception & Senses"),
    ("migaku", "みがく", "ミガク", "磨く", "to brush (teeth) / polish", "Godan", "Daily Actions"),
    ("minosu", "みなおす", "ミナオス", "見直す", "to reassess / look over again", "Godan", "Work & Study"),
    ("minarau", "みならう", "ミナラウ", "見習う", "to learn from watching", "Godan", "Work & Study"),
    ("minoru", "みのる", "ミノル", "実る", "to bear fruit / ripen", "Godan", "Nature & Weather"),
    ("miru", "みる", "ミル", "見る", "to observe / gaze at / watch", "Ichidan", "Perception & Senses"),
    ("miseru", "みせる", "ミセル", "見せる", "to put on display / show", "Ichidan", "Social & Communication"),
    ("mitsukaru", "みつかる", "ミツカル", "見つかる", "to be discovered", "Godan", "Daily Actions"),
    ("mitsukeru", "みつける", "ミツケル", "見つける", "to spot / seek out", "Ichidan", "Daily Actions"),
    ("mitsumeru", "みつめる", "ミツメル", "見つめる", "to stare intently / gaze at", "Ichidan", "Perception & Senses"),
    ("mochiiru", "もちいる", "モチイル", "用いる", "to make use of", "Ichidan", "Work & Study"),
    ("motsu", "もつ", "モツ", "持つ", "to hold in hand / possess", "Godan", "Daily Actions"),
    ("motoduku", "もとづく", "モトヅク", "基づく", "to be grounded / based upon", "Godan", "Work & Study"),
    ("motomeru", "もとめる", "モトメル", "求める", "to request / desire / pursue", "Ichidan", "Social & Communication"),
    ("motsureru", "もつれる", "モツレル", "縺れる", "to get tangled / tripped up", "Ichidan", "Daily Actions"),
    ("moukeru", "もうける", "モウケル", "儲ける", "to earn profits", "Ichidan", "Work & Study"),
    ("mousu", "もうす", "モウス", "申す", "to state humbly / be called", "Godan", "Social & Communication"),
    ("moushiageru", "もうしあげる", "モウシアゲル", "申し上げる", "to humbly tell / express", "Ichidan", "Social & Communication"),
    ("moushikomu", "もうしこむ", "モウシコム", "申し込む", "to sign up / apply formally", "Godan", "Work & Study"),
    ("moyasu", "もやす", "モヤス", "燃やす", "to incinerate / burn", "Godan", "Daily Actions"),
    ("moeru", "もえる", "モエル", "燃える", "to burst into flame / ignite", "Ichidan", "Nature & Weather"),
    ("mukaeru", "むかえる", "ムカエル", "迎える", "to welcome guests / usher in", "Ichidan", "Social & Communication"),
    ("mukau", "むかう", "ムカウ", "向かう", "to head towards / face", "Godan", "Movement & Travel"),
    ("muku", "むく", "ムク", "剥く", "to peel skin / rind", "Godan", "Cooking & Dining"),
    ("muku (face)", "むく", "ムク", "向く", "to turn towards / suit well", "Godan", "Daily Actions"),
    ("musubu", "むすぶ", "ムスブ", "結ぶ", "to tie a knot / connect", "Godan", "Daily Actions"),

    # N
    ("nagameru", "ながめる", "ナガメル", "眺める", "to admire scenic views", "Ichidan", "Perception & Senses"),
    ("nagareru", "ながれる", "ナガレル", "流れる", "to flow smoothly (water)", "Ichidan", "Nature & Weather"),
    ("nagasu", "ながす", "ナガス", "流す", "to flush / rinse down", "Godan", "Daily Actions"),
    ("naguru", "なぐる", "ナグル", "殴る", "to punch / wallop", "Godan", "Body & Actions"),
    ("nagusameru", "なぐさめる", "ナグサメル", "慰める", "to comfort / console", "Ichidan", "Emotions & Mind"),
    ("naku", "なく", "ナク", "泣く", "to weep / shed tears", "Godan", "Emotions & Mind"),
    ("naku (animal)", "なく", "ナク", "鳴く", "to sing / chirp / howl (animal)", "Godan", "Nature & Animals"),
    ("nakunaru", "なくなる", "ナクナル", "無くなる", "to run out / be lost", "Godan", "Daily Actions"),
    ("nakunaru (die)", "なくなる", "ナクナル", "亡くなる", "to pass away / perish", "Godan", "Daily Actions"),
    ("nakusu", "なくす", "ナクス", "無くす", "to misplace / eliminate", "Godan", "Daily Actions"),
    ("namakeru", "なまける", "ナマケル", "怠ける", "to slack off / idle", "Ichidan", "Work & Study"),
    ("nameru", "なめる", "ナメル", "舐める", "to lick with tongue", "Ichidan", "Cooking & Dining"),
    ("naoru", "なおる", "ナオル", "治る", "to heal / recover from illness", "Godan", "Daily Actions"),
    ("naoru (fix)", "なおる", "ナオル", "直る", "to get repaired (intransitive)", "Godan", "Daily Actions"),
    ("naosu", "なおす", "ナオス", "直す", "to fix / repair / cure", "Godan", "Daily Actions"),
    ("narabu", "ならぶ", "ナラブ", "並ぶ", "to form a line / stand side by side", "Godan", "Movement & Travel"),
    ("naraberu", "ならべる", "ナラベル", "並べる", "to arrange in neat row", "Ichidan", "Daily Actions"),
    ("narau", "ならう", "ナラウ", "習う", "to practice / take lessons", "Godan", "Work & Study"),
    ("nareru", "なれる", "ナレル", "慣れる", "to grow familiar / accustomed", "Ichidan", "Daily Actions"),
    ("naru", "なる", "ナル", "なる", "to become / turn into", "Godan", "Daily Actions"),
    ("naru (sound)", "なる", "ナル", "鳴る", "to chime / ring / sound", "Godan", "Daily Actions"),
    ("nayamu", "なやむ", "ナヤム", "悩む", "to agonize over / brood", "Godan", "Emotions & Mind"),
    ("negau", "ねがう", "ネガウ", "願う", "to request / desire earnest prayer", "Godan", "Social & Communication"),
    ("nemuru", "ねむる", "ネムル", "眠る", "to fall into deep sleep", "Godan", "Daily Actions"),
    ("neru", "ねる", "ネル", "寝る", "to go to bed / lay down", "Ichidan", "Daily Actions"),
    ("neru (knead)", "ねる", "ネル", "練る", "to knead dough / refine plans", "Godan", "Cooking & Dining"),
    ("nigeru", "にげる", "ニゲル", "逃げる", "to flee / escape", "Ichidan", "Movement & Travel"),
    ("nigiru", "にぎる", "ニギル", "握る", "to grip firmly / shape rice balls", "Godan", "Daily Actions"),
    ("nigoru", "にごる", "ニゴル", "濁る", "to become murky / voiced", "Godan", "Nature & Weather"),
    ("nikumu", "にくむ", "ニクム", "憎む", "to loathe / detest", "Godan", "Emotions & Mind"),
    ("niru", "にる", "ニル", "似る", "to bear resemblance / look like", "Ichidan", "People & Family"),
    ("niru (boil)", "にる", "ニル", "煮る", "to simmer / boil in broth", "Ichidan", "Cooking & Dining"),
    ("nobasu", "のばす", "ノバス", "伸ばす", "to stretch out / extend reach", "Godan", "Daily Actions"),
    ("noberu", "のべる", "ノベル", "述べる", "to state / declare / recount", "Ichidan", "Social & Communication"),
    ("noboru", "のぼる", "ノボル", "登る", "to scale / ascend / climb", "Godan", "Movement & Travel"),
    ("nokoru", "のこる", "ノコル", "残る", "to linger / remain behind", "Godan", "Daily Actions"),
    ("nokosu", "のこす", "ノコス", "残す", "to leave over / reserve", "Godan", "Daily Actions"),
    ("nomu", "のむ", "ノム", "飲む", "to drink / swallow down", "Godan", "Cooking & Dining"),
    ("noru", "のる", "ノル", "乗る", "to board / ride in a vehicle", "Godan", "Movement & Travel"),
    ("noseru", "のせる", "ノセル", "乗せる", "to give a lift / load aboard", "Ichidan", "Movement & Travel"),
    ("nozomu", "のぞむ", "ノゾム", "望む", "to wish for / aspire to", "Godan", "Emotions & Mind"),
    ("nugu", "ぬぐ", "ヌグ", "脱ぐ", "to peel off / take off clothes", "Godan", "Daily Actions"),
    ("nurasu", "ぬらす", "ヌラス", "濡らす", "to drench / dampen", "Godan", "Daily Actions"),
    ("nureru", "ぬれる", "ヌレル", "濡れる", "to get soaked / wet", "Ichidan", "Daily Actions"),
    ("nuru", "ぬる", "ヌル", "塗る", "to apply paint / spread butter", "Godan", "Daily Actions"),
    ("nusumu", "ぬすむ", "ヌスム", "盗む", "to steal / burglarize", "Godan", "Daily Actions"),

    # O
    ("oboeru", "おぼえる", "オボエル", "覚える", "to memorize / recall to mind", "Ichidan", "Work & Study"),
    ("ochiru", "おちる", "オチル", "落ちる", "to fall / fail exams", "Ichidan", "Movement & Travel"),
    ("odoroku", "おどろく", "オドロク", "驚く", "to be startled / amazed", "Godan", "Emotions & Mind"),
    ("odoru", "おどる", "オドル", "踊る", "to dance to rhythms", "Godan", "Hobbies & Leisure"),
    ("oikakeru", "おいかける", "オイカケル", "追いかける", "to chase / run after", "Ichidan", "Movement & Travel"),
    ("oikosu", "おいこす", "オイコス", "追い越す", "to overtake / pass by", "Godan", "Movement & Travel"),
    ("oitsuku", "おいつく", "オイツク", "追いつく", "to catch up with", "Godan", "Movement & Travel"),
    ("okiru", "おきる", "オキル", "起きる", "to awaken / stand up / occur", "Ichidan", "Daily Actions"),
    ("okonau", "おこなう", "オコナウ", "行う", "to execute / carry out", "Godan", "Work & Study"),
    ("okoru", "おこる", "オコル", "怒る", "to become enraged / scold", "Godan", "Emotions & Mind"),
    ("okosu", "おこす", "オコス", "起こす", "to awaken someone / trigger", "Godan", "Daily Actions"),
    ("oku", "おく", "オク", "置く", "to put down / set in place", "Godan", "Daily Actions"),
    ("okuru", "おくる", "オクル", "送る", "to dispatch / send mail / see off", "Godan", "Daily Actions"),
    ("okureru", "おくれる", "オクレル", "遅れる", "to lag / be late", "Ichidan", "Daily Actions"),
    ("omou", "おもう", "オモウ", "思う", "to feel / imagine / believe", "Godan", "Emotions & Mind"),
    ("omoidasu", "おもいだす", "オモイダス", "思い出す", "to recollect / remember", "Godan", "Emotions & Mind"),
    ("omoitsuku", "おもいつく", "オモイツク", "思いつく", "to hit upon an epiphany", "Godan", "Work & Study"),
    ("oriru", "おりる", "オリル", "降りる", "to step down / alight from train", "Ichidan", "Movement & Travel"),
    ("oru", "おる", "オル", "折る", "to snap / fold paper origami", "Godan", "Daily Actions"),
    ("oreru", "おれる", "オレル", "折れる", "to fracture / snap in two", "Ichidan", "Daily Actions"),
    ("osameru", "おさめる", "オサメル", "収める", "to dedicate / pay taxes / store", "Ichidan", "Work & Study"),
    ("oshiete ageru", "おしえてあげる", "オシエテアゲル", "教えてあげる", "to teach kindly", "Ichidan", "Work & Study"),
    ("oshieru", "おしえる", "オシエル", "教える", "to educate / teach / show", "Ichidan", "Work & Study"),
    ("osu", "おす", "オス", "押す", "to push forward / apply pressure", "Godan", "Daily Actions"),
    ("otozureru", "おとずれる", "オトズレル", "訪れる", "to pay a visit to / arrive", "Ichidan", "Movement & Travel"),
    ("otosu", "おとす", "オトス", "落とす", "to drop accidentally", "Godan", "Daily Actions"),
    ("owaru", "おわる", "オワル", "終わる", "to reach conclusion / end", "Godan", "Daily Actions"),
    ("oyogu", "およぐ", "オヨグ", "泳ぐ", "to swim through water", "Godan", "Movement & Travel"),

    # R
    ("renshuu suru", "れんしゅうする", "レンシュウスル", "練習する", "to drill / practice skills", "Suru Verb", "Work & Study"),
    ("renraku suru", "れんらくする", "レンラクスル", "連絡する", "to make contact / get in touch", "Suru Verb", "Social & Communication"),
    ("riyousuru", "りようする", "リヨウスル", "利用する", "to utilize / take advantage", "Suru Verb", "Daily Actions"),
    ("ryokou suru", "りょこうする", "リョコウスル", "旅行する", "to go on travels / vacation", "Suru Verb", "Movement & Travel"),
    ("ryouri suru", "りょうりする", "リョウリスル", "料理する", "to prepare culinary food", "Suru Verb", "Cooking & Dining"),
    ("ryuugaku suru", "りゅうがくする", "リュウガクスル", "留学する", "to study abroad in Japan", "Suru Verb", "Work & Study"),

    # S
    ("sagaru", "さがる", "サガル", "下がる", "to step back / drop down", "Godan", "Movement & Travel"),
    ("sageru", "さげる", "サゲル", "下げる", "to lower / hang / clear away", "Ichidan", "Daily Actions"),
    ("sagasu", "さがす", "サガス", "探す", "to search for / hunt", "Godan", "Daily Actions"),
    ("sagasu (job)", "さがす", "サガス", "捜す", "to seek missing items", "Godan", "Daily Actions"),
    ("sakebu", "さけぶ", "サケブ", "叫ぶ", "to shout loudly / yell", "Godan", "Social & Communication"),
    ("sakeru", "さける", "サケル", "避ける", "to avoid / steer clear of", "Ichidan", "Daily Actions"),
    ("saku", "さく", "サク", "咲く", "to bloom / blossom forth", "Godan", "Nature & Weather"),
    ("samageru", "さます", "サマス", "冷ます", "to let cool down", "Godan", "Cooking & Dining"),
    ("sameru", "さめる", "サメル", "冷める", "to cool off / lose warmth", "Ichidan", "Cooking & Dining"),
    ("sameru (wake)", "さめる", "サメル", "覚める", "to wake up to reality", "Ichidan", "Daily Actions"),
    ("sanpo suru", "さんぽする", "サンポスル", "散歩する", "to take an enjoyable walk", "Suru Verb", "Daily Actions"),
    ("sasaeru", "ささえる", "ササエル", "支える", "to shore up / support", "Ichidan", "Daily Actions"),
    ("sasou", "さそう", "サソウ", "誘う", "to invite along", "Godan", "Social & Communication"),
    ("sasu", "さす", "サス", "刺す", "to pierce / stab / prick", "Godan", "Daily Actions"),
    ("sasu (point)", "さす", "サス", "指す", "to indicate / point finger", "Godan", "Body & Actions"),
    ("sasu (umbrella)", "さす", "サス", "差す", "to put up an umbrella", "Godan", "Daily Actions"),
    ("sawagu", "さわぐ", "サワグ", "騒ぐ", "to make a ruckus / racket", "Godan", "Social & Communication"),
    ("sawaru", "さわる", "サワル", "触る", "to feel / lay hand upon", "Godan", "Perception & Senses"),
    ("seikatsu suru", "せいかつする", "セイカツスル", "生活する", "to lead daily life", "Suru Verb", "Daily Actions"),
    ("seikou suru", "せいこうする", "セイコウスル", "成功する", "to attain great success", "Suru Verb", "Work & Study"),
    ("seisan suru", "せいさんする", "セイサンスル", "生産する", "to manufacture / produce", "Suru Verb", "Work & Study"),
    ("sentaku suru", "せんたくする", "センタクスル", "選択する", "to select among options", "Suru Verb", "Work & Study"),
    ("sentaku suru (wash)", "せんたくする", "センタクスル", "洗濯する", "to wash laundry", "Suru Verb", "Daily Actions"),
    ("setsumei suru", "せつめいする", "セツメイスル", "説明する", "to explain clearly", "Suru Verb", "Social & Communication"),
    ("shaberu", "しゃべる", "シャベル", "喋る", "to talk casually / chatter", "Godan", "Social & Communication"),
    ("shashin o toru", "しゃしんをとる", "シャシンヲトル", "写真を撮る", "to snap a photo", "Godan", "Hobbies & Leisure"),
    ("shawaa o abiru", "しゃわーをあびる", "シャワーヲアビル", "シャワーを浴びる", "to take a shower", "Ichidan", "Daily Actions"),
    ("shikaru", "しかる", "シカル", "叱る", "to scold / reprimand", "Godan", "Social & Communication"),
    ("shimaru", "しまる", "シマル", "閉まる", "to close shut (intransitive)", "Godan", "Daily Actions"),
    ("shimeru", "しめる", "シメル", "閉める", "to shut down / close (transitive)", "Ichidan", "Daily Actions"),
    ("shimeru (tie)", "しめる", "シメル", "締める", "to fasten / tie a necktie", "Ichidan", "Daily Actions"),
    ("shinjiru", "しんじる", "シンジル", "信じる", "to believe in / trust", "Ichidan", "Emotions & Mind"),
    ("shinpai suru", "しんぱいする", "シンパイスル", "心配する", "to worry anxious thoughts", "Suru Verb", "Emotions & Mind"),
    ("shiraberu", "しらべる", "シラベル", "調べる", "to research / investigate", "Ichidan", "Work & Study"),
    ("shiru", "しる", "シル", "知る", "to know / be familiar with", "Godan", "Work & Study"),
    ("shitsumon suru", "しつもんする", "シツモンスル", "質問する", "to ask questions", "Suru Verb", "Social & Communication"),
    ("shoukai suru", "しょうかいする", "ショウカイスル", "紹介する", "to introduce someone", "Suru Verb", "Social & Communication"),
    ("shoutai suru", "しょうたいする", "ショウタイスル", "招待する", "to formally invite", "Suru Verb", "Social & Communication"),
    ("shukudai o suru", "しゅくだいをする", "シュクダイヲスル", "宿題をする", "to do homework assignments", "Suru Verb", "Work & Study"),
    ("shuppatsu suru", "しゅっぱつする", "シュッパツスル", "出発する", "to set off / depart", "Suru Verb", "Movement & Travel"),
    ("shusseki suru", "しゅっせきする", "シュッセキスル", "出席する", "to attend a ceremony", "Suru Verb", "Work & Study"),
    ("sodatsu", "そだつ", "ソダツ", "育つ", "to mature / grow up", "Godan", "Daily Actions"),
    ("sodateru", "そだてる", "ソダテル", "育てる", "to raise up / nurture", "Ichidan", "Daily Actions"),
    ("souji suru", "そうじする", "ソウジスル", "掃除する", "to tidy and clean", "Suru Verb", "Daily Actions"),
    ("soudan suru", "そうだんする", "ソウダンスル", "相談する", "to consult / ask advice", "Suru Verb", "Social & Communication"),
    ("sugosu", "すごす", "スゴス", "過ごす", "to pass time / spend days", "Godan", "Daily Actions"),
    ("sugu iku", "すぐいく", "スグイク", "すぐ行く", "to go right away", "Godan", "Movement & Travel"),
    ("suitoru", "すいとる", "スイトル", "吸い取る", "to absorb / suck up", "Godan", "Daily Actions"),
    ("suku", "すく", "スク", "空く", "to become empty / grow hungry", "Godan", "Daily Actions"),
    ("sukumu", "すくむ", "スクム", "竦む", "to freeze in fear / cower", "Godan", "Emotions & Mind"),
    ("sumu", "すむ", "スム", "住む", "to reside / live at", "Godan", "Daily Actions"),
    ("sumu (finish)", "すむ", "スム", "済む", "to conclude / finish without harm", "Godan", "Daily Actions"),
    ("suru", "する", "スル", "為る", "to perform / do", "Irregular", "Daily Actions"),
    ("suteru", "すてる", "ステル", "捨てる", "to cast away / throw out", "Ichidan", "Daily Actions"),
    ("suu", "すう", "スウ", "吸う", "to inhale / smoke / sip", "Godan", "Daily Actions"),
    ("suwaru", "すわる", "スワル", "座る", "to sit down in seat", "Godan", "Body & Actions"),

    # T
    ("taberu", "たべる", "タベル", "食べる", "to eat / consume", "Ichidan", "Cooking & Dining"),
    ("tadasu", "ただす", "タダス", "正す", "to correct mistakes", "Godan", "Work & Study"),
    ("taiketsu suru", "たいけつする", "タイケツスル", "対決する", "to confront / face off", "Suru Verb", "Work & Study"),
    ("taoreru", "たおれる", "タオレル", "倒れる", "to fall over / collapse", "Ichidan", "Movement & Travel"),
    ("taosu", "たおす", "タオス", "倒す", "to bring down / defeat", "Godan", "Daily Actions"),
    ("tanoshimu", "たのしむ", "タノシム", "楽しむ", "to enjoy / have fun", "Godan", "Hobbies & Leisure"),
    ("tanomu", "たのむ", "タノム", "頼む", "to request / commission", "Godan", "Social & Communication"),
    ("tariru", "たりる", "タリル", "足りる", "to be adequate / suffice", "Ichidan", "Daily Actions"),
    ("tasukaru", "たすかる", "タスカル", "助かる", "to be rescued / spared trouble", "Godan", "Daily Actions"),
    ("tasukeru", "たすける", "タスケル", "助ける", "to render aid / save", "Ichidan", "Social & Communication"),
    ("tatsu", "たつ", "タツ", "立つ", "to stand upright", "Godan", "Body & Actions"),
    ("tatsu (build)", "たつ", "タツ", "建つ", "to be erected / built", "Godan", "Daily Actions"),
    ("tateru", "たてる", "タテル", "建てる", "to construct a house", "Ichidan", "Work & Study"),
    ("tazuneru", "たずねる", "タズネル", "尋ねる", "to ask / inquire about", "Ichidan", "Social & Communication"),
    ("tazuneru (visit)", "たずねる", "タズネル", "訪ねる", "to call upon / visit", "Ichidan", "Movement & Travel"),
    ("tegami o dasu", "てがみをだす", "テガミヲダス", "手紙を出す", "to send a postal letter", "Godan", "Social & Communication"),
    ("tetsudau", "てつだう", "テツダウ", "手伝う", "to lend a helping hand", "Godan", "Social & Communication"),
    ("tobu", "とぶ", "トブ", "飛ぶ", "to fly through air / leap", "Godan", "Movement & Travel"),
    ("todokeru", "とどける", "トドケル", "届ける", "to deliver / hand over", "Ichidan", "Daily Actions"),
    ("todoku", "とどく", "トドク", "届く", "to reach destination / arrive", "Godan", "Daily Actions"),
    ("tokasu", "とかす", "トカス", "溶かす", "to melt / dissolve", "Godan", "Cooking & Dining"),
    ("tokeru", "とける", "トケル", "溶ける", "to thaw / liquefy", "Ichidan", "Nature & Weather"),
    ("tomaru", "とまる", "トマル", "止まる", "to come to a halt / stop", "Godan", "Movement & Travel"),
    ("tomaru (lodge)", "とまる", "トマル", "泊まる", "to stay the night at hotel", "Godan", "Movement & Travel"),
    ("tomeru", "とめる", "トメル", "止める", "to bring to a stop / park", "Ichidan", "Movement & Travel"),
    ("toru", "とる", "トル", "取る", "to grasp / take / score points", "Godan", "Daily Actions"),
    ("toru (photo)", "とる", "トル", "撮る", "to capture on camera", "Godan", "Hobbies & Leisure"),
    ("tousen suru", "とうせんする", "トウセンスル", "当選する", "to win an election / lottery", "Suru Verb", "Work & Study"),
    ("tsukau", "つかう", "ツカウ", "使う", "to utilize / spend / employ", "Godan", "Daily Actions"),
    ("tsukamaeru", "つかまえる", "ツカマエル", "捕まえる", "to catch / apprehend", "Ichidan", "Daily Actions"),
    ("tsukare-hateiru", "つかれはてる", "ツカレハテル", "疲れ果てる", "to become dead tired", "Ichidan", "Body & Actions"),
    ("tsukareru", "つかれる", "ツカレル", "疲れる", "to grow weary / fatigued", "Ichidan", "Body & Actions"),
    ("tsuku", "つく", "ツク", "着く", "to arrive at destination", "Godan", "Movement & Travel"),
    ("tsukuru", "つくる", "ツクル", "作る", "to craft / produce / cook", "Godan", "Daily Actions"),
    ("tsutaeru", "つたえる", "ツタエル", "伝える", "to convey / communicate", "Ichidan", "Social & Communication"),
    ("tsutawaru", "つたわる", "ツタワル", "伝わる", "to spread / be handed down", "Godan", "Social & Communication"),
    ("tsutomeru", "つとめる", "ツトメル", "勤める", "to be employed at", "Ichidan", "Work & Study"),
    ("tsuzukeru", "つづける", "ツヅケル", "続ける", "to continue onward", "Ichidan", "Work & Study"),
    ("tsuzuku", "つづく", "ツヅク", "続く", "to persist / keep going", "Godan", "Daily Actions"),

    # U
    ("ugoku", "うごく", "ウゴク", "動く", "to shift position / move", "Godan", "Movement & Travel"),
    ("ugokasu", "うごかす", "ウゴカス", "動かす", "to set in motion / shift", "Godan", "Daily Actions"),
    ("ukagau", "うかがう", "ウカガウ", "伺う", "to humbly inquire / visit", "Godan", "Social & Communication"),
    ("ukaru", "うかる", "ウカル", "受かる", "to pass entrance exams", "Godan", "Work & Study"),
    ("ukeru", "うける", "ウケル", "受ける", "to take exams / receive", "Ichidan", "Work & Study"),
    ("umareru", "うまれる", "ウマレル", "生まれる", "to be born into the world", "Ichidan", "People & Family"),
    ("umu", "うむ", "ウム", "産む", "to give birth / produce", "Godan", "People & Family"),
    ("unten suru", "うんてんする", "ウンテンスル", "運転する", "to drive a motorcar", "Suru Verb", "Movement & Travel"),
    ("undou suru", "うんどうする", "ウンドウスル", "運動する", "to do physical exercise", "Suru Verb", "Body & Actions"),
    ("uru", "うる", "ウル", "売る", "to vend / sell", "Godan", "Daily Actions"),
    ("urayamu", "うらやむ", "ウラヤム", "羨む", "to envy / covet", "Godan", "Emotions & Mind"),
    ("ureteiru", "うれている", "ウレテイル", "売れている", "to sell like hotcakes", "Ichidan", "Daily Actions"),
    ("ushinau", "うしなう", "ウシナウ", "失う", "to lose possession / part with", "Godan", "Daily Actions"),
    ("utau", "うたう", "ウタウ", "歌う", "to sing melodies", "Godan", "Hobbies & Leisure"),
    ("utsu", "うつ", "ウツ", "打つ", "to strike / type keys", "Godan", "Daily Actions"),
    ("utsusu", "うつす", "ウツス", "写す", "to transcribe / photograph", "Godan", "Work & Study"),

    # W
    ("wakareru", "わかれる", "ワカレル", "別れる", "to part ways / say farewell", "Ichidan", "Social & Communication"),
    ("wakaru", "わかる", "ワカル", "分かる", "to grasp meaning / understand", "Godan", "Work & Study"),
    ("wakasu", "わかす", "ワカス", "沸かす", "to boil water", "Godan", "Cooking & Dining"),
    ("waku", "わく", "ワク", "沸く", "to come to a rolling boil", "Godan", "Cooking & Dining"),
    ("warau", "わらう", "ワラウ", "笑う", "to smile / burst into laughter", "Godan", "Emotions & Mind"),
    ("waru", "わる", "ワル", "割る", "to crack / split / divide", "Godan", "Daily Actions"),
    ("wareru", "われる", "ワレル", "割れる", "to shatter into shards", "Ichidan", "Daily Actions"),
    ("watashi ni miseru", "わたしにみせる", "ワタシニミセル", "私に見せる", "to display to me", "Ichidan", "Social & Communication"),
    ("wataru", "わたる", "ワタル", "渡る", "to cross a river or road", "Godan", "Movement & Travel"),
    ("watasu", "わたす", "ワタス", "渡す", "to hand across / surrender", "Godan", "Daily Actions"),

    # Y
    ("yaburu", "やぶる", "ヤブル", "破る", "to rip paper / break promises", "Godan", "Daily Actions"),
    ("yabureru", "やぶれる", "ヤブレル", "破れる", "to get torn / break", "Ichidan", "Daily Actions"),
    ("yakeru", "やける", "ヤケル", "焼ける", "to be grilled / get sunburnt", "Ichidan", "Cooking & Dining"),
    ("yaku", "やく", "ヤク", "焼く", "to bake / roast / toast", "Godan", "Cooking & Dining"),
    ("yakusoku suru", "やくそくする", "ヤクソクスル", "約束する", "to promise / pledge", "Suru Verb", "Social & Communication"),
    ("yamu", "やむ", "ヤム", "止む", "to cease / abate (rain)", "Godan", "Nature & Weather"),
    ("yameru", "やめる", "ヤメル", "辞める", "to quit job / discontinue", "Ichidan", "Daily Actions"),
    ("yaru", "やる", "ヤル", "遣る", "to do / perform / give to animal", "Godan", "Daily Actions"),
    ("yasumu", "やすむ", "ヤスム", "休む", "to rest / take time off", "Godan", "Daily Actions"),
    ("yatoi-ireru", "やとい入れる", "ヤトイイレル", "雇い入れる", "to hire employees", "Ichidan", "Work & Study"),
    ("yobu", "よぶ", "ヨブ", "呼ぶ", "to summon / call over", "Godan", "Social & Communication"),
    ("yogosu", "よごす", "ヨゴス", "汚す", "to smudge / make dirty", "Godan", "Daily Actions"),
    ("yogoreru", "よごれる", "ヨゴレル", "汚れる", "to become stained", "Ichidan", "Daily Actions"),
    ("yomu", "よむ", "ヨム", "読む", "to read text", "Godan", "Work & Study"),
    ("yoyaku suru", "よやくする", "ヨヤクスル", "予約する", "to book a reservation", "Suru Verb", "Daily Actions"),
    ("yuderu", "ゆでる", "ユデル", "茹でる", "to boil (noodles/eggs)", "Ichidan", "Cooking & Dining"),
    ("yureru", "ゆれる", "ユレル", "揺れる", "to sway / quake", "Ichidan", "Nature & Weather"),
    ("yurusu", "ゆるす", "ユルス", "許す", "to forgive / permit", "Godan", "Social & Communication"),

    # Z
    ("zasetsu suru", "ざせつする", "ザセツスル", "挫折する", "to suffer a setback", "Suru Verb", "Work & Study"),
    ("zangyou suru", "ざんぎょうする", "ザンギョウスル", "残業する", "to work overtime", "Suru Verb", "Work & Study")
]

with open('src/data/vocab/n5_vocab.json', 'r', encoding='utf-8') as f:
    data = json.load(f)

existing = {item['romaji'].lower(): item for item in data['verbs']}

for item in raw_verbs:
    key = item[0].lower()
    if key not in existing:
        existing[key] = {
            "alphabet": item[0][0].upper(),
            "romaji": item[0],
            "hiragana": item[1],
            "katakana": item[2],
            "kanji": item[3],
            "meaning": item[4],
            "type": item[5],
            "topic": item[6]
        }

# Generate rich additional authentic JLPT verbs if needed to ensure >= 520
# Let's count current
verbs_list = list(existing.values())
print(f"Current verbs count: {len(verbs_list)}")
