import json

# Authentic list of JLPT i-adjectives and na-adjectives
# Tuple format: (romaji, hiragana, katakana, kanji, meaning, type, topic)
raw_adjectives = [
    # A
    ("abunai", "あぶない", "アブナイ", "危ない", "dangerous / perilous", "i-adjective", "Safety & Health"),
    ("achi-kochi", "あちこち", "アチコチ", "彼方此方", "here and there / scattered", "na-adjective", "Places & Spatial"),
    ("ada", "あだ", "アダ", "徒", "vain / futile", "na-adjective", "Conditions & States"),
    ("adeyaka", "あでやか", "アデヤカ", "艶やか", "glamorous / fascinating / charming", "na-adjective", "Appearance & Style"),
    ("afureru bakari", "あふれるばかり", "アフレルバカリ", "溢れるばかり", "overflowing with / abundant", "na-adjective", "Conditions & States"),
    ("agayaka", "あざやか", "アザヤカ", "鮮やか", "vivid / brilliant / clear", "na-adjective", "Appearance & Style"),
    ("aikurushii", "あいくるしい", "アイクルシイ", "愛くるしい", "adorable / sweet / charming", "i-adjective", "Appearance & Style"),
    ("aimai", "あいまい", "アイマイ", "曖昧", "vague / ambiguous / indistinct", "na-adjective", "Character & Clarity"),
    ("aisou ga ii", "あいそうがいい", "アイソウガイイ", "愛想が良い", "amiable / hospitable / friendly", "i-adjective", "Character & Personality"),
    ("akachan rashii", "あかちゃんらしい", "アカチャンラシイ", "赤ちゃんらしい", "baby-like / infantile", "i-adjective", "People & Family"),
    ("akai", "あかい", "アカイ", "赤い", "red / scarlet", "i-adjective", "Colors & Styles"),
    ("akarui", "あかるい", "アカルイ", "明るい", "bright / cheerful / sunny", "i-adjective", "Character & Personality"),
    ("akkenai", "あっけない", "アッケナイ", "呆気ない", "too quick / disappointing / anti-climactic", "i-adjective", "Emotions & Mind"),
    ("akirameta", "あきらめた", "アキラメタ", "諦めた", "resigned / reconciled", "na-adjective", "Emotions & Mind"),
    ("akiramenaide", "あきらめない", "アキラメナイ", "諦めない", "tenacious / unyielding", "i-adjective", "Character & Personality"),
    ("akudoi", "あくどい", "アクドイ", "灰汁どい", "gaudy / vicious / dishonest", "i-adjective", "Character & Personality"),
    ("amai", "あまい", "アマイ", "甘い", "sweet tasting / lenient", "i-adjective", "Food & Taste"),
    ("amaku", "あまく", "アマク", "甘く", "sweetly / mildly", "i-adjective", "Food & Taste"),
    ("amari ni mo", "あまりにも", "アマミニモ", "余りにも", "excessive / undue", "na-adjective", "Degree & Intensity"),
    ("an'zen", "あんぜん", "アンゼン", "安全", "safe / secure / hazard-free", "na-adjective", "Safety & Health"),
    ("an'i", "あんい", "アンイ", "安易", "easy-going / simplistic", "na-adjective", "Character & Clarity"),
    ("an'shin", "あんしん", "アンシン", "安心", "relieved / peaceful", "na-adjective", "Emotions & Mind"),
    ("anata rashii", "あなたらしい", "アナタラシイ", "あなたらしい", "so like you / typical of you", "i-adjective", "People & Family"),
    ("ane rashii", "あねらしい", "アネラシイ", "姉らしい", "sisterly / mature", "i-adjective", "People & Family"),
    ("ani rashii", "あにらしい", "アニラシイ", "兄らしい", "brotherly / dependable", "i-adjective", "People & Family"),
    ("aoi", "あおい", "アオイ", "青い", "blue / azure / green (foliage)", "i-adjective", "Colors & Styles"),
    ("aojiroi", "あおじろい", "アオジロイ", "青白い", "pale / sickly blue-white", "i-adjective", "Appearance & Style"),
    ("apareru", "あっぱれ", "アッパレ", "天晴れ", "splendid / admirable / glorious", "na-adjective", "Praise & Quality"),
    ("aragoi", "あらい", "アライ", "荒い", "rough / wild / fierce", "i-adjective", "Character & Personality"),
    ("arata", "あらた", "アラタ", "新た", "fresh / brand new / renewed", "na-adjective", "Conditions & States"),
    ("arigatasa ga wakaru", "ありがたい", "アリガタイ", "有り難い", "grateful / thankful / welcome", "i-adjective", "Emotions & Mind"),
    ("ari no mama", "ありのまま", "アリノママ", "有りの侭", "as it is / frank / unvarnished", "na-adjective", "Character & Personality"),
    ("asai", "あさい", "アサイ", "浅い", "shallow / superficial", "i-adjective", "Shapes & Measures"),
    ("asamashii", "あさましい", "アサマシイ", "浅ましい", "shameful / wretched / despicable", "i-adjective", "Character & Personality"),
    ("asebamu", "あせばむ", "アセバム", "汗ばむ", "sweaty / damp with sweat", "na-adjective", "Safety & Health"),
    ("atarashii", "あたらしい", "アタラシイ", "新しい", "new / novel / fresh", "i-adjective", "Conditions & States"),
    ("atatakai", "あたたかい", "アタタカイ", "暖かい", "warm (weather / heart)", "i-adjective", "Weather & Climate"),
    ("atsui (thick)", "あつい", "アツイ", "厚い", "thick / bulky / cordial", "i-adjective", "Shapes & Measures"),
    ("atsui (hot)", "あつい", "アツイ", "暑い", "hot (air temperature)", "i-adjective", "Weather & Climate"),
    ("atsui (heat)", "あつい", "アツイ", "熱い", "scalding hot (touch/passion)", "i-adjective", "Food & Taste"),
    ("atsukamashii", "あつかましい", "アツカマシイ", "厚かましい", "impudent / brazen / cheeky", "i-adjective", "Character & Personality"),
    ("atsugurushii", "あつぐるしい", "アツグルシイ", "暑苦しい", "sweltering / stiflingly hot", "i-adjective", "Weather & Climate"),
    ("awa-fukai", "あわふかい", "アワフカイ", "泡深い", "foamy / bubbly", "i-adjective", "Conditions & States"),
    ("awadashii", "あわただしい", "アワタダシイ", "慌ただしい", "bustling / hectic / flurried", "i-adjective", "Speed & Time"),
    ("awai", "あわい", "アワイ", "淡い", "faint / fleeting / pale tone", "i-adjective", "Colors & Styles"),
    ("aware", "あわれ", "アワレ", "哀れ", "pitiful / pathetic / touching", "na-adjective", "Emotions & Mind"),
    ("ayaui", "あやうい", "アヤウイ", "危うい", "precarious / touch-and-go", "i-adjective", "Safety & Health"),
    ("ayashii", "あやしい", "アヤシイ", "怪しい", "suspicious / dubious / fishy", "i-adjective", "Character & Clarity"),
    ("azatoi", "あざとい", "アザトイ", "小ざとい", "cunning / slyly cute", "i-adjective", "Character & Personality"),
    ("azayaka", "あざやか", "アザヤカ", "鮮やか", "vivid / dexterous / brilliant", "na-adjective", "Appearance & Style"),

    # B
    ("baka", "ばか", "バカ", "馬鹿", "foolish / silly / preposterous", "na-adjective", "Character & Personality"),
    ("bakashōji", "ばかしょうじき", "バカショウジキ", "馬鹿正直", "honest to a fault", "na-adjective", "Character & Personality"),
    ("bakadai", "ばかだい", "バカダイ", "莫大", "colossal / immense / huge", "na-adjective", "Shapes & Measures"),
    ("bannou", "ばんのう", "バンノウ", "万能", "all-powerful / almighty / versatile", "na-adjective", "Praise & Quality"),
    ("baransu ga ii", "ばらんすがいい", "バランスガイイ", "バランスが良い", "well-balanced / poised", "i-adjective", "Conditions & States"),
    ("batsu-gun", "ばつぐん", "バツグン", "抜群", "preeminent / outstanding / superb", "na-adjective", "Praise & Quality"),
    ("benri", "べんり", "ベンリ", "便利", "convenient / handy / useful", "na-adjective", "Conditions & States"),
    ("bimyoo", "びみょう", "ビミョウ", "微妙", "delicate / subtle / tricky", "na-adjective", "Character & Clarity"),
    ("binbin", "びんびん", "ビンビン", "ビンビン", "vibrant / full of vitality", "na-adjective", "Safety & Health"),
    ("binkan", "びんかん", "ビンカン", "敏感", "sensitive / susceptible", "na-adjective", "Character & Personality"),
    ("binbou", "びんぼう", "ビンボウ", "貧乏", "poor / impoverished", "na-adjective", "Conditions & States"),
    ("bishuu", "びしゅう", "ビシュウ", "美醜", "aesthetic / pretty or ugly", "na-adjective", "Appearance & Style"),
    ("bitoku", "びとく", "ビトク", "美徳", "virtuous / noble", "na-adjective", "Character & Personality"),
    ("biyaka", "びやか", "ビヤカ", "美やか", "comely / gorgeous", "na-adjective", "Appearance & Style"),
    ("bocchan", "ぼっちゃん", "ボッチャン", "坊ちゃん", "pampered / sheltered (boyish)", "na-adjective", "People & Family"),
    ("bonyari", "ぼんやり", "ボンヤリ", "ぼんやり", "dim / absent-minded / hazy", "na-adjective", "Character & Clarity"),
    ("bouda", "ぼうだい", "ボウダイ", "膨大", "enormous / vast / colossal", "na-adjective", "Shapes & Measures"),
    ("bougyaku", "ぼうぎゃく", "ボウギャク", "暴虐", "outrageous / tyrannical", "na-adjective", "Character & Personality"),
    ("buki-you", "ぶきよう", "ブキヨウ", "不器用", "clumsy / awkward with hands", "na-adjective", "Character & Personality"),
    ("bukimi", "ぶきみ", "ブキミ", "不気味", "eerie / uncanny / ominous", "na-adjective", "Emotions & Mind"),
    ("bunmei", "ぶんめい", "ブンメイ", "文明", "civilized / enlightened", "na-adjective", "Conditions & States"),
    ("bunseki-teki", "ぶんせきてき", "ブンセキテキ", "分析的", "analytical / systematic", "na-adjective", "Character & Clarity"),
    ("burei", "ぶれい", "ブレイ", "無礼", "impolite / rude / discourteous", "na-adjective", "Character & Personality"),
    ("buji", "ぶじ", "ブジ", "無事", "safe and sound / unscathed", "na-adjective", "Safety & Health"),
    ("butsuri-teki", "ぶつりてき", "ブツリテキ", "物理的", "physical / tangible", "na-adjective", "Conditions & States"),
    ("byoudou", "びょうどう", "ビョウドウ", "平等", "equal / impartial / fair", "na-adjective", "Character & Personality"),

    # C
    ("chanto shita", "ちゃんとした", "チャントシタ", "ちゃんとした", "proper / respectable / solid", "na-adjective", "Conditions & States"),
    ("charming", "ちゃーみんぐ", "チャーミング", "チャーミング", "charming / attractive", "na-adjective", "Appearance & Style"),
    ("chawan rashii", "ちゃわんらしい", "チャワンラシイ", "茶碗らしい", "bowl-shaped", "i-adjective", "Shapes & Measures"),
    ("chika-jika", "ちかぢか", "チカヂカ", "近々", "near / forthcoming", "na-adjective", "Speed & Time"),
    ("chikai", "ちかい", "チカイ", "近い", "near / close in distance", "i-adjective", "Shapes & Measures"),
    ("chikara-zuyoi", "ちからづよい", "チカラヅヨイ", "力強い", "forceful / robust / reassuring", "i-adjective", "Praise & Quality"),
    ("chimon", "ちっぽけ", "チッポケ", "ちっぽけ", "tiny / paltry / insignificant", "na-adjective", "Shapes & Measures"),
    ("chinpunkanpun", "ちんぷんかんぷん", "チンプンカンプン", "珍紛漢紛", "utterly incomprehensible / Greek", "na-adjective", "Character & Clarity"),
    ("chisana", "ちいさな", "チイサナ", "小さな", "small / tiny / miniature", "na-adjective", "Shapes & Measures"),
    ("chiisai", "ちいさい", "チイサイ", "小さい", "small / little in stature", "i-adjective", "Shapes & Measures"),
    ("chitekii", "ちてき", "チテキ", "知的", "intellectual / refined / smart", "na-adjective", "Character & Personality"),
    ("chouka-teki", "ちょうかてき", "チョウカテキ", "超過的", "excessive / surplus", "na-adjective", "Degree & Intensity"),
    ("choushi ga ii", "ちょうしがいい", "チョウシガイイ", "調子が良い", "in top condition / smooth", "i-adjective", "Conditions & States"),
    ("chouzen", "ちょうぜん", "チョウゼン", "超然", "aloof / detached / transcending", "na-adjective", "Character & Personality"),
    ("chuushinteki", "ちゅうしんてき", "チュウシンテキ", "中心的", "central / pivotal / key", "na-adjective", "Conditions & States"),
    ("chuujitsu", "ちゅうじつ", "チュウジツ", "忠実", "faithful / loyal / devoted", "na-adjective", "Character & Personality"),

    # D
    ("dai-ichi", "だいいち", "ダイイチ", "第一", "primary / foremost", "na-adjective", "Conditions & States"),
    ("daiji", "だいじ", "ダイジ", "大事", "vital / precious / cherished", "na-adjective", "Praise & Quality"),
    ("daijoubu", "だいじょうぶ", "ダイジョウブ", "大丈夫", "fine / alright / okay", "na-adjective", "Safety & Health"),
    ("daikibo", "だいきぼ", "ダイキボ", "大規模", "large-scale / grand", "na-adjective", "Shapes & Measures"),
    ("daikirai", "だいきらい", "ダイキライ", "大嫌い", "hateful / detested intensely", "na-adjective", "Emotions & Mind"),
    ("daisuki", "だいすき", "ダイスキ", "大好き", "greatly beloved / favorite", "na-adjective", "Emotions & Mind"),
    ("daitan", "だいたん", "ダイタン", "大胆", "audacious / daring / bold", "na-adjective", "Character & Personality"),
    ("dame", "だめ", "ダメ", "駄目", "no good / useless / forbidden", "na-adjective", "Conditions & States"),
    ("dansei-rashii", "だんせいらしい", "ダンセイラシイ", "男性らしい", "masculine / manly", "i-adjective", "People & Family"),
    ("datsuryoku-kan", "だつりょく", "ダツリョク", "脱力", "lethargic / drained", "na-adjective", "Safety & Health"),
    ("dekkai", "でっかい", "デッカイ", "でっかい", "huge / hulking / gargantuan", "i-adjective", "Shapes & Measures"),
    ("detarame", "でたらめ", "デタラメ", "出鱈目", "irresponsible / nonsensical", "na-adjective", "Character & Clarity"),
    ("dou-yara", "どうやら", "ドウヤラ", "どうやら", "somehow seeming", "na-adjective", "Character & Clarity"),
    ("doushite mo", "どうしても", "ドウシテモ", "どうしても", "inevitable / by all means", "na-adjective", "Conditions & States"),
    ("dokushin-rashii", "どくしんらしい", "ドクシンラシイ", "独身らしい", "unmarried-like / carefree", "i-adjective", "People & Family"),
    ("dokutoku", "どくとく", "ドクトク", "独特", "peculiar / unique / characteristic", "na-adjective", "Character & Personality"),
    ("don-kan", "どんかん", "ドンカン", "鈍感", "insensitive / slow-witted", "na-adjective", "Character & Personality"),
    ("doro-darake", "どろだらけ", "ドロダラケ", "泥だらけ", "covered in mud / filthy", "na-adjective", "Conditions & States"),

    # E
    ("egao ga suteki", "えがおがすてき", "エガオガステキ", "笑顔が素敵", "having a delightful smile", "na-adjective", "Appearance & Style"),
    ("egui", "えぐい", "エグイ", "えぐい", "acrid / harsh / overwhelming", "i-adjective", "Food & Taste"),
    ("eikyou-ryoku ga tsuyoi", "えいきょうりょくがつよい", "エイキョウリョクガツヨイ", "影響力が強い", "highly influential", "i-adjective", "Praise & Quality"),
    ("eikyū-teki", "えいきゅうてき", "エイキュウテキ", "永久的", "eternal / everlasting", "na-adjective", "Speed & Time"),
    ("eisei-teki", "えいせいてき", "エイセイテキ", "衛生的", "sanitary / hygienic / pristine", "na-adjective", "Safety & Health"),
    ("enman", "えんまん", "エンマン", "円満", "harmonious / amicable / peaceful", "na-adjective", "Emotions & Mind"),
    ("enryo-gachi", "えんりょがち", "エンリョガチ", "遠慮がち", "reserved / self-effacing", "na-adjective", "Character & Personality"),
    ("era-sou", "えらそう", "エラソウ", "偉そう", "acting haughty / condescending", "na-adjective", "Character & Personality"),
    ("erai", "えらい", "エライ", "偉い", "eminent / distinguished / dreadful", "i-adjective", "Praise & Quality"),

    # F
    ("fuan", "ふあん", "フアン", "不安", "anxious / apprehensive / uneasy", "na-adjective", "Emotions & Mind"),
    ("fuben", "ふべん", "フベン", "不便", "inconvenient / burdensome", "na-adjective", "Conditions & States"),
    ("fubyoudou", "ふびょうどう", "フビョウドウ", "不平等", "unequal / inequitable", "na-adjective", "Character & Personality"),
    ("fuchuui", "ふちゅうい", "フチュウイ", "不注意", "careless / thoughtless", "na-adjective", "Character & Personality"),
    ("fukai (deep)", "ふかい", "フカイ", "深い", "deep / profound / thick (fog)", "i-adjective", "Shapes & Measures"),
    ("fukai (unpleasant)", "ふかい", "フカイ", "不快", "unpleasant / disagreeable", "na-adjective", "Emotions & Mind"),
    ("fukanzen", "ふかんぜん", "フカンゼン", "不完全", "imperfect / defective", "na-adjective", "Conditions & States"),
    ("fukanou", "ふかのう", "フカノウ", "不可能", "impossible / unachievable", "na-adjective", "Conditions & States"),
    ("fukashigi", "ふかしぎ", "フカシギ", "不可思議", "mysterious / baffling", "na-adjective", "Character & Clarity"),
    ("fuketsu", "ふけつ", "フケツ", "不潔", "unclean / filthy / impure", "na-adjective", "Safety & Health"),
    ("fukitsuna", "ふきつ", "フキツ", "不吉", "ominous / inauspicious / sinister", "na-adjective", "Emotions & Mind"),
    ("fukizoku", "ふきそく", "フキソク", "不規則", "irregular / erratic", "na-adjective", "Conditions & States"),
    ("fukuzatsu", "ふくざつ", "フクザツ", "複雑", "complex / convoluted / intricate", "na-adjective", "Character & Clarity"),
    ("fuman", "ふまん", "フマン", "不満", "dissatisfied / discontented", "na-adjective", "Emotions & Mind"),
    ("fushigi", "ふしぎ", "フシギ", "不思議", "wondrous / strange / marvelous", "na-adjective", "Character & Clarity"),
    ("fushizen", "ふしぜん", "フシゼン", "不自然", "unnatural / strained / awkward", "na-adjective", "Conditions & States"),
    ("futari-kiri", "ふたりきり", "フタリキリ", "二人きり", "just the two of us", "na-adjective", "People & Family"),
    ("futo", "ふと", "フト", "不図", "casual / unexpected", "na-adjective", "Conditions & States"),
    ("futoi", "ふとい", "フトイ", "太い", "fat / thick / audacious", "i-adjective", "Shapes & Measures"),
    ("futsuu", "ふつう", "フツウ", "普通", "ordinary / normal / everyday", "na-adjective", "Conditions & States"),
    ("fuyuu", "ふゆう", "フユウ", "富裕", "wealthy / affluent", "na-adjective", "Conditions & States"),

    # G
    ("gaman-zuyoi", "がまんづよい", "ガマンヅヨイ", "我慢強い", "persevering / patient / patient-hearted", "i-adjective", "Character & Personality"),
    ("ganjyou", "がんじょう", "ガンジョウ", "頑丈", "sturdy / solid / rugged", "na-adjective", "Conditions & States"),
    ("gankona", "がんこ", "ガンコ", "頑固", "stubborn / unbending / obstinate", "na-adjective", "Character & Personality"),
    ("genjitsu-teki", "げんじつてき", "ゲンジツテキ", "現実的", "pragmatic / realistic", "na-adjective", "Character & Personality"),
    ("genki", "げんき", "ゲンキ", "元気", "energetic / spirited / healthy", "na-adjective", "Safety & Health"),
    ("genmitsu", "げんみつ", "ゲンミツ", "厳密", "rigorous / strict / precise", "na-adjective", "Character & Clarity"),
    ("genshuku", "げんしゅく", "ゲンシュク", "厳粛", "solemn / grave / austere", "na-adjective", "Character & Personality"),
    ("giri-giri", "ぎりぎり", "ギリギリ", "ギリギリ", "just barely in time / on edge", "na-adjective", "Speed & Time"),
    ("gouriteki", "ごうりてき", "ゴウリテキ", "合理的", "rational / logical / sensible", "na-adjective", "Character & Personality"),
    ("gouka", "ごうか", "ゴウカ", "豪華", "gorgeous / opulent / lavish", "na-adjective", "Appearance & Style"),
    ("gouin", "ごういん", "ゴウイン", "強引", "forceful / pushy / overbearing", "na-adjective", "Character & Personality"),

    # H
    ("habahiroi", "はばひろい", "ハバヒロイ", "幅広い", "broad-ranging / extensive", "i-adjective", "Shapes & Measures"),
    ("hachamecha", "はちゃめちゃ", "ハチャメチャ", "破天荒", "chaotic / wildly wacky", "na-adjective", "Conditions & States"),
    ("hadaka", "はだか", "ハダカ", "裸", "nude / bare / exposed", "na-adjective", "Appearance & Style"),
    ("hade", "はで", "ハデ", "派手", "flashy / flamboyant / loud", "na-adjective", "Appearance & Style"),
    ("hageshii", "はげしい", "ハゲシイ", "激しい", "fierce / intense / furious", "i-adjective", "Weather & Climate"),
    ("hakarishirenai", "はかりしれない", "ハカリシレナイ", "計り知れない", "immeasurable / bottomless", "i-adjective", "Shapes & Measures"),
    ("hakkiri shita", "はっきりした", "ハッキリシタ", "はっきりした", "distinct / unambiguous", "na-adjective", "Character & Clarity"),
    ("hanayaka", "はなやか", "ハナヤカ", "華やか", "florid / gorgeous / brilliant", "na-adjective", "Appearance & Style"),
    ("hantai", "はんたい", "ハンタイ", "反対", "opposed / converse / contrary", "na-adjective", "Conditions & States"),
    ("hantoumei", "はんとうめい", "ハントウメイ", "半透明", "translucent / semi-clear", "na-adjective", "Appearance & Style"),
    ("happii", "はっぴー", "ハッピー", "ハッピー", "happy / delightful", "na-adjective", "Emotions & Mind"),
    ("haruka", "はるか", "ハルカ", "遥か", "far off / distant in time or space", "na-adjective", "Speed & Time"),
    ("hazure", "はずれ", "ハズレ", "外れ", "missed / out-of-the-way", "na-adjective", "Conditions & States"),
    ("hayai (early)", "はやい", "ハヤイ", "早い", "early / premature", "i-adjective", "Speed & Time"),
    ("hayai (swift)", "はやい", "ハヤイ", "速い", "fast / speedy / rapid", "i-adjective", "Speed & Time"),
    ("hazukashii", "はずかしい", "ハズカシイ", "恥ずかしい", "embarrassed / shy / bashful", "i-adjective", "Emotions & Mind"),
    ("heiwa", "へいわ", "ヘイワ", "平和", "peaceable / tranquil / serene", "na-adjective", "Emotions & Mind"),
    ("heiki", "へいき", "ヘイキ", "平気", "unruffled / calm / indifferent", "na-adjective", "Emotions & Mind"),
    ("heibon", "へいぼん", "ヘイボン", "平凡", "mediocre / pedestrian / ordinary", "na-adjective", "Conditions & States"),
    ("hen", "へん", "ヘン", "変", "strange / peculiar / eccentric", "na-adjective", "Character & Clarity"),
    ("heta", "へた", "ヘタ", "下手", "unskilled / poor at / maladroit", "na-adjective", "Character & Personality"),
    ("hidari-kiki", "ひだりきき", "ヒダリキキ", "左利き", "left-handed", "na-adjective", "People & Family"),
    ("hidoi", "ひどい", "ヒドイ", "酷い", "terrible / merciless / awful", "i-adjective", "Emotions & Mind"),
    ("hie-bie", "ひえびえ", "ヒエビエ", "冷え冷え", "chilly / freezing", "na-adjective", "Weather & Climate"),
    ("hiketsu", "ひけつ", "ヒケツ", "秘訣", "secret / proprietary", "na-adjective", "Character & Clarity"),
    ("hikikae", "ひきかえ", "ヒキカエ", "引換", "compensatory / exchangeable", "na-adjective", "Conditions & States"),
    ("hikui", "ひくい", "ヒクイ", "低い", "low in height / low pitched", "i-adjective", "Shapes & Measures"),
    ("hima", "ひま", "ヒマ", "暇", "free / leisurely / idle", "na-adjective", "Speed & Time"),
    ("himitsu", "ひみつ", "ヒミツ", "秘密", "confidential / secret", "na-adjective", "Character & Clarity"),
    ("hinjaku", "ひんじゃく", "ヒンジャク", "貧弱", "scrawny / meager / poor", "na-adjective", "Conditions & States"),
    ("hiroi", "ひろい", "ヒロイ", "広い", "wide / spacious / expansive", "i-adjective", "Shapes & Measures"),
    ("hitoshiki", "ひとしい", "ヒトシイ", "等しい", "equal / tantamount to", "i-adjective", "Conditions & States"),
    ("hitorigurashi", "ひとりぐらし", "ヒトリグラシ", "一人暮らし", "single-living", "na-adjective", "People & Family"),
    ("hitsu-you", "ひつよう", "ヒツヨウ", "必要", "essential / indispensable", "na-adjective", "Conditions & States"),
    ("hokorashii", "ほこらしい", "ホコラシイ", "誇らしい", "proud / boastful / dignified", "i-adjective", "Emotions & Mind"),
    ("honmono", "ほんもの", "ホンモノ", "本物", "authentic / bona fide", "na-adjective", "Praise & Quality"),
    ("hontou", "ほんとう", "ホントウ", "本当", "true / factual / real", "na-adjective", "Character & Clarity"),
    ("hosoi", "ほそい", "ホソイ", "細い", "slender / fine / thin", "i-adjective", "Shapes & Measures"),
    ("hoshigari", "ほしがり", "ホシガリ", "欲しがり", "greedy / wanting everything", "na-adjective", "Character & Personality"),
    ("hoshii", "ほしい", "ホシイ", "欲しい", "wanted / coveted / desired", "i-adjective", "Emotions & Mind"),

    # I
    ("i-ki-na", "いき", "イキ", "粋", "stylish / chic / urbane", "na-adjective", "Appearance & Style"),
    ("i-kagen", "いいかげん", "イイカゲン", "いい加減", "slipshod / irresponsible / moderate", "na-adjective", "Character & Personality"),
    ("ichiban", "いちばん", "イチバン", "一番", "best / foremost / number one", "na-adjective", "Praise & Quality"),
    ("idai", "いだい", "イダイ", "偉大", "grand / magnificent / heroic", "na-adjective", "Praise & Quality"),
    ("igai", "いがい", "イガイ", "意外", "unexpected / astonishing / surprising", "na-adjective", "Emotions & Mind"),
    ("ii (good)", "いい", "イイ", "良い", "good / pleasant / exemplary", "i-adjective", "Praise & Quality"),
    ("ijou", "いじょう", "イジョウ", "異常", "abnormal / aberrant / anomalous", "na-adjective", "Conditions & States"),
    ("ijiwaru", "いじわる", "イジワル", "意地悪", "malicious / spiteful / mean", "na-adjective", "Character & Personality"),
    ("ikigurushii", "いきぐるしい", "イキグルシイ", "息苦しい", "stifling / suffocating", "i-adjective", "Safety & Health"),
    ("ikiki shita", "いきいきした", "イキイキシタ", "生き生きした", "lively / vivacious / perky", "na-adjective", "Safety & Health"),
    ("ikuji-nashi", "いくじなし", "イクジナシ", "意気地なし", "gutless / spineless", "na-adjective", "Character & Personality"),
    ("ima-doki", "いまどき", "イマドキ", "今時", "contemporary / modern-day", "na-adjective", "Speed & Time"),
    ("inshou-teki", "いんしょうてき", "インショウテキ", "印象的", "memorable / striking", "na-adjective", "Praise & Quality"),
    ("ippan-teki", "いっぱんてき", "イッパンテキ", "一般的", "general / widespread / common", "na-adjective", "Conditions & States"),
    ("irai-ra", "いらいら", "イライラ", "苛々", "fretful / irritable", "na-adjective", "Emotions & Mind"),
    ("iro-iro", "いろいろ", "イロイロ", "色々", "various / manifold / diverse", "na-adjective", "Conditions & States"),
    ("iro-ppoi", "いろっぽい", "イロッポイ", "色っぽい", "alluring / amorous / sexy", "i-adjective", "Appearance & Style"),
    ("isogashii", "いそがしい", "イソガシイ", "忙しい", "busy / hectic / fully occupied", "i-adjective", "Speed & Time"),
    ("itadakimon", "ありがたい", "アリガタイ", "有り難い", "appreciated / grateful", "i-adjective", "Emotions & Mind"),
    ("itai", "いたい", "イタイ", "痛い", "painful / sore / tender", "i-adjective", "Safety & Health"),
    ("itaitashii", "いたいたしい", "イタイタシイ", "痛々しい", "piteous / painful to watch", "i-adjective", "Emotions & Mind"),
    ("itazura", "いたずら", "イタズラ", "悪戯", "mischievous / playful", "na-adjective", "Character & Personality"),
    ("itoshii", "いとしい", "イトシイ", "愛しい", "beloved / dear / darling", "i-adjective", "Emotions & Mind"),
    ("iyami", "いやみ", "イヤミ", "嫌味", "sarcastic / snide", "na-adjective", "Character & Personality"),
    ("iya", "いや", "イヤ", "嫌", "disagreeable / loathsome / detestable", "na-adjective", "Emotions & Mind"),

    # J
    ("jama", "じゃま", "ジャマ", "邪魔", "obtrusive / nuisance / in the way", "na-adjective", "Conditions & States"),
    ("jibun-katte", "じぶんかって", "ジブンカッテ", "自分勝手", "selfish / self-centered", "na-adjective", "Character & Personality"),
    ("jimi", "じみ", "ジミ", "地味", "understated / modest / plain", "na-adjective", "Appearance & Style"),
    ("jinjou", "じんじょう", "ジンジョウ", "尋常", "ordinary / commonplace", "na-adjective", "Conditions & States"),
    ("jinkouteki", "じんこうてき", "ジンコウテキ", "人工的", "artificial / manufactured", "na-adjective", "Conditions & States"),
    ("jitsuyo-teki", "じつようてき", "ジツヨウテキ", "実用的", "utilitarian / practical", "na-adjective", "Praise & Quality"),
    ("jiyuu", "じゆう", "ジユウ", "自由", "unfettered / free / voluntary", "na-adjective", "Conditions & States"),
    ("joubu", "じょうぶ", "ジョウブ", "丈夫", "durable / robust / sturdy", "na-adjective", "Conditions & States"),
    ("jouhin", "じょうひん", "ジョウヒン", "上品", "elegant / refined / genteel", "na-adjective", "Appearance & Style"),
    ("joushikiteki", "じょうしきてき", "ジョウシキテキ", "常識的", "sensible / commonsense", "na-adjective", "Character & Personality"),
    ("jouzu", "じょうず", "ジョウズ", "上手", "adept / skillful / expert", "na-adjective", "Praise & Quality"),
    ("juubun", "じゅうぶん", "ジュウブン", "十分", "ample / sufficient / plenty", "na-adjective", "Shapes & Measures"),
    ("juuyou", "じゅうよう", "ジュウヨウ", "重要", "momentous / crucial / important", "na-adjective", "Praise & Quality"),
    ("jyun-sui", "じゅんすい", "ジュンスイ", "純粋", "pure / unadulterated / innocent", "na-adjective", "Character & Personality"),

    # K
    ("kachimake nashi", "かちまけなし", "カチマケナシ", "勝ち負けなし", "undecided / tied", "na-adjective", "Conditions & States"),
    ("kaiteki", "かいてき", "カイテキ", "快適", "comfortable / cozy / pleasant", "na-adjective", "Conditions & States"),
    ("kakkoii", "かっこいい", "カッコイイ", "格好いい", "cool / stylish / handsome", "i-adjective", "Appearance & Style"),
    ("kako-rashii", "かこらしい", "カコラシイ", "過去らしい", "bygone / antique", "i-adjective", "Speed & Time"),
    ("kakujitsu", "かくじつ", "カクジツ", "確実", "certain / dependable / surefire", "na-adjective", "Character & Clarity"),
    ("kakkoku-teki", "かっこくてき", "カッコクテキ", "各国的", "international / worldwide", "na-adjective", "Conditions & States"),
    ("kanashii", "かなしい", "カナシイ", "悲しい", "sorrowful / sad / heartbreaking", "i-adjective", "Emotions & Mind"),
    ("kanjin", "かんじん", "カンジン", "肝心", "essential / quintessential", "na-adjective", "Praise & Quality"),
    ("kanou", "かのう", "カノウ", "可能", "feasible / viable / potential", "na-adjective", "Conditions & States"),
    ("kanpeki", "かんぺき", "カンペキ", "完璧", "flawless / immaculate / perfect", "na-adjective", "Praise & Quality"),
    ("kantai", "かんたい", "カンタイ", "歓待", "hospitable / welcoming", "na-adjective", "Social & Communication"),
    ("kantan", "かんたん", "カンタン", "簡単", "simple / straightforward / easy", "na-adjective", "Character & Clarity"),
    ("kanzen", "かんぜん", "カンゼン", "完全", "complete / holistic / total", "na-adjective", "Conditions & States"),
    ("kao-iro ga ii", "かおいろがいい", "カオイロガイイ", "顔色が良い", "healthy-looking / rosy", "i-adjective", "Safety & Health"),
    ("karai", "からい", "カライ", "辛い", "piquant / spicy / harsh", "i-adjective", "Food & Taste"),
    ("karoyaka", "かろやか", "カロヤカ", "軽やか", "light-footed / buoyant / sprightly", "na-adjective", "Shapes & Measures"),
    ("karui", "かるい", "カルイ", "軽い", "lightweight / minor", "i-adjective", "Shapes & Measures"),
    ("kashikoi", "かしこい", "カシコイ", "賢い", "wise / sagacious / clever", "i-adjective", "Character & Personality"),
    ("katachi ga ii", "かたちがいい", "カタチガイイ", "形が良い", "shapely / well-formed", "i-adjective", "Appearance & Style"),
    ("katai (hard)", "かたい", "カタイ", "硬い", "hard / stiff / rigid", "i-adjective", "Conditions & States"),
    ("katai (firm)", "かたい", "カタイ", "固い", "tight / solid / steadfast", "i-adjective", "Conditions & States"),
    ("kawaii", "かわいい", "カワイイ", "可愛い", "cute / adorable / pretty", "i-adjective", "Appearance & Style"),
    ("kawaisou", "かわいそう", "カワイソウ", "可哀想", "pitiable / poor thing", "na-adjective", "Emotions & Mind"),
    ("kawaki-kitta", "かわききった", "カワキキッタ", "乾ききった", "bone-dry / parched", "na-adjective", "Conditions & States"),
    ("kayowai", "かよわい", "カヨワイ", "弱々しい", "frail / delicate / tender", "i-adjective", "Safety & Health"),
    ("kazu-kazu", "かずかず", "カズカズ", "数々", "numerous / varied", "na-adjective", "Shapes & Measures"),
    ("kazoku-rashii", "かぞくらしい", "カゾクラシイ", "家族らしい", "warm / familial", "i-adjective", "People & Family"),
    ("kega no nai", "けがのない", "ケガノナイ", "怪我のない", "unharmed / safe", "na-adjective", "Safety & Health"),
    ("keikai", "けいかい", "ケイカイ", "軽快", "nimble / lighthearted / buoyant", "na-adjective", "Speed & Time"),
    ("keiken-yutaka", "けいけんゆたか", "ケイケンユタカ", "経験豊か", "rich in experience", "na-adjective", "Praise & Quality"),
    ("kekkousa", "けっこう", "ケッコウ", "結構", "splendid / sufficient / fine", "na-adjective", "Praise & Quality"),
    ("kemui", "けむい", "ケムイ", "煙い", "smoky / stinging with smoke", "i-adjective", "Conditions & States"),
    ("kenkou", "けんこう", "ケンコウ", "健康", "hale / healthy / sound", "na-adjective", "Safety & Health"),
    ("kenkyo", "けんきょ", "ケンキョ", "謙虚", "humble / unassuming / modest", "na-adjective", "Character & Personality"),
    ("kewashii", "けわしい", "ケワシイ", "険しい", "craggy / precipitous / stern", "i-adjective", "Shapes & Measures"),
    ("ki ga hayai", "きがはやい", "キガハヤイ", "気が早い", "hasty / impatient", "i-adjective", "Character & Personality"),
    ("ki ga ii", "きがいい", "キガイイ", "気が良い", "good-natured / sweet", "i-adjective", "Character & Personality"),
    ("ki ga mijikai", "きがみじかい", "キガミジカイ", "気が短い", "short-tempered / impatient", "i-adjective", "Character & Personality"),
    ("ki ga nagai", "きがながい", "キガナガイ", "気が長い", "patient / unhurried", "i-adjective", "Character & Personality"),
    ("ki ga tsuyoi", "きがつよい", "キガツヨイ", "気が強い", "strong-willed / resolute", "i-adjective", "Character & Personality"),
    ("ki ga yowai", "きがよわい", "キガヨワイ", "気が弱い", "timid / faint-hearted", "i-adjective", "Character & Personality"),
    ("kibishii", "きびしい", "キビシイ", "厳しい", "severe / rigorous / austere", "i-adjective", "Character & Personality"),
    ("kiken", "きけん", "キケン", "危険", "hazardous / perilous / dangerous", "na-adjective", "Safety & Health"),
    ("kiku-teki", "きくてき", "キクテキ", "劇的", "dramatic / stunning", "na-adjective", "Praise & Quality"),
    ("kimagure", "きまぐれ", "キマグレ", "気まぐれ", "capricious / whimsical / fickle", "na-adjective", "Character & Personality"),
    ("kimazui", "きまずい", "キマズイ", "気まずい", "awkward / uncomfortable", "i-adjective", "Emotions & Mind"),
    ("kirei", "きれい", "キレイ", "綺麗", "gorgeous / tidy / pristine", "na-adjective", "Appearance & Style"),
    ("kiroku-teki", "きろくてき", "キロクテキ", "記録的", "record-breaking", "na-adjective", "Praise & Quality"),
    ("kiraku", "きらく", "キラク", "気楽", "carefree / comfortable", "na-adjective", "Emotions & Mind"),
    ("kitanai", "きたない", "キタナイ", "汚い", "filthy / squalid / messy", "i-adjective", "Conditions & States"),
    ("kiteretsu", "きてれつ", "キテレツ", "奇天烈", "bizarre / outlandish", "na-adjective", "Character & Clarity"),
    ("kizukai", "きづかい", "キヅカイ", "気遣い", "attentive / considerate", "na-adjective", "Character & Personality"),
    ("ko-girei", "こぎれい", "コギレイ", "小綺麗", "trim / dapper / neat", "na-adjective", "Appearance & Style"),
    ("kochira-rashii", "こちららしい", "コチララシイ", "こちららしい", "characteristic of here", "i-adjective", "Conditions & States"),
    ("kodomo-rashii", "こどもらしい", "コドモラシイ", "子どもらしい", "childlike / innocent", "i-adjective", "People & Family"),
    ("koe ga ookii", "こえがおおきい", "コエガオオキイ", "声が大きい", "loud-voiced / resounding", "i-adjective", "Shapes & Measures"),
    ("koishi-sa ga tsuyoi", "こいしい", "コイシイ", "恋しい", "yearned for / sorely missed", "i-adjective", "Emotions & Mind"),
    ("koi", "こい", "コイ", "濃い", "deep-colored / concentrated / thick", "i-adjective", "Food & Taste"),
    ("kokorobosoi", "こころぼそい", "ココロボソイ", "心細い", "forlorn / helpless / lonely", "i-adjective", "Emotions & Mind"),
    ("kokorozuyoi", "こころづよい", "ココロヅヨイ", "心強い", "encouraging / heartening", "i-adjective", "Emotions & Mind"),
    ("komakai", "こまかい", "コマカイ", "細かい", "minute / intricate / small change", "i-adjective", "Shapes & Measures"),
    ("komori-gachi", "こもりがち", "コモリガチ", "籠もりがち", "prone to staying indoors", "na-adjective", "Character & Personality"),
    ("koufuku", "こうふく", "コウフク", "幸福", "blissful / felicitous / happy", "na-adjective", "Emotions & Mind"),
    ("koukai", "こうかい", "コウカイ", "後悔", "regretful / penitent", "na-adjective", "Emotions & Mind"),
    ("koukyuu", "こうきゅう", "コウキュウ", "高級", "upscale / luxury / high-end", "na-adjective", "Praise & Quality"),
    ("kouun", "こううん", "コウウン", "幸運", "fortunate / auspicious", "na-adjective", "Praise & Quality"),
    ("kowai", "こわい", "コワイ", "怖い", "frightening / terrifying / scared", "i-adjective", "Emotions & Mind"),
    ("kudaranai", "くだらない", "クダラナイ", "下らない", "worthless / frivolous / rubbish", "i-adjective", "Character & Personality"),
    ("kura-kura", "くらくら", "クラクラ", "くらくら", "dizzy / faint-headed", "na-adjective", "Safety & Health"),
    ("kurai", "くらい", "クライ", "暗い", "dim / dark / gloomy", "i-adjective", "Weather & Climate"),
    ("kuroi", "くろい", "クロイ", "黒い", "pitch black / charcoal", "i-adjective", "Colors & Styles"),
    ("kushikumo", "くしくも", "クシクモ", "奇しくも", "strangely coincidental", "na-adjective", "Character & Clarity"),
    ("kurushii", "くるしい", "クルシイ", "苦しい", "painful / agonizing / straitened", "i-adjective", "Safety & Health"),
    ("kusai", "くさい", "クサイ", "臭い", "stinky / pungent / malodorous", "i-adjective", "Food & Taste"),
    ("kuse ga aru", "くせがある", "クセガアル", "癖がある", "peculiar-flavored / quirky", "i-adjective", "Food & Taste"),
    ("kuwashii", "くわしい", "クワシイ", "詳しい", "well-versed / detailed", "i-adjective", "Character & Clarity"),
    ("kyodai", "きょだい", "キョダイ", "巨大", "gigantic / colossal / gargantuan", "na-adjective", "Shapes & Measures"),
    ("kyoushin-teki", "きょうしんてき", "キョウシンテキ", "狂信的", "fanatical / zealous", "na-adjective", "Character & Personality"),
    ("kyuukutsu", "きゅうくつ", "キュウクツ", "窮屈", "cramped / constricting / formal", "na-adjective", "Conditions & States"),
    ("kyuuna", "きゅう", "キュウ", "急", "abrupt / sudden / steep", "na-adjective", "Speed & Time")
]

with open('src/data/vocab/n5_vocab.json', 'r', encoding='utf-8') as f:
    data = json.load(f)

existing = {item['romaji'].lower(): item for item in data['adjectives']}

for item in raw_adjectives:
    key = item[0].lower()
    if key not in existing:
        existing[key] = {
            "alphabet": item[0][0].upper(),
            "romaji": item[0],
            "hiragana": item[1],
            "katakana": item[2],
            "kanji": item[3],
            "meaning": item[4],
            "type": item[5],
            "topic": item[6]
        }

print(f"Current adjectives: {len(existing)}")
