import json

raw_adverbs_part2 = [
    # M
    ("maa-maa", "まあまあ", "マアマア", "まあまあ", "so-so / reasonably / now, now", "Degree & Extent"),
    ("maboroshi no gotoku", "まぼろしのごとく", "マボロシノゴトク", "幻の如く", "like a phantasm", "Manner & State"),
    ("mada", "まだ", "マダ", "未だ", "still / yet (with negative)", "Time & Sequence"),
    ("mada-mada", "まだまだ", "マダマダ", "まだまだ", "still a long way to go / not yet", "Degree & Extent"),
    ("maeshite", "まえもって", "マエモッテ", "前もって", "in advance / beforehand", "Time & Sequence"),
    ("magomago", "まごまご", "マゴマゴ", "まごまご", "flustered / in confusion", "Onomatopoeia & Mimetic"),
    ("maiasa", "まいあさ", "マイアサ", "毎朝", "every single morning", "Frequency & Habit"),
    ("maiban", "まいばん", "マイバン", "毎晩", "every night", "Frequency & Habit"),
    ("mainichi", "まいにち", "マイニチ", "毎日", "every day without fail", "Frequency & Habit"),
    ("maishuu", "まいしゅう", "マイシュウ", "毎週", "weekly / every week", "Frequency & Habit"),
    ("maitsuki", "まいつき", "マイツキ", "毎月", "monthly / every month", "Frequency & Habit"),
    ("maitoshi", "まいとし", "マイトシ", "毎年", "annually / every year", "Frequency & Habit"),
    ("majime ni", "まじめに", "マジメニ", "真面目に", "seriously / in earnest", "Manner & State"),
    ("maji de", "まじで", "マジデ", "マジで", "seriously? / for real", "Degree & Extent"),
    ("makoto ni", "まことに", "マコトニ", "誠に", "truly / sincerely / deeply", "Degree & Extent"),
    ("mame ni", "まめに", "マメニ", "忠実に", "diligently / frequently", "Frequency & Habit"),
    ("mannaka ni", "まんなかに", "マンナカニ", "真ん中に", "right in the center", "Places & Spatial"),
    ("maru de", "まるで", "マルデ", "丸で", "as if / just like / completely", "Degree & Extent"),
    ("masa ni", "まさに", "マサニ", "正に", "exactly / right at this moment / indeed", "Degree & Extent"),
    ("masaka", "まさか", "マサカ", "まさか", "by no means / don't tell me", "Condition & Logic"),
    ("masu-masu", "ますます", "マスマス", "益々", "increasingly / more and more", "Degree & Extent"),
    ("massaki ni", "まっさきに", "マッサキニ", "真っ先に", "first and foremost / head of line", "Time & Sequence"),
    ("masshiro ni", "まっしろに", "マッシロニ", "真っ白に", "turned purely white", "Manner & State"),
    ("massugu ni", "まっすぐに", "マッスグニ", "真っ直ぐに", "straight ahead / directly", "Manner & State"),
    ("mattaku", "まったく", "マッタク", "全く", "entirely / really / good grief", "Degree & Extent"),
    ("mazumazu", "まずまず", "マズマズ", "先ず先ず", "tolerably well / passable", "Degree & Extent"),
    ("mazu", "まず", "マズ", "先ず", "first of all / to begin with", "Time & Sequence"),
    ("mearashiku", "めあたらしく", "メアタラシク", "目新しく", "novel-looking", "Manner & State"),
    ("mechamecha", "めちゃくちゃ", "メチャクチャ", "滅茶苦茶", "chaotic / insanely / absurdly", "Degree & Extent"),
    ("medatou to", "めだとうと", "メダトウト", "目立とうと", "striving to stand out", "Manner & State"),
    ("megakete", "めがけて", "メガケテ", "目掛けて", "aiming directly at", "Places & Spatial"),
    ("mettani", "めったに", "メッタニ", "滅多に", "rarely / seldom (with negative)", "Frequency & Habit"),
    ("mieru youni", "みえるように", "ミエルヨウニ", "見えるように", "so that it can be seen", "Manner & State"),
    ("migi e hidari e", "みぎえひだりえ", "ミギエヒダリエ", "右へ左へ", "to the right and left", "Places & Spatial"),
    ("mijika ni", "みぢかに", "ミヂカニ", "身近に", "close at hand / familiar", "Places & Spatial"),
    ("miman de", "みまんで", "ミマンデ", "未満で", "under / less than", "Degree & Extent"),
    ("mina de", "みんなで", "ミンナデ", "皆で", "all together / collectively", "Manner & State"),
    ("miren rashiku", "みれんらしく", "ミレンラシク", "未練らしく", "with lingering regret", "Manner & State"),
    ("miri-miri", "みりみり", "ミリミリ", "ミリミリ", "creaking under pressure", "Onomatopoeia & Mimetic"),
    ("miso-miso", "みそみそ", "ミソミソ", "みそみそ", "sizzling broth", "Onomatopoeia & Mimetic"),
    ("mita koto nai hodo", "みたことないほど", "ミタコトナイホド", "見たことないほど", "unprecedentedly", "Degree & Extent"),
    ("mitame yori", "みた目より", "ミタメヨリ", "見た目より", "more than it looks", "Degree & Extent"),
    ("mochiron", "もちろん", "モチロン", "勿論", "of course / needless to say", "Condition & Logic"),
    ("mokusoku de", "もくそくで", "モクソクデ", "目測で", "by eye-measurement", "Manner & State"),
    ("moshikashite", "もしかして", "モシカシテ", "若しかして", "perhaps / by any chance", "Condition & Logic"),
    ("moshikashitara", "もしかしたら", "モシカシタラ", "若しかしたら", "possibly / peradventure", "Condition & Logic"),
    ("moshimo", "もしも", "モシモ", "若しも", "if ever / supposing that", "Condition & Logic"),
    ("motto", "もっと", "モット", "もっと", "even more / further", "Degree & Extent"),
    ("motto-mo", "もっとも", "モットモ", "最も", "most / extremely / although", "Degree & Extent"),
    ("moya-moya", "もやもや", "モヤモヤ", "もやもや", "foggy / hazy feelings", "Onomatopoeia & Mimetic"),
    ("muda ni", "むだに", "ムダニ", "無駄に", "in vain / needlessly", "Manner & State"),
    ("mugon de", "むごんで", "ムゴンデ", "無言で", "silently / mutely", "Manner & State"),
    ("mukashi kara", "むかしから", "ムカシカラ", "昔から", "since of old / traditionally", "Time & Sequence"),
    ("mukyuu ni", "むきゅうに", "ムキュウニ", "無休に", "without days off", "Frequency & Habit"),
    ("mura naku", "むらなく", "ムラナク", "斑なく", "evenly / uniformly", "Manner & State"),
    ("muri ni", "むりに", "ムリニ", "無理に", "forcibly / against one's will", "Manner & State"),

    # N
    ("nado", "など", "ナド", "等", "and so forth / such as", "Condition & Logic"),
    ("nagara", "ながら", "ナガラ", "ながら", "while / simultaneously", "Time & Sequence"),
    ("nagaku", "ながく", "ナガク", "長く", "for a long duration", "Time & Sequence"),
    ("nakanaka", "なかなか", "ナカナカ", "中々", "quite / considerably / easily not", "Degree & Extent"),
    ("naku-naku", "なくなぐ", "ナクナグ", "泣く泣く", "tearfully / sorrowfully", "Manner & State"),
    ("nan de mo", "なんでも", "ナンデモ", "何でも", "anything / they say that", "Condition & Logic"),
    ("nan to naku", "なんとなく", "ナントナク", "何となく", "for some vague reason", "Condition & Logic"),
    ("nan to itte mo", "なんといっても", "ナントイッテモ", "何と言っても", "undeniably / above all", "Degree & Extent"),
    ("nanto", "なんと", "ナント", "何と", "what! / how very!", "Degree & Extent"),
    ("naosara", "なおさら", "ナオサラ", "尚更", "all the more / still less", "Degree & Extent"),
    ("nanto-ka", "なんとか", "ナントカ", "何とか", "somehow or other / manage to", "Manner & State"),
    ("narubeku", "なるべく", "ナルベク", "成るべく", "as much as possible / preferably", "Degree & Extent"),
    ("naruhodo", "なるほど", "ナルホド", "成る程", "indeed / I see / quite so", "Condition & Logic"),
    ("nazo-meite", "なぞめいて", "ナゾメイテ", "謎めいて", "enigmatically", "Manner & State"),
    ("ne-gashira ni", "ねがしらに", "ネガシラニ", "根頭に", "at the root", "Places & Spatial"),
    ("neba-neba", "ねばねば", "ネバネバ", "ねばねば", "sticky / slimy (natto)", "Onomatopoeia & Mimetic"),
    ("nemu-souni", "ねむそうに", "ネムソウニ", "眠そうに", "sleepily", "Manner & State"),
    ("nesshin ni", "ねっしんに", "ネッシンニ", "熱心に", "enthusiastically / eagerly", "Manner & State"),
    ("niko-niko", "にこにこ", "ニコニコ", "にこにこ", "smiling beamingly", "Onomatopoeia & Mimetic"),
    ("nita-nita", "にたにた", "ニタニタ", "にたにた", "smirking slyly", "Onomatopoeia & Mimetic"),
    ("nito-nito", "にとにと", "ニトニト", "にとにと", "grinning broadly", "Onomatopoeia & Mimetic"),
    ("niwa-ka ni", "にわかに", "ニワカニ", "俄に", "suddenly / abruptly", "Time & Sequence"),
    ("nochi-hodo", "のちほど", "ノチホド", "後ほど", "later on / shortly after", "Time & Sequence"),
    ("nokorazu", "のこらず", "ノコラズ", "残らず", "without exception / every last bit", "Degree & Extent"),
    ("nonbiri to", "のんびりと", "ノンビリト", "のんびりと", "leisurely / carefree", "Onomatopoeia & Mimetic"),
    ("noro-noro to", "のろのろと", "ノロノロト", "のろのろと", "sluggishly / crawling along", "Onomatopoeia & Mimetic"),

    # O
    ("odayaka ni", "おだやかに", "オダヤカニ", "穏やかに", "calmly / gently", "Manner & State"),
    ("ogi-nai nagara", "おぎないながら", "オギナイナガラ", "補いながら", "while supplementing", "Manner & State"),
    ("oikakete", "おいかけて", "オイカケテ", "追いかけて", "in pursuit of", "Manner & State"),
    ("oishi-sou ni", "おいしそうに", "オイシソウニ", "美味しそうに", "relishingly / with gusto", "Manner & State"),
    ("omoi-kiri", "おもいきり", "オモイキリ", "思い切り", "to one's heart's content / daringly", "Degree & Extent"),
    ("omo-omo-shiku", "おもおもしく", "オモオモシク", "重々しく", "solemnly / ponderously", "Manner & State"),
    ("omomuki fukaku", "おもむきふかく", "オモムキフカク", "趣深く", "tastefully / with refined charm", "Manner & State"),
    ("omoni", "おもに", "オモニ", "主に", "chiefly / primarily / mainly", "Degree & Extent"),
    ("omowazu", "おもわず", "オモワズ", "思わず", "spontaneously / involuntarily", "Manner & State"),
    ("onaji-ku", "おなじく", "オナジク", "同じく", "similarly / likewise", "Condition & Logic"),
    ("onaji youni", "おなじように", "オナジヨウニ", "同じように", "in the same manner", "Manner & State"),
    ("onozukara", "おのずから", "オノズカラ", "自ずから", "of its own accord / naturally", "Condition & Logic"),
    ("oobosa ni", "おおきく", "オオキク", "大きく", "vastly / on a big scale", "Degree & Extent"),
    ("oogata ni", "おおがたに", "オオガタニ", "大型に", "substantially", "Degree & Extent"),
    ("oo-haba ni", "おおはばに", "オオハバニ", "大幅に", "drastically / by a large margin", "Degree & Extent"),
    ("ooi ni", "おおいに", "オオイニ", "大いに", "greatly / heartily / considerably", "Degree & Extent"),
    ("oo-kata", "おおかた", "オオカタ", "大方", "mostly / largely / probably", "Degree & Extent"),
    ("ooyoso", "おおよそ", "オオヨソ", "大凡", "roughly / approximately", "Degree & Extent"),
    ("orifushi", "おりふし", "オリフシ", "折節", "occasionally / on seasonal occasions", "Frequency & Habit"),
    ("orikomi-zumi de", "おりこみずみで", "オリコミズミデ", "織り込み済みで", "factored in already", "Condition & Logic"),
    ("osoraku", "おそらく", "オソラク", "恐らく", "in all likelihood / probably", "Condition & Logic"),
    ("osoro-osoro", "おそるおそる", "オソルオソル", "恐る恐る", "timidly / nervously", "Onomatopoeia & Mimetic"),
    ("osoku tomo", "おそくとも", "オソクトモ", "遅くとも", "at the very latest", "Time & Sequence"),
    ("oto mo naku", "おともなく", "オトモナク", "音もなく", "noiselessly / stealthily", "Manner & State"),

    # P
    ("pachi-pachi", "ぱちぱち", "パチパチ", "ぱちぱち", "clapping hands / crackling sparks", "Onomatopoeia & Mimetic"),
    ("pakuri to", "ぱくりと", "パクリト", "ぱくりと", "gobbling up in one bite", "Onomatopoeia & Mimetic"),
    ("para-para", "ぱらぱら", "パラパラ", "ぱらぱら", "flipping pages / light rain patter", "Onomatopoeia & Mimetic"),
    ("pasa-pasa", "ぱさぱさ", "パサパサ", "ぱさぱさ", "dry and crumbly", "Onomatopoeia & Mimetic"),
    ("pashari to", "ぱしゃりと", "パシャリト", "ぱしゃりと", "splashing lightly", "Onomatopoeia & Mimetic"),
    ("pata-pata", "ぱたぱた", "パタパタ", "ぱたぱた", "flapping wings / pattering footsteps", "Onomatopoeia & Mimetic"),
    ("pattari to", "ぱったりと", "パッタリト", "ぱったりと", "ceasing abruptly / bumping into", "Onomatopoeia & Mimetic"),
    ("patto", "ぱっと", "パット", "ぱっと", "flashing into sight / suddenly blooming", "Onomatopoeia & Mimetic"),
    ("pera-pera", "ぺらぺら", "ペラペラ", "ペラペラ", "fluently speaking / thin paper", "Onomatopoeia & Mimetic"),
    ("peko-peko", "ぺこぺこ", "ペコペコ", "ペコペコ", "starving hungry / bowing repeatedly", "Onomatopoeia & Mimetic"),
    ("petari to", "ぺたりと", "ペタリト", "ぺたりと", "sitting flat / sticking adhesive", "Onomatopoeia & Mimetic"),
    ("pika-pika", "ぴかぴか", "ピカピカ", "ピカピカ", "sparkling bright / shiny brand new", "Onomatopoeia & Mimetic"),
    ("piku-piku", "ぴくぴく", "ピクピク", "ぴくぴく", "twitching muscles", "Onomatopoeia & Mimetic"),
    ("pin-pin", "ぴんぴん", "ピンピン", "ぴんぴん", "lively and spry / hale and hearty", "Onomatopoeia & Mimetic"),
    ("pishari to", "ぴしゃりと", "ピシャリト", "ぴしゃりと", "slamming shut / cutting short", "Onomatopoeia & Mimetic"),
    ("pita-ri to", "ぴたりと", "ピタリト", "ぴたりと", "coming to a dead halt / fitting snugly", "Onomatopoeia & Mimetic"),
    ("pocha-pocha", "ぽちゃぽちゃ", "ポチャポチャ", "ぽちゃぽちゃ", "plump and chubby / splashing", "Onomatopoeia & Mimetic"),
    ("poka-poka", "ぽかぽか", "ポカポカ", "ぽかぽか", "pleasantly warm all over", "Onomatopoeia & Mimetic"),
    ("poki-poki", "ぽきぽき", "ポキポキ", "ぽきぽき", "snapping cleanly into pieces", "Onomatopoeia & Mimetic"),
    ("poro-poro", "ぽろぽろ", "ポロポロ", "ぽろぽろ", "tears trickling down / crumbling", "Onomatopoeia & Mimetic"),
    ("potsu-potsu", "ぽつぽつ", "ポツポツ", "ぽつぽつ", "raindrops starting / bit by bit", "Onomatopoeia & Mimetic"),
    ("pun-pun", "ぷんぷん", "プンプン", "ぷんぷん", "fuming with anger / strong odor", "Onomatopoeia & Mimetic"),
    ("puyo-puyo", "ぷよぷよ", "プヨプヨ", "ぷよぷよ", "squishy and gelatinous", "Onomatopoeia & Mimetic"),

    # R
    ("raku ni", "らくに", "ラクニ", "楽に", "with complete ease / comfortably", "Manner & State"),
    ("reisei ni", "れいせいに", "レイセイニ", "冷静に", "calmly and dispassionately", "Manner & State"),
    ("reigi-tadashiku", "れいぎただしく", "レイギタダシク", "礼儀正しく", "politely / mannerly", "Manner & State"),
    ("rippani", "りっぱに", "リッパニ", "立派に", "splendidly / creditably", "Manner & State"),
    ("ronri-teki ni", "ろんりてきに", "ロンリテキニ", "論理的に", "logically", "Manner & State"),

    # S
    ("sa", "さあ", "サア", "さあ", "come now / well then", "Condition & Logic"),
    ("saikin", "さいきん", "サイキン", "最近", "recently / in modern times", "Time & Sequence"),
    ("saisho ni", "さいしょに", "サイショニ", "最初に", "at the inception / first", "Time & Sequence"),
    ("saigo ni", "さいごに", "サイゴニ", "最後に", "finally / at long last", "Time & Sequence"),
    ("sappari", "さっぱり", "サッパリ", "さっぱり", "refreshingly / not at all (neg)", "Degree & Extent"),
    ("sara-ni", "さらに", "サラニ", "更に", "furthermore / all the more", "Degree & Extent"),
    ("sara-sara", "さらさら", "サラサラ", "さらさら", "smoothly flowing / rustling silk", "Onomatopoeia & Mimetic"),
    ("sassato", "さっさと", "サッサト", "さっさと", "promptly / without delay", "Speed & Time"),
    ("sate", "さて", "サテ", "さて", "well now / now then", "Condition & Logic"),
    ("sasuga ni", "さすがに", "サスガニ", "流石に", "as one would expect / naturally", "Degree & Extent"),
    ("seikaku ni", "せいかくに", "セイカクニ", "正確に", "accurately / punctually", "Manner & State"),
    ("seizei", "せいぜい", "セイゼイ", "精々", "at the very utmost / at best", "Degree & Extent"),
    ("sekkaku", "せっかく", "セッカク", "折角", "with special effort / precious chance", "Condition & Logic"),
    ("shibashiba", "しばしば", "シバシバ", "屡々", "repeatedly / time and again", "Frequency & Habit"),
    ("shikashi", "しかし", "シカシ", "しかし", "however / yet", "Condition & Logic"),
    ("shikkari", "しっかり", "シッカリ", "しっかり", "firmly / stoutly / reliably", "Manner & State"),
    ("shizen to", "しぜんと", "シゼント", "自然と", "spontaneously / naturally", "Manner & State"),
    ("shizuka ni", "しずかに", "シズカニ", "静かに", "quietly / softly", "Manner & State"),
    ("shikatanaku", "しかたなく", "シカタナク", "仕方なく", "helplessly / out of necessity", "Condition & Logic"),
    ("shinjirarenai hodo", "しんじられないほど", "シンジラレナイホド", "信じられないほど", "unbelievably / incredibly", "Degree & Extent"),
    ("shou-shou", "しょうしょう", "ショウショウ", "少々", "just a moment / a small bit", "Degree & Extent"),
    ("shoujiki ni", "しょうじきに", "ショウジキニ", "正直に", "frankly / honestly", "Manner & State"),
    ("sokkuri", "そっくり", "ソックリ", "そっくり", "looking exactly like / entirely", "Degree & Extent"),
    ("subete", "すべて", "スベテ", "全て", "entirely / all without omission", "Degree & Extent"),
    ("sugu ni", "すぐに", "スグニ", "直ぐに", "immediately / right away", "Time & Sequence"),
    ("sugoku", "すごく", "スゴク", "凄く", "awesomely / immensely / super", "Degree & Extent"),
    ("sukoshi", "すこし", "スコシ", "少し", "a small amount / a little", "Degree & Extent"),
    ("sukoshi-zuts", "すこしずつ", "スコシズツ", "少しずつ", "little by little / gradually", "Degree & Extent"),
    ("sukkari", "すっかり", "スッカリ", "すっかり", "completely / totally / thoroughly", "Degree & Extent"),
    ("sutto", "すっと", "スット", "すっと", "smoothly gliding / feeling relieved", "Onomatopoeia & Mimetic"),
    ("sumiyaka ni", "すみやかに", "スミヤカニ", "速やかに", "swiftly / expeditiously", "Speed & Time"),
    ("sunawachi", "すなわち", "スナワチ", "即ち", "in other words / namely", "Condition & Logic"),
    ("surasura", "すらすら", "スラスラ", "すらすら", "fluently / with effortless ease", "Onomatopoeia & Mimetic"),
    ("suru-suru", "するする", "スルスル", "するする", "gliding smoothly", "Onomatopoeia & Mimetic"),

    # T
    ("tabi-tabi", "たびたび", "タビタビ", "度々", "frequently / repeatedly", "Frequency & Habit"),
    ("tabun", "たぶん", "タブン", "多分", "presumably / likely / perhaps", "Condition & Logic"),
    ("tada", "ただ", "タダ", "只", "merely / only / free of charge", "Degree & Extent"),
    ("tadaima", "ただいま", "タダイマ", "只今", "right now / just this moment", "Time & Sequence"),
    ("tadashiku", "ただしく", "タダシク", "正しく", "correctly / righteously", "Manner & State"),
    ("taihen", "たいへん", "タイヘン", "大変", "greatly / enormously", "Degree & Extent"),
    ("taigai", "たいがい", "タイガイ", "大概", "generally / mostly / in moderation", "Degree & Extent"),
    ("taitei", "たいてい", "タイテイ", "大抵", "ordinarily / usually / mostly", "Frequency & Habit"),
    ("taki ni watatte", "たきにわたって", "タキニワタッテ", "多岐にわたって", "across multifaceted fields", "Places & Spatial"),
    ("takusan", "たくさん", "タクサン", "沢山", "in large quantities / plenty", "Degree & Extent"),
    ("tama ni", "たまに", "タマニ", "偶に", "once in a while / occasionally", "Frequency & Habit"),
    ("tamatama", "たまたま", "タマタマ", "偶々", "by fluke / by coincidence", "Condition & Logic"),
    ("tannin ni", "たんに", "タンニ", "単に", "simply / solely / merely", "Degree & Extent"),
    ("tashika ni", "たしかに", "タシカニ", "確かに", "surely / undeniably / certainly", "Condition & Logic"),
    ("tatoeba", "たとえば", "タトエバ", "例えば", "for instance / for example", "Condition & Logic"),
    ("tatoe", "たとえ", "タトエ", "例え", "even supposing that", "Condition & Logic"),
    ("tayumu koto naku", "たゆむことなく", "タユムコトナク", "弛むことなく", "relentlessly / untiringly", "Frequency & Habit"),
    ("teinei ni", "ていねいに", "テイネイニ", "丁寧に", "courteously / scrupulously", "Manner & State"),
    ("tekitoo ni", "てきとうに", "テキトウニ", "適当に", "suitably / or haphazardly", "Manner & State"),
    ("ten-ten to", "てんてんと", "テンテント", "点々と", "dotted here and there", "Places & Spatial"),
    ("tereteru", "てれて", "テレテ", "照れて", "bashfully / shyly", "Manner & State"),
    ("tobikiri", "とびきり", "トビキリ", "飛び切り", "extraordinary / top-notch", "Degree & Extent"),
    ("toki-doki", "ときどき", "トキドキ", "時々", "from time to time / sometimes", "Frequency & Habit"),
    ("toki ni", "ときに", "トキニ", "時に", "at times / by the by", "Time & Sequence"),
    ("toku ni", "とくに", "トクニ", "特に", "especially / extraordinarily", "Degree & Extent"),
    ("tokku ni", "とっくに", "トックニ", "疾っくに", "long since / long ago", "Time & Sequence"),
    ("tomo ni", "ともに", "トモニ", "共に", "jointly / together with", "Manner & State"),
    ("tonikaku", "とにかく", "トニカク", "兎に角", "anyway / in any case", "Condition & Logic"),
    ("totemo", "とても", "トテモ", "とても", "very / immensely / by no means (neg)", "Degree & Extent"),
    ("totsuzen", "とつぜん", "トツゼン", "突然", "suddenly / without warning", "Time & Sequence"),
    ("tsugi ni", "つぎに", "ツギニ", "次に", "next / following on", "Time & Sequence"),
    ("tsui ni", "ついに", "ツイニ", "遂に", "at long last / finally", "Time & Sequence"),
    ("tsui", "つい", "ツイ", "つい", "inadvertently / just a little while ago", "Time & Sequence"),
    ("tsukuzuku", "つくづく", "ツクヅク", "熟々", "deeply / keenly / thoroughly", "Degree & Extent"),
    ("tsumari", "つまり", "ツマリ", "詰まり", "in short / that is to say", "Condition & Logic"),
    ("tsune ni", "つねに", "ツネニ", "常に", "consistently / permanently", "Frequency & Habit"),
    ("tsuyoku", "つよく", "ツヨク", "強く", "strongly / vigorously", "Degree & Extent"),

    # U
    ("uchuu-teki ni", "うちゅうてきに", "ウチュウテキニ", "宇宙的に", "cosmically", "Degree & Extent"),
    ("ukkari", "うっかり", "ウッカリ", "うっかり", "carelessly / inadvertently", "Manner & State"),
    ("un to", "うんと", "ウント", "うんと", "a whole lot / with all one's might", "Degree & Extent"),
    ("ura-hara ni", "うらはらに", "ウラハラニ", "裏腹に", "contrary to / inversely", "Condition & Logic"),
    ("ureshi-sou ni", "うれしそうに", "ウレシソウニ", "嬉しそうに", "joyfully / delightedly", "Manner & State"),
    ("uro-uro", "うろうろ", "ウロウロ", "うろうろ", "loitering / wandering aimlessly", "Onomatopoeia & Mimetic"),
    ("utsura-utsura", "うつらうつら", "ウツラウツラ", "うつらうつら", "nodding off drowsily", "Onomatopoeia & Mimetic"),
    ("uyamuya ni", "うやむやに", "ウヤムヤニ", "有耶無耶に", "leaving things muddled", "Manner & State"),

    # W
    ("waga-mama ni", "わがままに", "ワガママニ", "我儘に", "selfishly", "Manner & State"),
    ("waku-waku", "わくわく", "ワクワク", "わくわく", "trembling with thrilling excitement", "Onomatopoeia & Mimetic"),
    ("wari to", "わりと", "ワリト", "割と", "comparatively / relatively", "Degree & Extent"),
    ("waza to", "わざと", "ワザト", "態と", "deliberately / on purpose", "Manner & State"),
    ("waza-waza", "わざわざ", "ワザワザ", "態々", "taking the trouble to", "Manner & State"),
    ("wazuka ni", "わずかに", "ワズカニ", "僅かに", "only slightly / narrowly", "Degree & Extent"),

    # Y
    ("yahari", "やはり", "ヤハリ", "やはり", "as anticipated / after all", "Condition & Logic"),
    ("yappari", "やっぱり", "ヤッパリ", "やっぱり", "after all (casual yahari)", "Condition & Logic"),
    ("yagate", "やがて", "ヤガテ", "軈て", "before long / presently", "Time & Sequence"),
    ("yakedo suru hodo", "やけどするほど", "ヤケドスルホド", "火傷するほど", "scaldingly hot", "Degree & Extent"),
    ("yami-kumo ni", "やみくもに", "ヤミクモニ", "闇雲に", "recklessly / blindly", "Manner & State"),
    ("yara-yara", "やらやら", "ヤラヤラ", "やらやら", "and what not", "Condition & Logic"),
    ("yasashiku", "やさしく", "ヤサシク", "優しく", "tenderly / gently", "Manner & State"),
    ("yasuku", "やすく", "ヤスク", "安く", "cheaply", "Manner & State"),
    ("yatto", "やっと", "ヤット", "やっと", "at long last / barely", "Time & Sequence"),
    ("yo-hodo", "よほど", "ヨホド", "余程", "greatly / to a large degree", "Degree & Extent"),
    ("yohaku naku", "よはくなく", "ヨハクナク", "余白なく", "without margin", "Degree & Extent"),
    ("yoi-yoi to", "よいよいと", "ヨイヨイト", "よいよいと", "steadily pacing", "Manner & State"),
    ("yoku", "よく", "ヨク", "良く", "well / skillfully / frequently", "Degree & Extent"),
    ("yoku-yoku", "よくよく", "ヨクヨク", "熟々", "very carefully / exceedingly", "Degree & Extent"),
    ("yokei ni", "よけいに", "ヨケイニ", "余計に", "superfluously / all the more", "Degree & Extent"),
    ("yori", "より", "ヨリ", "より", "even more / compared to", "Degree & Extent"),
    ("yorokonde", "よろこんで", "ヨロコンデ", "喜んで", "with great pleasure / gladly", "Manner & State"),
    ("yosou ijou ni", "よそういじょうに", "ヨソウイジョウニ", "予想以上に", "beyond expectations", "Degree & Extent"),
    ("yowaku", "よわく", "ヨワク", "弱く", "faintly / feebly", "Degree & Extent"),
    ("yukuri to", "ゆっくりと", "ユックリト", "ゆっくりと", "unhurriedly / leisurely", "Speed & Time"),
    ("yukkuri", "ゆっくり", "ユックリ", "ゆっくり", "slowly / taking one's ease", "Speed & Time"),
    ("yume-yume", "ゆめゆめ", "ユメユメ", "努々", "by no means (with neg)", "Degree & Extent"),
    ("yuruyaka ni", "ゆるやかに", "ユルヤカニ", "緩やかに", "gently sloping / leniently", "Manner & State"),

    # Z
    ("zatto", "ざっと", "ザット", "ざっと", "roughly / skimmingly / rushing water", "Degree & Extent"),
    ("zaa-zaa", "ざあざあ", "ザアザア", "ざあざあ", "pouring down rain", "Onomatopoeia & Mimetic"),
    ("zei-zei", "ぜいぜい", "ゼイゼイ", "ぜいぜい", "wheezing / gasping for air", "Onomatopoeia & Mimetic"),
    ("zen-zen", "ぜんぜん", "ゼンゼン", "全然", "not in the least (neg) / totally", "Degree & Extent"),
    ("zenbu", "ぜんぶ", "ゼンブ", "全部", "in its entirety / all", "Degree & Extent"),
    ("zenkoku-teki ni", "ぜんこくてきに", "ゼンコクテキニ", "全国的に", "nationwide", "Places & Spatial"),
    ("zenryoku de", "ぜんりょくで", "ゼンリョクデ", "全力で", "with all one's might", "Manner & State"),
    ("zettai ni", "ぜったいに", "ゼッタイニ", "絶対に", "unconditionally / definitely", "Condition & Logic"),
    ("zoku-zoku", "ぞくぞく", "ゾクゾク", "ぞくぞく", "shivering with chills or thrill", "Onomatopoeia & Mimetic"),
    ("zuibun", "ずいぶん", "ズイブン", "随分", "considerably / remarkably", "Degree & Extent"),
    ("zuke-zuke", "ずけずけ", "ズケズケ", "ずけずけ", "bluntly / tactlessly", "Onomatopoeia & Mimetic"),
    ("zura-ri to", "ずらりと", "ズラリト", "ずらりと", "lined up in a long row", "Onomatopoeia & Mimetic"),
    ("zutto", "ずっと", "ズット", "ずっと", "all along / by far / way more", "Degree & Extent")
]

import sys
sys.path.append('scripts')
import expand_adverbs

all_adv = dict(expand_adverbs.existing)

for item in raw_adverbs_part2:
    key = item[0].lower()
    if key not in all_adv:
        all_adv[key] = {
            "alphabet": item[0][0].upper(),
            "romaji": item[0],
            "hiragana": item[1],
            "katakana": item[2],
            "kanji": item[3],
            "meaning": item[4],
            "topic": item[5]
        }

final_adverbs = list(all_adv.values())
final_adverbs.sort(key=lambda x: x['romaji'].lower())

with open('src/data/vocab/n5_vocab.json', 'r', encoding='utf-8') as f:
    data = json.load(f)

data['adverbs'] = final_adverbs

with open('src/data/vocab/n5_vocab.json', 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print(f"Total Adverbs now saved in n5_vocab.json: {len(data['adverbs'])}")
