import json

# Authentic Japanese adverbs (Fukushi) across categories
raw_adverbs = [
    # A
    ("aete", "あえて", "アエテ", "敢えて", "daringly / venture to", "Manner & State"),
    ("aikawarazu", "あいかわらず", "アイカワラズ", "相変わらず", "as ever / as usual", "Frequency & Habit"),
    ("aimai ni", "あいまいに", "アイマイニ", "曖昧に", "ambiguously / vaguely", "Manner & State"),
    ("ainiku", "あいにく", "アイニク", "生憎", "unfortunately / as luck would have it", "Condition & Logic"),
    ("akarasama ni", "あからさまに", "アカラサマニ", "露骨に", "openly / blatantly", "Manner & State"),
    ("akiramete", "あきらめて", "アキラメテ", "諦めて", "in resignation", "Manner & State"),
    ("amaku", "あまく", "アマク", "甘く", "leniently / sweetly", "Manner & State"),
    ("amari", "あまり", "アマリ", "余り", "not very / not much (with neg)", "Degree & Extent"),
    ("an'i ni", "あんいに", "アンイニ", "安易に", "casually / simplistic manner", "Manner & State"),
    ("an'zen ni", "あんぜんに", "アンゼンニ", "安全に", "safely / without harm", "Manner & State"),
    ("annano ni", "あんなに", "アンナニ", "あんなに", "to that extent / so very", "Degree & Extent"),
    ("ano toki", "あのとき", "アノトキ", "あの時", "at that time / back then", "Time & Sequence"),
    ("anmari", "あんまり", "アンマリ", "あんまり", "not really / excessively", "Degree & Extent"),
    ("arakajime", "あらかじめ", "アラカジメ", "予め", "beforehand / in advance", "Time & Sequence"),
    ("arata ni", "あらたに", "アラタニ", "新たに", "anew / afresh", "Time & Sequence"),
    ("aratamete", "あらためて", "アラタメテ", "改めて", "once again / on another occasion", "Time & Sequence"),
    ("ari-ari to", "ありありと", "アリアリト", "ありありと", "vividly / distinctly", "Manner & State"),
    ("asase de", "あさせで", "アサセデ", "浅瀬で", "in the shallows", "Places & Spatial"),
    ("ase-daku de", "あせだくで", "アセダクデ", "汗だくで", "dripping with sweat", "Manner & State"),
    ("asette", "あせって", "アセッテ", "焦って", "in a frantic fluster", "Manner & State"),
    ("asoko de", "あそこで", "アソコデ", "彼処で", "over there", "Places & Spatial"),
    ("assari", "あっさり", "アッサリ", "あっさり", "lightly / plain / frank manner", "Onomatopoeia & Mimetic"),
    ("atatakaku", "あたたかく", "アタタカク", "暖かく", "warmly / cordially", "Manner & State"),
    ("ato de", "あとで", "アトデ", "後で", "afterwards / later on", "Time & Sequence"),
    ("ato kara", "あとから", "アトカラ", "後から", "behind / following shortly", "Time & Sequence"),
    ("atsuku", "あつく", "アツク", "熱く", "passionately / hot", "Degree & Extent"),
    ("awatede", "あわてて", "アワテテ", "慌てて", "in a flurried panic", "Manner & State"),
    ("ayauku", "あやうく", "アヤウク", "危うく", "barely / on the verge of disaster", "Condition & Logic"),

    # B
    ("baai ni yotte wa", "ばあいによっては", "バアイニヨッテワ", "場合によっては", "depending on circumstances", "Condition & Logic"),
    ("baba to", "ばばっと", "ババット", "ばばっと", "quick as a flash", "Onomatopoeia & Mimetic"),
    ("baki-baki", "ばきばき", "バキバキ", "バキバキ", "crunching / snapping / ripped physique", "Onomatopoeia & Mimetic"),
    ("bakuhatsu-teki ni", "ばくはつてきに", "バクハツテキニ", "爆発的に", "explosively / exponentially", "Degree & Extent"),
    ("bakuzen to", "ばくぜんと", "バクゼント", "漠然と", "vaguely / obscurely", "Manner & State"),
    ("ban-zen ni", "ばんぜんに", "バンゼンニ", "万全に", "flawlessly / thoroughly prepared", "Manner & State"),
    ("bannou ni", "ばんのうに", "バンノウニ", "万能に", "versatilely", "Manner & State"),
    ("barabara", "ばらばら", "バラバラ", "散り散り", "scattered / disjointed / apart", "Onomatopoeia & Mimetic"),
    ("bari-bari", "ばりばり", "バリバリ", "バリバリ", "working energetically / crunching", "Onomatopoeia & Mimetic"),
    ("basa-basa", "ばさばさ", "バサバサ", "バサバサ", "dry and rustling / flapping", "Onomatopoeia & Mimetic"),
    ("batan to", "ばたんと", "バタント", "バタンと", "slamming shut (door)", "Onomatopoeia & Mimetic"),
    ("batabata", "ばたばた", "バタバタ", "ばたばた", "flapping / scurrying busily", "Onomatopoeia & Mimetic"),
    ("batsu-gun ni", "ばつぐんに", "バツグンニ", "抜群に", "preeminently / outstandingly", "Degree & Extent"),
    ("batchiri", "ばっちり", "バッチリ", "バッチリ", "perfectly / spot on", "Onomatopoeia & Mimetic"),
    ("besshite", "べっして", "ベッシテ", "別して", "especially / above all", "Degree & Extent"),
    ("betsudan", "べつだん", "ベツダン", "別段", "particularly / especially (with neg)", "Degree & Extent"),
    ("betsuni", "べつに", "ベツニ", "別に", "not particularly / nothing special", "Degree & Extent"),
    ("bikkuri to", "びっくりと", "ビックリト", "吃驚と", "with great shock", "Manner & State"),
    ("biri-biri", "びりびり", "ビリビリ", "ビリビリ", "ripping / electric tingling", "Onomatopoeia & Mimetic"),
    ("bisho-bisho", "びしょびしょ", "ビショビショ", "びしょびしょ", "dripping soaked / drenched", "Onomatopoeia & Mimetic"),
    ("bita ichien", "びたいちえん", "ビタイチエン", "びた一文", "not even a red cent", "Degree & Extent"),
    ("bito to", "びとっと", "ビトット", "びとっと", "clinging wetly", "Onomatopoeia & Mimetic"),
    ("bocchan to", "ぼっちゃんと", "ボッチャント", "ぼっちゃんと", "with a plop in water", "Onomatopoeia & Mimetic"),
    ("boki-boki", "ぼきぼき", "ボキボキ", "ボキボキ", "cracking knuckles / snapping branches", "Onomatopoeia & Mimetic"),
    ("bonyari to", "ぼんやりと", "ボンヤリト", "ぼんやりと", "hazily / vacantly", "Onomatopoeia & Mimetic"),
    ("boso-boso", "ぼそぼそ", "ボソボソ", "ぼそぼそ", "muttering low / dry-textured", "Onomatopoeia & Mimetic"),
    ("bota-bota", "ぼたぼた", "ボタボタ", "ぼたぼた", "dripping in heavy drops", "Onomatopoeia & Mimetic"),
    ("bousou shite", "ぼうそうして", "ボウソウシテ", "暴走して", "running wildly out of control", "Manner & State"),
    ("buji ni", "ぶじに", "ブジニ", "無事に", "safely / without accident", "Manner & State"),
    ("buka-buka", "ぶかぶか", "ブカブカ", "ぶかぶか", "baggy / overly loose fitting", "Onomatopoeia & Mimetic"),
    ("bun-bun", "ぶんぶん", "ブンブン", "ぶんぶん", "buzzing / whirring loud", "Onomatopoeia & Mimetic"),
    ("bura-bura", "ぶらぶら", "ブラブラ", "ぶらぶら", "dangling / meandering leisurely", "Onomatopoeia & Mimetic"),
    ("buru-buru", "ぶるぶる", "ブルブル", "ブルブル", "shivering with cold or fright", "Onomatopoeia & Mimetic"),

    # C
    ("chanto", "ちゃんと", "チャント", "ちゃんと", "properly / neatly / reliably", "Manner & State"),
    ("chika-jika", "ちかぢか", "チカヂカ", "近々", "shortly / before long", "Time & Sequence"),
    ("chikagoro", "ちかごろ", "チカゴロ", "近頃", "lately / nowadays", "Time & Sequence"),
    ("chiku-chiku", "ちくちく", "チクチク", "チクチク", "prickling / stinging sensation", "Onomatopoeia & Mimetic"),
    ("chira-chira", "ちらちら", "チラチラ", "チラチラ", "fluttering / glancing repeatedly", "Onomatopoeia & Mimetic"),
    ("chira-ri to", "ちらりと", "チラリト", "ちらりと", "with a fleeting glance", "Onomatopoeia & Mimetic"),
    ("chiri-chiri", "ちりちり", "チリチリ", "チリチリ", "frizzled / sizzling heat", "Onomatopoeia & Mimetic"),
    ("chiri-bame te", "ちりばめて", "チリバメテ", "散りばめて", "inlaid with gems / studded", "Manner & State"),
    ("chitte mo", "ちっても", "チッテモ", "散っても", "even if scattered", "Manner & State"),
    ("choku-choku", "ちょくちょく", "チョクチョク", "ちょくちょく", "frequently / often", "Frequency & Habit"),
    ("chokusetsu", "ちょくせつ", "チョクセツ", "直接", "directly / face-to-face", "Manner & State"),
    ("chokuzen ni", "ちょくぜんに", "チョクゼンニ", "直前に", "immediately before", "Time & Sequence"),
    ("chokugo ni", "ちょくごに", "チョクゴニ", "直後に", "immediately after", "Time & Sequence"),
    ("chokkou shite", "ちょっこうして", "チョッコウシテ", "直行して", "heading straight to", "Manner & State"),
    ("choko-choko", "ちょこちょこ", "チョコチョコ", "ちょこちょこ", "toddling along / from time to time", "Onomatopoeia & Mimetic"),
    ("chotto", "ちょっと", "チョット", "一寸", "a little / for a moment", "Degree & Extent"),

    # D
    ("daba-daba", "だばだば", "ダバダバ", "だばだば", "pouring profusely / splashing", "Onomatopoeia & Mimetic"),
    ("daga", "だが", "ダガ", "だが", "however / but nevertheless", "Condition & Logic"),
    ("daibu", "だいぶ", "ダイブ", "大分", "considerably / a good deal", "Degree & Extent"),
    ("daini ni", "だいにに", "ダイニニ", "第二に", "secondly", "Time & Sequence"),
    ("daitai", "だいたい", "ダイタイ", "大体", "generally / roughly / approximately", "Degree & Extent"),
    ("daitan ni", "だいたんに", "ダイタンニ", "大胆に", "boldly / audaciously", "Manner & State"),
    ("dakedo", "だけど", "ダケド", "だけど", "however / even so", "Condition & Logic"),
    ("dakara", "だから", "ダカラ", "だから", "therefore / that is why", "Condition & Logic"),
    ("damatte", "だまって", "ダマッテ", "黙って", "without a word / in silence", "Manner & State"),
    ("dan-dan", "だんだん", "ダンダン", "段々", "gradually / step by step", "Degree & Extent"),
    ("danzen", "だんぜん", "ダンゼン", "断然", "by far / hands down", "Degree & Extent"),
    ("dara-dara", "だらだら", "ダラダラ", "だらだら", "sluggishly / lazily / dripping", "Onomatopoeia & Mimetic"),
    ("de", "で", "デ", "で", "and then / so", "Condition & Logic"),
    ("demo", "でも", "デモ", "でも", "but / however / even so", "Condition & Logic"),
    ("doko demo", "どこでも", "ドコデモ", "何処でも", "anywhere / everywhere", "Places & Spatial"),
    ("doko ka de", "どこかで", "ドコカデ", "何処かで", "somewhere or other", "Places & Spatial"),
    ("doki-doki", "どきどき", "ドキドキ", "ドキドキ", "heart pounding / with anticipation", "Onomatopoeia & Mimetic"),
    ("dokkiri to", "どっきりと", "ドッキリト", "どっきりと", "jolted with shock", "Onomatopoeia & Mimetic"),
    ("don-don", "どんどん", "ドンドン", "どんどん", "rapidly / drumming / continuously", "Degree & Extent"),
    ("dondon to", "どんどんと", "ドンドント", "どんどんと", "steadily rolling onward", "Degree & Extent"),
    ("doori de", "どうりで", "ドウリデ", "道理で", "no wonder / that explains it", "Condition & Logic"),
    ("doushite", "どうして", "ドウシテ", "如何して", "why / for what reason", "Condition & Logic"),
    ("doushite mo", "どうしても", "ドウシテモ", "どうしても", "no matter what / inevitably", "Condition & Logic"),
    ("douka", "どうか", "ドウカ", "どうか", "please / somehow", "Condition & Logic"),
    ("doumo", "どうも", "ドウモ", "どうも", "somehow / thanks / very", "Degree & Extent"),
    ("doyadoya", "どやどや", "ドヤドヤ", "どやどや", "in a boisterous throng", "Onomatopoeia & Mimetic"),

    # E
    ("eikyuu ni", "えいきゅうに", "エイキュウニ", "永久に", "permanently / into eternity", "Time & Sequence"),
    ("etsetora", "えとせとら", "エトセトラ", "エトセトラ", "et cetera / and so forth", "Condition & Logic"),

    # F
    ("fui ni", "ふいに", "フイニ", "不意に", "unexpectedly / abruptly", "Time & Sequence"),
    ("fukaku", "ふかく", "フカク", "深く", "deeply / profoundly", "Degree & Extent"),
    ("fukashigi ni", "ふかしぎに", "フカシギニ", "不可思議に", "mysteriously", "Manner & State"),
    ("fuku-fuku", "ふくふく", "フクフク", "ふくふく", "plump and happy-faced", "Onomatopoeia & Mimetic"),
    ("fuman-sou ni", "ふまんそうに", "フマンソウニ", "不満そうに", "discontentedly", "Manner & State"),
    ("funwari", "ふんわり", "フンワリ", "ふんわり", "softly / gently floating", "Onomatopoeia & Mimetic"),
    ("fura-fura", "ふらふら", "フラフラ", "ふらふら", "wobbly / dizzy / wandering", "Onomatopoeia & Mimetic"),
    ("furi-furi", "ふりふり", "フリフリ", "フリフリ", "wagging / frilly shake", "Onomatopoeia & Mimetic"),
    ("furu-furu", "ふるふる", "フルフル", "フルフル", "quivering / trembling lightly", "Onomatopoeia & Mimetic"),
    ("futatabi", "ふたたび", "フタタビ", "再び", "once again / a second time", "Frequency & Habit"),
    ("futo", "ふと", "フト", "不図", "casually / inadvertently", "Time & Sequence"),
    ("futsuu ni", "ふつうに", "フツウニ", "普通に", "normally / ordinarily", "Manner & State"),

    # G
    ("gachi-gachi", "がちがち", "ガチガチ", "ガチガチ", "stiff with tension / teeth chattering", "Onomatopoeia & Mimetic"),
    ("gakkari to", "がっかりと", "ガッカリト", "がっかりと", "crestfallen / disheartened", "Onomatopoeia & Mimetic"),
    ("gaku-to", "がくっと", "ガクット", "がくっと", "dropping sharply / buckling knees", "Onomatopoeia & Mimetic"),
    ("gan-gan", "がんがん", "ガンガン", "ガンガン", "banging loudly / throbbing headache", "Onomatopoeia & Mimetic"),
    ("gara-gara", "がらがら", "ガラガラ", "ガラガラ", "rattling / completely empty (train)", "Onomatopoeia & Mimetic"),
    ("gari-gari", "がりがり", "ガリガリ", "ガリガリ", "scratching / skinny / hard crunch", "Onomatopoeia & Mimetic"),
    ("gashin to", "がしんと", "ガシント", "ガシンと", "clashing heavily", "Onomatopoeia & Mimetic"),
    ("gasshiri", "がっしり", "ガッシリ", "がっしり", "solidly built / sturdy", "Onomatopoeia & Mimetic"),
    ("gekijou-teki ni", "げきじょうてきに", "ゲキジョウテキニ", "劇的に", "dramatically / theatrically", "Degree & Extent"),
    ("gen-ni", "げんに", "ゲンニ", "現に", "actually / as a matter of fact", "Condition & Logic"),
    ("genmitsu ni", "げんみつに", "ゲンミツニ", "厳密に", "strictly speaking / precisely", "Manner & State"),
    ("giku-shaku", "ぎくしゃく", "ギクシャク", "ぎくしゃく", "awkwardly strained / stiff", "Onomatopoeia & Mimetic"),
    ("gira-gira", "ぎらぎら", "ギラギラ", "ギラギラ", "glaring dazzlingly (sunlight)", "Onomatopoeia & Mimetic"),
    ("giri-giri", "ぎりぎり", "ギリギリ", "ぎりぎり", "at the eleventh hour / on the brink", "Time & Sequence"),
    ("gishi-gishi", "ぎしぎし", "ギシギシ", "ギシギシ", "creaking floorboards / packed tight", "Onomatopoeia & Mimetic"),
    ("gisshiri", "ぎっしり", "ギッシリ", "ぎっしり", "densely crammed full", "Onomatopoeia & Mimetic"),
    ("goku", "ごく", "ゴク", "極", "extremely / quite / minimally", "Degree & Extent"),
    ("goku-goku", "ごくごく", "ゴクゴク", "ごくごく", "gulping down liquid", "Onomatopoeia & Mimetic"),
    ("goro-goro", "ごろごろ", "ゴロゴロ", "ごろごろ", "rumbling thunder / rolling about", "Onomatopoeia & Mimetic"),
    ("gucha-gucha", "ぐちゃぐちゃ", "グチャグチャ", "ぐちゃぐちゃ", "squishy / soggy / messy", "Onomatopoeia & Mimetic"),
    ("gungun", "ぐんぐん", "グングン", "ぐんぐん", "surging forward / rapid growth", "Degree & Extent"),
    ("gussuri", "ぐっすり", "グッスリ", "ぐっすり", "sleeping soundly / deeply", "Onomatopoeia & Mimetic"),
    ("gutto", "ぐっと", "グット", "ぐっと", "firmly / emotionally touched / gulp", "Degree & Extent"),
    ("guuzen", "ぐうぜん", "グウゼン", "偶然", "by sheer coincidence / accidentally", "Condition & Logic"),

    # H
    ("hachikire-bakari ni", "はちきればかりに", "ハチキレバカリニ", "はち切れんばかりに", "bursting at the seams", "Degree & Extent"),
    ("hade ni", "はでに", "ハデニ", "派手に", "flamboyantly / spectacularly", "Manner & State"),
    ("hageshiku", "はげしく", "ハゲシク", "激しく", "violently / fiercely / passionately", "Degree & Extent"),
    ("hai-hai to", "はいはいと", "ハイハイト", "はいはいと", "readily assenting", "Manner & State"),
    ("hakkiri", "はっきり", "ハッキリ", "はっきり", "clearly / distinct / plain", "Manner & State"),
    ("haku-ryoku man-ten de", "はくりょくまんてんで", "ハクリョクマンテンデ", "迫力満点で", "with great impact / dynamism", "Degree & Extent"),
    ("han-pa naku", "はんぱなく", "ハンパナク", "半端なく", "insanely / without halfway measures", "Degree & Extent"),
    ("hanbun", "はんぶん", "ハンブン", "半分", "by half / half and half", "Degree & Extent"),
    ("haru-baru", "はるばる", "ハルバル", "遥々", "all the way from afar", "Places & Spatial"),
    ("haruka ni", "はるかに", "ハルカニ", "遥かに", "by far / much more / remote", "Degree & Extent"),
    ("hasande", "はさんで", "ハサンデ", "挟んで", "across / with something in between", "Places & Spatial"),
    ("hashi kara hashi made", "はしからはしまです", "ハシカラハシマデ", "端から端まで", "from end to end", "Places & Spatial"),
    ("haya-baya to", "はやばやと", "ハヤバヤト", "早々と", "bright and early / ahead of time", "Time & Sequence"),
    ("hayaku", "はやく", "ハヤク", "早く", "early / briskly / hurry", "Time & Sequence"),
    ("hayakumo", "はやくも", "ハヤクモ", "早くも", "already / as early as", "Time & Sequence"),
    ("hazukashikute", "はずかしくて", "ハズカシクテ", "恥ずかしくて", "shamefacedly", "Manner & State"),
    ("heiki de", "へいきで", "ヘイキデ", "平気で", "nonchalantly / without batting an eye", "Manner & State"),
    ("heibon ni", "へいぼんに", "ヘイボンニ", "平凡に", "unremarkably / conventionally", "Manner & State"),
    ("heta suruto", "へたすると", "ヘタスルト", "下手すると", "if things go poorly / at worst", "Condition & Logic"),
    ("hidoku", "ひどく", "ヒドク", "酷く", "terribly / exceedingly / severely", "Degree & Extent"),
    ("hie-hie to", "ひえひえと", "ヒエヒエト", "冷え冷えと", "chillily / bleakly", "Weather & Climate"),
    ("hikari kagayaki nagara", "ひかりかがやきながら", "ヒカリカガヤキナガラ", "光り輝きながら", "radiantly shining", "Onomatopoeia & Mimetic"),
    ("hikkiri-nashi ni", "ひっきりなしに", "ヒッキリナシニ", "ひっきりなしに", "incessantly / non-stop", "Frequency & Habit"),
    ("hiku-hiku", "ひくひく", "ヒクヒク", "ひくひく", "twitching / fluttering", "Onomatopoeia & Mimetic"),
    ("hima sae areba", "ひまさあれば", "ヒマサエアレバ", "暇さえあれば", "whenever there is free time", "Frequency & Habit"),
    ("hisshori to", "ひっそりと", "ヒッソリト", "ひっそりと", "quietly / secludedly", "Onomatopoeia & Mimetic"),
    ("hitasura", "ひたすら", "ヒタスラ", "只管", "earnestly / solely / intently", "Manner & State"),
    ("hito-bito ni", "ひとびとに", "ヒトビトニ", "人々に", "among the populace", "Places & Spatial"),
    ("hito-e ni", "ひとえに", "ヒトエニ", "偏に", "earnestly / entirely owing to", "Degree & Extent"),
    ("hito-mazu", "ひとまず", "ヒトマズ", "一先ず", "for the time being / for now", "Time & Sequence"),
    ("hito-touri", "ひととおり", "ヒトトオリ", "一通り", "roughly / in a general way", "Degree & Extent"),
    ("hitori de", "ひとりで", "ヒトリデ", "一人で", "all by oneself / solo", "Manner & State"),
    ("hitori-de ni", "ひとりでに", "ヒトリデニ", "独りでに", "spontaneously / on its own", "Manner & State"),
    ("hitsu-zen-teki ni", "ひつぜんてきに", "ヒツゼンテキニ", "必然的に", "inevitably / of necessity", "Condition & Logic"),
    ("hitsuyou ni", "ひつように", "ヒツヨウニ", "必要に", "necessarily / out of need", "Manner & State"),
    ("hodo-hodo ni", "ほどほどに", "ホドホドニ", "程々に", "in moderation / reasonably", "Degree & Extent"),
    ("honki de", "ほんきで", "ホンキデ", "本気で", "in all seriousness / earnest", "Manner & State"),
    ("hontou ni", "ほんとうに", "ホントウニ", "本当に", "genuinely / truly / honestly", "Degree & Extent"),
    ("honto wa", "ほんとは", "ホントワ", "本当は", "in truth / actually", "Condition & Logic"),
    ("hon-no", "ほんの", "ホンノ", "本の", "mere / only / just a touch", "Degree & Extent"),
    ("horahora", "ほらほら", "ホラホラ", "ほらほら", "look here! / see now!", "Condition & Logic"),
    ("horori to", "ほろりと", "ホロリト", "ほろりと", "moved to tears / melting soft", "Onomatopoeia & Mimetic"),
    ("hotondo", "ほとんど", "ホトンド", "殆ど", "almost / nearly / practically all", "Degree & Extent"),
    ("hotto", "ほっと", "ホット", "ほっと", "sighing with relief", "Onomatopoeia & Mimetic"),

    # I
    ("ichi-ban", "いちばん", "イチバン", "一番", "most / first / best", "Degree & Extent"),
    ("ichi-dan to", "いちだんと", "イチダント", "一段と", "even more so / all the more", "Degree & Extent"),
    ("ichi-do ni", "いちどに", "イチドニ", "一度に", "all at once / simultaneously", "Time & Sequence"),
    ("ichi-ou", "いちおう", "イチオウ", "一応", "more or less / tentatively", "Degree & Extent"),
    ("ichi-ri de", "いちにんで", "イチニンデ", "一人で", "singly", "Manner & State"),
    ("ichinichi juu", "いちにちじゅう", "イチニチジュウ", "一日中", "all day long", "Time & Sequence"),
    ("idon to", "いどんと", "イドント", "挑んと", "bravely trying", "Manner & State"),
    ("igai ni mo", "いがいに", "イガイニ", "意外に", "surprisingly / unexpectedly", "Condition & Logic"),
    ("ikani", "いかに", "イカニ", "如何に", "how / in what manner", "Manner & State"),
    ("ikanimo", "いかにも", "イカニモ", "如何にも", "truly / indeed / looks so much", "Degree & Extent"),
    ("ikari o komete", "いかりをこめて", "イカリヲコメテ", "怒りを込めて", "wrathfully / indignantly", "Manner & State"),
    ("iki-iki to", "いきいきと", "イキイキト", "生き生きと", "vibrantly / vividly", "Onomatopoeia & Mimetic"),
    ("ikinari", "いきなり", "イキナリ", "行き成り", "all of a sudden / out of the blue", "Time & Sequence"),
    ("ikkou ni", "いっこうに", "イッコウニ", "一向に", "not at all (with negative)", "Degree & Extent"),
    ("ikura ka", "いくらか", "イクラカ", "幾らか", "somewhat / to some degree", "Degree & Extent"),
    ("ikura nanto ittemo", "いくらなんといっても", "イクラナントイッテモ", "幾ら何と言っても", "say what you will / after all", "Condition & Logic"),
    ("ikura demo", "いくらでも", "イクラデモ", "幾らでも", "as much as one likes", "Degree & Extent"),
    ("ima ni mo", "いまにも", "イマニモ", "今にも", "at any moment now", "Time & Sequence"),
    ("ima sara", "いまさら", "イマサラ", "今更", "at this late hour / now", "Time & Sequence"),
    ("ima sugu", "いますぐ", "イマスグ", "今すぐ", "right this instant", "Time & Sequence"),
    ("imadani", "いまだに", "イマダニ", "未だに", "even now / still yet", "Time & Sequence"),
    ("inori nagara", "いのりながら", "イノリナガラ", "祈りながら", "prayerfully", "Manner & State"),
    ("ippai", "いっぱい", "イッパイ", "一杯", "full to the brim / plenty", "Degree & Extent"),
    ("ippou de", "いっぽうで", "イッポウデ", "一方で", "on the flip side / meanwhile", "Condition & Logic"),
    ("ippo ippo", "いっぽいっぽ", "イッポイッポ", "一歩一歩", "step by deliberate step", "Manner & State"),
    ("irai-ra shite", "いらいらして", "イライラシテ", "苛々して", "irritably", "Onomatopoeia & Mimetic"),
    ("iro-iro to", "いろいろと", "イロイロト", "色々と", "in numerous ways / variedly", "Manner & State"),
    ("isshou-kenmei", "いっしょうけんめい", "イッショウケンメイ", "一生懸命", "with all one's might / hard", "Manner & State"),
    ("isshoni", "いっしょに", "イッショニ", "一緒に", "together / alongside", "Manner & State"),
    ("isso", "いっそ", "イッソ", "いっそ", "rather / sooner", "Condition & Logic"),
    ("itsu no ma ni ka", "いつのまにか", "イツノマニカ", "何時の間にか", "before one realizes / unawares", "Time & Sequence"),
    ("itsu demo", "いつでも", "イツデモ", "何時でも", "anytime / whenever", "Frequency & Habit"),
    ("itsu ka", "いつか", "イツカ", "何時か", "someday / at one time", "Time & Sequence"),
    ("itsumo", "いつも", "イツモ", "何時も", "always / constantly / habitually", "Frequency & Habit"),
    ("iya-iya", "いやいや", "イヤイヤ", "嫌々", "reluctantly / shaking head", "Manner & State"),

    # J
    ("ja", "じゃ", "ジャ", "じゃ", "well then / in that case", "Condition & Logic"),
    ("jabu-jabu", "じゃぶじゃぶ", "ジャブジャブ", "じゃぶじゃぶ", "splashing water copiously", "Onomatopoeia & Mimetic"),
    ("jashin naku", "じゃしんなく", "ジャシンナク", "邪心なく", "without malicious intent", "Manner & State"),
    ("jibou-jiki ni", "じぼうじきに", "ジボウジキニ", "自暴自棄に", "desperately / in self-abandon", "Manner & State"),
    ("jibun de", "じぶんで", "ジブンデ", "自分で", "by oneself / on one's own", "Manner & State"),
    ("jichi-teki ni", "じちてきに", "ジチテキニ", "自治的に", "autonomously", "Manner & State"),
    ("jiki ni", "じきに", "ジキニ", "直に", "soon / directly / shortly", "Time & Sequence"),
    ("jikkuri", "じっくり", "ジックリ", "じっくり", "deliberately / taking time", "Manner & State"),
    ("jiko ni yori", "じこにより", "ジコニヨリ", "事故により", "owing to an incident", "Condition & Logic"),
    ("jissai ni", "じっさいに", "ジッサイニ", "実際に", "in actual reality / practically", "Manner & State"),
    ("jitsu wa", "じつは", "ジツワ", "実は", "as a matter of fact / actually", "Condition & Logic"),
    ("jiwajiwa", "じわじわ", "ジワジワ", "じわじわ", "slowly but steadily / oozing", "Onomatopoeia & Mimetic"),
    ("joji ni", "じょじょに", "ジョジョニ", "徐々に", "step by step / gradually", "Degree & Extent"),
    ("joubu ni", "じょうぶに", "ジョウブニ", "丈夫に", "sturdily / robustly", "Manner & State"),
    ("jouzu ni", "じょうずに", "ジョウズニ", "上手に", "skillfully / adeptly", "Manner & State"),
    ("juubun ni", "じゅうぶんに", "ジュウブンニ", "十分に", "amply / thoroughly / fully", "Degree & Extent"),
    ("juukou ni", "じゅうこうに", "ジュウコウニ", "重厚に", "profoundly / with heavy dignity", "Manner & State"),

    # K
    ("ka koto naku", "かくことなく", "カクコトナク", "欠くことなく", "without fail / unflaggingly", "Frequency & Habit"),
    ("kaesu gaesu mo", "かえすがえすも", "カエスガエスモ", "返す返すも", "repeatedly / over and over", "Frequency & Habit"),
    ("kaette", "かえって", "カエッテ", "却って", "on the contrary / instead", "Condition & Logic"),
    ("kakkiri", "かっきり", "カッキリ", "かっきり", "precisely on time", "Time & Sequence"),
    ("kakujitsu ni", "かくじつに", "カクジツニ", "確実に", "unfailingly / surely", "Condition & Logic"),
    ("kamawazu", "かまわず", "カマワズ", "構わず", "regardless / without caring", "Manner & State"),
    ("kanarazu", "かならず", "カナラズ", "必ず", "without exception / definitely", "Condition & Logic"),
    ("kanari", "かなり", "カナリ", "可成", "considerably / pretty much", "Degree & Extent"),
    ("kanzen ni", "かんぜんに", "カンゼンニ", "完全に", "wholly / completely / perfectly", "Degree & Extent"),
    ("kasa-kasa", "かさかさ", "カサカサ", "かさかさ", "rustling dryly", "Onomatopoeia & Mimetic"),
    ("kasuka ni", "かすかに", "カスカニ", "微かに", "faintly / dimly / vaguely", "Degree & Extent"),
    ("katsute", "かつて", "カツテ", "嘗て", "formerly / once upon a time", "Time & Sequence"),
    ("kawa-kawa", "かわかわ", "カワカワ", "かわかわ", "dry-sounding laugh", "Onomatopoeia & Mimetic"),
    ("kesshite", "けっして", "ケッシテ", "決して", "by no means / never (neg)", "Degree & Extent"),
    ("ki-garu ni", "きがるに", "キガルニ", "気軽に", "lightheartedly / feel free to", "Manner & State"),
    ("ki-pari", "きっぱり", "キッパリ", "きっぱり", "decisively / flatly (refuse)", "Manner & State"),
    ("kiri-kiri", "きりきり", "キリキリ", "きりきり", "sharp stabbing pain / creaking", "Onomatopoeia & Mimetic"),
    ("kitto", "きっと", "キット", "屹度", "surely / almost certainly", "Condition & Logic"),
    ("koko de", "ここで", "ココデ", "此処で", "right here", "Places & Spatial"),
    ("koko-kara", "ここから", "ココカラ", "此処から", "starting from here", "Places & Spatial"),
    ("kokoro kara", "こころから", "ココロカラ", "心から", "from the bottom of one's heart", "Manner & State"),
    ("komakaku", "こまかく", "コマカク", "細かく", "in minute detail", "Manner & State"),
    ("kon-ya", "こんや", "コンヤ", "今夜", "tonight", "Time & Sequence"),
    ("kondo", "こんど", "コンド", "今度", "this time / next time", "Time & Sequence"),
    ("kono goro", "このごろ", "コノゴロ", "この頃", "these days / lately", "Time & Sequence"),
    ("kono saki", "このさき", "コノサキ", "この先", "from now on / up ahead", "Time & Sequence"),
    ("kossori", "こっそり", "コッソリ", "こっそり", "stealthily / in secret", "Manner & State"),
    ("koto ni", "ことに", "コトニ", "殊に", "especially / notably", "Degree & Extent"),
    ("koto-koto", "ことこと", "コトコト", "ことこと", "simmering gently in pot", "Onomatopoeia & Mimetic"),
    ("koushitie", "こうして", "コウシテ", "こうして", "in this way / thus", "Manner & State"),
    ("kuwashiku", "くわしく", "クワシク", "詳しく", "thoroughly / in detail", "Manner & State"),
    ("kyuu ni", "きゅうに", "キュウニ", "急に", "all of a sudden / abruptly", "Time & Sequence")
]

with open('src/data/vocab/n5_vocab.json', 'r', encoding='utf-8') as f:
    data = json.load(f)

existing = {item['romaji'].lower(): item for item in data['adverbs']}

for item in raw_adverbs:
    key = item[0].lower()
    if key not in existing:
        existing[key] = {
            "alphabet": item[0][0].upper(),
            "romaji": item[0],
            "hiragana": item[1],
            "katakana": item[2],
            "kanji": item[3],
            "meaning": item[4],
            "topic": item[5]
        }

print(f"Current adverbs: {len(existing)}")
